### ISSUE TITLE
tokio-signal: windows DriverTask never terminates

### ISSUE THREAD

**Issue by ipetkov** [tokio-rs/tokio#1000]
The Windows implementation of `tokio-signal` uses a `DriverTask` to deliver any signals to leaf futures. Currently this task never terminates, which can cause deadlocks if used with `block_on_all`

https://github.com/tokio-rs/tokio/blob/9c5cad037fd78adb087bc4734f7670d5732122c5/tokio-signal/src/windows.rs#L198-L210

As a fix we should do something similar to the Unix implementation where either each leaf future acts as a "driver", or terminate the driver if there are no listeners

Extra context around this issue can be found [here](https://github.com/tokio-rs/tokio/pull/1136#issuecomment-502407872)

**Comment by EliSnow** [comment]
I am currently facing this issue. It is also manifest when used with the commonly used `tokio::run`.

**Comment by ipetkov** [comment]
Adding to v0.2 milestone, I'd like to get this issue fixed (and the experience and implementation between Unix and Windows largely unified) before the next major release
