### ISSUE TITLE
trace: Remove default level from `span!` macro

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#1013]
We've determined that having the `span!` macro default to the `TRACE` level is probably not ideal (see discussion on #952).

Instead, the `span!` macro should behave like the `event!` macro, and require an explicit level to be provided. In addition, we should add new `error_span!`, `warn_span!`, `info_span!`, `debug_span!`, and `trace_span!` macros that behave analogously to the existing event macros (setting a certain level).

This will break most existing code that uses spans, so we should get this change in prior to `tokio-trace` 0.1. In addition, we'll want to update the crates in the [nursery](https://github.com/tokio-rs/tokio-trace-nursery) that use the span macro.

**Comment by jxs** [comment]
i can take this one 🙂

**Comment by hawkw** [comment]
@jxs great, let me know if you get stuck on anything!

**Comment by jxs** [comment]
when only the name is provided, should the behavior be:
`span!(level: tokio_trace::Level::TRACE, "name")` or `span!(tokio_trace::Level::TRACE, "name")` ?

**Comment by hawkw** [comment]
I think the consensus on #952 was that the `span!` macro should _require_ a level, like the `event!` macro does (but, @LucioFranco and @carllerche, correct me if i'm wrong). So, it should probably require the first argument to be a level, rather than using a named argument for the level.

**Comment by LucioFranco** [comment]
@hawkw 👍 for me on that, and then introduce `trace_span!`, `info_span!`, etc
