### ISSUE TITLE
Broken link to example source code on web site (https://tokio.rs)

### ISSUE THREAD

**Issue by JoshLambda** [tokio-rs/tokio#1016]
Link to the `chat server example` source code is broken on web site https://tokio.rs .
Broken link is at the complete bottom of [this web page](https://tokio.rs/docs/going-deeper/chat/) and returns a 404 on github.

**Comment by kpp** [comment]
> The full code can be found here.

The link leads to https://github.com/tokio-rs/tokio/blob/master/tokio/examples/chat.rs which is 200 on github

**Comment by JoshLambda** [comment]
Weird... the link is working now on my side too. Sorry for the inconvenience.
