### ISSUE TITLE
trace: Allow separator(s?) in field names

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#1018]
A conversation with @carllerche and @Ralith on gitter brought up the consideration that it would be nice to allow separators in `tokio-trace` field names. This would support a convention of names like `peer.ip` and so on.

In `tokio-trace`'s macros, field names are currently required to be single `$ident` fragments. We should revisit this.

@Ralith suggested changing the macros to match something like
```rust
 $($part:ident).+
```
which would allow the use of `.` as a separator.

An alternative which just occurred to me right now is changing the `ident` matcher to a `path`, which would allow the use of `::` as a separator.

**Comment by davidbarsky** [comment]
If I recall correctly, Honeycomb and my CloudWatch Logs Insights use a JSONPath-like syntax, which results in the `.` separator being used.


________________________________

**Comment by LucioFranco** [comment]
@davidbarsky does it take the flat map of fields and structures them?

**Comment by hawkw** [comment]
> @davidbarsky does it take the flat map of fields and structures them?

@LucioFranco I think I see where you're going with this --- a subscriber would definitely be able to report data to an aggregator that supports structuring values like that based on the presence of a separator character! As a side note, this is (IMO) another argument in favour of having a conventional separator char rather than allowing arbitrary strings (so, possibly relevant to https://github.com/tokio-rs/tokio/pull/1022#issuecomment-478711454).

**Comment by LucioFranco** [comment]
@hawkw right, I think out of the box we could support this style, and I know for a fact that the work product im working on which is a log aggregator uses this style. 😄
