### ISSUE TITLE
tokio-fs: feature request: Add support for xattr

### ISSUE THREAD

**Issue by hnakamur** [tokio-rs/tokio#1023]
## Version

```
$ cargo tree | grep tokio
tokio-fs v0.1.6 (/home/hnakamur/.ghq/github.com/tokio-rs/tokio/tokio-fs)
├── tokio-io v0.1.11
├── tokio-threadpool v0.1.13
│   └── tokio-executor v0.1.7
├── tokio v0.1.18
│   ├── tokio-codec v0.1.1
│   │   └── tokio-io v0.1.11 (*)
│   ├── tokio-current-thread v0.1.6
│   │   └── tokio-executor v0.1.7 (*)
│   ├── tokio-executor v0.1.7 (*)
│   ├── tokio-fs v0.1.6
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-threadpool v0.1.13 (*)
│   │   └── tokio-io v0.1.11 (*)
│   ├── tokio-io v0.1.11 (*)
│   ├── tokio-reactor v0.1.8
│   │   ├── tokio-executor v0.1.7 (*)
│   │   └── tokio-io v0.1.11 (*)
│   ├── tokio-sync v0.1.4
│   ├── tokio-tcp v0.1.3
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-reactor v0.1.8 (*)
│   ├── tokio-threadpool v0.1.13 (*)
│   ├── tokio-timer v0.2.10
│   │   └── tokio-executor v0.1.7 (*)
│   ├── tokio-trace-core v0.1.0
│   ├── tokio-udp v0.1.3
│   │   ├── tokio-codec v0.1.1 (*)
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-reactor v0.1.8 (*)
│   └── tokio-uds v0.2.5
│       ├── tokio-codec v0.1.1 (*)
│       ├── tokio-io v0.1.11 (*)
│       └── tokio-reactor v0.1.8 (*)
├── tokio-codec v0.1.1 (*)
└── tokio-io v0.1.11 (*)
```

## Platform

```
Linux sunshine3 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Subcrates

tokio-fs

## Description

I'd like to use [xattr](https://crates.io/crates/xattr) crate with tokio-fs.
Here is my attempt to add functions for xattr.
https://github.com/tokio-rs/tokio/compare/master...hnakamur:xattr

Can I send a pull request from that branch?

**Comment by carllerche** [comment]
Thanks for the thought.

Generally, exposing "non blocking" functionality for external crates should be done in a standalone crate (for example, tokio-xattr). I would recommend starting with that. At that point, we can consider adding xattr support directly to tokio. To do that, the `xattr` crate would have to become an implementation detail.

I'm going to close this issue for now as the next steps are to put together a `tokio-xattr` crate to illustrate the ideas and let the API mature there, but feel free to comment here and I will see it.

**Comment by hnakamur** [comment]
Thanks for the comment. I'll create `tokio-xattr` as an external crate.

Could you make [`blocking_io`](https://github.com/tokio-rs/tokio/blob/4271a9cd8dc8d43249f5a4febe5fea19f4dca971/tokio-fs/src/lib.rs#L80) public?
To tell the truth, at first I tried to create an external crate, but I couldn't since `blocking_io` is private.

Can I name it `tokio-xattr` or should I use a different name?

**Comment by carllerche** [comment]
I'd rather keep it private for now. It is pretty easy to include as a private fn in your crate.

You can name it `tokio-xattr`.

**Comment by hnakamur** [comment]
I created https://github.com/hnakamur/tokio-xattr as an external crate.
Could you take a look?
Thanks!

**Comment by stjepang** [comment]
I took a look at this crate and it looks good to me! Would be happy to review a PR moving it into Tokio.

We should probably put the code inside `tokio-fs` behind a `#[cfg(unix)]` attribute rather than introduce a new `tokio-attr` crate.

**Comment by carllerche** [comment]
@stjepang I mostly want to hold off merging it into Tokio **immediately** until other inflight work is completed and the crate has an opportunity to mature a bit.

**Comment by carllerche** [comment]
And yes, I also would want to avoid adding a public dependency on an external crate.
