### ISSUE TITLE
Timeout consumes inner even it hadn't used

### ISSUE THREAD

**Issue by DenisKolodin** [tokio-rs/tokio#1034]
`Timer` consumes inner value even if it hadn't used so you can't get back the stream with this code:

```
let (tx, rx) = mpsc::channel(10);

let one_item = rx.into_future();

let with_timeout = Timeout::new(one_item, Duration::from_millis(1));

match with_timeout.wait() {
    Ok((item, stream)) => { }
    Err(err) => { /* can't get stream back here ((( */ }
}
```

**Comment by carllerche** [comment]
The strategy here would be to make sure `Timeout` has an `into_inner` fn, then write a combinator that includes the original item on error.

**Comment by qm3ster** [comment]
It exists: [`tokio::timer::timeout::Error::into_inner() -> Option<E>`](https://docs.rs/tokio/0.1/tokio/timer/timeout/struct.Error.html#method.into_inner)

**Comment by DenisKolodin** [comment]
That's what I thought at first, but it's not the same. This function returns inner error that occured in a stream and I can take stream in that case, but if I have a timeout error this method loose the stream instance forever and returns `None`.

**Comment by qm3ster** [comment]
@DenisKolodin Great new development you'll be happy to hear about:
[`impl<'a, S: Stream + ?Sized> Stream for &'a mut S`](https://docs.rs/tokio/0.1.18/tokio/prelude/trait.Sink.html#impl-Sink-4)
Which means you don't have to give your `Stream` away!
```rust
let (tx, mut rx) = mpsc::channel(10);

let with_timeout = (&mut rx).into_future().timeout(Duration::from_millis(1));

match with_timeout.wait() {
    Ok((item, _)) => { }
    Err(err) => { /* Not sure what to do here, I use async/await, which simplifies lifetimes */ }
}
```

**Comment by DenisKolodin** [comment]
@qm3ster The masterpiece! :smile: :+1: Now it's solved! Thank you!

**Comment by qm3ster** [comment]
I actually found this out about `Sink`, but guessed the same is true for `Stream`, and it is :smile: 
ended up changing
```rust
    async fn sreq(&mut self, req: ZnpReq) -> ParsingResult<ZnpRes> {
        let mut tx_lock = await!(self.tx.lock());
        let send = tx_lock.take().unwrap().send(req);
        let tx = await!(send).unwrap();
        *tx_lock = Some(tx);
    }
```
to just
```rust
    async fn sreq(&mut self, req: ZnpReq) -> ParsingResult<ZnpRes> {
        let mut tx_lock = await!(self.tx.lock());
        let send = Stream::send(&mut *tx_lock, req);
        await!(send).unwrap();
    }
