### ISSUE TITLE
Question about timeout logic

### ISSUE THREAD

**Issue by Vbozovic** [tokio-rs/tokio#1035]
Hi,
im new to tokio and rust in general and i have question on how to make a piece of code to run for 
**at most** `timeout`.In other words i need a piece of code to be interupted if i doesen't complete in the given time constraint. Currently i have the following, but i'm missing something. The timeout never happens and the execution is stuck in the `loop` part of the lazy future.

```
use std::time::Duration;
use futures::future;
use tokio::io::Error;
use tokio::prelude::*;
use tokio::runtime::current_thread::Runtime;

fn main(){
    let timeout: u64 = 1000;
    let mut runtime = Runtime::new().unwrap();
    let req_timeout = future::lazy(|| -> Result<String, Error>{
        println!("Start expensive");
        loop {
            //some expensive task

        }
        Ok("finished task".to_string())
    }).timeout(Duration::from_millis(timeout));
    let result = runtime.block_on(req_timeout);
    match result {
        Ok(_str) =>{println!("Task finished")},
        Err(_) =>{println!("Task interupted")}
    }

}
```
Can anyone tell me what i'm doing wrong, and how to fix it ?

**Comment by Stargateur** [comment]
Cross stack-overflow [question](https://stackoverflow.com/questions/55516235/how-can-i-make-a-piece-of-running-code-timeout)

**Comment by Vbozovic** [comment]
The question has been answered [here](https://stackoverflow.com/questions/55516235/how-can-i-make-a-piece-of-running-code-timeout)
