### ISSUE TITLE
trace-core: Add a function to invalidate and rebuild cached interest

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#1038]
Currently, `tokio-trace-core` permits `Subscriber`s to indicate that they are "always", "sometimes", or "never" interested in a particular callsite. When "always" or "never" is returned, then the interest is cached and the subscriber will not be asked again about that callsite. This is much more efficient than requiring the filter to be re-evaluated every time the callsite is hit.

However, if a subscriber wishes to change its filter configuration dynamically at runtime, it cannot benefit from this caching. Instead, it must always return `Interest::sometimes`.  Even when filters change very infrequently, they must still always be re-evaluated every time.

In order to support a use-case where subscribers may change their filter configuration at runtime (e.g. https://github.com/tokio-rs/tokio-trace-nursery/issues/42#issuecomment-480393443), but do so infrequently, we should consider introducing a new function to invalidate the cached interest. This would iterate over all the callsites in the registry, call `Callsite::clear_interest`, and then call `register_callsite` again on all the subscribers in the registry that are still active, providing the new interests to the callsite. This would allow the interests to be cached, but also support dynamically changing filter configurations.

It's worth noting that such an operation is likely to be fairly slow, it requires a number of iterations equal to the number of callsites times the number of subscribers. However, this still is probably much more efficient than re-evaluating filters every time a callsite is hit (based on reasonable assumptions about the number of callsites and the number of times a configuration might change).

We previously had [a similar function](https://github.com/hawkw/tokio-trace-prototype/blob/e0ae945be9404dfd38cd102d7585743d34b12597/tokio-trace-core/src/callsite.rs#L80-L86) in the prototype. However, it did not rebuild the cached interests, and discarded all the subscribers as well. This was intended primarily for testing purposes. An implementation for this use-case should behave differently.

**Comment by yaahallo** [comment]
I'd like to get involved on this one

**Comment by hawkw** [comment]
@yaahallo great! Hopefully the issue description gives you enough to work off of, but let me know if anything's missing.
