### ISSUE TITLE
Rename `AsyncWrite::shutdown`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#104]
Continuation of https://github.com/tokio-rs/tokio-io/issues/80

**Comment by kpp** [comment]
Let's vote. I am for `prepare_for_close`. Arguments against the others:

- finalize - finalizers are used to construct and destruct an object. We need a destructor finalizer only. Confusing.
- poll_close_ready - `poll` word, I would expect to call this function more than once if it returns `NotReady`
- start_close - both `start` and `close` words in 1 name. confusing.


BTW, why not create a constraint `Drop` for `AsyncWrite`?

**Comment by carllerche** [comment]
I kind of like `start_close` as an analog to `Sink::start_send` and it refers to "starting the process of closing", but I see the confusion.

I agree that `finalize` should be off the table.

> BTW, why not create a constraint `Drop` for `AsyncWrite`?

Async operations cannot be performed in a drop function. There needs to be a way to signal to the writer that the closing process will start. For example, a `BufWriter` would need to start flushing anything that is currently buffered.

**Comment by kpp** [comment]
Was it done in futures 0.2 as [poll_close](http://rust-lang-nursery.github.io/futures-rs/futures/io/trait.AsyncWrite.html#tymethod.poll_close)?
