### ISSUE TITLE
length_delimited should use a custom error

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#105]
Continuation of https://github.com/tokio-rs/tokio-io/issues/71

**Comment by canthar** [comment]
I think we have 3 options here:

1. Create a breaking change. Set `Decoder::Error` and `Encoder::Error` in `LengthDelimitedCodec` to custom `LengthDelimitedCodecError`. It'd provide consistency with other codecs API.
2. Set `LengthDelimitedCodec` as deprecated and create new codec with correct error type with different name, e.g. `LengthFieldCodec`.
3. Don't care and close this issue.

In my opinion the first option is best, what do you think?

**Comment by Darksonn** [comment]
[This appears to have been fixed.][1]

[1]: https://docs.rs/tokio-util/0.3.1/tokio_util/codec/length_delimited/struct.LengthDelimitedCodecError.html
