### ISSUE TITLE
https://docs.rs/tokio/0.1.19/tokio/ is broken

### ISSUE THREAD

**Issue by galich** [tokio-rs/tokio#1059]
## Version

0.1.19

## Description

https://docs.rs/tokio/0.1.18/tokio/  - search works
https://docs.rs/tokio/0.1.19/tokio/  - search does not work

browser console is full of 
> Blocked loading mixed active content “http://docs.rs/tokio/0.1.19/tokio/”
> The script from “https://docs.rs/tokio/0.1.19/search-index-20190417-1.36.0-nightly-3c3d3c177.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type.[Learn More]

**Comment by carllerche** [comment]
Unfortunately, that is going to be a bug with docs.rs (https://github.com/rust-lang/docs.rs) or rust-lang (doc generator).

**Comment by galich** [comment]
hopefully https://github.com/rust-lang/docs.rs/issues/316 can fix that

**Comment by galich** [comment]
fix just landed and it works
