### ISSUE TITLE
trace: Shorthand field syntax

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio#1062]
In tokio-trace, it'd be handy to write
```rust
debug!({ foo });
```
instead of
```rust
debug!({ foo = foo });
```
just like with Rust struct initialization. @hawkw made the good point that this conflicts in the case of `span!` where you can genuinely have a field without an initial value, but for `event!`-style macros it would be pretty convenient. After all, using the variable name as the field name is probably the common case!

**Comment by hawkw** [comment]
I'd really like to get this in the next breaking change release of `tokio-trace`. The main blocker is finding a satisfactory syntax for span fields whose values are uninitialized (which currently uses `foo,`), as I think it's a mistake to add this syntax for events without also adding it for spans. 

I think the best replacement syntax for uninitialized span fields is `foo = _`, but I'm not really a big fan of that. @jonhoo, @davidbarsky, @LucioFranco and @carllerche, if any of you have suggestions, I'd love to hear them!

**Comment by jonhoo** [comment]
I personally quite like `foo = _`, but some alternatives:

 - `_foo` (`_` prefix marks a Rust variable as "allow unused")
 - `foo..` (`..` suffix used(-ish) in patterns for "ignore the rest"; the connection is tenuous)
 - `..foo` (like the `..Default::default()` used in struct instantiation; the connection is tenuous)
 - `[foo]` (akin to "optional" arguments in cli programs)

**Comment by hawkw** [comment]
@jonhoo thanks for the additional suggestions! I agree that `foo = _` may still be the best option, but I'm open to most of your suggestions with the exception of `_foo`; since this is a valid Rust identifier and we are matching field names as identifiers, this may complicate detecting that case in the macros...

**Comment by hawkw** [comment]
As an alternative, it occurs to me that `..foo` could potentially be used as a syntax for capturing a variable from the environment, which would obviate the need for a breaking change, although this might be surprising.

**Comment by jonhoo** [comment]
Another somewhat weird alternative: `"foo"` to indicate it's a field _name_ `foo` rather than a _variable_ `foo`.

**Comment by davidbarsky** [comment]
`foo = _` is my favorite choice, given that `..foo` can be used for capturing context from the environment. Plus, it fits nicely with other syntax in Tokio Trace.

**Comment by hawkw** [comment]
I'd love to start working on this soon and get it into `tokio-trace` v0.2. It seems like most people think changing the current meaning of `foo,` in the span macros to `foo = _,`, and I agree that of the proposed syntax it's probably the most obvious. @carllerche, I'd love to get your input on the proposed macro syntax changes if you have a moment, though.

**Comment by carllerche** [comment]
My gut reaction is that optimizing ergonomics for avoiding `foo = foo` is best, so stick with `debug!({ foo });`. Then, come up with an alternate syntax for defining an uninitialized variable.

**Comment by hawkw** [comment]
@carllerche Yeah, that's what I think we've all agreed on --- what I wanted to get your opinion on was specifically what the uninitialized field syntax ought to look like.
