### ISSUE TITLE
trace: span guards

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio#1075]
Currently, the primary way to use a span is to use `.enter` and pass a closure to be executed under the span. While that is convenient in many settings, it also comes with two decently inconvenient drawbacks:

 - It breaks control flow statements like `return`, `?`, `break`, and `continue`
 - It require re-indenting a potentially large chunk of code if you wish it to appear under a span

It'd be great if spans also had an API that allowed you to instead enter them until the end of a scope. Something along the lines of a scope guard, where you would write

```rust
let guard = span.enter();

// code here is within the span

drop(guard);

// code here is no longer within the span
```

**Comment by thedodd** [comment]
Agreed. The only other tracing API I've used in the Rust ecosystem uses a similar pattern. It is definitely quite nice.
