### ISSUE TITLE
How to reuse connection or connection pool for a tcp client

### ISSUE THREAD

**Issue by ufosky** [tokio-rs/tokio#1079]
I have read some examples like this https://github.com/tokio-rs/tokio/blob/master/tokio/examples/hello_world.rs , the clients logic flow are alway like this:
```
  let client = TcpStream::connect(&addr)
        .and_then(|stream| {
            // do something with stream
        })
        .map_err(|err| {
            // do something with err
        });
    tokio::run(client);
```
If I want to do another thing later, I must connect the same address and write the other logic  like above. But the general idea for me like this:
```
let client = Client::connect(&addr); //Make this a global access variable
...
client.doSomething().and_then(...);
...
client.doSomethingOther().and_then(...);
```
Is there any idea about this?

**Comment by carllerche** [comment]
You either need to pass self by value and thread it through the closures or write a state machine by hand (implement Future)

You may want to check out tower and tokio-tower in the tower-rs github .org.
