### ISSUE TITLE
trace: Shorthand field debug/display syntax

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio#1081]
In `slog`, there is really handy [shorthand syntax](https://docs.rs/slog/2.4.1/slog/macro.log.html#fmtdisplay-and-fmtdebug-values) for using the `Debug` or `Display` implementation for a value when logging. Specifically, you can write:
```rust
info!(log, "thingy"; "x" => %x); // uses x's impl of fmt::Display
info!(log, "thingy"; "x" => ?x); // uses x's impl of fmt::Debug
```
In `tokio-trace` it is also possible to use `Dispaly` and `Debug` through `field::display` and `field::debug` respectively, but there is no equivalent shorthand. It'd be awesome if it were possible to write:
```rust
info!({ x = %x }, "thingy"); // uses x's impl of fmt::Display
info!({ x = ?x }, "thingy"); // uses x's impl of fmt::Debug
```
Ideally this would combine with https://github.com/tokio-rs/tokio/issues/1062 to produce:
```rust
info!({ %x }, "thingy");
info!({ ?x }, "thingy");
```

**Comment by hawkw** [comment]
This is definitely doable. There is currently another ticket (#1020) for adding nicer field value interpolation to event messages, which would probably _include_ this functionality, but I think we could add just shorthand syntax with significantly less work.
