### ISSUE TITLE
chore: audit deny lints in crates

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1083]
Each crate should have the same set of `deny` cfg.

This also applies to clippy lints being added in #1335.

**Comment by stjepang** [comment]
Can we perhaps remove `#{deny(warnings)]` this time and add the following to CI?

```bash
export RUSTFLAGS="-D warnings"
```

That way denied warnings don't get in the way when tweaking code and still get caught by CI before merging.

**Comment by carllerche** [comment]
I was thinking about doing this? `#![cfg_attr(test, deny(warnings))]`. WDYT?

**Comment by stjepang** [comment]
I found warnings get in the way while toying with tests -- my typical workflow is to comment out the `deny(warnings)` line, write some code, and finally uncomment it before submitting a PR.
