### ISSUE TITLE
signal: `libc` should not be re-exported.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1084]
Re-exported at `tokio_signal::unix::libc`.

**Comment by ipetkov** [comment]
I think this was done because the signal definitions are platform (libc) specific and it seems weird to have to explicitly pull in `libc` just to instantiate a `Signal` instance.

I don't like having `libc` reexports either, but I'm wondering what we can do about the ergonomics there

**Comment by carllerche** [comment]
I think we should keep an eye on mio 0.7 and see if any patterns used there can apply here.

**Comment by carllerche** [comment]
Done on master.
