### ISSUE TITLE
Runtime builder `panic_handler` docs are misleading

### ISSUE THREAD

**Issue by leoyvens** [tokio-rs/tokio#1091]
## Version

0.1.20

## Description

The [docs](https://docs.rs/tokio/0.1.20/tokio/runtime/struct.Builder.html#method.panic_handler) say:
> To abort the process on panics, use std::panic::resume_unwind() in this callback as shown below.

However I tried this and it doesn't abort the process, I suspect it only kills the worker thread that panicked. Ping @ry.

**Comment by ry** [comment]
@leodasvacas Huh. At least [in my program](https://github.com/denoland/deno/blob/5e56e26c8baad08954cdc3ecac34923dcdc39c12/cli/tokio_util.rs#L13-L24), I believe it is killing the process...

**Comment by carllerche** [comment]
Yeah, I think that would just kill the thread... I guess a better default would be to terminate the runtime...

**Comment by leodasvacas** [comment]
@carllerche It'd be great for my usecase if that could be the default.

**Comment by ry** [comment]
I am now experiencing this too. For [technical reasons] I wasn't being exposed to it before.
I feel like tokio::run should join worker threads....

**Comment by carllerche** [comment]
No longer relevant. `runtime::Builder::panic_handler` has been removed as it did not work as expected. Instead, use `std::panic::set_hook` directly.
