### ISSUE TITLE
async-await-preview feature missing in master.

### ISSUE THREAD

**Issue by peterhuene** [tokio-rs/tokio#1094]
## Version

master @ 38092010c4113e80612fe61bfec08a44c3d41a65

## Platform

All

## Subcrates

N/A

## Description

The 0.1.x branch [removed the async-await-preview feature](https://github.com/tokio-rs/tokio/commit/38092010c4113e80612fe61bfec08a44c3d41a65#diff-0a053cc4b37432b22b44e58a48f0ea81L60).

When this was merged into master, it became no longer possible for tokio to [export the async-await items](https://github.com/tokio-rs/tokio/blob/master/tokio/src/lib.rs#L107-L117) in the top-level crate as there's no feature present to enable it.

I assume we still need the feature in master.

**Comment by carllerche** [comment]
Thanks for the report. 0.1 started lagging behind breaking changes in nightly. We opted to stop maintaining async-await-preview in 0.1 in favor of a full update, which is happening in https://github.com/tokio-rs/tokio/pull/1120

It is a very big process, so it will take some time to finish.

**Comment by qm3ster** [comment]
@carllerche I don't know what you consider "some time", you seem to be blazing through it like knife through butter :100:

**Comment by ehiggs** [comment]
#1120 was merged. Should the feature be re-enabled or are there further tickets tracking how/when we might be able to try async/await preview work?

**Comment by LucioFranco** [comment]
@ehiggs its no longer a preview :) The master branch contains work in progress breaking changes for `tokio` 0.2 which will include full support for `std::future::Future` and `async/await`. So really all you need to do is fetch tokio from git, use a nightly compiler and set the `#![feature(async_await)]` flag. There should be some examples if you look around the master branch.

**Comment by carllerche** [comment]
Also, #1201 is the tracking issue.
