### ISSUE TITLE
Website (https://tokio.rs) needs a favicon

### ISSUE THREAD

**Issue by DirkyJerky** [tokio-rs/tokio#11]
For people like me who have just a few hundred tabs open all the time and want to get back to reading that fantastic tokio tutorial ;)

**Comment by carllerche** [comment]
Great idea 👍 I'm not really sure how to make one, maybe you know? I think the logo is in the repo.

**Comment by DirkyJerky** [comment]
https://tokio.rs/img/logo.png

**Comment by carllerche** [comment]
Thanks! Merged: https://github.com/tokio-rs/website/pull/86
