### ISSUE TITLE
Handle::wakeup interaction with Task::notify

### ISSUE THREAD

**Issue by cynecx** [tokio-rs/tokio#110]
Sorry if this is the wrong place to ask this but I am currently digging in the source-code of tokio and I am trying to understand its interaction with futures.

The thing I can't reason about is the interaction between a futures's`Task::notify` call and the `Handle::wakeup` call. Let's assume a task is running on some unmanaged thread and the future completes, how would the reactor know the task's completeness since I couldn't find any code in tokio or futures which calls `Handle::wakeup` which is the only way for the reactor to wakeup and check for events.

**Comment by carllerche** [comment]
I'm not sure I follow the question.

> Let's assume a task is running on some unmanaged thread 

What do you mean by an unmanaged thread? Specifically, if the thread is unmanaged, why does the reactor need to know that the task completed?

**Comment by cynecx** [comment]
@carllerche Oh sorry, I meant something like an event which isn't an os-event (sockets, fs, ...), more like a computational event. Since those events can't be directly registered by the reactor.

**Comment by cynecx** [comment]
I've just noticed. Is this probably related to https://github.com/tokio-rs/tokio/issues/73?

**Comment by carllerche** [comment]
So, `Handle::wakeup` is actually unrelated to "resources" (leaf nodes in a future graph). `Handle::wakeup` is to enable an executor to run a tokio reactor on its thread.

If you register a `mio::Evented` type w/ the tokio reactor, the reactor will automatically know how to wakeup due to the os-event.

**Comment by cynecx** [comment]
> So, Handle::wakeup is actually unrelated to "resources" (leaf nodes in a future graph). Handle::wakeup is to enable an executor to run a tokio reactor on its thread.

A `futures::sync::oneshot::channel` would also require `Handle::wakeup`, right? Assuming the reactor/event-loop is "sleeping", it would be woken up through `Handle::wakeup`?

If this is so, who or what exactly calls Handle::wakeup? (I couldn't find any explicit calls to that method in the source).

**Comment by carllerche** [comment]
`Handle::wakeup` is needed to combine a tokio reactor with an executor. For example, if you have a thread pool and you want each thread to also have a tokio reactor running, you would use `Handle::wakeup`.

However, I think your confusion is legitimate in that the use cases for the wakeup function are separate from other reasons to use `Handle`.

I'm going to remove `wakeup` for now as it would make more sense to provide that functionality by some separate strategy.

I hope this clarifies things.

**Comment by carllerche** [comment]
Ok, this PR makes `wakeup` private: https://github.com/tokio-rs/tokio/pull/117
