### ISSUE TITLE
Can't access tokio_futures::compat externally

### ISSUE THREAD

**Issue by trezm** [tokio-rs/tokio#1105]
## Version
b2c5398

## Description
It seems like some things have been shuffled around with the compat layer -- specifically that `tokio-async-await` -> `tokio-futures`. How do we now access the compat layer? `tokio-futures` on Cargo is still a placeholder, and I don't see a reexport of the compat module elsewhere. Is the plan to use the `tokio-futures` crate on crates.io, or reexport around [here](https://github.com/tokio-rs/tokio/blob/38092010c4113e80612fe61bfec08a44c3d41a65/tokio/src/lib.rs#L114) in the near future?

**Comment by udoprog** [comment]
futures-rs now includes a [compatibility layer] ([article]) which handles `0.1 <-> 0.3` in both directions. I'm [using it successfully with tokio]. Maybe that's what should be used instead?

[compatibility layer]: https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.16/futures/compat/index.html
[article]: https://rust-lang-nursery.github.io/futures-rs/blog/2019/04/18/compatibility-layer.html
[using it successfully with tokio]: https://github.com/udoprog/setmod/blob/master/bot/src/main.rs#L91

**Comment by mbilker** [comment]
You can still convert futures with `tokio_futures::compat::into_01`. I am using it in my program to convert a future from hyper for use with `async_wait!`.

**Comment by trezm** [comment]
What version are you using? crates.io still shows 0.0.0
https://crates.io/crates/tokio-futures

**Comment by mbilker** [comment]
> What version are you using? crates.io still shows 0.0.0 https://crates.io/crates/tokio-futures

I am using the current version from git master since that crate has not been deployed to crates.io.

**Comment by trezm** [comment]
Right -- and if you use a git branch as a dependency you can't publish the
lib to crates.io.

**Comment by carllerche** [comment]
This is no longer an issue on 0.2
