### ISSUE TITLE
TcpListener on iOS does not report bad file descriptor error

### ISSUE THREAD

**Issue by thombles** [tokio-rs/tokio#1112]
## Version

├── tokio v0.1.20
│   ├── tokio-codec v0.1.1
│   │   └── tokio-io v0.1.12
│   ├── tokio-current-thread v0.1.6
│   │   └── tokio-executor v0.1.7
│   ├── tokio-fs v0.1.6
│   │   └── tokio-threadpool v0.1.14
│   ├── tokio-reactor v0.1.9
│   │   └── tokio-sync v0.1.5
│   ├── tokio-tcp v0.1.3
│   ├── tokio-timer v0.2.11
│   ├── tokio-trace-core v0.1.0
│   ├── tokio-udp v0.1.3
│   │   ├── tokio-codec v0.1.1 (*)
│   └── tokio-uds v0.2.5

## Platform

iOS 12.2

## Description

I'm having trouble detecting when a listening TCP listening socket gets destroyed by iOS. I'm not sure whether it's a coding error, a bug in tokio, or a bug in mio. Perhaps someone can point me in the right direction!

The overall scenario in iOS:
1. Have app with a TCP listening socket
2. Go to home screen and background the app (threads get parked, sockets still alive at this point)
3. Lock device (sockets are killed by OS)
4. Unlock device and re-enter the running app

If I create a synchronous listener with `std::net::TcpListener` and loop on `incoming()`, I receive an error `Os { code: 9, kind: Other, message: "Bad file descriptor" }`, then an infinite series of `Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }` errors.

Using `tokio::net::TcpListener`, my stream task receives no values or errors to indicate that anything happened.

The async server, slightly modified from the tokio guide:
```rust
        let addr = "0.0.0.0:6142".parse().unwrap();
        let listener = tokio::net::TcpListener::bind(&addr).unwrap();
        let server = listener.incoming().for_each(|socket| {
            info!("New connection arrived on 6142");
            let (reader, writer) = socket.split();
            let amount = tokio::io::copy(reader, writer);

            let msg = amount.then(|result| {
                    match result {
                    Ok((amount, _, _)) => info!("wrote {} bytes", amount),
                    Err(e)             => info!("error: {}", e),
                }

                Ok(())
            });
            tokio::spawn(msg);
            Ok(())
        })
        .map_err(|err| {
            info!("Async accept error = {:?}", err);
        })
        .map(|_|{
            info!("Async ended normally");
        });
        executor.spawn(server);
        println!("Async TCP server running on 6142");
```

The sync server, slightly modified from the std docs:
```rust
        std::thread::spawn(move || {
            let listener = match std::net::TcpListener::bind("0.0.0.0:6143") {
                Ok(listener) => listener,
                Err(e) => {
                    error!("Error binding sync TCP listener: {}", e);
                    return;
                }
            };
            info!("Sync TCP server running on 6143");
            
            let mut err_count = 0;
            for stream in listener.incoming() {
                match stream {
                    Ok(_client) => {
                        info!("Sync TCP got a connection on 6143");
                    },
                    Err(e) => {
                        info!("Sync TCP incoming error: {:?}", e);
                        err_count += 1;
                        if err_count > 5 {
                            break;
                        }
                    }
                }
            }
            error!("Sync TCP shutting down!");
        });
```

Output when the app is first run and I make some connections:
```
Sync TCP got a connection on 6143
Sync TCP got a connection on 6143
Sync TCP got a connection on 6143
New connection arrived on 6142
wrote 4 bytes
New connection arrived on 6142
wrote 4 bytes
```

Log output after locking and unlocking:
```
Sync TCP incoming error: Os { code: 9, kind: Other, message: "Bad file descriptor" }
Sync TCP incoming error: Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }
Sync TCP incoming error: Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }
Sync TCP incoming error: Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }
Sync TCP incoming error: Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }
Sync TCP incoming error: Os { code: 53, kind: ConnectionAborted, message: "Software caused connection abort" }
Sync TCP shutting down!
```

**Comment by Darksonn** [comment]
Closing this as it is an old v0.1 issue. If the issue still exists in v0.2, please open a new issue.
