### ISSUE TITLE
Should `timeout` count from instantiation or from first poll?

### ISSUE THREAD

**Issue by leoyvens** [tokio-rs/tokio#1125]
With `.deadline(Instant::now() + timeout_duration)` clearly the duration counted from the point of instantiation, now `.timeout(timeout_duration)` kept that behaviour but it's no longer obvious, and to me it would be less surprising if it counted from the first call to poll rather than from instantiation, for example in the code:
```
fn make_request(dur: Duration) -> Future<...> {
   do_request.timeout(dur)
}

let d = Duration::from_secs(30);
let second_request = make_request(d);
make_request(d).and_then(|_| second_request)
```

I'd expect both requests to have individual timeouts of 30 seconds, but what happens is that the timeout for `second_request` is already counting from instantiation, even though it didn't yet have the chance to start a network request.

Should the behaviour of `timeout` change? Is it worth also having a `deadline` method that keeps the current semantics?

**Comment by carllerche** [comment]
I believe the current behavior is fine and will be less of an issue with async await, but I flagged the issue as rfc

**Comment by carllerche** [comment]
I believe the answer is "no" as futures tend to default to being lazy.

There is also a variant that takes an `Instant`. You can use that one in order to specify the exact expiration.
