### ISSUE TITLE
send_dgram doesn't work with connect on macOS

### ISSUE THREAD

**Issue by ColinFinck** [tokio-rs/tokio#1126]
## Version
```
└── tokio v0.1.21
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.12
    ├── tokio-current-thread v0.1.6
    │   └── tokio-executor v0.1.7
    ├── tokio-executor v0.1.7 (*)
    ├── tokio-fs v0.1.6
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-threadpool v0.1.14
    │       └── tokio-executor v0.1.7 (*)
    │   └── tokio-io v0.1.12 (*)
    ├── tokio-io v0.1.12 (*)
    ├── tokio-reactor v0.1.9
    │   ├── tokio-executor v0.1.7 (*)
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-sync v0.1.5
    ├── tokio-sync v0.1.5 (*)
    ├── tokio-tcp v0.1.3
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-reactor v0.1.9 (*)
    ├── tokio-threadpool v0.1.14 (*)
    ├── tokio-timer v0.2.11
    │   └── tokio-executor v0.1.7 (*)
    ├── tokio-trace-core v0.2.0
    ├── tokio-udp v0.1.3
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-reactor v0.1.9 (*)
    └── tokio-uds v0.2.5
        ├── tokio-codec v0.1.1 (*)
        ├── tokio-io v0.1.12 (*)
        └── tokio-reactor v0.1.9 (*)
```

## Platform
`Darwin computername.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

## Subcrates
tokio-udp

## Description
I'm creating a new socket with `let socket = tokio::net::UdpSocket::bind(&local_addr).unwrap()` and then limit communication to a specific client using `socket.connect(&client_addr).unwrap()`.
All documentation suggests that `recv` and `send` shall now be used instead of `recv_from` and `send_to`.
However, tokio::net::UdpSocket's `recv_dgram` and `send_dgram` functions always use `recv_from` and `send_to` internally. `send_dgram` also requires to specify a target IP address.

I can successfully use `send_dgram` under Windows and Linux by passing `client_addr` as the target IP address: `socket.send_dgram(buf, &client_addr)`. Their underlying `send_to` system API apparently works after `connect` when specifying the same client IP address.
However, the same code fails under macOS with `Socket is already connected (os error 56)`.
This seems to be a known limitation of macOS, see e.g. https://www.perlmonks.org/bare/?node_id=415228

Possible solutions I imagine:
- A new pair of functions `recv_dgram_connected` and `send_dgram_connected` returning futures for working on UDP sockets where `connect` has been called. They should call `recv` and `send` internally.
- Something like a `recv_dgram_filtered` function returning a future that only yields `Async::Ready` when a datagram has been received *and* it is from the given IP address (or based on a different filter criteria), thereby performing the filtering `connect` does at user level.

**Comment by carllerche** [comment]
Thanks for the report. I think this will probably require a breaking change to address.

**Comment by sopium** [comment]
Hi, I would like to add that in v0.1 there were already `poll_send` and `poll_recv`, which calls `send` and `recv` under the hood. They should work fine with connected sockets on MacOS.

In v0.2 you will be able to use `send` and `recv` with async/await.
