### ISSUE TITLE
timer: Consider removal of errors from futures

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1133]
As we update to std::future, `Future` and `Stream` no longer have built-in `Error` types. In many cases, it's easy enough to just set `type Output = Result<Item, Error>`, like for `TcpStream::connect`. However, for a `Timeout` or `Interval`, I think the idea that they may error is surprising.

In fact, in all the code I've written using `tokio-timer` anyways, we simply panic on a `timer::Error`, as there's not much we can really do at that point, and it should only happen in the pathological case (**way** too many timeouts), or in the woops case, where a timer wasn't created in the first place.

Additionally, since the traits no longer carry an error type, its not easy to map a timer error onto the inner futures output type. We'd either need to require `Future<Output = Result<T, E>>`, or return `Output = Result<F::Output, timer::Error>`, which could lead to nested `Result`s.

I propose that we could improve things by not returning some `timer::Error`, and instead panicking internally.

**Comment by LucioFranco** [comment]
@seanmonstar I'm +1 on this as well, I think this would be a huge ergonomic improvement, we do the same with timers at work.

**Comment by carllerche** [comment]
Seems plausible. Either the error is due to misuse or it is fairly catastrophic.

**Comment by seanmonstar** [comment]
Having worked a little on timer now, I see that only `Delay` and `Interval` could remove its error type. The `Timeout` adapter needs to return something to indicate an elapsed error occured.

**Comment by dekellum** [comment]
@carllerche, "catastrophic" meaning unrecoverable?

I implemented some fairly painful means of propagating those errors:

https://github.com/dekellum/body-image/blob/244ece05/body-image-futio/src/lib.rs#L356

Though, even here, I have one panic for a  branch I believed to be impossible.  Happy to be able to simplify this if there is no recoverable errors here.

**Comment by carllerche** [comment]
@dekellum the error cases are only possible due to a program bug, not an unexpected runtime condition.

**Comment by dekellum** [comment]
Cool, looking forward to it being simplified!

**Comment by seanmonstar** [comment]
As an update, the `std-future` branch has the proposed changes already.

**Comment by seanmonstar** [comment]
@dekellum The two "timer" error cases are:

- AtCapacity: a program has spawned **way** too many `Delay`s. I believe this would be close to pushing too many items into a hash map?
- Shutdown: a program tried to poll a `Delay` while there was no active timer. This should only happen if a programmer didn't setup a runtime.

**Comment by dekellum** [comment]
Thanks. Hmm... the last one, if I were receiving it I might choose to log and ignore it, so as to avoid panic in the middle of my (perhaps not entirely orderly) shutdown?

**Comment by carllerche** [comment]
Implemented.
