### ISSUE TITLE
Updated (0.2) `tokio_threadpool::blocking` should wake after NotReady?

### ISSUE THREAD

**Issue by dekellum** [tokio-rs/tokio#1147]
I've recently been experimentally updating a public Tokio 0.1 application's `Sink`s and `Stream`s to futures 0.3-alpha, via the latter's compatibility layer.  These `Sink`s and `Stream`s use `tokio_threadpool::blocking` because they conditionally do file I/O.  As a result of that the `Sink`s have become more complicated due to changes in the 0.3 `Sink` interface, see rust-lang-nursery/futures-rs#1665 for background details.

Anyway, I wanted to put this on your radar and make sure we are on the same page. As part of the 0.2 upgrade, when `tokio_threadpool::blocking` returns what is now `Async::NotReady`, perhaps becoming `Poll::Pending` with futures 0.3, it should take direct or delegate responsibility for _waking_ when a blocking thread later becomes available, correct?

Or is this mechanism going to be changed/replaced in some more fundamental way?

See the comment and surrounding in this current 0.3 `Stream` implementation:

https://github.com/dekellum/body-image/blob/244ece05/body-image-futio/src/uni_image.rs#L266

Note I think my `waker().wake_by_ref()` isn't actually needed yet, because I'm always using Tokio's 0.1 runtime, and not the futures 0.3 runtime. I've included it "just in case" that changes.

This should be a v0.2 milestone design/verification item, but I don't think I can apply that label myself.

Also please let me know if there is something I could help with toward the tokio 0.2 milestone? Beyond the obvious: early testing!

**Comment by carllerche** [comment]
The plan is to rework how blocking works (see "blocking" in #1177). Once this is done, the blocking fn will always succeed. Bounding the amount of blocking threads will be left to higher level abstractions.
