### ISSUE TITLE
tokio-async-await broken on latest nightly

### ISSUE THREAD

**Issue by binomial0** [tokio-rs/tokio#1154]
## Version

tokio-async-await 0.1.7

## Platform

Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

rustc: nightly 2019-06-14

## Subcrates

tokio-async-await 0.1.7

## Description

tokio-async-await doesn't compile.
```
error[E0432]: unresolved import `std::await`
  --> /home/***/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-async-await-0.1.7/src/lib.rs:35:9
   |
35 | pub use std::await as std_await;
   |         ^^^^^^^^^^^^^^^^^^^^^^^ no `await` in the root


```

This issue does not occur in nightly-2019-05-06. It is likely caused by [this change in rustc](https://github.com/rust-lang/rust/pull/60586).

**Comment by carllerche** [comment]
Master is currently being updated to use std::future.
