### ISSUE TITLE
runtime: Change Runtime to no longer wait for idle to shutdown

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1156]
Currently, a tokio runtime allows spawning tasks on it, and it will by default block the thread until all tasks have completed. This allows one to spawn a few main tasks, and then assume everything will finish before the process exits.

The downside to the current approach is that it can sometimes be hard to tell why a runtime is still busy. It also prevents any notion of "daemon task", a task that does some housecleaning periodically but otherwise shouldn't prevent shutdown.

# Proposal

**Change the strategy of runtimes to *only* run and block the server as long as the user explicitly asks for.** The user would do this via a call like `block_on(some_future)`. Inside that blocked-on future, it can spawn new tasks onto the runtime. If that future depends on a value from one of those spawned, then the original future would naturally keep the runtime running while the spawned task finishes.

Any spawned tasks that aren't needed by a blocked-on future may be dropped suddenly at shutdown. This behavior is similar to `std::thread::spawn`. If the main thread needs something from a spawned thread, it will naturally wait, and if it doesn't, the daemon thread won't block process shutdown.

This strategy is similar to Kotlin works: The main thread would wait on `runBlocking`, and any coroutines specifically spawned as children inside that main task would keep the event loop running, but any coroutines spawned via `GlobalScope.launch` are considered daemon coroutines, and the `runBlocking` won't wait for them.

## Examples

```rust
let mut runtime = Runtime::new();
runtime.block_on(async {
    let (tx, rx) = oneshot::channel();

    // spawned task, but the main future needs something from it,
    // so it will wait for its completion
    spawn(async move {
        // some async computation
        tokio::timer::delay(one_sec).await;
        tx.send(some_val);
    });

    println!("got it: {:?}", rx.recv().await);
});
```

Daemon tasks don't hold up shutdown:

```rust
let mut runtime = Runtime::new();
runtime.block_on(async {
    // spawned task, but the main future doesn't need it
    spawn(async move {
        // some async computation
        tokio::timer::delay(one_sec).await;
        println!("you won't see me");
    });

    tokio::timer::delay(half_sec).await;    
});
```

## Additional but optional improvements

To ease using a runtime, we can add a static function `tokio::block_on`, which would create a thread-local runtime if one didn't exist. This allows multiple subsequent calls to `block_on`, and some local app state that may have used the first runtime won't have conflicts being used on a second runtime.

```rust
let client = hyper::Client::new();

let response = tokio::block_on(async {
    client.get(some_url).await
});

// client now has in its connection pool a spawned task
// in the original runtime

// Running the runtime again will be able to reuse that connection
let response = tokio::block_on(async {
    client.get(some_url).await
});

// but once we're done, the spawned task doesn't hold up shutdown
```

**Comment by sfackler** [comment]
Apologies if this has already been discussed to death, but I've always kind of felt like the top-level `tokio::run` function is a bit like `Future::wait`, in that it confuses things. IMO it might be better to just have people construct and use a Runtime directly, which makes what's going on more obvious.

**Comment by seanmonstar** [comment]
@sfackler I guess the point is that it's supposed to be like `main`. We appreciate that `fn main` in Rust takes care of a bunch of boilerplate for us (handling argv and exist status). Still, even if we got rid of the static functions, this issue still tries to address the difference between daemon tasks and their affect on preventing shutdown.

**Comment by carllerche** [comment]
@seanmonstar I'm OK w/ the proposed change. This is more inline with how threads work.

@sfackler To address your comment, I would like to remove `tokio::run` in favor of an annotation:

```rust
#[tokio::main]
async fn main() {
    let client = hyper::Client::new();

    let response = client.get(some_url).await;

    println!("{}", response);
}
```

There would still be the ability to create the runtime value by hand and the macro should be relatively foolproof.

**Comment by maghoff** [comment]
I stumbled upon this issue because I actually have the reverse desire: [`futures::executor::ThreadPool::run`](https://docs.rs/futures-preview/0.3.0-alpha.16/futures/executor/struct.ThreadPool.html#method.run) only blocks until the given feature has completed.

I agree that it quickly gets confusing and hard to debug when the executor blocks for all spawned futures. (I have this experience from node.js) However, for limited test scenarios, it is immensely useful to be able to do exactly that.

There seems to be no proposed workaround that would allow "draining" the task queue. Could that be added in without causing too much of a maintenance burden?

**Comment by carllerche** [comment]
It probably is fine to leave that ability on the `Runtime` type but have `#[tokio::main]` exit the process when the main fn completes.

**Comment by carllerche** [comment]
This is done.
