### ISSUE TITLE
403 From Link In Docs

### ISSUE THREAD

**Issue by emilyaherbert** [tokio-rs/tokio#1157]
## Platform

docs.rs

## Description

This line is 403ing:
https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/current_thread/mod.rs#L64

I found it linked from this page in the docs:
https://docs.rs/tokio/0.1.21/tokio/runtime/current_thread/index.html

**Comment by tobz** [comment]
Fixed in #1173.  Thanks for your report. 👍
