### ISSUE TITLE
reactor: consider requiring all resources (TcpStream, TcpListener, ...) to be created from a runtime.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1168]
Currently, a `TcpStream` can be created at any time. On creation, the stream is not bound to any runtime. It is only on first use (call to poll_ready, read, write, etc...) that the resource is bound to the reactor. This lazy behavior requires non-trivial logic to support.

This functionality exists because of how Tokio is used with futures to date. It's common to do something like:

```rust
let my_fut = TcpStream::connect(...).and_then(|socket| {
    // do something
});

tokio::run(my_fut);
```

In this case, the TcpStream is created **before** being passed to the runtime.

With Tokio 0.2, in the common case, applications will be running entirely from a runtime:

```rust
#[tokio::main]
async fn main() {
    let conn = TcpStream::connect(...).await;
    // do something
}
```

By requiring a reactor handle to always be present, either by virtue of constructing the resource or by passing one explicitly, much internal complexity and atomic logic can be removed.

**Comment by carllerche** [comment]
If `TcpStream::connect` is called from *outside* of the runtime, I would then expect a panic to occur.

**Comment by LucioFranco** [comment]
I'm +1 on this, I think this is a good time to simplify. I don't think I have a use case where we need to construct outside of a runtime context.

**Comment by tobz** [comment]
Also +1.

**Comment by carllerche** [comment]
There is an additional complexity. The delayed registration has another benefit.

When using the concurrent runtime, each thread has its own I/O reactor. The lazy registration allows one thread to accept all inbound sockets then distribute them across other threads. When the accepted TcpStream is first used on a different thread, it is registered with that thread's I/O reactor.

Currently, the lazy registration includes two components:

- Acquiring storage for the necessary state. This storage is acquired from the reactor's slab.
- Register the socket with the I/O reactor's selector.

These two steps could be decoupled so that the first step (the more complicated to do lazily) is done eagerly, and second is done lazily, preserving the thread distribution benefit of lazy registration.

**Comment by carllerche** [comment]
Also, we should ensure the panic message is good.

**Comment by DoumanAsh** [comment]
Just to clarify: it does intend to mean from reactor, rather than runtime?

**Comment by carllerche** [comment]
This means from any context that has `tokio_net::driver::set_default` called.
