### ISSUE TITLE
tokio::timer::timeout::Error's API is sad

### ISSUE THREAD

**Issue by richardwhiuk** [tokio-rs/tokio#1169]
## Version

0.1.21

## Platform

All

## Description

The API for https://docs.rs/tokio/0.1.21/tokio/timer/timeout/struct.Error.html is quite annoying to use.

When handling the error, you need to write code which reads like:

```rust
.timeout()
.map_err(|err| {
    if err.is_inner() {
        err.into_inner.unwrap()
    } else if err.is_elapsed() {
        
    } else /* if err.is_timer() */ {
        err.into_timer.unwrap()
    }
}
```

It would be much nicer if you could do:

```rust
.timeout()
.map_err(|err| {
   match err {
      Error::TimerElapsed => {},
      Error::TimerError(e) => {},
      Error::InnerError(e) => {}
   }
}
```

The current approach doesn't feel very Rust-ic.

**Comment by tobz** [comment]
This is intentionally done for forwards compatibility so that adding a new variant doesn't immediately break peoples code, although I've seen tricks like a `#[doc(hidden)]` catch-all variant on enums so that callers had to have a wildcard match arm.

Not sure how Carl/Eliza/Sean feel about that pattern, though.

**Comment by carllerche** [comment]
As mentioned, this is done for forwards compatibility. Errors will not be enums in Tokio. It *could* be possible to have a conversion fn into enum, as there would be a way to future proof it.

That said, most errors have been removed in favor of a panic in the `std-future` branch.

**Comment by tikue** [comment]
Can't forwards compatibility be accomplished by a [`#[non_exhaustive]`](https://github.com/rust-lang/rust/issues/44109) attribute?

**Comment by hawkw** [comment]
When `#[non_exhaustive]` has been stable long enough to compile on the minimum supported Rust version, yes.

**Comment by carllerche** [comment]
@tikue it's also an 80% solution as it doesn't offer forwards compatibility on values contained by the enum. For example:

```rust
enum Foo {
   Bar(Baz),
}
```

and the you want to pass another value with `Bar`... you could add a `Bar2` variant... which is better than nothing.

Anyway, closing as there is no further action to take. Timeout's error is now always expired.
