### ISSUE TITLE
About threadpool blocking api

### ISSUE THREAD

**Issue by driftluo** [tokio-rs/tokio#1172]
Current API is this:
```rust
pub fn blocking<F, T>(f: F) -> Poll<T, BlockingError>
where
    F: FnOnce() -> T
```

When the function returns not ready, `f` is eaten and does not return.

This API forces the user to make a self-cache `FnOnce` implementation when calling `blocking`, to handle the not ready state return.

I took a moment to look at the source code of the pool. Found that actually there is the ability to return `FnOnce` to the user. However, this is a breaking change and affects the implementation of the fs module.

Perhaps, you can add a function that gives it the ability to return `FnOnce` to the user when the pool reaches the thread limit, so that the user does not need to construct the cache method.

Maybe like this(This type seems a bit strange):
```rust
enum CustomAsync<T, F> {
    NotReady(F),
    Ready(T)
}

pub fn blocking<F, T>(f: F) -> Result<CustomAsync<T, F>, BlockingError>
where
    F: FnOnce() -> T,
```

**Maybe I should pull request directly?**

**Comment by carllerche** [comment]
I agree that this is not ideal. The plan is to rework how blocking works (see "blocking" in #1177). Once this is done, the `blocking` fn will always succeed. Bounding the amount of blocking threads will be left to higher level abstractions.

Given this, I don't think the issue has any action item beyond #1177.
