### ISSUE TITLE
test: provide a crate for making testing easier

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1175]
Common patterns have emerged across the ecosystem for testing code written with Tokio. These should be aggregated and organized into a testing crate.

The crate is `tokio-test` and should contain:

- [x] common assertions
- [x] clock / timer mocking facilities.
- [ ] I/O mocking
  - [ ] carllerche/mock-io@f3ddbf19207b4b91629a1e8a8122ca48828d1ffe
  - [ ] carllerche/fixture-io@3dc9148ae4319e34b499f89b08ed25c980f1401e
- [ ] ability to introspect / inject into common types.
- [ ] testing runtime that aggregates all of this.
- [x] `#[tokio::test]` macro.

These utilities should include documentation.

**Comment by bbigras** [comment]
Is there any way right now to mock a timer or have a way to "advance the clock" in tests?

**Comment by LucioFranco** [comment]
@bbigras you can see an example here https://github.com/tokio-rs/tokio/blob/master/tokio/tests/timer_interval.rs#L34

**Comment by bbigras** [comment]
Thank you very much.

**Comment by ultrasaurus** [comment]
Would be great to include an example or two that use these utilities

**Comment by LucioFranco** [comment]
Agreed! I think we should write a blog post about them!

**Comment by carllerche** [comment]
THis is mostly done.
