### ISSUE TITLE
tokio_tcp::TcpStream::poll_read_ready fails to detect HUP

### ISSUE THREAD

**Issue by vi** [tokio-rs/tokio#1182]
## Version

* tokio-tcp 0.1.3
* tokio 0.1.21
* mio 0.6.19

## Platform

x86_64-unknown-linux-gnu

## Description

`TcpStream::poll_read_ready` claims to always include HUP on supported platform. I assume Linux (and Unix in genereal) is a supported platform. Yet arrival of FIN on the socket does not cause it to return `Ok(Async::Ready)`.

## Sample code

```
extern crate tokio;
extern crate tokio_tcp;
extern crate mio;

use tokio::prelude::*;

// Wait for TCP socket reset without reading or writing to it
struct WaitForJustHup(tokio_tcp::TcpStream);

impl Future for WaitForJustHup {
    type Item=();
    type Error=();
    fn poll(&mut self) -> Poll<(), ()> {
        let mut m = mio::Ready::empty();
        #[cfg(unix)] {
            m = mio::unix::UnixReady::hup().into();
        }
        let ret = self.0.poll_read_ready(m);
        println!("{:?}", ret);
        match ret {
            Ok(Async::NotReady) => Ok(Async::NotReady),
            _ => Ok(Async::Ready(())),
        }
    }
}

fn main() {
    let sa = "127.0.0.1:1234".parse().unwrap();
    let job = tokio_tcp::TcpStream::connect(&sa).map_err(drop).and_then(|tcp| {
        WaitForJustHup(tcp)
    });
    tokio::runtime::run(job);
}
```

When I run it against `nc -nvlp 1234`, I get:

```
Ok(NotReady)   # it connected
Ok(NotReady)   # I typed something into netcat
Ok(NotReady)   # I terminated netcat. I expect it to be Ok(Ready(_)) instead.
```

**Comment by vi** [comment]
With `mio = "=0.6.16"` it works:

```
Ok(NotReady)
Ok(NotReady)
Ok(Ready(Hup))
```

With `mio = "=0.6.17"` it fails:

```
Ok(NotReady)
Ok(NotReady)
Ok(NotReady)
^C
```

**Comment by vi** [comment]
https://github.com/tokio-rs/mio/commit/b89e3bd662c27242909b446dbb80c74249fe6042

**Comment by carllerche** [comment]
@vi yes, that was a bug. Reporting `RDHUP` as `HUP` was incorrect. I'm going to close this specific issue. I plan to revisit what events are exposed as part of 0.2.

**Comment by vi** [comment]
Will it be possible to:

* monitor for TCP's FIN or RSTs
* while having the socket already shut down for writing
* without reading from it (backpressure)

after the revisit?

**Comment by carllerche** [comment]
Yes, I would like to. It will most likely require platform specific code in Tokio to do so.

**Comment by carllerche** [comment]
I added a note here: #1209.
