### ISSUE TITLE
macros: provide #[tokio::main] macro

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1183]
The macro is already implemented in `tokio-macros`, but needs to be re-exported from the `tokio` crate as well as documented.

**Comment by zkat** [comment]
Is this a good first issue for a beginner who's unfamiliar with tokio? I've been looking out for opportunities to contrib.

**Comment by carllerche** [comment]
It could be yes. You can also get guidance in gitter.

It is mostly going to be exporting the macro from the tokio crate guarded by the `rt-full` flag.
