### ISSUE TITLE
meta: instrument Tokio with `tracing`.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1186]
This issue tracks instrumenting Tokio using the `tracing` crate (formerly known as `tokio-trace`). I will be updating the description with thoughts and the issue can be used for general discusssion.

## Runtime

- [x] Active tasks (#697).
- [ ] Track worker-id polling task (#815).

## Net
- [ ] #1504

**Comment by hawkw** [comment]
#2655 adds `tracing` spans for every spawned task, when enabled. We can derive information about task durations (and counting different types of task) using these spans.

**Comment by carllerche** [comment]
Gonna close this for now as it hasn't took off. We do want more instrumentation points though :)
