### ISSUE TITLE
tokio: update to mio 0.7

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1190]
Mio 0.7 is not yet released. The `tokio` master branch should depend on the `mio` master branch and track changes.

**Comment by Razican** [comment]
Hello, is there news on this regard?

**Comment by carllerche** [comment]
It is a goal for 0.3, which should be sometime next month. There are still some windows issues to work through.

**Comment by galich** [comment]
Current version of tokio refers to winapi 0.3 and mio 0.6, which refers to winapi 0.2. We have 2 versions of fairly large winapi crate to build every time.

@carllerche is there any specific issue we can try and help with to make mio 0.7 used in tokio faster?

**Comment by mzji** [comment]
mio has updated its winapi dependency to 0.3 now.

**Comment by Emilgardis** [comment]
mio 0.7.0 is now released. tokio-rs/mio#1279

**Comment by Stammark** [comment]
+1 for this from me!

Although to resolve winapi issues, the mio-named-pipes dependency would also have to be updated, too, probably (?) (see https://github.com/alexcrichton/mio-named-pipes/issues/7).

**Comment by Darksonn** [comment]
Regarding mio-named-pipes: #2547

**Comment by Darksonn** [comment]
oops

**Comment by jmagnuson** [comment]
PR for updating mio-named-pipes: https://github.com/alexcrichton/mio-named-pipes/pull/10

Previous work to update tokio to mio 0.7: https://github.com/tokio-rs/tokio/pull/1767

**Comment by damianwadley** [comment]
Note that mio 0.6 contains an indirect dependency (via [miow](https://crates.io/crates/miow) 0.2) on [net2](https://crates.io/crates/net2), which [has been deprecated](https://rustsec.org/advisories/RUSTSEC-2020-0016) in favor of [socket2](https://crates.io/crates/socket2) since earlier this month. `cargo audit` is also warning about it.
mio 0.7 (miow 0.3) has already moved to socket2.

**Comment by oherrala** [comment]
Borrowing this issue to mention that mio 0.7.0 release fixes a memory leak in Windows.

Upstream issue: https://github.com/tokio-rs/mio/issues/919

Issues hopefully solved by updating tokio's mio to 0.7.0 based on the issue and crate's dependency to tokio:

 * https://github.com/bluejekyll/trust-dns/issues/692
 * https://github.com/seanmonstar/reqwest/issues/284
 * https://github.com/stepancheg/grpc-rust/issues/110

**Comment by faern** [comment]
Any updates here? Getting rid of `mio 0.6` is certainly desirable.

**Comment by carllerche** [comment]
Planned as part of 0.3

**Comment by taiki-e** [comment]
Closing -- done in #2893
