### ISSUE TITLE
tokio: update to bytes 0.5

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1191]
`bytes` 0.5 is not yet released. The `tokio` master branch should depend on the `bytes` master branch and track changes.

**Comment by jplatte** [comment]
I've looked into this, it seems to require (more or less) some non-trivial changes. The biggest one I've found so far is changing `AsyncRead::poll_read`s `buf` parameter from `&mut [u8]` to `&mut [MaybeUninit<u8>]`. This seems like a reasonable change to me, but I'm not totally sure. Should all the code touching potentially-uninitialized buffers be changed to `[MaybeUninit<u8>]`?

**Comment by carllerche** [comment]
Done on master.
