### ISSUE TITLE
signal: update to std::future

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1193]
`tokio-signal` should be updated to use `std::future`.

This issue is to track discussion and progress.

cc @ipetkov

**Comment by ipetkov** [comment]
Started working on this and I noticed `tokio-signal` was still using the channels from `futures`. We should take this opportunity to migrate to `tokio-sync` for consistency across the `tokio` ecosystem (but might do this in separate PRs for reviewing sanity)

**Comment by carllerche** [comment]
@ipetkov great :+1:

**Comment by ipetkov** [comment]
One more issue I hit: `current_thread::Runtime`'s timer initialization is commented out, so none of the tests will run properly (since they enforce their own timeout to catch any deadlock regressions)

**Comment by carllerche** [comment]
Thanks for calling this out. It should be possible to bring back sooner than later.

**Comment by carllerche** [comment]
Working on it in https://github.com/tokio-rs/tokio/pull/1222

**Comment by carllerche** [comment]
#1237 turns out it was a bigger job than expected.

**Comment by carllerche** [comment]
Done in #1218.
