### ISSUE TITLE
tls: update to std::future

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1194]
`tokio-tls` should be updated to use `std::future`.

This issue is to track discussion and progress.

**Comment by jxs** [comment]
Hi, I started updating tokio-tls to to `std::future` (tokio-rs/tokio#1224) but noticed that `AsyncRead`/`AsyncWrite` are no longer bounded by `std::io::Read`/`Write`, and don't have a default implementation.   
 Also `TcpStream` no longer implements `Read`, so `native_tls::TlsStream<S>::Read` cannot be called.

 Should `Read`/`Write` be added again to `TcpStream` (and all the other Structs that are used by tokio_tls) with what was the default `AsyncRead`/`AsyncWrite` implementation and  `impl<S: Read + Write + Unpin> AsyncRead/AsyncWrite for tokio_tls::TlsStream<S>` until `native-tls` impelements `AsyncRead`/`AsyncRead`,
 Or wait for it and then `impl<S: AsyncRead + AsyncWrite + Unpin> AsyncRead/AsyncWrite for tokio_tls::TlsStream<S>`?

**Comment by carllerche** [comment]
We can probably add a `struct AllowStd<T>` similar to that in the futures repository that makes the bridge happy. Then:

```rust
struct TlsStream<T> {
    inner: native_tls::TlsStream<AllowStd<T>>,
}
```

I think this should work. Cheers.
