### ISSUE TITLE
tokio: introduce I/O utility helpers

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1203]
The existing I/O utility helpers were deleted in #1164. New ones should be implemented.

The utility helpers will be implemented on `AsyncReadExt` and `AsyncWriteExt` traits and will exist in `tokio::io`.

Some helpers to add include, but are not limited to:

### `AsyncReadExt`

- [x] `read`
- [x] `read_to_end`
- [x] `read_to_string`
- [x] `read_exact`
- [x] `read_until`
- [x] `copy`

### `AsyncWriteExt`

- [x] `write`
- [x] `write_all`
- [x] `flush`

**Comment by bIgBV** [comment]
I'm working on porting over `read_until` but it depends on the `std::io::BufRead` trait and the now deprecated `try_nb!` macro from tokio-io. I'm not sure how the `BufRead` bound will work with the new syntax.

One option is to copy over the functionality of `read_until` from `BufRead` into this future. This would mean adding a dependency on `memchr` though, as it looks like the standard library ships with its own version of the same.

**Comment by bIgBV** [comment]
Looks like `read_to_end` also depended on behavior from the `Read` trait and will have to be re-thought as well.

**Comment by taiki-e** [comment]
I think it is good to define the `AsyncBufRead` trait and experiment with it, like `futures-io`.

**Comment by mokomull** [comment]
Does `AsyncRead::split()` belong on this list as well?  It seems to have been replaced with a TCP-only implementation, but I was using it with UnixStream.

I am currently using futures 0.3's `AsyncReadExt::split` instead, via @Nemo157's [shim from #1297](https://github.com/tokio-rs/tokio/issues/1297#issuecomment-514377285), and it works beautifully.

**Comment by carllerche** [comment]
@mokomull added a line item to #1256.
