### ISSUE TITLE
sync: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1210]
Tracking misc smaller improvements to `tokio-sync`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Changes

- Consider switching `Lock` to borrow.
- Consider moving `AtomicWaker` into dedicated crate or some other crate.
- Investigate `&mut self` requirement for `UnboundedSender`.

### Tests

- Fix `tests/lock.rs`; `fn lock()`. The test depends on thread timing.

### `async` / `await`

Add `async` / `await` APIs for:

- [x] oneshot (#1211)
- [x] mpsc (#1211)
- [x] lock
- [x] watch

### Polish

- only run loom tests on CI by default.
- investigate `memcpy` calls (https://github.com/tokio-rs/tokio/pull/1540#issuecomment-531322702).

### Documentation

- [ ] Ensure all APIs are documented with examples.

**Comment by archseer** [comment]
Should the channel implementations be shared with futures-channel?

**Comment by carllerche** [comment]
@archseer futures-channel is welcome to copy whatever code. I don't know what their design goals are, so I cannot comment on whether or not they would want to copy it.

Given that the Tokio maintainers are the ones that will be maintaining the tokio-sync channel, it is easier for us to keep it in a crate we can publish to.
