### ISSUE TITLE
Hello world documentation broken link and ncat didn't work on Mac

### ISSUE THREAD

**Issue by songproducer** [tokio-rs/tokio#1213]
Hi!

Was following this tutorial:
https://tokio.rs/docs/getting-started/hello-world/

Which has a broken link:
You can find the full example here.
https://github.com/tokio-rs/tokio/blob/master/tokio/examples/hello_world.rs

Also this command did not work on Mac:
ncat -l -p 6142
nc: missing port with option -l

**Comment by LucioFranco** [comment]
Looks like we need to update the website to point to the `v0.1.x` branch as master is in flux right now.
