### ISSUE TITLE
Tasks must not implement Send

### ISSUE THREAD

**Issue by coder543** [tokio-rs/tokio#123]
[From here:](https://github.com/tokio-rs/tokio/blob/master/examples/hello_world.rs#L65) "The `current_thread` executor multiplexes all scheduled tasks on the current thread. This means that spawned tasks **must not** implement `Send`."

Should this say "This means that spawned tasks **are not required** to implement `Send`"?

**Comment by carllerche** [comment]
Oh yeah, definitely a mistake. You are correct that it should be "This means that spawned tasks are not required to implement Send"
