### ISSUE TITLE
Remove `tokio::run()`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1235]
This function is no longer relevant thanks to `#[tokio::main]`

Edit: `main` not `mian`.

**Comment by qm3ster** [comment]
I actually searched for `mian` :v

**Comment by carllerche** [comment]
woops...

**Comment by elpiel** [comment]
Can I pick this up?

**Comment by carllerche** [comment]
Sure, all the issues are up for grabs :+1:

**Comment by elpiel** [comment]
So update docs, remove usage of `tokio::run` in tests and etc?

**Comment by seanmonstar** [comment]
The removal was done in https://github.com/tokio-rs/tokio/pull/1280. Do you wish to use this to track it examples/docs?

**Comment by carllerche** [comment]
I think we can close this. All examples / docs need to go through a full audit anyway.

**Comment by Fedcomp** [comment]
How do i use tokio in tests now?
by the way https://docs.rs/tokio/0.2.0-alpha.4/tokio/runtime/struct.Runtime.html mentions `tokio::run`.

**Comment by ipetkov** [comment]
@Fedcomp you should use the [`tokio::test`](https://docs.rs/tokio-macros/0.2.0-alpha.4/tokio_macros/attr.test.html) macro on your tests (which become `async fn`s) which will run your future to completion

**Comment by Fedcomp** [comment]
@ipetkov thanks!
