### ISSUE TITLE
tokio-signal: update comment about ctrl-c with cargo run

### ISSUE THREAD

**Issue by totorigolo** [tokio-rs/tokio#1248]
The `ctrl-c` example in `tokio-signal` mentions a bug about using `cargo run`. However, this bug has been solved: https://github.com/rust-lang/rustup.rs/pull/1242.

https://github.com/tokio-rs/tokio/blob/cbad83f36250dee743e9ccef0cf473fce3300d28/tokio-signal/examples/ctrl-c.rs#L24-L32

Then, I think that this comment can be removed. I just want to be sure before opening a PR.

**Comment by ipetkov** [comment]
That sounds good to me, feel free to send a PR!
