### ISSUE TITLE
nitpicking

### ISSUE THREAD

**Issue by bestouff** [tokio-rs/tokio#125]
https://github.com/tokio-rs/tokio/blob/4ae76132c16c2cffd80373ea8c69091ab32d5b02/examples/hello_world.rs#L65
Is it "must not" or "don't have to" ?

**Comment by vitalyd** [comment]
I saw this too - should be “don’t have to” (or “aren’t required to” or whatever bikeshed formulation).

**Comment by carllerche** [comment]
Yep thanks for pointing it out. 

Fixed by #124
