### ISSUE TITLE
buf: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1251]
Tracking misc smaller improvements to `tokio-udp`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

**Comment by bluetech** [comment]
Currently (v0.2.0-alpha1), everything in the `tokio-buf` crate is commented out except for the `BufStream` trait itself. Is this a TODO for the 0.1 -> 0.2 transition, or something else?

**Comment by carllerche** [comment]
@bluetech yeah, we forgot to finish it :( it will be part of the next alpha.

**Comment by carllerche** [comment]
I'm going to close this as I think `tokio-buf` is going to be removed.
