### ISSUE TITLE
codec: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1252]
Tracking misc smaller improvements to `tokio-codec`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Api

- [ ] evaluate `Unpin` bounds. are they required?

### Polish

- [ ] evaluate module structure & re-exports with regards to error types.

**Comment by sopium** [comment]
I noticed an issue: `LinesCodecError`, the custom error type for the `LinesCodec`, is never exported.

**Comment by carllerche** [comment]
@sopium thanks, tracking.

**Comment by JohnDoneth** [comment]
The issue with regards to `LinesCodecError` has been resolved in #1350.
