### ISSUE TITLE
tls: misc improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1262]
Tracking misc smaller improvements to `tokio-tls`.

This issue is to be closed once there are no remaining breaking changes to make **or** remaining breaking changes are tracked in separate issues.

### Tests

* [ ] audit tests (some tests seem to require network access).

**Comment by dbcfd** [comment]
Working on tls-async, I made a number of changes to split up the code, and not expose native-tls.

https://github.com/dbcfd/tls-async

Is there any interest in bringing those changes back in to tokio-tls? Also is there interest in switching from native-tls to rustls. If so, I can do PR's.
