### ISSUE TITLE
examples page is giving 404

### ISSUE THREAD

**Issue by SauravDas90** [tokio-rs/tokio#1265]
https://github.com/tokio-rs/tokio/blob/master/tokio/examples

The example page is giving 404.

and its on the main page

Can anyone please fix that?

**Comment by LucioFranco** [comment]
Hi, the master branch is currently in flux as we update to std::future::Future. The old examples can be found here https://github.com/tokio-rs/tokio/tree/v0.1.x/tokio/examples

**Comment by carllerche** [comment]
The URL no longer returns a 404.
