### ISSUE TITLE
100% cpu in Enter::block_on

### ISSUE THREAD

**Issue by matthieugras** [tokio-rs/tokio#1296]
## Version
master

## Platform
Linux 4.19.58

## Description
this code:
```
#[tokio::main]
async fn main() -> Result<(), Error> {
    Delay::new(Instant::now() + Duration::from_secs(1000)).await;
    Ok(())
}
```

uses 100% cpu

Callgrind output:
![Screenshot_20190713_122337](https://user-images.githubusercontent.com/35115728/61170447-6966ba80-a569-11e9-9d92-7746eb223eb4.png)

**Comment by 95th** [comment]
Same thing happening for me in Windows 10
