### ISSUE TITLE
CONTRIBUTING.md should list a contact for CoC enforcement

### ISSUE THREAD

**Issue by SoniEx2** [tokio-rs/tokio#1299]
## Version

N/A

## Platform

N/A

## Subcrates

N/A

## Description

The CONTRIBUTING.md should list a contact for CoC-related communications. I'm not sure it'd be a good idea to contact the Rust mods about Tokio moderation issues. The following excerpt suggests I shouldn't:

> For other projects adopting the Rust Code of Conduct, please contact the maintainers of those projects for enforcement. If you wish to use this code of conduct for your own project, consider explicitly mentioning your moderation policy or making a copy with your own moderation policy so as to avoid confusion.

But I don't see any contact for the Tokio project.

**Comment by SoniEx2** [comment]
well, while I'm at it, could I be unbanned from the gitter? I'm sorry about earlier.

**Comment by Darksonn** [comment]
There is an email in `CODE_OF_CONDUCT.md` for this purpose.
