### ISSUE TITLE
Some documentation pages return 403

### ISSUE THREAD

**Issue by Hoverbear** [tokio-rs/tokio#13]
Examples:

* http://rust-doc.s3-website-us-east-1.amazonaws.com/tokio/master/mio/net/tcp/struct.TcpListener.html#method.take_socket_error
* http://rust-doc.s3-website-us-east-1.amazonaws.com/tokio/master/mio/net/unix/struct.UnixSocket.html#method.stream

Seems to be related to `#` in the link?

**Comment by carllerche** [comment]
Where was this linked from? I'm not uploading the `mio` documentation. So this is strange.

**Comment by carllerche** [comment]
I think this is fixed. It probably happened when I manually uploaded the documentation.
