### ISSUE TITLE
udp: try_clone missing for UdpSocket

### ISSUE THREAD

**Issue by mkindahl** [tokio-rs/tokio#1307]
## Version

0.2.0

## Platform

All

## Subcrates

tokio-udp

## Description

Although both `std::net::UdpSocket` and `mio::net::UdpSocket` provide an implementation of `try_clone`, there is no implementation of `try_clone` in `tokio::net::UdpSocket`.

**Comment by carllerche** [comment]
Tokio cannot support cloning as the OS selectors do not allow storing different data for FD clones. Because of this, we cannot properly dispatch events if the FD is cloned.

**Comment by mkindahl** [comment]
Discussions about deprecating `TcpSocket::try_clone` and a discussion about why it does not work as expected:

* [Issue #774: Error : "socket already registered" when upgrading from 0.1.11 to 0.1.13 (comment)](https://github.com/tokio-rs/tokio/issues/774#issuecomment-443519689)
* [PR#824 - tcp: deprecate `TcpStream::try_clone()`](https://github.com/tokio-rs/tokio/pull/824)

**Comment by mkindahl** [comment]
I still feel that it is a problem that you cannot clone the write end of a socket. It is a reasonable expectation that you should be able to use a socket from multiple locations to send out messages and there are no problems with supporting this on the OS level.

The alternatives to not supporting it in Tokio are:

* Implement some sort of system for dispatching messages through a unique socket instance, basically re-implementing something that Tokio already support.

  This diminish the usability of Tokio since it would require a user to implement parallel functionality to something that already exists in Tokio.

* Open two different sockets with different addresses, where one is just used for sending packets.

  This affect the usability of Tokio since an application cannot be designed in a reasonable manner.

  The application would have to either add the sender address to the actual UDP packets and ignore the sender address in the header, or keep track of two different addresses that are both associated with the same server. It would also require the application to keep track of what address should be used to receive packets, or allow packets to be received on both. It will also be confusing to a user why the application requires two ports rather than just one.

* Use `SO_REUSEPORT` or `SO_REUSEADDR` (I assume that it is possible to set socket options on Tokio sockets) to allow two different sockets to be bound to the same address.

  This diminish the usability of Tokio since it can lead to subtle bugs.

  Since packets received on the address will be "randomly" handled by one of the sockets, the packets might be lost if the application is not written to allow both sockets to receive packets.

**Comment by carllerche** [comment]
@mkindahl if you have a strategy by which cloning the socket can be implemented, I would be happy to consider it.

**Comment by mkindahl** [comment]
@carllerche Thank you. I need to read through the code and the other bug reports to understand what the root problem is, and I do not have an abundance of free time (and am comparably new to Rust and Tokio), but I will see if I can figure something out.

**Comment by jedisct1** [comment]
Any hope to reconsider this for tokio 0.3?

**Comment by carllerche** [comment]
How do you handle receiving? I assume you would have a single receiver which is then responsible for dispatching the message to the appropriate destination?

**Comment by jedisct1** [comment]
Yes, exactly. There is a single receiver, spawning tasks that directly send the response back to the client IP with `send_to()` when done.

**Comment by carllerche** [comment]
I will track this part of #1624.

**Comment by matclab** [comment]
@carllerche coud you please provide some insight about how a wrapper could resolve the problem ? As a Rust beginner it looks to me that the wrapper would encapsulate the UspSocket and as such would have the same problem of not being clonable. But I probably misunderstood the wrapper thing.

**Comment by matclab** [comment]
Ok, using a `Arc<Mutex<UdpSocket>>` solved my need for my use case.
