### ISSUE TITLE
Building a project with tokio crate instead of tokio-core

### ISSUE THREAD

**Issue by Relrin** [tokio-rs/tokio#132]
Hello!

I'm recently started migrating [my personal project](https://github.com/OpenMatchmaking/pathfinder) which is using tokio-core onto this crate, but can't build an application because getting errors:
1) When I'm trying to replace the tokio-crate in Cargo.toml onto `tokio = "0.1.1"`, I'm receiving the error for getting crates from registry:
```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `mio` (required by `tokio`):
all possible versions conflict with previously selected versions of `mio`
  version 0.6.12 in use by mio v0.6.12
  possible versions to select: 0.6.13
```
2) In this case if replacing onto `tokio = "0.1.0"`, then we will get the following compile error:
```
$ cargo build
   Compiling tokio v0.1.0
error[E0599]: no function or associated item named `from_std` found for type `mio::net::TcpListener` in the current scope
   --> C:\Users\Relrin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.1.0\src\net\tcp.rs:123:17
    |
123 |         let l = mio::net::TcpListener::from_std(listener)?;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `tokio`.
```

Any ideas how it can be fixed?

**Comment by kpp** [comment]
> When I'm trying to replace the tokio-crate in Cargo.toml onto tokio = "0.1.1", I'm receiving the error for getting crates from registry:

Update your `Cargo.lock` either by `cargo update` or by removing `Cargo.lock` and running `cargo build` again.

**Comment by Relrin** [comment]
Removing the `Cargo.lock` file and using `cargo build` command helped me. Thanks for the answer!
