### ISSUE TITLE
tokio: doc-comment example in tokio/src/lib.rs uses non-existant tokio::run

### ISSUE THREAD

**Issue by alex** [tokio-rs/tokio#1339]
https://github.com/tokio-rs/tokio/blob/master/tokio/src/lib.rs#L37-L67

This still uses `tokio::run` even though that no longer exists on `master`. It should be updated to the new APIs.

**Comment by carllerche** [comment]
Yes, in general master docs are pretty busted. I plan to do a pass (to at least delete out of date examples) before cutting an alpha.

Happy to take PRs to update docs though.
