### ISSUE TITLE
Change Executors to take &self

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1344]
The `Executor` and `TypedExecutor` traits both take `&mut self` in their `spawn` method. While this does make sense logically, it has this downside: you can't share an executor with an `Arc` (for example, an `Arc<dyn Executor>`). You can put the executor inside a `Mutex`, however *most* executors already can handle synchronization internally, frequently with some lock-free queue.

It might be a good idea to switch the `spawn` function to only take `&self`.

An alternative option is to leave them as `&mut self`, and implement `Executor for &T` for those that already have internal synchronization.

**Comment by LucioFranco** [comment]
@seanmonstar is there benefit to having them take `&self` over just having a cheap clone internally?

**Comment by seanmonstar** [comment]
The difficulty I ran into was when using it as a trait object, because then you can't make use of a cheap clone.

**Comment by LucioFranco** [comment]
Ah that makes a lot of sense, I think that is a good idea then!

**Comment by carllerche** [comment]
@seanmonstar the trait obj argument is solid. I am :+1:

**Comment by hawkw** [comment]
I think this issue is no longer relevant, as the `Executor` and `TypedExecutor` traits no longer exist.
