### ISSUE TITLE
Can't use codec and Framed with Udp

### ISSUE THREAD

**Issue by russelltg** [tokio-rs/tokio#1363]
## Version
Master as of today (Jul 27 2019)

## Platform
Linux, not that it should matter

## Subcrates
tokio-udp, tokio-codec

## Description
In tokio 0.1, you could use a `UdpFramed<SomeCodec>` to have a codec applied to your UDP socket. In tokio master, this seems to be replaced with `Framed`, which only supports `AsyncRead + AsyncWrite` types, which `UdpSocket` is not. 

Is there any planned way to use `Framed` with UDP? I'm willing to help if I'm shown in the right direction.

**Comment by LucioFranco** [comment]
hi! looks like we have still yet to port `UdpFramed` which is what you are looking for. 

https://github.com/tokio-rs/tokio/blob/master/tokio-udp/src/frame.rs#L27

This just needs to be updated to std::future::Future.

**Comment by carllerche** [comment]
It was explicitly punted on for now.

Having `async` fns on UDP ops changes the calculus a bit. Could you elaborate a bit on how you were using UDP framed?

**Comment by seirdb** [comment]
I noticed the same issue when looking at async/await for our current project.
We we're using the UDP framed to iterate (for_each) over the received packets (decoded datagrams) on a not-connected socket.

Looking at the docs for the current [master](https://github.com/tokio-rs/tokio/commit/ff922bbe6d8de897b01f006b8e22a59bef2c9190) branch, this is feasible to do by splitting the `UdpSocket` and using `recv_from` on the `UdpSocketRecvHalf`.

The decoding (and further down encoding) then needs to be done on the datagrams yielded from this `RecvFrom` future.

**Comment by russelltg** [comment]
I was using it to get a `Stream + Sink` udp object. I had manually implemented stream/sink implementations on top of that implementing a network protocol. It very well could be that there's a better way to do it now with async/await, as it's quite new to me.
