### ISSUE TITLE
Implement the AsRawFd/AsRawHandle for tokio::fs::File

### ISSUE THREAD

**Issue by svartalf** [tokio-rs/tokio#1364]
`tokio::fs::File` should has the [std::os::windows::io::AsRawHandle](https://doc.rust-lang.org/std/os/windows/io/trait.AsRawHandle.html) and [std::os::unix::io::AsRawFd](https://doc.rust-lang.org/std/os/unix/io/trait.AsRawFd.html) implementations.

It was mentioned before in #674, but it is kinda about a different thing, so I thought it's worth to create a new issue.

**Comment by carllerche** [comment]
Closed by #1827
