### ISSUE TITLE
Consider doing something similar to scope::spawn from crossbeam-utils

### ISSUE THREAD

**Issue by j-t-d** [tokio-rs/tokio#137]
It'd be really neat to be able to drop the 'static lifetime requirement on spawn. Would it be possible to extend the spawn api to be similar to Crossbeam's scoped threads? 

Right now I'm using Arc<AllTheThings> for immutable references that need to be shared between closures handled by spawn(). I'd love to just use the built-in lifetime management that Rust provides.

**Comment by kpp** [comment]
Please read this series of articles: https://boats.gitlab.io/blog/post/2018-01-25-async-i-self-referential-structs/

**Comment by carllerche** [comment]
Supporting lifetimes is plausible if you use `CurrentThread::block_on` (or `block_on_all`). Besides that, supporting lifetimes gets pretty tricky and would require a typed executor (an executor that only spawns futures of a specified type).

As mentioned above, the medium / long term plan is to use async / await as the strategy to support borrows.

**Comment by carllerche** [comment]
I believe this is more of a `futures` level discussion. If you would like to continue the discussion, could you open an issue [here](http://github.com/rust-lang-nursery/futures-rs)? Thanks.
