### ISSUE TITLE
tokio-tls should expose methods on TlsStream

### ISSUE THREAD

**Issue by sfackler** [tokio-rs/tokio#1383]
## Version

master

## Subcrates

tokio-tls

## Description

`native_tls::TlsStream` has various methods defined to access the underlying stream, the peer's certificate, and channel binding information. Now that `tokio_tls::TlsStream` doesn't publicly expose the inner `native_tls` stream, it will need to directly define equivalent methods.

https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsStream.html

**Comment by campbellC** [comment]
It seems that [this was possible in v0.2.1](https://docs.rs/tokio-tls/0.2.1/src/tokio_tls/lib.rs.html#82) but in the latest alpha version the same function now drops [straight down to the underlying inner stream](https://github.com/tokio-rs/tokio/blob/master/tokio-tls/src/lib.rs#L169). Was this an intentional reversion? I would very much like access to the certificates of Tls connections.

**Comment by aklitzke** [comment]
I'd like to bump this. Ran into this issue as well, I would also like to access the underlying certificates, and other native tls methods on TlsStream would be handy. I had to hack up the library to get them.

**Comment by aloucks** [comment]
Any update on this? Would you accept a PR that added additional methods to get the native tls stream?

**Comment by carllerche** [comment]
cc @LucioFranco

**Comment by LucioFranco** [comment]
@aloucks sure! we are currently in the process of moving things to `tokio-rs/tls` so I'd be happy to accept a PR there.

**Comment by hbobenicio** [comment]
Is this issue solved with the merge?

**Comment by campbellC** [comment]
I’ve upgraded to the latest version and this works fine for me. This issue can be closed, thanks!

**Comment by hbobenicio** [comment]
Hey @campbellC , would you mind sharing your example?

**Comment by campbellC** [comment]
@hbobenicio sure - I'm using this [here](https://github.com/campbellC/third-wheel/blob/master/src/http_proxy/mod.rs#L170-L172) to pull out the certificate and then spoof the contents for a man-in-the-middle proxy clone that I'm writing.
