### ISSUE TITLE
Drop Sync bound on runtime builder's after_start and before_stop

### ISSUE THREAD

**Issue by zimond** [tokio-rs/tokio#1389]
Current runtime builder's `after_start` and `before_stop` has a `Sync` bound. As the callbacks are specified for each thread, it's hard to inject thread-local variables ( `Rc` for example) in these hooks when `Sync` are needed. It seems there's no need to use those bounds.

**Comment by carllerche** [comment]
A single callback is passed to the threadpool builder and called concurrently from each worker thread. This is the source of the `Sync` requirement.
