### ISSUE TITLE
Is Handle Send + Sync?

### ISSUE THREAD

**Issue by cetra3** [tokio-rs/tokio#139]
The [RFC](https://github.com/tokio-rs/tokio-rfcs/pull/3) speaks about Handle becoming Send + Sync, but the [current implementation](https://github.com/tokio-rs/tokio/blob/master/src/reactor/mod.rs#L70) does not appear so.

**Comment by carllerche** [comment]
Those markers are derived by the compiler. If you look a bit further down there is an assertion that checks that those bounds are met.

**Comment by cetra3** [comment]
@carllerche Ok, it does look like `sync::Weak` is Send + Sync, but the [docs](https://github.com/tokio-rs/tokio/blob/master/src/reactor/mod.rs#L121) still say this about the handle (which is why I was confused):

```
Returns a handle to this event loop which cannot be sent across threads
but can be used as a proxy to the event loop itself.
```

I've submitted a PR to change the wording.

**Comment by carllerche** [comment]
Thanks, that is carry over from the old code base.
