### ISSUE TITLE
Should be able to poll on a &TcpListener

### ISSUE THREAD

**Issue by jethrogb** [tokio-rs/tokio#1413]
## Version

0.1.x

## Subcrates

tokio-tcp

## Description

Accepting a connection in `std` doesn't require mutable access to the `TcpListener`, so polling for the same should also not require it. However, there is currently no way to poll a `&TcpListener`.

`TcpStream` does support this through `impl AsyncRead|AsyncWrite for &'_ TcpStream` (although this was recently [removed in master](https://github.com/tokio-rs/tokio/pull/1120#discussion_r312209384))

**Comment by carllerche** [comment]
Can you describe why you want this? In general, `TcpStream` supports `Sync` but `TcpStream` does not support concurrent polling of `poll_read`. This is why `&mut self` is used.

**Comment by jethrogb** [comment]
Why wouldn't it support concurrent polling? As mentioned it used to.

**Comment by jethrogb** [comment]
> `TcpStream` does not support concurrent polling of `poll_read`

As mentioned this is supported through `impl AsyncRead|AsyncWrite for &'_ TcpStream`

**Comment by carllerche** [comment]
@jethrogb one task can call `poll_ready` concurrently to another calling `poll_write`, but two tasks cannot concurrently call `poll_read`. This is due to only one one task being notified.

Could you describe the use case? There could be a better way to model what you are trying to do.

**Comment by Darksonn** [comment]
This is not a feature we want for now. Split the `TcpStream` instead.

**Comment by jethrogb** [comment]
@Darksonn not sure what you're talking about? This issue is about TcpListener, not TcpStream.

**Comment by Darksonn** [comment]
Oh sorry, I misread the issue title.

**Comment by Darksonn** [comment]
Still, I don't think this is possible with how mio works. When you poll something, only the last used `Waker` is notified of updates, so if you poll it from many places, only one of them will actually work.

**Comment by jethrogb** [comment]
That seems fine, the woken up place will accept a connection and other place will get woken up next time?

**Comment by Darksonn** [comment]
No, if you poll it from two places, one of them will keep getting all of the connections and the other is never woken up again. This is because only the last waker is woken.

**Comment by carllerche** [comment]
This is covered by #2779 and will be supported once that lands.
