### ISSUE TITLE
IntoRawFd implementations missing

### ISSUE THREAD

**Issue by jethrogb** [tokio-rs/tokio#1414]
## Version

0.1.x

## Subcrates

tokio-tcp

## Description

`TcpStream` and `TcpListener` implement `AsRawFd` but not `IntoRawFd`. `IntoRawFd` is needed to drop the `TcpStream` or `TcpListener` without closing the connection.

(There's also no `FromRawFd` but these can be emulated using the `from_std` functions)

**Comment by Selicre** [comment]
IIRC, I asked about this before and the issue was `mio` managing its own buffers. Does that mean that this is planned to be changed, and does this mean that you would be able to pass the socket to other applications?

**Comment by carllerche** [comment]
My assumption is IntoRawFd is Unix only so that is fine.

**Comment by jethrogb** [comment]
I guess on Windows one would want to do the same with `IntoRawHandle`

**Comment by carllerche** [comment]
We need mio 0.7 for this.

**Comment by carllerche** [comment]
Blocked on mio 0.7. Adding this will be part of that updated. I don't think we need a dedicated issue open at the moment as progress is blocked.
