### ISSUE TITLE
tokio 0.2.0: io-compat not available for UnixStream and TCPStream

### ISSUE THREAD

**Issue by jedisct1** [tokio-rs/tokio#1417]
## 0.2.0

│   │   │   └── tokio-io v0.1.12
│   │   └── tokio-io v0.1.12 (*)
│   │   └── tokio-buf v0.1.1
│   ├── tokio v0.1.22
│   │   ├── tokio-current-thread v0.1.6
│   │   │   └── tokio-executor v0.1.8
│   │   ├── tokio-executor v0.1.8 (*)
│   │   ├── tokio-io v0.1.12 (*)
│   │   ├── tokio-reactor v0.1.9
│   │   │   ├── tokio-executor v0.1.8 (*)
│   │   │   ├── tokio-io v0.1.12 (*)
│   │   │   └── tokio-sync v0.1.6
│   │   ├── tokio-threadpool v0.1.15
│   │   │   └── tokio-executor v0.1.8 (*)
│   │   └── tokio-timer v0.2.11
│   │       └── tokio-executor v0.1.8 (*)
│   ├── tokio-buf v0.1.1 (*)
│   ├── tokio-executor v0.1.8 (*)
│   ├── tokio-io v0.1.12 (*)
│   ├── tokio-reactor v0.1.9 (*)
│   ├── tokio-tcp v0.1.3
│   │   ├── tokio-io v0.1.12 (*)
│   │   └── tokio-reactor v0.1.9 (*)
│   ├── tokio-threadpool v0.1.15 (*)
│   ├── tokio-timer v0.2.11 (*)
└── tokio v0.2.0-alpha.1
    ├── tokio-codec v0.2.0-alpha.1
    │   └── tokio-io v0.2.0-alpha.1
    ├── tokio-current-thread v0.2.0-alpha.1
    │   └── tokio-executor v0.2.0-alpha.1
    ├── tokio-executor v0.2.0-alpha.1 (*)
    ├── tokio-fs v0.2.0-alpha.1
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-threadpool v0.2.0-alpha.1
    │       ├── tokio-executor v0.2.0-alpha.1 (*)
    │       └── tokio-sync v0.2.0-alpha.1
    ├── tokio-io v0.2.0-alpha.1 (*)
    ├── tokio-macros v0.2.0-alpha.1
    ├── tokio-reactor v0.2.0-alpha.1
    │   ├── tokio-executor v0.2.0-alpha.1 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    ├── tokio-sync v0.2.0-alpha.1 (*)
    ├── tokio-tcp v0.2.0-alpha.1
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-reactor v0.2.0-alpha.1 (*)
    ├── tokio-threadpool v0.2.0-alpha.1 (*)
    ├── tokio-timer v0.3.0-alpha.1
    │   ├── tokio-executor v0.2.0-alpha.1 (*)
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    ├── tokio-udp v0.2.0-alpha.1
    │   └── tokio-reactor v0.2.0-alpha.1 (*)
    ├── tokio-uds v0.3.0-alpha.1
    │   ├── tokio-codec v0.2.0-alpha.1 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-reactor v0.2.0-alpha.1 (*)

## Platform

Darwin bbq.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

## Description

I'm trying to use Unix and TCP sockets created with `tokio 0.2.0` with `hyper`, that hasn't been updated for `future 0.3`.

Using `futures-compat` with the `io-compat` feature flag, I could call `compat()` on Unix and TCP streams created by `romio` so that they could be accepted by `hyper`'s `Http::serve_connection()`.

But with `tokio 0.2.0`, the `compat()` method is not available on `TcpStream` and `UnixStream`:

```text
   = note: the method `compat` exists but the following trait bounds were not satisfied:
           `&mut tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::Future01CompatExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncRead01CompatExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncWrite01CompatExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::io::AsyncReadExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::sink::SinkExt<_>`
           `&mut tokio_tcp::stream::TcpStream : futures_util::task::spawn::SpawnExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::try_future::TryFutureExt`
           `&mut tokio_tcp::stream::TcpStream : futures_util::try_stream::TryStreamExt`
           `&tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::Future01CompatExt`
           `&tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncRead01CompatExt`
           `&tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncWrite01CompatExt`
           `&tokio_tcp::stream::TcpStream : futures_util::io::AsyncReadExt`
           `&tokio_tcp::stream::TcpStream : futures_util::sink::SinkExt<_>`
           `&tokio_tcp::stream::TcpStream : futures_util::task::spawn::SpawnExt`
           `&tokio_tcp::stream::TcpStream : futures_util::try_future::TryFutureExt`
           `&tokio_tcp::stream::TcpStream : futures_util::try_stream::TryStreamExt`
           `tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::Future01CompatExt`
           `tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncRead01CompatExt`
           `tokio_tcp::stream::TcpStream : futures_util::compat::compat01as03::io::AsyncWrite01CompatExt`
           `tokio_tcp::stream::TcpStream : futures_util::io::AsyncReadExt`
           `tokio_tcp::stream::TcpStream : futures_util::sink::SinkExt<_>`
           `tokio_tcp::stream::TcpStream : futures_util::task::spawn::SpawnExt`
           `tokio_tcp::stream::TcpStream : futures_util::try_future::TryFutureExt`
           `tokio_tcp::stream::TcpStream : futures_util::try_stream::TryStreamExt`
```

**Comment by LucioFranco** [comment]
@jedisct1 so I believe the compat layer provided by futures-util-preview compats it with futures-io not tokio-io which are different traits. You can use https://github.com/nemo157/futures-tokio-compat/ to compat between the futures-io and tokio-io crates.

**Comment by jedisct1** [comment]
Thank you @LucioFranco !

I'm going to try that one, then.

Thank again for your help!
