### ISSUE TITLE
Update to futures `0.3.0-alpha.18`

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#1423]
Now that https://github.com/rust-lang-nursery/futures-rs/pull/1789 has been merged we can update tokio to this new version of futures.

**Comment by taiki-e** [comment]
Blocked on https://github.com/carllerche/loom/pull/35 (I received "failed to select a version" error when trying to do this.)

**Comment by carllerche** [comment]
We probably want to do #1264 before pushing out another release, otherwise things are going to be pretty painful.

**Comment by LucioFranco** [comment]
Agreed we should combine
