### ISSUE TITLE
Reimplement Core::run

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#143]
`tokio-core`'s `Core::run` method evaluated a future to completion, then returned the result.  `tokio` currently lacks any equivalent.  `current_thread::spawn`is the closest, but it can't return a result.  Please consider adding an equivalent method to `tokio`.

**Comment by carllerche** [comment]
This is included as part of #141. 🍾

**Comment by carllerche** [comment]
That PR has landed. You can now use `CurrentThread::block_on` which is equivalent.

**Comment by asomers** [comment]
Thanks.  I'm using `CurrentThread::block_on_all` and it's working.  I'm relying on the ability to call `Handle::current` outside of the `Reactor` loop, though, and I'm not sure that's guaranteed to work.

**Comment by carllerche** [comment]
Could you describe a bit more what specifically you are trying to achieve?

**Comment by asomers** [comment]
See https://github.com/tokio-rs/tokio/issues/153
