### ISSUE TITLE
udp: `UdpFramed` violates Decode impl contract

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#1443]
Note: This is an issue that is in 0.1.x and in 0.2.x. Any fix should be backported.

`UdpFramed` violates the decode contract by not attempting to continue decoding past the first discrete item if there is more data in the buffer. 

Correct Framed implementation https://github.com/tokio-rs/tokio/blob/v0.1.x/tokio-io/src/framed_read.rs#L199

and incorrect https://github.com/tokio-rs/tokio/blob/v0.1.x/tokio-io/src/framed_read.rs#L199

This is fixable by just looping and calling decode until None is returned. This is fine since udp datagrams contain all the bytes and there will never be more bytes for that "buffer". This would allow a user to use something like the lines codec with udp where multiple lines are packed into the datagram.

**Comment by JohnDoneth** [comment]
I am aiming to take a stab at this issue. If I'm understanding correctly, reading a `UdpPacket` with multiple lines would prove that `UdpFramed` no longer violates the Decode contract. Should that be added as a test then?

**Comment by LucioFranco** [comment]
@JohnDoneth yup! I would actually really really like if you could try to implement this on top of the `v0.1.x` branch so that we can get it released as part of a `0.1` release. Then we can back port it to master.

**Comment by udoprog** [comment]
From a question on Discord, and somewhat relevant.
The current master implementation of `UdpFramed` treats a `Decoder` returning `Ok(None)` as end of stream by propagating it ([here](https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/udp/frame.rs#L67)). This is seemingly incorrect according to the contract of `Decoder` where `Ok(None)` means that it doesn't have enough bytes to decode the frame. We should probably attempt another read on the underlying socket instead when this happens, or return an error. But this might be hard since the error type is opaque. Not sure what the best solution is!

**Comment by sfackler** [comment]
UDP packets aren't guaranteed to arrive in order (or arrive at all). How is a multi-packet message supposed to be reliably decoded at all?

**Comment by udoprog** [comment]
@sfackler I wasn't trying to imply to issue another read to add to the existing buffer, only to decode the next frame instead of terminating the stream.

**Comment by LucioFranco** [comment]
@udoprog yeah using `decode_eof` makes sense with udp but if you need mutli packet framing then you prob wanna write your own version.

**Comment by LucioFranco** [comment]
We applied the `decode_eof` change to `0.1` but not `0.2`

**Comment by udoprog** [comment]
> if you need mutli packet framing then you prob wanna write your own version.
I've clarified my initial comment since it seems to confuse people. I didn't intend to decode multiple packets as a frame. But to decode the next frame to avoid terminating the stream or returning an error.

**Comment by Darksonn** [comment]
Would #2368 fix this? (except v0.1 backport issues?)

**Comment by JohnDoneth** [comment]
I believe this can be closed now that #1444 and #1445 are both merged.

ping @LucioFranco
