### ISSUE TITLE
udp, uds: consider defining a datagram trait

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1458]
Both UDP and UDS have a framed implementation. These two implementations are similar, which makes it seem like there should be a trait implemented by both sockets and the framing code could be moved into tokio-codec.

cc @Ralith

**Comment by redtankd** [comment]
Since we have `tokio::codec::Framed`，why need a different UdpFramed?

**Comment by carllerche** [comment]
Primarily because a stream based `Framed` works differently than a datagram based `Framed`.

**Comment by Darksonn** [comment]
This is very low priority. If someone wants this, please open an issue or PR with a proposal for how to implement it.
