### ISSUE TITLE
Starting the timer causes panic.

### ISSUE THREAD

**Issue by szagi3891** [tokio-rs/tokio#1466]
## Version
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.39.0-nightly (bdfd698f3 2019-08-16)

```
oem@oem-Inspiron-5767 ~/Desktop/rust_async_timer_error $ cargo-tree tree
    Updating crates.io index
async_rs v0.1.0 (/home/oem/Desktop/rust_async_timer_error)
├── async-std v0.99.3
│   ├── async-task v1.0.0
│   │   └── crossbeam-utils v0.6.6
│   │       ├── cfg-if v0.1.9
│   │       └── lazy_static v1.3.0
│   │           └── spin v0.5.1
│   ├── cfg-if v0.1.9 (*)
│   ├── crossbeam-channel v0.3.9
│   │   └── crossbeam-utils v0.6.6 (*)
│   ├── futures-preview v0.3.0-alpha.17
│   │   ├── futures-channel-preview v0.3.0-alpha.17
│   │   │   ├── futures-core-preview v0.3.0-alpha.17
│   │   │   └── futures-sink-preview v0.3.0-alpha.17
│   │   │       └── futures-core-preview v0.3.0-alpha.17 (*)
│   │   ├── futures-core-preview v0.3.0-alpha.17 (*)
│   │   ├── futures-executor-preview v0.3.0-alpha.17
│   │   │   ├── futures-channel-preview v0.3.0-alpha.17 (*)
│   │   │   ├── futures-core-preview v0.3.0-alpha.17 (*)
│   │   │   ├── futures-util-preview v0.3.0-alpha.17
│   │   │   │   ├── futures-channel-preview v0.3.0-alpha.17 (*)
│   │   │   │   ├── futures-core-preview v0.3.0-alpha.17 (*)
│   │   │   │   ├── futures-io-preview v0.3.0-alpha.17
│   │   │   │   ├── futures-sink-preview v0.3.0-alpha.17 (*)
│   │   │   │   ├── memchr v2.2.1
│   │   │   │   ├── pin-utils v0.1.0-alpha.4
│   │   │   │   └── slab v0.4.2
│   │   │   └── num_cpus v1.10.1
│   │   │       └── libc v0.2.62
│   │   ├── futures-io-preview v0.3.0-alpha.17 (*)
│   │   ├── futures-sink-preview v0.3.0-alpha.17 (*)
│   │   └── futures-util-preview v0.3.0-alpha.17 (*)
│   ├── futures-timer v0.3.0
│   │   ├── futures-preview v0.3.0-alpha.17 (*)
│   │   └── pin-utils v0.1.0-alpha.4 (*)
│   ├── lazy_static v1.3.0 (*)
│   ├── log v0.4.8
│   │   └── cfg-if v0.1.9 (*)
│   ├── memchr v2.2.1 (*)
│   ├── mio v0.6.19
│   │   ├── iovec v0.1.2
│   │   │   └── libc v0.2.62 (*)
│   │   ├── libc v0.2.62 (*)
│   │   ├── log v0.4.8 (*)
│   │   ├── net2 v0.2.33
│   │   │   ├── cfg-if v0.1.9 (*)
│   │   │   └── libc v0.2.62 (*)
│   │   └── slab v0.4.2 (*)
│   ├── mio-uds v0.6.7
│   │   ├── iovec v0.1.2 (*)
│   │   ├── libc v0.2.62 (*)
│   │   └── mio v0.6.19 (*)
│   ├── num_cpus v1.10.1 (*)
│   ├── pin-utils v0.1.0-alpha.4 (*)
│   └── slab v0.4.2 (*)
└── tokio v0.2.0-alpha.1
    ├── bytes v0.4.12
    │   ├── byteorder v1.3.2
    │   └── iovec v0.1.2 (*)
    ├── futures-core-preview v0.3.0-alpha.17 (*)
    ├── futures-sink-preview v0.3.0-alpha.17 (*)
    ├── futures-util-preview v0.3.0-alpha.17 (*)
    ├── num_cpus v1.10.1 (*)
    ├── tokio-codec v0.2.0-alpha.1
    │   ├── bytes v0.4.12 (*)
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-sink-preview v0.3.0-alpha.17 (*)
    │   ├── log v0.4.8 (*)
    │   └── tokio-io v0.2.0-alpha.1
    │       ├── bytes v0.4.12 (*)
    │       ├── futures-core-preview v0.3.0-alpha.17 (*)
    │       ├── log v0.4.8 (*)
    │       └── memchr v2.2.1 (*)
    ├── tokio-current-thread v0.2.0-alpha.1
    │   ├── crossbeam-channel v0.3.9 (*)
    │   └── tokio-executor v0.2.0-alpha.1
    ├── tokio-executor v0.2.0-alpha.1 (*)
    ├── tokio-fs v0.2.0-alpha.1
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-util-preview v0.3.0-alpha.17 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-threadpool v0.2.0-alpha.1
    │       ├── crossbeam-deque v0.7.1
    │       │   ├── crossbeam-epoch v0.7.2
    │       │   │   ├── arrayvec v0.4.11
    │       │   │   │   └── nodrop v0.1.13
    │       │   │   ├── cfg-if v0.1.9 (*)
    │       │   │   ├── crossbeam-utils v0.6.6 (*)
    │       │   │   ├── lazy_static v1.3.0 (*)
    │       │   │   ├── memoffset v0.5.1
    │       │   │   │   [build-dependencies]
    │       │   │   │   └── rustc_version v0.2.3
    │       │   │   │       └── semver v0.9.0
    │       │   │   │           └── semver-parser v0.7.0
    │       │   │   └── scopeguard v1.0.0
    │       │   └── crossbeam-utils v0.6.6 (*)
    │       ├── crossbeam-queue v0.1.2
    │       │   └── crossbeam-utils v0.6.6 (*)
    │       ├── crossbeam-utils v0.6.6 (*)
    │       ├── futures-core-preview v0.3.0-alpha.17 (*)
    │       ├── futures-util-preview v0.3.0-alpha.17 (*)
    │       ├── lazy_static v1.3.0 (*)
    │       ├── log v0.4.8 (*)
    │       ├── num_cpus v1.10.1 (*)
    │       ├── slab v0.4.2 (*)
    │       ├── tokio-executor v0.2.0-alpha.1 (*)
    │       └── tokio-sync v0.2.0-alpha.1
    │           ├── fnv v1.0.6
    │           ├── futures-core-preview v0.3.0-alpha.17 (*)
    │           ├── futures-sink-preview v0.3.0-alpha.17 (*)
    │           └── futures-util-preview v0.3.0-alpha.17 (*)
    ├── tokio-io v0.2.0-alpha.1 (*)
    ├── tokio-macros v0.2.0-alpha.1
    │   ├── proc-macro2 v0.4.30
    │   │   └── unicode-xid v0.1.0
    │   ├── quote v0.6.13
    │   │   └── proc-macro2 v0.4.30 (*)
    │   └── syn v0.15.44
    │       ├── proc-macro2 v0.4.30 (*)
    │       ├── quote v0.6.13 (*)
    │       └── unicode-xid v0.1.0 (*)
    ├── tokio-reactor v0.2.0-alpha.1
    │   ├── crossbeam-utils v0.6.6 (*)
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── lazy_static v1.3.0 (*)
    │   ├── log v0.4.8 (*)
    │   ├── mio v0.6.19 (*)
    │   ├── num_cpus v1.10.1 (*)
    │   ├── parking_lot v0.9.0
    │   │   ├── lock_api v0.3.1
    │   │   │   └── scopeguard v1.0.0 (*)
    │   │   └── parking_lot_core v0.6.2
    │   │       ├── cfg-if v0.1.9 (*)
    │   │       ├── libc v0.2.62 (*)
    │   │       └── smallvec v0.6.10
    │   │       [build-dependencies]
    │   │       └── rustc_version v0.2.3 (*)
    │   │   [build-dependencies]
    │   │   └── rustc_version v0.2.3 (*)
    │   ├── slab v0.4.2 (*)
    │   ├── tokio-executor v0.2.0-alpha.1 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    │   [dev-dependencies]
    │   └── num_cpus v1.10.1 (*)
    ├── tokio-sync v0.2.0-alpha.1 (*)
    ├── tokio-tcp v0.2.0-alpha.1
    │   ├── bytes v0.4.12 (*)
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-util-preview v0.3.0-alpha.17 (*)
    │   ├── iovec v0.1.2 (*)
    │   ├── mio v0.6.19 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-reactor v0.2.0-alpha.1 (*)
    ├── tokio-threadpool v0.2.0-alpha.1 (*)
    ├── tokio-timer v0.3.0-alpha.1
    │   ├── crossbeam-utils v0.6.6 (*)
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-util-preview v0.3.0-alpha.17 (*)
    │   ├── slab v0.4.2 (*)
    │   ├── tokio-executor v0.2.0-alpha.1 (*)
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    │   [dev-dependencies]
    │   └── tokio-sync v0.2.0-alpha.1 (*)
    ├── tokio-udp v0.2.0-alpha.1
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-util-preview v0.3.0-alpha.17 (*)
    │   ├── log v0.4.8 (*)
    │   ├── mio v0.6.19 (*)
    │   └── tokio-reactor v0.2.0-alpha.1 (*)
    ├── tokio-uds v0.3.0-alpha.1
    │   ├── bytes v0.4.12 (*)
    │   ├── futures-core-preview v0.3.0-alpha.17 (*)
    │   ├── futures-util-preview v0.3.0-alpha.17 (*)
    │   ├── iovec v0.1.2 (*)
    │   ├── libc v0.2.62 (*)
    │   ├── log v0.4.8 (*)
    │   ├── mio v0.6.19 (*)
    │   ├── mio-uds v0.6.7 (*)
    │   ├── tokio-codec v0.2.0-alpha.1 (*)
    │   ├── tokio-io v0.2.0-alpha.1 (*)
    │   └── tokio-reactor v0.2.0-alpha.1 (*)
    └── tracing-core v0.1.5
        ├── lazy_static v1.3.0 (*)
        ├── lazy_static v1.3.0 (*)
        └── spin v0.5.1 (*)
    [dev-dependencies]
    ├── futures-util-preview v0.3.0-alpha.17 (*)
    └── num_cpus v1.10.1 (*)
```

## Platform
Linux oem-Inspiron-5767 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Subcrates
tokio-timer

## Description
I wanted to run timers from two different libraries. While performing the timer from Tokyo there was a panic

```
#![feature(async_await)]
use async_std::task;
use std::time::Duration;

use async_std::io;
use tokio::timer::Delay;

fn main() {
    println!("Hello, world! -- dd");

    task::block_on(async {
        io::timeout(Duration::from_secs(5), async {
            let stdin = io::stdin();
            let mut line = String::new();
            let n = stdin.read_line(&mut line).await?;
            Ok(())
        })
        .await;

        println!("timeout1 zaszedł");

        let when = tokio::clock::now() + Duration::from_millis(100);
        Delay::new(when).await;
        println!("100 ms have elapsed");

    });

}
```

When I run command cargo run, then I receive this error :

     Running `target/debug/async_rs`
Hello, world! -- dd
timeout1 zaszedł
thread 'async-task-driver' panicked at 'timer error: timer is shutdown', /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.1/src/delay.rs:112:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: <tokio_timer::delay::Delay as core::future::future::Future>::poll
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.1/src/delay.rs:112
  10: std::future::poll_with_tls_context::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  11: std::future::get_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:110
  12: std::future::poll_with_tls_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  13: async_rs::main::{{closure}}
             at src/main.rs:23
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  15: std::future::set_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:78
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  17: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/panic.rs:334
  18: <futures_util::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/catch_unwind.rs:29
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/panic.rs:315
  20: std::panicking::try::do_call
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  22: std::panicking::try
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/panicking.rs:275
  23: std::panic::catch_unwind
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/panic.rs:394
  24: <futures_util::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.17/src/future/catch_unwind.rs:29
  25: std::future::poll_with_tls_context::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  26: std::future::get_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:110
  27: std::future::poll_with_tls_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  28: async_std::task::pool::block_on::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:108
  29: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  30: std::future::set_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:78
  31: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  32: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libcore/future/future.rs:119
  33: std::future::poll_with_tls_context::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  34: std::future::get_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:110
  35: std::future::poll_with_tls_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:120
  36: async_std::task::pool::spawn_with_builder::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:213
  37: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  38: std::future::set_task_context
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:78
  39: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/future.rs:42
  40: async_task::raw::RawTask<F,R,S,T>::run
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-1.0.0/src/raw.rs:466
  41: async_task::task::Task<T>::run
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-1.0.0/src/task.rs:131
  42: <async_std::task::pool::spawn_with_builder::QUEUE as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}::{{closure}}::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:186
  43: async_std::task::pool::abort_on_panic
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:260
  44: <async_std::task::pool::spawn_with_builder::QUEUE as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:186
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/thread/local.rs:262
  46: std::thread::local::LocalKey<T>::with
             at /rustc/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/libstd/thread/local.rs:239
  47: <async_std::task::pool::spawn_with_builder::QUEUE as core::ops::deref::Deref>::deref::__static_ref_initialize::{{closure}}
             at /home/oem/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-0.99.3/src/task/pool.rs:183
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Repository for testing with this error:
https://github.com/szagi3891/rust_async_timer_error

**Comment by carllerche** [comment]
Thanks for the report.

Using timer APIs requires a timer to be running. Using the tokio runtime handles this detail for you. If you wish to use timer APIs outside of the tokio runtime, I would refer you to the documentation where it describes how to start a timer manually.

**Comment by szagi3891** [comment]
Probably there are also some problems with building documentation for this version:

https://docs.rs/crate/tokio-timer/0.3.0-alpha.1/builds/177453

```
$ rustc --version
rustc 1.38.0-nightly (95b1fe560 2019-07-20)
$ cratesfyi --version
cratesfyi 0.6.0 (f01dedd 2019-07-30)
$ cratesfyi ...
    Updating crates.io index
thread 'main' panicked at 'ErrorMessage {
    msg: "failed to select a version for the requirement `tokio = \"= 0.2.0-alpha.1\"`\n  candidate versions found which didn\'t match: 0.1.22, 0.1.21, 0.1.20, ...\n  location searched: crates.io index\nrequired by package `tokio-timer v0.3.0-alpha.1`",
}', src/bin/cratesfyi.rs:161:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by szagi3891** [comment]
@carllerche 

Could you give me the link to this documentation? I can't find it

**Comment by carllerche** [comment]
https://docs.rs/tokio-timer/0.3.0-alpha.2/tokio_timer/timer/index.html

- Create a `Timer`
- Pass handle to `set_default`
- Use timer APIs.

**Comment by szagi3891** [comment]
@carllerche 
Thank you. And are there any plans to make the executor more abstract? It would be nice to be able to call these two timers from different ecosystems on one executor.

**Comment by carllerche** [comment]
@szagi3891 what do you mean by this? You can call the timer from any ecosystem by following the steps above. What else do you have in mind?

**Comment by szagi3891** [comment]
@carllerche

I mean, this global variable with timer does not help when we want to use libraries from many ecosystems.

Maybe it'll be better:

```
fn main() {
    let mut rt = Runtime::new().unwrap();
    let mut rtStd = RuntimeStd::new();

    task::block_on(async {

        rtStd.io.timeout(Duration::from_secs(5), async {
            let stdin = io::stdin();
            let mut line = String::new();
            let n = stdin.read_line(&mut line).await?;
            Ok(())
        })
        .await;

        let when = tokio::clock::now() + Duration::from_millis(100);
        rt.Delay.new(when).await;
    });
}
```
Then it will be easier to compose feathers from different ecosystems.
