### ISSUE TITLE
Missing release for tokio-process?

### ISSUE THREAD

**Issue by alex** [tokio-rs/tokio#1477]
It looks like all the packages received alpha.2 releases yesterday, however tokio-process does not seem to have. Was this an accidental oversight?

**Comment by carllerche** [comment]
The plan was to move `tokio-process` into `tokio-net`, that didn't happen for the release... we will release alphas often. Are you blocked by this?

**Comment by alex** [comment]
I'm blocked from upgrading to alpha.2, nothing more :-)

**Comment by carllerche** [comment]
I can release tokio-process alpha-2, probably the easiest way to unblock. Next cycle it will be gone in favor of `tokio-net`.

**Comment by alex** [comment]
Sounds great. Thanks!

**Comment by carllerche** [comment]
I force pushed out a release... hopefully it isn't a dud.
