### ISSUE TITLE
Search results on docs.rs show futures under the tokio::io module

### ISSUE THREAD

**Issue by bIgBV** [tokio-rs/tokio#1478]
## Version
0.2.0-alpha.2

## Platform

Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
## Subcrates

tokio::io

## Description
When searching for `io` helpers on docs.rs, the methods from `AsyncReadExt` do not show up, instead unreachable links such as `tokio::io::_:Copy` show up.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/5019938/63285462-a6118a00-c26a-11e9-8cfb-9b3ce3dbd236.png">

Here is the link to search results which shows this behaviour: https://docs.rs/tokio/0.2.0-alpha.2/tokio/?search=copy

Searching for any of the io helper methods results in such results.

**Comment by carllerche** [comment]
This looks fixed.
