### ISSUE TITLE
Port AsyncRead/AsyncWrite Compat to Read/Write

### ISSUE THREAD

**Issue by dbcfd** [tokio-rs/tokio#1482]
## Version

0.2.0-alpha.X

## Subcrates

io

## Description

Currently tokio io provides its own AsyncRead and AsyncWrite traits. When dealing with blocking code, [futures](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/compat/compat03as01.rs#L255) provides a compatibility layer to turn the AsyncRead/AsyncWrite into Read/Write.

This relates to #1297 and #1479 while being finer grained. Lack of this functionality is impacting the ability of Reqwest to upgrade easily (specifically GZip decoding)

**Comment by dbcfd** [comment]
If a port of this functionality is desired, would be glad to do a PR for it.

**Comment by Nemo157** [comment]
We've been using https://github.com/rustasync/async-compression for supporting compression adaptors of `futures 0.3` types, if you want to add support of `tokio-io` traits there until they're stable enough to be supported by the upstream compression libraries I would be happy to (there may be good possibilities to reuse code across the different implementations).

**Comment by Darksonn** [comment]
I am closing this. Use the `async-compression` crate or similar instead.
