### ISSUE TITLE
cargo build occur error while use tokio and grpc together in Cargo.toml

### ISSUE THREAD

**Issue by dllhlx** [tokio-rs/tokio#149]
hi, I find cargo build occur error while use tokio and grpc library together in Cargo.toml, the error as below:
```
CMakeFiles/cmTC_d616b.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text.main+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_d616b] Error 1
gmake[1]: Leaving directory `/x/target/debug/build/qgrpcio-sys-3a0701b2bf9a9e20/out/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_d616b/fast] Error 2
```

**Comment by kpp** [comment]
@dllhlx Please provide your solution.

**Comment by carllerche** [comment]
This looks most likely like a problem w/ grpc.

**Comment by kpp** [comment]
Yes but this issue may occur in google search results so the solution will be appreciated.

**Comment by dllhlx** [comment]
@kpp  I find this problem disappear after I run ```cargo clear```, so I close this issue, maybe it is not a exception.
