### ISSUE TITLE
tokio example/connect.rs doesn't seem to work

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/tokio#1500]
## Version

From `v0.1.x` branch

## Platform

Darwin newair.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64 i386 MacBookAir8,1 Darwin

## Description

I can't seem to get the `connect.rs` example to work, but perhaps I am using it incorrectly.  From reading the comments in the example, it seems like it should work as client for `chat.rs` example.

I tried this code:

```
cargo run --example chat
     Running `target/debug/examples/chat`
server running on localhost:6142
```

confirmed works with telnet (as documented):

```
telnet localhost 6142
a
hello
```

causes the following output in chat server
```
`b"a"` is joining the chat
Received line (b"a") : Some(b"hello")
```

Then I run the `connect.rs` example :
```
cargo run --example connect 127.0.0.1:6142
b
hello
```
I expected to see this output in chat server: 
```
`b"b"` is joining the chat
Received line (b"b") : Some(b"hello")
```

Instead, I saw no output in chat server.

**Comment by carllerche** [comment]
Thanks for the detailed issue. It was super easy to repro and dig in.

It turns out that the issue is a bug in the `chat.rs` example. Specifically, `chat.rs` expects `\r\n` as line termination ([here](https://github.com/tokio-rs/tokio/blob/v0.1.x/tokio/examples/chat.rs#L335). This is what `telnet` sends, but when reading from stdin, only `\n` is sent.

**Comment by ultrasaurus** [comment]
Appreciate the quick response.  The examples are really nicely structured and commented for learning, so I took some time to understand the code a bit more.  I submitted PR for feedback on direction and can continue to work on that if it seems useful.
