### ISSUE TITLE
net: expose consistent tracing events

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#1504]
## Subcrates

- `tokio-net`

## Motivation

As of #1455, log records emitted by `tokio-net` have been replaced with `tracing` events. Because `tracing` spans allow user code to provide context to diagnostics emitted by libraries, diagnostics emitted by `tokio-net` have the potential to now be much easier to interpret than the prior unstructured `log` records. 

For example, when writing to or reading from a socket, higher-level code using `tokio-net` APIs might previously have logged the number of bytes written/read, plus contextual information from the domain of the application or higher-level library. If `tokio-net` also logged the number of bytes written/read, this may not be useful for debugging higher level library or application code, since `tokio-net`'s diagnostics would be missing the higher-level context.

With `tracing`, however, if higher-level code (say, `h2`) called `tokio-net`'s APIs inside a span representing a higher-level context (say, a HTTP/2 stream), any diagnostics emitted by the calls into `tokio-net` APIs would be located inside those spans. User code wouldn't be required to add those diagnostics. 

Currently, the diagnostics in most `tokio` crates are focused on _internal_ debugging — helping `tokio` maintainers diagnose problems with `tokio`. Since structured and contextual instrumentation makes it easier for users to consume diagnostics from libraries, we should focus on adding instrumentation that's valuable to users as well.

## Proposal

We should add diagnostic events to `tokio-net` that record data users are likely to want to use. We should use a consistent convention for how this data is structured(e.g. field naming) across modules, and document it so that users can consume it programmatically, such as by generating metrics.

I'd love to get input on what data it would be valuable to expose from `tokio-net`. As a starting point, here are some ideas:

+ When a socket is read from or written to, record the number of bytes read/written. 
  - The name of the field should should indicate read vs write, and that the value is a number of bytes (`read_bytes`/`written_bytes` or `read.bytes`/`write.bytes`?)
  - Consider namespacing the field under the kind of socket (for example, `udp.read_bytes`, `tcp.write_bytes`, etc)?
+ Framed codecs should record data about the frame being encoded/decoded, such as the current length, and emit events when a frame is completed. Some of this was added in #1455, but we should ensure that this data is structured consistently with data emitted by sockets.
+ Consider adding spans with local and remote addresses where applicable?

Part of #1186

**Comment by carllerche** [comment]
No longer relevant.
