### ISSUE TITLE
Connected framed UDP socket

### ISSUE THREAD

**Issue by zizhengtai** [tokio-rs/tokio#1506]
## Version

├── tokio-codec v0.2.0-alpha.3
│   └── tokio-io v0.2.0-alpha.3
├── tokio-io v0.2.0-alpha.3 (*)
├── tokio-net v0.2.0-alpha.3
│   ├── tokio-codec v0.2.0-alpha.3 (*)
│   ├── tokio-executor v0.2.0-alpha.3
│   │   ├── tokio-sync v0.2.0-alpha.3
│   ├── tokio-io v0.2.0-alpha.3 (*)
│   ├── tokio-sync v0.2.0-alpha.3 (*)
└── tokio-test v0.2.0-alpha.3
    ├── tokio v0.2.0-alpha.3
    │   ├── tokio-codec v0.2.0-alpha.3 (*)
    │   ├── tokio-executor v0.2.0-alpha.3 (*)
    │   ├── tokio-fs v0.2.0-alpha.3
    │   │   ├── tokio-executor v0.2.0-alpha.3 (*)
    │   │   ├── tokio-io v0.2.0-alpha.3 (*)
    │   │   └── tokio-sync v0.2.0-alpha.3 (*)
    │   ├── tokio-io v0.2.0-alpha.3 (*)
    │   ├── tokio-macros v0.2.0-alpha.3
    │   ├── tokio-net v0.2.0-alpha.3 (*)
    │   ├── tokio-sync v0.2.0-alpha.3 (*)
    │   ├── tokio-timer v0.3.0-alpha.3
    │   │   ├── tokio-executor v0.2.0-alpha.3 (*)
    │   │   └── tokio-sync v0.2.0-alpha.3 (*)
    ├── tokio-executor v0.2.0-alpha.3 (*)
    ├── tokio-io v0.2.0-alpha.3 (*)
    ├── tokio-sync v0.2.0-alpha.3 (*)
    └── tokio-timer v0.3.0-alpha.3 (*)

## Platform

Darwin localhost.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

## Description

`tokio_net::udp::UdpFramed` doesn't play nicely with a connected `UdpSocket`.

I tried this code:

```
let socket = UdpSocket::bind("[::]:0").await?;
socket.connect("stun.l.google.com:19302").await?;
let mut framed = UdpFramed::new(socket, MyCodec::new());
let peer_addr: SocketAddr = ...;
framed.send((my_item, peer_addr)).await?;  // panicked when unwrapped
```

I got this error:

```
thread 'client::tests::test_foo' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Error(TrackableError { kind: Other, cause: Some(Cause(Os { code: 56, kind: Other, message: "Socket is already connected" })), history: History([]) }) }', src/libcore/result.rs:1084:5
```

This is because `UdpFramed` expects an unconnected `UdpSocket` (and thus has the item type `(Item, SocketAddr)`). However, it'd be convenient to have something like a `UdpFramedConnected` that wraps a connected `UdpSocket`, and has the item type of simply `Item`.

**Comment by sunng87** [comment]
+1 for this. Also the `SocketAddr` in the `Sink` doesn't work nicely with current non-blocking `tokio_net::ToSocketAddrs` trait. Since `0.2.0-alpha.4`, tokio has built-in support for auto non-blocking DNS, hiding this detail in `connect` and `bind`. But the address resolution is still leaked to user in this `UdpFramed` sink, where we have to manually resolve the name to feed into the sink.

**Comment by carllerche** [comment]
:+1: we will have to think about how to unify all the cases.

**Comment by andrewhalle** [comment]
I tried reproducing this with the latest `tokio` on Linux with the following code (adapted from above):

```rust
// bytes = "1.6.0"
// futures = "0.3.30"
// tokio = { version = "1.37.0", features = ["full"] }
// tokio-util = { version = "0.7.11", features = ["net", "codec"] }

use std::net::SocketAddr;

use bytes::Bytes;
use futures::SinkExt as _;
use tokio::{io, net, net::UdpSocket};
use tokio_util::{codec::BytesCodec, udp::UdpFramed};

#[tokio::main]
async fn main() -> io::Result<()> {
    let socket = UdpSocket::bind("[::]:0").await?;
    socket.connect("stun.l.google.com:19302").await?;
    let mut framed = UdpFramed::new(socket, BytesCodec::new());
    let peer_addr: SocketAddr = net::lookup_host("stun.l.google.com:19302")
        .await
        .unwrap()
        .next()
        .unwrap();
    framed.send((Bytes::new(), peer_addr)).await?;
    Ok(())
}
```

I don't see a panic at `send()`. Does this issue still apply?

**Comment by Darksonn** [comment]
This is a very old issue and may not apply anymore. I'm going to close it. You can open a new issue if there is still a problem.
