### ISSUE TITLE
fs: Expose asyncify function

### ISSUE THREAD

**Issue by snsmac** [tokio-rs/tokio#1507]
Exposing this function would make it easier to integrate platform specific APIs into an async context without duplicating code

https://github.com/tokio-rs/tokio/blob/a59e096c4740204993ab2017dbb5098a35f93992/tokio-fs/src/lib.rs#L81-L88

Changing the function signature to 
```
pub async fn asyncify<F, T, E>(f: F) -> Result<T, E>
    where
        F: FnOnce() ->Result<T, E> + Send + 'static,
        T: Send + 'static,
        E: Send + 'static,
{
    sys::run(f).await
}
```

would make this even usable for functions that do not return an io::Result. (Like nix::Result)

If this change is wanted i can submit a PR

**Comment by carllerche** [comment]
This is just calling `blocking::run` (from tokio-executor). Is there a reason why this doesn't work?

**Comment by snsmac** [comment]
@carllerche It's definitely possible to use `blocking::run` manually. The reason why i would like to use the asyncify method is that I am afraid that my wrapping of methods and the one by tokio-fs could become different (like using a different executor) if there are changes to tokio-fs. But probably I am just overthinking this

**Comment by carllerche** [comment]
@snsmac things will evolve more before 0.2 final. I suggest tracking and bringing this discussion back up later when the executor / blocking stuff is more refined. As mentioned in the original PR, this is just an initial impl to unblock other work.

**Comment by carllerche** [comment]
I'll leave the issue open and tag it 0.2.

**Comment by carllerche** [comment]
The answer to this is to call: `tokio::task::spawn_blocking(....)` :+1:
