### ISSUE TITLE
test: assert_* macros formatting features are hard to use

### ISSUE THREAD

**Issue by RadicalZephyr** [tokio-rs/tokio#1511]
## Version
```
└── tokio-test v0.2.0-alpha.1
    ├── tokio-executor v0.2.0-alpha.1 (*)
    ├── tokio-io v0.2.0-alpha.1 (*)
    ├── tokio-sync v0.2.0-alpha.1 (*)
    └── tokio-timer v0.3.0-alpha.1 (*)
```

## Platform

Linux pop-os 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Subcrates

test

## Description

I was unable to actually utilize the advertised custom message feature of the `assert_*`  macros to take arbitrary formatting arguments.  Attempting to call them like so:

```rust
use tokio_test::{assert_pending, task::MockTask};

struct SomeFuture;
impl Future for SomeFuture {
    type Output = ();

    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        Poll::Ready(())
    }
}
impl Unpin for SomeFuture {}

#[derive(Debug)]
struct MyData;

#[test]
fn test_msg() {
    let mut task = MockTask::new();
    assert_pending!(task.poll(&mut SomeFuture), "custom-msg {:?}", MyData);
}
```

I expected this to both compile and when running tests to fail the `test_msg` test with this  message: 
```
thread 'test_msg' panicked at 'ready; value = (); custom-msg MyData', src/lib.rs:19:5
```

Instead, it fails to compile with this error message:

```
error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:19:49
   |
19 |     assert_pending!(task.poll(&mut SomeFuture), "custom-msg {:?}", MyData);
   |     --------------------------------------------^^^^^^^^^^^^^^^^^----------
   |     |                                           |
   |     |                                           creates a temporary which is freed while still in use
   |     temporary value is freed at the end of this statement
   |     borrow later used here
```

I cannot figure out how to use the custom formatting arguments correctly without this happening.

Also, I think the ergonomics of using the `tt` macro pattern type for the formatting arguments is quite poor, since I believe this means that many simple expressions would need to be wrapped in an explicit set of braces.  For instance, an `Enum::Variant` is not a single `tt`.  I believe it would be simpler to have the formatting elements be of pattern type `expr` would lead to the expected semantics of being able to use arbitrary expressions as formatting arguments.

**Comment by carllerche** [comment]
I'm guessing the problem is the comma? In the macro it is:

```rust
($e:expr, $($msg:tt),+) => {{
```

when it _probably_ should be:

```rust
($e:expr, $($msg:tt)+) => {{
```

Are you able to validate this and submit a PR (hopefully w/ some tests :heart:)?

**Comment by RadicalZephyr** [comment]
I'll look into it :)
