### ISSUE TITLE
Clarify Handle::current documentation

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#153]
The `Handle::current` documentation says that it will return a `Handle` to "the current reactor".  However, it seems to work even if there is no current reactor when I call it.  I can call `Handle::current` before creating any `Reactor`s, then pass the `Handle` into a `Reactor` with `current_thread::block_on_all` and everything works.  I assume that this is intended behavior, but the documentation makes it sound forbidden.  Could you please clarify the documentation?

Here's an example.  I call `Handle::current` on line 47, but don't create the `Reactor` until line 48.
https://github.com/asomers/tokio-file/blob/master/tests/file.rs#L47

**Comment by carllerche** [comment]
You are correct. This should be fixed.

**Comment by carllerche** [comment]
`Handle::current` is now deprecated and marked as `doc(hidden)`.
