### ISSUE TITLE
TcpStream padding inquiry

### ISSUE THREAD

**Issue by ivanceras** [tokio-rs/tokio#1530]
I have an HTTPS webserver using tokio with version
tokio = "0.1.22"

and let the byte stream passes through 2 proxies using tokio with version
tokio = "=0.2.0-alpha.2"

Both of this proxy is just using the [simple example](https://github.com/tokio-rs/tokio/blob/master/tokio/examples/proxy.rs) code:
```rust
    let (mut ri, mut wi) = inbound.split();
    let (mut ro, mut wo) = outbound.split();

    let client_to_server = ri.copy(&mut wo);
    let server_to_client = ro.copy(&mut wi);

```

These 2 proxies just dumbly passed whatever bytes that passed through the stream.
The way I read the bytes and write it back to the outbound stream is like this:
```rust
    let mut buff = vec![0; 32000];
    let mut len = ri.read(&mut buff).await?;
    let written = wo.write(&buf[0..len]).await?;
```

First proxy log:
![139](https://i.imgur.com/EvM1FSO.png)

Second proxy log:
![225](https://i.imgur.com/OTJfEDr.png)

I'm confused that the second proxy, somehow add a few more bytes such that the response packet becomes 225 in length. Why is it doing that? Is this a normal behavior?

The browser still receives the HTTPS traffic without problem.

What I'm trying to do, is pass a custom meta data information in between my proxies through the bytestream, but it seems I found an unexpected behavior on how TCP is streaming the data.

**Comment by hawkw** [comment]
Hi @ivanceras, are you still seeing this issue on the latest master version of tokio 0.2?

**Comment by ivanceras** [comment]
Hi @hawkw , this is not issue anymore. It was my misunderstanding of how streams and tls works in general.
