### ISSUE TITLE
Update tokio-process to v0.3.0-alpha.4

### ISSUE THREAD

**Issue by Luro02** [tokio-rs/tokio#1531]
## Version
tokio: v0.2.0-alpha-4
tokio-process: latest available version; v0.3.0-alpha-2

## Platform

Linux
## Subcrates

tokio-process (https://crates.io/crates/tokio-process)
## Description
I am unable to compile my crate, because of tokio-process
```
error: failed to select a version for `tokio-io`.
    ... required by package `tokio-process v0.3.0-alpha.2`
    ... which is depended on by `my_crate v0.1.0`
versions that meet the requirements `= 0.2.0-alpha.2` are: 0.2.0-alpha.2

all possible versions conflict with previously selected packages.

  previously selected package `tokio-io v0.2.0-alpha.4`
    ... which is depended on by `hyper v0.13.0-a.0 (https://github.com/hyperium/hyper#347a10eb)`
    ... which is depended on by `my_other_crate v0.1.0 `
    ... which is depended on by `my_crate v0.1.0`

failed to select a version for `tokio-io` which could resolve this conflict
```

**Comment by ipetkov** [comment]
Hi @Luro02, thanks for the report!

All the APIs from `tokio-process` have been moved to the new `tokio-net` crate, so please use that instead!

`tokio-process` is now deprecated (though we haven't gotten around to pushing out some deprecation warnings), but that's being tracked in #1469

Going to close this out, but feel free to reopen if you have other questions

**Comment by Luro02** [comment]
yeah I know about this, but I can't find it under "net" in the documentation:
https://docs.rs/tokio/0.2.0-alpha.4/tokio/net/index.html

**Comment by jothan** [comment]
@Luro02  Enable the process feature on tokio_net and run cargo doc
