### ISSUE TITLE
threadpools' `blocking()`  inside "main"'s `block_on` future

### ISSUE THREAD

**Issue by Blub** [tokio-rs/tokio#1532]
## Version

0.2.0-alpha.4

## Platform

linux

## Description

Futures running on the threadpool runtime's worker threads can use `tokio_executor::threadpool::blocking()`, but the "main" future running inside `block_on()` (as generated from `#[tokio::main]`) cannot, as it is not being executed in a worker thread.
Currently, this runtime's `block_on()` does not run in the context of a worker thread and will error with `'blocking' annotation used from outside the context of a thread pool`.

The threadpool runtime's documentation describe the notion of threads which can transition to and from a blocking I/O state. When explicitly using this runtime, it makes sense to also be able to use `tokio_executor::threadpool::blocking()` rather than the newly introduced
`tokio_executor::blocking::run()` (#1495) which builds a future waiting for a *separate* dedicated thread pool to do the work, and also doesn't act like an inline polling method.

What's the plan here? For now we have to work around this via:
```
let (tx, rx) = tokio::sync::oneshot::channel();
tokio::spawn(async move {
    tx.send(poll_fn(blocking(|| code())).await).unwrap();
});
rx.await.unwrap()
```

instead of using `#[tokio::main]`, but I think that `blocking()` could instead support this use case?

**Comment by carllerche** [comment]
There is a plan to fix this, but it requires some other work to be done first.

As a temporary measure, you can use `tokio_executor::blocking::run(...)` which takes a closure and runs that on a thread pool dedicated to blocking operations.

**Comment by jonhoo** [comment]
In Noria we have to use `threadpool::blocking` because we need to be able to block on a `poll_fn` that cannot move its arguments (i.e., the future isn't `'static`). This happens in a number of places, and would be very hard to change. Until there is a solution to this, that means that Noria cannot use `#[tokio::main]` or (perhaps more crucially) `#[tokio::test]`, which is quite unfortunate.

**Comment by Blub** [comment]
Okay so we now have a `block_in_place` vs `spawn_blocking`. `block_in_place` still cannot be used inside `#[tokio::main]` though (neither with `#[tokio::main(threaded_scheduler)]`).

**Comment by Darksonn** [comment]
This doesn't seem relevant anymore
