### ISSUE TITLE
Multiple threads spawning when using FramedWrite

### ISSUE THREAD

**Issue by evilbluebeaver** [tokio-rs/tokio#1542]
## Version

tokio v0.2.0-alpha.4
tokio-codec v0.2.0-alpha.4
tokio-io v0.2.0-alpha.4
tokio-executor v0.2.0-alpha.4
tokio-sync v0.2.0-alpha.4
tokio-fs v0.2.0-alpha.4
tokio-executor v0.2.0-alpha.4 (*)
tokio-io v0.2.0-alpha.4 (*)
tokio-sync v0.2.0-alpha.4 (*)
tokio-io v0.2.0-alpha.4 (*)
tokio-macros v0.2.0-alpha.4
tokio-net v0.2.0-alpha.4
tokio-codec v0.2.0-alpha.4 (*)
tokio-executor v0.2.0-alpha.4 (*)
tokio-io v0.2.0-alpha.4 (*)
tokio-sync v0.2.0-alpha.4 (*)
tokio-sync v0.2.0-alpha.4 (*)
tokio-timer v0.3.0-alpha.4
tokio-executor v0.2.0-alpha.4 (*)
tokio-sync v0.2.0-alpha.4 (*)
## Platform

Darwin EvilBeaver.local 19.0.0 Darwin Kernel Version 19.0.0: Sun Aug 18 23:37:31 PDT 2019; root:xnu-6153.0.166~17/RELEASE_X86_64 x86_64

## Description

There is such a code example

```
use futures::prelude::*;
use tokio;
use tokio::codec::{FramedRead, FramedWrite, LinesCodec};
use tokio::io::{stdin, stdout};
use tokio::prelude::*;
use tokio::sync::mpsc;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (mut tx_output, mut rx_output) = mpsc::unbounded_channel::<String>();

    tokio::spawn(async move {
        let mut output = FramedWrite::new(stdout(), LinesCodec::new());
        while let Some(line) = rx_output.recv().await {
>>          output.send(format!("OUT: {}", line)).await.unwrap();
        }
    });
    let mut input = FramedRead::new(stdin(), LinesCodec::new());
    while let Some(line) = input.next().await {
        let line = line.unwrap();
        tx_output.send(line.clone()).await.unwrap();
    }
    Ok(())
}

```
I push and hold Enter for a second and the number of system threads begins to grow rapidly.
```
PID        COMMAND   %CPU  TIME         #TH 
49564  tokio_role       0.0       00:00.51   34
```

But if I comment out the marked line it works as expected creating no more than 4 threads.
```
PID        COMMAND   %CPU  TIME         #TH
49395  tokio_role       0.0.      00:00.21   4    
```

Am I using it wrong or it's just a bug?

**Comment by carllerche** [comment]
Thanks for pointing this out. I think it probably is a bug somehow.

**Comment by jothan** [comment]
My guess is that after running a blocking task, the blocking pool thread races to increment num_idle while the app thread spawns another task. The app thread may see 0 idle threads and spawn another one.

This is just wild speculation for now.

https://github.com/tokio-rs/tokio/blob/b71b7b36bef9cc491c1fedebe52af96a6b285e4f/tokio-executor/src/blocking.rs#L104
