### ISSUE TITLE
tokio-tls broken on nightly-2019-09-10

### ISSUE THREAD

**Issue by dbcfd** [tokio-rs/tokio#1548]
## Version

0.3.0-alpha.4

## Subcrates
tokio-tls

## Description

Tokio is currently pinned to `nightly-2019-08-21`. `nightly-2019-09-10` is broken with 
```
    |
274 |         handshake(|s| self.0.connect(domain, s), stream).await
    |         --------------^^^^------------------------------
    |         |         |   |
    |         |         |   borrowed value does not live long enough
    |         |         value captured here
    |         a temporary with access to the borrow is created here ...
```

**Comment by davidbarsky** [comment]
This was tracked in https://github.com/tokio-rs/tokio/issues/1546—there's already a fix on master. In the mean time, you can:
- depend on Tokio from the master branch until a release is out,
- or pin your code to `nightly-2019-09-09`.

**Comment by dbcfd** [comment]
@davidbarsky #1547 doesn't change the rust toolchain version. Should there be a PR for that? The PR does fix the issue, but seems like regression could occur without a toolchain bump.

**Comment by theduke** [comment]
Could we get a alpha release with this fix?
