### ISSUE TITLE
Smooth transition from 0.1 to 0.2

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1549]
Original report: https://users.rust-lang.org/t/failed-to-port-mononoke-to-tokio-0-2-experience-report/32478

My read of this is that the primary issue is a lack of compat layers between 0.1 and 0.2.

## `tokio-compat`

The solution would be to provide a crate that implements a bridge runtime, setting up the required bits to run both 0.1 and 0.2 on the same runtime. Additionally, a compat layer between 0.1 and 0.2 traits (primarily read and write).

### Runtime

The `tokio-compat` crate would provide runtime types that mirror the API in Tokio 0.2. This runtime type would create both an 0.2 and 0.1 runtime simultaneously. It would *not* need to run two threadpool side by side, but it could bridge the two using a future compat layer. The compat runtime *would* need to spawn a single extra thread to run an 0.1 reactor & timer.

### APIs removed

Tokio 0.2 has hidden a number of APIs. For example, most of the I/O helper futures are now private. Same with `tcp::Incoming`. `tokio-compat` should provide versions of these futures. The specific strategy by which this could be done is TBD.

**Comment by farnz** [comment]
I'll file issues and attach them here for what I saw as the problems - the big issue is the bridge runtime, as you describe, then with some less significant issues around `AsyncRead`/`AsyncWrite`, one of which I think belongs to `futures` not `tokio`.

**Comment by farnz** [comment]
Issue #1551 for the async traits being out of sync between `tokio` and `futures`.

**Comment by farnz** [comment]
Issue #1552 for the runtime bridge, fleshing out what I want from it.

**Comment by farnz** [comment]
And rust-lang-nursery/futures-rs#1865 for the compat I/O issues I found, assuming that #1551 is fixed.

**Comment by vojtechkral** [comment]
@carllerche Thanks for looking into the `Incoming` problem. I think I thought it was a mistake rather than intent because `uds::Incoming` was/is public. What is the future intent for `incoming()` - will it return an existential type?

**Comment by h4x3rotab** [comment]
tokio-compat works as a charm! Looking forward to the regular release.

**Comment by hawkw** [comment]
Now that `tokio-compat` has been published for a while, I think we can close this.
