### ISSUE TITLE
`tokio-0.2.0-alpha4` `AsyncRead` and `AsyncWrite` traits are not the same as `futures-0.3.0-alpha18` versions.

### ISSUE THREAD

**Issue by farnz** [tokio-rs/tokio#1551]
`tokio-0.2`'s [`AsyncWrite`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/io/trait.AsyncWrite.html), [`AsyncRead`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/io/trait.AsyncRead.html) etc are out of sync with the `futures-0.3` versions - e.g. `tokio`'s `AsyncWrite` is implemented for `Vec<u8>`, while `futures`' [`AsyncWrite`](https://docs.rs/futures-preview/0.3.0-alpha.18/futures/io/trait.AsyncWrite.html) is implemented for `Cursor<T> where T: AsMut<[u8]>`.

Rather than supplying its own versions of these traits, could `tokio` reuse the `futures` versions?

**Comment by Nemo157** [comment]
See also https://github.com/tokio-rs/tokio/issues/1297

**Comment by carllerche** [comment]
Currently, the primary difference between the two traits is Tokio's reliance on `Buf` and `BufMut`. Adding these to `futures-io` has been proposed [here](https://github.com/rust-lang-nursery/futures-rs/issues/1818), but not accepted.

There are probably other issues that I would like to see addressed w/ the current traits (both futures-io and tokio), but on a personal note, I am punting on that until I am able to update Tokio to the latest mio & bytes crates.

**Comment by theduke** [comment]
So with `futures 0.3` out, what is the path forward here?

The `_buf` methods were not adopted, yet it would be really quite unfortunate if `tokio` continued to use different traits.

**Comment by jebrosen** [comment]
An idea that I think others have mentioned, but not posted here, would be for tokio to implement `futures_io::AsyncRead` for each type that also implements `tokio::io::AsyncRead`, under an optional dependency. This probably can't be done with a blanket impl, but a macro could be doable.

See also tokio-rs/tokio-compat#2 (adding I/O to tokio-compat)

**Comment by theduke** [comment]
Linking https://github.com/tokio-rs/tokio/pull/1744 for reference.

**Comment by tamird** [comment]
#1744 is now closer; @carllerche where should people be following along on efforts (if any) to converge `Async{Read,Write}` with those of `futures`?
