### ISSUE TITLE
Missing `process` feature

### ISSUE THREAD

**Issue by fominok** [tokio-rs/tokio#1559]
## Version 
0.2.0-alpha.4

## Subcrates 
tokio-net

## Description

Hello. I've tried to enable `process` feature, but it seems that it is unaccessable from tokio, the workarond for now is to put `tokio-net` directly into dependencies with this feature.

**Comment by ipetkov** [comment]
Thanks for the report @fominok!

Once #1561 lands it will be possible to access the `process` definitions directly from the `tokio` crate
