### ISSUE TITLE
Handle is hidden in the tokio 0.2

### ISSUE THREAD

**Issue by vorner** [tokio-rs/tokio#1565]
I'm playing with version 0.2.0-alpha.4.

When I want to create a [`TcpStream`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/net/struct.TcpStream.html#method.from_std) from the std stream, it wants a Handle. But:

* Clicking on that on the documentation page leads to a 404 page.
* Searching for Handle in the docs produce only the Handle in `current_thread` runtime.
* Looking at the [`Runtime`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/runtime/struct.Runtime.html) doesn't seem to have a way to get its handle in any way :-(.

I can use `Default::default()` to get some handle and it works, but this seems like something is not being publicly reexported/made available.

**Comment by carllerche** [comment]
The `runtime::Handle` type should cover all cases. You can initialize a runtime w/ **only** I/O enabled. In that case, it is identical to `reactor::Handle`.
