### ISSUE TITLE
Remove deprecated timer::Now

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1567]
the `Timer::new_with_now` and related traits have previously been deprecated, we should be able to remove them in master. It is replaced with configuring a `clock`.

**Comment by TheSamsa** [comment]
I'd like to try it, did some fiddeling but I am not 100% if I am doing the right thing you actually wan't! :eyes:

**Comment by aug2uag** [comment]
Sorry I was messing about with this, hadn't run tests and not reviewed the status!

**Comment by carllerche** [comment]
This was done on master :+1:
