### ISSUE TITLE
mpsc::Sender::send does not return the value back in case of error

### ISSUE THREAD

**Issue by endragor** [tokio-rs/tokio#1579]
## Version

tokio v0.2.0-alpha.5

## Description

In v0.2 API Sender's `send` method consumes the value and does not return it back in case of an error. It is not clear why it works that way. As I understand, the reason for returning error could be that the receiving side was closed while the sender was waiting. In such case the value was not sent and should be returned back.

Also, it would be nice to have the possible error reasons documented.

**Comment by carllerche** [comment]
Thanks for the report!

Tokio 0.2 final returns the value on error. #1865 expands on docs :+1:
