### ISSUE TITLE
Don't rename imports to _ in prelude

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#1593]
Please don't rename all those traits to `_` in prelude. It makes navigating the documentation of the crate much more difficult, especially since the all the links in the documentation go to `trait._.html`, which happens to be one of the `FutureExt` traits.

https://github.com/tokio-rs/tokio/blob/3a55aba251e445b1ff5e03ee2319d7a2920c1ee9/tokio/src/prelude.rs#L14-L27

**Comment by taiki-e** [comment]
> It makes navigating the documentation of the crate much more difficult, especially since the all the links in the documentation go to `trait._.html`, which happens to be one of the `FutureExt` traits.

I believe this can be avoided by using `#[doc(no_inline)]`. (see https://github.com/rust-lang-nursery/futures-rs/pull/1662#issuecomment-499792358)
