### ISSUE TITLE
Release new alpha/beta version adapte with rustc 1.39.0-beta

### ISSUE THREAD

**Issue by wangjia184** [tokio-rs/tokio#1612]
Rust 1.39 now is in beta channel and `async`/`await` keywords are stabilized.

future-preview released version [0.3.0-alpha.19](https://crates.io/crates/futures-preview/0.3.0-alpha.19) for this beta version.

Tokio version `tokio v0.2.0-alpha.5` cannot complie because it depends on `futures-core-preview 0.3.0-alpha.18` which cannot be compiled .

Please release a new alpha or beta version to update dependencies.

**Comment by Duddino** [comment]
I've managed to compile tokio on beta by just removing #![feature(async_await)] from every tokio file and dependency

**Comment by LucioFranco** [comment]
This has been done `0.2.0-alpha.6` is now out!
