### ISSUE TITLE
recv()/recv_from() on UdpSocket doesn't require a mutable reference

### ISSUE THREAD

**Issue by seirdb** [tokio-rs/tokio#1613]
## Version
0.2.0-alpha.5

## Platform
Linux

## Description
Currently, the recv/recv_from() functions require a mutable reference to the socket, although it doesn't seem necessary looking at the implementation.

The fact that they are requiring a mutable reference disallows someone to have an async task which await's on a socket, and an other one which updates it's configuration.

The following [example](https://gist.github.com/rust-play/99216ba39f9f41aaa283a334cef423f5) shows this issue, here we (can) get a runtime panic because we're trying to borrow() on the wrapping RefCell while also having a borrow_mut() open for awaiting on the receive. (The same would be true for a thread-safe version with a RwLock).

Is there a reason why this mutability is necessary? I've also noticed that during compilation no warning is issued about this.

The same is true by the way for sending.

**Comment by bartelsielski** [comment]
Just wanted to add that this is not true for standard library UdpSockets.

link: https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.recv

**Comment by carllerche** [comment]
Thanks for the report. I'm going to track this as part of #1624.
