### ISSUE TITLE
Feature-dependent dependencies are never selected

### ISSUE THREAD

**Issue by jsgf** [tokio-rs/tokio#1622]
## Version

git master

## Platform

all

## Subcrates

- tokio-net
- tokio-executor

## Description

[tokio/Cargo.toml](https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml#L84-L86) has:
```
[target.'cfg(feature = "tracing")'.dependencies]
tokio-net = { version = "=0.2.0-alpha.6", optional = true, path = "../tokio-net", features = ["tracing", "async-traits"] }
tokio-executor = { version = "=0.2.0-alpha.6", optional = true, path = "../tokio-executor", features = ["tracing"] }
```

According to Cargo's documentation, this does not work; the `cfg(feature = "tracing")` predicate will always evaluate to false. I think this only works because of the other unconditional dependency on tokio-net and tokio-executor above.

https://github.com/tokio-rs/tracing/issues/365 is a related issue, and https://github.com/rust-lang/cargo/issues/7442 is the Cargo issue which is mostly about lack of diagnostics for this issue.

**Comment by taiki-e** [comment]
Seems this was unintentionally fixed in #1680.
https://github.com/tokio-rs/tokio/pull/1680/files#diff-0a053cc4b37432b22b44e58a48f0ea81L83-L85
