### ISSUE TITLE
tokio_net::driver::Handle

### ISSUE THREAD

**Issue by jedisct1** [tokio-rs/tokio#1638]
`TcpStream::from_std()` requires a reactor `Handle`.

However,  the related `Handle` structure is not accessible without explicitly adding the `tokio_net` crate.

Is it intentional?

Or is there another way to get at least the default handle?

**Comment by hawkw** [comment]
You could use `Default::default()` to get the default handle without having to explicitly name the `Handle` type. For example:
```rust
let std_stream = std::net::TcpStream::connect("127.0.0.1:9999")?;
let mut stream = tokio::net::TcpStream::from_std(std_stream, &Default::default())?;
```
