### ISSUE TITLE
Any plan to support connecting via proxy?

### ISSUE THREAD

**Issue by kingluo** [tokio-rs/tokio#1644]
Just like golang, it provides proxy lib (https://godoc.org/golang.org/x/net/proxy), so that it supports `all_proxy` env var to specify the connect proxy, e.g. socks5 proxy.

Any plan to add this support in tokio or mio? For some app, it is very necessary.

**Comment by carllerche** [comment]
Doing so is out of scope for `tokio` / `mio` proper as it can live in external crates. That said, it could be useful to have an official answer.

I reserved https://crates.io/crates/tokio-proxy just in case. I would be happy for a contribution.

**Comment by kingluo** [comment]
> Doing so is out of scope for `tokio` / `mio` proper as it can live in external crates. That said, it could be useful to have an official answer.
> 
> I reserved https://crates.io/crates/tokio-proxy just in case. I would be happy for a contribution.

But `tokio`/`mio` should provide interface to accept proxy config.

Where's the source code of tokio-proxy?

**Comment by kingluo** [comment]
How about this?
https://github.com/kingluo/tokio-proxy

I make a `connect` function to connect target address via socks5 proxy.

**Comment by carllerche** [comment]
:+1: looks good.

I will close the issue as, for now, proxy is out of scope for tokio. good luck!

**Comment by kingluo** [comment]
Could you give the crate on the crates.io to me or add an maintainer for me? So that I could upload my codes to crates.io.
