### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#165]
A tracking issue for documentation improvements. Discussion around the content of the documentation should happen in the relevant issues.

This issue covers API, guide, and cookbook level docs. Items will be added and removed over time. This is currently not a comprehensive list.

# Guide documentation

Discussion issue: #13

* [ ]  Framing and codecs
* [ ] Implementing mini Tokio.
* [ ] Migration from tokio-core #138.
* [ ] Implementing custom I/O resources.
* [ ] Cancellation
* [ ] Backpressure

# API documentation

* [ ] `Handle::current` #153
* [ ] `PollEvented2` requires an overhaul.
* [ ] `tokio::spawn` requires additional docs / examples.

# Cookbook

Discussion issue: #86.

* [ ] Using oneshot to cancel an operation.

**Comment by kpp** [comment]
+ https://tokio.rs/blog/2018-03-timers/

**Comment by mmlinford** [comment]
How about a guide/cookbook on how to test?

**Comment by carllerche** [comment]
@mmlinford +1 though I think we are all still figuring that one out :)

**Comment by carllerche** [comment]
This issue is superseded by http://github.com/tokio-rs/doc-push.
