### ISSUE TITLE
What's the relationship between futures crate and tokio?

### ISSUE THREAD

**Issue by kingluo** [tokio-rs/tokio#1660]
My question may be silly, but I am indeed curious about this topic.
It seems there's some feature intersection between these two crates.
Like both have mpsc. Why not share the codes?

Could somebody explain the relationship between them? History, future plan, etc.

**Comment by LucioFranco** [comment]
@kingluo Hi! Both crates are complimentary. The futures crate provides more general futures utilities and combinators. We provide a subset that works with some of our specialized traits. The channel implementations are also different there are some issues open in both repos about this. Hope this helps 😄

**Comment by kingluo** [comment]
Can I use all features from `futures` in tokio? Like `mpsc`?

**Comment by jonhoo** [comment]
@kingluo You should be able to use anything except for things from `futures-io` (which use a different I/O setup than tokio uses).
