### ISSUE TITLE
Async RwLock

### ISSUE THREAD

**Issue by Luro02** [tokio-rs/tokio#1665]
## Description

An async version of [`RwLock`](https://doc.rust-lang.org/std/sync/struct.RwLock.html).

Possible reference material:
- https://docs.rs/async-std/0.99.9/async_std/sync/struct.RwLock.html
- https://docs.rs/futures-locks/0.4.0/futures_locks/struct.RwLock.html

**Comment by carllerche** [comment]
In progress: #1699
