### ISSUE TITLE
tokio-rs and futures-rs

### ISSUE THREAD

**Issue by kpp** [tokio-rs/tokio#1667]
Hi all,

There are a lot of combinators migrated from https://github.com/tokio-rs/tokio/tree/master/tokio-io/src/io into https://github.com/rust-lang-nursery/futures-rs/tree/master/futures-util/src/io.

I would like to know your thoughts on further reducing the code in tokio-io in order to ease the maintenance and mitigate potential security risks.

**Comment by carllerche** [comment]
The reason there is duplication is due to traits that do not match. The issue of the divergence will  be addressed before 0.2 final, but is not an immediate priority. Given this, I will close this as a dup of #1297.
