### ISSUE TITLE
Any plan to support sendfile?

### ISSUE THREAD

**Issue by kingluo** [tokio-rs/tokio#1673]
As known, on Linux/Unix, `sendfile` syscall is useful zero-copy feature. For async framework, I think it's necessary. For example, http file server to response the file content directly without reading into memory.

**Comment by carllerche** [comment]
Probably... for now it can be done by accessing the RawFd & PollEvented.

Given that there are no immediate plans to explore this, I will close the issue.

**Comment by jplatte** [comment]
Is there an example of how to do this using `RawFd` & `PollEvented`? Is a higher-level interface for it sth. that might happen this year, or next?

**Comment by asomers** [comment]
Two problems:
1) Tokio 1.0 removed `PollEvented`.  See #3197
2) sendfile is synchronous (synchronous on Linux; it's complicated on FreeBSD), so I'm not sure what you're hoping to accomplish with PollEvented.  Instead, you should execute sendfile in a blocking context.  https://docs.rs/tokio/1.6.1/tokio/task/index.html#blocking-and-yielding .
