### ISSUE TITLE
Implement AsyncWriteExt for Either?

### ISSUE THREAD

**Issue by Hippolot** [tokio-rs/tokio#1685]
If we implement `AsyncWriteExt` for `Either`, this code can be simplified to just `pub type Connection = Either<TokioTcpStream, TlsStream<TokioTcpStream>>;`:

```rust

#[derive(Debug)]
pub enum Connection {
    Tcp(TokioTcpStream),
    Tls(TlsStream<TokioTcpStream>),
}

impl AsyncWrite for Connection {
    fn poll_write(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<Result<usize, io::Error>> {
        match self.get_mut() {
            Self::Tcp(stream) => Pin::new(stream).poll_write(cx, buf),
            Self::Tls(stream) => Pin::new(stream).poll_write(cx, buf),
        }
    }

    fn poll_flush(self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<()>> {
        match self.get_mut() {
            Self::Tcp(stream) => Pin::new(stream).poll_flush(cx),
            Self::Tls(stream) => Pin::new(stream).poll_flush(cx),
        }
    }

    fn poll_shutdown(self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<()>> {
        match self.get_mut() {
            Self::Tcp(stream) => Pin::new(stream).poll_shutdown(cx),
            Self::Tls(stream) => Pin::new(stream).poll_shutdown(cx),
        }
    }
}
```

Should I open a PR for it, and if so, should I implement it directly inside https://github.com/tokio-rs/tokio/blob/master/tokio-io/src/io/async_write_ext.rs ?

**Comment by carllerche** [comment]
As of now, there is no plan to add a dependency on `Either` directly in the `tokio`. If anything, we could add an `Either` definition in `tokio-util` w/ the implementation.

**Comment by Hippolot** [comment]
It would be fine. Should I create a new file inside https://github.com/tokio-rs/tokio/tree/master/tokio-util/src ? Something like `either.rs`?

**Comment by ErichDonGubler** [comment]
This issue got closed, but...I didn't see it actually get resolved! Is this something interesting for a potential PR to `tokio-util`, @carllerche? Maybe gated behind a `either` feature flag?

**Comment by Hirrolot** [comment]
@ErichDonGubler, see https://github.com/tokio-rs/tokio/issues/1987.
