### ISSUE TITLE
Add support for UDP or datagram/packet based communication

### ISSUE THREAD

**Issue by sdroege** [tokio-rs/tokio#17]
It would be nice if tokio would also support UDP or datagram/packet based communication. It seems like the general idea still applies the same, just the implementation would look slightly different.

Feel free to close this if it's completely out of scope for tokio and you wouldn't even consider merging a PR for that :)

**Comment by carllerche** [comment]
No, definitely in scope. This is coming :)

**Comment by carllerche** [comment]
Initial UDP support got merged here: 262d0f47e6ddea0c0078e31e779f56a94114c1e7. There is more coming though...
