### ISSUE TITLE
Document features of tokio crate

### ISSUE THREAD

**Issue by Luro02** [tokio-rs/tokio#1701]
## Description
It'd be nice to have all features from [`Cargo.toml`](https://github.com/tokio-rs/tokio/blob/11952635840298d307dc10b26e6bdc78188c84ef/tokio/Cargo.toml#L26) documented in the [readme](https://github.com/tokio-rs/tokio/blob/master/README.md) or in [docs.rs](https://docs.rs/tokio/0.2.0-alpha.6/tokio/).
https://github.com/tokio-rs/tokio/blob/11952635840298d307dc10b26e6bdc78188c84ef/tokio/Cargo.toml#L26

**Comment by LucioFranco** [comment]
Agreed! I'd like to also see usage of the `doc_cfg` feature like we do with https://docs.rs/tonic.

**Comment by ultrasaurus** [comment]
attempting to weave in feature docs into the guide, but I'm stuck on really basic issue:  https://github.com/tokio-rs/tokio/issues/2075
