### ISSUE TITLE
Consider making a new alpha release (0.2.0-alpha.7)

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#1708]
## Version

0.2.0-alpha.6

## Platform

Darwin MB0 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

## Subcrates

- process
- io

## Description

There are many changes after the last release to crates.io. I am now migrating my project, which relies on `tokio-process`, `tokio-signal`, and `tokio::io::split`. So I hope tokio can make a new release.

**Comment by carllerche** [comment]
I'm happy to cut one whenever. What do @LucioFranco and @seanmonstar think? They maintain downstream crates and I think it is particularly painful for them.

**Comment by seanmonstar** [comment]
Seems like a good idea to get people using the new scheduler and stuffs.

**Comment by taiki-e** [comment]
FYI: futures plan to release 0.3 at the beginning of next week: https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/futures.200.2E3.2E0.20release/near/179481831

**Comment by LucioFranco** [comment]
I ideally would like to get on a semver version but now that crates are collapsed we can release a new alpha?

**Comment by zonyitoo** [comment]
@carllerche How about releasing a new alpha?

**Comment by theli-ua** [comment]
Now that futures 0.3.0 are released it might be worth it to upgrade and indeed have a new alpha

**Comment by expenses** [comment]
Yes please!

**Comment by tmccombs** [comment]
I can take a stab at upgrading to futures 0.3.0

**Comment by tmccombs** [comment]
Looks like futures was updated to 0.3.0 in 6f8b986bdb61843171ab90a1947349d5ac25576e

**Comment by wangjia184** [comment]
futures are in 0.3.1 now

**Comment by ice1000** [comment]
I wish we can have stable-compatible `tokio-process`, with async/await support!

**Comment by serzhiio** [comment]
it would be nice for me also to have tokio-codec and tokio-io to be compatible with stable latest futures!

**Comment by carllerche** [comment]
Happening soon.
