### ISSUE TITLE
Improve panic messages when runtime is not running

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#1713]
The panic messages when the reactor or timer are not available should be improved to better explain what a user needs to do to fix them (originally reported at https://github.com/hyperium/hyper/issues/1995).

- Current timer panic: `timer error: timer is shutdown`
- Current reactor panic: `no current reactor`

**Comment by leohard12** [comment]
Invest bot I need

**Comment by leohard12** [comment]
Vhrun bot
