### ISSUE TITLE
Expose or remove Delay::new_timeout

### ISSUE THREAD

**Issue by sfackler** [tokio-rs/tokio#1721]
A crate-private API allows a Duration to be associated with a `Delay` in addition to the `Instant` at which the delay resolves. This is only used by `Timeout`'s stream implementation to reset the delay when items are yielded by the underlying stream. The implementation doesn't do anything special internally - it looks like the only difference is there the `Duration` is stored - inside of the `Timer` glue or in the `Timeout<S>`.

It seems like this API should either be available to downstream users or removed.

**Comment by carllerche** [comment]
The function has been removed.
