### ISSUE TITLE
Clarify documentation around Decoder for UdpFramed

### ISSUE THREAD

**Issue by passcod** [tokio-rs/tokio#173]
Spent a lil while wondering what was up with this.

The `Decoder` doc says:

> If the bytes look valid, but a frame isn't fully available yet, then `Ok(None)` is returned. This indicates to the `Framed` instance that it needs to read some more bytes before calling this method again.
>
> Note that the bytes provided may be empty. If a previous call to `decode` consumed all the bytes in the buffer then `decode` will be called again until it returns `None`, indicating that more bytes need to be read.

However, in the context of UDP, "need more data" isn't really valid. A datagram is received entirely, afaik, or not at all. What actually happens in the code is that if `UdpFramed` get a `Decoder` return value of `Ok(None)`, it translates that to `Ok(Async::Ready(None))`, which silently closes the stream:

```rust
let frame_res = self.codec.decode(&mut self.rd);
self.rd.clear();
let frame = frame_res?;
let result = frame.map(|frame| (frame, addr)); // frame -> (frame, addr)
trace!("frame decoded from buffer");
Ok(Async::Ready(result))
```

So, I guess I'm either asking for:

- a documentation change that clarifies that returning `Ok(None)` from a `Decoder` used within `UdpFramed` is **fatal**; or
- a behaviour change so that returning a `Decoder` asking for more data from UDP generates an `Err()` instead.

**Comment by kpp** [comment]
Ah, sorry. I removed old `UdpCodec`, but I did not check docs.

**Comment by carllerche** [comment]
Ah yes, I think this wasn't intentional.

For now, we should update the documentation to state that if the decoder returns `Ok(None)` then the stream is terminated (which is not great, but not fatal).

We can revisit what should happen in 0.2.

**Comment by carllerche** [comment]
@kpp I don't think that the decoder should always return `Result`. The implementation of the codec can opt to return `Result`.

**Comment by valarauca** [comment]
I believe I hit this issue as well: https://github.com/tokio-rs/tokio-core/issues/305

**Comment by carllerche** [comment]
I'm going to close this issue for now simply since no further action can be taken until a breaking change happens. However, it is tracked by #591 and once the time comes, I will open it again.
