### ISSUE TITLE
DelayQueue: FusedStream

### ISSUE THREAD

**Issue by rubdos** [tokio-rs/tokio#1754]
## Version

- master
- 0.2.0-alpha

## Description

I'm trying to use a `DelayQueue` in `select!`, which is impossible as long as `DelayQueue` does not implement `FusedStream`.

Is it possible to just add this? Does it need a more sophisticated check?

```diff
diff --git a/tokio/src/time/delay_queue.rs b/tokio/src/time/delay_queue.rs
index 38d04940..b9e5aa34 100644
--- a/tokio/src/time/delay_queue.rs
+++ b/tokio/src/time/delay_queue.rs
@@ -733,6 +733,12 @@ impl<T> futures_core::Stream for DelayQueue<T> {
     }
 }

+impl<T> futures_core::FusedStream for DelayQueue<T> {
+    fn is_terminated(&self) -> bool {
+        false
+    }
+}
+
 impl<T> Default for DelayQueue<T> {
     fn default() -> DelayQueue<T> {
         DelayQueue::new()
```

Let me know if a patch would be applicable, I'll gladly file a MR.

**Comment by thepacketgeek** [comment]
@rubdos, I'm using DelayQueue in a `select!` macro here: https://github.com/thepacketgeek/bgpd-rs/blob/master/src/session/poller.rs#L125

I use FutureExt::fuse (but you could also use StreamExt::fuse)

**Comment by rubdos** [comment]
> I use FutureExt::fuse (but you could also use StreamExt::fuse).

Pretty sure you shouldn't be using `FutureExt::fuse`, since it fuses the future inside some loop. I cannot personally use `StreamExt::fuse`, because I need to be able to add new elements to the DelayQueue.

> Just curious: would this change remove the need to do that?

Absolutely. Just `select! {next = queue.next() }`, without any manual fusing.

**Comment by sfackler** [comment]
You fuse the stream outside of select, not inside of it.

**Comment by thepacketgeek** [comment]
@rubdos, Interesting. I'm definitely adding new items to the DelayQueue (https://github.com/thepacketgeek/bgpd-rs/blob/master/src/session/poller.rs#L160). It's my understanding that fuse() a future/stream from being polled after it's completed. In the case above, there's always at least one thing in DelayQueue so it never completes (and I continue re-adding items to it)

**Comment by carllerche** [comment]
As of now, Tokio is only implementing `Stream` from `futures-core`. If there is interest in revisiting this decision, an issue focusing on the topic should be opened.
