### ISSUE TITLE
Should futures be UnwindSafe to run on executor?

### ISSUE THREAD

**Issue by CodeSandwich** [tokio-rs/tokio#1786]
## Version

1.29, could by any

## Platform

Linux, doesn't matter

## Description

I'm suspecting that `tokio::run` breaks the `UnwindSafe` rules. The runtime catches all panics, prints them and lets process continue. That means that all futures spawned on it are implicitly passing the unwind boundary and they should be `UnwindSafe`. This shouldn't compile:

```rust
fn main() {
    // Create an `!UnwindSafe` variable
    let (sender, _) = std::sync::mpsc::channel::<()>();
    let fut = tokio::prelude::future::lazy(move || {
        let _ = sender; // `!UnwindSafe` variable is passed into future
        panic!();
        Ok(())
    });
    tokio::run(fut);
    println!("Panic was caught, unwind boundary is real");
}
```

The issue is correctly addressed in `Future::catch_unwind`, in order to catch panic it requires the future to be `UnwindSafe`, because it's aware that it creates an unwind boundary.

**Comment by CodeSandwich** [comment]
Reopened, because I thought I had found an explanation, but I hadn't.

**Comment by carllerche** [comment]
`Send + 'static` pretty much implies unwind safe. "unwind safe" isn't a memory safety concept but it is more about preventing bugs.

> It is possible, however, for logical invariants to be broken in Rust, which can end up causing behavioral bugs. Another key aspect of unwind safety in Rust is that, in the absence of unsafe code, a panic cannot lead to memory unsafety.

`tokio::spawn` does not require unwind safe for the same reason that `thread::spawn` does not.
