### ISSUE TITLE
CpuPool inside worker thread

### ISSUE THREAD

**Issue by BijanVan** [tokio-rs/tokio#179]
https://github.com/tokio-rs/tokio/blob/9f7a98af3c4cbeb89b162c1faa4480553a3dc82e/examples/echo-threads.rs#L68

fn worker(rx: mpsc::UnboundedReceiver<TcpStream>) runs under a worker thread. Is it necessary to create a CpuPool?

**Comment by carllerche** [comment]
I'm not sure I understand the question. `CpuPool` creates a thread pool.

That said, the docs are being updated and this example is being removed because Tokio will be multi threaded by default.

See [here](https://github.com/tokio-rs/tokio/tree/9f7a98af3c4cbeb89b162c1faa4480553a3dc82e/examples)

**Comment by kpp** [comment]
@BijanVan you are correct since we create `num_threads` workers, there is no need to create additional `CpuThread(1)`.

**Comment by carllerche** [comment]
The PR updating the examples is up: https://github.com/tokio-rs/tokio/pull/180

**Comment by carllerche** [comment]
#180 landed. I'm going to close this. Please comment further if you have additional questions.
