### ISSUE TITLE
Compatibility problems with async_std and Tokio

### ISSUE THREAD

**Issue by importcjj** [tokio-rs/tokio#1790]
I am making a connection pool with async/await syntax supported. The connection pool is designed to be can run in both Tokio and async-std runtime. But I had found out some cases that make a me confused.

* TcpStream implemented with Tokio-0.1 can run in the async-std-1.0 runtime.
* TcpStream implemented with Tokio-0.2 can not run in the async-std-1.0 runtime.
* TcpStream implemented with async-std-1.0 can run in the Tokio-0.2 runtime.

So, I want to know why TcpStream in Tokio-0.2 can not run in the async-std runtime.

Thank u.

**Comment by carllerche** [comment]
Tokio does not start any drivers by default, doing so would silently incur the overhead of background threads. The `#[tokio::main]` macro starts the driver. If the proc macro is not used, the user must start a `Runtime` manually.

**Comment by importcjj** [comment]
@carllerche 

I mean, how to make this code work? Now, It prints `
connect err: Custom { kind: Other, error: "no current reactor" }`

```fn main() {
    use async_std::task;
    use tokio::net::TcpStream;

    task::block_on(async {
        match TcpStream::connect("127.0.0.1:9998").await {
            Ok(_) => println!("connect ok"),
            Err(e) => println!("connect err: {:?}", e),
        }
    })
}```

**Comment by carllerche** [comment]
On master, you would need to use the `Runtime::enter` function.
