### ISSUE TITLE
Making tokio thread pool worker name consistent width for a given pool?

### ISSUE THREAD

**Issue by ahornby** [tokio-rs/tokio#1816]
Tokio runtime threadpool names look like they only have a way to [set prefix](https://docs.rs/tokio/0.2.0-alpha.6/tokio/runtime/struct.Builder.html#method.name_prefix), not the format of the thread number, so single vs double digit thread numbers causes variable length names, which in turn causes things using the thread name to move left and right.  In particular this means log lines don't line up between workers in the same pool if they include thread name.

Is there any existing way setting the format for the number part of thread name?   If not, any preferred approaches? Could add an optional format specifier to the builder, or could just unconditionally format the number part of the name with leading zeros based on thread pool size.

Here's an example of the thread name driven log wiggle I'd like to avoid.
```
I1122 03:48:41.320697 3225656 [tokio-runtime-worker-19] Right
I1122 03:48:42.344826 3225435 [tokio-runtime-worker-1] Left
I1122 03:48:44.380553 3225648 [tokio-runtime-worker-12] Right again
```

Aiming for all the threads in a given pool to have same width name:
```
I1122 03:48:41.320697 3225656 [tokio-runtime-worker-19] Nicely
I1122 03:48:42.344826 3225435 [tokio-runtime-worker-01] Lined
I1122 03:48:44.380553 3225648 [tokio-runtime-worker-12] Up
```

**Comment by carllerche** [comment]
Good thought :+1: We moved the number on master as I don't think it added any value. That will get them to line up.
