### ISSUE TITLE
Semaphore/Permit disappeared from public interface

### ISSUE THREAD

**Issue by cere42** [tokio-rs/tokio#1825]
I'm updating one of my projects from `0.2.0-alpha6` to `0.2.0` stable and just saw that tokio no longer exports its Semaphore implementation.

In #1785, the Semaphore/Permit feature suddenly went from public to `pub(crate)`. I don't think that PR intended to remove it from the public interface, it just seems to be an unintended side effect.

**Comment by carllerche** [comment]
Yeah.... we can bring it back. There were some things that were yanked to get 0.2 out sooner w/ the intent they would be brought back... 

Could you share how you are using `Semaphore`? There were a few open questions about how `Semaphore` should be shared publicly as the current API is pretty low level.

**Comment by cere42** [comment]
It's not too big of a deal for me as my use case doesn't actually rely on the async features of tokio's semaphore - I just used it because I needed a semaphore implementation and saw that tokio already had one, but I could switch to something else without too much trouble.

I use it for a specific kind of bucket based rate limiter. It gets initialized with a certain capacity, and when you poll the limiter, it takes a ticket from the semaphore. If the bucket is emptied, it starts returning `Pending` results. The tickets are returned to the semaphore a specific amount of time after that ticket was taken.

**Comment by dekellum** [comment]
I hadn't yet noticed this went away, but I too have code using it, prototyped on the alphas. 

I have implemented using `Semaphore` as an external constraint on the number of concurrent, blocking operations.  As you may recall, @carllerche, that usage was your suggestion. Blocking on the threaded runtime went away but last I saw it has come back, so my plan is to keep using the `Semaphore`.

**Comment by carllerche** [comment]
Yes... we need to revisit the semaphore per blocking op thing...

**Comment by sfackler** [comment]
I'm using it in a server to limit the number of active TCP connections in the acceptor. Pretty basic - acquire a permit before accepting, then wrap the socket in a type that releases the permit on drop.

**Comment by carllerche** [comment]
@sfackler So, what I would like to do is provide **that** API publicly...

**Comment by dekellum** [comment]
@carllerche Can you share what the impediment or concern is with (re-)exporting the `Semaphore`?  Wondering if I can help or if I should be looking for different implementation.

**Comment by FSMaxB** [comment]
Just want to add my use case: I'm limiting allocated bytes for a pipeline of image conversion operations (don't want to blow up when too many of the images are 4K).

I would have liked to use tokios Semaphore for that, but sadly you can only get a permit of 1 at a time. (I implemented it with `AtomicUsize` and a `Mutex<Vec<Task>>`, but just being able to get a ticket for any number would solve my use case.

**Comment by cetra3** [comment]
Just chiming in here, I'm now using the semaphore in `0.1` and has helped with my challenges.  I've got a backend service that tilts if you throw more than a dozen connections at it concurrently, and being able to "rate-limit" futures has helped.

With blocking futures you can use a cpu pool to limit these to a certain amount.  I see the semaphore as having the same utility as a cpu pool, but for futures.

**Comment by frostyplanet** [comment]
Semaphore is useful, we had used it to implement some custom synchronized logic,

**Comment by hlavaatch** [comment]
Please bring back Semaphore, we need high quality synchronization primitives for the same reasons as threads need them. Rolling your own is dangerous, people will get it wrong

**Comment by marcelbuesing** [comment]
Also affects the tower-limit -> tonic crate.

**Comment by dekellum** [comment]
The async-aware [`Semaphore`](https://docs.rs/futures-intrusive/*/futures_intrusive/sync/type.Semaphore.html) in _futures-intrusive_ crate offers more features and a `Future` for awaiting a 1-n permits.  Seems to work fine, including in combination with tokio threaded runtime, at least in my testing thus far.   Will there eventually be a tokio alternative?  Will it be faster or have some other advantage?

**Comment by dekellum** [comment]
Not due to clarity of direction here, but it looks like `Semaphore` has been re-released in tokio 0.2.5 with various API changes since its last alpha appearance.  Thanks for that, anyway!

**Comment by carllerche** [comment]
@dekellum that was a stop gap. We still have time to iterate. 0.3 is in a couple of months.

**Comment by dekellum** [comment]
My tests are pasing with this 0.2.5 `tokio::sync::Semaphore`, so I can now use either the futures-intrusive one or this one based on feature flag. And I'll have some comparative performance benchmarks that I could share.

It sounds like your plan entails something further in this feature area... would you be willing to elaborate on that, here or elsewhere?

**Comment by carllerche** [comment]
I don't have much of a plan yet. People were blocked on semaphore being gone, so @bikeshedder was kind enough to put something minimal together for us. I am open to thoughts on improvements / direction, but I don't have not thought further yet :).

**Comment by bikeshedder** [comment]
@carllerche I think this issue can be closed now that #1973 is merged.
