### ISSUE TITLE
`tokio::spawn` - missing feature gate specification in docs

### ISSUE THREAD

**Issue by olegnn** [tokio-rs/tokio#1836]
## Version

tokio-0.2.1

## Description

Missing `feature="rt-core"` for `tokio::spawn` on [index page](https://docs.rs/tokio/0.2.1/tokio/index.html) and on [`tokio::spawn` page](https://docs.rs/tokio/0.2.1/tokio/fn.spawn.html)

**Comment by carllerche** [comment]
Thanks. The cfg doc stuff is a little quirky.

**Comment by jebrosen** [comment]
Similarly, `block_in_place` [is listed](https://docs.rs/tokio/0.2.2/tokio/task/fn.block_in_place.html) as needing `rt-core` and `rt-threaded`, when it also requires `blocking`. It looks like reexports don't count and only the "original" item's `#[doc(cfg)]` is used.
