### ISSUE TITLE
tokio::test - how to test if read/write did not get called?

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/tokio#1847]
# Version 

```
irc-tokio v0.1.0 (/Users/sallen/src/rust/irc-tokio)
├── tokio v0.2.1
│   └── tokio-macros v0.2.0
└── tokio-util v0.2.0
    └── tokio v0.2.1 (*)
    └── tokio v0.2.1 (*)
└── tokio-test v0.2.0
    └── tokio v0.2.1 (*)
    └── tokio v0.2.1 (*)
```
## Platform

```
$ uname -a
Darwin newair.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64 i386 MacBookAir8,1 Darwin
```

## Subcrates

this is what is in `Cargo.toml`:

```
[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2.0", features = ["full"] }
futures = "0.3.0"

[dev-dependencies]
tokio-test = "0.2.0"
```

## Description

I wrote the following test which fails correctly when content of `write` is incorrect, but the code fails to call `read` and the test still passes:

```

#[tokio::test]
async fn can_create_protocol() {
  use tokio::io::{AsyncReadExt, AsyncWriteExt};
  use tokio_test::io::Builder;
  use tokio_test::io::Mock;

  let mock_connection: Mock = Builder::new().write(b"PASS secret\r\nNICK maria\r\nUSER maria 0 * maria\r\n").read(b":maria!maria@irc.gitter.im NICK :maria\r\n").build();

  let mut irc = Protocol::new(mock_connection, "maria");
  irc.connect("secret").await.expect("irc.connect");

  // how to test that the write and read actually happened
}
```
for full context, see [irc-tokio](https://github.com/ultrasaurus/irc-tokio/blob/eca0871868c0149aee617efb32786f75a05f8877/src/irc/mod.rs)

This may be  a missing  feature of `tokio::test` or perhaps it's there and is just missing tests/docs.  I was looking at `tokio-test/tests/io.rs` to try to understand how to do testing and found that useful.  

My next step in looking at this would be to write a failing test and happy to help add the feature, if it's not there already.  I thought I would leave a note here in case I'm missing something or there are planned changes in this area that I should wait for.

cc @jenmei

**Comment by barafael** [comment]
It looks like with #2693 this issue may be closed.
