### ISSUE TITLE
tokio::signal::unix::Signal missing Stream impl, poll methods are left undocumented

### ISSUE THREAD

**Issue by osa1** [tokio-rs/tokio#1848]
## Version

0.2.1, git HEAD

## Description

`tokio::signal::unix::Signal` used to be a `Stream` but with 0.2.1 the `Stream` implementation is gone. The documentation still says it's a `Stream` ("An implementation of Stream for receiving a particular type of signal."). Just chatted with @carllerche on gitter about this and it seems like this impl should still be there.

Another issue is with the hidden `recv` and `poll_recv` methods: https://github.com/tokio-rs/tokio/blob/master/tokio/src/signal/unix.rs#L393-L405 apparently those should be documented and exposed.

**Comment by ipetkov** [comment]
Hey @osa1 thanks for catching this! I had meant to address this, but got busy and missed the release 😅

Fixing the docs should be straightforward enough

**Comment by osa1** [comment]
@ipetkov Now that #1849 is merged would it be possible to release a new version after fixing the docs?

**Comment by ipetkov** [comment]
@osa1 yep that's the plan!

I've opened #1854 to fix the documentation, will work on scheduling a release after it lands

**Comment by osa1** [comment]
It seems like both issues are fixed now. Should we close this?

**Comment by ipetkov** [comment]
I've opened #1857 to prepare for the next release, so will close this!
