### ISSUE TITLE
idea can't found symbol

### ISSUE THREAD

**Issue by s97712** [tokio-rs/tokio#1850]
## Version
0.2.0 +

## Description

After version 0.2.0, tokio use `cfg_xxx` macros to enable features, but idea cannot analyze these macros, which caused in many symbols that cannot be found by idea

**Comment by carllerche** [comment]
I would open up a bug w/ IDEA. Using macros to define types is valid idiomatic Rust. If IDEA has suggestions, I would be open to it.

**Comment by s97712** [comment]
It's really painful not to be able to use autocomplete, Is there a temporary solution?

**Comment by carllerche** [comment]
I don't know. Is there an issue opened w/ them that can be tracked?

**Comment by s97712** [comment]
https://github.com/intellij-rust/intellij-rust/issues/4627

**Comment by s97712** [comment]
> I don't know. Is there an issue opened w/ them that can be tracked?

https://github.com/intellij-rust/intellij-rust/issues/4627
