### ISSUE TITLE
tokio::fs never waked up when ran by tokio::spawn

### ISSUE THREAD

**Issue by jean-airoldie** [tokio-rs/tokio#1851]
## Version
```toml
[dependencies]
tokio = { version = "0.2", features = ["rt-core", "time", "fs", "macros"] }
futures = "0.3"
tempfile = "3.1.0"
```
with tokio 0.2.1 being selected.

## Platform
`Linux  5.0.0-36-generic 18.04.1-Ubuntu x86_64`

## Description

The `tokio::fs` operations I tested are not waked up when driven by tokio::spawn. The following tests block forever:

```rust
#[cfg(test)]
mod tests {
    use {
        tokio::{fs, time::{timeout, Duration}},
        tempfile::tempdir,
        futures::future::FutureExt,
    };

    #[tokio::test]
    async fn test_read() {
        let temp = tempdir().unwrap();
        let dir = temp.path();

        let (driver, handle) = fs::read(dir.join("bar")).remote_handle();
        tokio::spawn(driver);

        // The task is never waked up.
        handle.await.unwrap();
    }

    #[tokio::test]
    async fn test_write() {
        let temp = tempdir().unwrap();
        let dir = temp.path();

        let (driver, handle) = fs::write(dir.join("bar"), b"bytes").remote_handle();
        tokio::spawn(driver);

        // The task is never waked up.
        handle.await.unwrap();
    }
}

```

Note that this is doesn't seem to be caused by the `#[tokio::test]` macro since I can replicate this behavior using `#[tokio::main]`. Also it doesn't seem to be caused by the `remote_handle` method either since I had the same behavior in one of my applications that doesn't use it. It seems that tokio::fs operations are simply not working when ran as a task inside tokio::spawn.

**Comment by pluth** [comment]
I've run into a similar issue with the dns feature where a SocketAddr doesn't get resolved. This leads me to belive that this issues is related to the blocking feature.

What I found interesting is that 
```rust
#[tokio::main]
async fn main() {
    tokio::spawn(async move {
        tokio::fs::read("./Cargo.toml").await.expect("read");
    }).await.unwrap();
}
```

does not terminate while
```rust
#[tokio::main]
async fn main() {
    tokio::fs::read("./Cargo.toml").await.expect("read");
}
```

does. 

Feature are `tokio = { version = "0.2.1", features = ["fs", "rt-core", "macros"] }`
Both examples work when adding the `rt-threaded` feature.

**Comment by zonyitoo** [comment]
Same problem when running futures with `tokio::spawn_blocking` if using the `basic_scheduler`. They are definitely related.

**Comment by carllerche** [comment]
Fix here: https://github.com/tokio-rs/tokio/pull/1861

**Comment by pluth** [comment]
Works for me. Thank you! 👍
