### ISSUE TITLE
tokio::fs::File doesn't expose `into_std()` in 0.2

### ISSUE THREAD

**Issue by bartlomieju** [tokio-rs/tokio#1852]
## Version

tokio 0.2 

## Description

In tokio 0.1 one could get underlying `std::fs::File` instance from `tokio::fs::File` like so:
```rust
OpenOptions::new().open().and_then(move |tokio_file| {
  let std_file = tokio_file.into_std();
});
```

Unfortunately I did not find this method in tokio 0.2 which is very desirable - eg. I want to start new `Command` with file as stdout/stderr for that command. `Command.stdout()` requires `Into<Stdio>` which is implemented for `std::fs::File` but not `tokio::fs::File`.

EDIT: 
As I see that design of `tokio::fs::File` changed it's not really useful to destructure the file. Something like `async fn try_clone_std() -> std::fs::File` would be fine :+1:

**Comment by carllerche** [comment]
what about `async fn into_std`?

**Comment by bartlomieju** [comment]
> what about `async fn into_std`?

```rust
pub async fn into_std(&self) -> io::Result<sys::File> {
    let std = self.std.clone();
    let std_file = asyncify(move || std.try_clone()).await?;
    Ok(std_file)
}
```

@carllerche something along those lines? I'll be happy to open a PR

**Comment by carllerche** [comment]
You would not need a clone. You would wait until the background operation is complete, then downcast then use `Arc::try_unwrap` to get the inner `file`.

You could also have a `try_into_std(self) -> Result<sys::File, Self>` that does the `Arc::try_unwrap` directly.
