### ISSUE TITLE
Execute tokio_timer::timeout::Timeout future without tokio::runtime

### ISSUE THREAD

**Issue by chunyingw** [tokio-rs/tokio#1855]
##Version
tokio 0.2.1
## Platform
Fuchsia
## Subcrates
tokio-executor, tokio-timer are related.
## Description
Any advice how to run tokio::time::timeout future w/o tokio runtime?

Before upgrade to tokio 0.2.1 version,  I was able to create timer context manually and use fuchsia executor to run tokio-time::time::Timeout future with the following sample codes:
<
use tokio_executor::park::ParkThread;
<snip>
 let clock = Clock::new();
 let timer = Timer::new_with_now(ParkThread::new(), clock.clone());
 let timer_handle = timer.handle();
<snip>
clock::with_default(&clock, || {
                let _timer = timer::set_default(&timer_handle);
                tokio_executor::with_default(&mut exec,  || {
                        fexec.run_singlethreaded(response_future)
                })
>
However with the latest tokio 0.2.1, some of the struct/API are not public any more, any advice how I can achieve the same purpose?

**Comment by carllerche** [comment]
Everything is part of `Runtime` now. Look at `runtime::Builder`. You can start a runtime with **only** a time driver, which is equivalent to using the old timer.

**Comment by carllerche** [comment]
I will leave a `docs` label as the above pattern needs to be documented somewhere.

**Comment by chunyingw** [comment]
Carl, thanks for the quick response. Yes, it's working now.
