### ISSUE TITLE
Improve documentation for exactly why we need Runtime::enter

### ISSUE THREAD

**Issue by rjsberry** [tokio-rs/tokio#1860]
In previous versions of tokio, the following was possible:

```rust
use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use tokio::runtime::Runtime;
use tokio::timer;

let rt = Rc::new(RefCell::new(Runtime::new().unwrap()));

// elsewhere

rt.borrow_mut().block_on(timer::delay_for(Duration::from_secs(1)));
```

As of tokio 0.2.1 the above panics with "no current timer" (`HandlePriv::current`), and needs to be written as:

```rust
use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use tokio::runtime::Runtime;
use tokio::timer;

let rt = Rc::new(RefCell::new(Runtime::new().unwrap()));

// elsewhere

let mut rt = rt.borrow_mut();
let fut = rt.enter(|| timer::delay_for(Duration::from_secs(1)));
rt.block_on(fut);
```

I'm sure this is a relatively niche example, but it wasn't clear from the documentation why this is required. It seems the exact reason is due to the thread local storage of the current timer handle, but I'm not sure if that's the sort of thing that wants mentioning in the docs.

**Comment by carllerche** [comment]
Do you have thoughts on where & how to mention it?

Also, you would probably write something like this:

```rust
rt.block_on(async {
    timer::delay_for(duration)
});
```

**Comment by jerry73204** [comment]
I have the same issue when using mpsc receiver in tokio. It does a non-blocking read on receiver in a non-async function. Thus I need `block_on` to do this job, but I get `no current timer` error. However, using `enter` seems not to fix this issue.

```rust
let timeout_recv = tokio::time::timeout(Duration::from_millis(0), self.receiver.recv());                                                                                           
let _ = self.runtime.block_on(timeout_recv)?;
```

**Comment by najamelan** [comment]
From looking [through the docs](https://docs.rs/tokio/0.2.4/tokio/runtime/struct.Builder.html), I saw the Builder type clearly has methods for these, but maybe there could be some general intro giving overview. A bunch of things have changed and for example I'm wondering when exactly single threaded tasks get run now that the `run` method no longer exists. I will have to read through `LocalSet`, `block_on` etc, but maybe a blogpost for guiding migration could help people understand the high level reasoning behind the new API?

**Comment by Darksonn** [comment]
I am replacing this issue by  #2696.
