### ISSUE TITLE
Time::Interval docs don't mention that "stream" feature is required for impl Stream

### ISSUE THREAD

**Issue by malaire** [tokio-rs/tokio#1878]
## Version

tokio 0.2.2 documentation

## Description

In https://docs.rs/tokio/0.2.2/tokio/time/struct.Interval.html it is not mentioned that `impl Stream for Interval` requires `stream` feature.

**Comment by dunnock** [comment]
Just got the same issue, it leads to rather confusing error message:
```
error[E0599]: no method named `next` found for type `tokio::time::interval::Interval` in the current scope
  --> src/main.rs:60:18
   |
60 |         interval.next().await;
   |                  ^^^^ method not found in `tokio::time::interval::Interval`
   |
   = note: the method `next` exists but the following trait bounds were not satisfied:
           `tokio::time::interval::Interval : futures_util::stream::stream::StreamExt`
```

**Comment by carllerche** [comment]
Unfortunately, it looks like `doc(cfg(...))`  doesn't highlight conditional trait implementations. We should definitely call it out in the API docs though. :+1:
