### ISSUE TITLE
Missing panic handler

### ISSUE THREAD

**Issue by krojew** [tokio-rs/tokio#1894]
## Version

0.2.1

## Platform

Ubuntu 19.10

## Description

The panic handling functionality appears to have disappeared from Builder when switching to the new scheduler. There doesn't seem to be any alternative nor any information why this happened and what the migration process should be.

**Comment by carllerche** [comment]
Adding that API was unnecessary as the panic handler is a *global* value and not per thread. You can cal the std api direclty: https://doc.rust-lang.org/std/panic/fn.set_hook.html
