### ISSUE TITLE
Timeout for stream

### ISSUE THREAD

**Issue by Riateche** [tokio-rs/tokio#1901]
## Version

0.2.2

## Description

In PR https://github.com/tokio-rs/tokio/pull/1774, the implementation of `Stream` for `Timeout` was removed, and the new constructor function (`timeout`) has a `T: Future` bound. Is there a way to create a stream with timeout now?

**Comment by carllerche** [comment]
We should add one back. Probably via `time::timeout_stream` or something. I think a separate fn would be clearer.

**Comment by carllerche** [comment]
Alternatively, we could do `StreamExt::timeout(self)`.

**Comment by carllerche** [comment]
Given that we have `StreamExt` we probably want to add a `timeout` fn on that.

**Comment by kamek-pf** [comment]
What workaround would you recommend in the meantime ?
I assume manually implementing `Stream` on a wrapper type and using `Delay` would work (?), or is there something simpler ?

**Comment by taiki-e** [comment]
Closing -- `StreamExt::timeout` is added in #2149
