### ISSUE TITLE
ConnectionRefused error when trying to work through the tutorials (Ubuntu, rustc 1.39.0, tokio 0.2.2)

### ISSUE THREAD

**Issue by biot023** [tokio-rs/tokio#1903]
## Version

0.2.2
(Tested with version 0.1.21 and got same error.)

## Platform

Linux drusila 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description

I'm working through the 'get started' tutorials on the tokio homepage to play with the new async/await syntax. However, when I try to run the most basic version of the code, I get this error:

    cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/hello-world`
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', src/libcore/result.rs:1165:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I'm at the very simplest stage of the tutorial, so the code I'm trying to run is this:

```
use tokio::{
    io,
    net::TcpStream,
    prelude::*,
};

#[tokio::main]
async fn main() {
    // Connect to port 6142 on localhost
    let mut stream = TcpStream::connect("127.0.0.1:6142").await.unwrap();

    stream.write_all(b"Hello, world\n").await.unwrap();

    println!("Wrote to stream");
}
```

(I'll post the full backtrace at the end of this ticket.)

I tested an older version of the tutorial that previously ran fine using tokio 0.1.21 and I get the same error, there, so I'm guessing something maybe has changed in Ubuntu?
Having googled around, I tried increasing `somaxconn` with this command:

    sudo sysctl -w net.core.somaxconn=1024

This didn't make any difference.
I've also run simple Ruby webservers on localhost to make sure that they worked, and they did.
I also ran a whole bunch of docker images that map to various ports on my local machine and they all worked just fine, too.

I noticed some kernel updates in my Ubuntu updates, recently, and wondered if they might have something to do with it?
I also recently tried to up the number of open files and processes reported for my user by the `ulimit` command without any success. This involved making changes to the system config as outlined [here](https://phpsolved.com/ubuntu-16-increase-maximum-file-open-limit-ulimit-n/). It's probably not relevant but I mention it just in case.

If anyone had any insight that might help I'd be very grateful. I appreciate this might not be a tokio thing but from my limited tests so far, it's only tokio code that's getting refused connections.

Thanks for any and all help,
   Doug.

### An attempt to run the program with RUST_BACKTRACE=full ###

    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/hello-world`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x561249a2d064 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x561249a2d064 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x561249a2d064 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x561249a2d064 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x561249a4859c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x561249a29ba7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x561249a2f515 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x561249a2f515 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x561249a2f515 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x561249a2f206 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x561249a2fc15 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x561249a2f7b2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x561249a2f6a6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x561249a45aaa - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x561249a45ba7 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x56124994b1f7 - core::result::Result<T,E>::unwrap::h1cb23bb918a3d413
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:933
  16:     0x5612499460de - hello_world::main::{{closure}}::h86edc507c07de36d
                               at src/main.rs:10
  17:     0x561249948ccb - <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::hfb18825cf80e91b9
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  18:     0x561249948369 - std::future::set_task_context::h1500ab0543418669
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:79
  19:     0x5612499488f6 - <std::future::GenFuture<T> as core::future::future::Future>::poll::h089bf33c6793cbc6
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/future.rs:43
  20:     0x56124994df94 - tokio::runtime::enter::Enter::block_on::h223ff65687b71529
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/enter.rs:100
  21:     0x561249946993 - tokio::runtime::thread_pool::ThreadPool::block_on::{{closure}}::h7e6effbbaaac7d1d
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/thread_pool/mod.rs:102
  22:     0x561249949637 - tokio::runtime::global::with_state::{{closure}}::hfa5cf1f996441a17
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:100
  23:     0x56124994c1a5 - std::thread::local::LocalKey<T>::try_with::h5801a6afc14b1a3f
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  24:     0x56124994b8bf - std::thread::local::LocalKey<T>::with::hcfafcff1555afb78
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  25:     0x5612499491be - tokio::runtime::global::with_state::h3ed92bfd217d23b3
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:83
  26:     0x56124994970b - tokio::runtime::global::with_thread_pool::he0290ae4936cd6c3
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:75
  27:     0x5612499478af - tokio::runtime::thread_pool::spawner::Spawner::enter::hd538c9a675866997
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/thread_pool/spawner.rs:44
  28:     0x56124994691f - tokio::runtime::thread_pool::ThreadPool::block_on::h131862f060cbb55e
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/thread_pool/mod.rs:100
  29:     0x56124994e205 - tokio::runtime::Runtime::block_on::{{closure}}::h58316e813c1ac2d2
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/mod.rs:411
  30:     0x56124994937b - tokio::runtime::global::with_state::{{closure}}::hb41536e16ef3f9c3
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:100
  31:     0x56124994bd69 - std::thread::local::LocalKey<T>::try_with::h2b65a6d43c788220
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  32:     0x56124994b5bf - std::thread::local::LocalKey<T>::with::h48c5d39c295966c0
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  33:     0x561249949270 - tokio::runtime::global::with_state::hb8494ca65796792e
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:83
  34:     0x56124994976d - tokio::runtime::global::with_thread_pool::hf42a1e9a5fea7789
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/global.rs:75
  35:     0x56124994785d - tokio::runtime::thread_pool::spawner::Spawner::enter::h0e94b5528825563f
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/thread_pool/spawner.rs:44
  36:     0x5612499465c4 - tokio::runtime::spawner::Spawner::enter::h76534fc9e0c9bf0f
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/spawner.rs:32
  37:     0x56124994de4a - tokio::runtime::handle::Handle::enter::{{closure}}::{{closure}}::he0493dd1ce4e3bec
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/handle.rs:36
  38:     0x56124994e5a0 - tokio::time::clock::Clock::enter::h89cbc0b8be59ccb4
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/time/clock.rs:30
  39:     0x56124994683a - tokio::runtime::time::variant::with_default::h2f564b1c08a20776
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/time.rs:43
  40:     0x56124994dd76 - tokio::runtime::handle::Handle::enter::{{closure}}::h24de7daee8caef81
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/handle.rs:36
  41:     0x56124994dbc8 - tokio::runtime::blocking::pool::Spawner::enter::{{closure}}::h962b6b3469139806
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/blocking/pool.rs:191
  42:     0x56124994cb75 - std::thread::local::LocalKey<T>::try_with::hf737ce263febbb4e
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:262
  43:     0x56124994b74f - std::thread::local::LocalKey<T>::with::h94b7e53af8573fba
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/local.rs:239
  44:     0x56124994dab8 - tokio::runtime::blocking::pool::Spawner::enter::hce5e47862defcdb9
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/blocking/pool.rs:176
  45:     0x56124994dcc6 - tokio::runtime::handle::Handle::enter::h06465078ececfe8e
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/handle.rs:33
  46:     0x56124994e0b0 - tokio::runtime::Runtime::block_on::h10f10d5aeef8bdcf
                               at /home/thisuser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.2/src/runtime/mod.rs:406
  47:     0x561249947932 - hello_world::main::hb96dccf391b1cae9
                               at src/main.rs:7
  48:     0x561249947a00 - std::rt::lang_start::{{closure}}::hf093ba73c6b486ef
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  49:     0x561249a2f643 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  50:     0x561249a2f643 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  51:     0x561249a32dda - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  52:     0x561249a3010d - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  53:     0x561249a3010d - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  54:     0x561249a3010d - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  55:     0x5612499479d9 - std::rt::lang_start::h2e3f707051dd755f
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  56:     0x56124994798a - main
  57:     0x7f493b9c3b97 - __libc_start_main
  58:     0x56124994422a - _start
  59:                0x0 - <unknown>

**Comment by sfackler** [comment]
Do you have a program listening on port 6142?

**Comment by biot023** [comment]
Hi -- no, I can run my toy Ruby webserver on port 6142 just fine and when I `netstat` it, it's perfectly clear.

**Comment by hawkw** [comment]
@biot023 the `hello-world` example _connects_ to a server listening on that port — it's a client. I think you need a server running as well, or else, you'll get "connection refused" because there's nothing there to accept your connection.

The [`echo` example](https://github.com/tokio-rs/tokio/blob/master/examples/echo.rs) has a server you can run that will echo back what the `hello-world` client sends to it. If you run it with
```
cargo run --example echo 127.0.0.1:6142
```
it should work?

**Comment by biot023** [comment]
@hawkw 
Ha ha, well... You won't believe this but, ah... Ha! You'll laugh... It, uh... Heh heh... It's, uh...
It's exactly what you said. And it's perfectly obvious in the tutorial, if you've got the wit to read it.
Cheers, man. I'll get my coat...
