### ISSUE TITLE
task: Add some way to drive a `LocalSet` inside of a task

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#1906]
Currently, the only way to run a `tokio::task::LocalSet` is to call its `block_on` method with a `&mut Runtime`, like
```rust
let mut rt = tokio::runtime::Runtime::new();
let local = tokio::task::LocalSet::new();
local.block_on(&mut rt, async {
  // whatever...
});
```

Unfortunately, this means that `LocalSet` doesn't work with the `#[tokio::main]`  and `#[tokio::test]` macros, since the `main` function is _already_ inside of a call to `block_on`.

We should consider adding a function like
```rust
pub fn run_with<F: Future>(&self, f: F) -> LocalFuture<F>
```
to `LocalSet`, so that users can write code like
```rust
#[tokio::main]
async fn main() {
    let local = tokio::task::LocalSet::new();
    local.run_with(async {
         // .. whatever ...
    }).await;
}
```
We could also add a `run()` or `run_until_idle()` that just drives the local set until all tasks spawned on it complete.

**Comment by asomers** [comment]
There definitely needs to be something like this.  I suggest a more elegant API: simply implement `Future<()>` for `LocalSet` so it may be used like this:
```rust
#[tokio::main]
async fn main() {
    let local = tokio::task::LocalSet::new();
    local.spawn_local(async {
         // .. whatever ...
    });
    local.await;
}
```
or like this:
```rust
fn do_something_single_threaded_in_background() -> impl Future<Output = ()> {
    let local = tokio::task::LocalSet::new();
    local.spawn_local(async {
         // .. whatever ...
    });
    local
}
```

**Comment by hawkw** [comment]
> There definitely needs to be something like this. I suggest a more elegant API: simply implement `Future<()>` for `LocalSet` so it may be used like this:

Took a quick crack at this, and it's definitely possible to do that. However, an `async` block that contains a `LocalSet` variable isn't `Send`, even if the `LocalSet` is created within that async block. Thus, while you can await a `LocalSet`, you can't spawn a task that does so, even if the localset itself remains on the worker thread that runs that task. This means you can only await `LocalSet` futures in `block_on`. It may take additional work to figure out how to allow spawning futures which contain their own localsets..

**Comment by hawkw** [comment]
(fwiw, I still think implementing `Future` for `LocalSet` is probably the most ergonomic API, it just means that it can only be used inside of a `block_on`/`tokio::main`)
