### ISSUE TITLE
task::LocalSet: provide `async fn await_on(impl Future)` and `async fn await_for_idle`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#1908]
naming TBD:

Providing such functions would allow using `LocalSet` directly from `#[tokio::main`].

* `await_on` would take a future to await.
* `await_for_idle` would run until the `LocalSet` is idle (no spawned futures).

**Comment by osa1** [comment]
> await_for_idle would run until the LocalSet is idle (no spawned futures).

This would be really helpful. That's also something that the old tokio (0.2.0-...) provided so having this will make migration easier.

**Comment by hawkw** [comment]
@carllerche BTW, I opened a very similar issue (#1906)

**Comment by osa1** [comment]
How hard would it be to implement `await_for_idle` for a beginner? I don't know tokio code base too much but I need this feature and I'm willing to implement it if it's not too complicated.
