### ISSUE TITLE
Panic when a future tries to call spawn during runtime shutdown

### ISSUE THREAD

**Issue by PvdBerg1998** [tokio-rs/tokio#1916]
## Version

0.2.3

## Platform

Windows 10 64 bit

## Description

Title. I'm using `tokio::spawn` in a `Drop` impl, which fails when the runtime is shutting down, with the following panic message: `thread 'main' panicked at 'no current reactor'`.

**Comment by carllerche** [comment]
Do you have repro code? Thinking about it it seems odd that a panic would get that error...

**Comment by PvdBerg1998** [comment]
I don't know what changed, but it seems fixed now
