### ISSUE TITLE
examples/chat.rs write buffer run out of capacity and panic

### ISSUE THREAD

**Issue by lu-zero** [tokio-rs/tokio#192]
in [buffer()](https://github.com/tokio-rs/tokio/blob/5555cbc85e48a110f7d7d60ba6af9ec31eb17142/examples/chat.rs#L262) it calls `put()` without checking if there is enough capacity.

and [here](https://github.com/tokio-rs/tokio/blob/master/examples/chat.rs#L181) it keeps queuing up without limit.

It is enough to have enough clients writing at the same time, or one client writing fast enough and the write buffer saturates with a panic.

**Comment by kpp** [comment]
Combine this issue with https://github.com/tokio-rs/tokio/issues/186

**Comment by carllerche** [comment]
@lu-zero Thanks for the report. You are correct that there are problems here.

I would also say that, while similar, this is a separate issue to #186.
