### ISSUE TITLE
Runtime::Drop waits for blocking synchronous code

### ISSUE THREAD

**Issue by PvdBerg1998** [tokio-rs/tokio#1923]
## Version

0.2.3

## Platform

Windows 10 64 bit

## Description

Spawning a long blocking synchronous task using `spawn_blocking` results in `Runtime::Drop` blocking until the task returns, which may be never. I believe that since this function is tied to some async context, it should get canceled (or ignored) when the runtime drops. There is no way to force a thread to stop, but it will halt when the main thread exits, which should be enough here.

**Comment by carllerche** [comment]
What do you think about having a `Runtime::shutdown_timeout(self, duration: Duration)` function? It would block for at most the requested duration and then exit. This will potentially leave threads hung.
