### ISSUE TITLE
Is `tokio::time::sleep` name better than `tokio::time::delay_for`?

### ISSUE THREAD

**Issue by FuGangqiang** [tokio-rs/tokio#1931]
`sleep` looks better, the std has a `thread::sleep`.

```
use std::time::Duration;
use tokio::time;

#[tokio::main]
async fn main() {
    time::sleep(Duration::from_millis(100)).await;
    println!("100 ms have elapsed");
}
```

**Comment by tomocrafter** [comment]
I don't think so, because time::sleep is blocks thread at that point, but delay for is literary "delay". It suspends at that time and then back again.
correct me if I'm wrong.

**Comment by carllerche** [comment]
Exactly. IMO sleep does not fit the action of the function or how it is used. Delay is most useful mixed with select to use as a time-out or a signal that a period of time has elapsed. It does not put the task to sleep (as you can still do work on the task using join or select).
