### ISSUE TITLE
Consider adding playground-specific metadata

### ISSUE THREAD

**Issue by shepmaster** [tokio-rs/tokio#1932]
## Version

0.2.x

## Description

With the changes in 0.2.x to use a feature-flagged `tokio` crate where everything is off by default, there's the *possibility* of Tokio not being shown in its best light on the playground.

The playground has [custom metadata](https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736) that allows crate owners to opt in to what features will be enabled on the playground.

This is **not** an immediate concern as Tokio is currently only brought into the playground as a dependency (of hyper and reqwest), so whatever flags they use should be sufficient, once they update to 0.2.x.

**Comment by carllerche** [comment]
I would be happy to add whatever metadata. Are you able to submit a PR w/ that?

**Comment by carllerche** [comment]
How does one get Tokio 0.2 in the playground?

**Comment by shepmaster** [comment]
> How does one get Tokio 0.2 in the playground?

The criteria is one of:

- Be in the [Rust Cookbook](https://rust-lang-nursery.github.io/rust-cookbook/)
- Be one of the top 100 downloaded crates
- Be a dependency of a crate otherwise included

Generally, the only directly-actionable route is the cookbook.

> Are you able to submit a PR w/ that?

I could. I assume that `full` would be the correct general-purpose feature?

**Comment by carllerche** [comment]
Yep, `full` is the way to go.

**Comment by carllerche** [comment]
I guess once `hyper` is updated to 0.2, then `tokio` will be included. I guess we should fix it before that...

**Comment by LucioFranco** [comment]
Yeah, we should def include it as `full` :+1: thanks for reaching out!
