### ISSUE TITLE
Cannot split UdpFramed, no method/trait implementation?

### ISSUE THREAD

**Issue by bitemyapp** [tokio-rs/tokio#1935]
## Version

```
$ cargo tree | grep tokio
├── tokio v0.2.4
│   └── tokio-macros v0.2.0
├── tokio-codec v0.1.1
│   └── tokio-io v0.1.12
├── tokio-util v0.2.0
│   └── tokio v0.2.4 (*)
│   └── tokio v0.2.4 (*)
```

## Subcrates

tokio_util, I think, since that's where UdpFramed got shuffled off to.

## Description

```
error[E0599]: no method named `split` found for type `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>` in the current scope
  --> src/main.rs:99:75
   |
99 |     let (sink, stream) = UdpFramed::new(socket, CapnpMessageCodec::new()).split();
   |                                                                           ^^^^^ method not found in `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>`

error[E0599]: no method named `split` found for type `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>` in the current scope
   --> src/main.rs:137:75
    |
137 |     let (sink, stream) = UdpFramed::new(socket, CapnpMessageCodec::new()).split();
    |                                                                           ^^^^^ method not found in `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>`
```

I'm updating my project that was using tokio/tokio_core/Rust 2015 in the past to 2018, tokio 0.2, and async/await. We're using the codec and UdpFramed support at the moment with Cap'n Proto. (cf. https://crates.io/crates/capnpc )

Currently the way the code works, it splits the sink and stream out of UdpFramed but it cannot find the method impl. I poked through docs.rs and none of the split implementations seem to be implemented for UdpFramed.

### Possible candidates for .split() that I tried from the docs

- tokio::io::split | Split a single value implementing `AsyncRead + AsyncWrite`

```
the trait `tokio::io::async_write::AsyncWrite` is not implemented for `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>`
```

- tokio::io::AsyncBufReadExt::split | Returns a stream of the contents of this reader split on…

```
   = note: the method `split` exists but the following trait bounds were not satisfied:
           `&mut tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec> : tokio::io::util::async_buf_read_ext::AsyncBufReadExt`
           `&tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec> : tokio::io::util::async_buf_read_ext::AsyncBufReadExt`
           `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec> : tokio::io::util::async_buf_read_ext::AsyncBufReadExt`

error[E0599]: no method named `split` found for type `tokio_util::udp::frame::UdpFramed<messages::codec::CapnpMessageCodec>` in the current scope
```

- tokio::net::TcpStream::split | Split a `TcpStream` into a read half and a write half,…

It's not a TcpStream, it's `UdpFramed`.

- tokio::net::UdpSocket::split | Split the `UdpSocket` into a receive half and a send half.…
Ditto. I doubt recourse to the underlying UdpSocket would preserved the dataframe/codec behavior we want.

- tokio::net::UnixStream::split | Split a `UnixStream` into a read half and a write half,…
Ditto.

Am I meant to track down the original and re-implement it? The documentation says to use `.split()`:

https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/udp/frame.rs#L26-L28

**Comment by sopium** [comment]
Use this [`split`](https://docs.rs/futures-util/0.3.1/futures_util/stream/trait.StreamExt.html#method.split) from `futures-utils` for `Stream` + `Sink`?

**Comment by mkindahl** [comment]
I ran into the same issue. Is anybody working on this?

**Comment by bitemyapp** [comment]
@mkindahl I had to fix my imports, things got moved around in one of the tokio reshufflings and I couldn't really find any migration docs or notes about how to fix missing methods/traits/etc. After some struggle and asking around, I stumbled on the modules I needed.

Here are imports from my (now working) project that I needed which are probably relevant to your situation:

```rust
use tokio::net::UdpSocket;
use tokio_util::udp::UdpFramed;
use tokio_util::codec::{Decoder, Encoder};
```

For futures stuff the imports for that simplified to:

```rust
use futures::prelude::*;
```

Shouldn't need much else, but let me know if you're still stuck after trying these. I'll close the issue since I've reported what solved my problem.

**Comment by canselcik** [comment]
This is really frustrating.

First of all, auto-complete is really hampered in all `tokio` modules due to what I am guessing really heavy use of macros.

I spent the last three days trying to figure out the exact same thing but for `TcpListener`, `TcpStream`, etc.

Your findings helped a lot in this thread but I am still unable to write to the `tokio_util::codec::framed::Framed<tokio::net::tcp::stream::TcpStream, RedisCodec>` and nothing works.

`write`, `write_all`, `poll_write`... any guesses?

**Comment by Darksonn** [comment]
> Your findings helped a lot in this thread but I am still unable to write to the `tokio_util::codec::framed::Framed<tokio::net::tcp::stream::TcpStream, RedisCodec>` and nothing works.
> 
> `write`, `write_all`, `poll_write`... any guesses?

Those methods you've posted are for writing to an [`AsyncWrite`][1], but [`Framed`][2] is a [`Sink`][3]. Please consider the various methods found on the [`SinkExt`][4] extension trait instead, in particular [`SinkExt::send`][5] and [`SinkExt::send_all`][6].

Similarly when reading you want to use methods intended for [streams][7], for which both Tokio and futures provide an extension trait: [`futures::stream::StreamExt`][8] and [`tokio::stream::StreamExt`][9].

[1]: https://docs.rs/tokio/0.2/tokio/io/trait.AsyncWrite.html
[2]: https://docs.rs/tokio-util/0.2/tokio_util/codec/struct.Framed.html
[3]: https://docs.rs/futures-sink/0.3/futures_sink/trait.Sink.html
[4]: https://docs.rs/futures/0.3/futures/sink/trait.SinkExt.html
[5]: https://docs.rs/futures/0.3/futures/sink/trait.SinkExt.html#method.send
[6]: https://docs.rs/futures/0.3/futures/sink/trait.SinkExt.html#method.send_all
[7]: https://docs.rs/futures/0.3.4/futures/stream/trait.Stream.html
[8]: https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html
[9]: https://docs.rs/tokio/0.2.10/tokio/stream/trait.StreamExt.html
