### ISSUE TITLE
UdpFramed documentation references non-existent feature

### ISSUE THREAD

**Issue by bitemyapp** [tokio-rs/tokio#1936]
The `frame.rs` module for UdpFramed has: `#[cfg_attr(docsrs, doc(feature = "codec-udp"))]`

https://github.com/tokio-rs/tokio/blob/7b4c999341809588a427a9a80d310ee4aa1c1a21/tokio-util/src/udp/frame.rs#L30

Is that special syntax signifying `codec` + `udp` for docs.rs or is it invalid?

**Comment by hawkw** [comment]
Off the top of my head, I _think_ this should be 
```rust
#[cfg_attr(docsrs, doc(all(feature = "codec", feature = "udp")))] 
```

**Comment by jbg** [comment]
there doesn't appear to be a `codec` feature
