### ISSUE TITLE
Public function becomes private with scheduler macro

### ISSUE THREAD

**Issue by tekjar** [tokio-rs/tokio#1944]
cargo tree | grep tokio
___ tokio v0.2.4
    ___ tokio-macros v0.2.0

## Description

Public function becomes private with scheduler macro

```

mod a {
    #[tokio::main(basic_scheduler)]
    pub async fn hello() {
        println!("hello world");
    }
}

fn main() {
    a::hello();
}
```

**Comment by DoumanAsh** [comment]
@carllerche I think we can releaes bug fix version with this fix? I doubt there will be many changes in future?
