### ISSUE TITLE
Broken links to entries prefixed with "tokio::"

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [tokio-rs/tokio#1945]
The page https://docs.rs/tokio/0.2.4/tokio/runtime/index.html includes links to the `#[tokio::main]` macro. These links point to a non-existent page https://docs.rs/tokio/0.2.4/tokio_macros/attr.main.html . It should be either https://docs.rs/tokio/0.2.4/tokio/attr.main.html or https://docs.rs/tokio-macros/0.2.0/tokio_macros/attr.main.html instead.

The same page also has a `tokio::spawn` link pointing to https://docs.rs/tokio/0.2.4/tokio/executor/fn.spawn.html . It should be https://docs.rs/tokio/0.2.4/tokio/fn.spawn.html instead.

It doesn't look like a typo, probably a rustdoc bug or misconfiguration.

**Comment by Darksonn** [comment]
This should be fixed.
