### ISSUE TITLE
Example using send_dgram/recv_dgram in a UDP client is missing

### ISSUE THREAD

**Issue by opensourcegeek** [tokio-rs/tokio#195]
For running UDP clients, send/receive is the usual way to work with it. The examples cover how to run a UDP server either by implementing Future trait directly or using UdpFramed. But a client example using send_dgram/recv_dgram that already return futures would be really helpful.

**Comment by kpp** [comment]
@opensourcegeek Isn't this [example](https://github.com/tokio-rs/tokio/blob/master/examples/connect.rs#L168) enough for you? You may run it: `cargo run --example connect -- --udp 127.0.0.1:8080`

**Comment by mexus** [comment]
I'll give it a try!
