### ISSUE TITLE
Throttle is not being exported

### ISSUE THREAD

**Issue by psmit** [tokio-rs/tokio#1951]
## Description

It seems that throttle in tokio::time is not being exported anymore, making it impossible to use. 

I think it is as easy as adding:

```
mod throttle;
pub use throttle::Throttle;
```

to tokio/src/time/mod.rs, and if that is the case I'm happy to make a PR.

**Comment by vorot93** [comment]
It requires a bit more than just a re-export. There's a PR available at #1949

**Comment by carllerche** [comment]
Throttle came back. :+1: thanks @vorot93
