### ISSUE TITLE
Bring Back shutdown_on_idle

### ISSUE THREAD

**Issue by asevans48** [tokio-rs/tokio#1957]
## Description

Shutdown on idle is now removed from the API. It is nice to have to be able to gracefully shutdown the system on a custom runtime. Can it be added back in?

**Comment by hawkw** [comment]
In `tokio` 0.2, `tokio::spawn` returns a [`JoinHandle`](https://docs.rs/tokio/0.2.4/tokio/task/struct.JoinHandle.html). You can now use those `JoinHandle`s to await the termination of spawned tasks in `block_on`, allowing more granular control over what futures keep the runtime running without requiring the runtime to track global idleness (which introduces overhead).

**Comment by carllerche** [comment]
#1879 is tracking a replacement. Until them what @hawkw said works.

**Comment by tyranron** [comment]
@carllerche #1879 is closed 😕   
What about is one, can it be reconsidered?

The soultion provided by @hawkw doesn't work well in a common case, sometimes leading to very scary hacks when we need to pass those `JoinHandle`s around via some global state.

The most common example when we need some notion of `AsyncDrop`, which we do today as `Drop` + `tokio::spawn`.
