### ISSUE TITLE
Channel Wait type is gone

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/tokio#1959]
The channel senders used to have a wait() method that retuned a sync interface to them. This is gone in 0.2. Is there a replacement available?

For context: I was using it to expose a Write implementation for an async stream. Is there a better way to do this? Should try to grab a reference to the Runtime and use block_on?

**Comment by sfackler** [comment]
futures::executor::block_on(chan.next())

**Comment by lnicola** [comment]
Teah, I imagine that would work. Thanks

**Comment by carllerche** [comment]
I would like to bring back *something*... maybe `.blocking()` instead, specifically for channels as it is a common case.

**Comment by Darksonn** [comment]
Closing as duplicate of #2629.
