### ISSUE TITLE
Failed to spawn tasks in dynamic library in plugins system

### ISSUE THREAD

**Issue by garyhai** [tokio-rs/tokio#1964]
## Version

tokio =  { version = "0.2.4", features = ["full"] }

## Platform
macOS, v10.15.1

## Subcrates
runtime

## Description

* Make a crate with crate-type = ["dylib"] 
* Export a function return an async function with tokio::spawn call in it.
* Load the dylib in another crate and call the exported function.
* Exception raised as below:

```
thread '<unnamed>' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /Users/gary/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/runtime/global.rs:50:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

If switch the runtime to async-std and call async_std::task::spawn, it works fine.

Please check test project: https://github.com/garyhai/async-plugins-test.git

**Comment by carllerche** [comment]
If you are not going via `#[tokio::main]`, you will need to manually create a runtime:

```rust
let mut rt = Runtime::new().unwrap();
rt.enter(|| {
    // whatever else
    tokio::spawn(...).
});
```

**Comment by garyhai** [comment]
I am working on a plugins system with methods registering. So I should create runtime in every method registered? I expect the functions in dynamic library can work as the local functions. Any suggestion?

**Comment by garyhai** [comment]
By the way, #[tokio::main] is applied. spawn in dynamic library function still report error.

**Comment by carllerche** [comment]
I don't know enough about the specific use case. If you have a way to store state that persists, I would store the runtime using that. Otherwise, you can always define a static runtime using `lazy_static` or something like that. To do that, you define a runtime, spawn it in a background thread, and set the handle (`runtime::Handle`) to the static variable.

**Comment by garyhai** [comment]
I just call a foreign function in #[tokio::main], it fails to work.

**Comment by garyhai** [comment]
I checked the source code of tokio::runtime. But don't know why the plain foreign function is scheduled into a fresh thread without Runtime. While local function works well to share the thread with created Runtime.

**Comment by carllerche** [comment]
One possibility is that the tokio in the foreign function is a different library somehow (different version?) than the one in `#[tokio::main]`? that would make the thread-local variables not match up.

Basically, all async IO requires an IO driver (epoll) to be running *somewhere*. Tokio does not magically start a background thread for you. You need to specify where the IO driver runs. The `#[tokio::main]` macro does this work for you.

**Comment by garyhai** [comment]
I am sure tokio is the same version as a same workspace test project. And all the code is in the #[tokio::main] Runtime. I have tried Runtime with different builder parameters.

**Comment by garyhai** [comment]
```rust
#[cfg(feature = "rt-async-std")]
#[async_std::main]
async fn main() {
    local_test().await;
    foreign_test().await;
}

#[cfg(feature = "rt-tokio")]
#[tokio::main]
async fn main() {
    local_test().await;
    foreign_test().await;
}

```

**Comment by carllerche** [comment]
Looking into it, it does look like you would need to instantiate a runtime... probably statically as I suggested above. The dylib isolates its symbols so it cannot access the runtime from the caller. This will result in each plugin having its own runtime.

**Comment by garyhai** [comment]
Thank you very much. I am eager for the solution for plug-ins projects.

**Comment by o01eg** [comment]
What about to send runtime handler to `FnRegMethod`?

**Comment by garyhai** [comment]
The runtime handler is persistent in a thread local storage, and managed by global thread pool. It can not be transferred between threads. tokio::spawn called in foreign function will spawn a "foreign" thread without Runtime initialization, while in local function the new task always pick a managed thread in the pool and scheduled in it.

**Comment by o01eg** [comment]
I suppose https://docs.rs/tokio/0.2.4/tokio/runtime/struct.Handle.html implements `Send` and can be transferred between threads.

**Comment by garyhai** [comment]
The handle can not be generate without thread-local Runtime, while the error is raised by tokio::spawn.

**Comment by lastagile** [comment]
@garyhai  Is this problem solved ? Maybe can use a tokio runtime handler

**Comment by seirdb** [comment]
I’m running into the same issue.

I’ve noticed that if I print `std::thread::current()`, the `id` is the same, but the `thread_name` is `Some(“main”)` vs `None` when inside the loaded plugin code.

**Comment by c00t** [comment]
> I’m running into the same issue.
> 
> I’ve noticed that if I print `std::thread::current()`, the `id` is the same, but the `thread_name` is `Some(“main”)` vs `None` when inside the loaded plugin code.

No, they are not the same, they just happen to have the same initial value. `name` and `id` are both implemented as thread_locals, the difference is that the `thread_name` of the thread that starts the program is initialized to `main`, and the `thread_id` is initialized to 1 (by atomically adding to a **static** counter), but dll stores its own copy of static variables. If you start another thread, you will see what happend. 

```rust
// main.rs
    // with thread_id = static_counter(0) + 1
    let thread = thread::spawn(move || {
        // with thread_id = static_counter(1) + 1
        let runtime = Runtime::new().unwrap();
        runtime.block_on(async {
            // some id, like
            // new thread: ThreadId(2)
            println!("new thread: {:?}", thread::current().id()); 
            lib.plugin_task("Cargo.toml".to_string()).await; 
        })
    });
    
    thread.join().unwrap();

// plugin/lib.rs -> plugin.dll
#[no_mangle]
pub fn plugin_task(s:_) -> FfiFuture {
    // with thread_id = static_counter(0) + 1
    // plugin thread: ThreadId(1)
    println!("plugin thread: {:?}", thread::current().id());
}
```

**Comment by JakkuSakura** [comment]
If rust could merge static and TLS between dylibs upon loading, these issues could be solved easier
