### ISSUE TITLE
join/try_join macro

### ISSUE THREAD

**Issue by Luro02** [tokio-rs/tokio#1966]
## Version
Latest

## Description

the futures-rs crate provides [try_join](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/macro.try_join.html), which allows to poll several futures concurrently and early returns, if any of the futures errored/paniced.
It returns a `Result<(Tuple of future results), E>`.

It would be nice to do the same thing, in tokio. (running try_join from futures-rs will spawn it on the futures executor, which is single threaded and not as efficient as tokio).
Maybe it's companion `join!` could be added too.
https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/macro.join.html

## Example
```rust
let a = async { Ok(1) };
let b = async { Ok(2) };
let c = async { Ok(3) };

let (r1, r2, r3) = try_join!(a, b, c)?;
```

# Futures implementation
https://github.com/rust-lang/futures-rs/blob/master/futures-macro/src/join.rs

**Comment by Luro02** [comment]
I'd be willing to implement this.

**Comment by taiki-e** [comment]
> running try_join from futures-rs will spawn it on the futures executor

no, all proc-macros in futures (join, try_join, select, select_biased) don't depend on futures' executor.

**Comment by Luro02** [comment]
okay, must have changed with the release of 0.3

**Comment by mqudsi** [comment]
For basic async projects, it's necessary to pull in the `futures` crate separately just to get the `join!` and `select!` macros - would you be willing to re-export or re-implement these?

**Comment by carllerche** [comment]
I think we will probably do that. I want to spend some time investigating the details.
