### ISSUE TITLE
interval::tick does not wait as expected

### ISSUE THREAD

**Issue by fbucek** [tokio-rs/tokio#1967]
## Version

tokio v0.2.4

## Platform

macOS 10.15

Darwin Retina-MBP.localdomain 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

## Subcrates

tokio-macros v0.2.0

## Description

interval::tick does not wait. Code from interval.rs module does not work as expected.

I am expecting that interval::tick will wait in current scope but wont be blocking current thread if another async tasks are running. Compared to std::thread::wait that would block all async tasks in current thread. Is that right?

```rust
use tokio::time::{self, Duration};

#[tokio::main]
async fn main() {

    // Get current timestamp
    let now = std::time::Instant::now();
    let mut interval = time::interval(Duration::from_millis(2000));

    interval.tick().await; // wait for 2s
    interval.tick().await; // wait for 2s
    interval.tick().await; // wait for 2s

    // Expected value: 6s
    // Actual value  : 4s 
    println!("{:?}", std::time::Instant::now() - now);
}
```

Output is

```bash
4.005027863s
````

Expected output is 6 seconds.

**Comment by malaire** [comment]
The [documentation](https://docs.rs/tokio/0.2.4/tokio/time/fn.interval.html) says that
> The first tick completes immediately

So it's

    interval.tick().await; // wait for 0s - zero wait here
    interval.tick().await; // wait for 2s
    interval.tick().await; // wait for 2s

and the result you get is 4 seconds as expected.

**Comment by fbucek** [comment]
Thanks. I missed that. So example comment is misleading. 

I thought that is is like thread::wait, but instead, it ensures that between same tick().await calls  will be delay at least specific duration. It make sense.

```rust
    interval.tick().await;
    interval.tick().await;
    interval.tick().await;

    // approximately 30ms have elapsed.  <-- maybe should be approx 20ms have elapsed 
```

**Comment by kellytk** [comment]
@fbucek Do you intend to open a PR fixing the comment?

**Comment by algebra2k** [comment]
> The [documentation](https://docs.rs/tokio/0.2.4/tokio/time/fn.interval.html) says that
> 
> > The first tick completes immediately
> 
> So it's
> 
> ```
> interval.tick().await; // wait for 0s - zero wait here
> interval.tick().await; // wait for 2s
> interval.tick().await; // wait for 2s
> ```
> 
> and the result you get is 4 seconds as expected.

good!
