### ISSUE TITLE
Nested `spawn_blocking` will panic

### ISSUE THREAD

**Issue by leoyvens** [tokio-rs/tokio#1982]
## Version

Tokio 0.2.4

## Platform

Mac

## Description

I'd expect calling `spawn_blocking` from within a task spawned with `spawn_blocking` to work, but instead it panics. If I put a task spawned with `spawn` between them, then it works.

**Comment by dbcfd** [comment]
Duplicate of #1838 ?

**Comment by carllerche** [comment]
This is a bit different. I will investigate soon. It *should* just be a question of setting the blocking pool context from a blocking task.

**Comment by carllerche** [comment]
#2006 contains a fix for this. Are you able to verify it works?
