### ISSUE TITLE
A non-#[tokio::main] example would be nice

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/tokio#1988]
There are valid reasons to avoid procedural macros, and while it's easy to spawn a runtime, it took me a couple of tries to find the right incantation (`rt.block_on(async move { run().await });`). I was using some timers, but didn't enable timer support in the run-time, and thought the error meant I'm not spawning the future properly.

An example of this would be nice.

**Comment by carllerche** [comment]
The second example here shows how: https://docs.rs/tokio/0.2.5/tokio/runtime/index.html#usage. Is this what you mean?

Where did you look first?

**Comment by carllerche** [comment]
We could probably include a snippet showing what the main macro expands to.

**Comment by lnicola** [comment]
In the examples directory.

**Comment by ultrasaurus** [comment]
I was thinking this would also be great to have as part of the documentation as a topic.

**Comment by Darksonn** [comment]
Fixed by #2683.
