### ISSUE TITLE
Moving `File::seek` broke my program.

### ISSUE THREAD

**Issue by VecrsIssues** [tokio-rs/tokio#1989]
## Version

tokio v0.2.5

## Platform

Linux 5.3.12-1-default #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081) x86_64 GNU/Linux

## Description

Tokio broke compatibility by moving `File::seek` to a trait, I'm not sure I need code for this.

```
error[E0599]: no method named `seek` found for type `tokio::fs::file::File` in the current scope
  --> src/fs_read.rs:74:14
   |
74 |         file.seek(SeekFrom::Start(start)).await?;
   |              ^^^^ method not found in `tokio::fs::file::File`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
           `use tokio::io::util::async_seek_ext::AsyncSeekExt;`
```

**Comment by carllerche** [comment]
Ah woops, this is a mistake. Thanks for pointing it out. We will issue a fix.

**Comment by carllerche** [comment]
Are you able to validate that https://github.com/tokio-rs/tokio/pull/1991 fixes the issue for you? If so, I can get 0.2.6 released shortly.

**Comment by VecrsIssues** [comment]
I can't fully confirm that this works, due to dependency issues, but I think you should publish the fix.

**Comment by carllerche** [comment]
You should be able to add a `patch.crates-io` to your crate. Something like:

```toml
[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio", branch = "fix-fs-seek" }
```

I'll get a fix out asap, but it would be good to have confirmation that it actually fixes the issue.

**Comment by VecrsIssues** [comment]
Okay, that fixes my issue.

**Comment by carllerche** [comment]
Great, thanks for verifying. As soon as I get CI to pass, i will work on a release.

**Comment by carllerche** [comment]
v0.2.6 is released: https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.6

Sorry for the inconvenience.
