### ISSUE TITLE
Cannot use Tokio Semaphore when spawning tasks

### ISSUE THREAD

**Issue by asevans48** [tokio-rs/tokio#1998]
## 0.2.6

```
[dependencies.tokio]
version="0.2.6"
features=["time", "sync", "rt-threaded"]
```

## Description

This may harken back to the removal of shutdown_on_idle but attempting to pass a permit to a spawned future results in the semaphore never living long enough. It would be great to be able to pass a permit to a spawned future that can drop the permit and free up other futures to acquire a permit.

As of now, it seems that the semaphore is practically single-threaded. No matter how I wait on a JoinHandle, the program fails. The program succeeds when using block_on instead of spawn.

## Code
```
//! Semaphore test

pub use tokio;
use tokio::sync::{Semaphore, SemaphorePermit};

pub struct TestStruct{
    sema: Semaphore,
}

async fn acquire_permit(cl: &TestStruct) -> SemaphorePermit<'_>{
    cl.sema.acquire().await
}

fn main(){
    let mut rt = tokio::runtime::Builder::new()
        .threaded_scheduler()
        .core_threads(4)
        .thread_name("test")
        .thread_stack_size(3 * 1024 * 1024)
        .enable_time()
        .build()
        .unwrap();
    let client = TestStruct{
        sema: Semaphore::new(1)
    };
    let permit: SemaphorePermit = rt.block_on(async{
        println!("Acquiring 1");
        acquire_permit(&client).await
    });
    let h = rt.spawn(async move{
        drop(permit);
    });
    let h2 = rt.spawn(async{
        println!("Acquiring 2");
        acquire_permit(&client).await;
    });
    rt.block_on(async move {
        h.await;
        h2.await;
    });
}
```
## Expected

The program will complete without error

## Actual

The program fails, complaining that the client does not liove long enough.
```

error[E0597]: `client` does not live long enough
  --> src\main.rs:28:14
   |
26 |       let permit: SemaphorePermit = rt.block_on(async{
   |  ____________________________________________________-
27 | |         println!("Acquiring 1");
28 | |         acq(&client).await
   | |         -----^^^^^^-------
   | |         |    |
   | |         |    borrowed value does not live long enough
   | |         returning this value requires that `client` is borrowed for `'static`
29 | |     });
   | |_____- value captured here by generator
...
41 |   }
   |   - `client` dropped here while still borrowed

error[E0597]: `client` does not live long enough
  --> src\main.rs:35:14
   |
33 |        let h2 = rt.spawn(async{
   |   _______________________-____-
   |  |_______________________|
   | ||
34 | ||         println!("Acquiring 2");
35 | ||         acq(&client).await;
   | ||              ^^^^^^ borrowed value does not live long enough
36 | ||     });
   | ||     -
   | ||_____|
   | |______value captured here by generator
   |        argument requires that `client` is borrowed for `'static`
...
41 |    }
   |    - `client` dropped here while still borrowed

error[E0597]: `client` does not live long enough
  --> src\main.rs:28:14
   |
26 |       let permit: SemaphorePermit = rt.block_on(async{
   |  ____________________________________________________-
27 | |         println!("Acquiring 1");
28 | |         acq(&client).await
   | |         -----^^^^^^-------
   | |         |    |
   | |         |    borrowed value does not live long enough
   | |         returning this value requires that `client` is borrowed for `'static`
29 | |     });
   | |_____- value captured here by generator
...
41 |   }
   |   - `client` dropped here while still borrowed

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0597`.
error[E0597]: `client` does not live long enough
  --> src\main.rs:35:14
   |
33 |        let h2 = rt.spawn(async{
   |   _______________________-____-
   |  |_______________________|
   | ||
34 | ||         println!("Acquiring 2");
35 | ||         acq(&client).await;
   | ||              ^^^^^^ borrowed value does not live long enough
36 | ||     });
   | ||     -
   | ||_____|
   | |______value captured here by generator
   |        argument requires that `client` is borrowed for `'static`
...
41 |    }
   |    - `client` dropped here while still borrowed

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0597`.
error: could not compile `rust-test`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `rust-test`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```

**Comment by carllerche** [comment]
Thanks for the detailed issue. You are correct that the `SemaphoreGuard` cannot be passed into spawns. As of now, there is no provided guard API that is `'static`. However, there is a work around you can use:

```rust
let semaphore = Arc::new(Semaphore::new(100));

let permit = semaphore.acquire().await;

// Do not release the permit back to the semaphore:
permit.forget();

let s2 = semaphore.clone();

tokio::spawn(async move {
    // return the permit to the semaphore
    s2.add_permits(1);
});
```

You can implement your own guard that contains `Arc<Semaphore>` to do this automatically.

I would be greatly appreciative if you could submit a doc PR to tokio that adds the above to the `Semaphore` API docs.

**Comment by asevans48** [comment]
@carllerche  Thank you for the fast reply. I will try this.

**Comment by asevans48** [comment]
Works I'll fork the project and see what I can do. Writing a production project using tokio. Very grateful for the work you put in but it might be a bit before I can actually find the time to dig into this issue further. Definitely on my backlog though.

**Comment by carllerche** [comment]
Great to hear :+1: I would love to hear more about what you are building. Feel free to ping me on discord (https://discord.gg/tokio).

**Comment by carllerche** [comment]
I would like a friendlier API for this case, but I am not sure what specifically.

**Comment by Darksonn** [comment]
For now I think we can start by mentioning the `Arc<Semaphore>` approach in the documentation. I'm marking this with `T-documentation`.

**Comment by hawkw** [comment]
> I would like a friendlier API for this case, but I am not sure what specifically.

Seems like, since `Arc<Semaphore>` is a valid method receiver, we could have a method where the `self` type is `Arc<Self>` that returns an owned guard variant?

**Comment by Darksonn** [comment]
Huh, I quite like that!

**Comment by carllerche** [comment]
Sounds good to me.

**Comment by carllerche** [comment]
It’s clever. I like it

**Comment by ICEYSELF** [comment]
Though this issue has been resolved, but in my limited opinion `Arc` is not a perfect solution. I would prefer an unsafe version of API. I wonder if there is any technological difficulties to implement unsafe API for `tokio::sync::Semaphore`?

**Comment by Darksonn** [comment]
What kind of unsafe API are you thinking of?

**Comment by ICEYSELF** [comment]
`tokio::sync::Semaphore` now has two kinds of API for acquiring permits, the one with lifetime:
```
pub async fn acquire<'_, '_>(&'_ self) -> SemaphorePermit<'_>
```
and the one with `Arc`:
```
pub async fn acquire_owned(self: Arc<Self>) -> OwnedSemaphorePermit
```
and I'm thinking about an `unsafe` version, just like:
```
pub unsafe async fn acquire_raw(*const self) -> SemaphorePermitRaw
```

**Comment by Darksonn** [comment]
You can do something like that by transmuting the reference to the `Semaphore` to a `&'static Semaphore` and using `acquire`.

**Comment by ICEYSELF** [comment]
> You can do something like that by transmuting the reference to the `Semaphore` to a `&'static Semaphore` and using `acquire`.

Okay. Thank you for your generous reply.
