### ISSUE TITLE
A way to check if Runtime has panicked tasks

### ISSUE THREAD

**Issue by MOZGIII** [tokio-rs/tokio#1999]
## Version

`0.2.6`

## Platform

Irrelevant, it's an API issue.

## Description

I'm looking for some way to detect whether the panics occurred or not at `Runtime`.
My use case is pretty simple, I just need it to fail tests if something goes wrong.
*I understand I can simply use a `basic_scheduler`, and with that setup it would panic the running thread.* That's what I ended up doing right now.

Is there a plan to enhance the API to provide some was of doing this for a multi-threaded scheduler?

**Comment by mikhailOK** [comment]
> I understand I can simply use a basic_scheduler, and with that setup it would panic the running thread. That's what I ended up doing right now.

Does it actually work?
I'm observing panics getting caught with basic_scheduler: #2002

**Comment by MOZGIII** [comment]
It worked and failed my test. I deliberately created a condition where the tested would fail, and the panic successfully failed the test. With default `Runtime`, it only prints the panic to console, but the test is green.

**Comment by MOZGIII** [comment]
Since I'm doing all this in the test environment, I'm doing a `block_on` - that might be the reason why it works for me while not working in other scenarios.

**Comment by Darksonn** [comment]
Closing in favor of #2699.
