### ISSUE TITLE
Panic Handler removed in 0.2

### ISSUE THREAD

**Issue by 95th** [tokio-rs/tokio#2008]
The panic handler support that @ry added in #1055 was somehow removed in 0.2. Currently the panicked thread dies and executor continues.

Is there an alternative way of achieving the panic handler functionality now?

Note that async-std currently aborts the executor in the same situation by default.

**Comment by carllerche** [comment]
You can call `std::panic::set_hook` directly. It is a global resource. Setting it as part of the runtime configuration provided no additional benefit.

**Comment by larsfillmore** [comment]
Consider the following program:
```rust
fn main() {
    let mut rt = tokio::runtime::Builder::new()
        .basic_scheduler()
        .enable_time()
        .build()
        .unwrap();

    let local = tokio::task::LocalSet::new();
    local.block_on(&mut rt, async {
        tokio::task::spawn_local(async {
            println!("before panic 1");
            panic!("test panic 1");
        });

        tokio::time::delay_for(std::time::Duration::from_secs(1)).await;
        println!("after timer tick");
        panic!("test panic 2");
    });

    println!("after block_on()");
}

```

It spawns a background panicking task on a `LocalSet` and makes the `LocalSet` block on another panicking task.

The current (tokio 0.2.9) behavior for `LocalSet` is to suppress the panic originating in the background task and stop on the panic in the block_on() task:
```
$ cargo run
before panic 1
thread 'main' panicked at 'test panic 1', src/main.rs:12:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
after timer tick
thread 'main' panicked at 'test panic 2', src/main.rs:17:9
$
```

How to stop the thread on any background task panic (to prevent silent failures)? Would you provide more info on the use of `std::panic::set_hook` for this?
