### ISSUE TITLE
Make tokio::process::Child stdin/stdout/stderr public fields to allow for split borrows

### ISSUE THREAD

**Issue by fegies** [tokio-rs/tokio#2009]
## Description

```rust
pub struct Child {
    child: ChildDropGuard<imp::Child>,
    stdin: Option<ChildStdin>,
    stdout: Option<ChildStdout>,
    stderr: Option<ChildStderr>,
}
```
together with the implementation of the acessors 

```rust
pub fn stdin(&mut self) -> &mut Option<ChildStdin> {
        &mut self.stdin
}
```
means that only one of the childs io streams can be accessed at a time without dropping down to unsafe code.

Making the fields public or providing an acessor borrowing multiple child io streams would remedy this.

A temporary workaround (which I would like not to have to use) would be to perform the borrow in unsafe code:
```rust
fn get_stdin_and_out<'a>(
    child: &'a mut Child,
) -> (&'a mut Option<ChildStdin>, &'a mut Option<ChildStdout>) {
    let ptr: *mut Child = child;
    unsafe {
        let sout = ptr.as_mut().unwrap().stdout();
        let sin = child.stdin();
        (sin, sout)
    }
}
```

**Comment by carllerche** [comment]
I think making the struct fields public and deprecating the accessors is fine. Let's match `std` and if we discover there is a problem, 0.3 is in the near future. WDYT @ipetkov ?

@sfackler do see any problems w/ this strategy? (making fields public & deprecating accessors)?

**Comment by ipetkov** [comment]
> I think making the struct fields public and deprecating the accessors is fine

Yes I think this is a good strategy! We can also hide the accessors from the docs as well. The `childDropGuard` will remain private so the struct is still extendable without breaking changes.
