### ISSUE TITLE
LocalSet should support spawning non-static futures

### ISSUE THREAD

**Issue by DoumanAsh** [tokio-rs/tokio#2013]
As all spawned futures are living as long as `LocalSet` itself it should be possible to spawn non-static futures

**Comment by carllerche** [comment]
This should be safe using the inherent spawn fn on `LocalSet`.

**Comment by ebkalderon** [comment]
Would this be possible on the `local_set()` free function as well? Also, is there any open pull requests for this?

**Comment by ebkalderon** [comment]
Would this be possible on the `spawn_local()` free function as well? Also, is there any ongoing work on this feature?

**Comment by Sosthene-Guedon** [comment]
Wouldn't that lead to the same issues that there was with the old scoped threads API? 
What if the `JoinHandle` is never awaited or if the LocalSet is leaked?

**Comment by Darksonn** [comment]
@Sosthene-Guedon Well, the `LocalSet` itself stores the future, so if the `LocalSet` is leaked, that future can no longer run.

That said, it's not entirely clear to me how to make it work. The `LocalSet` variable has to borrow from the variables that own the non-static data. (this is why it's definitely not possible with `spawn_local` — the `LocalSet` does not appear in the signature, so its lifetime cannot be tied up with the resource)

**Comment by akhilles** [comment]
I assume this would require changing `LocalSet` to `LocalSet<'a>` so that spawn API can be:
```rust
pub fn spawn_local<'a, F>(&self, future: F) -> JoinHandle<F::Output>
where
    F: Future + 'a,
    F::Output: 'static,
```
instead of:
```rust
pub fn spawn_local<F>(&self, future: F) -> JoinHandle<F::Output>
where
    F: Future + 'static,
    F::Output: 'static,
```
Would this be a breaking change?

An alternative approach is to introduce a `Scope` type that can spawn tasks tied to the lifetime of the scope (this is what bevy-tasks does: https://docs.rs/bevy_tasks/0.2.1/bevy_tasks/struct.TaskPool.html#method.scope). This can be done in a non-breaking way.

**Comment by Darksonn** [comment]
Yes, adding a lifetime to the `LocalSet` type is a breaking change.

**Comment by Darksonn** [comment]
It seems to me that this can already be done using the `FuturesUnordered` collection.

**Comment by akhilles** [comment]
> It seems to me that this can already be done using the `FuturesUnordered` collection.

Only for certain use-cases: every future pushed onto `FuturesUnordered` has to be of the same type and `FuturesUnordered::push` doesn't return a handle. Also, you have to pull in `futures-util` as a dependency and the `FuturesUnordered` implementation is quite complicated.

Are there any downsides to relaxing `LocalSet::spawn_local<F: Future + 'static>` to `LocalSet<'a>::spawn_local<'a, F: Future  + 'a>`?

**Comment by Darksonn** [comment]
Well the downside is that it makes the `LocalSet` type more complicated by adding a lifetime parameter. That said, we should consider this now rather than postponing it, because we can't do it once we release 1.0

**Comment by carllerche** [comment]
I don't think we are going to tackle this here.

**Comment by Darksonn** [comment]
Closing as this can be done in external crates, see e.g. [`async-executor`][1].

[1]: https://docs.rs/async-executor/
