### ISSUE TITLE
Unexpected WSAECONNRESET from UdpSocket::recv_from

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#2017]
## Version

v0.2.6

## Platform

Windows

## Subcrates

net

## Description

I found that in my project (https://github.com/shadowsocks/shadowsocks-rust/issues/179), `UdpSocket::recv_from` may return `Ok(0)` occationally and then immediately return `Err(Os { code: 10054, kind: ConnectionReset, message: "远程主机强迫关闭了一个现有的连接。" })` after that.

I have done some searching and find out that it is a common case on Windows platform: https://stackoverflow.com/questions/30749423/is-winsock-error-10054-wsaeconnreset-normal-with-udp-to-from-localhost

If you sent a packet to a destination that was closed, subsequent `recvfrom` may return `0` or `WSAECONNRESET`. This was also mentioned in https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-recvfrom .

A brute-force solution is to use `WSAIoctl` to let socket ignore `WSAECONNRESET` (in C++):

```cpp
DWORD dwBytesReturned = 0;
BOOL bNewBehavior = FALSE;
DWORD status;

status = WSAIoctl(sd,
                  SIO_UDP_CONNRESET,
                  &bNewBehavior,
                  sizeof(bNewBehavior),
                  NULL,
                  0,
                  &dwBytesReturned,
                  NULL,
                  NULL);
```

I can do that with `winapi` crate, but I need UdpSocket's `SOCKET`. Tokio v0.2.6 didn't provide it yet: https://github.com/tokio-rs/tokio/blob/master/tokio/src/net/udp/socket.rs#L408-L420 .

Or can Tokio provide a method to set this flag? `UdpSocket::set_ignore_connreset` maybe?

**Comment by zonyitoo** [comment]
I can workaround by `UdpSocket::from_std`, right now. But supporting it directly in tokio will be much more straight forward.

**Comment by Darksonn** [comment]
Closing for now. We can reconsider after mio v0.7.
