### ISSUE TITLE
Spawn trait

### ISSUE THREAD

**Issue by LinkTed** [tokio-rs/tokio#2018]
I wanted to ask if tokio provides a `struct` with the `futures::task::Spawn` trait.
I am using the recent version of `tokio = "0.2.6"` and did not found any `struct`, which implements the trait.

**Comment by carllerche** [comment]
We do not. We only depend on `futures-core` at the moment. Also, the `Spawn` trait as defined in `futures` forces an allocation where one is not required.

**Comment by carllerche** [comment]
I would suggest defining your own type that implements `futures::task::Spawn` and calls `tokio::spawn` or `tokio::runtime::Handle::spawn`.

**Comment by LinkTed** [comment]
Okay thank you for your help. I thought there was already one.

**Comment by carllerche** [comment]
There was one, but it was removed as it didn't carry its weight.
