### ISSUE TITLE
Consider merging rt-core and rt-threaded feature flags

### ISSUE THREAD

**Issue by vorot93** [tokio-rs/tokio#2024]
Right now in order to use work-stealing scheduler each user has to explicitly opt into `rt-threaded` feature flag. Otherwise basic scheduler is always used and `Builder::threaded_scheduler` runtime knob is not built.

This is pretty convoluted for a feature flag in that it doesn't strictly expand the scope of built library, but also modifies existing logic. In our case it may interfere with possible future scheduler auto-selection. Now that we have `core_threads` and `max_threads` knob, also available via proc macros (#2022), this may become a point of surprise for runtime users, both direct and via macro.

At the same time, `rt-multithreaded` only brings in `num_cpus` dependency which in itself ultimately relies on just `libc` crate. So the benefit of disabling the work-stealing scheduler is just a bit faster compile time which on its own is pretty meager.

**Comment by hawkw** [comment]
> At the same time, `rt-multithreaded` only brings in `num_cpus` dependency which in itself ultimately relies on just `libc` crate. So the benefit of disabling the work-stealing scheduler is just a bit faster compile time which on its own is pretty meager.

It's worth noting that although the feature flag doesn't pull a lot of large dependencies, it does enable a whole bunch of code _in tokio_, and in addition to increasing compile times, this also results in a noticeable impact on binary size (see https://github.com/tokio-rs/tokio/issues/1791#issuecomment-557202625). While it may not matter in all use-cases, I think this is significant enough that users who _really_ need small binaries are going to want the ability to switch it off.

**Comment by Darksonn** [comment]
Closing in favor of #2698.
