### ISSUE TITLE
Documentation mis-match for `tokio::sync::broadcast::Receiver` and `Clone`

### ISSUE THREAD

**Issue by sw17ch** [tokio-rs/tokio#2032]
## Version

As of 0.2.6. (a515f9c459d6)

## Platform

All

## Subcrates

`sync`

## Description

In the documentation for `tokio::sync::broadcast`, `Receiver` is described as supporting `Clone`, but this doesn't seem to be implemented.

https://github.com/tokio-rs/tokio/blob/a515f9c459d662b9c93d962812dc1fd8d1b32e08/tokio/src/sync/broadcast.rs#L4-L6

I can't tell if the documentation is outdated (and `Clone` should not be supported for `Receiver`), or if there's a missing `Clone` implementation for receivers.

Right now, I scatter `Sender` clones around in order to get `Receiver`s in different tasks. This makes me believe that the API was intended to have a `Clone` implementation for `Receiver`.

**Comment by LucioFranco** [comment]
This looks like an oversight in the docs, `Receiver` is not supposed to implement `Clone`. So would be good to get that removed from the docs. The only way to get more `Receiver`'s is to call `Sender::subscribe`.

**Comment by vadimcn** [comment]
> Receiver is not supposed to implement Clone

Is there a technical reason for this?  

I'm trying to implement a pub/sub-like architecture with a single publisher and multiple subscribers.  Once publisher shuts down, the subscribers must shut down as well.   
It's be nice if I could just drop the publisher, and subscribers could detect this by seeing end of the event stream.  However, currently I need to keep extra copies of the Sender around just to be able to create new subscribers, as well as an explicit way of signalling subscribers that the "real" publisher has shut down.  If I were able to clone Receiver's, this could be done much simpler.

**Comment by carllerche** [comment]
Implementing `Clone` would not be trivial. `Clone` would imply the new `Receiver` continues with the same cursor as the original receiver. This would require some non-trivial synchronization and a linear walk of all messages not yet seen by the receiver in order to increment a counter.

**Comment by albel727** [comment]
Well, one also doesn't need `Clone` for the said use-case. One needs a `Receiver::subscribe_to_same(&self) -> Self` method, or more flexible yet, a `Receiver::get_sender(&self) -> Sender` method. Both trivially implementable in the current code.

**Comment by Venryx** [comment]
Just wanted to mention for other googlers: If you're looking for a channel implementation that has `Clone` support on both its Sender and Receiver objects, the "flume" crate worked well for me: https://github.com/zesterer/flume

Not only does it have full `Clone` support, it also lets you send and receive either synchronously or asynchronously. (unlike most of the other `Clone`-compatible channel implementations I have seen)
