### ISSUE TITLE
Consider yanking outdated alpha crates and linking to the correct module

### ISSUE THREAD

**Issue by udoprog** [tokio-rs/tokio#2036]
Since #1264 - most crates have been moved back into one. However, alpha versions of the old crates are still around causing confusion. When going to https://docs.rs/tokio-process (early Google hit) you're not directed to the last stable version. Instead you get `0.3.0-alpha.2` without any indication that the crate has been deprecated in the latest version of tokio. This also makes it difficult to navigate to the last `0.1.x` compatible version in case you need to.

Consider doing the following:
* Yank outdated alpha crates.
* Create a new release of outdated `0.1.x` compatible crates pointing to documentation showing how the new structure in `0.2.x` with features should be used instead.

Non-exhaustive list of affected crates:
* https://docs.rs/tokio-process (`tokio::process`, `feature = "process"`).
  - [x] Deprecation notice (merge and add deprecation notice #2100).
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-reactor (`tokio::runtime`?).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-executor (`tokio::runtime`?).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-threadpool (`tokio::runtime`?).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-signal (`tokio::signal`,  `feature = "signal"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-timer (`tokio::time`,  `feature = "time"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-tcp (`tokio::net::tcp`,  `feature = "tcp"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-udp (`tokio::net::udp`,  `feature = "udp"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-uds (`tokio::net::unix`,  `feature = "uds"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-sync (`tokio::sync`,  `feature = "sync"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-codec (`tokio_util::codec`,  `feature = "codec"`).
  - [x] Deprecation notice (#2097, #2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-buf (deprecated)
  - [x] Deprecation notice (#2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.
* https://docs.rs/tokio-current-thread (replaced with `Runtime` + `LocalSet`)
  - [x] Deprecation notice (#2098)
  - [ ] Yank alpha versions.
  - [ ] Publish new version of outdated crate.

**Comment by Darksonn** [comment]
Being very active on the Rust user forum, I have answered the question of what happened to codec quite a few times. It would be really nice to have the doc for `tokio-codec` point to the correct location.

**Comment by Darksonn** [comment]
One alternative to yanking would be to add both a new `0.1.x` version and a new `0.2.0-alpha.x` version, both explaining updates adding text to explain where to find the version you probably want.

**Comment by LucioFranco** [comment]
This seems like a fantastic idea 👍

**Comment by udoprog** [comment]
`tokio-process` no longer exists in the `tokio` repo, so in order to make a change we might have to incorporate into this organization, or move it into the `0.1.x` branch of the `tokio` crate.

Thoughts?

**Comment by LucioFranco** [comment]
@udoprog moving it into 0.1.x I think makes sense? Where does it live now?

**Comment by carllerche** [comment]
These changes can happen in the 0.1.x branch. I would add deprecation notices in the readme, lib.rs docs then publish.

**Comment by udoprog** [comment]
> @udoprog moving it into 0.1.x I think makes sense? Where does it live now?

It seems like it was moved into tokio while `0.2.x` was being built, but eventually dropped in favor of merging it into the `tokio` crate. So it seems like the latest `tokio-process` crate was published from https://github.com/alexcrichton/tokio-process. Moving this into the `0.1.x` branch as the other crates seems like the right thing to do.

**Comment by LucioFranco** [comment]
that seems fine, we should add a note and appropriate license information but otherwise sounds good 👍

**Comment by udoprog** [comment]
Added notices to `lib.rs` as well in #2098

**Comment by udoprog** [comment]
`tokio-process` with deprecation notice added in #2100

**Comment by LucioFranco** [comment]
This has all been done, thanks for the help @udoprog

**Comment by jebrosen** [comment]
As far as I can tell rereleases weren't made for the `-alpha.*` versions, and those are still causing some confusion. For example, the `tokio-process` page https://docs.rs/tokio-process/0.2.5/tokio_process/ has that big scary button at the top "⚠ Go to latest version". At least for me, this is a bit of a "reflex click" before even reading the first page. The result then is "skipping" over the deprecation warning into the outdated docs at https://docs.rs/tokio-process/0.3.0-alpha.2/tokio_process/index.html. The same is true for `tokio-codec` as well; I haven't tested any others.

Would it be possible to make those re-releases as well?
