### ISSUE TITLE
Wait for all detached tasks

### ISSUE THREAD

**Issue by brunoczim** [tokio-rs/tokio#2039]
## Description

Tokio currently does not wait for detached tasks. From the docs:

```
Once Runtime is dropped, all runtime threads are forcibly shutdown. Any tasks that have not yet completed will be dropped.
```

[This can also be shown in this playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1ed23940b463d381e1cfb633135ddfa0).

So, my idea is that you could be able to wait for the detached threads by checking it through a method. Something like [this hypothetical code on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=de91b57a67a81bcc68f34ad42582b6ed). [Another alternative would be this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7070f198b17c119e87a594a8834ff932).

## Why detaching?

Because I need to write and flush to the stdout on a drop, and there is no way to wait for the resulting future inside an async function like drop.

**Comment by Matthias247** [comment]
At least your example should be implementable via #1879

**Comment by carllerche** [comment]
I am thinking that this is out of scope for `Runtime`, instead some additional layer as @Matthias247 proposed could be used.

As such, I am going to close this specific issue.
