### ISSUE TITLE
Sender::send must not return Result

### ISSUE THREAD

**Issue by oleganza** [tokio-rs/tokio#2072]
## Version

Tokio 0.2.6

## Description

Currently `sync::{oneshot, mpsc, broadcast}::Sender::send` returns a `Result<(),_>`. However, `Ok` does not guarantee that the value is actually delivered, making such return type unnecessarily complicated.

### Rationale:

1. If one **knows out of band** that the recipient is always around, then they have to do `.expect()` with a comment.
2. If one **does not care** whether the recipient is around, then they have to `.unwrap_or(())` with a comment.
3. If one **does care** to deliver the value, then relying on `Ok()` is not enough. The protocol should include a TCP-like acknowledgement message, which is application specific. Of course, the docs warn you about it, but people are used to rely on `Result::Ok` type to provide a guaranteed success.
4. If one **wants to clean up** resources when a channel is definitely closed, we may have a separate method `closed()->bool` to check for it, without having to necessarily send any messages to find this out. (Thanks to @hawkw for pointing out this case.)

Current design is simply annoying in cases (1,2) and dangerously misleading in case (3). I suggest the API is changed to return `()` and simply state that delivery is not guaranteed as the receiving end can disconnect at any time.

WDYT?

**Comment by hawkw** [comment]
Hmm, I've certainly seen code that relies on the `Err` side of the result to determine that the receive side has definitely ceased to exist. Then, the send-side code can clean up any resources associated with that receiver. I think this property is valuable enough that it's worth keeping around the current API. Just my two cents.

**Comment by oleganza** [comment]
>Then, the send-side code can clean up any resources associated with that receiver.

Thanks for pointing this out. IMHO, this check is better performed by an API decoupled from sending messages. E.g. if one feels like it's a moment to cleanup resources, there should be a separate method `.closed() -> bool` to use in this case.

**Comment by Darksonn** [comment]
We are mirroring the standard library, and I don't really think this is a big issue.
