### ISSUE TITLE
Missing fs::copy fn

### ISSUE THREAD

**Issue by DominicWrege** [tokio-rs/tokio#2076]
It would be nice to have an async tokio::fs::copy function like the [std](https://doc.rust-lang.org/std/fs/fn.copy.html) version.

**Comment by carllerche** [comment]
Sounds great! How about a Pr? You can look how the other fs fns are implemented. They are all shims so it shouldn’t be too hard to add a copy fn

**Comment by DominicWrege** [comment]
ok done
