### ISSUE TITLE
Observability of JoinError::Cancelled

### ISSUE THREAD

**Issue by dfoxfranke** [tokio-rs/tokio#2077]
If task A is awaiting task B's JoinHandle when the runtime is dropped, is there any guarantee (stable across future 0.2 releases) as to whether or not task A will ever wake up again and see the resulting 'cancelled' join error? Empirically, I have seen this happen, but seemingly only as a result of #2061. With that bug fixed, AFAICT the answer is reliably "no", task A will never wake up again.

Since JoinHandles don't provide any sort of cancel() method (there's no way other than dropping the runtime to cancel a task), it seems that, presently at least, cancellation JoinErrors aren't *ever* observable by any code outside the tokio crate. If this is expected to be a long-term state of affairs, I should probably update #2051 to make the is_cancelled() method either `pub(crate)` or `doc(hidden)`.

**Comment by carllerche** [comment]
At some point, there will be the ability to cancel tasks. We have not figured out the specifics yet. See [here](https://github.com/tokio-rs/tokio/issues/1879).

**Comment by carllerche** [comment]
That said, there is a possibility of races during shutdown where a task can run to see a cancelled task.

**Comment by dfoxfranke** [comment]
Thanks, that answers my question. In that case as for #2051 I'll keep `is_cancelled()` public.
