### ISSUE TITLE
runtime (threadpool) does not shutdown when thread panics

### ISSUE THREAD

**Issue by steffengy** [tokio-rs/tokio#209]
```rust
extern crate futures;
extern crate tokio;

fn main() {
    // Runtime does not shutdown ever... program never terminates
    tokio::run(futures::lazy(|| -> futures::future::FutureResult<(), ()> {panic!("test")}));
}
```

If this is expected behavior (requiring the user to handle panics), this should definitely documented.
Else and probably better, this should be handled.

**Comment by carllerche** [comment]
Thanks! This is definitely an omission.

**Comment by steffengy** [comment]
@carllerche 
Do you have any solution in mind for that?

In this case one could expect `shutdown_on_idle` (which tokio::run calls) to propagate the panic.
In other cases, where work is done concurrently, you won't necessarily want a single thread panic to shutdown the entire threadpool/runtime.

futures-cpupool simply uses "CpuFuture" as a "backchannel" for this,
since you'd expect to handle a failure when polling it anyways.

**So some ideas that could work from my point of  view so far**:
- Shutdown entire runtime by default, require explicit usage of futures `catch_unwind` to prevent this in cases where you want it (e.g. webservers, ...)
- make `tokio::run` (and other potential methods that should behave this way) use `catch_unwind` and rethrow the panic after idle shutdown

**Comment by carllerche** [comment]
ah, sorry... i'm looking into it right now.

It seems to be exposing some other limitations.

**Comment by carllerche** [comment]
I opened https://github.com/tokio-rs/tokio/pull/214.

This shuts down the worker threads, but many not result in all spawned futures to be dropped. These futures aren't leaked per se as they are tied to their notification handles, but this is probably not what is intended.

**Comment by steffengy** [comment]
@carllerche 
#214 doesn't fix the example I posted above.
This is because the worker panics, which only drops the `Worker` but not the runtime.
Then the runtime blocks until the workers are idle, which they are not because they are dead.

**Comment by carllerche** [comment]
Ah right, i read it wrong...

**Comment by carllerche** [comment]
I pushed #216 which wraps the task with a `catch_unwind`. This will not bubble up to the caller of `tokio::run` as the future passed to run is just another future submitted to the thread pool.

If the caller wishes to know if the future panicked, that should be handled by the caller.

**Comment by steffengy** [comment]
@carllerche That sounds reasonable and works.

**Comment by Marwes** [comment]
@carllerche 
> If the caller wishes to know if the future panicked, that should be handled by the caller.

What would be the best way of handling this? The following is the best/first thing I could come up with :/

```rust
pub fn run_no_panic_catch<F>(fut: F)
where
    F: Future<Item = (), Error = ()> + Send + ::std::panic::UnwindSafe + 'static,
{
    use std::sync::{Arc, Mutex};

    let error_result = Arc::new(Mutex::new(None));
    {
        let error_result = error_result.clone();
        tokio::run(
            fut.catch_unwind()
                .map_err(move |err| {
                    *error_result.lock().unwrap() = Some(err);
                })
                .and_then(|result| result),
        );
    }

    if let Some(err) = Arc::try_unwrap(error_result).unwrap().into_inner().unwrap() {
        panic!(err)
    }
}
```

It also seems that #216 have suppresed some tests in tokio itself like https://github.com/tokio-rs/tokio/blob/68b82f5721cbfa2076f53fa24961ee9273395b39/tests/runtime.rs#L49 which will not fail due to panics anymore.

**Comment by carllerche** [comment]
@Marwes you can *detect* if a panic happened by adding a `Drop` impl for the future. However, if you want to *prevent* panics for a future, that is another issue. Why do you need to prevent a future to panic?

The threadpool already internally catches panics, so it should not kill a thread.

**Comment by Marwes** [comment]
The code is from a test so if it panics for any reason I want to treat that as a test failure.

**Comment by Marwes** [comment]
I guess panics from futures dispatched onto a separate thread might still be supressed in that case though? 🤔

**Comment by carllerche** [comment]
What you probably want is to implement a future by hand with a drop impl that checks is the Future was dropped without yielding a value
