### ISSUE TITLE
Is it possible to use LocalSet from within a spawned task?

### ISSUE THREAD

**Issue by Alovchin91** [tokio-rs/tokio#2095]
## Version

tokio-macros v0.2.3
tokio v0.2.9

## Platform

MacOS 10.15.2:

Darwin 19.2.0
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

## Description

I can't find a way to use `LocalSet` inside a task spawned by `tokio::spawn` inside a `#[tokio::main]` main fn.

I tried this code:

```rust
#[tokio::main]
async fn main() {
    tokio::spawn(async move {
        let local = tokio::task::LocalSet::new();
        local.run_until(async {}).await;
    }).await.unwrap()
}
```

In this case, the compiler complains that:

```
rror[E0277]: `std::rc::Rc<tokio::task::local::Scheduler>` cannot be sent between threads safely
   --> src/main.rs:3:5
    |
3   |     tokio::spawn(async move {
    |     ^^^^^^^^^^^^ `std::rc::Rc<tokio::task::local::Scheduler>` cannot be sent between threads safely
    | 
   ::: /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/spawn.rs:123:21
    |
123 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
    = help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `std::rc::Rc<tokio::task::local::Scheduler>`
    = note: required because it appears within the type `tokio::task::local::LocalSet`
    = note: required because it appears within the type `{tokio::task::local::LocalSet, tokio::task::local::LocalSet, tokio::task::local::LocalSet, ()}`
    = note: required because it appears within the type `[static generator@src/main.rs:3:29: 6:6 {tokio::task::local::LocalSet, tokio::task::local::LocalSet, tokio::task::local::LocalSet, ()}]`
    = note: required because it appears within the type `std::future::GenFuture<[static generator@src/main.rs:3:29: 6:6 {tokio::task::local::LocalSet, tokio::task::local::LocalSet, tokio::task::local::LocalSet, ()}]>`
    = note: required because it appears within the type `impl std::future::Future`
```

From my understanding, it tries to capture a `Scheduler` from the outer context (the `main` function). (And `Rc` is obviously `!Send`.)

The only other way to run `LocalSet` that I know of is to call `LocalSet::block_on`, but it requires a `Runtime` which I don't think is possible to get from inside a context of `#[tokio::main]`, and also creating a new Runtime is not possible because I'm already in a context of a runtime.

Also, if I try to remove `await` and just pass the `Future` returned by `LocalSet::run_until` to `tokio::spawn` like this:

```rust
tokio::spawn({
    let local = tokio::task::LocalSet::new();
    local.run_until(async {})
}).await.unwrap()
```

then the compiler panics: https://github.com/rust-lang/rust/issues/68109

What I'm trying to achieve is to [run Actix inside Tokio runtime](https://actix.rs/actix/actix/struct.System.html#method.run_in_tokio) in a separate thread so I could send it a shutdown signal at some point.

Do you think there is a way to run `LocalSet` inside Tokio-spawned task? Or am I getting the whole idea of `LocalSet` wrong? 😬

Thanks!

**Comment by carllerche** [comment]
You cannot use regular `tokio::spawn` as spawned futures migrate across threads thus require `Send`. You can do something like:

```rust
#[tokio::main]
async fn main() {
    tokio::spawn_blocking(move {
        let rt = tokio::runtime::Handle::current();
        rt.block_on(async {
            let local = tokio::task::LocalSet::new();
            local.run_until(async {}).await;
        });
    }).await.unwrap()
}
```

**Comment by Alovchin91** [comment]
Thank you for the explanation, @carllerche! Unfortunately, latest version of `tokio::runtime::Handle` doesn't have the `block_on` method: https://docs.rs/tokio/0.2.9/tokio/runtime/struct.Handle.html

How can I do the same with the current API? Thanks!

**Comment by carllerche** [comment]
Oh sorry... I thought we were going to add it. Somebody still needs to write that PR :)

You can do this instead:

```rust
let rt = runtime::Handle::current();
rt.enter(|| {
    futures::executor::block_on(...)
})
```

**Comment by Alovchin91** [comment]
Thank you! Does exactly what I need 🙂 Hopefully there'll be a corresponding PR for `block_on` 🙂
