### ISSUE TITLE
Consider making broadcast Receiver recv_ref public

### ISSUE THREAD

**Issue by johnhurt** [tokio-rs/tokio#2099]
## Version
0.2.9

## Platform

MacOs, ios

## Description

I was trying to use a broadcast channel to distribute non-cloneable objects to a group of receivers, but the way broadcast receivers are written, this isn't possible.  If the recv_ref method was made public I think that would enable that as a feature.

**Comment by carllerche** [comment]
I tried initially to make it work, however I ran into lifetime problems. I believe that it _may_ require generic associated types or something like that to work.

**Comment by johnhurt** [comment]
Ah, yeah I see now. I was able to get the functionality I was looking for by (first making a few things public) and adding a `map_value` function so that I can call something arbitrary than clone on the unsafe deref. I don't think that would be a good or clean introduction to the api, but at least my curiosity is satisfied.  Thanks :)
