### ISSUE TITLE
Number of messages in UnboundedReceiver

### ISSUE THREAD

**Issue by vitorenesduarte** [tokio-rs/tokio#2102]
I was searching for some method that would let me inspect the number of pending messages in the channel and the closest thing I could found was `Stream::size_hint` (although my understanding is that this method is not implemented for `UnboundedReceiver` and `(0, None)` will be returned).

If implemented, would this be the appropriate way to check the number of pending messages?

If you have ideas about the best way to do this, I'm happy to do the work. Thanks.

**Comment by LucioFranco** [comment]
You could probably accomplish this outside of tokio too by wrapping the channel send/recv with a atomicusize counter that you fetch_add/fetch_sub.

**Comment by vitorenesduarte** [comment]
Ah, that makes sense. Thanks!

**Comment by Darksonn** [comment]
Closing in favor of #2642.
