### ISSUE TITLE
Broken Guides Link in Getting Help Section of Readme

### ISSUE THREAD

**Issue by jgould22** [tokio-rs/tokio#2105]
## Version
v0.2.9

## Platform
All

## Description
The `Guides` link in the README.md  at https://github.com/tokio-rs/tokio/blob/master/README.md#getting-help  sends you to a 404 

The link is https://tokio.rs/docs/

**Comment by LucioFranco** [comment]
Yeah looks like we need to update the link to https://tokio.rs/docs/getting-started/hello-world/

**Comment by ccope** [comment]
It appears that the link was changed from that last summer: https://github.com/tokio-rs/tokio/pull/1233

Also this github issue title has a typo ;-)

**Comment by jgould22** [comment]
:stuck_out_tongue:
