### ISSUE TITLE
Comparision of tokio-threadpool and futures-rs's thread pool?

### ISSUE THREAD

**Issue by jeehoonkang** [tokio-rs/tokio#211]
In [@aturon's blog post on futures-rs 0.2](http://aturon.github.io/2018/02/27/futures-0-2-RC/), he said that `ThreadPool` will be provided in futures-rs as a general-purpose task executor.  Also, [the Tokio 0.2 agenda](https://tokio.rs/blog/2018-02-tokio-reform-shipped/) says Tokio will decouple itself from task execution.

But recently [tokio-threadpool](https://github.com/tokio-rs/tokio/tree/master/tokio-threadpool) is being actively developed.  Is it temporary?  If not, what's the relation between the Tokio's thread pool and futures-rs's?

**Comment by carllerche** [comment]
The `tokio-threadpool` crate provides an efficient thread pool implementation geared towards workloads that involve many multiplexed unrelated asynchronous tasks, i.e., Tokio based applications.

The pool uses a work-stealing scheduling strategy, similar to Go, Erlang, Java's ForkJoin, .NET's pool, etc... This is an established scheduling algorithm for such work loads.

Besides that, future Tokio features will rely on hooking into the thread pool.

`tokio-threadpool is definitely not temporary.

I cannot comment on the thread pool included with the futures crate. Maybe @aturon has thoughts on the matter.

**Comment by jeehoonkang** [comment]
@carllerche @aturon

I just realized that `tokio_executor::Executor` really resembles `futures-rs`'s `Executor`: https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-core/src/executor.rs . I assume there are derived from the same code.

Currently there's a duplication in Tokio and futures-rs on the concept of executor and its implementations.  But there's actually no need to: while Rayon assumes significantly different workloads, it seems Tokio depends on futures-rs and Tokio and futures-rs are kinda being co-designed for the same purposes.

So how about merging the two's executor?  The merged implementation can be based on Tokio's, because [according to Tokio](https://github.com/tokio-rs/tokio/tree/master/tokio-threadpool#why-not-futures-cpupool), Tokio's thread pool is better than futures-rs's.  (As you two may well know of, `futures-rs`'s thread pool is from `futures-cpupool`: https://github.com/rust-lang-nursery/futures-rs/pull/763.)

**Comment by carllerche** [comment]
@jeehoonkang This is the plan for 0.2. The code in futures is not available to Tokio until a breaking change is made.

**Comment by carllerche** [comment]
Hope this answers your question. I'm going to close this now. Feel free to continue discussion here if you wish.

**Comment by jeehoonkang** [comment]
@carllerche Thanks for your answers!  I just wanted to know if there's a plan for merging the two thread executors 😃

**Comment by carllerche** [comment]
Ah yeah I missed that comment. 

Tokio will use the futures executor once it depends on 0.2.
