### ISSUE TITLE
#[tokio::main(basic_scheduler)] is neither deprecated nor documented

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [tokio-rs/tokio#2112]
`tokio 2.9`

[The documentation for `tokio::main` macro](https://docs.rs/tokio/0.2.9/tokio/attr.main.html) does not mention `basic_scheduler` at all.

#2022 says: "Current threaded_scheduler and basic_scheduler knobs are only retained for compatibility with existing code and are overridden if core_threads is set."

**Comment by Vlad-Shcherbina** [comment]
While we are at it, [the documentation for `tokio::main` macro](https://docs.rs/tokio/0.2.9/tokio/attr.main.html) also incorrectly says 'This is supported on feature="rt-threaded" only.'

**Comment by LucioFranco** [comment]
cc @vorot93
