### ISSUE TITLE
Missing documentation for #[tokio::main(core_threads=..., max_threads=...)]

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [tokio-rs/tokio#2113]
`tokio 2.9`

[The documentation for `tokio::main` macro](https://docs.rs/tokio/0.2.9/tokio/attr.main.html) does not explain what `core_threads` and `max_thread` options mean.

Should probably link to https://docs.rs/tokio/0.2.9/tokio/runtime/struct.Builder.html#method.core_threads and https://docs.rs/tokio/0.2.9/tokio/runtime/struct.Builder.html#method.max_threads

**Comment by LucioFranco** [comment]
cc @vorot93
