### ISSUE TITLE
how can we sync narrative docs between APIs and guide?

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/tokio#2124]
API docs are out of sync right now with website.  API docs have been fixed, but website has broken links and out of date content.  See https://github.com/tokio-rs/website/pull/404 for a stop-gap fix of the website 

* https://docs.rs/tokio/0.2.9/tokio/ and 
* https://tokio.rs/docs/overview/ 

## Version

0.2.9

## Description

At minimum we should have a note in the code here: https://github.com/tokio-rs/tokio/blob/master/tokio/src/lib.rs#L26 for docs that are duplicated on the website.  

Ideally the website would pull content from the API docs (and maybe some of the narrative docs which are getting very long should be migrated to the website).  

It would be good to keep the jumping back-and-forth and cross linking to a minimum.  It would be awesome to have an auto-generated list of links to API docs referenced in the guides and create some kind of build errors when they get out of sync.  We might even consider having the guides in this repo to make it easier to keep them in sync (and then CI with doc tests would enforce updating examples whenever APIs changes).

**Comment by Darksonn** [comment]
Closing as the new website seems to invalidate this issue.
