### ISSUE TITLE
tokio::sync::boardcast::RecvError and tokio::sync::boardcast::SendError don't implement std::fmt::Error

### ISSUE THREAD

**Issue by neetle** [tokio-rs/tokio#2132]
## Version

tokio-0.2.9

## Platform

All platforms

## Description

It looks like `tokio::sync::boardcast::RecvError` and `tokio::sync::boardcast::SendError` don't implement `std::format::Error`. I feel like this is a potential oversight - what would be the best way to have this rectified?

**Comment by LucioFranco** [comment]
https://github.com/tokio-rs/tokio/pull/2141 should fix this issue :)
