### ISSUE TITLE
Tokio panic when polling

### ISSUE THREAD

**Issue by dawid-nowak** [tokio-rs/tokio#2142]
## Version
tokio v0.2.9
tokio-macros v0.2.3
tokio-util v0.2.0
tokio-rustls v0.12.2

## Platform
Linux 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Description
Panics on poll. This is somewhat a strange problem but regularly reproducible and might as well be that tokio has nothing to do with it. I have been working with tonic/gRPC and when i restart the gRPC client and call server streaming regularly first message fails with this panic but all subsequent messages are working fine.

Trying to figure out how to debug where the problem is.

```
Message:  Should not panic!: SendError(Ok(SubscribeResponse { payload: [123, 34, 110, 97, 109, 101, 34, 58, 34, 99, 108, 105, 101, 110, 116, 34, 44, 34, 115, 117, 114, 110, 97, 109, 101, 34, 58, 34, 102, 111, 111, 111, 34, 44, 34, 99, 111, 117, 110, 116, 101, 114, 34, 58, 48, 125] }))
Location: src/libcore/result.rs:1165
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                          (7 post panic frames hidden)                          
 7: <std::future::GenFuture<T> as core::future::future::Future>::poll::ha53fd0c75b83fa18
    at <unknown source file>
 8: tokio::task::core::Core<T>::poll::h7b0b15f5e0e80564
    at <unknown source file>
 9: std::panicking::try::do_call::h3e420735e561b175
    at <unknown source file>
10: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
11: tokio::task::harness::Harness<T,S>::poll::hb44af2c865ac83ce
    at <unknown source file>
12: tokio::runtime::thread_pool::worker::GenerationGuard::run_task::hfb4b36a3d726e605
    at <unknown source file>
13: tokio::runtime::thread_pool::worker::GenerationGuard::run::h9d969abd6d5c1f82
    at <unknown source file>
14: std::thread::local::LocalKey<T>::with::hb90e9db956e44e01
    at <unknown source file>
15: tokio::runtime::thread_pool::worker::Worker::run::ha49d16178467f4de
    at <unknown source file>
16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h81ed65035635c27e
    at <unknown source file>
17: std::panicking::try::do_call::h47cf7699c4f97a91
    at <unknown source file>
18: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
19: tokio::task::harness::Harness<T,S>::poll::h3b992731047da1f6
    at <unknown source file>
20: tokio::runtime::blocking::pool::Inner::run::h50c6dbe342f4b2b7
    at <unknown source file>
21: tokio::runtime::context::enter::hae0beba33dadaf6d
    at <unknown source file>
22: std::sys_common::backtrace::__rust_begin_short_backtrace::h48e0d5c5b86412bb
    at <unknown source file>
23: std::panicking::try::do_call::h0c7f9be3365156ca
    at <unknown source file>
24: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
25: core::ops::function::FnOnce::call_once{{vtable.shim}}::hc84ec006f312e78f
    at <unknown source file>
26: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3534c64212330b0c
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h338c10574a337ece
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
28: std::sys_common::thread::start_thread::h761ac6d57710d65d
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys_common/thread.rs:13
29: std::sys::unix::thread::Thread::new::thread_start::h61c012ef60f933c0
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys/unix/thread.rs:79
30: start_thread
    at <unknown source file>
31: __clone
    at <unknown source file>
```

**Comment by udoprog** [comment]
It looks like you're running the application release mode without debug symbols.

Any chance you could re-run either in debug mode, or enable debug symbols by adding the following to your `Cargo.toml`?

```toml
[profile.release]
debug = true
```

**Comment by dawid-nowak** [comment]
@udoprog Thanks for looking into it. 
Yup. Reproduced in dev mode
"at /home/dawid/Workspace/rustycar/src/grpc_handler/mod.rs:112" is 
let r = tx.send(Ok(s)).await.expect("Should not panic!");

The application panicked (crashed).
Message:  Should not panic!: SendError(Ok(SubscribeResponse { payload: [123, 34, 110, 97, 109, 101, 34, 58, 34, 99, 108, 105, 101, 110, 116, 34, 44, 34, 115, 117, 114, 110, 97, 109, 101, 34, 58, 34, 102, 111, 111, 111, 34, 44, 34, 99, 111, 117, 110, 116, 101, 114, 34, 58, 48, 125] }))
Location: src/libcore/result.rs:1165
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                          (7 post panic frames hidden)                          
 7: core::result::Result<T,E>::expect::h2040b36fb856fe60
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
 8: <rustycar::grpc_handler::SwirAPI as rustycar::grpc_handler::client_api::client_api_server::ClientApi>::subscribe::__subscribe::{{closure}}::{{closure}}::h29ac33d659fd4e2e
    at /home/dawid/Workspace/rustycar/src/grpc_handler/mod.rs:112
 9: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}::he56ff04efea3b73f
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
10: std::future::set_task_context::h59a91228824daece
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
11: <std::future::GenFuture<T> as core::future::future::Future>::poll::he5558b5052f03991
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
12: tokio::task::core::Core<T>::poll::hb6f6b203b3a05e3a
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/core.rs:128
13: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}::h85e199c165b195f7
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:120
14: core::ops::function::FnOnce::call_once::h741dbd9d9c6785d2
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6532431c82f0ebda
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
16: std::panicking::try::do_call::h0721d21f7d62f621
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
17: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
18: std::panicking::try::h724ceb73e383511c
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
19: std::panic::catch_unwind::he9c49ecafe733978
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
20: tokio::task::harness::Harness<T,S>::poll::{{closure}}::h9cf27508afc2325b
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:101
21: tokio::loom::std::causal_cell::CausalCell<T>::with_mut::hd11e2c93c34c610f
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/loom/std/causal_cell.rs:41
22: tokio::task::harness::Harness<T,S>::poll::hd174e46c29690df3
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:100
23: tokio::task::raw::poll::ha9589d0857c87740
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:162
24: tokio::task::raw::RawTask::poll::h0def985254057210
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:113
25: tokio::task::Task<S>::run::h48e4e27967e55178
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/mod.rs:371
26: tokio::runtime::thread_pool::worker::GenerationGuard::run_task::he32b286e7278bd33
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:446
27: tokio::runtime::thread_pool::worker::GenerationGuard::process_available_work::hbafb99623396a281
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:304
28: tokio::runtime::thread_pool::worker::GenerationGuard::run::h1886c2a6f5005a9b
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:269
29: tokio::runtime::thread_pool::worker::Worker::run::{{closure}}::{{closure}}::h35324f1d513ad7c9
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:158
30: std::thread::local::LocalKey<T>::try_with::he9ccb43e571ac877
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
31: std::thread::local::LocalKey<T>::with::h136b429d38948e39
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
32: tokio::runtime::thread_pool::worker::Worker::run::{{closure}}::hd602b3c9d22f61fd
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:134
33: tokio::runtime::thread_pool::current::set::{{closure}}::h291e8c2d8230a09d
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/current.rs:47
34: std::thread::local::LocalKey<T>::try_with::hbdf807cf3eb74632
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
35: std::thread::local::LocalKey<T>::with::hc185caacfe1aeba1
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
36: tokio::runtime::thread_pool::current::set::h02b5668bfe010278
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/current.rs:29
37: tokio::runtime::thread_pool::worker::Worker::run::h726d8c18da47fb56
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/worker.rs:130
38: tokio::runtime::thread_pool::Workers::spawn::{{closure}}::{{closure}}::h235d04b17d14570e
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/thread_pool/mod.rs:113
39: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h6976671e69ff9511
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/blocking/task.rs:30
40: tokio::task::core::Core<T>::poll::h695765453b7509f2
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/core.rs:128
41: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}::he0c6748a27059fb8
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:120
42: core::ops::function::FnOnce::call_once::hce7459f08aec4b7a
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
43: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd825ba3cee569b78
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
44: std::panicking::try::do_call::h069799b85e5f759c
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
45: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
46: std::panicking::try::h21175d66ce61ab9b
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
47: std::panic::catch_unwind::h187d3a59fd128bdd
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
48: tokio::task::harness::Harness<T,S>::poll::{{closure}}::h607a6bcda3cfccc3
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:101
49: tokio::loom::std::causal_cell::CausalCell<T>::with_mut::ha58df70355f847ff
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/loom/std/causal_cell.rs:41
50: tokio::task::harness::Harness<T,S>::poll::h2046dc0099948c5a
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:100
51: tokio::task::raw::poll::haf439e22ed7c0556
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:162
52: tokio::task::raw::RawTask::poll::h0def985254057210
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:113
53: tokio::task::Task<S>::run::h36041ad0936be368
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/mod.rs:371
54: tokio::runtime::blocking::pool::run_task::hb25fd7d8a06a4d82
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/blocking/pool.rs:290
55: tokio::runtime::blocking::pool::Inner::run::h39be888b045acfb1
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/blocking/pool.rs:206
56: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}::ha3ff209a744cf85e
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/blocking/pool.rs:186
57: tokio::runtime::context::enter::h8c9ebda4c74c60aa
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/context.rs:72
58: tokio::runtime::handle::Handle::enter::h468bd5ec4cd167f3
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/handle.rs:33
59: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hc8e5f480693eca95
    at /home/dawid/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/blocking/pool.rs:185
60: std::sys_common::backtrace::__rust_begin_short_backtrace::h8fcec8c4aefdd082
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys_common/backtrace.rs:129
61: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd394855613be0e35
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:469
62: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h1ff71d7f595df636
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:317
63: std::panicking::try::do_call::h6ffe178e11c9eb67
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
64: __rust_maybe_catch_panic
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libpanic_unwind/lib.rs:78
65: std::panicking::try::h7ac4bd5e4d9119c8
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
66: std::panic::catch_unwind::h9a736ca5d50b43a9
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
67: std::thread::Builder::spawn_unchecked::{{closure}}::hf73ae8da6511ad9c
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/mod.rs:468
68: core::ops::function::FnOnce::call_once{{vtable.shim}}::hc739725ea96979e6
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
69: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h3534c64212330b0c
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
70: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h338c10574a337ece
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
71: std::sys_common::thread::start_thread::h761ac6d57710d65d
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys_common/thread.rs:13
72: std::sys::unix::thread::Thread::new::thread_start::h61c012ef60f933c0
    at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/sys/unix/thread.rs:79
73: start_thread
    at <unknown source file>
74: __clone
    at <unknown source file>
[2020-01-21T14:22:35.744068488Z INFO  rustycar::messaging_handlers::kafka_handler] Committing offsets: Ok(())

**Comment by udoprog** [comment]
So it looks like it's in your code:
```
let r = tx.send(Ok(s)).await.expect("Should not panic!");
```
And:
```
 8: <rustycar::grpc_handler::SwirAPI as rustycar::grpc_handler::client_api::client_api_server::ClientApi>::subscribe::__subscribe::{{closure}}::{{closure}}::h29ac33d659fd4e2e
    at /home/dawid/Workspace/rustycar/src/grpc_handler/mod.rs:112
```
A `send` will result in `SendError` if the receiver is closed or is dropped (<https://docs.rs/tokio/0.2.9/tokio/sync/mpsc/struct.Sender.html#errors-1>). So it looks like that is what's happening to the receiver side, which I'm assuming you control.

P.S. it might be better for you to [join the Discord](https://discord.gg/tokio), we have a `#tokio-users` channel where it's easier to go back and forth.

**Comment by dawid-nowak** [comment]
thanks, i will close for time being
