### ISSUE TITLE
tokio::spawn_blocking has slightly misleading documentation

### ISSUE THREAD

**Issue by FSMaxB-dooshop** [tokio-rs/tokio#2143]
## Version
tokio 0.2.9

## Platform

Linux 5.4.13 amd64

## Description

https://docs.rs/tokio/0.2.9/tokio/task/fn.spawn_blocking.html

> Run the provided closure on a thread where blocking is acceptable.
>
> In general, issuing a blocking call or performing a lot of compute in a future without yielding is not okay, as it may prevent the executor from driving other futures forward. A closure that is run through this method will instead be run on a dedicated thread pool for such blocking tasks without holding up the main futures executor.

This is missing the information that this thread pool for blocking tasks is going to spawn up to `max_threads - core_threads` (~512)  new threads on calls to `spawn_blocking` if no idle worker thread is available.

When I read this section in the documentation I implicitly assumed a similar behavior to the default runtime for futures, that has as many threads as the system has cores, but that doesn't seem to be the case looking at the source code.

In my case I was using it for heavy computation. I previously used `tokio-threadpool` but on porting to 0.2 I switched to `spawn_blocking` resulting in a hugely increased system load.

Knowing this I can create a separate runtime for my compute intensive workloads, but adding this information to the documentation would be helpful.

I can try to make a documentation PR if you want, but I'm writing this issue first because I'm not 100% confident in my documentation writing skills and if I got all the details correct.

**Comment by kosta** [comment]
I think the documentation should also note whether there is a limit on the number of tasks waiting to be executed if `spawn_blocking` is called many more times than threads being available. This indicated what failure mode is to be expected (memory usage / "stale work"; panics; returns errors etc.)

**Comment by FSMaxB-dooshop** [comment]
This seem to be the relevant sections:
https://github.com/tokio-rs/tokio/blob/5bf78d77ada685826b33fd62e69df179f3de8a1c/tokio/src/runtime/blocking/pool.rs#L47-L54

https://github.com/tokio-rs/tokio/blob/5bf78d77ada685826b33fd62e69df179f3de8a1c/tokio/src/runtime/blocking/pool.rs#L129-L192

The waiting tasks seem to be queued in a `VecDeque` meaning the size is only limited by available system memory if I understand correctly.

**Comment by Nemo157** [comment]
Current behaviour appears to be to panic when exceeding the pool, [running this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a766d9161aec13b08c9d4ff7cd0a0517)

```rust
#[tokio::main]
async fn main() {
    for i in 0..10000 {
        eprintln!("Running {}", i);
        tokio::task::spawn_blocking(|| std::thread::sleep(std::time::Duration::from_secs(1)));
    }
}
```

logs

```
Running 508
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1188:5

**Comment by FSMaxB-dooshop** [comment]
@Nemo157 I can't reproduce what you're seeing locally. I think this is just a limitation of the playground. They probably use cgroups or something similar to limit the amount of threads a single program can create.

**Comment by FSMaxB-dooshop** [comment]
```rust
fn main() {
    let mut runtime = tokio::runtime::Builder::new()
        .threaded_scheduler()
        .max_threads(20)
        .build().expect("Failed to build runtime.");
    runtime.block_on(spawn_blocking());
}

async fn spawn_blocking() {
    for i in 0..100 {
        eprintln!("Spawning {}", i);
        tokio::task::spawn_blocking(move ||{
            println!("Running {}", i);
            std::thread::sleep(std::time::Duration::from_secs(1));
            println!("Finished {}", i);
        });
    }
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc67c17ebf449b2a55fff1445cf489d8

This shows that if the amount of threads is limited manually, Tasks are spawned immediately and queued to be run once one of the threads becomes available.

**Comment by Nemo157** [comment]
Hmm, yes, running locally with a bit more debugging I see that it's running ~500 of the blocking tasks at a time and completes successfully. It took a while to figure out how to get the info, but [I confirmed that the playground has a 512 process limit in cgroups](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15971cffbbb9595859848a09f38db106).

It seems like Tokio should handle this case gracefully as well, but should be a separate issue.

**Comment by depombo** [comment]
> ## Version
> 
> tokio 0.2.9
> ## Platform
> 
> Linux 5.4.13 amd64
> ## Description
> 
> https://docs.rs/tokio/0.2.9/tokio/task/fn.spawn_blocking.html
> 
> > Run the provided closure on a thread where blocking is acceptable.
> > In general, issuing a blocking call or performing a lot of compute in a future without yielding is not okay, as it may prevent the executor from driving other futures forward. A closure that is run through this method will instead be run on a dedicated thread pool for such blocking tasks without holding up the main futures executor.
> 
> This is missing the information that this thread pool for blocking tasks is going to spawn up to `max_threads - core_threads` (~512) new threads on calls to `spawn_blocking` if no idle worker thread is available.
> 
> When I read this section in the documentation I implicitly assumed a similar behavior to the default runtime for futures, that has as many threads as the system has cores, but that doesn't seem to be the case looking at the source code.
> 
> In my case I was using it for heavy computation. I previously used `tokio-threadpool` but on porting to 0.2 I switched to `spawn_blocking` resulting in a hugely increased system load.
> 
> Knowing this I can create a separate runtime for my compute intensive workloads, but adding this information to the documentation would be helpful.
> 
> I can try to make a documentation PR if you want, but I'm writing this issue first because I'm not 100% confident in my documentation writing skills and if I got all the details correct.

I ran into the same confusion between the documentation and the source code as well. Thanks for pointing this out @FSMaxB-dooshop ! I have a compute intensive workload  too and having two separate run times, a basic_scheduler runtime for IO operations and a threaded_scheduler capped at the number of CPU threads - 1 seems like it might be the way to go for me. I am curious, what setup did you go with?

**Comment by Darksonn** [comment]
If anyone is up for writing a documentation PR that addresses this on `spawn_blocking`'s documentation, that would be great. A related piece of documentation was recently added to `lib.rs` in #2414, which you can use as inspiration. It could also be a good idea to link to the section from `spawn_blocking`.
