### ISSUE TITLE
tokio-net crate?

### ISSUE THREAD

**Issue by srijs** [tokio-rs/tokio#217]
I'm currently looking into porting hyper to the new, reformed tokio crate system.

Overall the changes seem more or less straight-forward, however I ran into one thing that made me less sure about how to proceed.

The tokio documentation provides this guidance:

> The tokio crate, found at the root, is primarily intended for use by application developers. Library authors should depend on the sub crates, which have greater guarantees of stability.

Wanting to use `TcpStream` and `TcpListener` in `hyper`, should I introduce a direct dependency on `tokio` here, going against this advice?

Or would it be prudent to move the `tokio::net` module into a `tokio-net` crate (or perhaps a pair of `tokio-tcp`/`tokio-udp` crates) so it can be consumed by libraries w/o introducing a `tokio` dependency?

**Comment by carllerche** [comment]
I'm thinking `tokio-tcp` / `tokio-udp`.

Hyper should not depend on the `tokio` crate. Pretty much everything in there will be moved out over time.

**Comment by srijs** [comment]
@carllerche should I make a PR to move things into a `tokio-tcp` crate, or is it not a good time for that?
