### ISSUE TITLE
how to make tokio::spawn work when it requires static?

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/tokio#2170]
## Version

```
$ cargo tree | grep tokio
└── tokio v0.2.10
    └── tokio-macros v0.2.3
```

## Platform

```
$ uname -a
Darwin newair.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64 i386 MacBookAir8,1 Darwin
```

## Description

I'm struggling to write code that conforms to the constraints of `tokio::spawn`.  It makes sense that `spawn` would require lifetimes that last as long as the program, since a thread might run independently for that long, yet I'm not sure how to satisfy that constraint.  I can often get code to compile by carefully comparing differences between an example and my code, which make me feel like I must be missing something conceptual.

Below is my latest little example which I can't get to compile.  It's just a tiny bit different from the `proxy.rs` example.  I had intended to write some more login inside the proxy, so was attempting to perform the copy logic in a function.  In this case, no error propagation is needed, but the compiler seemed to really, really want me to return a `Result`.

```async fn pipe<'a, Reader: AsyncRead + Send + Unpin, Writer: AsyncWrite + Send + Unpin>
(mut reader: Reader, mut writer:  Writer) -> Result<(), Box<dyn Error>>
{
  let mut buf = [0; 1024];
  // In a loop, read data from the src and write to the dest.
  loop {
    let n = match reader.read(&mut buf).await {
      // socket closed
      Ok(n) if n == 0 => {
        info!("src socket closed");
        return Ok(())  
      },
      Ok(n) => n,
      Err(e) => {
        eprintln!("failed to read from socket; err = {:?}", e);
        return Ok(())  
      }
    };
    info!("read {} bytes", n);

    // Write the data back
    if let Err(e) = writer.write_all(&buf[0..n]).await {
      eprintln!("failed to write to socket; err = {:?}", e);
      return Ok(())  
    }
  }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
  pretty_env_logger::init();
  let args: Vec<String> = env::args().collect();
  println!("{:?}", args);

  let src_addr = "127.0.0.1:19355";
  let dest_addr = "127.0.0.1:1935";

  info!("listen on {}", src_addr);
  let mut listener = TcpListener::bind(src_addr).await.expect("tcp listen bind");
  tokio::spawn(async move {
    let ( mut src, _) = listener.accept().await.expect("tcp listener accept");
    let ( src_reader, src_writer) = src.split();

    info!("connect to {}", dest_addr);
    let mut dest = TcpStream::connect(dest_addr).await.expect("tcp connection to destination");
    dest.set_nodelay(true).expect("dest tcp set_nodelay");
    let ( dest_reader, dest_writer) = dest.split();

    let dest_to_src = pipe(src_reader, dest_writer);
    let src_to_dest = pipe(dest_reader, src_writer);

    try_join(dest_to_src, src_to_dest).await.expect("try join");

  });

  let mut input = String::new();
  println!("press return to quit");
  std::io::stdin().read_line(&mut input).expect("stdio read_line");
  Ok(())
}
```

It fails to compile with this error:
```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be sent between threads safely
   --> src/main.rs:49:3
    |
49  |   tokio::spawn(async move {
    |   ^^^^^^^^^^^^ `(dyn std::error::Error + 'static)` cannot be sent between threads safely
    | 
   ::: /tokio-0.2.10/src/task/spawn.rs:123:21
    |
123 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
``` 

If helpful, it's in a github repo here: https://github.com/ultrasaurus/rust-tokio-proxy
The whole error is in the README :)

Thank you.

**Comment by ultrasaurus** [comment]
thx to David Barsky from tokio-docs discord, I got this to work. 
> you'll want to make the error Box<dyn Error + Send + Sync + 'static>>, I think
it really wants to you return a Send + Sync + 'static error because traits objects, unfortunately, require you to write out everything about them

So with my function signature like this: 
```
async fn pipe<'a, Reader: AsyncRead + Send + Unpin, Writer: AsyncWrite + Send + Unpin>
(mut reader: Reader, mut writer:  Writer) -> Result<(), Box<dyn Error + Send + Sync + 'static>>
```

The code works!

**Comment by ultrasaurus** [comment]
Adding docs label, so we can talk about this in the docs.  Would love it if some tokio experts were to opine on *why* this is true.  I even tried to use 'rt-core' instead of 'rt-threaded' and it still wanted a static lifetime, which seems like it shouldn't be needed for non-threaded execution, but perhaps there's another important safety constraint at work!

**Comment by ultrasaurus** [comment]
via discord discussion....

@jebrosen
> spawn doesn't (and probably can't/shouldn't) know whether or not you are using a single threaded runtime

David Barsky
> tokio::spawn's bounds are here: https://docs.rs/tokio/0.2.10/tokio/fn.spawn.html. The critical portion is this: 
```
pub fn spawn<T>(task: T) -> JoinHandle<T::Output> where
    T: Future + Send + 'static,
    T::Output: Send + 'static, 
```
> it's saying that the output of spawn needs to be Send + 'static, so adding the Send + 'static bounds to Box<dyn Error> means that the output of spawn does start to meet those bounds
but, this should on the issue

So, everything that is called from whatever is passed to spawn must be Send + 'static

**Comment by Darksonn** [comment]
This is covered by [the new tutorial](https://tokio.rs/tokio/tutorial/spawning).
