### ISSUE TITLE
Clarify documentation on sync::watch::Receiver::recv

### ISSUE THREAD

**Issue by hdevalence** [tokio-rs/tokio#2171]
## Version

0.2.10

## Description

I found the documentation for this method somewhat unclear:

https://docs.rs/tokio/0.2.10/tokio/sync/watch/struct.Receiver.html#method.recv

The documentation says that the future returns the latest value sent into the channel.  However, in that case, I'm not sure why it would be an async function, since there is always a latest value available.

The behaviour I would like (which I guess this function maybe has, due to its signature), is to return a future that will resolve to the next ready value, so that, e.g., calling `recv` once on a newly constructed channel will return a ready future with the initial value, and calling `recv` again will return a future that will not resolve until another item is sent through the sender.

**Comment by carllerche** [comment]
Does #2175 help clarify?

**Comment by hdevalence** [comment]
Yep! Those docs are very clear, thanks!
