### ISSUE TITLE
Provide a select_biased! macro

### ISSUE THREAD

**Issue by ifc2t** [tokio-rs/tokio#2181]
Since #2152 introduced the `select!` macro, is it possible to provide a `select_biased!` macro as well, similar to [the futures-rs one](https://github.com/rust-lang/futures-rs/blob/78d974c96b95bfe4a98de251f6d4441711c7d7cf/futures-util/src/async_await/select_mod.rs#L158-L303)?

It's useful in cases where the polling order _does_ matter, such as when you need to guarantee dropping a future at the next yield point.

**Comment by Darksonn** [comment]
I'm not sure adding a new macro makes sense, but we could add a `@bias` token or similar?

**Comment by carllerche** [comment]
I agree that there are use cases for controlling the poll order. However, I don't love the idea of having a separate macro for the use case.

I wonder if there is a way to work this into the `select!` macro itself. Maybe some way to annotate branches at the start as prioritized or something...

**Comment by qm3ster** [comment]
Henlo. I was having this was having this whole experience today, and here is what I learned:
The amazing and superior `tokio::select!` macro actually runs in order, it just selects a starting point with some kind of vendored pseudorandom generator, as follows:
```rust
let start = $crate::macros::support::thread_rng_n(BRANCHES);

for i in 0..BRANCHES {
    let branch;
    #[allow(clippy::modulo_one)]
    {
        branch = (start + i) % BRANCHES;
    }
```
I propose that we move all of the current implementation into a (possibly public? maybe later?) `select_starting_at!` macro that takes an additional expression to initialize `start`.

From there, we can reimplement `select!` to call that with `$crate::macros::support::thread_rng_n(BRANCHES);` and add `select_biased!` that just uses `0`, thus achieving complete code reuse.

Regarding special annotations on the arms, the current for-based design already doesn't allow patterns like "poll `A` then `C` then `B` then `D`", so for "always poll `A` first, then `B`,`C`,`D` in random order" it would have to be changed completely.

Declaration order is a well-understood pattern, and crazy patterns can be achieved with nested `select`s, if desirable.
