### ISSUE TITLE
Clearing read/write readiness for streams

### ISSUE THREAD

**Issue by polachok** [tokio-rs/tokio#2182]
## Version

0.1.x, 0.2.x

## Platform

Linux

## Description

I'd like to use `sendmsg(2)`, `recvmsg(2)` API on a socket. I can do that by using `.as_raw_fd()` and operating on raw file descriptor, but AFAIU after receiving EAGAIN (ErrorKind::WouldBlock) I have to call clear_read_ready()/clear_write_ready() which are not available on streams, only on PollEvented itself. `mem::transmute` into PollEvented works, but doesn't sound like a good idea.

**Comment by Darksonn** [comment]
Closing for now. We can reevaluate after #1190 is done.
