### ISSUE TITLE
Fuse type in tokio::stream::StreamExt is not hyperlinked and not searchable

### ISSUE THREAD

**Issue by osa1** [tokio-rs/tokio#2187]
This happens all the time (in different crates too) and it really bothers me. I'm looking at [documentation of StreamExt::fuse][1]. It returns a type called `Fuse`, but I can't see what that is. The type is not hyperlinked, and searching for it doesn't yield any results.

Only way to get any information about it is to look at the source code.

I think types mentioned by public API functions/methods should be public, otherwise I end up getting some internal type that I don't know what it is for or how to use it.

[1]: https://docs.rs/tokio/0.2.11/tokio/stream/trait.StreamExt.html?search=#method.fuse

**Comment by osa1** [comment]
Maybe I'm doing this wrong, but not exposing `Fuse` type is also making passing `fuse()`d stuff around in function arguments impossible.

**Comment by carllerche** [comment]
Ah, it's because the type is not re-exported as part of the public API.

I think that we can safely export types that implement `Stream`.

**Comment by Darksonn** [comment]
Closing in favor of #2188.
