### ISSUE TITLE
Audit TCP/UDP APIs

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#22]
The net types are expected to match `std`'s net types. The API should be audited to ensure that they still match up before we release 0.1 and commit to an API.

**Comment by carllerche** [comment]
Deviations:

* `Incoming` is a stream of `(TcpStream, SocketAddr)`, but std's is an iterator of only `TcpStream`.
* `TcpListener` should remove `only_v6` and `set_only_v6`.
* `TcpListener::from_std` why does this require the addr?
* `TcpStream::only_v6` should this go as well?
* `UdpSocket::send_dgram` takes `addr` by value.

Regarding `from_std` taking an `&addr`, I saw that mio currently needs it, but it looks like the only place it is used is [here](https://github.com/carllerche/mio/blob/master/src/sys/windows/tcp.rs#L650). Could this be replaced by calling `local_addr` on the socket?

/cc @alexcrichton

**Comment by alexcrichton** [comment]
AFAIK yes the `&addr` could be dropped in mio

**Comment by carllerche** [comment]
I created:

* https://github.com/carllerche/mio/pull/814 to remove `&addr` in Mio.
* https://github.com/tokio-rs/tokio/pull/89 to update teh `Incoming` signature.

**Comment by carllerche** [comment]
Should `only_v6` be removed from the UDP socket?

**Comment by alexcrichton** [comment]
It seems reasonable to match libstd *exactly* as much as possible, even if it means trimming back some functionality for now.

**Comment by carllerche** [comment]
This has been completed on master.
