### ISSUE TITLE
Allow unsized types in `tokio::sync::Mutex`

### ISSUE THREAD

**Issue by Diggsey** [tokio-rs/tokio#2209]
The pattern `Arc<Mutex<T>>` is often used, so allowing `T: ?Sized` enables the use of trait objects without a double indirection (`Arc<Mutex<dyn Foo>>` instead of `Arc<Mutex<Box<dyn Foo>>>`).

This would also bring it more inline with the `std::sync::Mutex` which already allows unsized types.

**Comment by carllerche** [comment]
Makes sense to me, but will that work outside of `std`? I know, for example, we cannot have custom `Arc` structs that work w/ trait objs. Could `Arc<Mutex<dyn Foo>>` work w/ std::Arc and tokio::Mutex?
