### ISSUE TITLE
threads and tokio

### ISSUE THREAD

**Issue by ufobat** [tokio-rs/tokio#221]
I am looking for more information on threads and tokio. Unfortunatelly I wasn't able to find them in the dokumentation. I am quite new to Rust, maybe I've just overseen it, but I've found the information that `tokio::spawn(future)` spawns a future on the threadpool. But what if I want to execute a Future in an own/seperate thread. (TLS offers to set a own verfiy_callback. Assuming this verify_callback blocks for a long time a cupple of incomming connections might block all workers in the thread pool). When the Future is done, is it still possible to schedule following Futures on the thread pool again? Am I allowed to `thread::spawn()` or do I need to setup somthing in a new thread so tokio still works?

**Comment by carllerche** [comment]
Sorry, I'm not entirely following.

> But what if I want to execute a Future in an own/seperate thread.

You would do something like: `thread::spawn(|| future.wait())`.

Tokio will also offer a better solution for "blocking" tasks soon.

**Comment by carllerche** [comment]
Tokio released `blocking`, you can find it in the docs as well as see how `tokio-fs` uses it.

i'm going to close this now, but if you still have a problem, please comment or open a new issue.
