### ISSUE TITLE
tokio::sync::mpsc::Sender::send should not take `&mut self` (or should not implement Clone)

### ISSUE THREAD

**Issue by aloucks** [tokio-rs/tokio#2214]
## Version
```
$ cargo tree | grep tokio
│   ├── tokio v0.2.11
│   │   ├── tokio-macros v0.2.4
│   ├── tokio-serde v0.6.0
│   └── tokio-util v0.2.0
│       └── tokio v0.2.11 (*)
├── tokio v0.2.11 (*)
├── tokio-serde v0.6.0 (*)
├── tokio-util v0.2.0 (*)
```

## Platform

Windows 10 64bit

## Description

[Sender::send](https://docs.rs/tokio/0.2.11/tokio/sync/mpsc/struct.Sender.html#method.send) and [Sender::try_send](https://docs.rs/tokio/0.2.11/tokio/sync/mpsc/struct.Sender.html#method.try_send) both take a `&mut self` receiver but this doesn't appear to be necessary. Sender implements [Clone](https://docs.rs/tokio/0.2.11/tokio/sync/mpsc/struct.Sender.html#impl-Clone) which can be used to create a `mut Sender` from a `&Sender` reference. This is also in contrast to the [std library version](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html#method.send) which only takes `&self`.

**Comment by loyd** [comment]
Also, it's in contrast to the [UnboundedSender::send](https://docs.rs/tokio/0.2.11/tokio/sync/mpsc/struct.UnboundedSender.html#method.send)

**Comment by carllerche** [comment]
Each Sender handle holds its own Send permit. This is the reason for &mut. To remove the mut requirement, an alternate back pressure model would need to be provided.

**Comment by Darksonn** [comment]
This doesn't seem like something we want to support at this time.
