### ISSUE TITLE
Detect TCP disconnect without reading or writing anything to that socket?

### ISSUE THREAD

**Issue by masnagam** [tokio-rs/tokio#2228]
## Version

* tokio: v0.2.11
  * tokio::net::tcp::TcpStream

## Description

In #483, it was discussed to use `poll_read_ready(Ready::empty())` for detecting TCP disconnect.

After that, `poll_read_ready()` was removed at 6d8cc4e4755abbd0baac9abf154837b9be011a07 according to a discussion on gitter as described in https://github.com/tokio-rs/tokio/pull/1392#issuecomment-519533786.

Is there any alternative way to detect TCP disconnect without writing or reading anything to/from that socket?

I haven't tried yet, but we might be able to use `peek()` or `poll_peek()` for this purpose.

### Background

In some situations, it's necessary to detect TCP disconnect without reading or writing anything to/from that socket.

For example, suppose an HTTP server that performs a time-consuming task for a response.  This HTTP server don't like to read data from the TCP socket for detecting disconnect in order to support HTTP keep-alive and request pipelining easily.  This HTTP server has no data to write until the task outputs something.

If there is no way to detect TCP disconnect other than reading/writing, this HTTP server cannot detect TCP disconnect until the task outputs something.

The similar situation occurs in `actix-web`.  And it seems to leak TCP sockets if clients disconnect while it waits for data from a `Stream` object:
https://github.com/masnagam/rust-case-studies/tree/master/actix-web-streaming-and-tcp-disconnect

### Related Issues

* #29
* #483
* #1182

### Example of detecting TCP disconnect using `poll_read_ready()`

* https://github.com/vi/websocat/commit/d7b0db2f8d12e6aa21dc5f1e3c6a0f04b905dd25

**Comment by masnagam** [comment]
Probably, the simplest solution is to restore [poll_read_ready()](https://github.com/tokio-rs/tokio/commit/6d8cc4e4755abbd0baac9abf154837b9be011a07#diff-518fdbe772bc565e09d579f6917df6c2L202).  However, in the historical point of view, this solution may be unacceptable in this project.

Personally, I think it's great for library users that Tokio provides lower level API as already mentioned in [#1392 (comment)](https://github.com/tokio-rs/tokio/pull/1392#issuecomment-519533786).

**Comment by Darksonn** [comment]
I think restoring `poll_read_ready()` would be fine.

**Comment by carllerche** [comment]
cc @seanmonstar

**Comment by carllerche** [comment]
This is now tracked by #2968
