### ISSUE TITLE
Executor-agnostic way of spawning a new task

### ISSUE THREAD

**Issue by mmlinford** [tokio-rs/tokio#223]
Is there a simple, "official" way of spawning a new task without necessarily knowing what kind of executor it's being run in (current_thread vs thread_pool)?

tokio::run() and tokio::spawn() work fine together, but tokio::executor::current_thread::block_on_all() does not work with tokio::spawn() or DefaultExecutor::current()::spawn() . Is this expected? Could block_on_all() be modified so make this work?

**Comment by carllerche** [comment]
`tokio::spawn` is this. However, it probably isn't fully hooked up everywhere.

**Comment by mmlinford** [comment]
Yeah, I guess that's what I was trying to communicate. Would a solution be to have block_on_all() set the DefaultExecutor to the CurrentThread instance it creates?

**Comment by carllerche** [comment]
Tokio now has the single threaded runtime which hooks everything up.
