### ISSUE TITLE
SocketAddr from UnixDatagram recv_from missing the last character

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#2230]
## Version

0.2.11

## Platform

```
Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

## Subcrates

net

## Description

Server:

```rust
let mut socket = UnixDatagram::bind("/tmp/shadowsocks-manager.sock")?;

let mut buf = [0u8; 1024];
loop {
    let (recv_len, src_addr) = socket.recv_from(&mut buf).await?;
    println!("{:?}", src_addr);
}
```

Client (in Python):

```python
import socket

cli = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
cli.bind('/tmp/shadowsocks-manager-c.sock')  # NOTE: this is the name of client's socket
cli.connect('/tmp/shadowsocks-manager.sock')

cli.send(b'ping')
print(cli.recv(1506))
```

Server receives 4 bytes sent from client, and print:

```
"/tmp/shadowsocks-manager-c.soc" (pathname)
```

Where is that missing `k`?

**Comment by zonyitoo** [comment]
I think the problem is the `len - 1` in: https://github.com/tokio-rs/mio/blob/master/src/sys/unix/uds/socketaddr.rs#L43

**Comment by kleimkuhler** [comment]
@zonyitoo I have not reproduced this using a Python client, but I don't think the issue here is in the linked code.

Tokio `0.2.11` still uses Mio `0.6.21` which in turn uses [mio-uds](https://docs.rs/mio-uds/0.6.7/mio_uds/). The code linked above is in a Mio `0.7` alpha.

To address that first, the path shortening is similar to [std](https://github.com/rust-lang/rust/blob/c06e4aca19046b07d952b16e9f002bfab38fde6b/src/libstd/sys/unix/ext/net.rs#L88) where OS path lengths are expected to be null-terminated. The path length subtraction is then needed to drop the null-terminator.

What may be happening here is that the Python client is not doing what `std` expects as linked above? If a socket's path length is not null-terminated, then the server's `println!` dispatches to this [Debug](https://github.com/rust-lang/rust/blob/c06e4aca19046b07d952b16e9f002bfab38fde6b/src/libstd/sys/unix/ext/net.rs#L243) impl where it then drops the last byte.

Maybe try making sure the client's bound path is null-terminated. Does that answer your question? I know there are a few links provided in this, but let me know if anything is not clear.

**Comment by zonyitoo** [comment]
More test with libstd's UnixDatagram:

```rust
use std::os::unix::net::UnixDatagram;

fn main() {
    let socket = UnixDatagram::bind("/tmp/shadowsocks-manager.sock").unwrap();

    let mut buf = [0u8; 65536];
    loop {
        let (n, src_addr) = socket.recv_from(&mut buf).unwrap();
        println!("size={} src={:?}", n, src_addr);
    }
}
```

Client is the same python script. And I got this result:

```
size=4 src="/tmp/shadowsocks-manager-c.soc" (pathname)
```

@kleimkuhler Could you try it on OS X?

**Comment by zonyitoo** [comment]
> Maybe try making sure the client's bound path is null-terminated.

I think the problem is OS X's bound path is not null-treminated. I am doing test with C.

**Comment by zonyitoo** [comment]
Test program in C

```c
#include <stdio.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char* argv[]) {
    int ret = 0;

    int fd = socket(AF_UNIX, SOCK_DGRAM, 0);
    if (fd < 0) {
        perror("socket");
        return EXIT_FAILURE;
    }

    struct sockaddr_un baddr;
    memset(&baddr, 0, sizeof(baddr));

    const char* BIND_PATH = "/tmp/shadowsocks-manager.sock";
    baddr.sun_family = AF_UNIX;
    strcpy(baddr.sun_path, BIND_PATH);

    unlink(BIND_PATH);

    if ((ret = bind(fd, (struct sockaddr*)&baddr, sizeof(baddr))) < 0) {
        perror("bind");
        close(fd);
        return EXIT_FAILURE;
    }

    char buf[65536];

    for (;;) {
        struct sockaddr_un caddr;
        memset(&caddr, 0, sizeof(caddr));
        socklen_t caddr_len = sizeof(caddr);

        ssize_t rcount = 0;
        if ((rcount = recvfrom(fd, buf, sizeof(buf), 0, (struct sockaddr*)&caddr, &caddr_len)) < 0) {
            perror("recvfrom");
            close(fd);
            return EXIT_FAILURE;
        }

        printf("recvfrom ret=%zd caddr_len=%u sun_len=%u sun_family=%d path=%s\n",
               rcount,
               caddr_len,
               caddr.sun_len,
               caddr.sun_family,
               caddr.sun_path);
    }

    return 0;
}
```

And test with the same Python client:

```
recvfrom ret=4 caddr_len=33 sun_len=33 sun_family=1 path=/tmp/shadowsocks-manager-c.sock
```

**Comment by zonyitoo** [comment]
Ok, I found the problem.

In OS X, `sockaddr_un` is defined as

```c
/*
 * [XSI] Definitions for UNIX IPC domain.
 */
struct  sockaddr_un {
	unsigned char   sun_len;        /* sockaddr len including null */
	sa_family_t     sun_family;     /* [XSI] AF_UNIX */
	char            sun_path[104];  /* [XSI] path name (gag) */
};
```

but Linux defines `sockaddr_un` as

```c
/* Structure describing the address of an AF_LOCAL (aka AF_UNIX) socket.  */
struct sockaddr_un
  {
    __SOCKADDR_COMMON (sun_);
    char sun_path[108];		/* Path name.  */
  };
```

and `__SOCKADDR_COMMON` is defined as

```c
#define	__SOCKADDR_COMMON(sa_prefix) \
  sa_family_t sa_prefix##family
```

So OS X has one more byte (`sun_len`) before `sun_path`! That's why!

**Comment by baum** [comment]
Should be closed this one 🖖

**Comment by jeromegn** [comment]
This is still an issue as far as I can tell. I figure some people are probably hitting this issue or maybe nobody has used UnixDatagrams on macOS? 😅 

Is there a reason this was marked as "not planned" and closed?

**Comment by zonyitoo** [comment]
Fix have been merged into cpython: https://github.com/python/cpython/pull/26866

**Comment by Darksonn** [comment]
Sorry I have no context on what this issue is, and the mio links don't work anymore. If there's still a problem, can you open a new bug report?

**Comment by zonyitoo** [comment]
@Darksonn The problem should still exist when working with older version of Python. This is a test case: https://github.com/tokio-rs/tokio/issues/2230#issuecomment-584526222 for reproducing with older version of Python (for example, Python 3.6).

The key problem was Python didn't set `sun_len` properly, which have missed the last `\0`. Rust libraries, including `mio`, `tokio`, `libstd`, reads `sun_len` and truncates `sun_path`.

Rust is doing the right thing.

**Comment by jeromegn** [comment]
I think I was mistaken. What I'm facing is probably a bug in an older version of `nix` because I can't reproduce using only tokio as server and client. Apologies!
