### ISSUE TITLE
Fix docs for time::interval

### ISSUE THREAD

**Issue by kpp** [tokio-rs/tokio#2241]
https://github.com/tokio-rs/tokio/blob/466dd4a851122ab2c2b11bf44148887e359fd938/tokio/src/time/interval.rs#L33

Shouldn't it be ~30ms because of three calls to .tick()?

**Comment by nickelc** [comment]
Yeah, you would normally assume it's 30ms. And I'm sure the tokio 0.1 equivalent behaved that way, but the first tick completes immediately.
https://github.com/tokio-rs/tokio/blob/466dd4a851122ab2c2b11bf44148887e359fd938/tokio/src/time/interval.rs#L8-L9

**Comment by Darksonn** [comment]
The docs are correct.
