### ISSUE TITLE
threads are never joined

### ISSUE THREAD

**Issue by mimoo** [tokio-rs/tokio#2243]
I'm investigating a memory leak issue, and I think it might come from this line of code: https://github.com/tokio-rs/tokio/blob/55b5e1b6adcc3f85a35d16444e496b203648c99d/tokio/src/runtime/blocking/pool.rs#L205

The `Spawner::spawn` never seem to join the thread on drop.

**Comment by Darksonn** [comment]
I am closing this due to lack of details together with the fact that the scheduler has been largely rewritten in #2273. If you have figured out the culprit of your leak and have further details, feel free to reopen.
