### ISSUE TITLE
Documentation for mpsc::Sender::poll_ready() is missing

### ISSUE THREAD

**Issue by mibes** [tokio-rs/tokio#2244]
## Version
tokio 0.2.11

## Platform

All

## Description

In our use case we need to check the mpsc::channel periodically in order to see if the Receiver hung up. We do not want to send a message (like a ping) to figure this out. The poll_ready() function seems to be fit for this purpose, but no documentation can be found on how this should be used. 

Digging through the mpsc::Sender source, we believe this is the way it could be used:

```Rust
pub async fn check_sender<T>(
    tx: &mut mpsc::Sender<T>,
) -> Result<(), tokio::sync::mpsc::error::ClosedError> {
    tokio::future::poll_fn(|cx| tx.poll_ready(cx)).await
}
```

To then use this function like:
```Rust
// Check the channel status
if let Err(err) = check_sender(&mut tx).await {
   println!("It looks like the Receiver hung up on you: {:?}", err);
   // handle disconnect
}
```

If this is indeed a valid way of using poll_ready(), it may be worthwhile to add this example to the documentation.

**Comment by najamelan** [comment]
A PR was merged that adds some documentation, see: https://docs.rs/tokio/0.2.16/tokio/sync/mpsc/struct.Sender.html

Calling `poll_ready` has a side-effect. It will reserve a slot in the internal buffer until you call the brand new `disarm` method. So if you call check_sender, you should disarm the `poll_ready` on success. Also know that it might return pending if the queue is full for an undefined time period. So it might hang your task for some time.

Sounds like the best solution for your problem would be if it had a `is_closed` method.

**Comment by mibes** [comment]
Nice! And thanks for the heads-up on the side-effect.
Indeed an is_closed() would be even better.

**Comment by Darksonn** [comment]
Sender now has a `disarm` method.
