### ISSUE TITLE
tokio::fs discards all io::Errors and gives opaque, unclear errors

### ISSUE THREAD

**Issue by djahandarie** [tokio-rs/tokio#2247]
Due to the `Err(_)` in

https://github.com/tokio-rs/tokio/blob/fc65951731506ba4bbbc08eed256b5e8b0d46655/tokio/src/fs/mod.rs#L88-L100

`tokio::fs` basically gives zero feedback why a filesystem operation fails for all of its operations (which all use `asyncify` internally); it simply says "background task failed".

I imagine there must be a reason why tokio does this (perhaps it's not easy/safe to return those `io::Error`s as is in a concurrent/asyc context?), but the current solution makes it exceptionally difficult to debug any sort of filesystem issue.

**Comment by sfackler** [comment]
That does not throw away errors produced by filesystem calls, it throws away the [`JoinError`](https://docs.rs/tokio/0.2.11/tokio/task/struct.JoinError.html) which in this context can only be returned if the filesystem call panicked.

Can you give a specific example of some code that produces an opaque, unclear error?

**Comment by djahandarie** [comment]
My mistake, I missed that JoinHandle’s Future impl had Output set to a Result itself. (I wish rustdoc made associated types a little more visible for things like Deref and Future...)

I don’t have a minimal testcase yet (can get one on Monday), but somehow I guess a panic is getting triggered. All I’m doing is join!ing 16 `fs::read`s inside a manually created tokio runtime (threaded, enable_all, thread_name) spawn, and I always hit that Err case and don’t get any further information for debugging.

**Comment by djahandarie** [comment]
I eventually figured out this was a case of not keeping the top-level task waiting on the spawned tasks, resulting in the runtime shutting down and those tasks failing midway through (with the above error).

I would have appreciated some sort of error message which would have helped suggest that while I was debugging, but my initial analysis of what was going on was certainly wrong so feel free to close this issue. Thank you!
