### ISSUE TITLE
Is there a way to dynamically configure max_threads while still using `#[tokio::main]`?

### ISSUE THREAD

**Issue by nerdrew** [tokio-rs/tokio#2248]
I'd like to be able to use `#[tokio::main]` so I don't need to pass a runtime handle throughout my code, but I'd like to be able to dynamically set the max threads at startup time, with say, an environment variable. Is that possible? Something that is worth feature-requesting?

**Comment by hawkw** [comment]
@nerdrew if you use the runtime builder rather than `#[tokio::main]`, you don't necessarily need to pass a runtime handle through everything. For example, you can do this:
```rust
fn main() {
    tokio::runtime::Builder::new()
        .core_threads(get_dynamic_number_of_threads())
        // ... other runtime configuration 
        .build()
        .unwrap()
        .block_on(async {
            // any code you would have put in `#[tokio::main]` here...
        })
}
```
everything else you've written should just work exactly as it does with `#[tokio::main]`.
}

**Comment by nerdrew** [comment]
Ah. Interesting. Cool. So `tokio::spawn` will run the task on the configured Runtime? I'm upgrading an app from tokio 0.1, where I feel like `tokio::spawn`'s documentation said it would run the task on a default runtime. Did that change 0.1 -> 0.2 or did I misunderstand the old docs?

**Comment by hawkw** [comment]
The runtime you call `block_on` on sets itself as the "default" while the `block_on` is on the stack (which is for the entirety of your program). Perhaps we should have used the term "current" rather than "default"... :)

**Comment by nerdrew** [comment]
Thanks!
