### ISSUE TITLE
Problems with IDEs

### ISSUE THREAD

**Issue by Hirrolot** [tokio-rs/tokio#2249]
I have this version of Tokio in my project:

```toml
tokio = { version = "0.2.11", features = ["full"] }
```

But absolutely all items inside the modules are not highlighted by IDEs (Vs Code with rust-analyzer and IntelliJ IDEA). It's very-very hard to work like that, do you have a quick fix?

**Comment by Hirrolot** [comment]
Just enabled experimental macro expansion in IntelliJ IDEA and it helped, but `tokio::sync` is still not highlighted.

**Comment by Darksonn** [comment]
I would post a bug to the IDE instead.
