### ISSUE TITLE
net::UnixListener: Consider exposing poll_accept()

### ISSUE THREAD

**Issue by akshayknarayan** [tokio-rs/tokio#2260]
`UnixListener::poll_accept()` is currently `pub(crate)`.

However, `TcpListener::poll_accept()` is `pub` as of this commit: https://github.com/tokio-rs/tokio/commit/8a7e57786a5dca139f5b4261685e22991ded0859#diff-a0e934bf38b64e9a75c741bff132d8adL129

The corresponding `Incoming` types do expose `poll_accept()`, but the `UnixListener` and `TcpListener` should perhaps be made consistent - i.e., either restore `pub(crate)` to `TcpListener::poll_accept()` or make `UnixListener::poll_accept()` `pub`.

**Comment by kleimkuhler** [comment]
@akshayknarayan I believe this is "temporary" until Tokio no longer depends on `mio-uds` for `UnixListener` since it does not have a stable release. If so, I think this could made `pub` once Tokio depends on a newer version of `mio`.

**Comment by de-vri-es** [comment]
This has been fixed by #2845 and #2880 :D 

Not released yet, but this issue can probably be closed now.
