### ISSUE TITLE
Confusing compilation error when sync::broadcast::Receiver<T> is not Clone

### ISSUE THREAD

**Issue by gavrie** [tokio-rs/tokio#2261]
## Version

tokio-0.2.11

## Platform

macOS (Darwin)

## Description

I started using `sync::broadcast`, and fought for a long time with a confusing compilation error when the type used as the parameter of the channel does not implement `Clone`.

Example code:

```
use tokio::stream::StreamExt;
use tokio::sync::broadcast::channel;

//#[derive(Clone)]
pub struct Foo {}

#[tokio::main]
async fn main() {
    let (_, mut rx) = channel::<Foo>(1);
    rx.next().await;
}
```

When compiling this, I get:

```
error[E0599]: no method named `next` found for type `tokio::sync::broadcast::Receiver<Foo>` in the current scope
  --> src/bin/channel_clone.rs:10:8
   |
10 |     rx.next().await;
   |        ^^^^ private field, not a method
   |
   = note: the method `next` exists but the following trait bounds were not satisfied:
           `tokio::sync::broadcast::Receiver<Foo> : tokio::stream::StreamExt`
```

Uncommenting the `derive(Clone)` fixes the issue. The root cause is that `broadcast` requires the parameter to be `Clone`:

```
// tokio/src/sync/broadcast.rs

impl<T> crate::stream::Stream for Receiver<T>
where
    T: Clone,
```

I would have expected the compilation error to mention that my custom type doesn't implement `Clone`, rather than complaining that the channel doesn't implement `StreamExt` (or even better, `Stream`).

Is this a compiler issue or a Tokio issue?

**Comment by Darksonn** [comment]
The [`channel`][1] constructor should probably require `T: Clone`.

[1]: https://docs.rs/tokio/0.2.11/tokio/sync/broadcast/fn.channel.html

**Comment by Darksonn** [comment]
I have assigned this to the v0.3 milestone, as it is a breaking change.
