### ISSUE TITLE
macOS failing to send/receive empty UDP packets?

### ISSUE THREAD

**Issue by djc** [tokio-rs/tokio#2268]
On current master, I see the `send_framed` test in tokio-util hanging (on current macOS). Apparently this is not being tested in CI, since it only tests the subcrates on Linux.

Is this something that should get fixed, or should we ignore the failure?

The latter can be done with something like:

```diff
diff --git a/tokio-util/tests/udp.rs b/tokio-util/tests/udp.rs
index 51c65c63..ecc7d422 100644
--- a/tokio-util/tests/udp.rs
+++ b/tokio-util/tests/udp.rs
@@ -8,6 +8,7 @@ use futures::future::FutureExt;
 use futures::sink::SinkExt;
 use std::io;
 
+#[cfg_attr(any(target_os = "macos", target_os = "ios"), allow(unused_assignments))]
 #[tokio::test]
 async fn send_framed() -> std::io::Result<()> {
     let mut a_soc = UdpSocket::bind("127.0.0.1:0").await?;
@@ -35,6 +36,7 @@ async fn send_framed() -> std::io::Result<()> {
         b_soc = b.into_inner();
     }
 
+    #[cfg(not(any(target_os = "macos", target_os = "ios")))]
     // test sending & receiving an empty message
     {
         let mut a = UdpFramed::new(a_soc, ByteCodec);
```

For the former, it's not obvious how to fix. It seems that macOS will just skip empty UDP packets, so the only workaround I can think of is to send something instead.

**Comment by djc** [comment]
Apparently this is a known problem (regression) in kqueue:

https://github.com/kleimkuhler/mio/commit/9355161a8ab919bfc440b75a4ac37c74b2a8e334
https://github.com/nodejs/node/issues/30030

(I pinged a contact in Apple's networking group about it.)

**Comment by kleimkuhler** [comment]
> I pinged a contact in Apple's networking group about it.

@djc Great thanks--I'm interested in hearing if you get any updates on that! Seems like this issue has been around for some time now.

**Comment by djc** [comment]
Word from Apple is that this is about to get fixed in macOS 10.15.4.

**Comment by kleimkuhler** [comment]
Oh that’s awesome. Thanks for the update!

**Comment by kleimkuhler** [comment]
@djc by the way tokio-rs/mio#1292 adds a test for this. I don't think this version is available on CI yet, but it's there to merge when available.
