### ISSUE TITLE
give the max value of Duration for timeout in document 

### ISSUE THREAD

**Issue by x1957** [tokio-rs/tokio#2271]
Confused with panic when use ***tokio::time::timeout***
```
thread 'main' panicked at 'timer error: the timer is shutdown, must be called from the context of Tokio runtime',
```
The max value for timeout duration  is  68719476735 millisecond.
https://github.com/tokio-rs/tokio/blob/master/tokio/src/time/wheel/mod.rs#L46
```
const NUM_LEVELS: usize = 6;

const MAX_DURATION: u64 = (1 << (6 * NUM_LEVELS)) - 1;
```

Maybe nobody use such big duration, but someone like me may give a big number for default timeout, will meet this panic.

Shall we document the max value or give an error when timeout duration bigger than MAX_DURATION?

**Comment by sander2** [comment]
I ran into the same issue, I am not sure why you closed it..

**Comment by Darksonn** [comment]
@sander2 Can you open a new issue instead?

**Comment by x1957** [comment]
> I ran into the same issue, I am not sure why you closed it..

no response in long time^_^

**Comment by x1957** [comment]
@sander2 reopened

**Comment by Darksonn** [comment]
Can you please post an example that reproduces the error?

**Comment by sander2** [comment]
I was trying something like `time::delay_for(time::Duration::from_secs(u64::MAX))`, as I needed an effectively infinite delay.
