### ISSUE TITLE
how to spawn multiple tasks in basic_scheduler

### ISSUE THREAD

**Issue by guotie** [tokio-rs/tokio#2272]
## Version

0.2

## Platform

windows, linux

## Description

I want run multiple ws connect in one thread, how to do it?

my code is like:
```
#[tokio::main]
async fn main() {
    let runtime = Builder::new()
        .basic_scheduler()
        .build()
        .unwrap();

    runtime.spawn(async {
        ws_1().await;
    });
    runtime.spawn(async {
        ws_2().await;
    });
}
```

when i run it, error:
```
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', 

```

**Comment by Darksonn** [comment]
If you are using the `#[tokio::main]` macro, you should not also be creating a `Runtime` object — that's what the macro does for you. You can simply use `tokio::spawn` directly or use an ordinary main function `fn main() {`.
