### ISSUE TITLE
Discord invite link is broken

### ISSUE THREAD

**Issue by rainhead** [tokio-rs/tokio#2305]
The "Chat" link at https://crates.io/crates/tokio points to an invalid Discord invitation. Someone else has invited me, but I thought I'd bring this up for others.

**Comment by halzy** [comment]
@rainhead Are you able to reproduce this? I couldn't.

**Comment by rainhead** [comment]
@halzy Seems to work now. Maybe it was a problem at Discord, or with the cookies it stored in my browser?

**Comment by Darksonn** [comment]
Ah, it got fixed over in #2299.
