### ISSUE TITLE
Proposal: allow acces to RawFd for tokio::io::Stdout

### ISSUE THREAD

**Issue by MarinPostma** [tokio-rs/tokio#2311]
## Version

I am currently using 0.2.13, and this feature mostly relate to io

## Platform

`Linux march 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux`

## Description

It is often necessary to manipulate Stdout in unix, for example to set a terminal in raw mode. For this a RawFd in necessary. It would be useful for tokio::io::Stdout to implement AsRawFd. Rust's std::io::Stdout implements it, and tokio::fs::File does too (#674, #1364). For sake of completeness, maybe Stdin should implement it too.
I don't know of the equivalent for Window, but it may be interesting to investigate there too.

**Comment by kleimkuhler** [comment]
@MarinPostma This seems reasonable especially since `std` has the implementations.

Windows has an equivalent `AsRawHandle` trait.
