### ISSUE TITLE
Expose tokio::time::clock

### ISSUE THREAD

**Issue by MOZGIII** [tokio-rs/tokio#2313]
## Version

`tokio` `0.2.13` doesn't expose it.

## Description

`tokio::time::clock` is really neat. It would be great if it's exposed at the public API.

**Comment by carllerche** [comment]
More details is needed to evaluate this request. What is the motivation behind this request? What alternatives have been tried, ...

**Comment by MOZGIII** [comment]
The main goal is to improve the test here: https://github.com/timberio/vector/blob/e3566cdcdd9a9abeebc57be5cfda1c125a870a00/src/expiring_hash_map.rs#L243-L270

No alternatives were considered. I don't have other ideas really - leaving it as is maybe.
