### ISSUE TITLE
select! with I/O read branch blocks program from exit

### ISSUE THREAD

**Issue by jayjun** [tokio-rs/tokio#2318]
## Version

```
└── tokio v0.2.13
    └── tokio-macros v0.2.5
```

## Platform

macOS Mojave 10.14.6 (Darwin Kernel Version 18.7.0)

## Description

If a `select!` branch does an I/O read but was not selected, the program does not exit.

This minimal example selects between a standard input read and timeout.

```rust
use tokio::prelude::*;

#[tokio::main]
async fn main() {
    let mut stdin = tokio::io::stdin();
    let mut buffer = [0; 8];

    let duration = std::time::Duration::from_secs(3);
    let timeout = tokio::time::delay_for(duration);

    tokio::select! {
        _ = stdin.read(&mut buffer) => println!("reading done"),
        _ = timeout => println!("timeout!"),
    }

    println!("the end")
}
```

Run it. Press Enter and the program ends as expected.

```
$ cargo run
foo
reading done
the end
$
```

Run it again but wait for timeout. It won’t exit.

```
$ cargo run
timeout!
the end
```

Pressing Enter now does end the program, which means `stdin.read(&mut buffer)` is still active and blocking the exit.

I’m not familiar with how the macro or mio works, but I expect `select!` to deregister any cancelled branches from events and certainly not prevent exits.

**Comment by Darksonn** [comment]
This is likely because `stdin` internally uses `spawn_blocking`, so it is impossible to interrupt the read.

**Comment by jayjun** [comment]
You’re right, I assumed mio has file I/O.

I don’t mind that `tokio::io` wraps blocking `std::io` calls but there are a couple of gotchas.

1. A normal program exits as long as its main thread finishes, even if child threads are blocked. But `spawn_blocking` can stop `main()` (the real one) from returning.

2. `std::io::Read::read` can be interrupted by `ErrorKind::Interrupted` but Tokio specifically made that [impossible](https://github.com/tokio-rs/tokio/blob/fce6845f2b2165c6835b0b9de8d6728da387ad79/tokio/src/io/blocking.rs#L178-L188) for `Blocking<T>`.

My workaround now is to call `shutdown_timeout` after my main task returns.

```rust
use std::time::Duration;
use tokio::prelude::*;

fn main() {
    let mut runtime = tokio::runtime::Builder::new()
        .basic_scheduler()
        .enable_all()
        .build()
        .unwrap();

    runtime.block_on(async {
        let mut stdin = tokio::io::stdin();
        let mut buffer = [0; 8];

        let duration = Duration::from_secs(3);
        let timeout = tokio::time::delay_for(duration);

        tokio::select! {
            _ = stdin.read(&mut buffer) => println!("reading done"),
            _ = timeout => println!("timeout!"),
        }

        println!("the end");
    });

    runtime.shutdown_timeout(Duration::from_secs(0));
}
```

**Comment by carllerche** [comment]
Fixing this will be not super trivial. For now, we should probably document this on stdin and suggest using shutdown with timeout

**Comment by emgre** [comment]
What's the difference between this and what was reported on https://github.com/tokio-rs/tokio/issues/589 ?

**Comment by Darksonn** [comment]
It is the same issue. We have since learned that setting stdin to nonblocking is a bad idea, and can break the program writing to our stdin. There is no real solution.

**Comment by Darksonn** [comment]
I am closing this in favor of #2466.
