### ISSUE TITLE
Support transferring FDs between processes for UnixStream and UnixDatagram

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#2322]
## Version

v0.2.13

## Platform

```
Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

and other *nix systems.

## Subcrates

net

## Description

*nix systems support transferring file descriptors between processes with  `UnixStream` and `UnixDatagram`.

**Comment by polachok** [comment]
Check out https://github.com/polachok/passfd/tree/tokio-2

**Comment by Darksonn** [comment]
Closing as duplicate of #2975. I know this one came first, but the other has more info.
