### ISSUE TITLE
When should poll_write return Error:ZeroWrite and when return Ok(0)

### ISSUE THREAD

**Issue by shuoli84** [tokio-rs/tokio#2329]
### Version
```
│   └── tokio v0.2.13
│       └── tokio-macros v0.2.5
└── tokio v0.2.13 (*)
```

### Description
I see different behavior in code, e.g, in write_all, if the underlying returns Ok(0), it will return ZeroWrite, but for write_i32 etc, they just return Poll::pending and will retry later.

**Comment by kleimkuhler** [comment]
I think the behavior we want here is for the type specific `write_`s to return `Error::WriteZero`, similar to `write_all`.

If it can't write, then it should register interest and be woken up when it's possible.

If it can write, but writes `0` bytes, then I think most cases should treat that as an error.

@shuoli84 Does that sound correct in the context of why you opened this issue?

**Comment by shuoli84** [comment]
@kleimkuhler thanks. makes a lot sense. Then we should modify write_*'s behavior?

**Comment by kleimkuhler** [comment]
@shuoli84 Yep I think that's what we'd want to do here.

**Comment by shuoli84** [comment]
@kleimkuhler could you pls help to review the pr?
