### ISSUE TITLE
tokio::fs::copy sometimes not copying permissions?

### ISSUE THREAD

**Issue by dubiousjim** [tokio-rs/tokio#2341]
## Version

Rust version 1.42.0

```
$ cargo tree | grep tokio
│   │   │   │   └── tokio-io v0.1.13
│   └── tokio v0.2.13
│       └── tokio-macros v0.2.5
│   │   │   ├── tokio v0.2.13 (*)
│   │   │   └── tokio-util v0.2.0
│   │   │       └── tokio v0.2.13 (*)
│   │   ├── tokio v0.2.13 (*)
│   │   ├── tokio v0.2.13 (*)
│   │   ├── tokio-rustls v0.13.0
│   │   │   ├── tokio v0.2.13 (*)
│   ├── tokio v0.2.13 (*)
│   ├── tokio-rustls v0.13.0 (*)
├── tokio v0.2.13 (*)
├── tokio-rustls v0.13.0 (*)
```

## Platform

Seen on Mac and Ubuntu Github CI servers (`os: [macOS-latest, ubuntu-16.04]`).

Dev machine: Linux engine1 5.4.10-x86_64-linode132 #1 SMP PREEMPT Thu Jan 9 21:17:12 UTC 2020 x86_64 GNU/Linux

## Description

I'm developing for [Deno](https://deno.land/), which uses `tokio::fs` (among other components). While writing some tests, I discovered that `tokio::fs::copy(&from, &to).await?`, which is supposed to copy the file permissions over, sometimes failed to be doing so. At least, it wouldn't show up immediately. Here is the invoking code:

```
tokio::fs::copy(&from, &to).await?;
#[cfg(unix)]
{
  use std::os::unix::fs::PermissionsExt;
  let from_meta = tokio::fs::metadata(&from).await?;
  let to_meta = tokio::fs::metadata(&to).await?;
  eprintln!("from={:o} to={:o}", from_meta.permissions().mode(), to_meta.permissions().mode());
}
```

Here is the output from some runs of that:

> from=100644 to=100644
> from=100604 to=100644
> from=100640 to=100604
> from=100604 to=100644

In all these cases, the mode on `to` is what it was before the copy started (or 0o644 if the file is being created).

But now if I try to make minimal test cases for this (using either `tokio::fs` or even `std::fs`), I can't reproduce.

```
#![warn(rust_2018_idioms)]
use std::os::unix::fs::PermissionsExt;
use std::error::Error;
use tokio;

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn Error>> {
    let f = tokio::fs::File::create("foo.txt").await?;
    f.set_permissions(PermissionsExt::from_mode(0o640)).await?;
    println!("mode1={:o}", tokio::fs::metadata("foo.txt").await?.permissions().mode());
    tokio::fs::copy("foo.txt", "bar.txt").await?;
    println!("mode2={:o}", tokio::fs::metadata("bar.txt").await?.permissions().mode());
    Ok(())
}                                                                                                                                                                                  

```

when run gives:

> mode1=100640
> mode2=100640

Any insight into what might be going on?

**Comment by dubiousjim** [comment]
The unexpected output from first code show up on my dev machine (`uname -a` output above) as well as the github CI servers.

And the attempt to make a minimal test case still fails to do so (still shows the permissions being copied over), even if I add a `tokio::fs::File::create("bar.txt").await?;` line after the `let f = ...` line, so that the destination file isn't being created by the `tokio::fs::copy`.

**Comment by dubiousjim** [comment]
In case it's relevant, the first code snippet (displaying the issue) is inside a context like this:
```
use futures::future::FutureExt;
...
  let fut = async move {
    ...
    tokio::fs::copy(&from, &to).await?;
    // etc
    ...
  };

  if is_sync {
    let res = futures::executor::block_on(fut)?;
    ...
  } else {
    let res = fut.boxed_local();
    ...
  }
```

**Comment by kleimkuhler** [comment]
@dubiousjim It looks like [tokio::fs::copy](https://github.com/tokio-rs/tokio/blob/f0bfebb7e1b1b7e86857781a6d730679b9761daf/tokio/src/fs/copy.rs#L21-L26) isn't doing a `set_permissions` anywhere like I would expect.

The second you example you provided doesn't actually produce the same output for me on macos. The files have different permissions.

**Comment by dubiousjim** [comment]
That's helpful. I'm sure that our first example (embedded inside more complex code for Deno) is failing on the Github Mac machines, and on my Linux (Arch) dev machine. I think I've seen this failure on the Github Linux (Ubuntu) machines, but can't swear to it right now. I only get reports from the first failing Github system.

My attempt to make a minimal example demonstrating the failure runs on the Linux dev machine, but I couldn't get it to show the failure. But @kleimkuhler says he does see the failure when running the minimal example on a Mac. I'll see if I can duplicate/experiment on a Mac too, but I've got an older Mac OS, so the results might not be generally applicable.

It'd be useful to know if the std::fs example fails on the setups where the tokio one does --- then it'd be a Rust issue not a tokio one.

```
use std::os::unix::fs::PermissionsExt;                                                                                                                                             

fn main() -> std::io::Result<()> {
    let f = std::fs::File::create("foo.txt")?;
    // std::fs::File::create("bar.txt")?; // try with and without this
    f.set_permissions(PermissionsExt::from_mode(0o640))?;
    println!("mode1={:o}", std::fs::metadata("foo.txt")?.permissions().mode());
    std::fs::copy("foo.txt", "bar.txt")?;
    println!("mode2={:o}", std::fs::metadata("bar.txt")?.permissions().mode());
    Ok(())
}
```

**Comment by kleimkuhler** [comment]
@dubiousjim The example using `std::fs` example doesn't fail for me on macos like it does for `tokio::fs`

**Comment by dubiousjim** [comment]
Great, thanks @kleimkuhler.

**Comment by kleimkuhler** [comment]
@dubiousjim If you have a minute to test a specific branch, let me know if b7c9b4e3001c1d022c4b272c652ef563fb1c5453 fixes it for you on linux since we're seeing different behaviors.

**Comment by dubiousjim** [comment]
Hi @kleimkuhler, I'd be glad to help track this down, but...

I know how to git-clone the branch you linked to, and expect I could figure out how to build against it on my dev machine. But the dev machine is already _not_ showing the issue **with the toy case**, so the branch you linked to is probably going to leave things working at least as well there.

Re **the more complex case in our real project**...

I'm a novice wrt cargo and the build config of our project. So I don't know how to switch out the version of tokio our project builds against. There are these lines in a Cargo.toml file:
```
tokio = { version = "0.2.13", features = ["rt-core", "tcp", "udp", "process", "fs", "blocking", "sync", "io-std", "macros", "time"] }                                              
tokio-rustls = "0.13.0"
```
Is there something I could replace them with to build against the branch you linked to?

**Comment by dubiousjim** [comment]
For our actual use case, now that I see the implementation of tokio::fs::copy in the diff that you link to, I wonder whether our project really needs to be engaging with this issue.

I had the impression that Rust's `std::fs::copy` was potentially faster than opening files and using `io::copy`. With the right OS support, the former would do the copy without ever moving the data out of kernel space. We have some options on our copy operation that require us to use the `io::copy` path some of the time, and that's working fine with copying permissions. But I was looking for the cases where we didn't need to do that, and then using `std::fs::copy` for them, because it might be more efficient. Then when we switched from `std::fs` to `tokio::fs`, I just kept the same structure. But now if I understand the code I'm looking at in the branch linked above, the `tokio::fs::copy` is just wrapping `tokio::io::copy` anyway. So we might as well simplify our code and use `tokio::io::copy` for all paths, and there we're not having permissions problems. (Because we have to manually copy the permissions ourselves.)

At the same time, though, if there is an issue with `tokio::fs::copy`, where its behavior is sometimes diverging from that of `std::fs::copy` and its own documentation, it should be identified and fixed.

**Comment by dubiousjim** [comment]
(facepalm) When trying to generate the minimal test case, I first tried on my dev machine with `std::fs` (4th code block in this thread), which copies permissions correctly. Then I converted to the `tokio::fs` code (2nd code block in this thread). But I forgot to clear the `bar.txt` file. When that is cleared, then the minimal test case does in fact show the error on my Linux machine. Looking at the implementation, I expect that the branch that @kleimkuhler linked to should fix it.

**Comment by kleimkuhler** [comment]
> . But now if I understand the code I'm looking at in the branch linked above, the tokio::fs::copy is just wrapping tokio::io::copy

Yep if you can continue to use `tokio::io::copy` that is probably okay still--depends on the use case for sure.

> When that is cleared, then the minimal test case does in fact show the error on my Linux machine

Awesome glad to hear. I was little confused why that was passing for you.
