### ISSUE TITLE
docs link broken

### ISSUE THREAD

**Issue by EverlastingBugstopper** [tokio-rs/tokio#2342]
## Version

0.2.13

## Description

https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/notify.rs#L19 the link to `Semaphore` is broken

**Comment by Darksonn** [comment]
The link appears to work both on [docs.rs][1] and when I compile locally. If you compiled the documentation locally, you need to use a special command to build the documentation as described [here][2].
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
```
If I've missed something, feel free to reopen the issue.

[1]: https://docs.rs/tokio/0.2.13/tokio/sync/struct.Notify.html
[2]: https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md#cargo-commands

**Comment by EverlastingBugstopper** [comment]
hmm weird - it does seem to work. wonder what was going on
