### ISSUE TITLE
Provide a way to start reactor and executor on the same thread

### ISSUE THREAD

**Issue by tanriol** [tokio-rs/tokio#235]
In some configurations it is desirable for some subset of futures and the reactor they depend upon to run on the same thread. For example, the application may be responsible for both a number of low-priority tasks and some high-priority, latency-sensitive one. The futures themselves can be easily run on a `current_thread` executor in a high-priority realtime thread, but the reactor they depend on needs to be high-priority too, and should ideally run on the same thread.

**Comment by tanriol** [comment]
Mentioning #234 as possibly related.

**Comment by carllerche** [comment]
Now that #234 has landed, the strategy would be to add a `single_threaded` bool on the builder. If it is set, the thread pool is not used, instead `current_thread` is.

**Comment by kpp** [comment]
runtime::Builder::build:

>```rust
    pub fn build(&mut self) -> io::Result<Runtime> {
        // Spawn a reactor on a background thread.
        let reactor = Reactor::new()?.background()?;

        // Get a handle to the reactor.
        let handle = reactor.handle().clone();

        let pool = self.threadpool_builder
            .around_worker(move |w, enter| {
                ::tokio_reactor::with_default(&handle, enter, |_| {
                    w.run();
                });
            })
            .build();
```

So the reactor spawns 1 background thread and we need 1 more thread for runtime. 2 threads total, but we need to run it in 1. Right?

**Comment by tanriol** [comment]
@kpp Are you asking about my use case? One thing that's definitely needed is the ability to configure *all required threads* with the correct scheduler, which is currently missing for the reactor thread. As for latency, I'm not exactly sure on the latency implications of an extra thread switch, but I'll try to benchmark them.

**Comment by carllerche** [comment]
What I would do is probably

1) Disable the

**Comment by carllerche** [comment]
I would probably:

1) Add `Builder::single_threaded()`
2) Disable the thread pool
3) Use `current_thread`
4) Run the reactor on the current thread
5) Have `tokio::spawn` spawn onto the current_thread executor.

That would be equivalent.

**Comment by kpp** [comment]
I thought that running reactor on the current thread would block the thread.

**Comment by carllerche** [comment]
The reactor blocks, but unblocks when there is work to be done.

**Comment by bennofs** [comment]
Is there some way to get the old behaviour of `tokio-core`'s `Core` with the current code easily? (where the event loop and the futures all run in a single thread)

**Comment by carllerche** [comment]
@bennofs This is what the issue represents.

**Comment by sdroege** [comment]
https://github.com/tokio-rs/tokio/issues/265 is related to this and has an implementation for a single-threaded reactor/executor. And another use-case where the thread-pool kills performance.

I also have a full-featured implementation of this available here: https://github.com/sdroege/gst-plugin-threadshare/blob/master/src/iocontext.rs
Feel free to copy anything needed from there

**Comment by carllerche** [comment]
I've been thinking more about this.

There is an additional complexity around adding a single threaded option. Assuming that this means using `CurrentThread` as the executor and `Runtime` then optionally contains a `CurrentThread` instance, this would make `Runtime: !Send` as `CurrentThread: !Send`.

I see 2.5 options (two are related):

* It is OK for `Runtime: !Send`. This doesn't seem great and would not be backwards compatible w/ today's API.
* We add `SingleThreadedRuntime` and `Builder::build_singlethreaded() -> SingleThreadedRuntime`
* We make `Runtime` generic over some type that differentiates it between the current variant and the single threaded variant.

**Comment by kpp** [comment]
> + We add SingleThreadedRuntime and Builder::build_singlethreaded() -> SingleThreadedRuntime

That's what I thought, because `Runtime` now contains `pool` which is ambiguous for SingleThreadedRuntime

**Comment by sdroege** [comment]
> contains a CurrentThread instance, this would make Runtime: !Send as CurrentThread: !Send

I worked around that in my implementation by not storing the `CurrentThread` instance, but a way to pass `Future`s from other threads to that thread, and then schedule them from there on the `CurrentThread`.

**Comment by Albibek** [comment]
I've tried to copy tokio-core's behaviour. Here's what I 've got.
```
let mut enter = tokio_executor::enter().expect("Enter");
let reactor = tokio_reactor::Reactor::new().expect("reactor");

let handle = reactor.handle();
tokio_reactor::with_default(&handle, &mut enter, move |e| {
    let timer = tokio_timer::timer::Timer::new(reactor);
    tokio_timer::with_default(&timer.handle(), e, move |e| {
        let mut exec = current_thread::CurrentThread::new_with_park(timer);
        let delay = tokio_timer::Delay::new(
            Instant::now() + Duration::from_secs(1),
        ).map(|_| {
            println!("DELAY");
        })
            .map_err(|e| println!("timer err: {:?}", e));
        exec.spawn(Box::new(future::empty::<(), ()>()));
        exec.spawn(Box::new(delay));

        exec.enter(e).run().expect("FUUU");
    })
});
```

It currently works single-threaded, but still is a small demo and probably requires some work to send new futures to be urn on that thread.
