### ISSUE TITLE
Require a public visible function to swap handle of Runtime instance.

### ISSUE THREAD

**Issue by garyhai** [tokio-rs/tokio#2350]
Context of Runtime use a TLS to keep Handle. If call an exported function with spawn-related function call in a loaded dynamic lib, tokio Runtime panicked at 'not currently running on the Tokio runtime.` To get ride of this issue, I have to pass Handle::current function pointer of host application to DLL, then use the function pointer to spawn tasks.

For plug-ins framework application, there is a requirement of exporting a function to add or swap handle of current CONTEXT. Even more, is there a way to merge the Runtime handle automatically according to thread context?

Please check the program [async-plugins-test](https://github.com/garyhai/async-plugins-test). To run the test:
```bash
cargo build --all
cargo run
```

**Comment by Darksonn** [comment]
It's not very clear what you are asking, but I'm guessing you're looking for the [`Handle::enter`][1] method. If I misunderstood what you were looking for, feel free to ask additional questions below.

[1]: https://docs.rs/tokio/0.2/tokio/runtime/struct.Handle.html#method.enter

**Comment by garyhai** [comment]
Thank you. The use case is call an async function with tokio::spawn call of a dylib. #2435 is just what I want.
