### ISSUE TITLE
Race in futures2 integration

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#236]
Looks like CI is failing: https://travis-ci.org/tokio-rs/tokio/jobs/354098705#L1055

cc @aturon

**Comment by aturon** [comment]
I'm able to reproduce, will work to track it down.

**Comment by aturon** [comment]
The core symptom here is that threadpool task state is appearing with an invalid value, which should not be possible since all writes are easily verified to only use valid values. So probably this is a memory safety bug elsewhere.

**Comment by carllerche** [comment]
Alright, I'll try taking a look. Thanks

**Comment by aturon** [comment]
Oh sorry, by "elsewhere" I didn't mean in your code. I meant elsewhere as in *not* in the threadpool code.

**Comment by aturon** [comment]
(I'm actively working to debug this)

**Comment by aturon** [comment]
@carllerche OK so you made me curious -- I tried running the original `hammer_split` test for futures 0.1, and it's just immediately deadlocking for me (no panics though). So... not sure what to think.

**Comment by aturon** [comment]
Deadlocks in release mode as well.

**Comment by aturon** [comment]
@carllerche OK, I'm reasonably confident this is an existing issue.

To reproduce the problem, try modifying `global.rs` (the original test) to run the body of `hammer_split` in a `loop`. You will consistently get panics and/or segfaults, *without* turning on unstable-futures.

**Comment by aturon** [comment]
For reference, here's the modified version of the test I'm running: https://gist.github.com/aturon/cb57706164d96495b6b78b75c977b4e5

When I do `cargo test hammer_split --test global -- --nocapture` I get segfaults every time, usually after just a few iterations.

**Comment by kpp** [comment]
Are you sure your segfaults are not linked with mine? https://github.com/tokio-rs/tokio/pull/233

**Comment by carllerche** [comment]
So, it is possible that there are multiple issues. However, I am pretty certain I have identified at least one with `AtomicTask`. I will be working on a fix.

**Comment by carllerche** [comment]
This is fixed by #243.
