### ISSUE TITLE
Feature: support std::io in tokio_util::codec

### ISSUE THREAD

**Issue by Plecra** [tokio-rs/tokio#2367]
The `codec::Encoder` and `codec::Decoder` traits describe operations on available data, and could be useful in any context where we want to frame a series of bytes.

As they don't contain async methods, I think it would be a good idea to implement `Iterator`, `io::Read`, and `io::Write` for `FramedRead<Read, Decoder>`, `FramedRead<Read, Decoder<Item = AsRef<[u8]>>`, and `FramedWrite<Write, Encoder>` respectively.

Would this be possible and a welcome change? I'd like to make a PR if all's good.

**Comment by Darksonn** [comment]
I think this should go in its own crate.

**Comment by Plecra** [comment]
I believe having both implementations available on the same struct is useful for avoiding code duplication in libraries depending on tokio-codec. Some libraries like to provide sync and async versions of their APIs, and this would allow them to implement both versions over the same types.

Do you think a duplicate version of `FramedRead` with its own AsyncRead/Read etc implementations should be made?

**Comment by Darksonn** [comment]
I still think the codec module should only provide async versions of the api. That said, I would be ok with adding another module to `tokio-util` with an async-to-blocking adapter for `Stream`, `AsyncRead` and `AsyncWrite`.
