### ISSUE TITLE
consider add DirBuilder and implement std::os::unix::fs::DirBuilderExt

### ISSUE THREAD

**Issue by Sherlock-Holo** [tokio-rs/tokio#2369]
## Version

0.2.15

## Platform

Linux

## Description

I read `tokio` doc but don't find `DirBuilder` like `std::fs::DirBuilder`.

It's a good idea to support `DirBuilder` like `std::fs::DirBuilder`, and make it implement `std::os::unix::fs::DirBuilderExt`

**Comment by shkurski** [comment]
Hi!
I'd be interested in giving it a go. It seems that a thin wrapper around `std::fs::DirBuilder` should be sufficient, similar to how `tokio::fs::OpenOptions` is implemented. What do you think? I'm new to the Rust, so I'd appreciate it if you could point on any potential pitfalls you see (from both Rust and Tokio perspectives) with this approach.

**Comment by Darksonn** [comment]
Yeah, that's more or less the strategy. The crucial thing is to ensure that any blocking operation uses `asyncify` like you see on [`OpenOptions::open`][2] ([view source][1]).

If you have any questions or just want to say hi, I recommend joining [our Discord server][3].

[1]: https://docs.rs/tokio/0.2.20/src/tokio/fs/open_options.rs.html#378-384
[2]: https://docs.rs/tokio/0.2/tokio/fs/struct.OpenOptions.html#method.open
[3]: https://discord.gg/tokio
