### ISSUE TITLE
Chat Example returns NotReady without waking the task

### ISSUE THREAD

**Issue by JonasZ95** [tokio-rs/tokio#237]
https://github.com/tokio-rs/tokio/blob/master/examples/chat.rs#L354

Unless I misunderstood something If any data is read from the socket which does not contain "\r\n"(a full line) It will simply return NotReady without ever getting woken up.

**Comment by kpp** [comment]
Looks like the same: https://github.com/tokio-rs/tokio/issues/186

**Comment by JonasZ95** [comment]
@kpp, It would've been different.

However I oversaw that 'fill_read_buf' never return Ready unless the socket is closed. So It's definitly not a bug and will work fine.
