### ISSUE TITLE
How to use a global runtime for all tests?

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/tokio#2374]
Is it possible to use the same runtime instance to run all tests?

The use case:
An instance of my application is created and stored in a `lazy_static` object to be used by all tests; this application internally uses an async connection pool based on tokio.

The problem:
`[tokio::test]` creates a new runtime for each test, so:
- the async connection pool of the application is initialized when the first test accesses it
- the async connection pool is then bound to the runtime of the first test
- when the first test ends, its runtime is closed and consequently, the pool is also closed 
- then, all other tests fail because the pool is closed.

To solve this I would like `[tokio::test]` to use a single runtime instance for all tests.

For example, an idea could be:
```rust

lazy_static! {
    static ref MY_APP: MyApp = MyApp::default();
 }

#[tokio::test(runtime = "rt()")] // <-- HERE I WOULD LIKE TO PASS A CUSTOM RUNTIME
async fn test_1() {
   MY_APP.do_something().await;
}

#[tokio::test(runtime = "rt()")] // <-- HERE I WOULD LIKE TO PASS A CUSTOM RUNTIME
async fn test_2() {
   MY_APP.do_something().await;
}

fn rt() -> &'static tokio::runtime::Runtime {
    lazy_static! {
        static ref RT: tokio::runtime::Runtime = tokio::runtime::Builder::new()
        .threaded_scheduler()
        .enable_all()
        .build()
        .expect("Should create a tokio runtime");
    }
    &RT
}
```

**Comment by LucioFranco** [comment]
I would suggest that using a global connection pool like that is generally an anti pattern and generates surprising effects. I personally would suggest removing the global pool and using the same tokio::test macro. This is by far the best way to reduce tests affecting each other in weird ways.

**Comment by ufoscout** [comment]
@LucioFranco 
The application and the pool are global/static only for the integration tests because considering that the app starts in a couple of seconds and that we have thousands of tests, then the execution time of the tests would grow considerably if we restart the app for each test.

In addition, in this particular case, the application is a web server that uses postgres as the storage layer and, of course, it internally manages all accesses to the DB through a connection pool.
As the web server is supposed to be completely stateless, an eventual side effect of a test on another one would mean that there is a bug in the application; so, I would be extremely happy to find it during the tests instead of in production. 
In fact, we have also a set of tests explicitly written to try to identify bad usage of the cache for example.

**Comment by LucioFranco** [comment]
So if you have a global runtime you can just in your tests do

```rust
RT.block_on(async move {
	// test
})
``` 

which is basically what the macro does but because of certain internals block_on takes &mut self, so you will want to do the Handle::current + futures_executor::block_on trick.

Overall, I still suggest spinning up a single connection pool per test anyways, I don't suspect this should be too expensive if you only need say one connection per test?

**Comment by ufoscout** [comment]
@LucioFranco 
thanks! I ended up with something like:
```rust
pub fn test<F: std::future::Future>(f: F) -> F::Output {
    rt().handle().enter(|| futures::executor::block_on(f))
}

#[test]
fn a_test() {
    test(async {
        println!(" this is async");
    });
}
```

Anyway, it would be great to have it on tokio itself so there would be no need for all that boilerplate code and the nested "test()" call.

**Comment by LucioFranco** [comment]
I think we are likely to not support something like that since we generally want to promote the usage of `tokio::test` since in my opinion that is the right way. I am going to close this issue, please re-open if you have any more questions! Hope everything works! :)

**Comment by casey** [comment]
I believe I have run into a scenario where I am truly unable to use a per-test runtime as set up by `#[tokio::test]`.

I am writing a Discord bot. Discord's API is large and complex, so I can't mock it. I also can't run it locally, because it is proprietary. So, my tests must run against the live API.

Let's call the type that represents a session with the Discord API as a `Session`.

Discord rate-limits log in to once every 5 seconds. So I can't create a new `Session` in each test.

I tried to use a global `Session` object, however, I believe that this is problematic because the session will be created in the runtime the `#[tokio::test]`-annotated test that initializes it, and the rest of the tests will be using a `Session` object that has been initialized in a different runtime.

I'm not sure, but I've seen some surprising errors, like [this one](https://github.com/hyperium/hyper/issues/2112), which I believe are being caused by running futures on the wrong runtime.

So, I think I have no choice but to use a global runtime.

I understand the desire to guide users towards `#[tokio::test]`, however, it would be nice to provide a way to use `#[tokio::test]` with a global runtime, when needed. Not being able to use the macro, and having to wrap every test in a helper function, introducing another level of indentation, is less than ideal.

**Comment by casey** [comment]
I ran into another situation where I was forced to use a global runtime for all tests. The tests in question were browser tests, which use the `chromiumoxide` crate to interact with a headless browser. Initializing a browser is slow, so I needed to share a browser instance between all tests. However, the browser instance must run on the same runtime as the test, so I had to remove `#[tokio::test]` and use a shared, global runtime.

Any chance this issue could get a second look? So far, it's been a pretty common (2 for 2) that I've needed to use a global runtime when writing async tests, so I suspect it's common for others. It would be nice if there was an easy way to do this, without needing to use something like `lazy_static` to initialize a global runtime, and doing:

```rust
#[test]
fn test() {
  RUNTIME.block_on(async {
    // test code
  });
}
```

In every test.

**Comment by Darksonn** [comment]
I am open to suggestions for how to achieve a shared runtime.

**Comment by casey** [comment]
How about a `shared_runtime` argument to the `tokio::test` attribute that causes the test to run with a lazily initialized shared runtime:


```
#[tokio::test(shared_runtime)]
async fn test() {
  ...
}
```

**Comment by gwy15** [comment]
I ran into this problem too and created this crate to provide `#[tokio_shared_rt::test]` that acts like `#[tokio::test]` but uses a shared runtime.

https://crates.io/crates/tokio-shared-rt

```rust
#[tokio_shared_rt::test]
async fn t1() {
    db_pool().foo().await;
}
#[tokio_shared_rt::test(shared)]
async fn t2() {
    db_pool().foo().await;
}
#[tokio_shared_rt::test(shared = true)]
async fn t3() {
    db_pool().foo().await;
}
#[tokio_shared_rt::test(shared = false)]
async fn delicate_runtime_test() {
    db_pool().foo().await;
}
```

**Comment by elichai** [comment]
> I am open to suggestions for how to achieve a shared runtime.

I'd love to hear what the problems are preventing just sticking it in a `OnceCell` might be worth it at least for tests. is it because the runtime will never be dropped?

**Comment by txbm** [comment]
I am also facing a recent testing issue that would benefit from Tokio supporting a parameter to enable a shared runtime between tests. I am surprised that this feature has not already been implemented given how commonly it seems to be needed for a variety of use cases.

**Comment by Tockra** [comment]
I ran into a similar issue. 
I want to setup a test-container for the whole test suite. For that I'm using a OnceCell. But the problem here is that the container is never dropped. So everytime I do this, I have a running docker container as left-over:
```rs
static KEYCLOAK: OnceCell<(ContainerAsync<GenericImage>, String)> = OnceCell::const_new();

async fn start_auth_container() -> &'static (ContainerAsync<GenericImage>, String) {
    KEYCLOAK
        .get_or_init(|| async { start_keycloak_container().await })
        .await
}

#[tokio::test]
async fn test1(
) {
    let keycloak = start_auth_container().await;

    println!("{:?}", keycloak.1);
    //let app = start_app("some").await;
}

#[tokio::test]
async fn test2(
) {
    let keycloak = start_auth_container().await;

    println!("{:?}", keycloak.1);
    //let app = start_app("some").await;
}
```

A shared runtime, where I could do some specific clean up call at the end, would be a great solutions and other testing frameworks like junit have such stuff for years...

**Comment by LennDG** [comment]
I have a similar issue to @Tockra .

My application executes HTTP requests to arbitrary servers, and I want to have the tests spinning up their own test server. It looks like this:

```rust

use super::*;
use anyhow::Result;
use tokio::sync::OnceCell;

async fn create_test_server() -> () {
        static INSTANCE: OnceCell<()> = OnceCell::const_new();

        INSTANCE
            .get_or_init(|| async {
                let listener = tokio::net::TcpListener::bind("0.0.0.0:10001")
                    .await
                    .unwrap();

                let app = test_server::create_app();
                tokio::spawn(async move {
                    axum::serve(listener, app).await.unwrap();
                });
            })
            .await;
    }


#[tokio::test]
    async fn test_execute_basic() -> Result<()> {
        create_test_server().await;

        let state = execute(...).await?;
        ...
        Ok(())
    }

async fn test_execute_for_each_simple() -> Result<()> {
        create_test_server().await;

        let state = execute(...).await?;
        ...
        Ok(())
    }

```

Because each test uses a separate runtime, the OnceCell does not prevent creation of multiple servers. This leads to a "AddrInUse" error.

Of course it is possible that I am misunderstanding the issue here. If so, please let me know.

**Comment by Tockra** [comment]
@LennDG I think you create a new INSTANCE each time you call create_test_server().
Try to use it as global variable. Here a small example of my current used mongodb database container:
```rs
use std::env;

use ctor::dtor;
use log::debug;
use mongodb::options::ClientOptions;
use mongodb::{Client, Collection};
use testcontainers::{runners::AsyncRunner, ContainerAsync};
use testcontainers::{ContainerRequest, GenericImage};
use tokio::sync::OnceCell;

static MONGODB: OnceCell<(ContainerAsync<GenericImage>, String)> = OnceCell::const_new();
#[dtor]
unsafe fn shutdown() {
    let container_id = MONGODB.get().map(|c| c.0.id());
    if let Some(container_id) = container_id {
        std::process::Command::new("docker")
            .args(["container", "rm", "-f", container_id])
            .output()
            .expect("failed to stop testcontainer");
        std::process::Command::new("docker")
            .args(["volume", "rm", container_id])
            .output()
            .expect("failed to remove volume");
    }
}

pub async fn get_db_container() -> &'static (ContainerAsync<GenericImage>, String) {
    MONGODB
        .get_or_init(|| async { start_mongodb_container().await })
        .await
}

pub async fn start_mongodb_container() -> (ContainerAsync<GenericImage>, String) {
    let mongodb = get_mongodb_image().start().await.unwrap();

    let is_in_pipeline = env::var("CI").unwrap_or_else(|_| "false".to_string()) == "true";
    let host = if is_in_pipeline {
        format!("{}", mongodb.get_bridge_ip_address().await.unwrap())
    } else {
        format!("{}", mongodb.get_host().await.unwrap())
    };

    let port = if is_in_pipeline {
        27017
    } else {
        mongodb.get_host_port_ipv4(27017).await.unwrap()
    };

    debug!("mongodb started on port {}", port);

    (mongodb, format!("mongodb://{host}:{}", port))
}

fn get_mongodb_image() -> ContainerRequest<GenericImage> {
    let image_name =
        env::var("MONGODB_TEST_IMAGE").unwrap_or_else(|_| "mongodb-test:latest".to_string());
    let parts: Vec<&str> = image_name.split(':').collect();
    let (name, tag) = match parts.as_slice() {
        [name, tag] => (*name, *tag),
        [name] => (*name, "latest"),
        _ => ("mongodb-test", "latest"),
    };

    GenericImage::new(name, tag).into()
}

pub async fn get_mongo_db_collection<T: Send + Sync>(
    db_url: &str,
    database: &str,
    collection: &str,
) -> Collection<T> {
    let mut options = ClientOptions::parse(db_url).await.unwrap();

    options.direct_connection = Some(true);

    let client = Client::with_options(options).unwrap();

    client.database(database).collection(collection)
}

pub async fn get_not_valid_mongo_db_collection<T: Send + Sync>() -> Collection<T> {
    let client = Client::with_uri_str("mongodb://192.168.178.1:27017")
        .await
        .unwrap();
    client.database("not_valid").collection("not_valid")
}
```

**Comment by belchior** [comment]
I think I found a good trade off to fix this issue converting all my tests to run in a single `#[tokio::test]` function, in this approach all tests that depends on database connection must be executed in the same test function, I tested this solution in Postgres and Mongodb and both works well and the tests runs much faster compared to previous alternative based on cascading db references or cloning.

```rust
// src/database/connection.rs

use tokio::sync::OnceCell;

pub async fn get_connection() -> Database {
  static DATABASE: OnceCell<Database> = OnceCell::const_new();

  DATABASE
    .get_or_init(|| async {
      // my connection setup here

      db
    })
    .await
    .clone()
}
```

```rust
// src/all_tests_that_depends_on_db.rs

#[tokio::test]
async fn main() {
  tokio::join!(
    foo_spec::test_1(),
    bar_spec::test_2(),
  );
}

mod foo_spec {
  use crate::database;

  pub async fn test_1() {
    let db = database::get_connection().await;
    // assert something
  }
}

mod bar_spec {
  use crate::database;

  pub async fn test_2() {
    let db = database::get_connection().await;
    // assert something
  }
}
```

You can find the real implementation in [this repository](https://github.com/belchior/rust_web_server/branches/all)
