### ISSUE TITLE
Unicode characters are split when writing to windows terminal

### ISSUE THREAD

**Issue by brunoczim** [tokio-rs/tokio#2380]
## Version

0.2.16

## Platform

Windows

## Description

So, windows stdout as a console only accepts utf-16 characters. Stdlib's stdout detects whether the Stdout is a console in Windows, and then **it assumes the byte buffer is encoded in utf-8 and then converts it to utf-16** so it can be printed. The problem is: Tokio's Stdout seems to split the buffer if it is bigger than `MAX_BUF`, **and the split point might be between multi-byte characters!**

I tried this code:

```rust
use std::str;
use tokio::io::{self, AsyncWriteExt};

const MAX_BUF: usize = 16 * 1024;

#[tokio::main]
async fn main() {
    assert_eq!("█".len(), 3);
    // this will actually have the size MAX_BUF * 3
    // I could only get an error being this big!
    let string = str::repeat("█", MAX_BUF);
    let mut stdout = io::stdout();
    stdout.write_all(string.as_bytes()).await.unwrap();
    stdout.flush().await.unwrap();
}
```

I expected to see this happen: Lots of bars being printed

Instead, this happened: Many of them were printed, but this error happened while printing:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Windows stdio in console mode does not support writing non-UTF-8 byte sequences" }', src\libcore\result.rs:1165:5                       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.                                                                                     error: process didn't exit successfully: `target\debug\teste.exe` (exit code: 101)
```

**Comment by Darksonn** [comment]
What happens if you do the same using the standard library?

**Comment by brunoczim** [comment]
It prints the bar correctly, without any error.

**Comment by Darksonn** [comment]
Hmm, I'm a bit puzzled. Neither Tokio's nor std's stdout type have any special handling for `write_all`, and Tokio's stdout internally just calls the stdout in std. Normally stdout is line buffered by std, which is what avoids breaking up utf-8 in weird places, but it will flush if the line becomes longer than 1024 bytes.

Unless Tokio unnecessarily flushes inside `write_all` (which I can't see anywhere), I don't see how this can be Tokio specific.

Note that I can't test this myself, as I don't have a windows machine.

**Comment by brunoczim** [comment]
Correct me if I'm wrong, but tokio [splits buffers](https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/blocking.rs#L219-L226) if they are bigger than [MAX_BUF](https://github.com/tokio-rs/tokio/blob/master/tokio/src/io/blocking.rs#L29). 

STD's stdout only splits buffer at [unicode boundaries.](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/stdio.rs#L68)
