### ISSUE TITLE
Forwarding input arguments of #[tokio::test] annotated tests

### ISSUE THREAD

**Issue by rubdos** [tokio-rs/tokio#2388]
Test fixture libraries such as [rstest](https://github.com/la10736/rstest) tend to use a proc macro to inject fixtures in tests, *based on function parameters of the test function*. Example:

```rust
#[fixture] fn fix -> u32 {2}
#[rstest] fn foo(fix: u32) { assert_eq!(2, fix) }
```

Currently, there is an [ongoing discussion in `rstest`](https://github.com/la10736/rstest/issues/85) on how to best integrate with test-suites other than the default Rust `#[test]`, in particular those that use `async`, such as `#[tokio::test]`.

In order to transparently integrate and make the `#[rstest]` and `#[tokio::test]` attributes "commutative", the function arguments of a test should simply be forwarded by the `tokio::test` proc macro. [Currently, adding function arguments to a test triggers a custom error](https://github.com/tokio-rs/tokio/blob/de8326a5a490aafdf12848820d1496b758f1ec57/tokio-macros/src/entry.rs#L195). As far as I know, *Rust itself* would generate an error like that, even without that part of code.

This brings me to my main question: dropping that check would allow tighter cooperation with `rstest`, and I believe with other, future fixture frameworks too. Would Tokio accept a patch, dropping that check, like [the one `actix-net` just accepted](https://github.com/actix/actix-net/pull/127)? As far as I can tell, everything else is already in place.

**Comment by hawkw** [comment]
> Would Tokio accept a patch, dropping that check, like [the one `actix-net` just accepted](https://github.com/actix/actix-net/pull/127)? As far as I can tell, everything else is already in place.

I think that would be fine. You're right that if a `#[tokio::test]`-annotated function is used without `#[rstest]` or another attribute that provides arguments, the `#[test]` attribute will generate an error _anyway_, so Tokio doesn't need to have its own error. I'd get input from other Tokio maintainers as well, but this seems reasonable to me.

**Comment by rubdos** [comment]
As discussed in [the issue at `rstest`](https://github.com/la10736/rstest/issues/85#issuecomment-611454811), this is not required for `rstest` to work at all.  It could, however, be useful for different fixture frameworks, and it makes sense IMO to default to the default Rust error either way, instead of making Tokio's own error.
