### ISSUE TITLE
Sink trait for MPSC

### ISSUE THREAD

**Issue by hrvolapeter** [tokio-rs/tokio#2389]
## Version 
0.2.16

## Description
[mpsc/mod.rs](https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/mpsc/mod.rs) in the documentation mentions `Sender` implements `Sink` trait from futures. This seems to be true in the past, but it seems to be removed now.

What's the intent should the `Sink` be implemented, why was it removed? Having Sink trait implemented would certainly simplify some things.

**Comment by Darksonn** [comment]
I believe `Sink` was removed with v0.2 as the trait does not have a clear path into the standard library.

**Comment by hawkw** [comment]
We should probably remove references to it from the docs, then.

**Comment by stsydow** [comment]
Maybe I missed something, but I have no good/elegant idea how to send a Stream into a Sender.
Are there any plans?

There is an implicit example in the docs for Sender.disarm() how to forward every item by foot, but it is really a headache to upgrade form 0.1 now. For the moment I switched to the MPCS channel from the futures crate, but it is quite slow in comparison.

As good future options I could imagine:
- A Sink impl in tokio-util for Sender
- Sender.drain(S: Stream) -> DrainFuture<S>

**Comment by Darksonn** [comment]
You don't need to follow the disarm example if you are in async code. Depending on how you wish to handle failed sends, you can just use a loop like this.
```rust
while let Some(item) = stream.next().await {
    if sender.send(item).is_err() {
        break;
    }
}
```

**Comment by stsydow** [comment]
As I'm writing a library for parallel stream processing,
I would prefer the "old" way of composing stream and sink operators.  
(Maybe I'm to much in the pre async/await style still?)
And only later handing it to the runtime for execution. 
Using the Sink abstraction in my code also allows changing the channel implementation 
later with less effort.
But I understand that Sink is a quite complicated interface you probably want to get around.  

I read your post in some other discussion that one can build it all just using Stream, which I think is true 
but maybe not always convenient.

For tokio I think Sender.drain(stream) could help to keep Streams and channels compatible.
A SinkAdapter in tokio-util could help upgrading code with out reinventing the wheel.
I would be willing to contribute that if there is any interest.

For my code I will probably build a SinkAdapter.
I work on it work my PhD and can provide the library here on github if it is of interest.

**Comment by Darksonn** [comment]
You can find an implementation of `Sink` on [`tokio_util::sync::PollSender`][1].

[1]: https://docs.rs/tokio-util/0.6/tokio_util/sync/struct.PollSender.html

**Comment by BratSinot** [comment]
> You can find an implementation of `Sink` on [`tokio_util::sync::PollSender`](https://docs.rs/tokio-util/0.6/tokio_util/sync/struct.PollSender.html).

Thanks a lot! I was trying to find in `tokio_stream` =)

**Comment by akiradeveloper** [comment]
@BratSinot Are you trying to implement `Sink` for `UnboundedSender`? I found this implementation is missing although the Receiver side has conversion wrapper called `UnboundedReceiverStream`. That's why I've reached here.

**Comment by BratSinot** [comment]
> @BratSinot Are you trying to implement `Sink` for `UnboundedSender`? I found this implementation is missing although the Receiver side has conversion wrapper called `UnboundedReceiverStream`. That's why I've reached here.

Hi.
I just copy-paste `PollSender` and change `Sender` to `UnboundedSender` (and remove some dead code. But now I rewrite my program in different way.

**Comment by Darksonn** [comment]
Making a `Sink` wrapper for `UnboundedSender` would be very easy and much simpler than `PollSender` because the `UnboundedSender::send` method is not async.

**Comment by Adrodoc** [comment]
I would very much like to see a Sink implementation for UnboundedSender as well. In the meantime I will use https://crates.io/crates/sender-sink/0.1.0
