### ISSUE TITLE
Stream::flatten and other Iterator method clones

### ISSUE THREAD

**Issue by sollyucko** [tokio-rs/tokio#2415]
It would be useful to have `Stream::flatten`, which would convert a `Stream<Item = Stream<Item = A>>` to a `Stream<Item = A>`, an analogue of [`Iterator::flatten`](https://doc.rust-lang.org/std/iter/trait.Iterator.html?search=#method.flatten). It would act like `Stream::chain` but for a `Stream` of `Stream`s instead of a pair of `Stream`s.

In general, `Stream` analogues of various `Iterator` methods would be useful, as mentioned in #741.

I could try to implement this and submit a PR, if this sounds useful.

**Comment by Darksonn** [comment]
Until we've decided if this is something we want, you can use futures' [`StreamExt::flatten`][1] method. The main issue with adding more combinators is that they can make previously compiling code break by introducing ambiguity if someone imported both our and futures' `StreamExt` trait.

One option would be to introduce it as a top-level function in the `stream` module similar to e.g. [`iter`][2].

[1]: https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.flatten
[2]: https://docs.rs/tokio/0.2/tokio/stream/fn.iter.html

**Comment by sollyucko** [comment]
Adding extra dependencies isn't really an issue for me, so I'll just use `futures`'s implementation.
