### ISSUE TITLE
Possibly refactor AsyncBufRead

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2428]
In the spirit of [this RFC][1], we should consider refactoring `AsyncBufRead` in a similar way to allow unlimited peeking.

It is worth noting that this removes some types' ability to implement the trait without complicating the types. This is the case for e.g. [`StreamReader`][2]. That said, as is, the trait is more or less only useful for `read_line`, and other single-byte-separated splits.

[1]: https://github.com/rust-lang/rfcs/pull/1015
[2]: https://docs.rs/tokio/0.2/tokio/io/struct.StreamReader.html

**Comment by seanmonstar** [comment]
For 0.3, I'd want to propose just removing the trait, and figuring it out when not under a time crunch.

**Comment by seanmonstar** [comment]
I'm still personally in favor or removing the trait and suggesting people use `LinesCodec` if they want that feature. However, if keeping it, here's a proposal to allow us to punt design:

### Seal `AsyncBufRead`

We could seal the trait, similar to `ToSocketAddrs`. That means all the methods would be "private", and it's only usefulness is possible as bounds, and the extension methods like `lines()`.

**Comment by carllerche** [comment]
I believe that based on #2896, we will need to move `AsyncBufRead` -> `tokio-util`? It probably would be nice to include some note in the Tokio docs pointing to `tokio-util`.

**Comment by carllerche** [comment]
We are going to punt on this for now.
