### ISSUE TITLE
I wonder if there is any atomicity violation in poll_ready

### ISSUE THREAD

**Issue by BurtonQin** [tokio-rs/tokio#2429]
## Version
0.2.18
## Platform
64-bit Windows 10
## Description
By reading the source code, I wonder if there is any atomicity violation in macro `poll_ready` in tokio/src/io/poll_evented.rs

https://github.com/tokio-rs/tokio/blob/43bbbf61a2a87a879834ec644fd4f1c598e77640/tokio/src/io/poll_evented.rs#L125-L160

The above logic can be simplified to
```
1. let mut cached = self.cache.load();
2. ret = F1(cached);
3. Check if ret.is_empty();
4. if not: cached = F2(cached); self.cache.store(cached);
```

If two threads T1&T2 are executing simultaneously:
T1: 1, 2, 3 (if ret.is_empty() is false)
T2: 1, 2, 3, 4 (update self.cache, maybe now ret.is_empty() is true)
T1: 4 (Still consider ret.is_empty() is false and update self.cache accordingly)

The problem is load() and store() are seperated and 
the execution of store() is dependent on load().
Therefore, if load() and store() are interleaved by another store(), a possible atomicity violation happens.

I wonder if this is an issue. If not, how does the code logic avoid it? Thank you.

**Comment by carllerche** [comment]
Probably.... short answer is: don't do it :smile:

There are bigger issues w/ concurrently calling `poll_read_ready` and `poll_write_ready`... they can only remember one waker.

I looked at the fns and was surprised there was no documentation calling this out. Would you mind submitting a PR adding some documentation stating that the caller must ensure that the functions are not being concurrently called?

**Comment by Darksonn** [comment]
Note that for types such as `TcpStream`, this is enforced by the type system by making it impossible to call the functions concurrently due to functions taking `&mut self`. This is why splitting works the way it does.

https://github.com/tokio-rs/tokio/blob/a3aab864d776692bc53357b115c8b06d789c630b/tokio/src/net/tcp/stream.rs#L638-L679

**Comment by BurtonQin** [comment]
The following safe code calls `poll_read_ready()` in two threads and it built successfully.

```Rust
//main.rs
use tokio::io::PollEvented;

use futures::ready;
use mio::Ready;
use mio::net::{TcpStream, TcpListener};
use std::io;
use std::task::{Context, Poll};
use std::net::SocketAddr;
use futures::future::poll_fn;
use std::sync::Arc;
use std::thread;

struct MyListener {
    poll_evented: PollEvented<TcpListener>,
}

impl MyListener {
    pub fn poll_accept(&self, cx: &mut Context<'_>) -> Poll<Result<TcpStream, io::Error>> {
        
        let ready = Ready::readable();

        ready!(self.poll_evented.poll_read_ready(cx, ready))?;  
        // poll_read_ready() should not be called in two threads, but there is no guarantee!

        match self.poll_evented.get_ref().accept() {
            Ok((socket, _)) => Poll::Ready(Ok(socket)),
            Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                self.poll_evented.clear_read_ready(cx, ready)?;
                Poll::Pending
            }
            Err(e) => Poll::Ready(Err(e)),
        }
    }
}

async fn foo() {
    let addr = "127.0.0.1:8000".parse::<SocketAddr>().unwrap();
    let listener1= Arc::new(MyListener {
        poll_evented: PollEvented::new(TcpListener::bind(&addr).unwrap()).unwrap(),
    });

    let listener2 = Arc::clone(&listener1);

    poll_fn(|cx| listener1.poll_accept(cx)).await;  // poll_read_ready() called in thread 1.

    let a = thread::spawn(move ||
        poll_fn(move |cx| listener2.poll_accept(cx))  // poll_read_ready() called in thread 2.
    );
    a.join();
}

fn main() {
    foo();
}
```

```
//Cargo.toml
[dependencies]
tokio = { version = "0.2.18", features = ["io-driver"] }
mio = "0.6.10"
futures = "0.3.4"
```

**Comment by Darksonn** [comment]
Calling it concurrently will mess up mio's internal state, but it shouldn't cause UB. My previous comment on `TcpStream` was regarding the `tokio::net::TcpStream` type, not the `PollEvented<std::net::TcpStream>` type, which doesn't have these safeguards.

**Comment by BurtonQin** [comment]
When the safety of a function depends on its caller, it does not seem that safe.
I think a document is good for now.
In the future, perhaps we should try to change the function interfaces (to &mut self?) so that the compiler can prevent the developers from concurrently calling them.

**Comment by carllerche** [comment]
Safety means something very specific in Rust.

That said, I think the fact that the concern leaked out is not ideal. Fixing it requires a breaking change though, so until 0.3, docs is the best we can do.
