### ISSUE TITLE
subtraction overflow in tokio-threadpool

### ISSUE THREAD

**Issue by srijs** [tokio-rs/tokio#244]
On current master, there seems to be a race condition in tokio-threadpool where occasionally I run into a subtraction overflow when logging the number of workers (https://github.com/tokio-rs/tokio/blob/master/tokio-threadpool/src/lib.rs#L1089).

```
thread panicked at 'attempt to subtract with overflow', /Users/srijs/.cargo/git/checkouts/tokio-377c595163f99a10/7b1306e/tokio-threadpool/src/
lib.rs:1089:53
```

Maybe the atomic ordering is not strict enough?

**Comment by carllerche** [comment]
Thanks for the report. I've been working out some bugs, though I am not sure if it is related.

Work is here: https://github.com/tokio-rs/tokio/pull/243. Maybe you can see if the bug happens on that branch?

**Comment by carllerche** [comment]
@kamyuentse Is this w/ futures2 enabled or not?

**Comment by kamyuentse** [comment]
@carllerche  Without the feature `futures2`, this issue happened randomly when I debug the `hyper:unfutures-02`, there is a test (`conn_drop_prevents_pool_checkout`) fails before, but sean remove it and merge the PR.

Log
```
... Drop the worker inside Runtime::threadpool

 TRACE tokio_threadpool::pool     > worker_terminated; num_workers=0
 TRACE tokio_threadpool::pool     > notifying shutdown task
 TRACE tokio_threadpool::shutdown > Shutdown::poll
 TRACE tokio_reactor              > event Readable Token(4194303)
 DEBUG tokio_reactor              > loop process - 1 events, 0.000s
 DEBUG tokio_reactor::background  > shutting background reactor down NOW
 TRACE tokio_threadpool::notifier > Notifier::notify; id=0x10f81f130
 TRACE tokio_threadpool::pool     >   -> submitting to random; idx=4
 ^
 |--- Test will be passed when this line not appears,
        or spawn a new worker for this task before reactor has shut down.
for example (
 TRACE tokio_threadpool::pool     >   -> submitting to random; idx=4
 TRACE tokio_threadpool::worker   > spawning new worker thread; id=4
 DEBUG tokio_reactor::background  > background reactor has shutdown
 TRACE tokio_threadpool::worker   > shutting down thread; idx=4
 TRACE tokio_threadpool::worker   > found work while draining; signal_work
thread 'tokio-runtime-worker-4' panicked at 'attempt to subtract with overflow', /Users/kam/.cargo/git/checkouts/tokio-377c595163f99a10/dbcd835/tokio-threadpool/src/pool/mod.rs:172:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
)
 DEBUG tokio_reactor::background  > background reactor has shutdown
```

| Submit task before the reactor shutdown | Spawn a new worker | Overflow panic | Test pass |
| --| - | -|  - |
| Y | Y | Y | Y |
| Y | N | N | N |
| N | N | N | Y |

I hope this information is helpful.

**Comment by carllerche** [comment]
Ok, thanks. Do you have steps to repro the issue?

**Comment by kamyuentse** [comment]
@carllerche  Enable `RUST_LOG=trace` then run that test case several times, I think this issue will arise. But I am not trying to write a minimal test case without the hyper.

**Comment by carllerche** [comment]
@kamalmarhubi Which hyper branch? Master?

**Comment by kamalmarhubi** [comment]
@kamyuentse I think you were the intended target of a notification :-)

**Comment by carllerche** [comment]
I'm reopening this until I can investigate the issue described above.

**Comment by carllerche** [comment]
#317 changes all the logic around where the panic occurs. I'm going to wait to see if the issue happens once that work lands.

**Comment by carllerche** [comment]
@kamyuentse I'm not seeing this issue happen w/ the latest changes on master (#317). Are you able to confirm this?

**Comment by kamyuentse** [comment]
@carllerche Sorry for the delay, I was out last week. I checked and not seeing this issue happen. Thanks for your great work!

**Comment by carllerche** [comment]
@kamyuentse Great! Thanks for verifying 👍
