### ISSUE TITLE
Crossbeam Unbounded Channel Sender in Tokio Task?

### ISSUE THREAD

**Issue by depombo** [tokio-rs/tokio#2447]
Is there any performance penalty from using a Crossbeam unbounded channel `Sender` in a Tokio task instead of the Tokio unbounded channel `Sender`? I already use an unbounded crossbeam channel in a basic (or single-threaded) Tokio runtime to communicate with a Rayon cpu thread pool and I would like to reuse it, if possible. I will only use `try_recv`, and never `recv`, for either within the Tokio runtime. 

I ask because the Tokio and Crossbeam unbounded channel `Sender`s both block, but return immediately so it’s not clear to me what the performance difference, if any, would be for my specific use case.

Thanks!

**Comment by Matthias247** [comment]
As long as you don't block on inside a tokio task (e.g. by writing to a bounded blocking channel or receiving from a blocking channel) every channel type is ok. Crossbeam included.

**Comment by Darksonn** [comment]
It seems like this has been answered, so I am closing it. If you have further questions, feel free to reopen or just post them below.

**Comment by let4be** [comment]
> As long as you don't block on inside a tokio task (e.g. by writing to a bounded blocking channel or receiving from a blocking channel) every channel type is ok. Crossbeam included.
Is it though? If there is no data in the channel it will block whole thread indefinitely instead of yielding control back to tokio scheduler...

**Comment by Darksonn** [comment]
> If there is no data in the channel it will block whole OS thread indefinitely

This would block the thread. Matthias said "as long as you don't block".

> I just wanna write software using green threads and it seems to be incredibly difficult to achieve in modern rust because of lack of docs and endless zoo of libraries with unknown interactions

Here are some resources:

 * [Async: What is blocking?](https://ryhl.io/blog/async-what-is-blocking/)
 * [Channels chapter in Tokio tutorial](https://tokio.rs/tokio/tutorial/channels)

Generally when it comes to channels, the ones built in to Tokio can do almost everything you might want to do. They are found in various modules of `tokio::sync`. This thread just answers whether crossbeam is wrong to use, which it _sometimes_ is and _sometimes_ isn't.

If you want guidance on other things but channels, open a [discussion][1], or ask on our [Discord server][2]. You can also ask on the [user's forum][3].

[1]: https://github.com/tokio-rs/tokio/discussions
[2]: https://discord.gg/tokio
[3]: https://users.rust-lang.org/
