### ISSUE TITLE
0.2.17 regresssion: Core threads number cannot be above max limit

### ISSUE THREAD

**Issue by kornelski** [tokio-rs/tokio#2452]
I have a 12-core machine. In 0.2.16 this code runs fine:

```rust

    let rt = tokio::runtime::Builder::new()
        .threaded_scheduler()
        .max_threads(8)
        .build()
        .unwrap();
```

In 0.2.17 and later it fails with:

> 'Core threads number cannot be above max limit' in src/runtime/builder.rs:467:13

The assertion fails, because tokio now decides to use 12 core_threads, which became higher than my max of 8.

**Comment by carllerche** [comment]
Whoops, sorry about that. I will work on getting a fix out tomorrow.

We are going to need more tests there as well.

**Comment by carllerche** [comment]
This PR should fix it: https://github.com/tokio-rs/tokio/pull/2457

If you have a moment, I would appreciate confirmation.

**Comment by kornelski** [comment]
PR looks good to me.
