### ISSUE TITLE
Missing doc. No found SO_REUSEADDR solution for TcpListener

### ISSUE THREAD

**Issue by heretic13** [tokio-rs/tokio#2453]
Hello.

Tokio version: 0.2.19
Documentation - https://docs.rs/tokio/0.2.19/tokio/net/struct.TcpListener.html

I do not see information about the SO_REUSEADDR option.
Can i think that function
impl TcpListener
pub async fn bind <A: ToSocketAddrs> (addr: A) -> Result <TcpListener>
automatically sets this option?

The SO_REUSEADDR option is the basis of TCP servers; no industrial server can work without it. The lack of intelligible documentation is a big minus for the library.
The lack of support for the SO_REUSEADDR option is an even bigger minus.

**Comment by Darksonn** [comment]
Tokio's tcp api is based on the standard library, and [`std::net::TcpListener`][2] does not talk about `SO_REUSEADDR` either. The current behaviour is to always set `SO_REUSEADDR` when binding a listener, as Tokio internally uses the v0.6 version of the `mio` crate, whose `TcpListener` documentation you can find [here][4].

If you wish to configure the socket beyond what Tokio allows you to, the current solution is to use the [`socket2`][3] crate to configure it, and then convert it to a Tokio tcp stream. Take a look at my answer to [this SO question][1], which describes how to do this:
```rust
async fn connect_bind(bind: SockAddr, connect: SockAddr) -> Result<TcpStream> {
    spawn_blocking(move || {
        let socket = Socket::new(Domain::ipv4(), Type::stream(), None)?;
        socket.bind(&bind)?;
        socket.connect(&connect)?;
        TcpStream::from_std(socket.into_tcp_stream())
    }).await?
}
```
We are interested in providing a `TcpSocket` api or something like that, which would allow additional configuration, but the standard library provides no such api, and we have not yet taken the time to design it.

[1]: https://stackoverflow.com/questions/59298027/how-to-bind-on-tcp-client-side-in-rust-tokio/59916539
[2]: https://doc.rust-lang.org/stable/std/net/struct.TcpListener.html
[3]: https://docs.rs/socket2
[4]: https://docs.rs/mio/0.6/mio/net/struct.TcpListener.html#method.bind

**Comment by heretic13** [comment]
Good. But what about writing in your documentation that the option is set to true so that people don’t ask unnecessary questions and do not waste time researching. I think I’m not the only one who has addressed such a question and will continue to asking.

**Comment by Darksonn** [comment]
I agree that it should be added to the documentation.

I am not aware of anyone having asked the question before, and a large number of our documentation changes are indeed based on questions we receive. Of course, it is possible that someone was looking for the information, found it elsewhere, and then didn't tell us.
