### ISSUE TITLE
Add map method to MutexGuard, RwLockReadGuard, RwLockWriteGuard

### ISSUE THREAD

**Issue by sunjay** [tokio-rs/tokio#2471]
Thanks for such an excellent crate! I'm really enjoying using it and it's very well documented. :smile: 

## Version

`tokio v0.2.20`

## Description

The [`parking_lot` crate](https://docs.rs/parking_lot) provides a `map` method on `MutexGuard`, `RwLockReadGuard`, `RwLockWriteGuard` that is very convenient when you need to return some part of a locked value. For example, this can be used to implement a method that return a reference to a single field of a value that you previously locked.

* [`MutexGuard::map`](https://docs.rs/lock_api/0.3.4/lock_api/struct.MutexGuard.html#method.map)
* [`RwLockReadGuard::map`](https://docs.rs/lock_api/0.3.4/lock_api/struct.RwLockReadGuard.html#method.map)
* [`RwLockWriteGuard::map`](https://docs.rs/lock_api/0.3.4/lock_api/struct.RwLockWriteGuard.html#method.map)

Would it be possible for tokio to add these methods to its lock guards? Are there any major complications that could be encountered due to async or because of the mutex implementation?

I'd be willing to work on this if no one else is available. (Though I would not object if someone else is willing to take this on.)

**Comment by hawkw** [comment]
You may be happy to learn that there's already [a PR open](https://github.com/tokio-rs/tokio/pull/2445) to add `map` methods to the `RwLock` guards!

**Comment by sunjay** [comment]
@hawkw This is great! I'm going to get started on a PR for adding `map` to `MutexGuard`. :tada:
