### ISSUE TITLE
tokio-timer: Wheel panicked at 'elapsed=7481664; when=7481664'

### ISSUE THREAD

**Issue by paulhauner** [tokio-rs/tokio#2473]
## Version

tokio-timer = "0.2.12"
tokio = "0.1.22"

## Platform

Linux xxxx 5.6.5-arch3-1 1 SMP PREEMPT Sun, 19 Apr 2020 13:14:25 +0000 x86_64 GNU/Linux

## Description

Originally observed in [this issue](https://github.com/sigp/lighthouse/issues/1067), we're experiencing a panic when using `tokio-timer::DelayQueue`:

```
thread 'tokio-runtime-worker-6' panicked at 'elapsed=5186752; when=5186752', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/wheel/mod.rs:244:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: tokio_timer::wheel::level_for
  14: tokio_timer::wheel::Wheel<T>::remove
  15: tokio_timer::delay_queue::DelayQueue<T>::reset
  16: hashmap_delay::hashset_delay::HashSetDelay<K>::insert
  17: eth2_libp2p::peer_manager::PeerManager<TSpec>::ping_request
  18: <eth2_libp2p::behaviour::Behaviour<TSubstream,TSpec> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  19: <libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo> as futures::stream::Stream>::poll
  20: <eth2_libp2p::service::Service<TSpec> as futures::stream::Stream>::poll
  21: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  25: tokio_threadpool::task::Task::run
  26: tokio_threadpool::worker::Worker::run_task
  27: tokio_threadpool::worker::Worker::run
  28: tokio_timer::clock::clock::with_default
  29: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  30: std::thread::local::LocalKey<T>::with
  31: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The panic caused when `elapsed == when` in [`wheel::level_for`](https://github.com/tokio-rs/tokio/blob/97565c0e7565c2d260bf5ce3102a4034fdd9652b/tokio-timer/src/wheel/mod.rs#L241-L249).

Let's look at how these variables are set:

- `elapsed`: via [`Wheel::poll`](https://github.com/tokio-rs/tokio/blob/97565c0e7565c2d260bf5ce3102a4034fdd9652b/tokio-timer/src/wheel/mod.rs#L139-L167).
- `when`: when called via `Wheel::remove` (see backtrace) it is set [from the store](https://github.com/tokio-rs/tokio/blob/97565c0e7565c2d260bf5ce3102a4034fdd9652b/tokio-timer/src/wheel/mod.rs#L128).

Here's a scenario where I _think_ we can trigger it:

- There are `n > 1` items ready to be expired, where `item.when` is equivalent for all `n`.
- `Wheel:poll` is called once and a single item (`n[0]`) is expired.
  - As a side-effect, `self.elapsed` is set to `item.deadline` which _I think_ [can equal `item.when`](https://github.com/tokio-rs/tokio/blob/97565c0e7565c2d260bf5ce3102a4034fdd9652b/tokio-timer/src/wheel/level.rs#L143) (haven't got too deep into `Wheel`, could be wrong).
- `Wheel::remove` is called for item `n[1]`.
  - `wheel::level_for` is called with `self.elapsed` and `item.when` which are equal (if my previous assumption was correct).
  - Panic.

As a heuristic, I noticed that `Wheel::insert` [is guarded](https://github.com/tokio-rs/tokio/blob/97565c0e7565c2d260bf5ce3102a4034fdd9652b/tokio-timer/src/wheel/mod.rs#L105) against `elapsed == when` whilst `Wheel::remove` isn't. This _feels_ like a bug to me but it's a big assumption.

P.S thanks for maintaining tokio, great library :)

**Comment by fegies** [comment]
Here is a Rust Playground (with tokio 0.2.21 at the point of writing.)

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=70c733471acfe840dd80a4fa82ce3b26

I dont know exactly if it is the same behavior as experienced by the case above, but explicitly setting trying to set a timeout to an instant in the past and then trying to remove/reset it cause a panic with exactly the same stack trace.
