### ISSUE TITLE
Make codec more discoverable

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2475]
The codec module in tokio-util is currently not as discoverable as I would like. Even when people see the `tokio-util` crate, I often see people get confused and think its some multi-media thing.

One thing that needs to be improved in particular is the top-level module description, which currently is

> Utilities for encoding and decoding frames.

This should be improve to something that makes it clear that this is about streams and sinks, and splitting things into multiple messages.

Ideas for additional ways of making it discoverable are very welcome!

**Comment by nickkuk** [comment]
The codec module easily solves a frequently demanded task ([1](https://github.com/hyperium/hyper/issues/2166), [2](https://github.com/hyperium/hyper/issues/2176), [3](https://github.com/seanmonstar/reqwest/issues/879)) of converting `AsyncRead` to `Stream`. Maybe we should write about it?

Recently I've added new examples to [hyper](https://github.com/hyperium/hyper/pull/2193) and [reqwest](https://github.com/seanmonstar/reqwest/pull/888).
