### ISSUE TITLE
Add join_all function for waiting on an iterator of futures

### ISSUE THREAD

**Issue by sunjay** [tokio-rs/tokio#2478]
The `futures` crate provides [`futures::future::join_all`](https://docs.rs/futures/0.3.4/futures/future/fn.join_all.html) which allows you to take an iterator of futures and get a `Vec<T>` with the results of polling all of them. @carllerche indicated [on Discord](https://discordapp.com/channels/500028886025895936/500336333500448798/706284140764463115) that it would be desirable to add this to `tokio`. This issue tracks the work on that.

I am willing to work on this, but I am still new to `tokio` (and async in general), so I will need some guidance to get started. In particular, it looks like we won't be starting by just copying `JoinAll` from the `futures` crate. @carllerche has some ideas which they will hopefully share in a comment below. :)

**Comment by Darksonn** [comment]
In my opinion we would also want a `FuturesUnordered` and `select_all`. The implementation of `join_all` in futures scales very poorly with the number of items, and I would like to have ours switch to `FuturesUnordered` if there are many futures.

**Comment by sunjay** [comment]
> The implementation of `join_all` in futures scales very poorly with the number of items, and I would like to have ours switch to `FuturesUnordered` if there are many futures.

Maybe we could have two versions then? Ordering is still useful in certain contexts, even if synchronization or whatever makes it slower in certain contexts. We could follow the standard library convention and name them `join_all` and `join_all_unstable` or we could stick with "unordered" and call it `join_all_unordered`. If you think unordered should be the default, we could also have `join_all_ordered` instead. 

From an API point of view, I also think we should consider adding all of these as methods on an extension trait. That way someone can use `join_all` as a normal part of their method chain. For example, with a `Vec<Mutex<T>>` this would look like `v.iter().map(|mutex| mutex.lock()).join_all()`.

**Comment by Darksonn** [comment]
We can definitely use `FuturesUnordered` internally and still make the output ordered. That's not an issue. It's more about making the implementation efficient. Note that your iterator thing is very similar to [`buffer_unordered`][1].

[1]: https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.buffer_unordered

**Comment by surechen** [comment]
> We can definitely use `FuturesUnordered` internally and still make the output ordered. That's not an issue. It's more about making the implementation efficient. Note that your iterator thing is very similar to [`buffer_unordered`](https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.buffer_unordered).

Hello, Darksonn. is this work still in progress? In futures-rs/futures-util/stream, in addition to futures_unordered, it also has futures_ordered, is it more suitable for join_all? Does this mean that futures_ordered or futures_unordered needs to be added to the crate tokio-stream before the join_all method is added in the crate tokio? futures-rs/futures-util/stream contains more methods than tokio-stream, for example split and peek, will these methods be added to tokio-stream?

**Comment by Darksonn** [comment]
No, we are not currently working on this. For now, if the [`tokio::join!`][4], [`tokio::try_join!`][5] or [`tokio::select!`][6] macros do not fit your running-things-concurrently use case, I recommend using [`buffer_unordered`][1], [`buffered`][2] or [`FuturesUnordered`][3] from the futures crate.

I have removed some of the tags from this issue, as with the split of streams out from the main Tokio crate, the design of this feature would need to be discussed in more detail before implementation.

[1]: https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.buffer_unordered
[2]: https://docs.rs/futures/0.3/futures/stream/trait.StreamExt.html#method.buffered
[3]: https://docs.rs/futures/0.3/futures/stream/struct.FuturesUnordered.html
[4]: https://docs.rs/tokio/1/tokio/macro.join.html
[5]: https://docs.rs/tokio/1/tokio/macro.try_join.html
[6]: https://docs.rs/tokio/1/tokio/macro.select.html

**Comment by Darksonn** [comment]
I'm going to close this. There are lots of ways of doing it. You may use the things from the previous list, and there is also [`JoinSet`](https://docs.rs/tokio/latest/tokio/task/struct.JoinSet.html) now.
