### ISSUE TITLE
Deprecate and prune `tokio-tls`

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#2483]
Now that we have https://github.com/tokio-rs/tls for all our tokio based tls crates we should deprecate `tokio-tls` in favor of `tokio-native-tls`.

- [x] publish deprecation
- [x] upgrade dependent crates
- [x] prune `tokio-tls` from master

**Comment by LucioFranco** [comment]
https://github.com/hyperium/hyper-tls/pull/65

**Comment by Darksonn** [comment]
What is the status on this?

**Comment by LucioFranco** [comment]
All is done!
