### ISSUE TITLE
Inconsistent doc re: BufWriter behaviour on drop

### ISSUE THREAD

**Issue by artempyanykh** [tokio-rs/tokio#2484]
## Version

0.2.13

## Description

1. [Here](https://docs.rs/tokio/0.2.20/tokio/io/index.html#buffered-readers-and-writers) 2nd code snippet on `BufWriter` says that:

> // the buffer is flushed once writer goes out of scope

2. However, [here](https://docs.rs/tokio/0.2.20/tokio/io/struct.BufWriter.html) the doc says:

> When the BufWriter is dropped, the contents of its buffer will be discarded. Creating multiple instances of a BufWriter on the same stream can cause data loss. If you need to write out the contents of its buffer, you must manually call flush before the writer is dropped.

Given that I just got bitten by a missing `shutdown` on `BufWriter`, I'm guess the 2nd doc is actually correct, but wanted to double check. If so, I can adjust the doc in the code snippet in 1.

**Comment by Darksonn** [comment]
Ah yeah, that should be fixed. It doesn't buffer on drop because that's impossible.
