### ISSUE TITLE
TCP Server - Bug?

### ISSUE THREAD

**Issue by hanusek** [tokio-rs/tokio#2492]
## Version
Tokio 0.1.22

## Platform
Ubuntu Linux 18.04 LTS x86_64

## Description

I tried write TCP server - https://github.com/hanusek/tokio-tcp-server.

I expected to see this happen: The TCP Server receives 12 bytes of data each time.

Instead, this happened: 
Every now and then an error occurs - the received data frame is not complete.

## Listing
```
TCP Server
listening...TcpListener { addr: V4(0.0.0.0:502), fd: 3 }
Conected: 127.0.0.1:51086
2020-05-05 22:20:48.239102348 +02:00 Error: Len is Incorrect
Conected: 127.0.0.1:51122
2020-05-05 22:21:30.520593395 +02:00 Error: Len is Incorrect
Conected: 127.0.0.1:51140
2020-05-05 22:22:12.757771345 +02:00 Error: Len is Incorrect
Conected: 127.0.0.1:51144
2020-05-05 22:22:55.021565442 +02:00 Error: Len is Incorrect
Conected: 127.0.0.1:51150
2020-05-05 22:23:37.282017740 +02:00 Error: Len is Incorrect
Conected: 127.0.0.1:51156
```

## Forum 
https://users.rust-lang.org/t/tokio-net-mio-net-and-tcp-header/41879

**Comment by Matthias247** [comment]
That's not a bug. It's a misunderstanding of TCP. TCP offers a byte streaming, not packet transmission. There are no frame/packet/etc boundaries. Each intermediary (e.g. the Kernels send and receive buffers) are free to change frame boundaries as long as the overall data-stream stays intact.

If you need packet boundaries, you need to define an application protocol on top of TCP.
