### ISSUE TITLE
Add interval example to time module

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2494]
It is rather common to see people wanting to run something every so often. I would like the time module to have an example of this.

**Comment by siyopao** [comment]
Is an example like this what you had in mind?
```
```

**Comment by Darksonn** [comment]
I would like to use the [`interval`][1] function. Perhaps something like [this][2]? It would be nice if it also includes an explanation of the difference between using `interval` vs using `delay_for` for this.

[1]: https://docs.rs/tokio/0.2/tokio/time/fn.interval.html
[2]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94d2099c1d76f763ed7cee3610d82570

**Comment by siyopao** [comment]
I am not entirely sure that I understand myself, but is only difference that the first `tick` will complete immediately? From the docs it seems that `interval` will yield, but `delay_for` will block, but I am not entirely sure that this is the case. How about using them both in an [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bdac57ed8be531204735291c56129c93) and adding some explanation?

Thank you for your help.

**Comment by Darksonn** [comment]
Imagine if the `println!` took half a second to complete. Then the `delay_for` version would run the `println` every 1.5 seconds, whereas using `interval` would run it once every second.

**Comment by siyopao** [comment]
Ah, thank you, your explanation was very clear. Can we use it as in [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8a09464db48dcd304ab721a7931b734b), and perhaps add that if we replaced `interval` with `delay_for` each loop would take three seconds?

**Comment by Darksonn** [comment]
That sounds reasonable! Grammarwise I'd prefer `task_that_takes_a_second` instead.

**Comment by siyopao** [comment]
Thank you. It seems I have a terrible imagination when it comes to function names so I simply used your suggestion. How does the following look?
```
```

**Comment by Darksonn** [comment]
It would be something like that, yes!

**Comment by siyopao** [comment]
Great! Thanks for you help. So, silly question, where to put this example? In the `examples` directory as `interval.rs` maybe?

**Comment by Darksonn** [comment]
It should go on the module documentation for the `time` module, which you can find [here][1]. It would also be good to have the same example on the documentation for the `interval` function, which you can find [here][2]. The `delay_for` function could also use an example [here][3].

[1]: https://github.com/tokio-rs/tokio/blob/master/tokio/src/time/mod.rs#L1-L60
[2]: https://github.com/tokio-rs/tokio/blob/master/tokio/src/time/interval.rs#L8-L35
[3]: https://github.com/tokio-rs/tokio/blob/master/tokio/src/time/delay.rs#L23-L39

**Comment by siyopao** [comment]
Cool. Thanks. I'll try to get around to it very soon.
