### ISSUE TITLE
tokio::time does not use mio::timer?

### ISSUE THREAD

**Issue by Mygod** [tokio-rs/tokio#2508]
Is this something you are looking into implement?

**Comment by carllerche** [comment]
Thanks for the offer. The mio timer has been deprecated. Tokio is able to provide better timing logic than mio.

**Comment by Mygod** [comment]
Thank you for your response! Could you point me to the better timing logic currently? (trying to read the source code)

**Comment by carllerche** [comment]
The general idea is to use the `epoll_wait` timeout argument paired with a hashed timing wheel. The implementation is in [here](https://github.com/tokio-rs/tokio/tree/master/tokio/src/time/driver).

**Comment by Mygod** [comment]
Ah found it. I was deceived by the simplistic looking of [timeout.rs](https://github.com/tokio-rs/tokio/blob/f9ddb93604a830d106475bd4c4cae436fafcc0da/tokio/src/time/timeout.rs). It turns out the magic is at `delay_until`.
