### ISSUE TITLE
Futures 0.2 integration issues

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#251]
This is a tracking issue for issues w/ the futures 0.2 integration:

* The sub dependencies aren't all correct. For example, when the `futures2` feature is enabled for `tokio-reactor`, it does not enable it for `tokio-executor`.
* [This](https://github.com/tokio-rs/tokio/blob/master/tokio-threadpool/tests/threadpool.rs#L553) test needs to be updated.
* #248 seems to be caused by the futures 0.2 integration. @seanmonstar posted #254 but it needs review.
* Re-enable tests disabled by #259.
* StableFuture

cc/ @aturon

**Comment by kpp** [comment]
+ Remove `tokio-io/src/[read/read_exact...]` in favour of https://github.com/rust-lang-nursery/futures-rs/tree/master/futures-util/src/io

**Comment by carllerche** [comment]
I also don't think that the `futures2` crate is needed. Instead, Tokio can depend on the sub crates instead of the facade. This is probably going to be better practice anyway.

**Comment by carllerche** [comment]
I'm going to close this as it does not seem like Tokio will support futures 0.2. The feature flag has been removed and futures 0.3 is also being worked on.
