### ISSUE TITLE
Introspection of current running/idle threads and total spawned tasks

### ISSUE THREAD

**Issue by Kixiron** [tokio-rs/tokio#2510]
Allowing library users to see these kinds of stats would help tons, especially with critical applications who need to see detailed resource usages due to constrained environments

**Comment by carllerche** [comment]
The intent is to use the tracing crate to expose these metrics. It is just blocked on implementation :-)

**Comment by Kixiron** [comment]
For people who don't want to rely on the tracing crate, could a mechanism to get these statistics be part of tokio itself?

**Comment by carllerche** [comment]
`tracing` is mostly a method by which data can be exported. It has all the necessary infrastructure needed to opt-in at multiple levels (instrumentation, callsites, ...).

Additionally, `tracing` is also part of the greater Tokio stack.

Is there a reason why you don't want to rely on it?

**Comment by Kixiron** [comment]
Added complexity and added dependencies mostly (although if it’s already in the stack that’s not as much of an issue I guess), plus we already use a full-blown service for reporting statistics and it’d be nice to be able to easily integrate tokio metrics into that without adding any extra layers of complexity

**Comment by carllerche** [comment]
We can add a default aggregator that provides accessors for key metrics. It would be built on top of `tracing-core` though. This dep is designed to be as light / minimal as possible. Most of `tracing` is opt-in.

**Comment by Kixiron** [comment]
That's be perfect, thank you!

**Comment by ptescher** [comment]
Was debugging an issue that could really use this. Tracing is great but currently relies on all libraries to support it. Seems like https://github.com/tokio-rs/tokio/issues/1186 would get this done, is it still relevant and being worked on?

**Comment by hawkw** [comment]
@ptescher sorry, I've been busy with other things, but I'd really like to wrap that up. I'll give it some time today to see how much of the preliminary work on this can be brought back.

**Comment by ptescher** [comment]
@hawkw down to help out too, would be super useful for our stack.

**Comment by hawkw** [comment]
@ptescher you may be happy to note that #2655 adds a `tracing` span to every spawned task (when the `tracing` feature is enabled). The next steps will involve actually consuming those spans to generate tokio-specific data.

**Comment by Darksonn** [comment]
This is: https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html
