### ISSUE TITLE
Semaphore: cannot add more than MAX_PERMITS permits

### ISSUE THREAD

**Issue by vojtechkral** [tokio-rs/tokio#2514]
## Version

0.2.20

## Platform

`Linux 5.6.3-arch1-1 #1 SMP PREEMPT Wed, 08 Apr 2020 07:47:16 +0000 x86_64 GNU/Linux`

## Description

I tried to `add_permits(std::usize::MAX)` but got a panic:

    cannot add more than MAX_PERMITS permits (2305843009213693951)

It seems the `MAX_PERMITS` const should probably be exposed or at least it should be mentioned in the docs that you can't add `std::usize::MAX` permits...

**Comment by Darksonn** [comment]
Documenting the upper limit sounds like a good idea.

**Comment by vojtechkral** [comment]
Ok. Btw. the reason I ran into this is I was trying to get a wake-all-waiting sync primitive, it seems `Notify` can't do that. I'm not sure I'm doing this right. Is there a better way to get wake-all-waiting?

**Comment by Darksonn** [comment]
Sounds like the [`watch`][1] channel can do that?

[1]: https://docs.rs/tokio/0.2/tokio/sync/watch/index.html

**Comment by vojtechkral** [comment]
Ah, of course, can't believe I forgot about `watch`, thanks!

**Comment by NOVA-ME** [comment]
Can I work on this.I'll give a pr later.And how about change it like this.
```rust
    /// Adds `n` new permits to the semaphore.
    /// `n` must less than ```MAX_PERMITS```
    /// [`MAX_PERMITS`]: crate::sync::Semaphore::MAX_PERMITS
    pub fn add_permits(&self, n: usize) {
        self.ll_sem.release(n);
    }
```

**Comment by Darksonn** [comment]
@NOVA-ME Sure, go ahead and submit a PR! For some general advice regarding the formatting, you need an empty line to introduce a line break, and you generally should not start a sentence with code. Similarly link locations should have an empty line around them.

We can discuss additional formatting questions on the PR. Note that when compiling the documentation to check how it looks, you need a special command as described in [`CONTRIBUTING.md`][1].

[1]: https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md#cargo-commands

**Comment by NOVA-ME** [comment]
I have send a pr #2539
