### ISSUE TITLE
Panic: "unexpected task state; Idle"

### ISSUE THREAD

**Issue by kamyuentse** [tokio-rs/tokio#253]

**Comment by carllerche** [comment]
Thanks for the report. Do you have more context / repro?

**Comment by kamyuentse** [comment]
@carllerche  Happened when I test hyper, similar to #248 ?

**Comment by carllerche** [comment]
With "latest hyper" do you mean when using the unstable-futures feature flag?

**Comment by kamyuentse** [comment]
@carllerche Yes, with "unstable-futures" feature, is that a integrate issue? Or the`tokio` has race condition?

**Comment by carllerche** [comment]
Ok, then this is most likely the same as #248 and the fix would be #254.

I'm going to close this as a dup.
