### ISSUE TITLE
The broadcast channel receiver sometimes panics while dropping with the message "unexpected empty broadcast channel"

### ISSUE THREAD

**Issue by 42triangles** [tokio-rs/tokio#2533]
## Version
`tokio v0.2.20`, `tokio-macros v0.2.5`

## Platform

`Linux pa-player 4.19.115-v7 #1 SMP Thu Apr 16 13:53:57 UTC 2020 armv7l GNU/Linux` (using the Yocto Project)

## Description

This happened in a relatively large codebase, so it's rather hard to try to isolate what exactly contributes to this behaviour, and as such, I sadly do not have a minimal example for when this happens.

Specifically, the `panic!("unexpected empty broadcast channel")` at `src/sync/broadcast.rs:957` (the `Drop` implementation for `Receiver<T>`) gets triggered sometimes, which as far as I can tell is not documented anywhere and as such seams to be a bug, and not a misuse of the broadcast channel.

The channel in question was created via `tokio::sync::broadcast::channel(1)`, in case this might be the edge case responsible.

**Comment by Darksonn** [comment]
The broadcast channel was changed in the [v0.2.21][1] release. Can you check if you still get the issue.

[1]: https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.21

**Comment by 42triangles** [comment]
As far as I can tell the issue doesn't occur anymore. I'll close the ticket and reopen it should it occur again.

**Comment by 42triangles** [comment]
The issue appears to still occur sporadically.

**Comment by 42triangles** [comment]
As far as I can tell stopping the sheer amount of spamming (which was essentially a busy loop of spamming until the response is received) stops the issue from occurring.

**Comment by Darksonn** [comment]
It would be very helpful if you could try to make it happen in a small test case.

**Comment by 42triangles** [comment]
> This happened in a relatively large codebase, so it's rather hard to try to isolate what exactly contributes to this behaviour, and as such, I sadly do not have a minimal example for when this happens.

I *finally* managed to replicate it (thanks for reminding me to try again with the added knowledge of the spamming maybe being a part of it):

```rust
use std::mem::drop;

use tokio::sync::broadcast;

#[tokio::main]
async fn main() {
    loop {
        let (sender, _unused_receiver) = broadcast::channel(3);
        let actual_receiver = sender.subscribe();

        {
            tokio::spawn(async move {
                for _ in 0..30 {
                    let _ = sender.send(());
                }
            });
        }

        drop(actual_receiver);  // also happens when dropping the first receiver first
    }
}
```

The bug appears to occur when:
* There are more than one receivers
* At the point of one of the receivers dropping there are still values being sent into the channel
* The channel has a low capacity

**Comment by Darksonn** [comment]
Thank you! Confirmed locally on my machine in both debug and release mode.
