### ISSUE TITLE
CancellationToken cfg

### ISSUE THREAD

**Issue by MikailBag** [tokio-rs/tokio#2534]
## Version
v0.2.20 or  `master`
## Platform
any
## Subcrates
probably `tokio-sync`
## Description

Currently, to use `CancellationToken` one has to add `tokio_unstable` [cfg](https://github.com/tokio-rs/tokio/blob/fb7dfcf4322b5e60604815aea91266b88f0b7823/tokio/src/macros/cfg.rs#L360) to `$RUSTFLAGS`. This is not very comfortable thing to do, especially for libraries (though libraries can greatly benefit from one true cooperative cancellation). That's why, I propose alternative solution:
`CancellationToken` would be gated on `cfg(feature = "unstable_cancellation_token")` or `cfg(feature = "unstable")`. Documentation would state (both in features section in crate overview and in CancellationToken docs), that the functionality is not covered by semver and can be changed in every subsequent release, so users should be ready to change their code after updating Tokio version.

If you agree, I will be happy to submit PR.

UPD: I have forgotten to mention that, of course, `feature = all` would not enable `feature = unstable`.

**Comment by carllerche** [comment]
This is by design. As the API will change still, it is important that the **end** application opts into it. Adding friction for libraries is an explicit choice at this point.

That said, I am wondering if we can explore the API in a separate crate in order to make it "public".

**Comment by MikailBag** [comment]
Well, your explanation (and explanation by `@vorot93`) makes total sense.
Thank you for clarification.
