### ISSUE TITLE
paper of timer wheel

### ISSUE THREAD

**Issue by zyctree** [tokio-rs/tokio#2537]
i would like to read the code about the detail implementation of timer, found

```rust
///
/// # Implementation
///
/// THe time driver is based on the [paper by Varghese and Lauck][paper].
///
```

but the link to the paper is missing, searching in history, there is a commit that removed this link,
https://github.com/tokio-rs/tokio/commit/7b53b7b659fe1feeb30e768cad8fdadf9531beb6#diff-e7962099c7699aa4d4efb9ac594f0665L82. is there any reason it was removed? seems like it was removed by accident

Btw, this link missing makes `cargo doc --document-private-items` fail

**Comment by Darksonn** [comment]
You can find the paper [here](http://www.cs.columbia.edu/~nahum/w6998/papers/ton97-timing-wheels.pdf). This issue will be fixed by #2572.
