### ISSUE TITLE
mio-named-pipes pulls old crates

### ISSUE THREAD

**Issue by xTachyon** [tokio-rs/tokio#2547]
Hello. Not sure if this is the best place to ask, but I'm quite annoyed that tokio uses `mio-named-pipes` which pulls old deps along with it.

I'm looking for a way to disable the usage of that crate. I see it's optional, but it looks like it's used by quite a few useful features.

I get that *someone* might want to use named pipes on windows, and that's fine, but for me personally it won't probably be something I need very soon.

So, that's my problem, it pulls old duplicates crates that take compilation time, which is already bad. What can I do ?

**Comment by taiki-e** [comment]
Closing -- dependency on mio-named-pipes is removed in #2893
