### ISSUE TITLE
unresolved future tokio::time::interval within tokio::select

### ISSUE THREAD

**Issue by iffyio** [tokio-rs/tokio#2565]
**Version**
rustc: 1.43.0
tokio: 0.2.21

**Platform**
5.3.0-51-generic

**Description**
Hi! I ran into a behavior that I couldn't explain while running
multiple `select!` branches in a loop, one of which had `interval.tick()`
as an async expression - The `interval.tick()` handler never executed, likely
because its future never resolved.

Here's an example to reproduce the behavior.

The idea here is to spawn a routine and shut it down after a timeout expires.
The routine sits in a loop, either waiting for a shutdown
signal (by `recv`ing on a channel) or, periodically logs a message to stdout.

The **expected behavior**, is that the program should log to stdout
during the time it waits for the shutdown signal (so we should get
several log lines with the message 'tick'

The **observed behavior**, is that nothing is logged to stdout because
the `interval.tick()` future never resolves.

Interesting is that is that, by not sending on the shutdown channel,
we get the expected behavior.

```rust
use tokio::time;
use std::time::Duration;

#[tokio::main(core_threads=2)]
async fn main() -> Result<(), std::io::Error> {
    let (mut send, recv) = tokio::sync::mpsc::channel(100);

    let shutdown_trigger = tokio::spawn(async move {
        tokio::time::delay_for(Duration::from_millis(1000)).await;

        // We get the expected behavior by commenting out this line.
        send.send(()).await.unwrap();
    });

    let done = run_with_shutdown(recv);
    shutdown_trigger.await.unwrap();
    done.await;

    Ok(())
}

async fn run_with_shutdown(mut shutdown: tokio::sync::mpsc::Receiver<()>) {
    let mut interval = time::interval(time::Duration::from_millis(100));
    loop {
        tokio::select! {
               _ = &mut Box::pin(interval.tick()) => println!("tick"),
               _ = &mut Box::pin(shutdown.recv()) => {
                    println!("shutting down");
                    return
               },
            }
    }
}

```

**Comment by Darksonn** [comment]
This doesn't do what you think it does:
```rust
let done = run_with_shutdown(recv);
shutdown_trigger.await.unwrap();
done.await;
```
This will wait for `shutdown_trigger` to finish before starting to run `run_with_shutdown`. This is because you did not spawn it, and futures do nothing until polled. It will work if you swap them.

Note that your loop can be written a bit simpler like this:
```rust
loop {
    tokio::select! {
       _ = interval.tick() => println!("tick"),
       _ = shutdown.recv() => {
            println!("shutting down");
            return
       },
    }
}
```
Note that with the `send` commented out, it still takes a second before it starts printing `tick`.
