### ISSUE TITLE
tokio::sync::Mutex is slow when used with futures::stream::FuturesUnordered

### ISSUE THREAD

**Issue by fluxxu** [tokio-rs/tokio#2568]
**Version**
tokio v0.2.21
tokio-macros v0.2.5

**Platform**
macOS Catalina/Windows 64

**Description**
Our GraphQL server uses [DataLoader](https://github.com/cksac/dataloader-rs) to cache queries. Yesterday we found that sometimes the server uses 100% CPU and hangs. We did some digging and turns out if we replace `tokio::sync::Mutex` with `futures::lock::Mutex`, the issue is gone.

**Reproduce**
I made a reproducible example here:

https://github.com/BSpaceinc/tokio-2568

Mutex implementation is controlled by feature flags:

```
PS C:\Users\fluxx\Projects\tokio-2568> cargo run --no-default-features --features mutex-tokio --release
    Finished release [optimized] target(s) in 0.11s
     Running `target\release\tokio-2568.exe`
tokio::sync::Mutex = 85ms
```

```
cargo run --no-default-features --features mutex-futures --release
   Compiling tokio-2568 v0.1.0 (C:\Users\fluxx\Projects\tokio-2568)
    Finished release [optimized] target(s) in 1.61s
     Running `target\release\tokio-2568.exe`
futures::lock::Mutex = 64ms
```

```
PS C:\Users\fluxx\Projects\tokio-2568> cargo run --no-default-features --features mutex-async-std --release
   Compiling tokio-2568 v0.1.0 (C:\Users\fluxx\Projects\tokio-2568)
    Finished release [optimized] target(s) in 1.68s
     Running `target\release\tokio-2568.exe`
async_std::sync::Mutex = 67ms
```

You can see the time difference between `futures::lock::Mutex` and `async_std::sync::Mutex` is negligible while `tokio::sync::Mutex` spent much longer.

**Comment by carllerche** [comment]
For posterity, in case anyone comes across this later, I have included the submitted repro. The result of the discrepancy is due to an incorrect benchmark setup. The Tokio version is doing a lot more work than the others.

The difference comes from the fact that, for Tokio, each task is spawned onto the thread pool, which causes contention on the mutex. For the `futures` and `async-std` version, the tasks are run single-threaded, which results in no contention.

```rust
use futures::stream::FuturesUnordered;
use futures::stream::StreamExt;
use std::sync::Arc;
use std::time::Instant;

#[tokio::main]
async fn main() {
    let n = 500;
    let yield_count = 100;

    println!("Running {} tasks using futures mutex...", n);
    let t = Instant::now();
    let lock_count = futures_mutex(n, yield_count).await;
    let d = Instant::now() - t;
    println!("Lock count = {}, time = {}ms", lock_count, d.as_millis());

    println!("Running {} tasks using tokio mutex...", n);
    let t = Instant::now();
    let lock_count = tokio_mutex(n, yield_count).await;
    let d = Instant::now() - t;
    println!("Lock count = {}, time = {}ms", lock_count, d.as_millis());

    println!("Running {} tasks using async-std mutex...", n);
    let t = Instant::now();
    let lock_count = async_std_mutex(n, yield_count).await;
    let d = Instant::now() - t;
    println!("Lock count = {}, time = {}ms", lock_count, d.as_millis());
}

async fn tokio_mutex(n: usize, yield_count: usize) -> i32 {
    use tokio::sync::Mutex;
    let state = Arc::new(Mutex::new(0_i32));
    let tasks = FuturesUnordered::new();
    for _ in 0..n {
        let state = state.clone();
        let task = tokio::spawn(async move {
            let mut lock = state.lock().await;
            *lock = *lock + 1;
            for _ in 0..yield_count {
                tokio::task::yield_now().await;
            }
            drop(lock);
        });
        tasks.push(task);
    }
    tasks.collect::<Vec<_>>().await;
    let lock = state.lock().await;
    *lock
}

async fn futures_mutex(n: usize, yield_count: usize) -> i32 {
    use futures::lock::Mutex;
    let state = Arc::new(Mutex::new(0_i32));
    let tasks = FuturesUnordered::new();
    for _ in 0..n {
        let state = state.clone();
        let task = async move {
            let mut lock = state.lock().await;
            *lock = *lock + 1;
            for _ in 0..yield_count {
                tokio::task::yield_now().await;
            }
            drop(lock);
        };
        tasks.push(task);
    }
    tasks.collect::<Vec<_>>().await;
    let lock = state.lock().await;
    *lock
}

async fn async_std_mutex(n: usize, yield_count: usize) -> i32 {
    use async_std::sync::Mutex;
    let state = Arc::new(Mutex::new(0_i32));
    let tasks = FuturesUnordered::new();
    for _ in 0..n {
        let state = state.clone();
        let task = async move {
            let mut lock = state.lock().await;
            *lock = *lock + 1;
            for _ in 0..yield_count {
                tokio::task::yield_now().await;
            }
            drop(lock);
        };
        tasks.push(task);
    }
    tasks.collect::<Vec<_>>().await;
    let lock = state.lock().await;
    *lock
}
```

**Comment by fluxxu** [comment]
Hi @carllerche,

You are right. I realized the problem of my benchmark setup, so I closed this issue and deleted the repository.
I am still trying to make a correct reproducible example of this issue.
Sorry for the confusion.

**Comment by carllerche** [comment]
@fluxxu if you are seeing 100% CPU load, could you run a profile to see the stack where the time is spent?

Also, if you are using `FuturesUnordered`, I know it had some issues in the past that could result in 100% cpu load paired w/ some tokio types.

**Comment by fluxxu** [comment]
@carllerche 
Yes, it does seem to relate to `FuturesUnordered`.

|Function Name|Total CPU [unit, %]|Self CPU [unit, %]|Module|
|---|---|---|---|
| - futures_util::stream::futures_unordered::{{impl}}::poll_next<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|31068 (99.68%)|694 (2.23%)|bs-api.exe|
| - core::sync::atomic::atomic_load<usize>|658 (2.11%)|658 (2.11%)|bs-api.exe|
| - futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>::dequeue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|2665 (8.55%)|633 (2.03%)|bs-api.exe|
| - alloc::sync::{{impl}}::deref<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1746 (5.60%)|520 (1.67%)|bs-api.exe|
| - alloc::sync::Arc<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>::inner<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1235 (3.96%)|500 (1.60%)|bs-api.exe|
| - core::ptr::non_null::NonNull<core::task::wake::Context>::as_ptr<core::task::wake::Context>|497 (1.59%)|497 (1.59%)|bs-api.exe|
| - core::num::{{impl}}::wrapping_sub|496 (1.59%)|496 (1.59%)|bs-api.exe|
| - core::future::get_context|935 (3.00%)|491 (1.58%)|bs-api.exe|
| - core::sync::atomic::atomic_store<usize>|483 (1.55%)|483 (1.55%)|bs-api.exe|
| - core::mem::align_of_val<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|703 (2.26%)|482 (1.55%)|bs-api.exe|
| - core::ptr::non_null::NonNull<alloc::sync::ArcInner<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>::as_ref<alloc::sync::ArcInner<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>|707 (2.27%)|435 (1.40%)|bs-api.exe|
| - core::cell::UnsafeCell<mut futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>*>::get<mut futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>*>|430 (1.38%)|429 (1.38%)|bs-api.exe|
| - futures_util::stream::futures_unordered::FuturesUnordered<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>::unlink<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|3141 (10.08%)|422 (1.35%)|bs-api.exe|
| - core::ptr::non_null::NonNull<alloc::sync::ArcInner<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>::as_ptr<alloc::sync::ArcInner<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>|414 (1.33%)|414 (1.33%)|bs-api.exe|
| - core::sync::atomic::atomic_swap<usize>|414 (1.33%)|414 (1.33%)|bs-api.exe|
| - alloc::sync::Arc<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>::inner<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1086 (3.48%)|404 (1.30%)|bs-api.exe|
| - bs_pricing_package::graphql::query::{{impl}}::resolve_field_async::{{closure}}|11919 (38.24%)|381 (1.22%)|bs-api.exe|
| - core::ptr::read<core::option::Option<alloc::sync::Arc<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>>|510 (1.64%)|376 (1.21%)|bs-api.exe|
| - alloc::sync::Arc<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>::from_raw<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|3011 (9.66%)|376 (1.21%)|bs-api.exe|
| - core::sync::atomic::atomic_swap<u8>|368 (1.18%)|368 (1.18%)|bs-api.exe|
| - futures_util::stream::futures_unordered::FuturesUnordered<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>::link<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|2949 (9.46%)|344 (1.10%)|bs-api.exe|
| - futures_util::stream::futures_ordered::{{impl}}::poll<core::pin::Pin<alloc::boxed::Box<Future>>>|31067 (99.67%)|330 (1.06%)|bs-api.exe|
| - core::ptr::non_null::NonNull<alloc::sync::ArcInner<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>::as_ref<alloc::sync::ArcInner<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>|735 (2.36%)|327 (1.05%)|bs-api.exe|
| - core::ptr::non_null::NonNull<alloc::sync::ArcInner<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>::as_ptr<alloc::sync::ArcInner<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>|325 (1.04%)|325 (1.04%)|bs-api.exe|
| - core::alloc::layout::size_align<alloc::sync::ArcInner<()>>|324 (1.04%)|324 (1.04%)|bs-api.exe|
| - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future>>|31068 (99.68%)|317 (1.02%)|bs-api.exe|
| - core::sync::atomic::AtomicPtr<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>::load<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1052 (3.38%)|314 (1.01%)|bs-api.exe|
| - alloc::sync::data_offset<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|3091 (9.92%)|311 (1.00%)|bs-api.exe|
| - core::alloc::layout::Layout::padding_needed_for|1018 (3.27%)|306 (0.98%)|bs-api.exe|
| - core::ptr::non_null::NonNull<core::task::wake::Context>::cast<core::task::wake::Context,core::task::wake::Context>|804 (2.58%)|301 (0.97%)|bs-api.exe|
| - core::future::from_generator::{{impl}}::poll<generator-3>|13773 (44.19%)|271 (0.87%)|bs-api.exe|
| - futures_task::waker_ref::waker_ref<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|589 (1.89%)|271 (0.87%)|bs-api.exe|
| - alloc::sync::Weak<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>::upgrade<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1149 (3.69%)|265 (0.85%)|bs-api.exe|
| - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<()>>|8263 (26.51%)|265 (0.85%)|bs-api.exe|
| - juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::{{closure}}<bs_pricing_package::types::PricingPackage,bs_pricing_package::graphql::context::PricingPackageContext,juniper::value::scalar::DefaultScalarValue>|13181 (42.29%)|263 (0.84%)|bs-api.exe|
| - core::ptr::non_null::NonNull<core::task::wake::Context>::new_unchecked<core::task::wake::Context>|262 (0.84%)|262 (0.84%)|bs-api.exe|
| - alloc::sync::{{impl}}::deref<futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|1119 (3.59%)|258 (0.83%)|bs-api.exe|
| - core::alloc::layout::Layout::new<alloc::sync::ArcInner<()>>|937 (3.01%)|255 (0.82%)|bs-api.exe|
| - futures_util::stream::futures_unordered::ready_to_run_queue::ReadyToRunQueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>::enqueue<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|1694 (5.43%)|254 (0.81%)|bs-api.exe|
| - core::sync::atomic::atomic_load<u8>|249 (0.80%)|249 (0.80%)|bs-api.exe|
| - core::ptr::mut_ptr::{{impl}}::cast<core::task::wake::Context,core::task::wake::Context>|246 (0.79%)|246 (0.79%)|bs-api.exe|
| - futures_util::stream::futures_unordered::task::{{impl}}::wake_by_ref<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|5406 (17.34%)|244 (0.78%)|bs-api.exe|
| - core::future::from_generator::{{impl}}::poll<generator-16>|12373 (39.70%)|238 (0.76%)|bs-api.exe|
| - core::ptr::mut_ptr::{{impl}}::is_null<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|237 (0.76%)|237 (0.76%)|bs-api.exe|
| - futures_util::stream::futures_unordered::FuturesUnordered<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>::pending_next_all<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>|941 (3.02%)|235 (0.75%)|bs-api.exe|
| - core::ptr::swap_nonoverlapping_one<core::option::Option<alloc::sync::Arc<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>>|944 (3.03%)|232 (0.74%)|bs-api.exe|
| - core::sync::atomic::atomic_or<usize>|231 (0.74%)|231 (0.74%)|bs-api.exe|
| - core::mem::take<core::option::Option<alloc::sync::Arc<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>>>|1493 (4.79%)|226 (0.73%)|bs-api.exe|
| - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future>>|31067 (99.67%)|223 (0.72%)|bs-api.exe|
| - core::mem::min_align_of_val<futures_util::stream::futures_unordered::task::Task<futures_util::stream::futures_ordered::OrderWrapper<core::pin::Pin<alloc::boxed::Box<Future>>>>>|221 (0.71%)|220 (0.71%)|bs-api.exe

**Comment by carllerche** [comment]
What version of the `futures` crate do you have pulled in?

**Comment by fluxxu** [comment]
0.3.4

```
PS C:\Data\Projects\bs-core> cargo tree | findstr.exe "futures"
??  ????? futures v0.3.4
??  ??  ????? futures-channel v0.3.4
??  ??  ??  ????? futures-core v0.3.4
??  ??  ??  ????? futures-sink v0.3.4
??  ??  ????? futures-core v0.3.4
??  ??  ????? futures-executor v0.3.4
??  ??  ??  ????? futures-core v0.3.4
??  ??  ??  ????? futures-task v0.3.4
??  ??  ??  ????? futures-util v0.3.4
??  ??  ??      ????? futures v0.1.29
??  ??  ??      ????? futures-channel v0.3.4 (*)
??  ??  ??      ????? futures-core v0.3.4
??  ??  ??      ????? futures-io v0.3.4
??  ??  ??      ????? futures-macro v0.3.4
??  ??  ??      ????? futures-sink v0.3.4
??  ??  ??      ????? futures-task v0.3.4
??  ??  ????? futures-io v0.3.4
??  ??  ????? futures-sink v0.3.4
??  ??  ????? futures-task v0.3.4
??  ??  ????? futures-util v0.3.4 (*)
??      ????? futures-core v0.3.4
??  ??      ??  ????? futures-core v0.3.4
??  ??      ????? futures-core v0.3.4
??  ??      ????? futures-util v0.3.4 (*)
??  ??      ??  ????? futures-channel v0.3.4 (*)
??  ??      ??  ????? futures-core v0.3.4
??  ??      ??  ????? futures-util v0.3.4 (*)
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-sink v0.3.4
??  ??      ??  ??  ????? futures-util v0.3.4 (*)
??  ??      ??  ??      ????? futures-core v0.3.4
??  ??      ??  ??      ????? futures-sink v0.3.4
??  ??      ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??      ????? futures-core v0.3.4
??  ??      ??      ????? futures-util v0.3.4 (*)
??  ??      ??  ????? futures-core v0.3.4
??  ??      ??  ????? futures-util v0.3.4 (*)
??  ??      ??  ??  ????? futures-core v0.3.4
??  ??      ??  ??  ????? futures-util v0.3.4 (*)
??  ??      ????? tracing-futures v0.2.3
??  ??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??  ??  ????? futures v0.3.4 (*)
??  ??  ??  ????? futures v0.3.4 (*)
????? futures v0.3.4 (*)
??  ??  ????? futures v0.1.29
??  ??  ??  ????? futures v0.1.29
??  ??  ??  ????? futures-cpupool v0.1.8
??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??      ????? futures v0.1.29
??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??      ????? futures v0.1.29
??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??  ??      ????? futures v0.1.29
??  ??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??  ??      ????? futures v0.1.29
??  ??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??  ??  ????? futures v0.1.29
??  ??  ??  ??      ????? futures v0.1.29
??  ??  ??      ????? futures v0.1.29
??  ??  ??  ????? futures v0.1.29
??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??  ??  ??  ????? futures v0.3.4 (*)
??  ??  ????? futures v0.3.4 (*)
??  ??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
????? futures v0.3.4 (*)
??  ????? futures v0.3.4 (*)
??      ????? futures v0.3.4 (*)
??      ??  ????? futures v0.3.4 (*)
```

**Comment by fluxxu** [comment]
@carllerche
I made another example here:
https://github.com/BSpaceinc/tokio-2568

All codes are the same expect the Mutex implementation ([controlled by feature flag](https://github.com/BSpaceinc/tokio-2568/blob/master/src/mutex.rs)).

**Comment by Matthias247** [comment]
FWIW, I tried the latest repro repro with a release build (not linked in the readme), and also added a futures-intrusive version (which should actually be pretty similar to the tokio version).

For me the async-std, futures-rs and futures-intrusive versions are all bouncing somewhere between 40-60ms (most interestingly all at the edges  - never hits 50ms), whereas the tokio version is around 80ms.

Didn't notice any hangs.

**Comment by fluxxu** [comment]
I have updated the example code.
tokio 0.2 -> 0.3
added futures-intrusive

Results on my Ryzen 3900XT + Windows machine:

## `tokio::sync::Mutex`

```
cargo run --no-default-features --features mutex-tokio --release
    Finished release [optimized] target(s) in 0.08s
     Running `target\release\tokio-2568.exe`
tokio::sync::Mutex = 68ms
```

## `futures::lock::Mutex`

```
cargo run --no-default-features --features mutex-futures --release
    Finished release [optimized] target(s) in 0.09s
     Running `target\release\tokio-2568.exe`
futures::lock::Mutex = 57ms
```

## `async_std::sync::Mutex`

```
cargo run --no-default-features --features mutex-async-std --release
    Finished release [optimized] target(s) in 0.09s
     Running `target\release\tokio-2568.exe`
async_std::sync::Mutex = 58ms
```

## `futures-intrusive(fair = false)`

```
cargo run --no-default-features --features mutex-futures-intrusive --release
    Finished release [optimized] target(s) in 0.08s
     Running `target\release\tokio-2568.exe`
futures_intrusive::sync::Mutex(fair = false) = 63ms
```

## `futures-intrusive(fair = true)`

```
cargo run --no-default-features --features mutex-futures-intrusive-fair --release
    Finished release [optimized] target(s) in 0.09s
     Running `target\release\tokio-2568.exe`
futures_intrusive::sync::Mutex(fair = true) = 62ms
```

I think the diff is very small now and since this is a micro-benchmark, it may not be worthwhile to investigate this issue.
And I couldn't find a reliable way to reproduce that CPU 100% issue.
Closing
