### ISSUE TITLE
Handle::spawn missing feature flag documentation attribute

### ISSUE THREAD

**Issue by haze** [tokio-rs/tokio#2584]
**Version**  0.2.21
**Platform** Darwin Deep-Pearl 19.5.0 Darwin Kernel Version 19.5.0: Sat Mar 21 01:41:29 PDT 2020; root:xnu-6153.120.15~20/RELEASE_X86_64 x86_64
**Description** In the docs (viewed [here](https://docs.rs/tokio/0.2.21/tokio/runtime/struct.Runtime.html#method.spawn)), `Handle::spawn` is feature gated by `rt-core`, but the documentation does not convey this.

**Comment by jyn514** [comment]
`spawn()` no longer has `cfg(feature = "rt-core")`, so I think this can be closed. https://docs.rs/tokio/1.0.1/src/tokio/runtime/mod.rs.html#372-378

**Comment by Darksonn** [comment]
Yeah, the `Runtime` itself is now feature gated by the feature `rt`.
