### ISSUE TITLE
Make blocking thread timeout configurable

### ISSUE THREAD

**Issue by oribs1** [tokio-rs/tokio#2585]
**Is your feature request related to a problem? Please describe.**
I have a case where I want to schedule a potentially blocking task every 60 seconds. Today the timeout for a thread in the BlockingPool is a constant named `KEEP_ALIVE` with the value of 10. This mean that in my worst case scenario I would have to create a new thread each time I schedule my task. For my workflow it make more sense to keep the thread alive for a longer period, this way avoiding creating a new thread each time I schedule a task. 

**Describe the solution you'd like**
Making the constant `KEEP_ALIVE` configurable through the Builder

**Describe alternatives you've considered**
Without it, the best alternative is to schedule a "dummy" task, to make sure the thread is staying alive

**Comment by carllerche** [comment]
Sounds good to me :+1: I would be open to a PR for this.
