### ISSUE TITLE
`read_to_end` sometimes returns 0 bytes, even though the document exists.

### ISSUE THREAD

**Issue by rodya-mirov** [tokio-rs/tokio#2586]
**Version**
List the versions of all `tokio` crates you are using. The easiest way to get
this information is using `cargo-tree`.

Attached; note two copies of `tokio`, but everything else is fine. This is being pulled in by an old version of `hyper`, which in turn is being pulled in by `tower`, which is abandoned and pinned to some old dependencies. This issue actually came out by me trying to get rid of it, which involves me moving to async.

* tokio v0.2.21
* tokio v0.1.22
* tokio-macros v0.2.5
* tokio-util v0.3.1
* tokio-tls v0.3.1
* tokio-io v0.1.13
* tokio-buf v0.1.1 
* tokio-codec v0.1.2
* tokio-current-thread v0.1.7
* tokio-executor v0.1.10
* tokio-fs v0.1.7
* tokio-threadpool v0.1.18
* tokio-reactor v0.1.12
* tokio-sync v0.1.8
* tokio-tcp v0.1.4
* tokio-timer v0.2.13
* tokio-udp v0.1.6
* tokio-uds v0.2.6

**Platform**
Darwin MCC02ZJGEXMD6M 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Description**
Enter your issue details here.
One way to structure the description:

A perfectly good S3 document will sometimes fail to download.

I tried this code (snipped heavily to just show the relevant parts):

```
async {
                // output is a StreamingOutput from a client.get_object(get_request) call
                let mut buffer = Vec::new();
                let result = output.into_async_read().read_to_end(&mut buffer).await;
                // buffer should now have bytes in it
}
```

*I expected to see this happen*: the bytes would be consistently downloaded, in their entirety.

*Instead, this happened*: sometimes, `read_to_end` would give 0 bytes. Even if I add in a retry loop (calling read_to_end endlessly, over and over), it will always download 0 bytes. Trying the entire request over again seems to fix it.

I'm not sure if this is me using it wrong, or what; I've just updated from rusoto 0.42, which was sync enough; but the new implementation of `into_blocking_read` panics if there is an ambient tokio runtime, so I must use `into_async_read`, which seems to be unreliable in the above sense.

**Comment by rodya-mirov** [comment]
Just an update; in the original block of code, the `get_object` call and `read_to_end` call were in different async blocks, and thus possibly executing on different instances of tokio's Runtime. I've moved it so it's inside one single async block, and the problem seems to be resolved.

However, this makes me really uncomfortable -- it seems to imply that the state of the future is partially stored in itself, and partially stored in the Future. Moreover, there's no obvious way to even determine if they were running on different runtimes, since the runtime is in global, mutable, _hidden_ state. This is precisely the mess that I thought Rust aspired to never get involved with, but here we are.

I'm leaving this open, because even though my issue is resolved, this whole state of affairs makes me very uncomfortable.

**Comment by Darksonn** [comment]
Can you elaborate a bit more on what's going on here? You said the two calls were in different async blocks, but that doesn't necessarily imply you have multiple runtimes running. Are you creating multiple runtimes yourself, or where are the multiple runtimes coming from?

And even then, it's not clear why having the `get_object` call be in a different runtime from `read_to_end` should cause problems. That sounds like it would be a bug in rusoto if so.

**Comment by rodya-mirov** [comment]
Hi, sorry, I swear I posted this on rusoto's tracker. I closed it because I realized it was on tokio's, which makes no sense (maybe I had both tabs open? no idea).

The mess I ended up with is that I have a worker thread (not in an async runtime) doing a bunch of work in the background (but taking up most of the CPU/memory resources), as well as an actix server running to post work / check on the results. iirc actix uses its own handrolled variant of a tokio runtime.

To interact with rusoto in the worker thread, I have this snippet:

```
use std::future::Future;

use tokio::runtime::{Handle, Runtime};

pub fn wait_for<T, Fut: Future<Output = T>>(fut: Fut) -> T {
    if let Ok(handle) = Handle::try_current() {
        handle.block_on(fut)
    } else {
        Runtime::new()
            .expect("Should be able to launch runtime, none is running")
            .block_on(fut)
    }
}
```

which attempts to detect if there is a runtime going (by the way; it doesn't detect actix's runtime with Handle::try_current(), but Runtime::new() causes a runtime panic; lovely).

What I had been doing was, in the "download from s3" bit, calling `wait_for` on the initial get object call, and `wait_for` again on the `read_to_end` call. This intermittently (but not that rarely) caused it to "successfully" download 0 bytes (but the content-length in the metadata had a nonzero size).

When I put everything in the same async block the problem went away. The reason I suggest they may be running in different runtimes is because of the `wait_for` -- I don't understand whether `Runtime::new()` leaves the runtime lying around, accessible for the next call, or immediately drops it (I would hope the latter but there's no telling). In any case it would appear (wild guess) that sometimes the future would start downloading _some_ of the bytes in the initial get call, leave them attached to the runtime (somehow?) and then the second call has no way to know those bytes were lost, and just keeps reading from where it is.

Hopefully that's enough context. Not sure what to do with all this.

**Comment by Darksonn** [comment]
Your `wait_for` would unconditionally panic if called from inside a runtime, even if the runtime is correctly detected by `try_current`. You can't use `block_on` inside a runtime.

> I don't understand whether Runtime::new() leaves the runtime lying around, accessible for the next call, or immediately drops it

Your `wait_for` drops the runtime on every call. To reuse it, you would need a global or similar.

**Comment by rodya-mirov** [comment]
Well, that explains half of it. Is there any way to fix this wait_for? I just want to wait for a future

**Comment by Darksonn** [comment]
You can't `block_on` inside a runtime. You should `.await` the future instead of trying to block the thread.

**Comment by rodya-mirov** [comment]
If only it were that easy. The function isn't async -- in fact the whole point of this function is to allow calling an async function in a sync context.

I'm reminded of this old blog post: https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/

I'm trying to call an async function in a sync function, because the alternative is to make every single function in my project async, even though I only need it in one tiny place. Further, it's causing panics because of state that's not locally observable, and that's really frustrating. The blocking variant in rusoto must do the same thing as this under the hood, because it causes the same runtime panic if it happens to be called from a thread that tokio or actix controls.

**Comment by Darksonn** [comment]
You are not _really_ trying to call async from a truly sync context here. You are in an async context already, but you have a sync layer between you and the async context. The Rust language does not have a runtime, so the kind of magic necessary to avoid this issue is simply impossible in Rust. Async functions are compiled in a very very different way from ordinary functions.

You may be able to get it to work with [`block_in_place`][3], which works [inside a spawned task][1], but not [in the main function][2], and requires the threaded runtime. By using this technique, you give up most of the advantages of async/await over simply spawning threads, but you may find it helpful anyway.

[1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8640622d677dfdb79bc0ceb2d3e13f59
[2]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5de84f7f50c36b83ee0a120bfa68c5b5
[3]: https://docs.rs/tokio/0.2/tokio/task/fn.block_in_place.html

**Comment by rodya-mirov** [comment]
Well, "context" perhaps has an unclear meaning. The function of interest is not an async function. I understand the distinction between async and sync functions; but if you call an async function (regardless of where), it returns a Future, which is (among many other things), a struct which can be passed around and acted on. I am just attempting to execute the future. The function that is attempting to execute it, has no way of knowing if there is an ambient runtime (as best as I can tell).

In my context I'm not worried about the advantages of async/await (if I was IO bound, I would indeed paint the whole project red and be done with it). I see you're saying I can't call `block_on` with the current Handle (if it exists); I wonder what this API is for and why it's public, if it's guaranteed to fail.

In any case I wonder if there is a reliable way of detecting _that_ I am in a runtime's context. Clearly tokio can do this under the hood, because it's capable of launching these runtime panics. If I had such a function (even a boolean would do), I could either use the (correctly functioning) "launch a new runtime and have it execute the future" method, or, if there is an ambient runtime, launch a new thread and execute it in that.

Is there such a function, which actually works?

**Comment by Darksonn** [comment]
> The function of interest is not an async function.

Then it really should not be in an async context in the first place. Blocking the thread inside a future running on the Tokio runtime monopolizes one of Tokio's threads, and Tokio only spawns one per cpu core. Once you have 8 (or however many cpu cores you have) tasks that are blocking without telling the executor, everything else will cease to execute until a thread is freed up.

You are generally supposed to use [`spawn_blocking`][1] or [`block_in_place`][2] whenever you want to transition from async to sync code. The first is vastly preferable to the latter, but can only be used at the boundary between async and blocking code. The latter can also be used further in, but is a footgun in various ways.

> Well, "context" perhaps has an unclear meaning.

With "context", I am referring to anything that is in the callstack of an async function without marking the transition into blocking code with the tools outlined above.

> I see you're saying I can't call block_on with the current Handle (if it exists); I wonder what this API is for and why it's public, if it's guaranteed to fail.

The `Handle` type is intended as a tool for talking to a runtime from other threads. You would normally e.g. spawn a thread and move the `Handle` into the thread, in which case the `Handle::block_on` method works fine.

> In any case I wonder if there is a reliable way of detecting _that_ I am in a runtime's context.

The `Handle::try_current` method should allow this. If actix does something weird that breaks this, I don't know what it is, but with any normal runtime, `try_current` should certainly work.

That said, trying to do this is not recommended, and if at all possible, you should make sure that blocking code does not run directly on the Tokio runtime without a `spawn_blocking` call in between. It is the responsibility of the async code to ensure that any non-async code it calls runs off the async context.

[1]: https://docs.rs/tokio/0.2/tokio/task/fn.spawn_blocking.html
[2]: https://docs.rs/tokio/0.2/tokio/task/fn.block_in_place.html
