### ISSUE TITLE
`TcpClient` leaks connection

### ISSUE THREAD

**Issue by jvff** [tokio-rs/tokio#26]
I don't know if this is an expected behavior, but it seems that a `TcpClient` somehow leaks its internal connection (a `TcpStream` instance?) into the `tokio_core::reactor::Core` it's running on.

I created an [example test case][1] that has two tests. One test forces the `Core` instance to drop before the test asserts that the connection is closed (somewhat indirectly, by checking if a dummy server thread has finished). The other lets the `Core` instance live beyond the assertion, so it's only dropped in the end of the test. The first test succeeds, while the second fails.

[1]: https://github.com/jvff/possible_tokio-proto_tcpclient_connection_leak

**Comment by carllerche** [comment]
Is this regarding tokio-proto? https://github.com/tokio-rs/tokio-proto If so, would you mind opening the issue there?

**Comment by jvff** [comment]
Oops, sorry, I posted to the wrong project :'(

Should I close this issue?

Thanks for the patience.

**Comment by carllerche** [comment]
It's ok. I will close. Feel free to open the issue on the other repo.
