### ISSUE TITLE
Align Encoder::encode() arguments with ByteOrder::write_*() [paper cut]

### ISSUE THREAD

**Issue by manuels** [tokio-rs/tokio#260]
There is a paper cut in the order of the arguments of

    trait tokio_io::codec::Encoder {
        fn encode(
            &mut self, 
            item: Self::Item, 
            dst: &mut BytesMut
        ) -> Result<(), Self::Error>;
    }

Since `dst` is `BytesMut` it is very likely that you call something like `LittleEndian::write_u16(&mut dst, 1_000_000);`.

As you can see the arguments here a flipped: `Encoder::encode(value, dst)` vs `ByteOrder::write_*(dst, value)`.

I would recommend to align the arguments of `Encoder::encode()` with `ByteOrder::write_*()` to get rid of this paper cut.

**Comment by carllerche** [comment]
Thanks, this is a good thought.

Is there any precedent regarding argument order in `std`?

**Comment by manuels** [comment]
I just know of `std::ptr::write_bytes(
    dst: *mut T, 
    val: u8, 
    count: usize
)` which has a similar use case.

**Comment by carllerche** [comment]
@manuels thanks for looking that up. That looks like a good equivalent. So, we should try to keep `dst` as the first argument.

I will tag this as 0.2 as it is a breaking change.

**Comment by carllerche** [comment]
I'm going to close this issue for now simply since no further action can be taken until a breaking change happens. However, it is tracked by #591 and once the time comes, I will open it again.
