### ISSUE TITLE
Incorrect doc comment for time::driver::entry::Entry

### ISSUE THREAD

**Issue by bjorn3** [tokio-rs/tokio#2617]
https://github.com/tokio-rs/tokio/blob/d2f81b506a469481ab0b62aaeaf48fc8c60e4c66/tokio/src/time/driver/entry.rs#L30-L34

> When `None`

`inner` is not an `Option`.

**Comment by blasrodri** [comment]
When calling `inner.updgrade()` returns `None`, perhaps @bjorn3 ?

**Comment by bjorn3** [comment]
Maybe say "When empty, ..." or something like that?

**Comment by blasrodri** [comment]
@Darksonn can we close it?

**Comment by Darksonn** [comment]
Yes. Please add "Fixes #PRNUM" or "Closes #PRNUM" on your PRs descriptions, as github then automatically closes the issue when the PR is merged.
