### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.remaining() >= dst.len()'

### ISSUE THREAD

**Issue by yuya008** [tokio-rs/tokio#2618]
**Version**
```
❯ cargo tree | grep tokio                                                                                                        proxy-rs/git/master
└── tokio v0.2.21
    └── tokio-macros v0.2.5
❯
```
**Platform**
Linux xs103192226168 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description**
Sorry, this stack error, I can not understand, because there is no information of my code, please have a look.
Here is my code repository: https://github.com/yuya008/proxy-rs

**Comment by carllerche** [comment]
We will need more info. At the very least the file / line no that the panic happens at.

Can you explain why you think this is a tokio bug?

**Comment by yuya008** [comment]
@carllerche I added the information
