### ISSUE TITLE
memory fragmentation due to size of tokio/src/time/driver/entry::Entry 

### ISSUE THREAD

**Issue by Dushistov** [tokio-rs/tokio#2619]
**Version**

tokio git: d2f81b506a469481ab0b62aaeaf48fc8c60e4c66

**Platform**

Linux 15inch 5.4.43-1-lts #1 SMP Wed, 27 May 2020 23:42:34 +0000 x86_64 GNU/Linux

**Description**

Full discussion can be found here: https://users.rust-lang.org/t/slow-memory-creep-in-long-running-tokio-process/44115/

[short summary of the bug]

I tried this code:

```
#[tokio::main]
async fn main() {
    for i in 0..1000 {
        many_tasks().await;

        println!("Run {:3}: {:?}", i, procinfo::pid::statm_self());
    }
}

async fn many_tasks() {
    let handles = (0..5_000_000)
        .map(|_| tokio::task::spawn(my_task()))
        .collect::<Vec<_>>();

    // order doesn't matter, wait for everything
    for handle in handles {
        handle.await.unwrap();
    }
}

async fn my_task() {
    tokio::time::delay_for(std::time::Duration::from_secs(5)).await;
}
```

I expected to see this happen: stabilization of growing of resident memory size at some point

Instead, this happened: the resident size keep growing

The profiling by  @bjorn3  shows that main culprit is  tokio/src/time/driver/entry::Entry ,

The `mem::size_of<Entry>()` shows 256 bytes,
so I made such changes and the size of `Entry` reduced to 128:
```
 #[derive(Debug)]
+#[cfg_attr(target_arch = "x86_64", repr(align(128)))]
+#[cfg_attr(not(target_arch = "x86_64"), repr(align(64)))]
 pub(crate) struct Entry {
     /// Only accessed from `Registration`.
-    time: CachePadded<UnsafeCell<Time>>,
+    time: UnsafeCell<Time>,
```

after that result is much better:
Before:
Run  82: Ok(Statm { size: 1658207, resident: 1117890, share: 623, text: 134, data: 1406815 })
After:
Run  82: Ok(Statm { size: 1150303, resident: 642104, share: 587, text: 134, data: 921357 })

**Comment by hawkw** [comment]
Hmm. It's worth noting that these entries are padded to the size of a whole CPU cache line for a reason: it avoids [false sharing](https://en.wikipedia.org/wiki/False_sharing) when two threads access other fields of the entry concurrently, which could negatively impact performance.

**Comment by Dushistov** [comment]
> these entries are padded to the size of a whole CPU cache line

I guessed about it, that why it is not PR :) This diff is just demonstration of this is possible to fix
within tokio. The main concern that the real tokio program would eat memory every day because of fragmentation, so you have to deploy it with memory watcher that kill it and restart. And this happens on the most popular platform: x86_64/linux. May be create separate memory pool per popular high frequently allocated things like timer?

**Comment by hawkw** [comment]
Yeah, it's possible we could do something similar to the slab allocation scheme used in the IO driver.

**Comment by carllerche** [comment]
The timer has been rewritten to no longer allocate per timeout. This issue should no longer apply. Thanks.
