### ISSUE TITLE
Compat with tokio-core's Handle?

### ISSUE THREAD

**Issue by bennofs** [tokio-rs/tokio#262]
Is there some way to provide a compatibility layer so that it is possible to use crates designed for `tokio-core` with `tokio` (or the other way around)? Right now that does not work since the handle types are not compatible.

**Comment by carllerche** [comment]
The way to work this right now is to create a `tokio_core::Core`, and take *that* `Handle`. You can get the new Tokio handle w/ https://docs.rs/tokio-core/0.1.16/tokio_core/reactor/struct.Handle.html#method.new_tokio_handle

Does that work?

**Comment by bennofs** [comment]
It is less flexible than the new way. For example, it is not possible to avoid using the `thread_pool` executor that way.

**Comment by carllerche** [comment]
the thread pool does no work unless it is used (no threads should be started).

That said, it would be plausible to add new constructors to `Core` that allow configuring it.

It will not be possible go from new_tokio::Handle -> old_tokio::handle.

**Comment by bennofs** [comment]
Would it also be possible to add an option to run `Core` with the `current_thread` executor? If I could limit the thread pool to 1 thread that should also be ok, but using `current_thread` is nicer.

**Comment by carllerche** [comment]
`Core` uses the current thread executor. When using `Core` by default, no thread pool thread is spawned.

**Comment by bennofs** [comment]
Oh I see, this issue can be closed in that case. I was confused because Core now uses Runtime which has a thread pool, but you are of course right, `Core::run` does not use the `Runtime`'s executor for the main future (it is only set as the default executor). In that case, this issue can be closed.
