### ISSUE TITLE
Upgrade mio to 0.7 to avoid compiling winapi twice

### ISSUE THREAD

**Issue by Michael-F-Bryan** [tokio-rs/tokio#2625]
I was troubleshooting compile times in one of my projects and found that I'm pulling in `winapi` v0.2.8 as well as v0.3.8, adding an extra 45 seconds to a full build.

Looking through my `Cargo.lock`, it seems like the chain is: tokio 0.2.21 → mio 0.6.22 → kernel32-sys 0.2.2 → winapi 0.2.8

I'm not sure how hard it'll be, but is it possible to bump the `mio` dependency to 0.7.0?

**Comment by Darksonn** [comment]
Updating mio is a breaking change, so this will not be changed until we reach v0.3. I believe the plan is to remove mio from Tokio's public api to avoid this in the future.
