### ISSUE TITLE
Blocking send and recv on bounded mpsc channel

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2629]
Wanting to communicate between sync and async code is rather common.

**Comment by carllerche** [comment]
We can probably add functions with `blocking_` prefixes. The key is to emphasize that these blocking fns must not be called from the runtime.

**Comment by xd009642** [comment]
I started having a brief look at this in #2684 would this just be for the bounded mpsc or also other channels?

**Comment by Darksonn** [comment]
It's mostly relevant for the bounded mpsc.
