### ISSUE TITLE
Consider renaming `Sleep` in tokio-timer

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#263]
This is a follow up to the timer PR: #249

In the original timer PR, `Sleep` is a future that does no work and completes with `()` at a specified instant:

```rust
Sleep::new(Instant:now() + Duration::from_millis(100))
    .wait()
```

However, `sleep` implies putting *something* to sleep, usually the current thread. This doesn't really represent what the type does as all it is is a notification that an instant in time has been reached.

Javascript uses `setTimeout` for this. I hesitate to use `Timeout` as timing out implies that some work is being timed and canceled if it goes for too long. This isn't what the type does either.

Some proposals for names:

* `Alarm` -- Seems plausible, `Alarm` might imply something bad is happening (fire alarm).
* `Delay` -- implies a `Duration` argument, not `Instant`.
* `When` -- too clever?

**Comment by Diggsey** [comment]
`Defer`?

**Comment by lnicola** [comment]
I like `Sleep` and `Timeout`.

`TimedWait`?

**Comment by carllerche** [comment]
@lnicola What do you think about the mentioned reservations?

`Sleep`: should put something (a thread?) to sleep.
`Timeout`: should cancel an operation that took too long.

**Comment by lnicola** [comment]
`Sleep` -- I see it like putting a `Future` to sleep, which is a small generalization over threads.
`Timeout` -- The word can also mean a pause or break, not only cancelling something, but yes, I see your point. I'm not sure if the name matters that much, though.

To compare, .NET has a `Task::Delay` method. In their case, however, the return type is simply `Task`.

**Comment by daiheitan** [comment]
Snooze? Since firefox has a https://addons.mozilla.org/en-US/firefox/addon/snoozetabs/ experiment

**Comment by kpp** [comment]
`Delay`
`LazyCockroach`
`TimeTraveler`

**Comment by Diggsey** [comment]
`WaitUntil` works well:

`WaitUntil(tomorrow).and_then(...)`.

**Comment by kpp** [comment]
`BackToThe(future).and_then(...);`
