### ISSUE TITLE
sync: bounded mpsc memory use is proportional to max waiters

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#2637]
**Version**

```
tokio v0.2.21
```

**Platform**

all

**Description**

The memory use of the bounded MPSC channel is proportional to the maximum number of tasks that have concurrently waited on the channel. This isn't _technically_ a "memory leak" as reported by tools like `valgrind`, as the memory _is_ freed when the channel is dropped. However, in systems where channels are long-lived, it may as well be a memory leak --- especially if the workload is bursty and the number of waiting tasks occasionally spikes. 

`tokio::sync`'s locking primitives, like `Mutex`, do not exhibit the same behavior. Instead, the memory use of a `Mutex` remains constant regardless of how many tasks are waiting for it. This is because the locks use the new intrusive semaphore implementation added in #2325. The intrusive semaphore does not require additional memory allocations per waiting task, while the old semaphore implementation (which uses a non-intrusive linked list) does. In addition, cancelled waiters in the new semaphore are unlinked from the list _when_ the waiting task terminates, while the old implementation only removes cancelled tasks from the wait list when it notifies a waiter.

I wrote a quick demo of this that compares the `mpsc` and `Mutex`: 
https://github.com/hawkw/tokio-buffer-repro

It spawns a bunch of tasks that all attempt to wait on `Sender::send`/`Mutex::lock` when the `mpsc` is full or the `Mutex` is already locked. The tasks cancel themselves after a period of time. During this, the repro prints the process' current memory use.

At the end of the test, before the `Mutex`/`mpsc` are dropped, we see the following:
```
mpsc:  waiters:      0; RSS:  36780 kb; virt: 6768197632 kb;
mutex: waiters:      0; RSS:   4844 kb; virt: 6676283392 kb;

```
We should update the MPSC channel to use the new semaphore implementation.

**Comment by hawkw** [comment]
As a side note: we have also observed occasional latency spikes after switching some code in Linkerd that used `Mutex` to use a `mpsc` channel instead. However, we don't have as tight a repro for that yet, so I'm going to work on this and hope it also improves that problem.

**Comment by zaharidichev** [comment]
@hawkw I am interested in working on that if it is ok. I had a question though.. It seems to me that switching to the new semaphore would necessitate the removal of the `poll_ready`, and `disarm` functions on the bounded sender. Or am I missing something. And if that is the case, is it fine to do so? I mean isn't having an `async fn send` that can fail if the buffer is full enough? Or are there more fundamental reasons for splitting the workflow into slot reservation/release steps and exposing these methods?

**Comment by carllerche** [comment]
Ah, I have this work in progress. It is close to completion.I hope to have a PR up today. I should have posted that, sorry.
