### ISSUE TITLE
Monitor channel buffer capacity

### ISSUE THREAD

**Issue by sampaioletti** [tokio-rs/tokio#2642]
**Describe the solution you'd like**
Provide a way to monitor the capacity of the channel buffers. i.e.
```rust
impl Sender<T>{
[...]
  pub fn buffer_len(&self)->usize{
   self.[inner-semaphore].available_permits()
  }
}
```

**Describe alternatives you've considered**
Currently using atomics to keep an accounting

**Additional context**
Not sure if that would be the correct way to handle it, in my case the loading on one worker thread may vary so I used the count to temporarily spawn additional works as needed.

Additionally the ability to resize the semaphore would be nice. Obviously there are ways to handle this outside of tokio, but I wasn't sure if it was basically already (nearly) possible with the semaphore api.

Thanks!

**Comment by Darksonn** [comment]
If this is possible to add with the information already stored in the channel, then I would be happy to add this feature.
