### ISSUE TITLE
Extend macros to optionally pass a runtime handle to the function

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tokio#2651]
**Is your feature request related to a problem? Please describe.**

The `tokio::main` or `tokio::test` macros are convenient helpers that avoid the boilerplate of setting up a runtime.
Unfortunately, using those macros comes at a cost: Not having access to the runtime at all.

**Describe the solution you'd like**

Extend the macros to allow users to opt in to receiving a `tokio::runtime::Handle` as an argument, like this:

```rust
#[tokio::main]
async fn main(handle: &Handle) {
        
}
```

**Describe alternatives you've considered**

The alternative to this is using the global `tokio::spawn` function within all application code that needs to spawn tasks. The downside of this is that it establishes an implicit dependency to the tokio runtime.
Even though this dependency most likely already exists, it may still be preferred to explicitly declare this dependency by requiring a `Handle` as a parameter.

Another alternative is give users access to the global runtime so they can acquire a `Handle` themselves at the top of main and pass it down to application code that requires a `Handle`.

At the moment, users have to choose between:

- boilerplate-free runtime setup through `#[tokio::main]`
- explicit dependency on the task spawning through a Handle

Allowing users to request a `Handle` as a parameter would solve this problem.

**Additional context**

- This feature can be implemented in a backwards-compatible way.
- To explicitly identify the handle, we could require marking it with `#[handle]` although I am not sure it is necessary because I can't think of any other parameters the user might want to have passed in.

**Comment by Darksonn** [comment]
Does this not work for you?
```rust
use tokio::runtime::Handle;

#[tokio::main]
async fn main() {
    let handle = Handle::current();
    
    ...
}
```

**Comment by thomaseizinger** [comment]
Oh, I didn't know about that API :D

I guess that solves the problem, thank you :)
