### ISSUE TITLE
Consider `future.spawned()` syntax

### ISSUE THREAD

**Issue by jerry73204** [tokio-rs/tokio#2652]
I found it a little cumbersome to spawn a future like this.

```rust
let future = async move {
    /* some lengthy code
       ...
       ...
    */
};
let handle = tokio::spawn(future);
```

I would prefer having an extension trait that adds the `.spawned()` suffix method call like this. Same would applies on closures and `Runtime::spawn()`.

```rust
let handle = async move { /* ... */ }.spawned();
```

**Comment by taiki-e** [comment]
(As a problem before considering whether it makes sense to do this), I don't think it makes sense to compare the two examples you wrote. The first example has bindings, the second example does not. Also, in the first example, the async block spans multiple lines, but in the second example, it is one line.


For example, the first example could be written as:
```rust
let handle = tokio::spawn(async move {
    /* some lengthy code
       ...
       ...
    */
});
```

**Comment by Darksonn** [comment]
I don't think adding this would bring much.

**Comment by hawkw** [comment]
It should also be quite easy for a third party crate to implement this in an extension trait in less than 20 lines of code. See [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c802a091480f5718e6bc3394a6e3d4a8).
