### ISSUE TITLE
AsyncBufRead Lines that ends with \r or \n

### ISSUE THREAD

**Issue by WeaponMan** [tokio-rs/tokio#2657]
**Is your feature request related to a problem? Please describe.**
I wanted to capture output from `rsync --info=progress2` with normal `Lines`, but found out that the output from rsync is ending with \r instead of \n, so the read loop was struck till rsync exited.

**Describe the solution you'd like**
Slight variation of Lines but with \r and \n as line ending or maybe better version will be something that I can specify what bytes (array of bytes one byte in that array is the ending) are the "split" to be considered a "line", maybe something like that exists already that gives string back in a stream like lines do?

**Describe alternatives you've considered**
I rolled my solution that I copied and modified from tokio source. not pretty but it gets the job done for now.

**Additional context**
-

**Comment by Darksonn** [comment]
Does [`read_until`][1] not satisfy your use case?

[1]: https://docs.rs/tokio/0.2/tokio/io/trait.AsyncBufReadExt.html#method.read_until

**Comment by WeaponMan** [comment]
not really look at what I did I need 2 possible untils:
```rust
pub(super) fn read_until_internal<R: AsyncBufRead + ?Sized>(
  mut reader: Pin<&mut R>,
  cx: &mut Context<'_>,
  byte: u8,
  byte2: u8,
  buf: &mut Vec<u8>,
  read: &mut usize,
) -> Poll<io::Result<usize>> {
  loop {
    let (done, used) = {
      let available = futures::ready!(reader.as_mut().poll_fill_buf(cx))?;
      if let Some(i) = memchr::memchr(byte, available) {
        buf.extend_from_slice(&available[..=i]);
        (true, i + 1)
      } else if let Some(i) = memchr::memchr(byte2, available) {
        buf.extend_from_slice(&available[..=i]);
        (true, i + 1)
      } else {
        buf.extend_from_slice(available);
        (false, available.len())
      }
    };
    reader.as_mut().consume(used);
    *read += used;
    if done || used == 0 {
      return Poll::Ready(Ok(mem::replace(read, 0)));
    }
  }
}

```

**Comment by Darksonn** [comment]
That implementation appears incorrect. Shouldn't you take the minimum of the indexes if both exist?

In any case, I think this belongs in Tokio's codec module rather than on `AsyncBufRead`, if we want it at all.

**Comment by WeaponMan** [comment]
Mainly I wanted all lines that ends with \n if there is \r in between that it doesn't really matter to me in the available buffer but if there is atleast one \r without \n then "split" it, because I would be buffering whole output until \n is found and that is a lot of data.
I use this to capture output of rsync that is send to server and saved to the database for logging purpose.

**Comment by hawkw** [comment]
> That implementation appears incorrect. Shouldn't you take the minimum of the indexes if both exist?
> 
> In any case, I think this belongs in Tokio's codec module rather than on `AsyncBufRead`, if we want it at all.

I believe the `LinesCodec` in `tokio_util` will handle `\r` nicely.

**Comment by Darksonn** [comment]
I don't think it currently handles lines that end with `\r` instead of `\r\n`.

**Comment by Darksonn** [comment]
I think that this is rather niche, and not too difficult to build manually with the codec module, so I'm going to close it.
