### ISSUE TITLE
Expressions in tokio attributes

### ISSUE THREAD

**Issue by xd009642** [tokio-rs/tokio#2662]
It would be quite nice (imo) to allow for expressions that result in the expected type in the macros i.e. `tokio::main` when setting the number of threads. This is probably best summed up with a minimal example so here's one I tried to see if it would work:

```Rust
use std::env::var;

fn get_threads() -> usize {
    if let Ok(s) = var("NUMBER_OF_THREADS") {
        s.parse().unwrap_or_else(|_| num_cpus::get_physical())
    } else {
        num_cpus::get_physical()
    }
}

#[tokio::main(core_threads="get_threads()")]
async fn main() {
    println!("Hello, world!");
}
```

Of course the alternative is to just use the runtime builder which is easy enough but I thought this might be easily done and be preferred for simpler changes i.e. changing to logical cpus not physical

**Comment by Darksonn** [comment]
This seems reasonably easy to implement using [`syn::parse_str`][1]. 

[1]: https://docs.rs/syn/1/syn/fn.parse_str.html

**Comment by xd009642** [comment]
Yeah I knew it was possible from using nom-derive. I'm happy to implement this and might start looking at it tonight if there's nothing already done or any objections to the idea :smile:

**Comment by xd009642** [comment]
@Darksonn I've created a WIP PR. It currently just uses parse_str to get an expression from string literals and uses that. https://github.com/tokio-rs/tokio/pull/2664

**Comment by Darksonn** [comment]
As discussed on discord, we have decided to close this as we do not want to support expressions in the `#[tokio::main]` macro. People should use the runtime builder instead.
