### ISSUE TITLE
Improve codec's documentation

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2681]
The documentation is currently rather poor for new users.

**Comment by carlosb1** [comment]
what is the status of this issue? Is it closed in the the other issue (#45)?. could it be good to have some guidelines about what it is necessary for this documentation?

**Comment by Darksonn** [comment]
This is still very relevant. Basically I am looking for an improvement such that I no longer have to link people to [this][1] when they ask for help. The following things would be useful:

 1. A general explanation of the methods that are used for `Decoder`. People very often don't understand how (or even that) they are supposed to handle incomplete frames.
 2. A similar explanation for `Encoder`. This one is simpler.
 3. A full example of a `Decoder`.
 4. A full example of an `Encoder`.

[1]: https://users.rust-lang.org/t/understanding-framed-in-tokio/42449/2

**Comment by Darksonn** [comment]
The documentation should also mention the `StreamReader` and `ReaderStream` types that are also in tokio-util, since `StreamReader` is a special case of an decoder with a `BytesCodec`.

**Comment by carlosb1** [comment]
Ok, I started with an [example](https://github.com/carlosb1/website/tree/2681_improve_codec_documentation/tutorial-code/codecs) that it works.

**Comment by Darksonn** [comment]
I would prefer an example that actually deals with the kind of data that has well defined boundaries, since otherwise it doesn't demonstrate when to use `Ok(None)`, and how to manipulate the data remaining in the `BytesMut`. For example, the stream could be a sequence consisting of 4 byte length markers followed by that number of bytes.

**Comment by carlosb1** [comment]
No problem, it was only a template. Anyway, I can use another parser like serde-json or I can get ideas from LengthDelimitedCodec . Furthermore, I can keep sending my doubts via slack if it is easy.

**Comment by Darksonn** [comment]
Sure, just ask any questions in the discord.

**Comment by carlosb1** [comment]
I added here a [tutorial](https://github.com/carlosb1/website/blob/2681_improve_codec_documentation/content/tokio/tutorial/codecs.md) and here the [code](https://github.com/carlosb1/website/tree/2681_improve_codec_documentation/tutorial-code/codecs).  I can do the PR if it is enough or we can discuss about more changes.

**Comment by Darksonn** [comment]
There are some problems with the decoder examples in your tutorial. The main thing I need the tutorial to explain is `Framed` does _not_ know where chunks start and end. That's the job of the decoder! The data in `buf` may not yet be a full JSON object, and in that case it should return `Ok(None)` to wait for more (additionally, `buf.len()` will never be zero). There may also be more data than a single JSON object, and it needs to handle that by only removing part of the data in the buffer.

I would prefer if we start with a much smaller piece of text we can put on docs.rs to explain this. We can add a section to the website after we have improved the text on docs.rs itself.

**Comment by carlosb1** [comment]
I see that you has another  PR for this, if you need some help. I open to contribute!
