### ISSUE TITLE
IO traits in v0.3

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2692]
I am opening this issue to have a place to keep track of our plans for the `AsyncRead`/`AsyncWrite` traits in v0.3. Some questions to address:

 - What to do about vectored IO?
 - What to do about io_uring?
 - What to do about the traits from the futures crate?

Related dicussions:

 - Refactor `AsyncBufRead` #2428
 - Technical notes regarding io_uring #2411

Old discussions: #1271, #1272, #1297, #1551

**Comment by carllerche** [comment]
I believe the questions that must be answered by 0.3 have been.

* vectored I/O has been removed from *traits* and will be added back to **structs** at some point in the future.
* `io_uring` -> punt until after 1.0
* I/O traits in the futures crate -> not implement. We are only depending on traits in `std`.

**Comment by carllerche** [comment]
* vectored writes has been brought back, vectored reads can be done in a forwards-compatible way.
* io_uring` support will be added in a forwards-compatible way.
* `std` will not include async I/O traits.

We can close this I think.

**Comment by kaimast** [comment]
> vectored writes has been brought back, vectored reads can be done in a forwards-compatible way.

Where is this now? I cannot find a `write_vectored` or `write_all_vectored` in the `AsyncWriteExt`.

**Comment by Darksonn** [comment]
We have [`poll_write_vectored`][1] on `AsyncWrite`, but there's currently no helper for it on the extension trait.

[1]: https://docs.rs/tokio/1/tokio/io/trait.AsyncWrite.html#method.poll_write_vectored

**Comment by 0x5459** [comment]
> vectored writes has been brought back, vectored reads can be done in a forwards-compatible way.

Please forgive my ignorance, I don't know how to vectored reads in a forwards-compatible way.

**Comment by Darksonn** [comment]
By "forwards-compatible" I mean that it can be added to Tokio in the future.

Tokio doesn't come with helpers for it, but [`async_io`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.async_io) can be used to execute any custom IO operation.
