### ISSUE TITLE
Document missing timer panics

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2696]
We should document somewhere what to do when you encounter panics regarding a missing timer. There are two main situations where this happens:

1. Forgot to use `.enable_all()` on builder.
2. Created timer outside of Tokio, e.g. `rt.block_on(delay_for(...))`

**Comment by Darksonn** [comment]
Reopening as I would like more documentation about this.

**Comment by seunghunee** [comment]
@Darksonn Do we need more documentation?

**Comment by Darksonn** [comment]
I can't think of any. I didn't notice that this issue was linked, and you didn't use a [keyword][1], so it wasn't auto-closed when I merged it.

[1]: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
