### ISSUE TITLE
Be consistent about threaded vs basic scheduler in v0.3

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2698]
Currently `Runtime::new()` and `#[tokio::main]` will make their choice about the kind of runtime by inspecting the `rt-threaded` flag. This should be changed in Tokio v0.3, and code uses `#[tokio::main]` without `rt-threaded` should probably error with a suggestion to enable the feature or to use the basic scheduler.

We should also overhaul the runtime builder.

**Comment by carllerche** [comment]
Superseded by #2698

**Comment by benesch** [comment]
> Superseded by #2698

#2698 is this very issue :D. For posterity, I believe the correct superseding issue is #2720.
