### ISSUE TITLE
Document how to remotely kill child process

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2703]
Add an example that looks roughly like this to the documentation.
```rust
let (send, recv) = oneshot::channel::<()>();

tokio::select! {
    _ = &mut child => {},
    _ = recv => {
        child.kill();
    }
}
```

See more [here](https://github.com/tokio-rs/tokio/pull/2512#issuecomment-663954076).

**Comment by blasrodri** [comment]
Where should this be placed?

**Comment by Darksonn** [comment]
Either on the `tokio::process` module or on `tokio::process::Child`.

**Comment by jakajancar** [comment]
Thanks, was struggling with exactly this and the example is helping already :)
