### ISSUE TITLE
Add opposite of stream_reader

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2705]
The [`tokio::io::stream_reader`][1] adapter allows you to convert a `Stream<Item=Result<Bytes, Error>>` into an `AsyncRead`. I would like to provide an adapter for the opposite conversion as well.

It is currently already possible to do this using
```rust
FramedRead::new(my_async_read, BytesCodec::new()).map_ok(BytesMut::freeze)
```
from `tokio-util`, but this is such a common operation that I think we should provide a dedicated adapter in `tokio::io` as well.

Name suggestion: `stream_chunker`

[1]: https://docs.rs/tokio/0.2/tokio/io/fn.stream_reader.html

**Comment by taiki-e** [comment]
Done in #2714 / #2788. (seems pr to non-default branch doesn't close issue)
