### ISSUE TITLE
API parameters that are asserted to be non-zero should be of type NonZeroUsize or similar.

### ISSUE THREAD

**Issue by khuey** [tokio-rs/tokio#2742]
A number of parameters in various tokio APIs are usizes that must be non-zero, e.g. `core_threads`, `max_threads`, the argument to `mpsc::channel`, etc. The last one tripped me up when porting code because `crossbeam::mpsc::channel(0)` is equivalent to `tokio::mpsc::channel(1)`. This can all be enforced in the type system and be caught at compile time.

**Comment by taiki-e** [comment]
Related: https://github.com/rust-lang/futures-rs/pull/1803, https://github.com/stjepang/async-channel/issues/2

**Comment by khuey** [comment]
Seems that something like rust-lang/rust#69329 would be helpful here then.

**Comment by carllerche** [comment]
`NonZeroUsize` isn't really intended for APIs. It is intended to help the compiler optimize struct layout. It also is not idiomatic Rust.

**Comment by Lucretiel** [comment]
>  It also is not idiomatic Rust.

It's not? I've been more and more using it for this exact purpose, what's wrong with it?
