### ISSUE TITLE
`File` is not following `AsyncWrite` contract

### ISSUE THREAD

**Issue by ktff** [tokio-rs/tokio#2760]
**Version**
Current 0.2.22v

**Platform**
All

**Description**
Contract of `AsyncWrite::poll_shutdown` says

> Invocation of a shutdown implies an invocation of flush

which is not true for `File` https://github.com/tokio-rs/tokio/blob/77e6bb8d066a328cddbde250ad9f79aa2cd60a2d/tokio/src/fs/file.rs#L759-L761

**Comment by carllerche** [comment]
Flush is a noop for files. The contract is respected. If you wish to ensure syncing to disk, you must call the explicit function.

**Comment by carllerche** [comment]
Btw, this has come up a few times. It would be nice if you could submit a PR that explains this in a comment

**Comment by ktff** [comment]
My bad. Yes a comment would be nice, I'll add it.

**Comment by carllerche** [comment]
Masa’s hm

**Comment by carllerche** [comment]
oh
