### ISSUE TITLE
time: Consider renaming `time::{delay_for, delay_until}` to `time::{sleep, sleep_until}`

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tokio#2770]
**Is your feature request related to a problem? Please describe.**
(This is less of a problem and more of a papercut.)

I've noticed that people occasionally don't realize that `tokio::time::delay_for` is equivalent to [`std::thread::sleep`](https://doc.rust-lang.org/stable/std/thread/fn.sleep.html). This manifests as asking in support channels for a `thread::sleep` equivalent or they _use_ `std::thread::sleep`.

**Describe the solution you'd like**
Rename `time::{delay_for, delay_until}` to `time::{sleep, sleep_until}` such that less-experienced Tokio users can more easily find a `std`-equivalent API in Tokio.

**Describe alternatives you've considered**
- Don't do this.

**Comment by Darksonn** [comment]
I think this sounds like a good idea. We have #2589, but it only works when you type `sleep` exactly, and doesn't find it when searching e.g. `slee`.

**Comment by cdmistman** [comment]
`time::{sleep, sleep_until}` could be `#[inline(always)]` that simply call `time::{delay_for, delay_until}` with the same args. This would mean that the new functions are still aliases, except not just for the docs, and fixing the searching issue with docs. This would not be a breaking change to the existing API and wouldn't introduce confusion for current code that depends on those functions.

**Comment by Darksonn** [comment]
The PR was merged. We still need to decide whether we want to backport it.

**Comment by davidbarsky** [comment]
I'd be happy to backport these changes, but I _believe_ that's gated on Carl's release permissions.

**Comment by carllerche** [comment]
Closing this as the backport isn't critical to 0.3. I have no opinion on backporting. If someone wants to do it, go for it :+1:.
