### ISSUE TITLE
examples: Add a `futures::executor::ThreadPool` example

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#2774]
We should include an example in `examples` called `custom-executor` that will show how to use tokio io/timers within a custom executor.

This [gist](https://gist.github.com/LucioFranco/ec8c6617b7193fd062d1ddc32b5bb991) is a good starting point. We likely want to show a couple things:

1) Setting up a tokio runtime that runs on a single thread and is driven without the need to explicitly spawn futures onto it.
2) Show how to "enter" the tokio context on each poll invocation of the custom executor.

**Comment by carlosb1** [comment]
I updated your [example](https://raw.githubusercontent.com/carlosb1/tokio/2774_add_futures_executor_threadpool/examples/custom-executor.rs) (I think correctly), @LucioFranco in my branch, if you think, it is more or less correct I can run the pull request

**Comment by Darksonn** [comment]
Note that an API for this purpose was added to tokio-util [here](https://docs.rs/tokio-util/0.5/tokio_util/context/index.html).

**Comment by carlosb1** [comment]
In fact, how I see, you did an example https://github.com/LucioFranco/tokio-compat-02

**Comment by Darksonn** [comment]
@carlosb1 I'd still like an example on Tokio itself. If you submit a PR (using as much of the tokio-util impl as possible), that would be great.

**Comment by carlosb1** [comment]
Ok! perfect, I refactor a little the code and I commit it..
