### ISSUE TITLE
Typo in tokio::sync::broadcast::Receiver::try_recv docs

### ISSUE THREAD

**Issue by ThatsNoMoon** [tokio-rs/tokio#2781]
The documentation for [tokio::sync::broadcast::Receiver::try_recv](https://github.com/tokio-rs/tokio/blob/c393236dfd12c13e82badd631d3a3a90481c6f95/tokio/src/sync/broadcast.rs#L796) states that `try_recv` has three failure cases compared to `recv`'s one failure case, but `recv` appears to have two failure cases (lagged and closed).

**Comment by Darksonn** [comment]
Ah, that must have been copied from one of the other channels that doesn't have lagged.
