### ISSUE TITLE
docs: incorrect feature requirements for test and main macros

### ISSUE THREAD

**Issue by Riateche** [tokio-rs/tokio#2798]
The documentation for these macros says: ([link](https://docs.rs/tokio/0.2.22/tokio/attr.main.html))

> This is supported on feature="rt-threaded" and feature="macros" only.

But `rt-threaded` is not actually required. `rt-core` is enough.

**Comment by Darksonn** [comment]
This will be fixed by #2720.

**Comment by taiki-e** [comment]
Closing -- fixed: https://docs.rs/tokio/1.4.0/tokio/#attributes
