### ISSUE TITLE
Consider coordinating tokio-io / bytes releases

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#28]
There are pending breaking changes as part of `bytes` that would require bumping tokio-io which would require a breaking tokio change.

**Comment by tailhook** [comment]
What breaking changes are planned? Any pointers?

**Comment by carllerche** [comment]
I haven't made a full inventory of breaking changes yet. Each crate should get a milestone to track.

I don't think that the `bytes` crate has anything major. The biggest is changing some `IntoBuf` impls to get rid of `Cursor`.

`iovec` needs to a breaking change to better address the soundness issue that was discovered and fixed in 0.1.1.

Off the top of my head, I don't *think* that `tokio-io` has any breaking changes itself, but it needs to bump the version since it re-exports `bytes` and `iovec` types.

**Comment by tailhook** [comment]
I also think BufMut should have `put_*` methods documented to grow buffer, as well as the implementation for `BytesMut` (this is a sort of extension to https://github.com/carllerche/bytes/issues/131 which is marked as 0.5-blocker).

**Comment by aturon** [comment]
I put some commentary on blocking 0.1 [here](https://github.com/tokio-rs/tokio/issues/27#issuecomment-342671384).

**Comment by cramertj** [comment]
> Off the top of my head, I don't think that tokio-io has any breaking changes itself,

It'd be nice to have an opportunity to do [this](https://github.com/tokio-rs/tokio-io/issues/83).

**Comment by carllerche** [comment]
I believe that the current plan is to only release tokio 0.1 and then coordinate an ecosystem bump after that.

**Comment by cramertj** [comment]
@carllerche Do you mean `tokio` 0.2?

**Comment by cramertj** [comment]
@carllerche Oh, I see, you mean of the `tokio` crate, not `tokio-core`.
