### ISSUE TITLE
sync: add `mpsc::Sender::closed` future

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#2800]
**Is your feature request related to a problem? Please describe.**
Currently, the `tokio::sync::watch` channel has a [`Sender::closed` async function](https://docs.rs/tokio/0.2.22/tokio/sync/watch/struct.Sender.html#method.closed). This can be awaited in order to notify a task when the receivers of that channel are all closed.

However, the `mpsc` channel's `Sender` type does not currently have such a function. This would be useful to add.

For an example use-case, see https://github.com/linkerd/linkerd2/issues/4926. In essence, the intended use case is to prevent leaks of a task that sends messages over an MPSC channel by ensuring it is woken when the receiver ends of that channel are all gone. Currently, the sender can only become aware of the channel closing _when it actually attempts to send a message_. Although dropping the receivers would wake up the sender task if it is waiting to send a message (in the bounded MPSC), it won't be woken if it is waiting for some other work...but if there are no longer any receivers, that other work may no longer be necessary, and should be cancelled.

If we added a `closed` future, it would be possible to `select` over `closed` and some other work, so that the task is woken when the channel is closed and can proactively cancel itself.

**Describe the solution you'd like**

We should add a `closed` future, like the one on `watch::Sender`.

**Describe alternatives you've considered**
We could, alternatively, not do this. However, there isn't really any other good way to solve the problem that I can think of.

**Additional context**
Somewhat related: #2481

**Comment by taiki-e** [comment]
Closing -- done in #2840
