### ISSUE TITLE
Sink Api

### ISSUE THREAD

**Issue by Future2100** [tokio-rs/tokio#2815]
**Is your feature request related to a problem? Please describe.**
I used Sink to send data to the underlying TCP stream,  the API start_send require an item of sending object.

**Describe the solution you'd like**
I have gone through the API, I think using a ref instead of an item is more efficient.

**Comment by Darksonn** [comment]
The `Sink` trait is not used by the core Tokio crate, although it is in used in `tokio-util`. I assume that you are referring to the codec api from `tokio-util`.

Anyways, since the `Item` can be any type, and since a reference is a type, it should be possible to use a reference as the item type.

**Comment by Future2100** [comment]
@Darksonn you are right, I need to learn how to use it in my scenario.
