### ISSUE TITLE
LengthDelimitedCodec doc or impl error

### ISSUE THREAD

**Issue by nujz** [tokio-rs/tokio#2818]
**Version**
```
> cargo tree | grep tokio
│   ├── tokio v0.2.22
│   │   └── tokio-macros v0.2.5
│   ├── tokio-util v0.3.1
│   │   └── tokio v0.2.22 (*)
├── tokio v0.2.22 (*)
└── tokio-util v0.3.1 (*)
```

**Description**

doc [example-1](https://docs.rs/tokio-util/0.3.1/tokio_util/codec/length_delimited/index.html#example-1):
```
LengthDelimitedCodec::builder()
    .length_field_offset(0) // default value
    .length_field_length(2)
    .length_adjustment(0)   // default value
    .num_skip(0) // Do not strip frame header
    .new_read(io);
```

```
         INPUT                           DECODED
+-- len ---+--- Payload ---+     +-- len ---+--- Payload ---+
| \x00\x0B |  Hello world  | --> | \x00\x0B |  Hello world  |
+----------+---------------+     +----------+---------------+
```

I tried this code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=40736a1bbd2a840da9cb64aaab666e84)):

```rust
use bytes::BufMut;
use tokio::stream::StreamExt;
use tokio_util::codec::LengthDelimitedCodec;

#[tokio::main]
async fn main() {
    let s = "Hello world";

    let mut buf = bytes::BytesMut::default();
    buf.put_uint(s.len() as u64, 2);
    buf.put_slice(s.as_bytes());

    println!("{:?}", buf);

    let mut delimited = LengthDelimitedCodec::builder()
        .length_field_offset(0)
        .length_field_length(2)
        .length_adjustment(0)
        .num_skip(0)
        .new_read(buf.as_ref());

    let res = delimited.next().await.unwrap().unwrap();

    println!("{:?}", res);

    // assert_eq!(buf, res);
}

```

output:
```
b"\0\x0bHello world"
b"\0\x0bHello wor"
```

**Comment by blasrodri** [comment]
@nujz 
The line `buf.put_uint(s.len() as u64, 2);` is causing trouble. If you remove it, it works as advertised.

Try applying this diff:

```diff
index b339f71..14ae7ab 100644
--- a/asd.rust
+++ b/asd.rust.working
@@ -7,7 +7,7 @@ async fn main() {
     let s = "Hello world";
 
     let mut buf = bytes::BytesMut::default();
-    buf.put_uint(s.len() as u64, 2);
+    // buf.put_uint(s.len() as u64, 2);
     buf.put_slice(s.as_bytes());
 
     println!("{:?}", buf);
@@ -23,5 +23,5 @@ async fn main() {
 
     println!("{:?}", res);
 
-    // assert_eq!(buf, res);
+    assert_eq!(buf, res);
 }
```

**Comment by nujz** [comment]
@blasrodri 
Removing the line `buf.put_uint(s.len() as u64, 2);` is causing panic.

**Comment by blasrodri** [comment]
> @blasrodri
> Removing the line `buf.put_uint(s.len() as u64, 2);` is causing panic.

@nujz can you please check https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cec7a97b2c31517c4115585de143d829

**Comment by blasrodri** [comment]
@nujz sorry, it wasn't the right thing to do. I checked it again, but more thoroughly.
There's `.length_adjustment()`, and it's definition says:
> Delta between the payload length specified in the header and the real
> payload length

The payload length is 13, but 11 was specified. Therefore, it needs to be adjusted by +2. And it is done through this function.
You can check that this works [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9481d03ab1fe3f173751ed25fe4b44aa)
The docs should reflect this. Let me know whether you want to make a PR, or I will.

**Comment by blasrodri** [comment]
@Darksonn should we close this?

**Comment by Darksonn** [comment]
I haven't really kept up with it. Was it just a misunderstanding of the docs, or is something wrong in there?

**Comment by blasrodri** [comment]
I think it's well documented.

**Comment by nujz** [comment]
@blasrodri your code is not the same with the code in [example-1](https://docs.rs/tokio-util/0.3.1/tokio_util/codec/length_delimited/index.html#example-1).

> The payload length is 13, but 11 was specified. Therefore, it needs to be adjusted by +2. And it is done through this function.
> You can check that this works [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9481d03ab1fe3f173751ed25fe4b44aa)

There's `.length_adjustment(0)` in doc. But your code is `.length_adjustment(2)`. So there is some different between the doc and impl.

You can check [example-3](https://docs.rs/tokio-util/0.3.1/tokio_util/codec/length_delimited/index.html#example-3). They have the same issue.

**Comment by Darksonn** [comment]
@nujz Can I ask you to open a PR that fixes the issues you see?

**Comment by nujz** [comment]
@Darksonn I'm not sure whether to modify the document or the implemented code. I ran the code in the document and found that the running result was different from the document.

**Comment by blasrodri** [comment]
@nujz I'll update the docs and reference it to you on the PR

**Comment by nujz** [comment]
@blasrodri Thanks.
