### ISSUE TITLE
try_join! does not return early when Err is encountered

### ISSUE THREAD

**Issue by gregdhill** [tokio-rs/tokio#2832]
**Version**
└── tokio v0.2.22
    └── tokio-macros v0.2.5

**Platform**
Linux 5.7.2-arch1-1 x86_64 GNU/Linux

**Description**
Attempting to use the macro `try_join!` to resolve two or more `JoinHandle`s does not return early when an `Err` is encountered.

Example code:
```rust
use std::time::Duration;
use tokio::time::delay_for;

async fn throw_error1() -> Result<(), &'static str> {
    delay_for(Duration::from_millis(100)).await;
    Err("Error1")
}

async fn throw_error2() -> Result<(), &'static str> {
    delay_for(Duration::from_millis(200)).await;
    Err("Error2")
}

#[tokio::main]
async fn main() -> Result<(), ()> {
    match tokio::try_join!(tokio::spawn(throw_error1()), tokio::spawn(throw_error2())) {
        Ok(res) => println!("Ok: {:?}", res),
        Err(e) => panic!("{}", e),
    };
    Ok(())
}
```

I would expect this code to panic on `Error1` but it instead waits for both futures to complete (`Ok((Err("Error1"), Err("Error2"))`).

**Comment by Darksonn** [comment]
The type of `tokio::spawn(throw_error1())` is `Result<Result<(), &'static str>, JoinError>`, and returns `Ok(Err("Error1"))`.

**Comment by gregdhill** [comment]
@Darksonn Is the return type of `tokio::spawn(throw_error1())` not `JoinHandle<Result<(), &'static str>>`? I have the same issue with the following code:

```rust
#[tokio::main]
async fn main() -> Result<(), ()> {
    match tokio::try_join!(
        tokio::spawn(async { throw_error1().await }),
        tokio::spawn(async { throw_error2().await })
    ) {
        Ok(res) => println!("Ok: {:?}", res),
        Err(e) => panic!("{}", e),
    };
    Ok(())
}
```

As described in the [docs](https://docs.rs/tokio/0.2.22/tokio/macro.try_join.html#runtime-characteristics) I believe the code above should panic on `Error1` but it doesn't. Am I missing something?

**Comment by Darksonn** [comment]
Ah, sorry. The thing with type `Result<Result<(), &'static str>, JoinError>` is `tokio::spawn(throw_error1()).await`. Try running the code below:
```rust
use std::time::Duration;
use tokio::time::delay_for;

async fn throw_error1() -> Result<(), &'static str> {
    delay_for(Duration::from_millis(100)).await;
    Err("Error1")
}

#[tokio::main]
async fn main() {
    println!("{}", tokio::spawn(throw_error1()).await.is_ok());
}
```
This [prints true](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2846b34264b592dec5e9d1d30778964b). Try also this:
```rust
#[tokio::main]
async fn main() {
    match tokio::spawn(throw_error1()).await {
        Ok(Ok(())) => println!("a"),
        Ok(Err(_)) => println!("b"),
        Err(_) => println!("c"),
    }
}
```
This [prints `b`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dc94aecce7fee16a6b5f09aae2dc6b3e).

**Comment by gregdhill** [comment]
Ah I see thanks! So is there any way to position `try_join` such that it will throw on the inner `Err`?

**Comment by Darksonn** [comment]
What do you want to happen if you receive a `JoinError`? This happens if the task panics, or the runtime is shut down.

**Comment by gregdhill** [comment]
> Wait on multiple concurrent branches, returning when all branches complete with Ok(_) or on the first Err(_).

Ideally I would like `try_join` to work the same way with green threads (`tokio::spawn`) as it does with async futures.

**Comment by Darksonn** [comment]
The most direct translation is to `unwrap()` the outer result, as it only fails when the task panics.
```rust
#[tokio::main]
async fn main() -> Result<(), ()> {
    let output = tokio::try_join!(
        async { tokio::spawn(throw_error1()).await.unwrap() },
        async { tokio::spawn(throw_error2()).await.unwrap() }
    );
    match output {
        Ok(res) => println!("Ok: {:?}", res),
        Err(e) => panic!("{}", e),
    };
    Ok(())
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ba9817f2acee6c93d2ea4167791aa143)

**Comment by JanisGailis** [comment]
Sorry for reviving this issue.

I agree with @gregdhill that the current behaviour of how `tokio::spawn` and `try_join!` interact is pretty counterintuitive. The [docs](https://docs.rs/tokio/0.3.5/tokio/macro.try_join.html#runtime-characteristics) explicitly warn users that using `try_join!` on a bunch of futures will ensure concurrency, but not parallelization, and that one should use `tokio::spawn` and pass the handle to `try_join!` if one needs parallelization.

But when you actually do this, the behaviour of `try_join!` becomes more like that of `join!`. In essence you wait until all of the futures finish with a `Result`, and only then you have the chance to propagate the errors further. Which is really not what you'd be aiming for if you were trying to use `try_join!` in the first place. Especially in case of long-running tasks.

Adding one possible solution for other people potentially struggling with this that doesn't involve `unwrap`:
```rust
use std::time::Duration;
use std::pin::Pin;
use futures::Future;
use tokio::time::sleep;
use anyhow::{anyhow, Result};

async fn throw_error1() -> Result<()> {
    sleep(Duration::from_millis(100)).await;
    Err(anyhow!("Error1"))
}

async fn throw_error2() -> Result<()> {
    sleep(Duration::from_millis(200)).await;
    Err(anyhow!("Error2"))
}

#[tokio::main]
async fn main() -> Result<(), ()> {
    let output = tokio::try_join!(
        spawn_fallible(Box::pin(throw_error1())),
        spawn_fallible(Box::pin(throw_error2())),
    );
    match output {
        Ok(res) => println!("Ok: {:?}", res),
        Err(e) => panic!("{}", e),
    };
    Ok(())
}

async fn spawn_fallible<T>(task: Pin<Box<T>>) -> Result<()>
where
    T: Future<Output = Result<()>> + Send + 'static,
{
    tokio::spawn(task).await??;
    Ok(())
}

```

**Comment by Darksonn** [comment]
Note that the `Box::pin` calls in the above snippet is completely unnecessary.

**Comment by JanisGailis** [comment]
You're right!

I have them in the function signature, as the particular real life futures I have to deal with needed the pinned boxes due to `!Send` values.

**Comment by Darksonn** [comment]
A pinned box changes nothing with regards to `!Send` values. Did you mean `!Unpin`? Even then, it is ok to move `!Unpin` futures until their first poll, so it should still be ok without a box.

**Comment by JanisGailis** [comment]
Yeah, just tried actually removing the boxes, and it's fine. Thanks! 
I'll edit the snippet as well.

**Comment by Jimmy-Z** [comment]
I just found out about this, thanks @Darksonn for the explanation, but I think the document should be updated to warn user about this.
