### ISSUE TITLE
FR: tokio::stream::extend

### ISSUE THREAD

**Issue by elbaro** [tokio-rs/tokio#2842]
```
let mut a = Vec::new();
let b = get_stream();
tokio::stream::extend(&mut a, b).await;
```

**Comment by carllerche** [comment]
I'm going to close this due to inactivity and a lack of detail.

If this feature is still needed, I would recommend writing a more detailed proposal such that a contributor is able to understand the requirements and provide a PR.

**Comment by elbaro** [comment]
#3010 is waiting for review.

`tokio::stream::extend` is a handy function for a case where you want `Vec::extend(items)` but items are prepared asynchronously. The interface would be `Vec::extend_with_stream(..)` or `tokio::stream::extend`. `async-std` has this [one](https://docs.rs/async-std/1.7.0/async_std/stream/fn.extend.html). I found myself using this pattern a lot to make a sync point and collect the results, but I don't know this is a common pattern for others.
