### ISSUE TITLE
RwLock: Recursive reads cause deadlock

### ISSUE THREAD

**Issue by librelois** [tokio-rs/tokio#2849]
**Version**
tokio v0.2.22
tokio-macros v0.2.5

**Platform**
`Linux N13-N140ZU 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description**
If a user does a recursive read while a writer has requested the lock, it causes a deadlock. 
The documentation does not indicate that recursive reads are not supported.
If this is intentional it should be pointed out in the documentation for the RwLock type and the read() method.

Minimal test to reproduce the deadlock :

```rust
#[tokio::test]
    async fn recursive_read_lock() {
        let mutex = Arc::new(tokio::sync::RwLock::new(0));
        let read1 = mutex.read().await;

        let mutex2 = mutex.clone();
        let task = tokio::spawn(async move {
            let mut write = mutex2.write().await;
            *write += 1;
        });

        tokio::time::delay_for(Duration::from_millis(200)).await;

        let read2 = mutex.read().await; // Await forever here

        drop(read1);
        drop(read2);
        task.await.expect("task panicked or cancelled");
        assert_eq!(1, *(mutex.read().await));
    }
```

I expected to see this happen: test pass

Instead, this happened: test never finish

**Comment by Darksonn** [comment]
This is due to the fairness of `RwLock`.

> The priority policy of Tokio's read-write lock is _fair_ (or [_write-preferring_]), in order to ensure that readers cannot starve writers. Fairness is ensured using a first-in, first-out queue for the tasks awaiting the lock; if a task that wishes to acquire the write lock is at the head of the queue, read locks will not be given out until the write lock has been released. This is in contrast to the Rust standard library's `std::sync::RwLock`, where the priority policy is dependent on the operating system's implementation.
>
> [`RwLock` documentation][1]

[_write-preferring_]: https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock#Priority_policies
[1]: https://docs.rs/tokio/0.2.22/tokio/sync/struct.RwLock.html

**Comment by librelois** [comment]
> I don't think it's possible to do anything about this while maintaining fairness

Yes the `parking_lot` developers came to the same conclusion: 

https://docs.rs/lock_api/0.4.1/lock_api/struct.RwLock.html#method.read_recursive

> Unlike read, this method is guaranteed to succeed without blocking if another read lock is held at the time of the call. This allows a thread to recursively lock a RwLock. However using this method can cause writers to starve since readers no longer block if a writer is waiting for the lock.

And they specify that the `read` method can deadlock in case of recursive read: 

> Note that attempts to recursively acquire a read lock on a RwLock when the current thread already holds one may result in a deadlock.

https://docs.rs/lock_api/0.4.1/lock_api/struct.RwLock.html#method.read

> but I am certainly open to documenting this issue better.

Yes, that's what this issue is all about: documenting which uses can cause a deadlock (without unsafe block) so that the user is well aware of what not to do (personally it would have saved me a lot of debugging time).

**Comment by Hodkinson** [comment]
#3389 addresses this

**Comment by davidpdrsn** [comment]
Closing since the docs were updated to mention this in https://github.com/tokio-rs/tokio/pull/3389 and no other solutions seem viable.

**Comment by rubdos** [comment]
> > I don't think it's possible to do anything about this while maintaining fairness
> 
> Yes the `parking_lot` developers came to the same conclusion:
> 
> https://docs.rs/lock_api/0.4.1/lock_api/struct.RwLock.html#method.read_recursive

I wonder though, is it not possible to detect that a `read` was made on a task that already holds a `read`, detect the possible deadlock, and give preference to the current task? This would be a kind of `ReentrantRwLock`. I'm just hand waving here, I truly wonder whether it's possible. Should I open a new issue for discussion?

**Comment by Darksonn** [comment]
"Task" is a more fluid concept than thread, so you would run into some issues. It is plausible that you could do something with Tokio's task-local, but it would have weird behavior in various cases. For example, what if you move the guard from one task to another? What if you have a `FuturesUnordered` in the task, essentially running a large number of tasks in one?

**Comment by rubdos** [comment]
Thanks for still coming back to this :-)

> For example, what if you move the guard from one task to another? What if you have a `FuturesUnordered` in the task, essentially running a large number of tasks in one?

Yes, I figured those two would be problems. I wonder whether there's no other primitive that would be both fair, and protect against this kind of dead locks. `RwLock` seems most suitable for a system of reader-tasks and writer-tasks now.

**Comment by Darksonn** [comment]
In principle you could have a `read` method that bypasses the fairness, but I don't think this is great. In general, I'm not sure I would want our lock to support recursive reads.
