### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [tokio-rs/tokio#2850]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/tokio-rs/tokio/blob/77e6bb8d066a328cddbde250ad9f79aa2cd60a2d/.github/workflows/ci.yml#L113
This should now be `cargo miri test --features rt-core,rt-threaded,rt-util,sync task`.

**Comment by Darksonn** [comment]
Thanks!
