### ISSUE TITLE
io: investigate removing io-driver & io-readiness feature flags from Cargo.toml

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2869]
PR #2828 added two internal feature flags. This was done to simplify the conditional compilation. Unfortunately, this can be accessed externally. It would be worth spending a moment to see if those can be removed.

**Comment by ipetkov** [comment]
@seanmonstar I see that the `io-driver` feature is now considered internal-only, but it used to guard things like `runtime::Builder::enable_io()`. Just wanted to check, do we intend for public io types to always get compiled in?

**Comment by seanmonstar** [comment]
Things like `enable_io` should now be enabled only if one of the features that *uses* the IO driver is enabled, like `tcp`, `udp`, etc.

**Comment by ipetkov** [comment]
Makes sense, in that case we probably won't have a singular feature name for docs.rs (e.g. "this method is only available under X feature")?

**Comment by seanmonstar** [comment]
True, documenting it will be uglier... :(
