### ISSUE TITLE
stream: coordinating Tokio 1.0 with the availability of Stream in std

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2870]
Currently, Tokio uses the `Stream` trait provided by `futures-core`. There is an ongoing [effort](https://github.com/rust-lang/wg-async-foundations/blob/master/rfc-drafts/stream.md) to define a `Stream` trait within std. Tokio is currently aiming to release 1.0 by the end of the year. Given the Rust release cadence, `Stream` may not be available in `std` on the stable channel by the end of the year.

If `Stream` is not available on the Rust stable channel by the end of the year, we have two options.

1. Delay Tokio 1.0 until `Stream` becomes available in std.
2. Remove `Stream` usage from Tokio until 6 months after it becomes available in `std` (due to the proposed MSRV policy).

## Stream usage

Currently, `Stream` is implemented in Tokio by:

* `mpsc::Receiver`
* `broadcast::Receiver`
* `signal::Signal`

Tokio also provides a `tokio::stream` module containing a number of useful stream utilities. A list can be found [here](https://docs.rs/tokio/0.2.22/tokio/stream/index.html).

## Removing the `Stream` dependency

If `Stream` is removed from the `tokio` crate, it can be placed temporarily in the `tokio-util` crate. This crate is not intended to reach 1.0 by the end of year. `Stream` usage within Tokio is already isolated via the `stream` feature flag. While useful, it is not a critical dependency.

Removing `Stream` from `tokio` would impact the discoverability of the utilities. This could be mitigated by including an empty `tokio::stream` module with documentation explaining where to find the utilities.

## Adding `Stream` post 1.0

Adding `Stream` after an initial 1.0 release would take at least 6 months given the currently proposed MSRV policy (#2718). According to the policy, 1.x releases are permitted to increase the MSRV, but **must support all Rust versions released in the past 6 months**.

## Next steps

I will leave this open-ended for now as we collect comments. We can then decide on the direction we want to take.

**Comment by sfackler** [comment]
I don't know what the current thought is, but there was an idea that the futures crate could start transparently reexporting std's Stream when being built against a suitable version to avoid forcing a big migration.

**Comment by taiki-e** [comment]
See also https://github.com/rust-lang/futures-rs/issues/2207

**Comment by carllerche** [comment]
@taiki-e thanks for that. My understanding is that it would still technically be a breaking change. My gut is that I would rather start a 1.0 stability guarantee on strong footing.

**Comment by davidbarsky** [comment]
For exhaustiveness, I think there that there's a third option: a six month MSRV policy can take effect _well_ after a 1.0 is released. I'm not convinced that a Tokio 1.0 release needs to be coupled to a six month MSRV policy _at release_. This is something that can be added retroactively.

**Comment by taiki-e** [comment]
@carllerche Yeah, that's technically breaking change. AFAIK, theoretically, if the signature of the std Stream trait doesn't change, and the build script works, and the user doesn't accidentally rely on the *unstable* Stream trait (that requires`#![feature]`), no breakage will occur. But, in any case, when defining `Stream` in `futures_core`, the risk cannot be zero.

FYI: I've created a demo of how that's implemented: https://github.com/taiki-e/futures-compat-experiment

**Comment by taiki-e** [comment]
Perhaps another idea for this would be to use a (disabled by default) feature flag that includes the version number: like `stream03`, `stream1`. 
(Once std `Stream` is stable, make the `stream1` feature to no-op and always implement the stream from `futures_core`. If the implementation of `futures_core`'s `Stream` is different from std's `Stream`, we can implement std's `Stream` directly as they don't conflict.)

**Comment by Keruspe** [comment]
Related: https://github.com/rust-lang/rust/pull/79023

**Comment by carllerche** [comment]
As of this comment, [`Stream` trait RFC](https://github.com/rust-lang/rfcs/pull/2996) is not yet merged. I expect it is mostly ready to go, but I am not exactly clear on the expected timeline.

If `Stream` lands in stable sometime in January 2021, I think we could consider delaying the 1.0 release, but probably not more than that. However, I would expect `Stream` to not be available in std until later.

Assuming that `Stream` lands in stable February 2021 or later, I propose:

* Extract the contents of `tokio::stream` into the `tokio-stream` crate.
* Leave an empty `tokio::stream` module documenting that `Stream` utilities exist in `tokio-stream` and will be merged back into `tokio` once the `Stream` trait lands in `std`.
* Remove `Stream` impls for misc types and document how to use `async-stream` to get your own stream implementation. These types already have inherent fns to consume and do not depend on their `Stream` implementations.
   * `tokio::fs::ReadDir`
   * `tokio::io::Lines`
   * `tokio::net::{TcpListener, UnixListener}`
   * `tokio::signal::{CtrlC, CtrlBreak}`
   * `tokio::sync::broadcast`
   * `tokio::time::Interval`

Once `Stream` lands in `std`, we add `tokio::stream` back. However, we must do this in a way that preserves the Tokio's MSRV guarantee of ~6 months. To do this, we can add a build script that detects the Rust version. If using a version of Rust that includes `Stream`, then re-export that `Stream` and use it. Otherwise, define a  `Stream` trait that matches the version in `std` and use that one. This is a similar strategy as the one proposed for [`futures-rs`](https://github.com/rust-lang/futures-rs/issues/2207) but does not introduce `Stream` until **after** `Stream` is in the `std` stable channel. This prevents potential breaking changes with mismatched `Stream` versions

**Comment by carllerche** [comment]
The stream::Iter utility uses the coop helper which is not public. Instead, we could hard limit the number of items returned to 32 then yield. It is not ideal but is temporary. 

cc @LucioFranco
