### ISSUE TITLE
No way to get current value of `Now` from Timer?

### ISSUE THREAD

**Issue by jsgf** [tokio-rs/tokio#288]
The tokio-timer `Timer` type doesn't seem to have a way to get access to its source of "now", which is necessary to construct future relative times. One option is to assume that `Instant::now()` always returns a useful time, but it's not clear to me that it is guaranteed to have the same timebase/clock source.

Alternatively I could make my own instance of `SystemNow`, but the `Timer` might have been constructed with a different now.

It seems to me that `Timer` should have a `fn current_now(&self) -> &N` method so that users can use the same timebase that it is using internally.

**Comment by jsgf** [comment]
Though the `Now` trait's use of `&mut self` for `now()` makes that pretty awkward.

**Comment by carllerche** [comment]
Timer could have a now fn with &mut. Does that work?

**Comment by jsgf** [comment]
Hm, if the intent of the design is that there's a single `Timer` instance that's shared among multiple threads, and its `timer::Handle` that you do all your interactions through, then I think it would need to be on `Handle`. Otherwise you wouldn't be able to call a `fn now(&mut self)` method on a `Timer` in another thread (or at least wrap it in a `Mutex` or something, which seems suboptimal).

I'm curious about what implementations of `Now::now` actually need `&mut self`? `SystemNow` doesn't, but presumably you have another implementation which does?

**Comment by carllerche** [comment]
A mocked timer or any impl that attempts to keep in sync across nodes.

That said, it probably would be worth including `now` on `Handle`, but as you pointed out that will be difficult with `&mut self`. Another difficulty is that I would rather avoid adding a generic to `Handle`. Also, if `Handle` had `now()` that would add a `Sync` requirement to `T: Now`.

Another option (though probably less ideal) is that `Handle` has access to the last `Instant` that the `Timer` observed. So, whenever `Timer` calls `now` it updates a value... It probably isn't a great idea to assume that this value is current though...

**Comment by jsgf** [comment]
The main problem is how to implement "in 31ms". In the old API, `sleep()` was relative, but now `delay()` is absolute. I think that's a good idea for a time API, but it does mean you need to be able to express "now + 31ms" where "now" is reasonably precise.

**Comment by jsgf** [comment]
> A mocked timer or any impl that attempts to keep in sync across nodes.

It seems to me that they're both unusual enough that they could cope with interior mutability. What do you mean by "node" here? Do you mean cross-machine NTP-like timesync?

**Comment by carllerche** [comment]
I'm pretty sure this would be a breaking change, so I will flag it as such.

**Comment by olix0r** [comment]
https://github.com/tokio-rs/tokio/pull/368 is related to this, though I think that this time sourcing needs to be _independent_ of timer in some way so that multiple modules that rely on the same time source can be tested.

> Alternately, we may want to consider a system that allows a time source to be loaded contextually (i.e. as is done for the current reactor) to avoid promulgating N: Now generic bounds. (they spread quickly). Ideally, we feed this all back into std so that Instant::now honors alternate time sources, so that underlying libs need not use tokio's time system.

This is important when, for instance, we have a module that measures latency and a module that enforces timeouts. If I want to test these modules together, I don't want to have to make the latency module aware of timers...

**Comment by carllerche** [comment]
You want to take a look at #381? That PR would resolve this issue w/o requiring a breaking release.

**Comment by carllerche** [comment]
Is this issue solved w/ the introduction of `clock::now()`?

**Comment by carllerche** [comment]
I believe this is solved w/ `clock::now()`. I am closing this issue. Please comment if this is incorrect.
