### ISSUE TITLE
Fully seal ToSocketAddrs

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tokio#2891]
Currently the `ToSocketAddrs` trait is meant only for bounds, and all methods are supposed to be implementation details. This is done by putting them methods on "private" super trait. However, due to the way bounds on generics works, these methods are accidentally available to users.

```rust
fn bound<T: ToSocketAddrs>(t: T) {
    // But legal here, since T: ToSocketAddrs leaks the super trait methods
    t.to_socket_addrs();
}

fn main() {
    // Uncomment to see error
    //"127.0.0.1:0".to_socket_addrs();
    bound("127.0.0.1:0");
}
```

The solution is to define a private `Internal` argument type that must also be passed, so a user will see a compilation error when trying to call `t.to_socket_addrs()`, since they didn't call `t.to_socket_addrs(Internal)`, and can't!

**Comment by taiki-e** [comment]
Probably `FromStream` has the same issue.
