### ISSUE TITLE
net: possible race during I/O driver shutdown

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#2924]
When shutting down the I/O driver, all existing I/O resources should be notified and all subsequent operations error. Any attempt to create a new I/O resource should fail.

There currently is some logic to handle this, but after a quick skim, I believe it may be racy. When polling an I/O resource, first the handle is checked to see if a strong reference to the I/O driver still exists. If one does not, the I/O resource assumes the I/O driver is gone. When the I/O driver shuts down, it wakes all associated I/O resources.

I wonder if an I/O resource is added **during** the shutdown process if it will get notified of the shutdown or if it will hang indefinitely. I also wonder if the Arc is correctly dropped before the I/O resources are notified.

Ref: https://github.com/tokio-rs/tokio/pull/2919/files#r501433182

**Comment by zaharidichev** [comment]
Is someone taking a look at that? Can I ?

**Comment by Darksonn** [comment]
Please do!

**Comment by bdonlan** [comment]
I independently discovered this as part of work in #2903; there's also another related race where a readiness future can be created after notifications fire off (but before the `Weak<Inner>` becomes non-upgradable). I'll have a different fix for both in my AsyncFd branch shortly.

**Comment by bdonlan** [comment]
@zaharidichev FYI

**Comment by zaharidichev** [comment]
@bdonlan makes sense. I will close my PR in favor of yours then
