### ISSUE TITLE
Document mocking time in tokio-timer

### ISSUE THREAD

**Issue by Michael-F-Bryan** [tokio-rs/tokio#295]
How would one go about mocking the system's "sense of time" used in `tokio_timer::timer::Timer`?

It's pretty common to swap out the system clock with something else for running tests and simulating real operation at an accelerated rate. What would I need to do to mock the default `Timer` used by `tokio-timer` when we don't want to run at real time?

I'd be happy to add alternate implementations of `tokio_timer::timer::Now` to the `tokio-timer` crate for others to use, I just need some direction and maybe a bit of help understanding how timers interact with the system under the hood.

cc: #127

**Comment by carllerche** [comment]
This relates to #381.

**Comment by carllerche** [comment]
I'm going to roll this up with #1175.
