### ISSUE TITLE
Is the shutdown impl of File incorrect?

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#2950]
Consider the following snippet from the `AsyncWrite` impl for `tokio::fs::File`.

https://github.com/tokio-rs/tokio/blob/24d0a0cfa8916eaef17f40f044d978aa3904d654/tokio/src/fs/file.rs#L680-L688

However the `AsyncWrite` trait contains the following snippet:

> Invocation of a shutdown implies an invocation of flush. Once this method returns Ready it implies that a flush successfully happened before the shutdown happened. That is, callers don't need to call flush before calling shutdown. They can rely that by calling shutdown any pending buffered data will be written out.

This is clearly not the case above.

**Comment by carllerche** [comment]
Looks highly suspect to me.

**Comment by zaharidichev** [comment]
for reference: #2761 and #2760

**Comment by Darksonn** [comment]
The conclusion here is to replace `poll_shutdown` with the following:
```rust
fn poll_shutdown(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), io::Error>> {
    self.poll_flush(self, cx)
}
```
