### ISSUE TITLE
Tokio 0.3 compatibility with hyper server

### ISSUE THREAD

**Issue by ancwrd1** [tokio-rs/tokio#2977]
**Version**
Latest 0.3

**Platform**
Linux generic 5.8.14 x86_64

**Description**
According to the documentation the tokio-compat-02 should provide a way to bridge between the 0.2-based crates and  the 0.3 runtime. When trying to use it with `hyper` server code it panics on the try_bind operation. It's not very clear how to use the `.compat()` call in this case because try_bind is not an asynchronous operation.

Code snippet:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn error::Error>> {
        ...
        let server = Server::try_bind(&address)?;
        ...
}
```

It panics on `try_bind` with this:

```text
'there is no reactor running, must be called from the context of Tokio runtime'
```

**Comment by Darksonn** [comment]
Try one of these:
```rust
let server = async { Server::try_bind(&address) }.compat().await?;
```
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn error::Error>> {
    real_main().compat().await
}
async fn real_main() -> Result<(), Box<dyn error::Error>> {
        ...
        let server = Server::try_bind(&address)?;
        ...
}
```
Note that you will be able to use both Tokio 0.2 and 0.3 inside the compat region, so there's no issue with Tokio 0.3 becoming unavailable.

**Comment by ancwrd1** [comment]
Thanks a lot for your reply, it works indeed. I think it could be worth noting in the documentation or providing an example.

**Comment by Darksonn** [comment]
Documenting this is certainly on my todo-list. I plan to do so tomorrow.
