### ISSUE TITLE
Client TcpStream has no response after server termination

### ISSUE THREAD

**Issue by xutianyi1999** [tokio-rs/tokio#2982]
**Version**
└── tokio v0.3.0
    ├── tokio-macros v0.3.0

**Platform**
64-bit (Windows)

**Description**
The client did not receive the end message or error after the TCP server process terminated

```rust
async fn server() -> Result<()> {
  let mut listener = TcpListener::bind("127.0.0.1:12345").await?;

  while let Ok((_, addr)) = listener.accept().await {
    println!("{:?} connected", addr);
    loop{};
  }
  Ok(())
}

async fn client() -> Result<()> {
  let mut socket = TcpStream::connect("127.0.0.1:12345").await?;
  let mut buff = [0u8; 1024];

  let n = socket.read(&mut buff).await?;
  println!("{}", n);
  println!("disconnect");
  Ok(())
}
```

**Comment by Darksonn** [comment]
Can you provide more details? I tried running the following two programs:
```rust
use tokio::io::{Result, AsyncReadExt};
use tokio::net::TcpStream;

async fn client() -> Result<()> {
  let mut socket = TcpStream::connect("127.0.0.1:12345").await?;
  let mut buff = [0u8; 1024];

  let n = socket.read(&mut buff).await?;
  println!("{}", n);
  println!("disconnect");
  Ok(())
}


#[tokio::main]
async fn main() {
    client().await.unwrap();
}
```
```rust
use tokio::io::Result;
use tokio::net::TcpListener;

async fn server() -> Result<()> {
  let mut listener = TcpListener::bind("127.0.0.1:12345").await?;

  while let Ok((_, addr)) = listener.accept().await {
    println!("{:?} connected", addr);
    loop{};
  }
  Ok(())
}

#[tokio::main]
async fn main() {
    server().await.unwrap();
}
```
and on my (Linux) machine, the client did disconnect once I killed the server process. Did you do something different from this?

**Comment by xutianyi1999** [comment]
After I tested it on linux, the client ended normally, on windows I killed the server, the connection has been released, but the client is still stuck in socket.read()

**Comment by carllerche** [comment]
Ok, I have identified [this](https://github.com/tokio-rs/mio/blob/872ceda1636a06ff40552078a4cfd4ae8e6a7be0/src/sys/windows/selector.rs#L230-L237) section as suspect.

It looks like `AFD_POLL_ABORT` gets **unset** when the socket connects (becomes writable). Ensuring it `AFD_POLL_ABORT` remains set fixes the repro.
