### ISSUE TITLE
#[cargo::test] macro not working in tokio 0.3

### ISSUE THREAD

**Issue by abreis** [tokio-rs/tokio#2995]
I just migrated a code base to tokio 0.3 and async tests tagged with `#[tokio::test]` now panic with one of:  
> panicked at 'there is no timer running, must be called from the context of Tokio runtime'

> panicked at 'not currently running on the Tokio runtime.'

My `Cargo.toml` [dependencies] is:
> tokio = { version = "0.3", features = ["rt-multi-thread", "time", "macros", "signal"] }

and we have no [dev-dependencies].

Reverting to tokio 0.2 makes async tests work again.

**Comment by abreis** [comment]
On further inspection it looks like I have both `tokio-macros` v0.2.5 and 0.3.0 being pulled, the 0.2 version coming from a dependency of a dependency.

I guess this is not a tokio issue then, just a dependency mismatch. Thanks!

**Comment by UkonnRa** [comment]
Well, I know it's a dependency issue, but is there any way to walkaround? Say I am using tokio 0.3, but mongodb-rs is still using 0.2. I want to use mongodb with 0.3. Any advice?

**Comment by Darksonn** [comment]
@UkonnRa For using Tokio 0.2 libraries with Tokio 0.3, check out the [Compatibility between 0.2 and 0.3][1] section in the release announcement. The compatibility layer should work in tests too.

[1]: https://tokio.rs/blog/2020-10-tokio-0-3#compatibility-between-02-and-03
