### ISSUE TITLE
Properly document how to find the number of bytes read by poll_read

### ISSUE THREAD

**Issue by valff** [tokio-rs/tokio#2999]
One of the breaking changes to the `AsycRead` trait was changing the return type from `Result<usize>` to `Result<()>`, but the documentation wasn't changed and still contains the following:

> `Poll::Ready(Ok(n))` means that n bytes of data was immediately read and placed into the output buffer, where `n` == 0 implies that EOF has been reached.

[docs.rs](https://docs.rs/tokio/0.3.0/tokio/io/trait.AsyncRead.html)

As `poll_read` no longer returns the number of bytes read, what is the way to know if EOF has been reached?

**Comment by Darksonn** [comment]
Thank you for the question. The number of bytes read by a read operation is denoted by the increase in the length of [`ReadBuf::filled`][1]. Additionally, if the `ReadBuf` has just been created with `ReadBuf::new` or `ReadBuf::uninit`, the number of filled bytes would initially be zero, so the number of bytes read would be `read_buf.filled().len()`.

You have reached EOF when the number of filled stays unchanged by a successful read.

I have marked this as a question and `E-help-wanted` as this is a common question and something we need to document better.

[1]: https://docs.rs/tokio/0.3/tokio/io/struct.ReadBuf.html#method.filled

**Comment by valff** [comment]
Thanks, makes sense.
