### ISSUE TITLE
Support custom async I/O operations

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/tokio#3000]
**Is your feature request related to a problem? Please describe.**
Some applications benefit from nonstandard I/O primitives such as `sendmmsg` and use of control messages/ancillary data to access advanced platform-specific features like explicit congestion notification flags and segmentation offloading of UDP packets. These aren't supported by tokio, and are sufficiently niche and diverse that built=in support for every possibility may not be feasible. In 0.2, `PollEvented` made this possible, but it has been removed.

**Describe the solution you'd like**
Something analogous to `PollEvented` supported on every target platform, allowing arbitrary async calls into the OS to be used.

**Comment by Ralith** [comment]
Per discussion in chat, a simple minimal solution would be `poll_read_ready`/`poll_write_ready` methods on `UdpSocket` and any other primitives of interest, at least for applications which only need weird operations on the usual primitives.

**Comment by carllerche** [comment]
As the solution is to expose readiness on the socket types, I will close this as a dup of #2968
