### ISSUE TITLE
chore: add stress tests to CI

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3022]
We should add some full feature stress tests in CI that run under valgrind or other tools to catch memory issues.

For example, we could setup an echo client / server running on separate runtimes but within the same process and send a few MB.

**Comment by carlosb1** [comment]
Which it could be the next step / action point for this? is it necessary some valgrind library for rust / cargo or should it be some call outside cargo commands?  I see .cirrus.yml is the place to add this "extra" step, It doesn't seem difficult if our output is a report.
