### ISSUE TITLE
macros: add a way to get the runtime from the body we launch

### ISSUE THREAD

**Issue by Keruspe** [tokio-rs/tokio#3026]
As said in #2965 we're now supposed to use an Arc<Runtime> and pass it around instead of calling `Handle::current()`.

While this can be achieved when creating the Runtime manually, it's not possible when using `#[tokio::main]` as the Runtime isn't passed to the main body.

There should be a way to access it either through an argument, a local variable or a static one.

**Comment by carllerche** [comment]
Closing as a dup of #2965. We can bring back a handle type.
