### ISSUE TITLE
tokio 0.2 connect_std function behaves a bit wrong on windows

### ISSUE THREAD

**Issue by driftluo** [tokio-rs/tokio#3030]
version: win10 10.0.19041.264

Although this is a doc hidden function, I still want to submit this bug, and in 0.3, using `socket2` + `TcpSocket` does not have this problem

code:
```
use socket2::{Domain, Protocol as SocketProtocol, Socket, Type};
use tokio::net::TcpStream;
use std::net::SocketAddr;

fn main() {
    let socket = Socket::new(Domain::ipv4(), Type::stream(), Some(SocketProtocol::tcp())).unwrap();
    let addr = "127.0.0.1:1337".parse::<SocketAddr>().unwrap();
    let bind_addr = "127.0.0.1:1339".parse::<SocketAddr>().unwrap();

    // socket.set_reuse_address(true).unwrap();    /// number 1
    // socket.bind(&bind_addr.into()).unwrap();      /// number 2

    let mut rt = tokio::runtime::Runtime::new().unwrap();
    rt.block_on(async {
        TcpStream::connect_std(socket.into_tcp_stream(), &addr).await
    }).unwrap();
}
```

Run the code as above, it will report an error: `Os {code: 10022, kind: InvalidInput, message: "An invalid parameter was provided." }`

if uncomment the comment at number 1, and the error remains
if uncomment the comment at number 1 and 2, and it can run normally

**Comment by carllerche** [comment]
There isn't much that we can do here. It is a fundamental problem w/ the internal windows implementation of `TcpSocket`.

This is fixed on 0.3, so I am going to close as there isn't a way to backport the fix.
