### ISSUE TITLE
Add a to_std method for tokio's TcpStream

### ISSUE THREAD

**Issue by Daksh14** [tokio-rs/tokio#3031]
**Is your feature request related to a problem? Please describe.**
Cannot convert from a tokio TcpStream to a std one which allows the conversion to a socket2 socket which allows editing various params for a TcpStream

**Describe the solution you'd like**
Implement a `to_std` method for tokio's TcpStream. 

**Describe alternatives you've considered**
None considered

**Additional context**
None provided

**Comment by carllerche** [comment]
It should be possible to impl `TryFrom` to convert between the two. We also could probably provide `as_std(&self) -> &TcpStream`.

I would be interested to hear what others think. cc @tokio-rs/maintainers

**Comment by Darksonn** [comment]
Is the conversion fallible?

**Comment by carllerche** [comment]
Converting will require deregistering, which could fail.

**Comment by Darksonn** [comment]
I do think that a conversion is valuable. The `as_std` you proposed would also be neat.

**Comment by mariusmuja** [comment]
The absence of a way to convert from tokio TcpStream to std TcpStream is preventing me from updating from tokio 0.2 to 0.3.

In my use case, I have a custom TcpStream that also reads RX timestamps from the socket in addition to the payload. I can use `AsyncFd`, however I need to convert from a `tokio::net::TcpStream` (received from a `tokio::net::TcpListener`) to `AsyncFd<std::net::TcpStream>` and as far as I can tell there is no way of extracting the `std::net::TcpStream` and de-registering. I could write a custom `TcpListener` I guess, but I would be great if tokio's `TcpStream` had an `into_std(self)` or a `TryFrom` was available.

**Comment by liufuyang** [comment]
Maybe I can help on this? Even though I don't have much `TcpStream` knowledge yet but I'd love to help and learn :)

**Comment by carlosb1** [comment]
I was checking and I want to be sure... I see that the tcpStream is mapped in the mio library... should it  extract the object from there and expose?

**Comment by Darksonn** [comment]
Yeah, it should take out the mio `TcpStream` then convert it (possibly through `IntoRawFd` if necessary).
