### ISSUE TITLE
Change mentions of net2

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3034]
The `net2` crate is deprecated, so our documentation should recommend another crate. One such mention can be found here:

https://github.com/tokio-rs/tokio/blob/ce173fdc918c5934561560a97d366fce6edb36d0/tokio/src/net/udp/socket.rs#L168-L170

I have not checked whether there are other mentions than the one above.

**Comment by zaharidichev** [comment]
I will take that
