### ISSUE TITLE
io: consider changing ReadBuf to return UninitSlice instead of MaybeUninit<u8>

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3036]
The ReadBuf::unfilled_mut fn uses MaybeUninit. While an unsafe fn to return MaybeUnint is sound, maybe we should consider leveraging the UninitSlice type provided by the bytes crate.

**Comment by seanmonstar** [comment]
What the benefit of doing that for `ReadBuf`? There already methods on `ReadBuf` to fill in the bytes, so the only purpose of `ReadBuf::unfilled_mut()` is to get a slice that we can pass to be filled by something like a syscall. Otherwise, we'd just pass `ReadBuf` directly...

**Comment by carllerche** [comment]
Mostly to match `BufMut` for consistency. It isn't a critical change.

**Comment by carllerche** [comment]
I vote to close this with "won't fix".

**Comment by Darksonn** [comment]
I agree this doesn't bring much value.
