### ISSUE TITLE
0.3 removed tokio::io::Registration, breaking dbus-tokio crate

### ISSUE THREAD

**Issue by diwic** [tokio-rs/tokio#3040]
Hi,

It looks like all possibilities to add a custom fd have been removed with Tokio 0.3, or possibly it has been moved to somewhere I can't find it. In Tokio 0.2 we used `tokio::io::Registration` for this purpose.

This is a fundamental feature for the `dbus-tokio` crate, so at this point we can't upgrade to 0.3. The code is also something that has been tested and patched by several community members as we had some hard time removing race conditions etc, so if the logic has been significantly changed, we need to start that process over from scratch. 
The somewhat hairy code is here in case you want a look at it: https://github.com/diwic/dbus-rs/blob/master/dbus-tokio/src/connection.rs

**Comment by Darksonn** [comment]
This is due to the removal of mio from the public API of Tokio. The next release will contain a type called `AsyncFd`, which was merged with #2903, however it has not been released yet.

**Comment by carllerche** [comment]
Fixed by #2903.
