### ISSUE TITLE
Backport RwLockWriteGuard::downgrade fix

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3053]
We need to backport  #2957 to 0.2.x.

cc @zaharidichev

**Comment by zaharidichev** [comment]
Will take care of that

**Comment by zaharidichev** [comment]
@Darksonn `downgrade` was recently added in #2733. Unless I am mistaken there is nothing to backport. Correct?

**Comment by Darksonn** [comment]
I guess you're right. I just thought it existed due to https://github.com/tokio-rs/tokio/pull/2957#issuecomment-708531330.
