### ISSUE TITLE
io: depend on bytes 1.0

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3058]
Before releasing Tokio 1.0, the `bytes` dependency needs to be updated to `bytes` 1.0.

**Comment by jonhoo** [comment]
Related `bytes` milestone for 1.0: https://github.com/tokio-rs/bytes/milestone/3

**Comment by taiki-e** [comment]
Also, `bytes` 0.6 milestone still has some open issues: https://github.com/tokio-rs/bytes/milestone/2

**Comment by carllerche** [comment]
@taiki-e good call. We should triage them.

**Comment by taiki-e** [comment]
In addition, `bytes` 0.5 milestone also has some open issues: https://github.com/tokio-rs/bytes/milestone/1
(I didn't notice it because the milestone was closed.)
