### ISSUE TITLE
sync: consider exposing `Semaphore::close` in public API

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#3061]
**Is your feature request related to a problem? Please describe.**
When updating `tower::buffer` to Tokio 0.3, it was necessary to [replace the use of tokio's bounded MPSC channel with a re-implementation using the _unbounded_ MPSC and Tokio's semaphore](https://github.com/tower-rs/tower/pull/476). This is because the bounded MPSC no longer exposes `poll_ready`, and the `ready` method borrows the sender, so it can't be easily boxed for an unbounded lifetime. Using `Sender::poll_ready` used to be sufficient to ensure that tasks waiting for the buffer service to become ready would be notified when the buffer worker terminates, because the senders would be woken on close. 

This doesn't work with the new approach using the semaphore, because the `Semaphore::acquire_owned` method requires the `Semaphore` itself to be `Arc`ed. The `Arc` is necessary to uphold the intrusive waitlist's safety invariants; as the semaphore cannot be dropped while there are still tasks in its waitlist. However, this means we can't drop it to notify the waiting tasks. Instead, we use the somewhat jankier approach of [just adding a big pile of permits to the semaphore](https://github.com/tower-rs/tower/blob/9cecf463cafcfc3666e4a1be40c6dbc482dd7967/tower/src/semaphore.rs#L96-L112) and hoping that callers don't continue trying to acquire permits from it. This isn't great, for that reason and because it's _theoretically_ (although probably not practically) possible to leak tasks if the semaphore is close to the maximum number of permits.

See tower-rs/tower#480 for details.

**Describe the solution you'd like**

The internal semaphore implementation has a `close` method, which does exactly what we'd want it to do: 
https://github.com/tokio-rs/tokio/blob/9097ae548f9a1bcd261385ceba29b800b0ee2a21/tokio/src/sync/batch_semaphore.rs#L165-L186

However, the public API semaphore type doesn't expose this for users to call. It would be nice if it did, for use cases like this.

**Describe alternatives you've considered**
- I also considered using a `Notify` alongside the semaphore to signal that the buffer has closed. However, `Notify::notify_all` is _also_ not public, so that's not a great option.
- We could continue just adding a bunch of permits. This is probably fine but it feels kinda messy.

I can't think of any arguments against adding `close` to the API except that it's good to stabilize as minimal an API surface as possible. It doesn't feel like a potential footgun (as long as the behavior is documented)...

**Comment by carllerche** [comment]
This will require changing `acquire()` to return `Result`, making it a breaking change. I am tagging this for 1.0.

**Comment by jkurian** [comment]
Hi, I would like to take a stab at this.

**Comment by carllerche** [comment]
Closed by #3065
