### ISSUE TITLE
Tokio 0.3 timer will hang when duration is small

### ISSUE THREAD

**Issue by quininer** [tokio-rs/tokio#3069]
**Version**

```
└── tokio v0.3.2
```

**Platform**

```
Linux hostname 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
```

and windows 10.

**Description**

code https://gist.github.com/quininer/72dd236419c67f99b1f9ae0711ca0411

```rust
fn main() {
    let rt = tokio::runtime::Runtime::new().unwrap();

    let j = rt.spawn(async move {
        loop {
            dbg!("start");
            tokio::time::sleep(std::time::Duration::from_millis(0)).await;
            dbg!("end");
        }
    });

    rt.block_on(j).unwrap();
}
```

This code may hang on sleep.

I discovered this problem earlier, but I haven't had time to debug it recently. :(

**Comment by Darksonn** [comment]
I changed it to the following:
```rust
fn main() {
    let rt = tokio::runtime::Runtime::new().unwrap();

    let j = rt.spawn(async move {
        let mut i = 0;
        loop {
            println!("start {}", i);
            tokio::time::sleep(std::time::Duration::from_millis(0)).await;
            println!("end {}", i);
            i += 1;
        }
    });

    rt.block_on(j).unwrap();
}
```
It behaves as I would expect, i.e. printing start and end forever. What do you see?

**Comment by quininer** [comment]
It will always stop at a number on my machine. If you use tsan, it seems easier to reproduce.

![Screenshot_20201029_205450](https://user-images.githubusercontent.com/6286761/97576599-53fcf480-1a29-11eb-95b7-f41455a27f7a.png)

**Comment by carllerche** [comment]
@bdonlan is working on timer improvements. He will include this as a test case. The PR should be up soon.

**Comment by quininer** [comment]
I think this has been fixed.
