### ISSUE TITLE
PollEvented2::new() != PollEvented2::new_with_handle(Handle::default())

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#307]
The docs for `PollEvented2::new` claim that it constructs a `PollEvented` with the "default reactor".  However, my crate's tests all pass if I do `try!(PollEvented2::new_with_handle(my_thing, &Handle::default()))`, but they hang if I do `PollEvented2::new(my_thing)`.  So what's the real difference?  My tests are all pretty simple.  They construct a `PollEvented` before starting any tasks, and then pass it into a `current_thread::block_on_all` loop.

**Comment by carllerche** [comment]
I agree that this is not ideal...

Fixing this in a backwards compatible way might be tricky.

The difference is that `Handle::default` will use the global reactor if called from outside of a runtime. This global reactor will most likely go away in 0.2 and was from pre `Runtime`.

If I do change `Handle::default`, it will be to not use the global reactor. This would match the behavior of not passing in a handle.

**Comment by asomers** [comment]
At the least, the documentation should clarify the differences between the two default reactors.  Are you suggesting that it should be invalid to call either `Handle::default()` or `PollEvented2::new()` outside of a runtime?  In that case, should they panic?
