### ISSUE TITLE
Max permits for Semaphore::add_permits does not match documentation

### ISSUE THREAD

**Issue by andrewhickman** [tokio-rs/tokio#3095]
**Version**

Tested on version 0.2.22 and on commit e309da0beeb48a0c2ecd0f15eb600f871ec98e19

**Platform**

Windows 10 64 bit

**Description**

I tried this code:

```
let s = tokio::sync::Semaphore::new(0);
s.add_permits(usize::MAX >> 3);
```

According to the documentation, the maximum permits is `usize::MAX >>3`, and exceeding this is an error. Therefore I would expect this code to work

Instead, it panics with `cannot add more than MAX_PERMITS permits (2305843009213693951)`. Using `usize::MAX >> 4` instead works.

**Comment by Darksonn** [comment]
This line is certainly a bit weird:

**Comment by andrewhickman** [comment]
Hmm yeah it seems to drop the first bit of the permit count

Using `0x8fffffffffffffff` permits also works

**Comment by blasrodri** [comment]
> This line is certainly a bit weird:
> 
> https://github.com/tokio-rs/tokio/blob/0b3918bce956567cccc617213a56c339a5a21d6f/tokio/src/sync/batch_semaphore.rs#L256
> 
> Should it shift in the other direction? With this code, `permits` wont ever be odd.

I think you're right here.
