### ISSUE TITLE
Expose tokio::io::PollEvented please

### ISSUE THREAD

**Issue by open-trade** [tokio-rs/tokio#3115]
Widely used by the other crates, it is hard to upgrade these crates without PollEvented, Currently PollEvented is only crate visible, please make it outside visible.

**Comment by Darksonn** [comment]
PollEvented uses the mio crate in its public API, which we don't want to do anymore. Alternate apis are needed.

**Comment by Keruspe** [comment]
Did you give AsyncFd a look?

**Comment by open-trade** [comment]
> Did you give AsyncFd a look?

My use case has no underlying Unix file descriptor.

**Comment by carllerche** [comment]
I opened #3118 to track named pipes.

We cannot expose Mio as part of the public API as we may wish to alter the internals to avoid Mio (perhaps uring).

**Comment by benjumanji** [comment]
> Alternate apis are needed.
It might have been nice to not make upgrading impossible until those newer apis were created.

**Comment by carllerche** [comment]
Feel free to submit a PR adding named to pipe support. As an open source project, we have limited resources and make decisions based on what we are able to get done.

**Comment by benjumanji** [comment]
> Feel free to submit a PR adding named to pipe support.

I don't need named pipe support.

**Comment by ZoeyR** [comment]
It is a shame that unix is getting preferential treatment here with the `AsRawFd` trait. There will inevitably be developer requirements that will not be met by the built-in windows types. For instance the proposed named pipes PR doesn't have security descriptors, and given the breadth of windows APIs I doubt there will ever be a complete solution.
