### ISSUE TITLE
Hang with LocalSet

### ISSUE THREAD

**Issue by alecmocatta** [tokio-rs/tokio#3117]
**Version**

`0.3.3` (current latest)

**Platform**

Tested on Linux and macOS

**Description**

This code hangs, whereas I would expect it to complete. The `LocalSet` is being awaited upon, therefore I would expect the spawned task to complete.

```rust
use futures::{
    future::{pending, ready},
    FutureExt,
};
use tokio::task::LocalSet;

#[tokio::main]
async fn main() {
    let ls = LocalSet::new();
    futures::select! {
        _ = ls.run_until(pending::<()>()).fuse() => unreachable!(),
        ret = async { ls.spawn_local(ready(())).await.unwrap() }.fuse() => ret
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=69699b05e5a2253a386fde6ba3796f50))

**Comment by Darksonn** [comment]
I played a bit around with this. The cause appears to be the following:

1. The `select!` polls the first branch, resulting in a `run_until` call that's sleeping.
2. The `select!` polls the second branch, spawning the future onto the local set.
3. But `run_until` is sleeping and the spawn does not emit a wake-up to it, so it keeps sleeping.

If you change it to spawn first, or for `run_until` to have a wake-up after the spawn, then it works.

**Comment by carllerche** [comment]
Seems like a spawn should result in waking the local set?. cc @hawkw

**Comment by hawkw** [comment]
> Seems like a spawn should result in waking the local set?. cc @hawkw

That seems right, we can do that!
