### ISSUE TITLE
Tasks not scheduled to thread blocked in rt.block_on

### ISSUE THREAD

**Issue by alecmocatta** [tokio-rs/tokio#3120]
**Version**

`0.3.3` (current latest)

**Platform**

Tested on Linux and macOS

**Description**

I want to do something similar to @carllerche's suggestion here: https://github.com/tokio-rs/tokio/issues/2095#issuecomment-573330413. I'm calling `rt.block_on(async { ... })` inside `rt.spawn_blocking(|| ...)`. Unfortunately tasks submitted by `rt.spawn(async { ... })`) are not being scheduled to these blocking threads.

This is confirmed by this code, which I would expect to print `a` thru `e` but only prints `a` thru `c`.

```rust
use futures::future::pending;
use std::{sync::Arc, time::Duration};
use tokio::{
    runtime::Builder,
    task::{self, LocalSet},
};

fn main() {
    let rt = Arc::new(
        Builder::new_multi_thread()
            .enable_all()
            .worker_threads(1)
            .build()
            .unwrap(),
    );
    for i in 0..4 {
        let r1 = rt.clone();
        let _ = rt.spawn_blocking(move || {
            println!("worker thread {}", i);
            r1.block_on(LocalSet::new().run_until(pending::<()>()));
            unreachable!();
        });
    }
    rt.block_on(async { LocalSet::new().run_until(main2()).await })
}

async fn main2() {
    println!("a");

    task::spawn(async {
        println!("b");
        std::thread::sleep(Duration::new(100, 0));
    });

    println!("c");

    task::spawn(async {
        println!("d");
    })
    .await
    .unwrap();

    println!("e");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=004bc0c907d4abc8fd1d2ea287f2fc04))

**Comment by Darksonn** [comment]
The tasks _should_ not be scheduled on those blocking threads. You can't hook a `LocalSet` up to the runtime's `spawn` method. The only way tasks can start running on those `LocalSet`s is if:

 * Someone calls `LocalSet::spawn_local` on that `LocalSet`.
 * Someone calls `tokio::task::spawn_local` from a future already running on that `LocalSet`.

The future that prints `d` will run eventually once the 100 second sleep finishes blocking the single thread in the executor.

**Comment by alecmocatta** [comment]
Sorry, I've removed `LocalSet` to avoid that confusing the issue. The issue is that there are 4 threads blocking inside `rt.block_on`, but that aren't being scheduled any tasks.

**Comment by Darksonn** [comment]
Spawned tasks are not scheduled in `block_on` calls.

**Comment by alecmocatta** [comment]
Precisely. Personally I found this surprising; there's no reason in theory why tokio couldn't add threads blocking in `block_on` to the runtime's worker pool. Indeed tokio has total control of the thread at this point. IIRC `async-std` does schedule tasks to threads blocked in `block_on`.

**Comment by Darksonn** [comment]
One issue with that is that we have to be able to migrate tasks off the thread in case one of the tasks calls `block_in_place`. We would not be able to migrate the `block_on` future since it is not required to be `Send`.

**Comment by alecmocatta** [comment]
As I understand it, `block_in_place` is a bit of a hack that is useful in quite specific use cases, but should not generally be used and indeed the docs make clear its footgun potential ("any other code running concurrently in the same task will be suspended... To avoid this issue, use `spawn_blocking` instead"). Thus I'm not sure I can really agree with compromising other aspects of the API due to it.

Just also to add some context, this is wholly an [XY problem](https://xyproblem.info): my actual need is to be able to call `spawn_local` from tasks spawned on a `Runtime`. Unfortunately this does not seem possible with the current API.

**Comment by Darksonn** [comment]
If you want to spawn tasks on a remote `LocalSet`, you can set up a task on that `LocalSet` that receives new tasks from a `tokio::sync::mpsc` channel. It would look something like this:
```
use futures::future::{pending, LocalBoxFuture};
use std::{sync::Arc, time::Duration};
use tokio::{runtime::Builder, task, sync::mpsc};

type TaskFn = Box<dyn FnOnce() -> LocalBoxFuture<'static, ()> + Send>;

fn main() {
    let rt = Arc::new(
        Builder::new_multi_thread()
            .enable_all()
            .worker_threads(1)
            .build()
            .unwrap(),
    );
    
    let (spawn, mut recv_spawn) = mpsc::unbounded_channel::<TaskFn>();
    
    let r1 = rt.clone();
    std::thread::spawn(move || {
        let ls = task::LocalSet::new();
        ls.block_on(&r1, async {
            while let Some(task_fn) = recv_spawn.recv().await {
                ls.spawn_local(task_fn());
            }
        });
    });
    
    rt.block_on(main2(spawn));
}
```
To send the `JoinHandle` back to the spawner, you could include an `oneshot::Receiver<JoinHandle<()>>` in the mpsc channel message type and send the join handle on that oneshot channel.
