### ISSUE TITLE
Obsolete phrase in documentation about #[tokio::main]

### ISSUE THREAD

**Issue by vi** [tokio-rs/tokio#3144]
**Version**

0.3.3

**Description**

[`#[tokio::main]`'s documentation](https://docs.rs/tokio/0.3.3/tokio/attr.main.html) seem to contain obsolete phrase:

> This is supported on crate features rt-multi-thread and macros only.

In reality it seems like Tokio 0.3 supports the macro for basic "rt" as well, not only for "rt-multi-thread".

**Comment by Darksonn** [comment]
This is because we export two different versions of the macro depending on the feature flags. These reexports will probably need to be changed to not use the `cfg_*` to fix this documentation issue.
