### ISSUE TITLE
tokio-macros/src/lib.rs mentions new_multi_thread, which does not seem to exist

### ISSUE THREAD

**Issue by mcr** [tokio-rs/tokio#3151]
**Version**
I am trying to establish a bug in rtnetlink where it works with #[tokio::main] vs explicit bootstrap of tokio runtime, so I am digging into what the macro does.

obiwan-[connect/netlink/rtnetlink](2.6.6) mcr 18302 %cargo tree | grep tokio
│   │   └── tokio v0.2.22
│   │       └── tokio-macros v0.2.5
│   ├── tokio v0.2.22 (*)
│   └── tokio-util v0.2.0
│       └── tokio v0.2.22 (*)
└── tokio v0.2.22 (*)

**Platform**
obiwan-[connect/netlink/rtnetlink](2.6.6) mcr 18303 %uname -a
Linux obiwan 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux

**Description**
The documentation in the comment says:

````
/// ```rust
/// #[tokio::main]
/// async fn main() {
///     println!("Hello world");
/// }
/// ```
///
/// Equivalent code not using `#[tokio::main]`
///
/// ```rust
/// fn main() {
///     tokio::runtime::Builder::new_multi_thread()
///         .enable_all()
///         .build()
///         .unwrap()
///         .block_on(async {
///             println!("Hello world");
///         })
/// }
/// ```
````

So I create a file:

````
fn main() {
     tokio::runtime::Builder::new_multi_thread()
         .enable_all()
         .build()
         .unwrap()
         .block_on(async {
             println!("Hello world");
         })
}
````

but, no such new_multi_thread() seems to exist.

**Comment by taiki-e** [comment]
Note that to use `Builder::new_multi_thread`, you need to enable the `rt-multi-thread` crate feature.
https://docs.rs/tokio/0.3.3/tokio/runtime/struct.Builder.html#method.new_multi_thread

**Comment by mcr** [comment]
I'm not seeing this crate feature in 0.2.22.

````
obiwan-[connect/netlink/rtnetlink](2.6.6) mcr 18318 %cargo build --example get_links0
error: failed to select a version for `tokio`.
    ... required by package `rtnetlink v0.5.0 (/ssw/projects/pandora/connect/netlink/rtnetlink)`
versions that meet the requirements `=0.2.22` are: 0.2.22

the package `rtnetlink` depends on `tokio`, with features: `rt-multi-thread` but `tokio` does not have these features.
````

And when I try new_current_thread() instead (which I started with before), I also found it wasn't present in the crate I have.  I will switch to the git tree I've checked out to see.

Ultimately, I need to do some things before starting tokio runtime (specifically, I need to fork(2)), so I'd rather not use the macro.

**Comment by taiki-e** [comment]
The document you mentioned in the title is for tokio/tokio-macros 0.3 and is not compatible with tokio/tokio-macros 0.2.

If you using tokio 0.2, [`Builder::new().threaded_scheduler()`](https://docs.rs/tokio/0.2.23/tokio/runtime/struct.Builder.html#method.threaded_scheduler) is equivalent to 0.3's `Builder::new_multi_thread()` (note that `rt-threaded` crate feature is needed)

**Comment by Darksonn** [comment]
Closing as this seems to be about looking at the wrong version of the documentation.
