### ISSUE TITLE
try_nb! is not exported by `tokio` crate

### ISSUE THREAD

**Issue by tdyas** [tokio-rs/tokio#316]
The `try_nb` macro is defined in the `tokio-io` subcrate and is not exported when users `#[macro_use]` the `tokio` parent crate. Since `macro_reexport` is not stabilized, maybe consider defining `try_nb` in the `tokio` crate temporarily? (Unless there is a way to `macro_use` macros from a subcrate?)

**Comment by carllerche** [comment]
Thanks for the report. It should be possible to use `tokio` almost entirely without `try_nb`. The `try_nb` macro is being deprecated. If you have a case where you can't switch to `try_ready`, please let me know.
