### ISSUE TITLE
util: FramedRead api

### ISSUE THREAD

**Issue by driftluo** [tokio-rs/tokio#3165]
Why doesn't `FramedRead` have a `read_buffer_mut` API?

When replacing the codec, there may be residual unparsed buffers that need to be replaced with the new codec, I have to do this now：
```
let frame = FramedRead::new(readpart, codec);
// Replace buffered data
unsafe {
   let buffer = frame.read_buffer() as *const BytesMut as *mut BytesMut;
   *buffer = raw_part.read_buf;
}
```
by the way, `Framed::from_parts` can change `FramedParts`, but `FramedRead` and `FramedWrite` can't do it 

If it is considered feasible, I can refer to PR to implement it

**Comment by Darksonn** [comment]
I don't think there's much reason besides nobody having implemented it. Feel free to submit a PR.

Be aware that the unsafe code you have posted has undefined behaviour.

**Comment by driftluo** [comment]
ok, I will implement it immediately, and then PR
