### ISSUE TITLE
docs: Add note in `time` about `runtime::Builder::enable_time` & change time driver panic message

### ISSUE THREAD

**Issue by sharnoff** [tokio-rs/tokio#3172]
This issue comes in one part problem, and two parts suggested solution (that I'd be happy to do, if it seems like a good idea).

I was recently trying to use some of the functionality from `tokio::time`, and got a panic on a call to `tokio::time::sleep` that read:

> there is no timer running, must be called from the context of Tokio runtime

This seemed a little strange because I was clearly calling it from within a runtime. It turned out the issue was actually that I hadn't enabled the time driver on the `runtime::Bulider`, but there wasn't anything in the documentation of the `time` module to indicate that was required, and I didn't find the panic message super helpful!

Anyways - I think it would be great to have a note in the documentation for `tokio::time` about enabling the time driver in the runtime builder, as well as tweaking the error message to be something more like:

> there is no timer running, must be called from the context of **a time-driver enabled Tokio runtime**

I'm happy to submit a PR for these changes - I figured it would be good to gather some feedback first, because they seem like the sort of thing that would be more subjective.

ETA: It might also be worth clarifying in `Runtime::new()` that it enables all devices (io, time) by default, because this is only an issue when using a `Builder` directly.

**Comment by Darksonn** [comment]
I think updating the error message to talk about a time-driver enabled runtime is a good idea!

**Comment by sharnoff** [comment]
Just found this and realized I never followed up. Looks like it's been fixed since - the panic message is much nicer now!

> A tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers
