### ISSUE TITLE
Make tokio::signal::windows::ctrl_c() public?

### ISSUE THREAD

**Issue by niklasf** [tokio-rs/tokio#3178]
There is already the platform independent `tokio::signal::ctrl_c()`, but it would be useful to have a stream analogous to `tokio::signal::windows::ctrl_break()` (which is already public).

It looks like the function already exists. Is there a reason to keep it private?

**Comment by ipetkov** [comment]
Hi @niklasf thanks for the report!

There's no strict reason why this wasn't exposed, seems like it was omitted because the cross platform `ctrl_c` exists, and so far no one has needed the stream version until now...

Happy to review a PR for the change if you're interested in submitting one!
