### ISSUE TITLE
futures2 should depend on futures 0.2

### ISSUE THREAD

**Issue by fudini** [tokio-rs/tokio#318]
Currently it's 0.2-beta

**Comment by russelltg** [comment]
It seems to have changed... 

https://github.com/tokio-rs/tokio/commit/dbcd8353b05002a98ea77dc2227ffeb84f0fd466

**Comment by fudini** [comment]
Then it just needs a push to crates.io where the version is still 0.2-beta.

**Comment by flosse** [comment]
Isn't it [v0.2.1](https://crates.io/crates/futures/0.2.1)?

**Comment by carllerche** [comment]
Thanks for teh report.

Tokio futures 0.2 support is probably not going to happen. I believe @aturon is waiting for 0.3 at this point.
