### ISSUE TITLE
Please publish deprecation notice on tokio-core crates.io page

### ISSUE THREAD

**Issue by jnqnfe** [tokio-rs/tokio#3182]
Hi,

I'm updating some dependencies for something which led me to an issue relating to `tokio-core` deprecation. I was not immediately aware that `tokio-core` had been abandoned in favour of `tokio` and only discovered the deprecation notice in the readme by accident which clarified things. Could you please publish a new `tokio-core` package to crates.io simply bundling the updated readme such that the deprecation notice actually appears on the `tokio-core` crates.io page. This would have been much appreciated by way have preventing my confusion had it already been done.

edit: d*** it, please also do so for the other crates like `tokio-io` that have also been deprecated :/

Thanks.

**Comment by Darksonn** [comment]
I think we need @carllerche to do this, since [the github repo][1] is archived and the crate is owned by Carl rather than the Tokio github organization.

[1]: https://github.com/tokio-rs/tokio-core

**Comment by Darksonn** [comment]
This is done.

**Comment by jnqnfe** [comment]
> This is done.

Thankyou :)
