### ISSUE TITLE
New timer does not interrupt I/O wait in multi-threaded scheduler

### ISSUE THREAD

**Issue by tijsvd** [tokio-rs/tokio#3190]
**Version**
tokio v0.3.4, tokio-macros v0.3.1

**Platform**
`Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux`

**Description**

Split from #3168 

Minimal example:

```rust
#[tokio::main(flavor="multi_thread")]
async fn main() {
    tokio::spawn(async {
        for i in 0.. {
            tokio::time::sleep(std::time::Duration::from_millis(1)).await;
            println!("slept {}", i);
        }
    });

    loop {
        tokio::time::sleep(std::time::Duration::from_secs(10)).await;
    }
}
```

Prints consecutive numbers to the terminal. Unexpectedly, it occasionally pauses for several (up to 10) seconds. If I change the second timer to a large number, it will just hang.

According to gdb, at the point of hanging, multiple threads are parked in what looks like normal idling (no work). One thread waits in epoll_wait, with a timeout close to the large timer value. If I then continue in gdb (epoll would return with EINTR), the process continues correctly until it hangs again.

**Comment by Darksonn** [comment]
I just tried running this with the OS below. I didn't see any hanging after letting it run until around 35000. How long do you need to run it observe the failure?
```
Linux 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux
```

**Comment by tijsvd** [comment]
It varies, sometimes a few seconds, sometimes several minutes. The minimal example here seems less prone to hanging than the larger one in the other ticket.

**Comment by tijsvd** [comment]
I couldn't easily reproduce this on my desktop either with the code above. Earlier I was running on a 8-vCPU AWS box. It may have something to do with the willingness of the scheduler to move tasks around?

The following hangs more easily, on my desktop as well:

```rust
#[tokio::main(flavor="multi_thread")]
async fn main() {
    tokio::spawn(async {
        for i in 0.. {
            tokio::time::sleep(std::time::Duration::from_millis(1)).await;
            for _ in 0..100 {
                tokio::task::yield_now().await;
            }
            println!("slept {}", i);
        }
    });

    loop {
        tokio::time::sleep(std::time::Duration::from_secs(3600)).await;
    }
}
```

**Comment by tijsvd** [comment]
Could this have something to do with a race condition in the timer stack processing, and missing a notification? Consider that on Linux, Mio's waker uses eventfd, but not in semaphore mode (`EFD_SEMAPHORE`), which means that multiple calls to `wake()` will lead only to a single wakeup. Is there a single timer/IO driver or does every thread have its own?

**Comment by carllerche** [comment]
Looks related to #3069, there is a pending fix on master. @tijsvd could you see if master fixes the problem?

**Comment by tijsvd** [comment]
Yes that fixes it.

**Comment by carllerche** [comment]
The fix has been released :+1:
