### ISSUE TITLE
spawn_local outside LocalSet in single-threaded runtime

### ISSUE THREAD

**Issue by tijsvd** [tokio-rs/tokio#3191]
**Is your feature request related to a problem? Please describe.**
The multi-threaded, work-stealing scheduler is fine for largish, mostly independent tasks, like a web server. But in a system with small tasks that heavily interact (e.g. the back-end for an online game), the only way to get reasonable performance is to make sure all tasks run in the same thread.

For this reason, I generally run such a system with the basic (current-thread) runtime, and where needed I run multiple such runtimes in explicitly spawned OS threads. Then, to allow `Rc` and `RefCell` instead of `Arc` and `Mutex`, I'll run a `LocalSet` in each runtime.

However this all looks a bit ugly. If I'm using a single-threaded scheduler, I should not need an additional construction to spawn `!Send` tasks. Plus, `LocalSet` seems to have its own run queue, and the interaction with the regular runtime, and the implications thereof, are unclear.

**Describe the solution you'd like**
I'd like `spawn_local` to just work, when in the context of a single-threaded runtime, but without `LocalSet`.

**Describe alternatives you've considered**
Alternatively, `LocalSet` could detect that it's using a single-threaded runtime, and redirect all tasks to it? Or the documentation may be improved, like what actually happens if a `LocalSet` is await-ed in a multi-threaded runtime; and what happens if more `LocalSet`s than worker threads would be active.

**Comment by Darksonn** [comment]
> If I'm using a single-threaded scheduler, I should not need an additional construction to spawn `!Send` tasks.

I know it seems this way, but that is not the case. The Tokio `Runtime` type implements `Send`, so you can move the `Runtime` itself across threads after spawning tasks on it. It only works with a `LocalSet` because the `LocalSet` is `!Send`.

When you use a `LocalSet` with a multi-threaded runtime, the tasks on that `LocalSet` will not run on the multi-threaded runtime's own threads. Instead they run in the thread you called `LocalSet::block_on` in, and the number of threads working with the multi-threaded runtime increases by the number of local sets.

**Comment by tijsvd** [comment]
Right, then perhaps using LocalSet is just the right way to do this. Is there a performance overhead of using LocalSet on a single-threaded runtime, compared to using the runtime only?

I assume there is some thread-local component of the runtime that runs the event loop for that thread, and that I/O and timer components hook into? Or is it just a pointer to the concrete `Runtime` that is registered?

**Comment by Darksonn** [comment]
Closing this as `spawn_local` cannot work without a `LocalSet` due to the reasons listed above.

Yes, Tokio uses some thread-locals for the IO and timer drivers.
