### ISSUE TITLE
Non-main async fn

### ISSUE THREAD

**Issue by pickfire** [tokio-rs/tokio#3195]
I was figuring out why manually creating `Runtime` and using an async function there does not work, I mean as in the port is not being binded correctly.

```rust
fn main() {
    thread::spawn(|| {
        use tokio::runtime::Runtime;

        let rt = Runtime::new().unwrap();
        rt.spawn(start(tx));
        tokio::spawn(start()); 
    });
}

async fn start() {
    let listener = TcpListener::bind("127.0.0.1:2345").await.unwrap();
    println!("listening");

    loop {
        let (mut socket, _) = listener.accept().await.unwrap();
        ...
    }
}
```

But `ss -aptn | grep 2345` shows nothing. It took me some time to look online and figure it out that I could use `#[tokio::main]` for other functions. Doing this work:

```rust
fn main() {
    thread::spawn(|| {
        start(); 
    });
}

#[tokio::main]
async fn start() {
    let listener = TcpListener::bind("127.0.0.1:2345").await.unwrap();
    println!("listening");

    loop {
        let (mut socket, _) = listener.accept().await.unwrap();
        ...
    }
}
```

Maybe we should document it that `#[tokio::main]` could be used for non-main functions?

**Comment by malaire** [comment]
Your first code is missing `.enable_io()` call.

**Comment by pickfire** [comment]
Oh, I didn't know I need to do that. But shouldn't it fail or show some warnings when `enable_io` is not called?

**Comment by sfackler** [comment]
Are you sure both the `rt.spawn(...)` and `tokio::spawn(...)` lines should be there?

In either case, you are spawning a task and not waiting for it to run, so the runtime immediately drops and the thread immediately exits.

**Comment by pickfire** [comment]
> Are you sure both the rt.spawn(...) and tokio::spawn(...) lines should be there?

No, I am not quite sure about that part but the function did run, `println!("listening")` does work.

**Comment by Darksonn** [comment]
I'm fine with mentioning in the doc that it can be used on all functions :+1:
