### ISSUE TITLE
tokio::io::split is not guaranteed to work for all AsyncRead + AsyncWrite types

### ISSUE THREAD

**Issue by Matthias247** [tokio-rs/tokio#3200]
[`tokio::io::split`](https://docs.rs/tokio/0.3.4/tokio/io/fn.split.html) is currently implemented by `Arc`-wrapping an async stream to get an `AsyncRead` and `AsyncWrite` handle. When `read/write` is called on those handles, the calls will be forwarded to the underlying streams `poll_read/poll_write` methods within a  Mutex. 

This is only guaranteed to work if the underlying Stream actually supports independent read and write operations, or more precise: It has a fully independent `Waker` for write operations and one for `Read` operations. If the underlying `Stream` is only able to store one `Waker` then it can't wake up 2 tasks which are accessing it for read and write operations, and an operation issued by the second task might remove the waker set the by the first task and thereby prevent the first task from ever making progress again.

Tokio streams which are directly wrapping OS  streams fulfill this property - however custom user-streams might not.

TLS streams are not always guaranteed to fulfill this property, as described in https://github.com/tokio-rs/tls/issues/40

I therefore think the current version of `tokio::io::split` is not necessarily something that should be offered. It could be fixed by creating a delegating `Waker` for the read and write halfs - and whenever a `.wake()` from the underlying stream happens waking both the last `Waker`  stored by `WriteHalf` and the last `Waker` stored by `ReadHalf`. This however comes with a certain level of overhead, and will needlessly cause spurious wakeups for streams which properly suppport independent reads and writes.

Another option is to remove the API and only offer `split` APIs on types which are actually guaranteed to be splittable (like the TCP stream).

The last option is place a big warning on the API docs. But obviously those are not always read.

**Comment by Darksonn** [comment]
This seems like a problem because the tls stream is probably the most common use-case of the `tokio::io::split` function in my experience talking to people.

**Comment by carllerche** [comment]
If `AsyncRead` and `AsyncWrite` are both implemented **correctly** it should be safe. However, it sounds like TLS does not implement the traits correctly?

**Comment by carllerche** [comment]
Closing as this is an issue w/ TLS (referenced in the issue).
