### ISSUE TITLE
AsyncFd usability issues

### ISSUE THREAD

**Issue by Keruspe** [tokio-rs/tokio#3208]
AsyncFd has (imo) some usability issues which could be improved quite easily (I can provide patches if the suggested solutions sounds good to you.

Let's say I have a custom TLS stream, that is provided by an external source and has not been created by tokio. the naive approach would be to register it using AsyncFd:

```
let stream = AsyncFd::new(stream);
```

Then if I want to e.g. write to it using some poll_write-like method:

```
let guard = ready!(stream.poll_write_ready(cx))?;
guard.with_io(|| stream.write(buf))
```

This looks ok *buf* if I need a mutable reference for writing, this won't compile since there already is a reference stored in the guard.
Current workaround it to create the AsyncFd with just the raw fd from the stream and cache the readable/writable state, which is clearly non optimal.

What I suggest:
- First, in the with_io closure, the guard should pass its reference to the inner stream: `guard.with_io(|stream| stream.write(but))`
- Second, either make `poll_write_ready` and firends take a `&mut` and pass the `&mut` to with_io, or add some new `poll_write_ready_mut` which does so with some `AsyncFdReadyGuardMut` or such.

WDYT?

**Comment by bdonlan** [comment]
These suggestions make sense (and some of them resemble what we've discussed in other threads), but I'd be inclined to wait for 1.0, given that 1.0 is coming soon, the `with_io` change is not backwards compatible (and adding another method would be confusing) and workarounds exist (eg, using a Mutex, or using a raw fd and keeping state elsewhere).

**Comment by Darksonn** [comment]
I think this is certainly something we should improve.

**Comment by arcnmx** [comment]
I tried replacing `PollEvented` with `AsyncFd` and ran into the same issue; `AsyncFd` taking ownership of the fd (combined with the guard borrowing it) makes it unusable. So +1 to both suggestions here!

**Comment by bIgBV** [comment]
@LucioFranco I can pick this up.

**Comment by arcnmx** [comment]
Another usability point I got bit by yesterday but now seems obvious in hindsight... it's awkward that clearing the readiness flag doesn't register the task waker, so one might end up having to use it like...

```rust
loop {
    let mut ready = ready!(fd.poll_read_ready(cx))?;
    match ready.with_io(|| file.read(buffer)) {
        Err(e) if e.kind() == ErrorKind::WouldBlock => continue,
        res => break Poll::Ready(res),
    }
}
```

If `with_io` returned `Poll<io::Result<T>>` instead, then it would be more fool-proof and obvious how to use it. It seems kind of silly to return `Poll::Ready(Err(ErrorKind::WouldBlock))` and hope the poll is called again by the caller, but that also seems like it might be what the current api is encouraging?

**Comment by carllerche** [comment]
@arcnmx I agree. We should make that change.

Who here is going to work on the PR for these changes?

**Comment by bIgBV** [comment]
@carllerche I wanted to take a stab at this.

**Comment by carllerche** [comment]
Changes have been merged to master. Thanks all.

Also, this is the final Tokio 1.0 issue :tada:

**Comment by coolreader18** [comment]
@arcnmx just banged my head against the wall with that issue for at least an hour; I was assuming that clearing the ready state reregistered the waker, but as you point out it doesn't. I think it does make more sense to have a loop for that, as there's no reason that you shouldn't just read again if it's available right away, but I think the docs for clear_ready need to be improved. Specifically I think the line "The internal readiness flag will be cleared, and **tokio will wait for the next** edge-triggered readiness notification from the OS" (emphasis mine) was what lead me to believe clear_ready would reset the waker. I guess tokio _will_ wait for the next notification, but won't necessarily let you know unless you ask nicely :P

**Comment by Darksonn** [comment]
Yes, you are expected to be calling `try_io` or friends in a loop like in the example i wrote on the main `AsyncFd` docs. Of course, I'm sure there are docs that should still be improved.
