### ISSUE TITLE
Poll-style APIs for sync primitives

### ISSUE THREAD

**Issue by NeoLegends** [tokio-rs/tokio#3209]
**Is your feature request related to a problem? Please describe.**

As far as I'm aware the sync primitives (Mutex, Semaphore) do not expose a poll-style API, making them harder to use in hand-implemented futures or, more importantly, `Service::poll_ready`.

**Describe the solution you'd like**

Expose a `.poll()` interface on those primitives that can be used w/o acquiring a future that must be polled first.

**Describe alternatives you've considered**

Currently we get the future, box it up to get nameable types (since they use `async fn`) and then poll those, but that's hacky and less performant.

**Additional context**

Implementing a `tower::Service` that needs access to an async Semaphore do perform it's work. Came across this issue while implementing `poll_ready`.

**Comment by NeoLegends** [comment]
A workaround to achieve poll-based functionality now (at the cost of synchronization overhead) is to spawn a task whose only responsibility is to acquire semaphore / mutex permits and send them into a channel. That can then be polled via the regular stream mechanisms.

**Comment by Darksonn** [comment]
We are working on this for mpsc in #3105. The `poll_*` functions can in some cases not be added directly on the primitive as the operation requires a `!Unpin` piece that is stored in the future. It is however possible build a wrapper that includes this piece and has `&mut self` poll methods rather than the usual `&self` methods.

**Comment by NeoLegends** [comment]
For future readers: there is a wrapper for Semaphores with optimized allocation here: https://docs.rs/tokio-util/0.6.4/tokio_util/sync/struct.PollSemaphore.html

**Comment by Darksonn** [comment]
Yes. Beyond that, there is also [`PollSender`][1] and the things in [`tokio_stream::wrappers`][2]. Can you update the original issue to mention the things that are missing? E.g. mutex is still missing.

[1]: https://docs.rs/tokio-util/0.6/tokio_util/sync/struct.PollSender.html
[2]: https://docs.rs/tokio-stream/0.1/tokio_stream/wrappers/index.html

**Comment by matklad** [comment]
`PollSemaphore` is missing API to acquire `n` permits at once. Context: I want to throttle `AsyncRead` to read at most `n` bytes per second. The way I want to do that is by creating a semaphore with `n` permits, which is refilled every second, and I need to use that semaphore from my struct that implements AsyncRead.

**Comment by Darksonn** [comment]
That should be relatively easy to add. If you want to write a PR for it, then go ahead.

**Comment by Darksonn** [comment]
Closed by #5137.
