### ISSUE TITLE
`around_worker` has no effect in conjunction with `Runtime`

### ISSUE THREAD

**Issue by dylanede** [tokio-rs/tokio#321]
Since the implementation of `runtime::Builder` uses `around_worker` on `thread_pool::Builder` itself inside its `build` method, this overrides any closure set via `around_worker` on the thread pool builder set in the runtime builder via `runtime::Builder::threadpool_builder()`.

For example, the closure set for `around_worker` in the following code is never called:

```rust
    let mut pool_builder = tokio::executor::thread_pool::Builder::new();
    pool_builder.around_worker(|worker, _| {
        use std::panic;
        println!("Starting new worker");
        let worker = panic::AssertUnwindSafe(worker);
        let result = panic::catch_unwind(|| {
            worker.run();
        });
        println!("Worker exited with status: {:?}", result);
    })
        .name_prefix("tokio-thread-");
    let mut rt = tokio::runtime::Builder::new()
        .threadpool_builder(pool_builder)
        .build()
        .unwrap();
    rt.spawn(future::lazy(|| { /* ... */ }));
    rt.shutdown_on_idle().wait().unwrap();
```

**Comment by carllerche** [comment]
You are correct.

Thinking about it more, I believe that accepting a thread pool builder when building the runtime is not correct. Instead, the runtime builder should provide its own builder fns that do the right thing.

**Comment by carllerche** [comment]
Would you like to try to take a stab at updating the builder?

The steps would be to add the relevant threadpool builder fns on the runtime builder and deprecate the fn that takes the threadpool builder. 

Also, you can expose after_start and before_stop initially if you want. 

Thoughts?

**Comment by carllerche** [comment]
This was resolved by removing the ability to pass a threadpool builder to the runtime builder.
