### ISSUE TITLE
Item type of broadcast Stream

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3214]
The item type of the broadcast [`into_stream`][1] Stream is `Result<T, RecvError>`, but that `RecvError` has a variant called `Closed`. We should reconsider this, as the stream should just return `None` in that situation.

[1]: https://docs.rs/tokio/0.3/tokio/sync/broadcast/struct.Receiver.html#method.into_stream

**Comment by carllerche** [comment]
You are correct in that the stream should represent "closed" as returning `None`. Are you proposing defining a new error type for the stream version that does not have `Closed`?

**Comment by Darksonn** [comment]
That would certainly be an option. I'm also open to other solutions, but I'm not sure what alternatives there are.

**Comment by carllerche** [comment]
@Darksonn How do you think we should proceed here?

**Comment by Darksonn** [comment]
I think we should add a new error type. Considering we already have an entire module for errors for broadcast, I do not think that is an issue API-complexity wise, as people probably wont look into that module very much.

I also think it would make sense to make the `impl Stream` return type by `into_stream` a concrete type called e.g. `ReceiverStream`. This one in particular is often used together with things like `StreamMap` and then put in a struct, so I've seen people want to name the type several times.

**Comment by LucioFranco** [comment]
We are removing the stream impl in #2870, so I think we can punt on this for now?

**Comment by Darksonn** [comment]
Fair point.

**Comment by henryboisdequin** [comment]
Is this still relevant and an issue to work on?

**Comment by Darksonn** [comment]
Ah, thanks for reminding me of the issue. No, a new `Stream` impl was added as [`BroadcastStream`][1], which does indeed use a custom enum.

[1]: https://docs.rs/tokio-stream/0.1/tokio_stream/wrappers/struct.BroadcastStream.html
