### ISSUE TITLE
Bidirectional tokio_io::io::copy of TcpStreams doesn't always complete

### ISSUE THREAD

**Issue by dgllghr** [tokio-rs/tokio#322]
I ran into this issue using tokio-io, but based on the code in tokio I believe this issue still applies. I am using tokio-core 0.1.17, tokio-io 0.1.6, and futures 0.1.21.

## Summary

Setting up a bidirectional pipe of two TcpStreams using `io::copy()` and `TcpStream::split()` results in a future that does not always complete when one of the streams is closed (which then may result in `too many open files` when sockets are not released):

```
fn bidirectional_copy(c1: TcpStream, c2: TcpStream) -> Box<Future<Item=(u64, u64), Error=std::io::Error>> {
    let (c1_read, c1_write) = c1.split();
    let (c2_read, c2_write) = c2.split();

    let half1 = copy(c1_read, c2_write);
    let half2 = copy(c2_read, c1_write);
    Box::new(half1.join(half2).map(|((x, _, _), (y, _, _))| (x, y)))
}
```

I am a beginner to Rust and tokio, so it may be that this is an obviously wrong approach. But it was easy to find `split` and `copy` and get this up and running, so at the very least I think it might be helpful to document the pitfalls of using them like this (my guess is in `split`). 

## My Guess

Based on my reading of the implementation of `copy`, my guess is that because the `writer` in each `Copy` struct is not being touched when there is no data to be read, `copy` is not detecting when the write side is closed. If only connection `c1` (from above) is closed, then only `half1` is detecting that the connection is closed, and it is exiting as `ok`, but `half2` is not detecting that its write end is closed because it is not touching the writer. Then `join` only exits when _both_ futures exit with `ok`, so it is never exiting.

## Possible solution

https://github.com/tokio-rs/tokio-socks5 has been an excellent reference guide for me to get started with rust and network programming with tokio. It contains an example of a bidirectional Tcp copy, and it uses a custom implementation. That custom implementation touches the reader and writer on every iteration, and from my testing I believe that solves the problem.

I've modified that implementation to be more similar to how `copy` works (copy uses an owned buffer and the `tokio-socks5` library uses a global shared buffer). The general idea is to use `poll_read` and `poll_write` to touch the sockets on every iteration.

```
#[derive(Debug)]
struct Transfer {
    reader: Rc<TcpStream>,
    writer: Rc<TcpStream>,
    buf: Box<[u8]>,
    amt: u64,
    pos: usize,
    cap: usize,
    read_done: bool,
}

impl Transfer {
    fn new(reader: Rc<TcpStream>, writer: Rc<TcpStream>) -> Transfer {
        Transfer {
            reader,
            writer,
            buf: Box::new([0; 2048]),
            amt: 0,
            pos: 0,
            cap: 0,
            read_done: false,
        }
    }
}

impl Future for Transfer {
    type Item = u64;
    type Error = io::Error;

    fn poll(&mut self) -> Poll<u64, io::Error> {
        loop {
            let read_ready = self.reader.poll_read().is_ready();
            let write_ready = self.writer.poll_write().is_ready();
            let write_amt = if self.pos == self.cap {
                if !read_ready {
                    return Ok(Async::NotReady)
                }
                let n = try_nb!((&*self.reader).read(&mut self.buf));
                self.cap = n;
                self.pos = 0;
                n
            } else {
                self.cap - self.pos
            };

            while self.pos < self.cap {
                if !write_ready {
                    return Ok(Async::NotReady)
                }
                let m = try_nb!((&*self.writer).write(&self.buf[self.pos..self.cap]));
                if m == 0 {
                    return Err(io::Error::new(io::ErrorKind::WriteZero,
                                              "write zero byte into writer"));
                }
                self.pos += m;
                self.amt += m as u64;
            }

            if write_amt == 0 && self.pos == self.cap {
                try_nb!((&*self.writer).flush());
                try!(self.writer.shutdown(Shutdown::Write));
                return Ok(self.amt.into())
            }
        }
    }
}
```

This implementation fixes the issue for me.

**Edit:** Looking at the `futures` library again, I think there is an even simpler solution: just use `select`! Now I don't think this is really a bug at all and it's just a case of using the wrong function. Please feel free to close if there is nothing actionable here.

**Comment by carllerche** [comment]
It looks like you figured it out on your own :) 👍 

Indeed you are correct. You would want to use `select` in this case to achieve your behavior. The behavior you explained is intended.

I'm going to close the issue. Feel free to continue posting to this issue if you have further questions.
