### ISSUE TITLE
Feature list is incomplete

### ISSUE THREAD

**Issue by Pand9** [tokio-rs/tokio#3241]
https://docs.rs/tokio/0.3.5/tokio/#feature-flags

This list does not list "tracing" feature flag, while this one does: https://docs.rs/crate/tokio/0.3.5/features
Description of https://docs.rs/tokio/0.3.5/tokio/#feature-flags implies it's a complete list, so it should either be changed, or missing elements should be added.

**Comment by Darksonn** [comment]
Closed by #3254.
