### ISSUE TITLE
tokio: consider removing prelude

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3257]
Does tokio::prelude carry its weight? Some consider the prelude an anti-pattern. Should we remove it? Should we doc-hide it?

**Comment by LucioFranco** [comment]
We should go ahead and do this

**Comment by leoyvens** [comment]
I used to advocate for preludes, but now that IDE integration is good enough that auto-imports are easy, they became a lot less useful and necessary.

**Comment by zaharidichev** [comment]
@LucioFranco I can take that one if noone is working on it.

**Comment by Darksonn** [comment]
Note that this would likely merge conflict with #3291 on doc changes if that is not merged before this is started.
