### ISSUE TITLE
Make windows-only APIs show up on docs.rs

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3275]
Currently all windows-only APIs can only be seen on docs.rs if you choose windows under the target dropdown. Very few people actually do this, so they are easily missed.

There should be some way to make rustdoc generate documentation for them even though the documentation is being generated on Linux.

**Comment by jyn514** [comment]
You can do this the same way as async-std and the standard library: https://github.com/rust-lang/rust/pull/43348, https://github.com/rust-lang/rust/issues/75100. It's documented at https://doc.rust-lang.org/nightly/rustdoc/advanced-features.html#interactions-between-platform-specific-docs.

That said, I consider that a misfeature and I really wish rustdoc didn't support it. Could you instead link to the windows docs from the landing page?

**Comment by Darksonn** [comment]
The windows docs are already available if you pick it under the target, but it's not very easily discoverable. I think if we were to avoid this, we would have to add links on the unix types for any type with a windows equivalent.

**Comment by blasrodri** [comment]
Perhaps adding a note on the main page of the docs, alerting non-Linux users that they can click the drop-down to find the docs corresponding to their targets could work.

**Comment by Darksonn** [comment]
This was fixed by 3770.
