### ISSUE TITLE
tokio::test is documented as being multi-threaded by default, it's not

### ISSUE THREAD

**Issue by malaire** [tokio-rs/tokio#3290]
In https://docs.rs/tokio/0.3.6/tokio/attr.test.html
> The default test runtime is multi-threaded.

ps. The Note-section might also need to be updated.

**Comment by Darksonn** [comment]
Turns out we just need to release a new version of `tokio-macros`.

**Comment by Darksonn** [comment]
I asked the docs.rs team to rebuild the main Tokio crate, which should update the docs now that we have a new tokio-macros release.
