### ISSUE TITLE
tcp: remove `shutdown()` fn on `TcpStream` in favor of `AsyncWrite::shutdown()`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3294]
The trait function calls `shutdown(WRITE)`. The duplication is confusing and causes some naming conflicts.

Access to the syscall is available by accessing the `std` socket and calling `shutdown()` on that.

This would also apply to `UnixStream`

**Comment by aknuds1** [comment]
Is this still relevant if #3291 gets closed, since `AsyncWrite` doesn't have the shutdown method yet?

**Comment by Darksonn** [comment]
Yes. The method is just on `AsyncWriteExt` instead.

**Comment by aknuds1** [comment]
@Darksonn Thanks for clarifying!

**Comment by aknuds1** [comment]
I'll look into solving this.
