### ISSUE TITLE
Figure out how to release new versions while maintaining a global event loop.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#33]
The crate will need to try to manage a single global event loop even if multiple versions of the crate are pulled in at the same time.

The strategy by which to do this should be figured out ahead of time.

**Comment by carllerche** [comment]
I believe that the global event loop will have to be constant across Mio versions.

**Comment by aturon** [comment]
Can you elaborate on why this should block 0.1? It seems to me more a concern to grapple with if/when we have such breakage to make.

Also, it seems plausible to me that you should simply not be able to use multiple major versions of this crate simultaneously as reachable public dependencies.

In any case, there's exactly one way to do this, AFAIK: have one of the library versions be implemented in terms of the other. It's pretty hard to get more concrete than that without having a clear picture of what the breakage might be.

If the breakage involves public dependencies (like mio), then the same applies at that level, which would likely make bridging between them impossible.

**Comment by aturon** [comment]
Some additional thoughts about version bumps [here](https://github.com/tokio-rs/tokio/issues/27#issuecomment-342671384).

**Comment by carllerche** [comment]
The current plan for tokio 0.1 is to not wait on Mio 0.7, so that means at least initially, the global reactor will not be shared.
