### ISSUE TITLE
Turning Tokio's types into streams in Tokio 1.0

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3303]
This is a proposal for how we can make it as easy as possible to turn the main Tokio types into a `Stream`, to ease transition to a Tokio 1.0 without the `Stream` trait.

The first part of the proposal is to define the following sealed trait:
```Rust
trait TokioStreamHelper: Sealed {
    type Item;
    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>>;
}
```
This will allow us to define a struct `TokioStream<S>` which converts any Tokio type with a `poll_*` method into a named type that implements `Stream`.
```Rust
struct TokioStream<S> {
    inner: S,
}
impl<S: TokioStreamHelper> Stream for TokioStream<S> {
    type Item = S::Item;
    
    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let inner = unsafe {
            Pin::map_unchecked_mut(self, |me| &mut me.inner)
        };
        inner.poll_next(cx)
    }
}
```
To implement this trait, we would expose various methods such as `poll_recv` on the main Tokio types, and tokio-stream would implement the above trait on those types like this:
```Rust
impl<T> TokioStreamHelper for tokio::sync::mpsc::Receiver<T> {
    type Item = T;
    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        self.poll_recv(cx)
    }
}
```
At this point, any user of Tokio can turn an mpsc receiver into a `Stream` with `TokioStream::new(recv)`.

There are some types that cannot be turned into a stream with this approach such as the receiver of a broadcast channel. For these, the documentation should suggest that you use the [`async-stream`](https://docs.rs/async-stream/) crate to turn them into a stream.

**Comment by hawkw** [comment]
Hmm, I was going to propose a much simpler approach which was just 
```rust
pub trait IntoStream {
    type Item;
    type Stream: Stream<Item = Self::Item>;
    fn into_stream(self) -> Self::Stream;
}
```
by analogy with `IntoIterator`, and providing implementations of that trait for `tokio` types in `tokio-stream`. But, either design would work fine, I think!

Regardless, it would be nice if the wrapper types had accessors for the inner type (`inner`/`inner_mut`/`into_inner`?) and/or implemented `Deref`/`DerefMut`. It would be nice to retain the ability to call the wrapped type's other methods, especially in cases like `mpsc::Receiver`, which can't be cloned...

**Comment by Darksonn** [comment]
Yeah, after more thought I agree that an `IntoStream` is a good idea. We can provide public wrapper types in `tokio-stream` for mpsc and friends. This would also allow us to implement it for broadcast with `async-stream`.

**Comment by Darksonn** [comment]
This is now doable using the `tokio_stream::wrappers` module for most types. Note that the doc is currently generated incorrectly, so some of the streams are not displayed on docs.rs, but if you compile the doc locally with all features enabled, you should see them all.
