### ISSUE TITLE
Should try_read take ReadBuf?

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3311]
Currently `TcpStream::try_read` takes a `&mut [u8]`. Should it be changed to take a `ReadBuf`? The same applies to `try_recv`.

**Comment by carllerche** [comment]
I think it is on. I don’t really consider it low level as it is to be called from async / await. It is the try_ variant to async fn read. We also can add try_read_buf to support safe reads into non-initialized memory.

**Comment by Darksonn** [comment]
Alright. Opened #3313 to track `_buf` variants.
