### ISSUE TITLE
Request new method `peer_addr` for `tokio::net::UdpSocket`

### ISSUE THREAD

**Issue by PragmaTwice** [tokio-rs/tokio#3312]
**Is your feature request related to a problem? Please describe.**
As in the question #3309, I want to obtain `peer_addr` in `tokio::net::UdpSocket`, as `std::net::UdpSocket::peer_addr`.

**Describe the solution you'd like**
Provided by @Darksonn in Discord, implement it for `mio::net::UdpSocket`, then forward it to `tokio::net::UdpSocket`.

**Describe alternatives you've considered**
Provided by @Darksonn in Discord, downgrade to `RawFd` and retrieve `peer_addr`, which is a workaround.

**Comment by carlosb1** [comment]
I did a [proposal](https://github.com/carlosb1/tokio/tree/3312_request_new_method_peer_addr) , but it is necessary update mio to 0.8.0
