### ISSUE TITLE
length_delimited shouldn't reserve space up front

### ISSUE THREAD

**Issue by tikue** [tokio-rs/tokio#333]
https://github.com/tokio-rs/tokio/blob/master/tokio-io/src/length_delimited.rs#L328-L330

This opens an attack vector where a naughty client could open many connections and take down a server by sending just a header specifying the max size over each connection.

e.g.: A server with max frame length of 8 MB and allows 1000 connections per IP could be forced to allocate 8 GB by a job that only sends 8 KB of data.

One straightforward solution is to change `decode_data` to reserve more space if `src` is full and `src.len() < n`.  Since `BytesMut` already handles exponentially increasing the size of reservations to amortize the cost, it could be as simple as `reserve(n.min(MAX_RESERVATION_SIZE))` (which probably should be configurable).

**Comment by carllerche** [comment]
As discussed on Gitter, I do not think this needs to be fixed.

When allocating large buffers, the memory should not be wired up, instead the MMU will lazily wire it up on access, so there will not be a DOS potential.
