### ISSUE TITLE
Unsoundness mapping/downgrading in RwLock

### ISSUE THREAD

**Issue by Koxiaet** [tokio-rs/tokio#3344]
Version: Tokio 1.0.0

In the code:
```rust
use std::cell::Cell;
use tokio::sync::{RwLock, RwLockWriteGuard};

#[tokio::main]
async fn main() {
    let lock = RwLock::new(Cell::new(10_u32));
    let guard = lock.write().await;
    let guard = RwLockWriteGuard::map(guard, Cell::get_mut);
    let guard = RwLockWriteGuard::downgrade(guard);
    let value_ref: &u32 = &*guard;
    lock.read().await.set(11);
        
    drop(value_ref);
}
```

We obtain a reference to the Cell as well as a reference to the inner value - this can be seen in the error running Miri on [the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0c47dd006c0e9ce0cbab3c47b08fafa4).

This same unsoundness occurred in [parking_lot](https://github.com/Amanieu/parking_lot/issues/198), and they had to remove the `downgrade` API (on mapped guards) as a result. However, this isn't really an option for Tokio now that it's stable.

(sorry for the edits, I accidentally posted this before I'd finished writing it)

**Comment by Darksonn** [comment]
Well that's problematic. It was added in #2733.

**Comment by MikailBag** [comment]
AFAIK fixing soundness bug is valid reason to break backwards compatibility.
For example [Rust RFC 1122](https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md#soundness-changes) allows it.
