### ISSUE TITLE
No obvious way to set a read limit for read_until

### ISSUE THREAD

**Issue by Wesmania** [tokio-rs/tokio#3346]
In standard library, it's possible to call BufRead's `read_until` with a read limit using a pattern like this:
```
reader.by_ref().take(limit).read_until(byte, buf)
```
The `by_ref()` call allows us to reuse the reader later. The same pattern works in `async_std`, as its `ReadExt` trait implements `by_ref`:
```
reader.by_ref().take(limit).read_until(byte, buf).await
```
Tokio only implements `by_ref` for `*Half` traits, which means the above one-liner doesn't work after wrappeng them in a `BufReader`. I don't see any other way of imposing a read limit on `read_until` in Tokio other than reimplementing it.

I suppose the simplest (end-user wise) way to fix this would be to implement `by_ref` in `AsyncReadExt` for any `AsyncRead`. I have no idea how hard it is, #2716 mentions some trouble implementing `by_ref` for `TcpStream`.

**Comment by Darksonn** [comment]
Note that `reader.by_ref()` is equivalent to `(&mut reader)`, so you should be able to do this:
```
(&mut reader).take(limit).read_until(byte, buf).await
```
The `TcpStream::by_ref` discussion is unrelated. Adding it would be very easy.

**Comment by Wesmania** [comment]
It works for me, thanks. I suppose `by_ref` is just there for chaining.
