### ISSUE TITLE
TcpStream Implementations of AsyncRead/AsyncWrite

### ISSUE THREAD

**Issue by MggMuggins** [tokio-rs/tokio#335]
A bit of a forward: I'm working on porting tokio to [RedoxOS](http://redox-os.org) and so this issue isn't really related to your work maintaining Tokio. However, I think the code that I am asking about might benefit from some discussion. Basically, feel free to close this if you don't think it's in scope.

My investigations have led me to https://github.com/tokio-rs/tokio/blob/master/tokio-tcp/src/stream.rs#L487-L515 https://github.com/tokio-rs/tokio/blob/master/tokio-tcp/src/stream.rs#L575-L584. The way I understand these functions is that they attempt to write from a provided `Buf` to the internal `TcpStream`, and if it would block return an error. This seems like an operation which basically requires creating a `[u8]` from the provided `Buf` and writing it to the internal `mio::TcpStream`. Instead, there is a two-dimentional operation going on with arrays of `IoVec`, which makes the code difficult to read. My guess is there is a good reason as to why `[IoVec]` is used, but it's certainly not clear to me based on any of the documentation or source code for surrounding calls or the code itself.

I'd appreciate some help understanding this code, and maybe helping improve Tokio by possibly rewriting those implementations to make more sense.

**Comment by carllerche** [comment]
`IoVec` is the abstraction around the various vectored buffer abstractions provided by operating systems.

It allows reading from and writing to discontinuous chunks of memory with one syscall. This is basically the API that provides `readv` and `writev` access.
