### ISSUE TITLE
Failure to build: the trait `std::marker::Copy` is not implemented for `std::io::IoSlice

### ISSUE THREAD

**Issue by dgoulet** [tokio-rs/tokio#3355]
**Version**
```
│   ├── tokio v1.0.1
│   └── tokio-postgres v0.7.0
│       ├── tokio v1.0.1 (*)
│       └── tokio-util v0.6.0
│           ├── tokio v1.0.1 (*)
│           └── tokio-stream v0.1.0
│               └── tokio v1.0.1 (*)
```

**Platform**

Linux 5.8.0-25-generic Ubuntu

**Description**

Attempting to build `postgres` crate, which uses `tokio_postgres` in the background, the `tokio-util` build fails with:

```
   Compiling tokio-util v0.6.0
error[E0277]: the trait bound `std::io::IoSlice<'_>: std::marker::Copy` is not satisfied
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.6.0/src/lib.rs:189:30
    |
189 |             let mut slices = [IoSlice::new(&[]); MAX_BUFS];
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `std::io::IoSlice<'_>`
    |
    = note: the `Copy` trait is required because the repeated element will be copied

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tokio-util`.

To learn more, run the command again with --verbose.
```

I've tried both on cargo stable (`rustc 1.48.0 (7eac88abb 2020-11-16)`) and nightly (`rustc 1.51.0-nightly (0b644e419 2020-12-26)`).

**Comment by taiki-e** [comment]
Hmm, IoSlice implements Copy in Rust 1.44+ (https://github.com/rust-lang/rust/commit/79b8ad84c84481a43704213cd0948d2ba0ea63b4), and tokio-util's MSRV is Rust 1.45. I guess your project may be [overriding the default toolchain with the old toolchain in some way](https://rust-lang.github.io/rustup/overrides.html). 

Could you try with toolchain override shorthand (`cargo +nightly build`)?

**Comment by dgoulet** [comment]
You were right, it turns out that the `rustc` Ubuntu system wide package was always used instead of the one I installed with `rustup`.

I apologize for this issue, I should have checked that. Big thanks for your help!.

**Comment by shuke0327** [comment]
I  met the same problem wen compiling tokio-utils, thanks for the question and answer.
