### ISSUE TITLE
Don't start the reactor when running Miri

### ISSUE THREAD

**Issue by Kestrer** [tokio-rs/tokio#3360]
It can be useful to run async tests in Miri. However, `#[tokio::test]` will currently attempt to start the reactor, which will cause an error in Miri as it isn't supported. By only starting the reactor on `#[cfg(not(miri))]`, we will be able to run tests using Miri without having to use `futures_executor::block_on` or something like that.

**Comment by Darksonn** [comment]
I suppose something like that could work.

**Comment by blasrodri** [comment]
@Koxiaet
You’re thinking of ignoring  [this line](https://github.com/tokio-rs/tokio/blob/master/tokio-macros/src/entry.rs#L254) when running Miri?

**Comment by Koxiaet** [comment]
@blasrodri Even better, `enable_io` (and `enable_time` if Miri doesn't support it) could become a no-op on Miri, which also makes sense and is perhaps simpler

**Comment by RalfJung** [comment]
FWIW, this should be done with care. `cfg(miri)` is mainly intended for test cases; we also use it in the standard library in a few places. There are situations in user code where this makes sense, and this might be one of them -- it is just important to be aware of the implication: the `cfg`'d-out code is not tested by Miri. So any such `cfg` introduces some risk that when testing things in Miri, one is not testing the things one thinks one is testing.

So when a library does this, it might be worth pointing this out somewhere in the documentation, at least.

**Comment by Darksonn** [comment]
It's possible that it is better to update tests to not enable IO so we don't run into the miri error on starting epoll. Then we can do it selectively on tests that don't depend on epoll, but are still e.g. threaded.

**Comment by blasrodri** [comment]
> It's possible that it is better to update tests to not enable IO
Do you mean by modifying the proc macro, and changing the `add_all` call in case `is_test` is `true` on function `parse_knobs`?

**Comment by Darksonn** [comment]
No, I meant modifying each test directly rather than modifying the macro. Tests which actually use IO should not be modified of course, as they simply cannot run with miri.

**Comment by carllerche** [comment]
Until Miri is stabilized as part of the rust stable channel, I am inclined to *not* factor it in. The runtime builder provides sufficient configuration options to disable the IO driver.

**Comment by tiif** [comment]
A quick search on ``miri`` in the issue tracker led me to this issue, currently the ``#[tokio::test]`` issue appeared to be solved.

**Comment by nurmohammed840** [comment]
@tiif, Just today I added this PR #6900, Without knowing that `#[tokio::test]` works on Linux, So I closed it.
Unfortunately, at the moment, it does not work on Windows.

**Comment by tiif** [comment]
Oh yea, you are right. I forgot that ``#[tokio::test]`` probably still won't work in MacOS or Windows. This is tracked under https://github.com/rust-lang/miri/issues/1719.

**Comment by RalfJung** [comment]
The recommendation for non-Linux users is to run Miri with ``--target x86_64-unknown-linux-gnu``. That  should work everywhere and does not require any special tools.
