### ISSUE TITLE
Standardize missing executor panic messages

### ISSUE THREAD

**Issue by shepmaster** [tokio-rs/tokio#3361]
Sometimes you get an error like:

> there is no reactor running, must be called from the context of Tokio runtime

Sometimes it's like:

> not currently running on the Tokio runtime

**Describe the solution you'd like**

Ideally, these would all have the same error text, or at least a common substring. This makes searching for and finding solutions easier.

**Additional context**

[Why do I get the error “there is no reactor running, must be called from the context of Tokio runtime” even though I have #[tokio::main]?](https://stackoverflow.com/a/64780012/155423)

**Comment by Darksonn** [comment]
It could be good to include the Tokio version in the error message too.

**Comment by aknuds1** [comment]
I can try to solve this.

**Comment by aknuds1** [comment]
Note to self: "no reactor found" should print a message about `enable_all` if the problem is that missing.

**Comment by carllerche** [comment]
It would be helpful to explain how to fix it as well or at least a ref to docs

**Comment by aknuds1** [comment]
@carllerche @Darksonn do you know how to track down error cases corresponding to there being no reactor running, so I can figure out where to standardize?

**Comment by Darksonn** [comment]
There are already some mentioned earlier in this thread. Besides those, I would search for `panic!` in the codebase.
