### ISSUE TITLE
Add tokio-stream wrappers for watch and broadcast receivers

### ISSUE THREAD

**Issue by peku33** [tokio-rs/tokio#3382]
In tokio 0.2 watch and broadcast receivers implemented Stream.
In tokio 1.0 they don't.

While I know watch and broadcast will probably never be Stream themselves, there is some work in progress to make them convertible into Streams: https://github.com/tokio-rs/tokio/issues/3303

While this is still in progress - is it possible to have watch and broadcast receiver wrappers added to tokio-stream?

**Comment by Darksonn** [comment]
We can add wrappers that just internally use the `async-stream` crate. We can't do better as the channels have no `poll_recv` method.

**Comment by peku33** [comment]
Yes, please

**Comment by liufuyang** [comment]
I will give a try to see if I can help adding it :)

**Comment by jhpratt** [comment]
This would be wonderful to have! It's the only thing preventing me from doing a full upgrade to tokio 1.0 on a major project of mine.

**Comment by liufuyang** [comment]
Sorry I got dragged away for something else and couldn't find time finishing it up. Perhaps I can take a look at it this coming weekends. Otherwise @Darksonn might be able to give me a hand or just do this on her own if I am too slow progressing :)

**Comment by peku33** [comment]
Hi, any update on this?

**Comment by Darksonn** [comment]
Yes! The wrappers were waiting for #3464, which was just released in tokio-util v0.3.6 one hour ago.

**Comment by Darksonn** [comment]
The wrappers are out in tokio-stream v0.1.3.
