### ISSUE TITLE
Update runtime documentation to reflect `blocking` feature.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#339]
These docs are out of date: https://docs.rs/tokio/0.1.6/tokio/runtime/index.html

**Comment by dekellum** [comment]
With some help in #419, I'm willing to that this and attempt general doc updates for the `blocking` feature.

**Comment by carllerche** [comment]
Great 👍  I would definitely appreciate it if you could take what you learn and translate it to docs / comments!

**Comment by carllerche** [comment]
I believe this was handled.
