### ISSUE TITLE
Feature "full" does not enable feature "test-util"

### ISSUE THREAD

**Issue by wqfish** [tokio-rs/tokio#3395]
The document (https://docs.rs/tokio/1.0.1/tokio/index.html#feature-flags) says

> full: Enables all Tokio public API features listed below.

But the `test-util` feature doesn't seem to be enabled with `full`. Probably either include the `test-util` feature with `full`, or clarify this in the document?

**Comment by Darksonn** [comment]
I've updated this as a doc issue and help-wanted in case anyone wants to update the doc.
