### ISSUE TITLE
tokio::main and tokio::test trigger errant "unnecessary braces around block return value" rustc warnings

### ISSUE THREAD

**Issue by chanks** [tokio-rs/tokio#3403]
Reproduction on playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03c32dd3a3859630dc943844f347066c

**Version**
I first experienced this with 0.2.23, but playground seems to be using 1.0.1 and it's still happening there.

**Description**
I was just experimenting with the `fn_single_line` rustfmt config option on nightly. With a short-enough `main()` or test function body, rustc generates incorrect warnings:

```
warning: unnecessary braces around block return value
 --> src/lib.rs:2:17
  |
2 | async fn main() { println!("hello") }
  |                 ^^^^^^^^^^^^^^^^^^^^^ help: remove these braces
  |
  = note: `#[warn(unused_braces)]` on by default

warning: unnecessary braces around block return value
 --> src/lib.rs:5:23
  |
5 | async fn my_test_fn() { assert!(true) }
  |                       ^^^^^^^^^^^^^^^^^ help: remove these braces
```

The warnings go away if the proc macros are removed from the functions, so I assume this is tokio's problem rather than rustc's.

**Comment by taiki-e** [comment]
I believe this is the same issue as https://github.com/rust-lang/rust/issues/71080

**Comment by chanks** [comment]
Thanks!
