### ISSUE TITLE
tokio_util: Always pending feature for `DelayQueue`

### ISSUE THREAD

**Issue by DenisKolodin** [tokio-rs/tokio#3407]
It's impossible to use `DelayQueue` in a loop with `select!`, because the `select!` macros requires all streams to be `fuse`d, but `DelayQueue` returns `Ready(None)` if it no contains any scheduled item. It "breaks" a `FusedStream`.

That's good to have `always_pending` option that will never return `Ready(None)` and a `DelayQueue` instance can be used with `fuse` wrapper without drawbacks.

```rust
let delay_queue = DelayQueue::new().fuse();
loop {
    select! {
        item = delay_queue.select_next_some() => {
           // The fused `DelayQueue` closed and this code will never called (
        }
        event_to_schedule = some_channel.select_next_some() => {
            delay_queue.get_mut().insert_at(event_to_schedule.item, event_to_schedule.instant);
        }
    }
}
```

If the `DelayQueue` is empty there is a workaround to use a temporary `pending()` stream instead of fused `delay_queue` or have two different `select!` variants: the first with a queue and the second without.

If we will have something like `DelayQueue::new(always_pending: true)` that will never return `Ready(None)` that can solve the problem.

**Comment by Darksonn** [comment]
If you use Tokio's `select!` macro instead, this is no problem.
```Rust
let delay_queue = DelayQueue::new();
loop {
    tokio::select! {
        Some(item) = delay_queue.next() => {
            ...
        }
        Some(event_to_schedule) = some_channel.recv() => {
            delay_queue.insert_at(event_to_schedule.item, event_to_schedule.instant);
        }
    }
}
```

**Comment by DenisKolodin** [comment]
@Darksonn Thanks for the response. But I have some extra requirements (I made an inaccuracy forgot to mention them):
- I need to use `select_biased!` (because I also have a high-priority queue that has to be consumed first)
- I want to use that code later in the browser (using WASM). I know `DelayQueue` is not compatibe with WASM, but I mean I can't use `tokio::select!` freely with different implementation of `DelayQueue` (`tokio` and third-party).

**Comment by Darksonn** [comment]
I'm pretty sure that you can reset the closed state of the `Fuse` wrapper like this:
```Rust
let delay_queue = DelayQueue::new().fuse();
loop {
    select! {
        item = delay_queue.select_next_some() => {
            ...
        }
        event_to_schedule = some_channel.select_next_some() => {
            let mut inner = delay_queue.into_inner();
            inner.insert_at(event_to_schedule.item, event_to_schedule.instant);
            delay_queue = inner.fuse();
        }
    }
}
```

**Comment by DenisKolodin** [comment]
That's good idea. Thanks! I think the issue can be closed now )
