### ISSUE TITLE
No way to wait for a child to exit without closing stdin

### ISSUE THREAD

**Issue by Benjamin-L** [tokio-rs/tokio#3420]
**Is your feature request related to a problem? Please describe.**
The docs for `Child::wait` say that it will automatically close the stdin handle in order to avoid a deadlock. In my case, I want to manage closing stdin by myself, but still schedule a waker for when the child exits. Here's a simplified version of what I'm doing:

```rust
let stdin = child.stdin.as_mut().unwrap();
let mut stdin_done = false;
loop {
    tokio::select! {
        exit_status = child.wait() {
            // ...
            break;
        }
        chunk = body_rx.recv(), if !stdin_done => match chunk {
            Some(chunk) => stdin.write_all(&chunk[..]).await,
            None => {
                stdin_done = true;
                stdin.shutdown().await;
            }
        }
        // ...
    }
}
```

Deadlocking is not an issue here because of the `select!`. There is also a `Child::try_wait` method, which appears to be appropriate here, but doesn't wake the task if the child exits, so using that instead of `wait` could cause a deadlock where the task never gets woken again if the task sending data to `body_rx` stops.

**Describe the solution you'd like**
Ideally there would either by an argument for `Child::wait` which would specify whether stdin gets closed. Since this would be a breaking change, it would probably be better to just add another method like `Child::wait_with_stdin`. I'm not sure what the best name for it would be.

**Describe alternatives you've considered**
Giving up on tokio's process support entirely and just spawning an OS thread to deal with this is always an option.

**Comment by Darksonn** [comment]
I think you can just take the `ChildStdin` out of `Child` first by calling `Option::take`. Then there's no stdin in the struct anymore.
```Rust
let stdin = child.stdin.take().unwrap();
```

**Comment by Benjamin-L** [comment]
Ah, that works perfectly. It might be worth putting something in the documentation to point this out, but I'm good closing this issue.
