### ISSUE TITLE
`tracing` the executor, inlined async function behavior

### ISSUE THREAD

**Issue by vjancik** [tokio-rs/tokio#3440]
**Is your feature request related to a problem? Please describe.**
I'm trying to get `tracing` information on when tasks / futures are being scheduled on the `tokio` runtime.

**Describe the solution you'd like**
`tracing` with `RUST_LOG=tokio=trace` should show each future being run on the executor.

**Describe alternatives you've considered**
Instrumenting the functions themselves doesn't help me because I'm trying to trace yields to the executor.

**Additional context**
I'm trying to determine the behavior of `#[inline]` and `#[inline(always)]` for `async` functions. Whether a an `.await` on an inlined async function yields to the executor, or whether the `.await` is "transparent" and becomes a no-op.

I've tried your `chat` example, but the only tracing information the current implementation provides is:
```
TRACE mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
```

I also tried building with `.cargo/config.toml`:
```
[target.x86_64-unknown-linux-gnu.tokio]
rustc-cfg = ["tokio_unstable"]
```
as per the `tokio/Cargo.toml` recommendation, but that didn't produce any different effect.

**Comment by malaire** [comment]
Did you also add `tracing` feature in `Cargo.toml`? Note that `full` does **not** enable that and it needs to be added separately.

```
tokio = { version = "1.0", features = ["full", "tracing"] }
```

**Comment by vjancik** [comment]
Yes. And it just occurred to me, that there was no output because there was no task yield. A future awaiting another future wouldn't reach the executor. My mistake.
