### ISSUE TITLE
Using `unwrap` is causing panic

### ISSUE THREAD

**Issue by Kalomidin** [tokio-rs/tokio#3445]
https://github.com/tokio-rs/tokio/blob/5402c948eebbb4c6c695e156d68ce495a43ea81a/tokio/src/sync/watch.rs#L210
In that function `borrow`, it uses `unwrap` where we may fail to catch the error if we have `PoisonError`
My suggestion is that, would that not be better to return ` Ref<'_, Result<T, PoisonError<T>>>` instead of `Ref<'_, T>` ?

**Comment by Darksonn** [comment]
The question is if we want poison detection here at all.

**Comment by Kalomidin** [comment]
Is it the only `broadcast` function in `Sender` accesses `shared_value` in `Receiver` as `mut`?
I was just not sure about it and for the sake of `safety`, I referred to it.

**Comment by Darksonn** [comment]
Yes, it is only modified from `send`. In any case, we cannot change the return type due to backwards compatibility.

**Comment by Kalomidin** [comment]
I am convinced that it is totally safe to use unwrap there.
So I believe it is impossible to come up with an example that would trigger `poison error`

**Comment by Darksonn** [comment]
Oh, so it can only happen if the panics happen while a _write_ guard is held? I guess that makes sense.
