### ISSUE TITLE
Futures passed to `block_on` get polled whenever a subtask becomes ready

### ISSUE THREAD

**Issue by Matthias247** [tokio-rs/tokio#3475]
**Version**

```
use tokio; // 1.0.2
```

**Platform**

Linux  (haven't explicitly tried on other platforms)

**Description**

If a `Future` is passed to `block_on`, it should behave like any other `Future` which gets executed by tokio. It should only be woken if is `Waker` gets woken - which indicates it can make progress. However it seems like currently `Future`s passed to `block_on` are woken whenever any other `Future` that is handled by the same runtime can make progress. I guess it's polled in every eventloop cycle. If the `Future`  passed to `block_on` is rather big this can be a major waste of effort (in the program where this was found the `Future` actually locked a synchronous mutex for 100µs on each iteration, which caused another tokio task to be blocked for this time).

I tried this code:

[Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d55d844edb8dd57df7c71b5861caa2e2)

```rust
use tokio; // 1.0.2

use std::pin::Pin;
use std::task::{Context, Poll};
use std::future::Future;
use std::time::Duration;

fn main() {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
        
    let (tx, rx) = tokio::sync::oneshot::channel();
        
    rt.spawn(async {
        for _ in 0 .. 5 {
            tokio::time::sleep(Duration::from_millis(7)).await;
            println!("Timer");
        }
        
        tx.send(()).unwrap();
    });
    
    rt.spawn(async {
        for _ in 0 .. 5 {
            tokio::time::sleep(Duration::from_millis(5)).await;
            println!("Timer2");
        }
    });

    rt.block_on(async {
        Fut{
            receiver: rx,
        }.await;
    });
}

struct Fut {
    receiver: tokio::sync::oneshot::Receiver<()>,
}

impl Future for Fut {
    type Output = ();
    
    fn poll(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        println!("Was polled");
        
        match Pin::new(&mut self.receiver).poll(cx) {
            Poll::Pending => Poll::Pending,
            _ => Poll::Ready(())
        }
    }
}
```

**I expected to see this happen:**

`Was polled` showing up 2 times

**Instead, this happened:**

`Was polled` showing up whenever any other task made progress:

```
Was polled
Was polled
Was polled
Timer2
Was polled
Timer
Was polled
Timer2
Was polled
Timer
Was polled
Timer2
Was polled
Was polled
Timer2
Was polled
Timer
Was polled
Timer2
Was polled
Timer
Was polled
Was polled
Timer
Was polled
```

**Comment by carllerche** [comment]
Fixing this shouldn't be too hard. The waker passed to the `block_on` future would have to have some way to inform the caller that it was actually woken.

**Comment by seanmonstar** [comment]
I believe this is the same as https://github.com/tokio-rs/tokio/issues/1897.

**Comment by pickfire** [comment]
Is this resolved? The pull request was merged.
