### ISSUE TITLE
Why don't we use Any instead of raw pointer?

### ISSUE THREAD

**Issue by HeeillWang** [tokio-rs/tokio#3485]
https://github.com/tokio-rs/tokio/blob/06d6adf4b7597fa316f3277c2aa60da27dac59fc/tokio/src/runtime/task/join.rs#L218-L231

I understand it is necessary to erase the generic types here. But why don't we use [Any](https://doc.rust-lang.org/std/any/index.html) instead of raw pointer? I think it is more rustic way, though it might harm performance(not sure about this...). Any other advantages to use raw pointer here?

**Comment by Darksonn** [comment]
Performance-wise, a `&mut dyn Any` has twice the size of an `*mut ()`.
