### ISSUE TITLE
time::interval doesn't work during cargo tests, while time::sleep does

### ISSUE THREAD

**Issue by miklelappo** [tokio-rs/tokio#3501]
**Version**
```
├── tokio v0.3.5
│   └── tokio-macros v0.3.1 (proc-macro)
├── tokio-fd v0.2.1
│   └── tokio v0.3.5 (*)
├── tokio-util v0.5.0
│   └── tokio v0.3.5 (*)
```

**Platform**
Linux PCNAME 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description**
In test configuration time::interval behaviour is slightly different from normal build and exits immediately after being called.

I tried this code (also on rust playground):

```
#[tokio::main]
async fn main() {
}
mod tests {
    use std::time::{Duration, SystemTime};
    use tokio::time::{interval, sleep};
    #[tokio::test]
    async fn test_interval() {
        println!("{:?}", SystemTime::now());
        let mut delay = interval(Duration::from_secs(2));
        delay.tick().await;
        println!("{:?}", SystemTime::now());
        assert_eq!(true, false);
    }
    #[tokio::test]
    async fn test_sleep() {
        println!("{:?}", SystemTime::now());
        sleep(Duration::from_secs(2)).await;
        println!("{:?}", SystemTime::now());
        assert_eq!(true, false);
    }
}
```

I expected to see this happen: tests duration to be both around 2 seconds

Instead, this happened: test_interval exits immediately, while test_sleep runs 2 seconds

[Link to rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=46bf1137033b39b2d53468ed70cc49a3)

**Comment by Darksonn** [comment]
The first call to `tick` returns immediately.

**Comment by miklelappo** [comment]
True.
