### ISSUE TITLE
Adding an infinite timeout option.

### ISSUE THREAD

**Issue by abrassel** [tokio-rs/tokio#3519]
**Is your feature request related to a problem? Please describe.**
In applications where only some of the spawned tasks need to be wrapped with a timeout, it's useful from a typing perspective to wrap the other futures in an "infinite" timeout.

**Describe the solution you'd like**
Some mechanism to specify that the timeout will never occur.  For example, having passing in a duration of 0 be a special value to indicate that no time out should occur.  

**Describe alternatives you've considered**
I've attempted to coerce the original future and the future generated by `timeout` into pinned box traits around closures.  However, this results in issues pertaining to the fact that `Future` is an opaque type.  

`Either` does not work because it's only implemented over the same associated type.

My current workaround is to collect into two iterators and call `join_all` separately on them.

**Comment by Darksonn** [comment]
Can you give some more details?

**Comment by abrassel** [comment]
Sure!  Would you like more details about my use case or about how I would like the feature to look?

**Comment by Darksonn** [comment]
Your use case. What types are involved here. Why doesn't `Either` work?

**Comment by abrassel** [comment]
After posting this, I found the `Either` crate and that works fine.  I tried `futures::future::Either` late last night and it gave me warnings about a mismatch between the associated types.  

I'll try it again now and see if I can reproduce the issue.

**Comment by Darksonn** [comment]
The error you mention about associated types sound like the two halves have different output types, but it doesn't really make sense to have the two versions return a different type. I'm pretty sure `futures::future::Either` should work.

**Comment by abrassel** [comment]
Well, guess I shouldn't have been coding so late.  I swapped the `Either` crate for `futures::future::Either` and it works flawlessly :)
What is actually the problem is that `join_all` doesn't like the different output types. I hadn't tried removing that yesterday.

I'll go ahead and close the issue :)
