### ISSUE TITLE
Windows runtime doesn't drain work queues on shutdown

### ISSUE THREAD

**Issue by jakubtyrcha** [tokio-rs/tokio#3522]
**Version**
tokio v1.2.0
tokio-macros v1.1.0 (proc-macro)

**Platform**
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-pc-windows-msvc
release: 1.49.0
cargo 1.49.0 (d00d64df9 2020-12-05)
64-bit Windows

**Description**
According to (https://docs.rs/tokio/1.2.0/tokio/runtime/struct.Runtime.html):
```
Shutting down the runtime is done by dropping the value. The current thread will block until the shut down operation has completed.

    Drain any scheduled work queues.
    Drop any futures that have not yet completed.
    Drop the reactor.
```
The runtime is supposed to drain scheduled work queues, but drop any futures that have not yet completed. I don't know how to interpret this, as it sounds a bit contradictory. The runtime seems to behave differently on UNIX (tested play.rust-lang.org) and on Windows (tested on my Win64 machine).

I tried this code:

(example from https://docs.rs/tokio/1.2.0/tokio/sync/struct.Notify.html)

```
use tokio::sync::Notify;
use std::sync::Arc;

#[tokio::main]
async fn main() {
    let notify = Arc::new(Notify::new());
    let notify2 = notify.clone();

    tokio::spawn(async move {
        notify2.notified().await;
        println!("received notification");
    });

    println!("sending notification");
    notify.notify_one();
}
```

I expected to see this happen (the task is in the queue, so I assume the queue should be drained before the shutdown):

On console output:
`sending notification`
`received notification`

Instead, this happened:
`sending notification`

I see the expected behaviour in Playground.

**Comment by Darksonn** [comment]
This is expected behavior. All tasks are dropped when the runtime shuts down. The fact that it sometimes prints `received notification` just has to do with whether the spawned task was quick enough to catch the notification before it was killed.
