### ISSUE TITLE
Extract `Encoder`, `Decoder`, and `Framed*` into a new tokio-codec crate

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#353]
This extracts the core types from [`tokio_io::codec`](https://docs.rs/tokio-io/0.1.6/tokio_io/codec/index.html) into a dedicated crate.

To do so with less disruption in 0.1 would mean:

* tokio-codec depends on tokio-io.
* tokio-codec re-exports `Encoder` / `Decoder` from tokio-io.
* `Encoder`, `Decoder` in `tokio-io` are annotated deprecated and doc hidden.
* The various `Framed*` types in `tokio-io` are marked deprecated and hidden
* The `Framed*` types are copied to `tokio-codec` and the pending breaking changes are applied (#148 and any other).

The utility codecs `BytesCodec` and `LinesCodec` would move to `tokio-util`.

**Comment by bryanburgers** [comment]
The `AyncRead` trait's `framed` function uses `Encoder` and `Decoder`. If `tokio-codec` depends on `tokio-io`, that won't work.

How do you suggest we solve the circular dependency?

**Comment by bryanburgers** [comment]
I suppose, since we are deprecating (and not removing) everything, we could deprecate `framed` on the `AsyncRead` trait. We’d still need a good place for it to live in the `tokio-codec` library. That could be as a stand-alone function, or it could be hanging off some other trait or struct.

**Comment by carllerche** [comment]
@bryanburgers yes. We should deprecate `framed` on `AsyncRead` as well. The deprecated `AsyncRead::framed` fn can point to the deprecated `Framed` types in `tokio-io`.

**Comment by hawkw** [comment]
I believe  #360 closes this?
