### ISSUE TITLE
TCPStream/UDPSocket tos/set_tos methods

### ISSUE THREAD

**Issue by dvolodin7** [tokio-rs/tokio#3545]
**Is your feature request related to a problem? Please describe.**
Some network applications rely on proper marking of egress packets using ToS/DSCP fields. Routing protocols,
management traffic, VoIP applications and so on. 

ToS can be set on socket level using `setsockopt` call, using `IPPROTO_IP` level and `IP_TOS` option.
TCPStream and UDPSocket already have functions:

*  `ttl`
* `set_ttl`

for getting an setting TTL field. TTL is manipulated via the same `setsockopt`/`getsockopt` calls.

**Describe the solution you'd like**
Adding methods

* `tos`
* `set_tos`

for getting socket's ToS settings will be good addition for a large spectre of network applications.

**Describe alternatives you've considered**
Direct usage of setsockopt on raw socket handle still possible, and can be used as workaround.

**Additional context**
N/A

**Comment by aym-v** [comment]
Before we can update the sockets implementation in tokio, mio and the std library need to be updated. I opened the above PR to start with.
