### ISSUE TITLE
Inconsistent reporting "reactor gone"

### ISSUE THREAD

**Issue by stepancheg** [tokio-rs/tokio#3546]
Consider this example:

```
fn main() {
    // here we create a reactor to create a listener
    let listener = tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(async { tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap() });
    let port = listener.local_addr().unwrap().port();

    let handle = std::thread::spawn(move || {
        println!("accepting...");
        // and here we create a fresh reactor to accept with previously created listener
        let accepted = tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(async { listener.accept().await.unwrap() });
        println!("accepted {:?}", accepted);
    });

    println!("connect...");
    let connected = std::net::TcpStream::connect(("127.0.0.1", port)).unwrap();
    println!("connected {:?}", connected);
    handle.join().unwrap();
}
```

Invocation of this program results in "reactor gone" error: reactor created for listener is gone at the moment of listener accept.

So my conclusion is that listener IS tied to specific reactor. Which might be reasonable.

However, if I change the first line of code to:

```
    // keep the reactor to the moment of listener.accept, but do not use it for listener accept
    // that new reactor is not running when listener.accept is executed, it just exists
    let keep_reactor = tokio::runtime::Runtime::new().unwrap();
    let listener = keep_reactor
        .block_on(async { tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap() });
```

The program starts working fine. So original reactor is NOT required to run accept? Then why first program panicked then?

I suspect the correct behavior is to always use the reactor which was used to create a listener. So listener.accept should panic if current thread reactor is different from reactor used to create the listener.

I have a relatively large program which hangs and it has more than one reactor. I cannot reproduce the hang-up yet (and cannot fix it yet, the problem appeared when I upgraded tokio). So far I found this issue, so it might be related.

So
* if my suspicion that we must not switch reactors is correct, let's add an assertion, and likely my program will panic instead of hanging
* otherwise if switching reactor is acceptable, let's fix "reactor gone" error

**Comment by Darksonn** [comment]
A `TcpListener` is generally tied to the runtime it was created on, but as long as that runtime is not destroyed, it will work even if moved to another runtime.

**Comment by stepancheg** [comment]
@Darksonn OK, then if that's expected behavior I'll continue digging.

**Comment by Darksonn** [comment]
You can change the runtime an IO resource is tied to be converting back and forth into the `std` type. It will end up tied to the runtime that you call `from_std` from in that case.

**Comment by stepancheg** [comment]
Just in case, my problem was not related to switching reactors, but accidentally it reproduced only with multiple reactors.

So let's close the issue if it works as expected.

**Comment by stepancheg** [comment]
Why the issue is closed? Is it not a bug? Is it fixed? Or just batch or issues got closed by timeout?

**Comment by Darksonn** [comment]
I was looking through old issues, it looked like it was really just a user question that had been answered, and the last comment said "let's close the issue".

**Comment by stepancheg** [comment]
It works as expected then. Ok, thanks.
