### ISSUE TITLE
A way to determine if current thread is a "blocking thread".

### ISSUE THREAD

**Issue by trevyn** [tokio-rs/tokio#3559]
**Is your feature request related to a problem? Please describe.**
I almost wrote a `spawn_blocking` call in a function that I think is already being called in a `spawn_blocking` context.

**Describe the solution you'd like**
A way to determine if the current thread is already a "blocking thread".

**Comment by Darksonn** [comment]
Can you elaborate a bit on your use-case?

**Comment by trevyn** [comment]
Sure, I'm using the [`juniper_warp`](https://github.com/graphql-rust/juniper) GraphQL server framework, to which I pass an async handler, in which I want to do some blocking stuff:

```rust
async fn my_query_handler() {
  tokio::task::spawn_blocking(move || {
    // ... blocking stuff here ...
  }).await;
}
```

But then I look in the [internal dispatch](https://github.com/graphql-rust/juniper/blob/master/juniper_warp/src/lib.rs#L211) of `juniper_warp`, and I see calls to `spawn_blocking` already... So is it possible that `juniper_warp` is calling my async handler from a `tokio` thread that is already OK for blocking?

**Comment by Darksonn** [comment]
The code running inside `spawn_blocking` is non-async, so they would not be able to call `my_query_handler` there, as it is an async function.

**Comment by trevyn** [comment]
Ah, I see. In the general case, could it be doing something like

```rust
async fn dispatch() {
  tokio::task::spawn_blocking(move || {
    futures::executor::block_on(user_query_handler());
  }).await;
}
```

(or if that's not exactly correct, otherwise polling the `Future` returned by the `async` function manually, and in a blocking manner, without using `await`)

**Comment by Darksonn** [comment]
Even inside such a `spawn_blocking`/`block_on` pair, I would not just block the thread. There may be a `tokio::join!` or similar somewhere above you in the callstack, and blocking would prevent other halves of the join from running.

**Comment by trevyn** [comment]
Ok, so it's advised to always do the `spawn_blocking` myself if I expect to block for more than ~10-100 microseconds (per [Async: What is blocking?](https://ryhl.io/blog/async-what-is-blocking/)). Thank you for the explanations!
