### ISSUE TITLE
Add acquire_owned_many for Semaphore

### ISSUE THREAD

**Issue by staticgc** [tokio-rs/tokio#3567]
The [semaphore](https://docs.rs/tokio/1.2.0/tokio/sync/struct.Semaphore.html) has [non-owned version](https://docs.rs/tokio/1.2.0/tokio/sync/struct.Semaphore.html#method.acquire_many) of acquiring many permits. 

Proposal: A similar owned version to acquire many permits

```rust
pub async fn acquire_owned_many(self: Arc<Self>, n: u32) -> Result<OwnedSemaphorePermit, AcquireError> {}
```

Similarly to add a try version of the above function.

Happy to raise a PR for this!

**Comment by Darksonn** [comment]
Please see #3535.
