### ISSUE TITLE
fix clippy -- -D warnings  ?

### ISSUE THREAD

**Issue by cssivision** [tokio-rs/tokio#3585]
when run `cargo clippy -- -D warnings`, errors occur.

maybe we can fix it, and this rule to ci.yaml.

**Comment by taiki-e** [comment]
I think this is due to we use old clippy https://github.com/tokio-rs/tokio/pull/2962
The latest clippy supports MSRV configurations, but there is still the issue that clippy adds new lints with each new release, blocking irrelevant PR.

**Comment by Darksonn** [comment]
Feel free to submit PRs that fix clippy warnings in newer versions of clippy than the one we are using.

**Comment by taiki-e** [comment]
`-D warnings` is not needed. We have already denied warnings (via RUSTFLAGS).
