### ISSUE TITLE
tokie::time:sleep Panics

### ISSUE THREAD

**Issue by cleanerx** [tokio-rs/tokio#3595]
**Version**
 tokio v0.2.25

**Platform**
Linux worker1 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
32bit

**Description**
Calling this in the arm (32bit) platform results in a panic

 tokio::time::sleep(tokio::time::Duration::from_secs(std::u64::MAX)).await;

Panic: 

   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:349:21
   4: <std::time::Instant as core::ops::arith::Add<core::time::Duration>>::add
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/time.rs:374:9
   5: <tokio::time::instant::Instant as core::ops::arith::Add<core::time::Duration>>::add
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/time/instant.rs:145:27
   6: tokio::time::delay::delay_for
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/time/delay.rs:56:17
   7: kubelet::kubelet::start_plugin_registry::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/kubelet-0.6.0/src/kubelet.rs:170:21
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
   9: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/core.rs:173:17
  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  11: tokio::runtime::task::core::Core<T,S>::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/core.rs:158:13
  12: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  13: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
  15: std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  16: __rust_try
  17: std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  18: std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  19: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  20: tokio::runtime::task::raw::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  21: tokio::runtime::task::raw::RawTask::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  22: tokio::runtime::task::Notified<S>::run
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  23: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
  24: tokio::coop::with_budget::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/coop.rs:127:9
  25: std::thread::local::LocalKey<T>::try_with
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:272:16
  26: std::thread::local::LocalKey<T>::with
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:248:9
  27: tokio::coop::with_budget
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/coop.rs:120:5
  28: tokio::coop::budget
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/coop.rs:96:5
  29: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
  30: tokio::runtime::thread_pool::worker::Context::run
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
  31: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
  32: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  33: tokio::runtime::thread_pool::worker::run
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
  34: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
  35: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
  36: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/core.rs:173:17
  37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  38: tokio::runtime::task::core::Core<T,S>::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/core.rs:158:13
  39: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  40: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  41: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
  42: std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  43: __rust_try
  44: std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  45: std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  46: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  47: tokio::runtime::task::raw::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  48: tokio::runtime::task::raw::RawTask::poll
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  49: tokio::runtime::task::Notified<S>::run
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  50: tokio::runtime::blocking::pool::Inner::run
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
  51: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
  52: tokio::runtime::context::enter
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/context.rs:72:5
  53: tokio::runtime::handle::Handle::enter
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/handle.rs:76:9
  54: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17

**Comment by Darksonn** [comment]
Closing as fixed by #3551.

Feel free to reopen if I have misunderstood the problem.
