### ISSUE TITLE
Missing documentation for feature `time` in crate tokio_util

### ISSUE THREAD

**Issue by oddcoder** [tokio-rs/tokio#3596]
**Version**
tokio ="1"
tokio-util = "0.6.3"

**Platform**
Windows 64 bit

**Description**
With this cargo.toml
```
tokio = { version = "1", features = ["net", "io-util"] }
tokio-util = "0.6.3"
```
I got the following error

```
2 | use tokio_util::time::DelayQueue;
  |                 ^^^^ could not find `time` in `tokio_util`
```

Turns out that there was feature for `time`, and I never read about in the documentation.
Maybe the docs need little help with that ? (or perhaps the feature should be enabled by default)

**Comment by Darksonn** [comment]
The fix for this would be adding the appropriate annotations on the `time` module and `DelayQueue` type such that it gets marked in the documentation as requiring the time feature.
