### ISSUE TITLE
Polling the reactor should return an io::Result

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#36]
Currently, polling the reactor does not return `io::Result`. This means that unexpected I/O errors result in a panic.

Ideally, the reactor would not panic due to external errors.

**Comment by Thomasdezeeuw** [comment]
Do mean the `Reactor::run` and `Reactor::turn` methods? If so I could make a PR if you like.

**Comment by alexcrichton** [comment]
@Thomasdezeeuw the `run` method is [slightly in flux](https://github.com/tokio-rs/tokio/pull/58) so mind holding off until that lands? Afterwards seems fine to just update the signature of the `turn` method!

**Comment by alexcrichton** [comment]
Done in https://github.com/tokio-rs/tokio/pull/40
