### ISSUE TITLE
EnterGuard<> must always be used

### ISSUE THREAD

**Issue by farazshaikh** [tokio-rs/tokio#3608]
**Version
tokio v1.3.0 (*)

**Platform**
all

**Description**
{
   handle.enter();  // IMO Never makes sense to immediately drop the handle.
    foo..
}

[short summary of the bug]
For "some" reason we ended up creating 2 runtimes in a project.
We used .enter() to specifically tie some code down to one of specific runtimes.
Missing the ```let _guard = `` part didn't get flagged by the compiler.
Overall caused some confusion as the code rightly didn't work as executed.

```
runtime {
   let nested_runtime = runtime::new
   nested_runtime::enter();   // missed the let binding. Intention was to use the nested runtime.
}
```

I expected to see this happen: 
The compiler should have warned, linter should have warned. Code should not have compiled.

Instead, this happened: 
Code compiled and didn't worked as intended.

**Comment by Darksonn** [comment]
Closed by #3609
