### ISSUE TITLE
Add static runtime

### ISSUE THREAD

**Issue by Bajix** [tokio-rs/tokio#3610]
**Is your feature request related to a problem? Please describe.**
I have various use cases in mind for batch processing tools built around the design pattern of using static_init to initialize unbound flume channels that simply collect messages in batches and execute batched tasks. This would be a loop while the channel is open within a tokio::task::spawn and process these tasks in a batched fashion by spawning a task per batch. For this to work, the Tokio runtime needs to be initialize first via static_init so now there's the question of can this be something an ecosystem is built around and if so can we modify Tokio as to make this easier and to encourage authors.

**Describe the solution you'd like**
Tokio could expose the runtime statically via static init and #[tokio::main] could use the static instance. This would make it such that Tokio would be available before main and any library author could leverage this as to make zero-cost statics.

**Describe alternatives you've considered**
Any project that doesn't want to wait for this to be added could simply use static_init to manually create the runtime and use that within main and this could probably be moved into a crate with some macro added for convenience. Any project that doesn't care about the overhead could use once_cell or lazy_static to abstract away the mutability dilemma at the cost of a 2ns overhead per call. These options are fine, but if Tokio standardizes this then maybe that leads to more adoption, more ecosystem development and better optimizations.

**Additional context**
Zero-cost static task batching via message passing feels like something that would give Rust the edge especially for GraphQL APIs that can get around the N+1 problem w/out much overhead via message passing & batch loading. There are a lot of use cases for initializing async things pre-main and likely this would lead to a very slight performance boost and hopefully get people to think more about using static message channels as an alternative to locks.

**Comment by Darksonn** [comment]
In Rust, we don't really have code that runs before main. Are you asking for the ability to put a `Runtime` in a `static` global variable?

**Comment by Bajix** [comment]
You're right, but maybe the Rust community *should* start having code that runs before main. Pre-main initialization is zero-cost and anything that is a static once_cell::sync::Lazy can instead be expressed without this overhead. If the runtime is static, then the runtime can be pre-main too, which by extension facilitates static async channels that need no lazy wrapper. This clearly enables optimizations that couldn't otherwise occur

**Comment by Darksonn** [comment]
I mean, if what you're looking for is channels, that could be done without necessarily requiring the runtime to be static. A channel typically does not depend on the runtime to function.

**Comment by Bajix** [comment]
Ok yes obviously this can be engineered around which I spoke to when opening this. Using a lazily initialized static with once_cell::sync::Lazy accomplishes what I'm looking for from a behavior perspective but my point is that there's a cost to this when there doesn't need to be. If I want to avoid relying on once_cell::sync::Lazy or parking_lot::once though and don't want to use request contextual type maps though then the only way to do this is via static_init both on the channels and on the Tokio runtime. Statics when used with pre-main initialization let us avoid the overhead here. It's a very small overhead, but it's not nothing, and the point is that it's an optional overhead that can be engineered around. Very minor gains are to be had

**Comment by Darksonn** [comment]
Making runtimes work in `static`s is either going to be very difficult or not possible. I don't think adding life-before-main to make it possible is worth it. 

Also, you misunderstood what I tried to say regarding channels. It would be possible to write an async message passing channel that can be stored in a `static` global, without the use of `Lazy` or `OnceCell`.

**Comment by Bajix** [comment]
> Making runtimes work in statics is either going to be very difficult or not possible. I don't think adding life-before-main to make it possible is worth it (and it could be done by an external crate).
Can you explain? I'm confused by why this would be the case; I think what I'm asking would be some variation of a wrapper around the below.

```
#[dynamic(drop)]
static RUNTIME: Runtime = unsafe { runtime::Builder::new_multi_thread()
    .worker_threads(4)
    .build()
    .unwrap() };

fn main() -> {
  RUNTIME.block_on(async move { .. })
}
```

> Also, you misunderstood what I tried to say regarding channels. It would be possible to write an async message passing channel that can be stored in a static global, without the use of Lazy or OnceCell.

How would this work in a way that doesn't involve parking_lot::once or some manual initialization? If I had a static channel then I would still need to move or clone the receiver into the tokio::task::spawn loop and so I would need a mechanism in order to do so. Presumably that would be parking_lot::once or std::sync::once, but I guess in my mind I have no way of differentiating the cost of this between this design and using once_cell::sync::Lazy as all of these are some sort of atomic usize bitwise state machine with a spin loop mechanism and I guess I assume all of these to have equivalent near 2ns overhead. The only way I see this as having no overhead is if it's constructed statically and the receiver startup part either happens then or later from other means; the question is if there's a means to start that after the tokio runtime is online in a way that has zero cost and that doesn't require some manual initialization invocation. I would be happy to find a way to do this that is zero cost and doesn't impose extra work on any would be end users were I to open source any batching tools.

**Comment by sfackler** [comment]
What is `#[dynamic(drop)]` supposed to be?

**Comment by MikailBag** [comment]
I think Darksonn's point regarding channels is that tokio channels do not use `Runtime` in any way, and they can be used with any other executor. So neither changes to Runtime API nor the introduction of the global runtime will make channels more usable in static contexts.

**Comment by Bajix** [comment]
I was using flume channels. Anyway I suppose yes I can define this statically but I can’t run tokio::task::spawn during initialization it I do so and so this imposes the need to do some post creation initialization or to delay initialization until I can use tokio::task::spawn. So I suppose channels aren’t the issue but the inability to use tokio::task::spawn on creation with static_init is.

**Comment by Darksonn** [comment]
You would need to spawn the task that receives from the static channel in your main function or something. The thing that this kind of static channel would allow is mostly the ability to access the channel's sender directly from the static whenever you need to send.

Spawning new tasks from a static function is just not going to be possible. For example, a quick test I just cooked up gives this:
```
error: `async` blocks are not allowed in statics
 --> src/lib.rs:6:24
  |
6 | static VAL: bool = foo(async move { println!("hi"); });
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

As for life-before-main, you can try to do it yourself with the [`ctor`][1] crate, but please note the following warning from the crate:

> The code that runs in the ctor and dtor functions should be careful to limit itself to libc functions and code that does not rely on Rust's stdlib services.

Tokio's runtime depends on Rust's stdlib services. For example, we spawn threads.

[1]: https://github.com/mmastrac/rust-ctor

**Comment by Bajix** [comment]
Is there a way to work around this by some other means? Say for instance adding a macro for eventual initialization once the runtime is online. If pre-main initialization and a static runtime is a non-starter, then making a way to do things run upon runtime initialization is the next best thing.

**Comment by Darksonn** [comment]
You can probably set up something that uses the [`inventory`][1] crate, which would allow you to put an annotation on various methods all over your program. You can then have a single method you call from your main function that looks up all instances of the annotation and does whatever initialization you want.

This would not even require any special support in Tokio. You could go ahead and do this now in a new crate.

In fact, I'm pretty sure that some of the web server libraries use this strategy for registration of routes.

[1]: https://docs.rs/inventory

**Comment by Bajix** [comment]
Ok that's a good alternative option. Thanks for your help and insights!
