### ISSUE TITLE
Documentation of `block_on` is unclear on where the future is run

### ISSUE THREAD

**Issue by malaire** [tokio-rs/tokio#3627]
Tokio 1.4.0

Documentation of `Handle::block_on` says (emphasis added)
> This runs the given future **on the runtime**, blocking until it is complete, and yielding its resolved result. Any tasks or timers which the future spawns internally will be executed **on the runtime**.

This is unclear because given future is run in the current thread and not in threadpool of the runtime while any spawned tasks are run in threadpool of the runtime. Using "on the runtime" to describe these two different behaviors is wrong in my opinion.

`Runtime::block_on` has the same issue.

**Comment by Darksonn** [comment]
Thanks for pointing this out.
