### ISSUE TITLE
TcpStream::connect is refused in special circumstances 

### ISSUE THREAD

**Issue by 36k-wild-monkey** [tokio-rs/tokio#3632]
## c language call pseudo code 
```C
int g_conn_num = 0;

void on_connect(int conn_id) {
  InterlockedExchangeAdd(g_conn_num, 1);
  printf("%d",g_conn_num );
}
void on_receive(int conn_id, char* msg, int msg_size) {
}
void on_on_close(int conn_id) {
}
void on_on_fail(int conn_id) {
}
void on_run() {
  for(int i=0; i<12000; i++) {
    tcp_connect("127.0.0.1:5000","", on_connect, on_receive, on_close, on_fail);
  }
  sleep(99999);
}

void main() {
   schedule_run(15, 30, 5*1024*1024, on_run);
}

```
[test project](https://gitee.com/wlp_sixsixsix/websocket-epl/tree/master/rust%E5%B0%81%E8%A3%85%E7%89%88/rs-ws)

tokio: 1.3.0

1. I use rust to compile and export dynamic libraries to C language, but there will be a lot of connection errors   
2. The problem is at the `inner_tcp_connect` function on lines 508-513 of `src/lib.rs`. If you use `TcpStream::connect(address)`, there will be a lot of connection failures. If you change to the following code, all of them are correct. 

```rust
    let std_stream = std::net::TcpStream::connect(address);
    if let Err(_) = std_stream {
        return Err(Error::from(ErrorKind::ConnectionRefused));
    };
    //     std_stream.set_nonblocking(true)?;
    let conn = TcpStream::from_std(std_stream.unwrap());
```

**Comment by Darksonn** [comment]
So just to understand you, it doesn't work when it looks like this?
```Rust
let conn = TcpStream::connect(address).await;
if let Err(_) = conn {
    return Err(Error::from(ErrorKind::ConnectionRefused));
};
let stream = conn.unwrap();
```
In what way does it fail?

**Comment by 36k-wild-monkey** [comment]
The code is tested under win10 x64, `TcpStream::connect(address)` returns ConnectionRefused, error message 10061

**Comment by Darksonn** [comment]
Since the async version is not [blocking the thread][1], so you are going to have all 12000 connect calls running at the same time, whereas the blocking version is rate limited to at most 15 at the time, as that is the number of worker threads in your runtime.

[1]: https://ryhl.io/blog/async-what-is-blocking/

**Comment by 36k-wild-monkey** [comment]
> Since the async version is not [blocking the thread](https://ryhl.io/blog/async-what-is-blocking/), you are going to have all 12000 connect calls running at the same time, whereas the blocking version is rate limited to at most 15 at the time, as that is the number of worker threads in your runtime.

```rust
    let conn = tokio::net::TcpStream::connect(address).await;
    if let Err(_) = conn {
        return Err(Error::from(ErrorKind::ConnectionRefused));
    };
    println("connection");
```
So how do I get the correct stream? Now only part of this code can be connected successfully, and the connection must be repeated repeatedly.

**Comment by Darksonn** [comment]
What do you mean by "correct stream"?

**Comment by Darksonn** [comment]
The correct solution is probably to rate limit the opening of connections. You can do this with a [`Semaphore`][1].
```Rust
// Using 20 for upper limit on number of parallel connections.
static CONNS_LIMIT: Semaphore = Semaphore::const_new(20);
```
```Rust
// Wait for one of the 20 permits to become available.
let permit = CONNS_LIMIT.acquire().await.unwrap();

let conn = TcpStream::connect(address).await;
if let Err(_) = conn {
    return Err(Error::from(ErrorKind::ConnectionRefused));
};
let stream = conn.unwrap();

drop(permit); // allow another connection to be opened
```

[1]: https://docs.rs/tokio/1/tokio/sync/struct.Semaphore.html

**Comment by 36k-wild-monkey** [comment]
## mio/src/net/tcp/stream.rs
```rust
impl TcpStream {
    /// Create a new TCP stream and issue a non-blocking connect to the
    /// specified address.
    pub fn connect(addr: SocketAddr) -> io::Result<TcpStream> {
        let socket = TcpSocket::new_for_addr(addr)?;
        socket.connect(addr)
    }
  ....
}
```
## mio/src/net/tcp/socket.rs
```rust
impl TcpSocket {
    ....
    pub fn connect(self, addr: SocketAddr) -> io::Result<TcpStream> {
        let stream = sys::tcp::connect(self.sys, addr)?;

        // Don't close the socket
        mem::forget(self);
        Ok(TcpStream::from_std(stream))
    }
  ....
}
```
## mio/src/sys/windows/tcp.rs
```
pub(crate) fn connect(socket: TcpSocket, addr: SocketAddr) -> io::Result<net::TcpStream> {
    use winsock2::connect;

    let (raw_addr, raw_addr_length) = socket_addr(&addr);

    let res = syscall!(
        connect(socket, raw_addr.as_ptr(), raw_addr_length),
        PartialEq::eq,
        SOCKET_ERROR
    );

    match res {
        Err(err) if err.kind() != io::ErrorKind::WouldBlock => {
            Err(err)
        }
        _ => {
            Ok(unsafe { net::TcpStream::from_raw_socket(socket as StdSocket) })
        }
    }
}
```
Isn't TcpStream thread safe? I looked at the mio code and found that the socket is not set to noblock, and `ioctlsocket` or `setsockopt` is not called.

**Comment by Darksonn** [comment]
It is thread safe. The problem is most likely that the server you are connecting to does not support that many connections at the same time.

**Comment by Darksonn** [comment]
One way to see this is to note that 10061 means that you could not make a connection because the target machine actively refused it.

**Comment by 36k-wild-monkey** [comment]
The test tool I use is "sokit-1.3-win32-enu". I have changed many tools and it is the same. Now it seems that it is a problem with the testing tool. The problem is solved, thank you
