### ISSUE TITLE
tokio_threadpool::blocking cannot be used in libraries due to existence of alternative runtimes

### ISSUE THREAD

**Issue by bluetech** [tokio-rs/tokio#364]
Context: https://github.com/hyperium/hyper/pull/1514

Hyper uses `futures_cpupool` for performing blocking DNS resolving. I thought it'd be a good idea to replace it with `blocking()`. However, hyper needs to work under alternative runtimes, like the `current_thread` one, where `blocking` doesn't work (`BlockingError` is returned immediately), so hyper can't use `blocking`, or share the already-existing tokio thread pool for that matter. Is this a correct analysis? Should this be mentioned in the docs?

Additionally, since `tokio-fs` uses `blocking` internally, does it mean that `tokio-fs` can't be used in libraries like hyper?

**Comment by carllerche** [comment]
That is correct, tokio-fs requires tokio runtime. Unfortunately, there isn't much that can be done as the strategy used to provide the blocking interface requires tight integration with the executor.

I'm going to close this issue as I don't think that it is actionable. If you have further questions, feel free to reply.
