### ISSUE TITLE
Feature: async file I/O on Linux via AIO

### ISSUE THREAD

**Issue by dbkaplun** [tokio-rs/tokio#366]
Hello,

I just found [this article](http://kkourt.io/blog/2017/10-14-linux-aio.html) that states that asynchronous I/O on Linux is possible. I don't know enough about the subject but I wanted to open discussion as I feel this functionality may be useful for some.

Would it be possible to implement Linux-specific methods in tokio-fs for non-blocking file operations?

**Comment by tikue** [comment]
According to [this article](https://lwn.net/Articles/724198/) AIO is not guaranteed to be nonblocking:

> The Linux asynchronous I/O (AIO) layer tends to have many critics and few defenders, but most people at least expect it to actually be asynchronous. In truth, an AIO operation can block in the kernel for a number of reasons, making AIO difficult to use in situations where the calling thread truly cannot afford to block.

**Comment by carllerche** [comment]
I was thinking that you could use the `blocking` API to manage syscalls that did, in fact, sometime block. This way, the total amount of blocking would be minimized, but you could still deal w/ the random blocks.

That said, this is very low priority for me personally. If somebody else wants to experiment with this, great. However, I am going to close this to try to keep the issue tracker (somewhat) clean.

**Comment by dbkaplun** [comment]
For the sake of posterity, will you accept a PR for this change?

**Comment by carllerche** [comment]
There is a path to getting such a commit included in Tokio.

Ideally, it would eventually be encapsulated in `tokio-fs` somehow. However, a first step would probably be a separate crate that explores the space. Then, once something is working, we can evaluate a path to getting it included.

I personally do not have much experience w/ Linux's async I/O. So, I would need to dig more into the details to get more specific.
