### ISSUE TITLE
util: `PollSemaphore` should expose `available_permits`

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#3682]
**Is your feature request related to a problem? Please describe.**
The `tokio::sync::Semaphore` type provides a [`Semaphore::available_permits` method](https://docs.rs/tokio/1.4.0/tokio/sync/struct.Semaphore.html#method.available_permits) which returns the current number of permits available on the semaphore. `tokio_util::sync::PollSemaphore` [does not expose such a method](https://docs.rs/tokio-util/0.6.5/tokio_util/sync/struct.PollSemaphore.html#implementations). It is possible to use `PollSemaphore::into_inner` or `PollSemaphore::clone_inner` to unwrap the inner semaphore, but this may require cloning/dropping the semaphore's `Arc` which shouldn't be necessary to access the permits.

**Describe the solution you'd like**
We should add a `PollSemaphore::available_permits` that calls `Semaphore::available_permits` on the inner `Semaphore`. We could probably also add a `PollSemaphore::add_permits` method while we're here. This should be pretty trivial to add.

**Describe alternatives you've considered**
Alternatively, we could just add a `PollSemaphore::inner_ref` or similar method for borrowing the inner `Semaphore`. `PollSemaphore` could even implement `AsRef<Semaphore>`.

This might be a little more complex to use (`semaphore.as_ref().available_permits()` vs `semaphore.available_permits()`) and is less visible in the API docs, but it would let us easily expose _all_ the methods on the inner type transparently without having to wrap them. This could be both a pro or a con, if there are methods of the inner `Semaphore` type that `PollSemaphore` should not expose...

**Comment by Darksonn** [comment]
I thought we already had an `impl AsRef<Semaphore> for PollSemaphore`, but I see that it is missing. It would be nice to add that too.
