### ISSUE TITLE
Suggestions for `blocking` API around `read_dir`

### ISSUE THREAD

**Issue by stuhood** [tokio-rs/tokio#369]
We have usages of `Path::{read_dir,read_link}` and `std::fs::symlink_metadata` that it would be nice to be able to execute directly on a tokio Runtime via the blocking API.

Should these be incorporated into `tokio_fs`? If so, where?

If we should write them in our consumer, I think I might need to wait for #339, as `impl Read for tokio::fs::file::File` seems to require access to internal APIs (`::would_block`).

**Comment by olix0r** [comment]
> Should these be incorporated into tokio_fs?

I nominate yes

**Comment by stuhood** [comment]
@olix0r : Sounds good! I might take a swing at this this weekend, but if you have any thoughts on where this should go, let me know.

One bit of inspiration might be `tokio-process`: [CommandExt](https://docs.rs/tokio-process/0.2.0/tokio_process/trait.CommandExt.html) extends `std::process::Command` with `async` versions of a few methods. A `tokio_fs::PathExt` might make sense for these...?

@alexcrichton: Have you been happy with the `CommandExt` pattern?

**Comment by alexcrichton** [comment]
I've personally been happy with `FooExt` patterns, yeah

**Comment by carllerche** [comment]
@stuhood So, I have looked through the existing Tokio crates, and currently the `*Ext` trait pattern has not been used. I also don't love how you create a `std::Command` and can accidentally call `spawn` instead of `spawn_async`.

I would vote to avoid the ext pattern and to duplicate `std` types as needed. Basically, if the type has any fn that can block, to create an async equivalent in `tokio-fs`.

Thoughts?

**Comment by stuhood** [comment]
Sorry for licking the cookie here... I am unlikely to get a chance to work on this anytime soon.

One additional thought I've had on this though is that executing a sequence of blocking operations within a `blocking` block seems like a very likely pattern. As a concrete example: "running `std::fs::read_dir` and then inspecting all entries in the directory". Many components of that are blocking, and introducing task/thread-management overhead per-method call there would likely be overkill.

A literal `blocking` block is useful for that case, and also avoids overhauling a bunch of APIs unnecessarily.

**Comment by stuhood** [comment]
It looks like all of the methods that were relevant to us are now implemented: thanks!

I'll watch #339, #629, and #726 regarding the other question. Thanks!
