### ISSUE TITLE
TcpSocket::from_std

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3734]
Currently the only way to convert a socket2 socket into a `TcpSocket` is the platform-dependent `FromRawFd` or `FromRawSocket` methods. Can we do better?

**Comment by aym-v** [comment]
Would this comment about transitive dependencies also apply to this? -> https://github.com/tokio-rs/mio/pull/1431#issuecomment-763861677

**Comment by Darksonn** [comment]
I mean, we should probably just have a `from_std` method. We definitely don't want `socket2` in our public API.
