### ISSUE TITLE
tokio_fs stdin does not work interactively

### ISSUE THREAD

**Issue by euclio** [tokio-rs/tokio#374]
Not sure if this is some OS-level trickery or a bug in tokio-fs stdin implementation.

I'm running the tokio-fs std-echo example on my MacOS machine, and I notice that stdin is flushed to stdout when piping, but lines entered interactively are not echoed. I also tried using the following code to the same effect:

```rust
pub fn main() {
    let pool = Builder::new()
        .pool_size(1)
        .build();

    pool.spawn({
        let input = FramedRead::new(stdin(), BytesCodec::new())
            .map(|bytes| bytes.freeze());

        let output = FramedWrite::new(stdout(), BytesCodec::new());

        input
            .forward(output)
            .map(|_| ())
            .map_err(|e| panic!("io error = {:?}", e))
    });

    pool.shutdown_on_idle().wait().unwrap();
```

**Comment by carllerche** [comment]
The tokio-fs implementation is a very light wrapper over the implementation in rust. Does interactive work with blocking stdin?

**Comment by euclio** [comment]
This works as expected:

```rust
use std::io;

fn main() {
    let mut stdin = io::stdin();
    let mut stdout = io::stdout();

    io::copy(&mut stdin, &mut stdout).unwrap();
}
```

**Comment by carllerche** [comment]
Instead of using the framing helpers, could you try: https://docs.rs/tokio/0.1.6/tokio/io/fn.copy.html

That should keep it as close as possible to the other.

**Comment by euclio** [comment]
Ok, this code works:

```
//! Echo everything received on STDIN to STDOUT.

extern crate tokio;
extern crate futures;
extern crate tokio_fs;
extern crate tokio_io;
extern crate tokio_threadpool;
extern crate termion;

use tokio_fs::{stdin, stdout};
use tokio_threadpool::Builder;

use futures::Future;

pub fn main() {
    let pool = Builder::new()
        .pool_size(1)
        .build();

    pool.spawn({
        tokio::io::copy(stdin(), stdout()).map(|_| ()).map_err(|e| panic!("{}", e))
    });

    pool.shutdown_on_idle().wait().unwrap();
}
```

I wonder why the framing helpers don't, though?

**Comment by carllerche** [comment]
There is probably some buffering logic (or bug)? Maybe you can try to dig into the implementations to see if you can figure it out?

**Comment by euclio** [comment]
I'm also noticing some strange behavior with signals:

```
extern crate futures;
extern crate libc;
extern crate tokio;
extern crate tokio_fs;
extern crate tokio_io;
extern crate tokio_signal;

use futures::{Future, Stream};
use tokio_io::codec::{FramedRead, LinesCodec};
use tokio_signal::unix::Signal;

#[derive(Debug, PartialEq, Eq)]
enum Event {
    Line(String),
    Signal(libc::c_int),
}

fn main() {
    let done = futures::lazy(|| {
        let stdin = FramedRead::new(tokio_fs::stdin(), LinesCodec::new()).map(|l| Event::Line(l));
        let signals = Signal::new(libc::SIGWINCH)
            .flatten_stream()
            .map(|s| Event::Signal(s));
        Ok(stdin.select(signals))
    }).and_then(|events| {
        events.map_err(|e| panic!("{}", e)).for_each(|e| {
            println!("{:?}", e);
            Ok(())
        })
    });

    tokio::run(done);
}
```

In this example, `SIGWINCH` never appears in the event stream, even when sent directly. Compare with just streaming `Signal` without stdin.

**Comment by Marwes** [comment]
I am not sure exactly how this manifests due to the use of codec but I believe that the underlying problem is that one can't use `blocking` on a task which concurrently needs to do some other work. In this case the bytes from stdin will be read and sent to the encoder, however they will not be sent to stdout until `poll_complete` is called on the encoder. In the example the `forward` future is used to both read from the decoder and write to the encoder but `forward` does not call `poll_complete` until the decoder returns `NotReady` (it tries to take as many elements as possible from the stream to start sending them before actually calling `poll_complete`). But since `blocking` is used that will never happen.

I don't believe this is fixable, the best workaround I have found is to use a channel as an intermediary so that `blocking` operations are put on their own task with `spawn`

**Comment by carllerche** [comment]
This is definetly annoying. I agree that there is no obvious immediate fix. Except maybe forward fn should be tweaked. That is in the futures repo, so I am going to close this issue

**Comment by Marwes** [comment]
The only way I can see to "fix" forward is to make it run `poll_complete` after each sent item. But that would be a bad idea for throughput as it would make to encoder write to stdout (or the socket, file, etc) for each item. Pushing multiple items at once gives the sink control over how much data it can take  before it sends it on which can greatly increase throughput (if the sinks buffer is full it can send it in a `start_send` call to flush it and make room).

**Comment by euclio** [comment]
Yeah, this is an interesting case because I *do* want the sink flushed after each send. So maybe there is a need for a sink that does that.

**Comment by Marwes** [comment]
> Yeah, this is an interesting case because I do want the sink flushed after each send. So maybe there is a need for a sink that does that.

@euclio I am curious, Could you elaborate on that?

**Comment by euclio** [comment]
This was part of a terminal UI that I was writing, so I was using a stdout as a `Sink` to send ANSI escape sequences to. However, I wanted to flush stdout after each send, because I wanted it to be immediately displayed to the user.

**Comment by Marwes** [comment]
It will still display "immediately" though. It is only if there are more things to read from the stream that it will hold try to send more. So for a interactive session the stream would return `NotReady` as soon as there is not anything more to send (at the moment) and then run `poll_complete`

**Comment by carllerche** [comment]
synchronous programming as the same problem. I believe that, in that case, one has to flush before each read.
