### ISSUE TITLE
Fix documentation of PollEvented

### ISSUE THREAD

**Issue by MarcoIeni** [tokio-rs/tokio#3746]
The [PolledEvent](https://github.com/tokio-rs/tokio/blob/14bb2f624f1ac3d440dd302219a48e9e8e926b50/tokio/src/io/poll_evented.rs#L62-L66) struct documentation needs to be reviewed.
For example, it refers to the functions `clear_write_ready` and `clear_read_ready` which do not exist.

I opened this issue from [this](https://github.com/tokio-rs/tokio/pull/3715#issuecomment-825185848) discussion.

**Comment by MarcoIeni** [comment]
Sorry, I did a mistake by opening this as a bug. Can you remove the "bug" label? Thanks.

**Comment by Darksonn** [comment]
I adjusted the labels.
