### ISSUE TITLE
No good way to reliably notify all consumers about a change

### ISSUE THREAD

**Issue by arthurprs** [tokio-rs/tokio#3757]
**Is your feature request related to a problem? Please describe.**

Consider an use-case where a producer wants to notify consumers about a change, even if they were doing something else at the time of the notification.

At first Notify and Notify::notify_waiters seem like a fit, but it's not. Because notify_waiters doesn't make the permit available for waiters that are not waiting at the time of the notification.

C: subscribe to S by cloning the Notify
P: `notifier.notify_waiters()`
C: `notifier.notified().await` <<< waits even if the permit was provided above

**Option 1**

One way to get the expected behavior is to use a broadcast channel with capacity of 1.

C: subscribe to S by calling `sender.subscribe()`
P: `sender.send(())`
C: `receiver.recv().await` <<< wakes up correctly, with either `Err(Lagged(_))` or `Ok(())`

This works but involves a a couple locks inside the Broadcast channel unnecessarily.

**Option 2**

A `Watch` works too but it's unergonomic to keep both `Sender` and `Receivers` around, as there's no equivalent to `subscribe()`

**Describe the solution you'd like**

**Option 1**

Add `Notifier::notify_all` which will notify all existing waiters, not only the ones awaiting.

**Option 2**

Consider exposing `Watch::subscribe` which already exists internally. With it this use case can be modeled ergonomically/performantly with a `Sender::subscribe()` + `Receiver::changed().await`

https://github.com/tokio-rs/tokio/blob/d4075a445770bd5f4982006ec6f7b60d3fb6373e/tokio/src/sync/watch.rs#L413-L413

**Describe alternatives you've considered**

See description above, which mentions 2 options, each with its set of drawbacks.

**Additional context**

I did find #3066 seems to describe a similar need but was closed with a partial(?) solution in the form of `Notifier::notify_awaiters` which only takes into account current waiters.

**Comment by Darksonn** [comment]
> Add `Notifier::notify_all` which will notify all existing waiters, not only the ones awaiting.

This is not possible because unlike the channels, the `Notify` utility does not know how many waiters there are. It is shared by putting it in an `Arc`, not by cloning the `Notify` itself.

**Comment by Wesmania** [comment]
Would changing signature of `notified` to `fn(&self) -> impl Future<Output = ()> + '_` help? This way, `Notified` struct could insert itself into a waiter queue immediately and could be used like so:

```rust
struct Event {
    occured: Arc<Mutex<bool>>,
    notify: Notify,
}

impl Event {
    fn set(&self) {
        *self.occured.lock().unwrap() = true;
        self.notify.notify_waiters();
    }

    fn wait(&self) -> impl Future<()> {
        let guard = self.occured.lock().unwrap();
        let wait = self.notify.notified();
        let occured = *guard;
        async move {
            if occured {
                return;
            } else {
                wait.await;
            }
    }
}

```

**Comment by arthurprs** [comment]
Something like that works, and is very similar to Watch with no value. But `occurred` needs to be a counter (that is also tracked in Event) so each Event instance can track if it's up to date or not.

**Comment by Wesmania** [comment]
Actually I'm wrong, `notify` already works like that since `Notified` is constructed as part of the future. Sorry for the confusion.

**Comment by Darksonn** [comment]
The `subscribe` method has been exposed on the watch channel, so I'm closing this.
