### ISSUE TITLE
tokio::io::copy should return error when writer broken

### ISSUE THREAD

**Issue by cssivision** [tokio-rs/tokio#3759]
**Version**
tokio 1.5.0

**Platform**
Darwin Kernel Version 17.5.0

**Description**
This is the current poll method for `tokio::io::copy`.
 
https://github.com/tokio-rs/tokio/blob/adad8fc3cdeffb6449edac55558510f4d12c95be/tokio/src/io/util/copy.rs#L28-L76

if `reader` alway return `Pending`, we register the waker and waiting for data ready and wake the task again, but we never touch `writer` until we can read some data from the reader.  if writer broken for some reason, nothing happen, in this situation we should return error.

I think we should call poll_read and poll_write during this poll, either IO resource has returned error,  tokio::io::copy should return error.

**Comment by Darksonn** [comment]
How would you do that? Attempt a write of zero bytes?
