### ISSUE TITLE
Consider making `DefaultExecutor` be `Send + Sync`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#376]
Right now, it cannot be used from the context of the default runtime. It should be backwards compatible to make this change.

**Comment by srijs** [comment]
I'd be interested in picking this up. Could you provide some more details on what the expected behaviour should be? For instance, if I send `DefaultExecutor` from thread A to thread B, and then spawn a future onto it, does it just use the TLS variable that was set on thread B at the time?

**Comment by carllerche** [comment]
I don’t think so. I believe that DefaultExecutor should be equivalent to tokio::spawn. So, id just call spawn on whatever the current tls var is set to and return an error if non is set.

**Comment by srijs** [comment]
Looks like this can be closed now after merging #472!
