### ISSUE TITLE
SignalKind::from_raw leaks a non-stable type alias from libc

### ISSUE THREAD

**Issue by udoprog** [tokio-rs/tokio#3767]
**Version**
1.5.0

**Platform**
Unix

**Description**

We have a type alias from an unstable `libc` that's leaking through a public API here (`c_int`):
https://docs.rs/tokio/1.5.0/tokio/signal/unix/struct.SignalKind.html#method.from_raw

Given that it's an alias I don't think there's any inherent issues with changing it to a ~~`RawFd` <https://doc.rust-lang.org/std/os/unix/io/type.RawFd.html>~~ [`c_int` from std](https://doc.rust-lang.org/std/os/raw/type.c_int.html). The hazard of keeping it is that `tokio` `1.x` is now tied to only use future versions of `libc` which exports a compatible type alias.

**Comment by Darksonn** [comment]
Changing it to [`std::os::raw::c_int`][1] or something would probably be good. I can't imagine that the alias in std will ever differ from the one in libc, so I think this is safe enough to do.

[1]: https://doc.rust-lang.org/std/os/raw/type.c_int.html

**Comment by Darksonn** [comment]
Hmm. Does `c_int` differ on any platforms we support?

**Comment by taiki-e** [comment]
If I haven't missed anything, it seems the current c_int always is i32: [std](https://github.com/rust-lang/rust/blob/d6d028369be9eb02d219506c0dd662a2f863fc18/library/std/src/os/raw/mod.rs#L136), [libc](https://github.com/rust-lang/libc/search?q=%22pub+type+c_int%22)

**Comment by ipetkov** [comment]
I don't anticipate the `c_int` type used by libc to ever change, but even if it does, I doubt there will be platforms which have so many signals that can't be fit into a i32. I'm fine with replacing the alias with `std::os::raw::c_int`
