### ISSUE TITLE
Incompatibility between CurrentThread and generic spawning

### ISSUE THREAD

**Issue by djc** [tokio-rs/tokio#377]
In my library, I want to spawn tasks onto whatever the current run-time is, during execution. For testing, I'd like to be able to spawn a server (which does not complete) and a client (which should run to completion). If I use `CurrentThread` for the latter, `tokio::spawn()` from any of the running tasks will fail with `SpawnError { is_shutdown: true }` (which I find very non-intuitive). If I start a `Runtime` instead, it appears that there is no (simple) way of getting something like `block_on()` or `block_on_all()` that will let the runtime gracefully shutdown on a subset of the spawned tasks.

**Comment by djc** [comment]
So possibly what I'm asking is just: would it be reasonable to let `tokio::spawn()` spawn on the `CurrentThread` iff `DefaultExecutor::spawn()` returns `SpawnError { is_shutdown: true }`?

**Comment by carllerche** [comment]
There now is a current thread runtime, which does all the necessary setup: https://docs.rs/tokio/0.1.6/tokio/runtime/current_thread/index.html. I would recommend using this for tests (it has `block_on`).

The current_thread executor, just like threadpool, is a lower level building block. This is why it doesn't set `DefaultExecutor` by default. There probably should be some easy way for it to set itself as the default executor, but I haven't focused on this. The main issue is that it should be possible to use the current_thread executor but have the default executor set to something else (like a thread pool).

Hope this answers your question. You should just be able to call `DefaultExecutor::spawn()`.

PS: It probably would be a good idea to have a "no executor specified" error variant. Thoughts? Maybe open a new issue to discuss this.

Slightly related: #376

**Comment by djc** [comment]
Using the `current_thread::Runtime` seems to solve my problem for now. I briefly looked around and it looks like it's not very accessible from other parts of the documentation. Perhaps the documentation for `current_thread::Executor` should mention it, for example? The module-level documentation for `tokio::runtime` also doesn't mention it. I got to looking at executors because the documentation for `tokio::spawn()` refers to them. Maybe that should point to runtimes first?

I've filed an issue about getting a better error as #382.

**Comment by ashthespy** [comment]
Seem to be also running into a similar issue, an unsure how to proceed.
I am trying to span a main future, using `current_thread::Runtime`, and then use the `current_thread::TaskExecutor` and `spawn_local` to spawn new futures. This however doesn't seem to work. What am I doing wrong? 

Pseudo code:
```Rust
use tokio::runtime::current_thread::{Runtime, TaskExecutor};

// Main task
let mut runtime = Runtime::new().unwrap();
let fut = fut_task();
runtime.block_on(fut()).unwrap()

// Sub task
<Snip>
// Spawn a future on the main fut
TaskExecutor::current().spawn_local(Box::new(f));
// Which fails with 
Status: Err(SpawnError { is_shutdown: true })
```
