### ISSUE TITLE
tokio::select compiler help message sometimes missing

### ISSUE THREAD

**Issue by soerenmeier** [tokio-rs/tokio#3779]
**Is your feature request related to a problem? Please describe.**
This is not a problem but a misleading error.
When checking the following code (just a simplification):
```rust
tokio::select! {
    _ = &mut fut => {},
    _ = &mut fut if cond => {}
}
```
I received the following error:
```
error: no rules expected the token `}`
  --> src/main.rs:12:2
   |
12 | /     tokio::select! {
13 | |         _ = &mut fut => {},
14 | |         _ = &mut fut if cond => {}
15 | |     }
   | |_____^ no rules expected this token in macro call
```
My first though was that I missed some brackets, after finally looking at the docs I noticed the comma is missing.  
After playing with it a bit I found that there exists a helpful error message:
```rust
tokio::select! {
    _ = &mut fut => {},
    _ = async {} if cond => {}
}
```
```
error: no rules expected the token `}`
  --> src/main.rs:12:2
   |
12 | /     tokio::select! {
13 | |         _ = &mut fut => {},
14 | |         _ = async {} if cond => {}
15 | |     }
   | |_____^ no rules expected this token in macro call
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: missing comma here
   |
14 |         _ = async {},  if cond => {}
```
**Describe the solution you'd like**
It would be nice if that help message would be displayed with this code as well:
```rust
tokio::select! {
    _ = &mut fut => {},
    _ = &mut fut if cond => {}
}
```
Can this even be fixed in tokio itself or should this be filled in rust?

**Comment by Darksonn** [comment]
I don't think this is possible without turning it into a proc-macro.

**Comment by soerenmeier** [comment]
Good to know, i've posted a question on [reddit](https://www.reddit.com/r/rust/comments/naml7r/compiler_help_message_not_always_showing_up_in/) asking if this could be fixed in rust. Will close this later today.
