### ISSUE TITLE
Assertion failed: cx_core.is_none()

### ISSUE THREAD

**Issue by freesig** [tokio-rs/tokio#3796]
**Version**
tokio v1.6.0

**Platform**
`Linux pop-os 5.8.0-7630-generic #32~1605108806~20.10~7e52b13-Ubuntu SMP Wed Nov 11 19:10:30 UTC  x86_64 x86_64 x86_64 GNU/Linux`

**Description**

[short summary of the bug]
When running `block_on` from within a `block_in_place` I sometimes get `assertion failed: cx_core.is_none()` [here](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/thread_pool/worker.rs#L190).
The `block_in_place` is being called from a wasmer host function call.
[This](https://github.com/holochain/holochain/blob/d16477e04b0a0266642e105d85e4bb4cf3d5070e/crates/holochain/src/core/ribosome/host_fn/get.rs#L23) is the place is our codebase where this is showing up.

Unfortunately this result is flaky and I haven't found a reliable way to reproduce this. It also seems to show up more often in release builds.
I know this isn't an ideal bug report, I'd love to have some smaller code that reproduces this. I might need some guidance as to what conditions cause this assert to fail so I can reproduce the problem a little easier.

**Comment by freesig** [comment]
Ok some more information. I tried moving the `block_in_place` to before the wasmer calls but the error shows up so perhaps this has nothing to do with wasmer.
I think it might be something to do with calling `runtime.block_on` from within a `block_in_place` but its showing up so infrequently that it's hard to tell. 
I'm going to write some more tests to try and flush it out and will report the results back here.

**Comment by carllerche** [comment]
This is very strange. I reviewed the code in Tokio. Because it relates to thread-local state, there should be no concurrency factor. I also reviewed the relevant code paths and am not sure how that assertion could be hit.

Does wasmer have its own thread or thread-local implementation?

**Comment by freesig** [comment]
After some more investigation I found [another](https://github.com/holochain/holochain/blob/d16477e04b0a0266642e105d85e4bb4cf3d5070e/crates/holochain_sqlite/src/db.rs#L48) `block_in_place` in our code base that was causing this. After removing it the issue has gone away. It was being called from the wasmer side so I suspect there must be something odd with the wasmer threads and as you suggest perhaps the thread-local is handled in an odd way there.
I'm not really sure where to go with this issue now, perhaps it's an issue with wasmer and not tokio anyway so maybe it can be closed.

**Comment by Machine90** [comment]
I've found this comment in "std::thread::local::statik::key" (__StaticLocalKeyInner): "On some platforms like wasm32 there's no threads, so no need to generate thread locals and we can instead just use plain statics!". I guess this is the root cause.
