### ISSUE TITLE
epoll_fd leaks to child processes

### ISSUE THREAD

**Issue by Tim-Zhang** [tokio-rs/tokio#3809]
**Version**
\>= 0.3

**Platform**
Linux k 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description**

I tried this code:

```
use nix::unistd;
use std::ffi::CString;

fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?;

    rt.block_on(async {
        let path = CString::new("/usr/bin/sleep").unwrap();
        let args = vec![
            CString::new("sleep").unwrap(),
            CString::new("500000").unwrap(),
        ];
        let envs: Vec<&CString> = Vec::new();
        unsafe {
            match unistd::fork().unwrap() {
                unistd::ForkResult::Parent { child: _, .. } => {
                    println!("{}", "hehe");
                }
                unistd::ForkResult::Child => match unistd::execve(&path, &args, &envs) {
                    Err(_e) => {
                        std::process::exit(1);
                    }
                    _ => unreachable!(),
                },
            };
        }

        tokio::time::sleep(std::time::Duration::from_secs(10000)).await;
    });

    Ok(())
}
```
start the program then check fds.

```
tim@k:~$ ps aux|grep sleep
tim       279808  0.0  0.0   2516   592 pts/0    S+   13:44   0:00 sleep 500000
tim       281141  0.0  0.0   2516   584 ?        S    13:46   0:00 sleep 180
tim       281419  0.0  0.0  17672   728 pts/5    S+   13:47   0:00 grep --color=auto sleep

tim@k:~$ ls -l /proc/279808/fd
total 0
lrwx------ 1 tim tim 64 May 25 13:44 0 -> /dev/pts/0
lrwx------ 1 tim tim 64 May 25 13:44 1 -> /dev/pts/0
...
lrwx------ 1 tim tim 64 May 25 13:44 7 -> 'anon_inode:[eventpoll]'
...
```

The fd of epoll was mistakenly leaked to the child process

**Comment by Tim-Zhang** [comment]
@Darksonn This issue was closed by pr merged, but the problem still exist until the version released, Can you reopen it?

**Comment by Darksonn** [comment]
I will reopen this pending the backport in https://github.com/tokio-rs/mio/pull/1495, but once the backport is merged we will close it. We usually do not keep issues open just because the fix is still pending a release.

**Comment by Thomasdezeeuw** [comment]
I've merged the pr on Mio side, want a new release for it? Or does anyone have any pending changes to Mio?

**Comment by Darksonn** [comment]
Go ahead and make a release for it.

**Comment by Tim-Zhang** [comment]
@Thomasdezeeuw @Darksonn Thanks.

**Comment by Thomasdezeeuw** [comment]
Publish Mio v0.7.12, also fixed it for kqueue in commit https://github.com/tokio-rs/mio/commit/b367a05e408ca90a26383c3aa16d8a16f019dc59, pr for master: https://github.com/tokio-rs/mio/pull/1496.

**Comment by Thomasdezeeuw** [comment]
For people still keeping track, v0.7.12 of Mio was yanked, but v0.7.13 (just released) fixes this.

**Comment by Tim-Zhang** [comment]
Thank you @Thomasdezeeuw , I have updated the mio and everything is ok.
