### ISSUE TITLE
io: write_all panics if underlying AsyncWrite returns value larger than provided bytes size

### ISSUE THREAD

**Issue by edward-shen** [tokio-rs/tokio#3819]
**Version**
v1.6.0

**Platform**
`Linux kurante 5.12.4-zen1-2-zen #1 ZEN SMP PREEMPT Sat, 15 May 2021 20:58:03 +0000 x86_64 GNU/Linux`

**Description**

The `write_all` call from `AsyncWriteExt` will panic if the underlying `AsyncWrite` implementation returns a value larger than the length of the buffer that was to be written.

[Playground link.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=77353482098b70383209700863586a9e)

This was eventually traced down to an unmentioned invariant that `AsyncWrite::write` assumes that a successful write is between `0 <= n <= buf.len()`.

The easiest fix would be to mention this invariant in the docs, which I'd be happy to do if you'd like.

**Comment by Darksonn** [comment]
The documentation requires that "`Poll::Ready(Ok(n))` means that `n` bytes of data was immediately written." It doesn't really make sense for `n` be larger than the length of the buffer. Feel free to clarify the documentation.

**Comment by edward-shen** [comment]
I was particularly confused because I was writing an encryption wrapper around an underlying `AsyncWrite` whose bytes when encrypted were larger than the bytes when left in plain text. I mistakenly returned the number of encrypted bytes written, which is how I ran into this issue.

I'll create a PR for this shortly.
