### ISSUE TITLE
Better error from tokio::spawn() if no `Runtime` is running

### ISSUE THREAD

**Issue by djc** [tokio-rs/tokio#382]
Currently if you run a `current_thread::Executor`, running `spawn()` from the futures run by that executor will fail with `SpawnError { is_shutdown: true }`. It would be nice if the error was clearer here about what's going wrong. (For more context see #377.)

**Comment by maufl** [comment]
Do I understand correctly that this means I can't call `tokio::spawn` before calling `tokio::run`?

**Comment by carllerche** [comment]
This is correct. If you need to call `tokio::spawn`, you should wrap the init code w/ `lazy` and pass that to `tokio::run`. Something like:

```rust
tokio::run(future::lazy(|| {
   tokio::spawn(my_task());
   Ok(())
}))
```

I want to make this nicer in 0.2

**Comment by maufl** [comment]
Cool, that solved my problem for now.

**Comment by carllerche** [comment]
The message is now: "must be called from the context of Tokio runtime"
