### ISSUE TITLE
`tokio::select` not compatible with `clippy::default_numeric_fallback`

### ISSUE THREAD

**Issue by kamulos** [tokio-rs/tokio#3830]
**Version**
1.6.1

**Platform**
Linux xyz 5.12.7-arch1-1 #1 SMP PREEMPT Wed, 26 May 2021 22:03:57 +0000 x86_64 GNU/Linux

**Description**
There might be good reasons for this, but the `tokio::select` macro is preventing me from activating `clippy::default_numeric_fallback` in my code.

``` rust
pub async fn myfunc() {
    tokio::select! {
        _ = empty() => (),
        else => (),
    }
}

async fn empty() {}
```

Run with:

```
cargo clippy -- -W clippy::default_numeric_fallback
```

**Comment by taiki-e** [comment]
This is a bug of clippy that warns code generated by macros.

**Comment by taiki-e** [comment]
Filed https://github.com/rust-lang/rust-clippy/issues/7304 to report this bug, and filed #3831 to avoid this bug.

**Comment by kamulos** [comment]
thanks for the quick reaction :blush:
