### ISSUE TITLE
current_thread::Runtime doesn't work on tokio-fs

### ISSUE THREAD

**Issue by uccidibuti** [tokio-rs/tokio#386]
When i try to open a file on a current_thread runtime the open /create function always fail, this is my code:
``
...
use tokio::io;
use tokio::runtime::current_thread::Runtime;
...
let mut rt = Runtime::new().unwrap();
rt.spawn({
  tokio::fs::File::open(file_path).and_then(|file| { io::read_to_end(file, vec![]) }).then(move |res| {
    println!("{:?}", res); Ok(()) 
  })
});
rt.run();
``
My output:
Err(Custom { kind: Other, error: StringError("tokio-fs::File::open must be called from the context of the Tokio runtime.") })

**Comment by kpp** [comment]
right.

`rt.spawn({ tokio::fs::File::open(file_path).and_then(|file| { io::read_to_end(file, vec![]) }).then(move |res| { println!("{:?}", res); Ok(()) }) });` looks for compiler like this:

```
let temp1 = tokio::fs::File::open(file_path);
let temp2 = temp1.and_then(|file| { io::read_to_end(file, vec![]);
let temp3 = temp..then(move |res| { println!("{:?}", res); Ok(()) });
rt.spawn(temp3);
```
So `File::open` is called not in the context of tokio runtime but in "main" (I believe it was main) thread even before you called `rt.spawn`.

What you want is smth like this:

```
rt.spawn(lazy(move || {
    tokio::fs::File::open(file_path).and_then(|file| { io::read_to_end(file, vec![]) }).then(move |res| { println!("{:?}", res); Ok(()) })
}))
```

**Comment by uccidibuti** [comment]
Now i have changed my code but it is still doesn't work, this is my main.rs, is it correct?
``... 
use tokio::runtime::current_thread::Runtime;
fn main() {
        let mut rt = Runtime::new().unwrap();
        let file_path = "foo.txt";
        rt.spawn(
                future::lazy(move || {
                        tokio::fs::File::open(file_path)
                        .and_then(|file| {
                                io::read_to_end(file, vec![])
                        })
                        .then(move |res| {
                                println!("{:?}", res);
                                Ok(())
                         })		
                })
        );
        rt.run();
//rt.shutdown_on_idle();
} ``
Output: 
Err(Custom { kind: Other, error: StringError("tokio-fs::File::open must be called from the context of the Tokio runtime.") })

Note: if i replace `` use tokio::runtime::current_thread::Runtime `` with ``use tokio::runtime::Runtime ``
and then ``rt.run()`` with ``rt.shutdown_on_idle()`` my code works correctly..
Output:
Ok((File { std: Some(File { fd: 6, path: "/home/lorenzo/develop/tokio_example/foo.txt", read: true, write: false }) }, [97, 115, 100, 97, 115, 100, 97, 115, 100]))

**Comment by uccidibuti** [comment]
Now i change my code code but it is still doesn't works, this is my main.rs, is it correct?
``
use tokio::runtime::current_thread::Runtime;
//use tokio::runtime::Runtime;
fn main() {
	let mut rt = Runtime::new().unwrap();
	let file_path = "foo.txt";
	rt.spawn(
		future::lazy(move || {
			tokio::fs::File::open(file_path)
			.and_then(|file| {
				io::read_to_end(file, vec![])
			})
			.then(move |res| {
				println!("{:?}", res);
				Ok(())
			})		
		})
	);
	rt.run();
	//rt.shutdown_on_idle();
}
``
Output:
Err(Custom { kind: Other, error: StringError("tokio-fs::File::open must be called from the context of the Tokio runtime.") })
 Note if i replace ``use tokio::runtime::current_thread::Runtime;`` with ``use tokio::runtime::Runtime`` and then ``rt.run();`` with ``rt.shutdown_on_idle();`` my code works correctly.
Output:
Ok((File { std: Some(File { fd: 6, path: "/home/lorenzo/develop/tokio_example/foo.txt", read: true, write: false }) }, [97, 115, 100, 97, 115, 100, 97, 115, 100]))

**Comment by kpp** [comment]
You found a bug.

```
fn blocking_io<F, T>(f: F) -> Poll<T, io::Error>
where F: FnOnce() -> io::Result<T>,
{
    match tokio_threadpool::blocking(f) {
        Ok(Ready(Ok(v))) => Ok(v.into()),
        Ok(Ready(Err(err))) => Err(err),
        Ok(NotReady) => Ok(NotReady),
        Err(_) => Err(blocking_err()),
    }
}
fn blocking_err() -> io::Error {
    io::Error::new(Other, "tokio-fs::File::open must be called \
                   from the context of the Tokio runtime.")
}
pub fn blocking<F, T>(f: F) -> Poll<T, BlockingError>
where F: FnOnce() -> T,
{
    let res = Worker::with_current(|worker| {
        let worker = match worker {
            Some(worker) => worker,
            None => {
                return Err(BlockingError { _p: () });  //  <========= We are here
            }
        };

        // Transition the worker state to blocking. This will exit the fn early
        // with `NotReady` if the pool does not have enough capacity to enter
        // blocking mode.
        worker.transition_to_blocking()
    });

    // If the transition cannot happen, exit early
    try_ready!(res);

    // Currently in blocking mode, so call the inner closure
    let ret = f();

    // Try to transition out of blocking mode. This is a fast path that takes
    // back ownership of the worker if the worker handoff didn't complete yet.
    Worker::with_current(|worker| {
        // Worker must be set since it was above.
        worker.unwrap()
            .transition_from_blocking();
    });

    // Return the result
    Ok(ret.into())
}
```

`Worker::with_current` gives us `None`.

**Comment by cynecx** [comment]
I think the problem here is that `Runtime::spawn` doesn't set a default executor, that's why `Worker::with_current` returns `None`. I guess the proper way is to use `Runtime::spawn` within a current executor context by using `Runtime::block_on` or `run` instead (which will call the internal `Runtime::enter` methods which actually set-ups all context stuff, such as the default timer/executor).

**Comment by kpp** [comment]
No. `block_on` does not work either.

```
$ cat tokio-fs/tests/current_thread.rs
extern crate tokio;
extern crate tokio_fs;
extern crate tempdir;

use tokio::runtime::current_thread::Runtime;
use tokio::prelude::*;

use tempdir::TempDir;

#[test]
fn current_thread() {
    let dir = TempDir::new("tokio-fs-tests").unwrap();
    let file_path = dir.path().join("non_existant.txt");

    let mut rt = Runtime::new().unwrap();
    rt.block_on(
        future::lazy(move || {
            tokio::fs::File::open(file_path)
            .and_then(|file| {
                tokio::io::read_to_end(file, vec![])
            })
            .and_then(move |(file, bytes)| {
                Ok(())
            })
        })
    ).unwrap();
}
```

```
running 1 test
test current_thread ... FAILED

failures:

---- current_thread stdout ----
None
thread 'current_thread' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("tokio-fs::File::open must be called from the context of the Tokio runtime.") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    current_thread
```

**Comment by bluetech** [comment]
`tokio-fs` requires the tokio multi-threaded runtime, see #364.

**Comment by carllerche** [comment]
The documentation for the current_thread runtime should call this out better.

**Comment by kpp** [comment]
@carllerche do you claim that there is no solution for this issue?

**Comment by carllerche** [comment]
A bit more context in #344, specifically here: https://github.com/tokio-rs/tokio/issues/344#issuecomment-391171627

`tokio-fs` relies on the `blocking` annotation, which requires that all futures spawned on the executor are `Send`. This goes against the point of `current_thread`. `tokio-fs` could potentially have a fallback strategy... but I am not 100% sure. It is also low priority for me, so unless somebody else does the investigation, I don't see a fix.

**Comment by carllerche** [comment]
I will try to write up steps to implement a backup strategy.

**Comment by carllerche** [comment]
This is now tracked in #1178.
