### ISSUE TITLE
rt: deadlock when shutting down the runtime

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#3869]
Originally reported [here](https://github.com/hyperium/h2/issues/546). Tokio shouldn't be calling shutdown [here](https://github.com/tokio-rs/tokio/blob/d1aa2df80ecc19d014c909813700e39c2197c96e/tokio/src/runtime/queue.rs#L521) for tasks that are already on the runtime.

**Comment by Darksonn** [comment]
Fixed by #3870.
