### ISSUE TITLE
clearing TcpStream's writable event

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/tokio#3873]
**Is your feature request related to a problem? Please describe.**

I am trying to make `TcpStream` to support TCP Fast Open. On Linux and FreeBSD, TFO is enabled with:

1. Enable `TCP_FASTOPEN` sockopt on the socket
2. Call `sendto` with the first packet
3. Call `send` as the normal TCP sockets

Since `TcpStream::poll_write` actually calls `send`, so I have to manually do:

1. `poll_write_ready`
2. `sendto`, and check `EAGAIN` or `EINPROGRESS`
3. If `errno == EINPROGRESS`, I have to **clear the write ready state and call `poll_write_ready` again**

**Describe the solution you'd like**

1. Provide a method `clear_write_ready` to clear the writable state of the internal `io`
2. `poll_write_ready` returns a `WriteReadyGuard` just like `AsyncFd`

**Describe alternatives you've considered**

There shouldn't be an alternative way to make it possible.

**Additional context**

```
[pid  9423] sendto(15, "POST /api HTTP/1.1\r\nHost: 149.15"..., 266, MSG_FASTOPEN, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("...")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

ref https://github.com/shadowsocks/shadowsocks-rust/issues/555

**Comment by zonyitoo** [comment]
Which solution you prefer? @Darksonn I could make a PR.

**Comment by zonyitoo** [comment]
Or maybe, add `poll_try_write_io` and `poll_try_read_io` methods.

**Comment by carllerche** [comment]
Adding a method to clear readiness is tricky as it opens up the API to potential races. An event may be received after the last time readiness is observed and the call to clear readiness, resulting in a lost event. This is why AsyncFd returns a readiness guard and that is used to clear readiness (the guard prevents the race).

For this case, I am wondering if exposing `try_io` on `TcpStream` is the best option. It would most likely not need the `cx` as you can call `writable().await` before calling `try_io`.

Thoughts @Darksonn ?

**Comment by Darksonn** [comment]
A `try_io` like API seems reasonable.

**Comment by zonyitoo** [comment]
With `try_io`, I can convert `EINPROGRESS` to an `io::Error` with `ErrorKind::WouldBlock`, which should work as expected.
