### ISSUE TITLE
copy_bidirectional hangs when one side of the stream shuts down

### ISSUE THREAD

**Issue by cfal** [tokio-rs/tokio#3876]
**Version**
tokio v1.7.1
tokio-macros 1.2.0

**Platform**
Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description**

When the `b` end of copy_bidirectional closes, the Future can get to a state where it is never polled again. I've been using copy_bidirectional with 2 tokio::net::TcpStream's and noticed that sockets kept getting stuck. So I added logging before and after each `ready!(poll_copy)` and `ready!(poll_shutdown)` call in `transfer_one_direction` and saw the following:

```
127.0.0.1:52113 to 127.0.0.1:60000 a->b poll_copy before
127.0.0.1:52113 to 127.0.0.1:60000 b->a poll_copy before
127.0.0.1:52113 to 127.0.0.1:60000 b->a poll_copy after
127.0.0.1:52113 to 127.0.0.1:60000 b->a poll_shutdown before
127.0.0.1:52113 to 127.0.0.1:60000 b->a poll_shutdown after
```

..after which the task did not wake again. `ss` shows the socket in `CLOSE-WAIT` state and does not close until the program is terminated.

Initially, I tried to call `transfer_one_direction` in the a->b direction again when the TransferState changed after the b->a invocation. However, I still saw `CLOSE-WAIT` sockets after a while, as well as the same issue in the opposite direction.

I ended up with [this](https://github.com/cfal/tobaru/commit/4343df39ac372581a9d68463fd43cf622cda9083) which returns whenever either direction is ready, but perhaps that doesn't work well for more generic cases. For my case, I haven't seen missing data at either end of the socket with this change.

I don't have any snippet to readily reproduce this but it's used in [this project](https://github.com/cfal/tobaru) if that helps.

cc @conblem

**Comment by Darksonn** [comment]
Are you sure that the other end is reading the data you are sending? I took a look at your code and at the implementation of `copy_bidirectional` in Tokio, but I didn't spot anything that could cause this.

**Comment by cfal** [comment]
Thanks for looking. One cause seems to be when the `b` end of the pipe closes before `copy_bidirectional` begins, which causes it to hang. See [this gist](https://gist.github.com/cfal/66024781f81d4fd2e7fb675b16752833). If you uncomment the `sleep` line after `accept`, `copy_bidirectional` finishes successfully.

**Comment by Darksonn** [comment]
You typically only shut down communication in your own write direction. When you drop a socket or call `shutdown(Both)`, that is an _abnormal_ tcp shutdown. The normal way to shut down a tcp socket is to have each end call `shutdown(Write)`. 

It is not possible for Tokio to detect the abnormal shutdown until it tries to write to the broken connection, which it doesn't until the other end writes something to forward.

**Comment by cfal** [comment]
I probably shouldn't have added a `shutdown(Both)` statement there :)

I think for my usecase, it's unfortunately very possible for one end to call `close(2)` early. So I guess I'll have to stick to a customized version that closes on a failing read without waiting for a failing write.

Thanks for the feedback!

**Comment by Darksonn** [comment]
If you want it to exit once the communication in one direction exits, then yes that's what you should do.

**Comment by Darksonn** [comment]
Closing as this doesn't appear to be a bug in Tokio. The IO traits do not really support a stream shutting down its close direction.

If you have an idea that better handles this case, feel free to reopen this issue, open a new issue, or open a PR.
