### ISSUE TITLE
Expose max permits of a semaphore through an associated constant

### ISSUE THREAD

**Issue by EFanZh** [tokio-rs/tokio#3878]
**Is your feature request related to a problem? Please describe.**

I want to implement an event notification object that notifies waiters on drop. Like so:

```rust
pub struct OneshotEvent {
    inner: Arc<Semaphore>,
}

impl OneshotEvent {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(Semaphore::new(0)),
        }
    }

    pub fn wait(&self) -> impl Future<Output = ()> {
        Arc::clone(&self.inner)
            .acquire_owned()
            .map(|r| drop(r.unwrap()))
            .boxed()
    }
}

impl Drop for OneshotEvent {
    fn drop(&mut self) {
        self.inner.add_permits(usize::MAX >> 3);
    }
}
```

The thing is that I hard coded `usize::MAX >> 3` according to the document. The underlying implementation could change at any time which may lead to broken code.

**Describe the solution you'd like**

Define `Semaphore::MAX_PERMITS` to indicate the max permits value so I can use the value reliably.

**Comment by sb64** [comment]
The documentation in [tokio/src/sync/batch_semaphore.rs](https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/batch_semaphore.rs#L108-L115) considers it a breaking change to change the max number of permits:

https://github.com/tokio-rs/tokio/blob/3207479fa7cce61ba568c0e352f498c4b7f3fd3c/tokio/src/sync/batch_semaphore.rs#L108-L115

However, in my opinion, it makes sense to add that constant for easier access anyways. I'm not a maintainer, though, but I would be happy to open a PR implementing this if a maintainer agrees that this should be added.

**Comment by Darksonn** [comment]
Please note that adding that many permits would fail if the semaphore already has permits. For your use-case, calling [`close`](https://docs.rs/tokio/1/tokio/sync/struct.Semaphore.html#method.close) on the semaphore seems like a better fit.

**Comment by Darksonn** [comment]
Closing this issue because there is a better solution to the problem.
