### ISSUE TITLE
Using stream::iter_ok on a Receiver deadlocks

### ISSUE THREAD

**Issue by sashaweiss** [tokio-rs/tokio#388]
Hi,

The docs for [stream::iter_ok](1) say that it produces a `Stream` that simply wraps an iterator over `Result`s, and that it can never block since Rust iterators don't express the ability to block. However, I seem to have run into a case where that's not strictly true, and it's producing behavior I didn't expect.

Specifically, in a project I'm working on I have a loop over values coming from an [mpsc::Receiver](2), which implements `IntoIterator`. I want to create a Stream of those values, and `for_each` over it - similarly to a stream over `incoming` connections on a `TcpListener`. However, if I call `stream::iter_ok` on a receiver, it seems to deadlock the entire program, rather than just blocking that future until values become available.

(I looked for a future-y version of a receiver, but the corresponding methods in Tokio appear to be deprecated and recommend using the stdlib one instead.)

I wrote a small example [here](https://github.com/sashaweiss/tokio_iterok_example). In it, I create two Streams - one over immediately available values, and one over a receiver. The stream over immediate values sends those values to the receiver. Finally, the two Streams are `join`ed, and the joint future is run.

My expectation was that the sending future would produce values for the receiving future to consume, and that once there was a value available the receiving future would unblock and run, until the receiving channel closed (when there were no more values to send, and the sender was dropped). However, this seems to be deadlocked, and I'm having trouble understanding why.

I understand that receivers violate the idea that Iterators never block, and that consequently this may be an invalid thing to do. However, I'm struggling to understand why the blocking nature of the channel is causing the sending stream to be deadlocked as well.

Thanks in advance for your advice!

Best,
Sasha

[1]: https://docs.rs/tokio/0.1.6/tokio/prelude/stream/fn.iter_ok.html
[2]: https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html

**Comment by tobz** [comment]
The links in your comment are pointing to entirely-unrelated Tokio issues, and not documentation, so it's a little hard to understand the context here, but..

Looking at the `join` combinator, I would also expect that the sending future could be allowed to make progress towards sending into the receiver.  Both futures in a `join` should be polled, and so as long as you were on a computer with multiple cores, such that Tokio was spawning multiple executor threads... it seems like it should be able to schedule both to separate threads, thus allowing progress?

Regardless, futures _has_ an [mpsc implementation](https://docs.rs/futures/0.1.21/futures/sync/mpsc/index.html) precisely for this reason, which already implements the stream/sink API.  You can and should use that.  As you might expect, using blocking operations, locks, etc, in Tokio comes with a "here be dragons" warning.

**Comment by tobz** [comment]
So, I conferred with some people on the Tokio gitter, and I can't believe I missed this, but: the futures are part of the _same_ task.

Simply put, the two futures -- the sender and the receiver -- get joined together (receiver first) and _that_ single future is the task that runs.  It goes to poll the receiver first, and blocks fully.  Thus, your deadlock.

I'd say this is safe to close at that point.

**Comment by sashaweiss** [comment]
Yep - that makes a lot of sense. Thanks for the explanation! I appreciate it.
