### ISSUE TITLE
`cargo +nightly doc` compilation broken

### ISSUE THREAD

**Issue by thanethomson** [tokio-rs/tokio#3880]
**Version**
1.7.1

**Platform**

* GitHub Actions running Ubuntu latest
* Ubuntu 20.04.2 LTS

**Description**
We're currently running into an issue trying to test our documentation build: https://github.com/informalsystems/tendermint-rs/pull/910/checks?check_run_id=2878946357

It appears as though it's due to the new named pipe code introduced in #3760, specifically the code in `tokio/src/net/windows/named_pipe.rs`

The command to run to reproduce this problem locally on our side (from Ubuntu) is:

```bash
RUSTFLAGS="--cfg docsrs" cargo +nightly doc --all-features
```

**Comment by Darksonn** [comment]
The correct command is:
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
```

**Comment by thanethomson** [comment]
Excellent, thanks @Darksonn! That fixed it.
