### ISSUE TITLE
Advance paused time to next time point

### ISSUE THREAD

**Issue by bruceg** [tokio-rs/tokio#3883]
**Is your feature request related to a problem? Please describe.**
I have set up a test harness for some timing sensitive code that pauses the clock, sets up some intervals and timeouts (in the code under test), and the repeatedly issues small sleeps to step the clock near the next interval time. This effectively amounts to polling the clock at an interval for something to have happened in the test code, and is a rather inefficient way to accomplish the goal.

**Describe the solution you'd like**
The above process would be much more efficient if there were an async interface that could step the paused clock *directly* to the next time point. This would likely need to either resolve to an `Option` or panic if there are no time points left.

**Describe alternatives you've considered**
We had been using `time::advance` with a small duration for this task, but its behavior changed as of version 1.6.2 to better match the documentation when the clock is paused. We have switched to `time::sleep(Duration::from_millis(0)).await` which *works* for us but may conceivably change if the internals of the paused time system are reworked. As such, interface stability is also a concern.

**Comment by danburkert** [comment]
This is the implementation I've used, but I agree it'd be better to have something more principled:

**Comment by Darksonn** [comment]
When the time is paused, the clock will auto-advance once there are no futures with work to do.

**Comment by Darksonn** [comment]
Can you elaborate on what you need here, and why the auto-advance is not enough for your use-case?

**Comment by Darksonn** [comment]
Closing due to lack of response.
