### ISSUE TITLE
Consider adding spawn_cancelable to tokio-executor

### ISSUE THREAD

**Issue by whitfin** [tokio-rs/tokio#389]
Currently (as far as I know) the only way to "cancel" a future spawned onto a Tokio `Runtime` is to spawn via the following (please excuse any mistakes, typing in the GitHub UI):

```rust
use futures::sync::oneshot;
use futures::*;
use tokio;

let (p, c) = oneshot::channel::<()>();

let select = select_all(vec![
  future::Either::A(c),
  future::Either::B(whatever_my_task_is)
]);

tokio::spawn(select);
```

And then the following to cancel:

```rust
p.send(()).unwrap();
```

Is there potential for adding a `spawn_cancelable` to the executor trait (and thus `tokio::spawn_cancelable`), to return what is effectively `p` from the block above? That then becomes this:

```rust
let p = tokio::spawn_cancelable(whatever_my_task_is);
```

Which is much easier to read, and little overhead on the Tokio side - it also becomes much more obvious on how you can create tasks which can be easily canceled.

This is referenced as a documentation issue in #165, but I wanted to raise this as a potential addition as I've found myself in need of this pattern in at least 2 projects recently. If we don't want to include it, no bother, just wanted to make sure it was brought up! FWIW, the name is a placeholder - if someone has a better name for it, feel free to suggest!

Thanks for reading!

**Comment by whitfin** [comment]
Happy to PR this if it's accepted, just wanted to discuss first :)

**Comment by Keruspe** [comment]
Not sure if it would better fit in tokio or directly in futures, but I'd definitely like something like this too

**Comment by carllerche** [comment]
Futures already has something similar w/ `oneshot::spawn`: https://docs.rs/futures/0.1.18/futures/sync/oneshot/fn.spawn.html.

Does this work?

**Comment by whitfin** [comment]
@carllerche for Futures, yes. Does it make sense to have something synonymous for Tokio?

**Comment by carllerche** [comment]
It probably does make sense to include something like this in a `tokio-util` crate... I haven't thought through exactly what this crate would contain and how it would be structured yet though.

**Comment by carllerche** [comment]
Tracked here: #1180
