### ISSUE TITLE
Make TcpStream poll_*_priv methods public but unsafe

### ISSUE THREAD

**Issue by eloff** [tokio-rs/tokio#3894]
The AsyncRead and AsyncWrite poll methods take &mut self, and then delegate to a method of the same name with _priv suffix that take a shared &self. I would like these methods to be public somehow, because not having access to them imposes an unreasonable burden.

At it's root, a socket is full duplex and can read and write concurrently in different threads. The shared _priv methods allow this behavior. But they also allow things that could cause trouble, such as trying to read and write with non-blocking calls in multiple threads. This is safe, but will cause the IO to overlap, which is not what the user intended. My guess is &mut was used in the poll methods to prevent this mistake at the language level.

But sometimes you want that full duplex behavior, so TcpStream has a split_into() method that creates a read and write end of the connection shared through an internal Arc<TcpStream>, this costs a heap allocation for the stream, but it's a fair tradeoff. The read and write ends of the stream use the internal _priv methods through the Arc, so it works just fine while still blocking potential overlapping reads and writes at the language level.

However, enter TlsStream over a TcpStream. A TlsStream cannot be split like this, except through a wrapper in tokio-io, which works with a Mutex (actually a shitty spinlock that yields the OS thread - but I digress). The Mutex acquisition is just around calls to poll, so you can interleave reads with other reads or writes with other writes. It serves to enforce rust aliasing rules by preventing there from ever being two &mut references to the underlying stream as well as protect the Tls internal state machine.

So basically we have no additional safety compared to using the _priv methods, but we do have a new external dependency with a questionable implementation and a lot of locking overhead.

It would be much better from my perspective to just expose those _priv methods, but mark them unsafe (they aren't) so that if people want to use them like adults, and take responsibility for preventing reads and writes from overlapping themselves, they can.

Alternately, one might argue that TLStream just needs a split method that doesn't have that silly mutex implementation. But TLS can write when you issue a read, and read when you issue a write - because it's a complex state machine. So any implementation really needs to be inside tokio where it can access those _priv methods - which is undesirable for lots of reasons. Again, we return to needing to have those methods public, and then the various TlsStream crates could conceivably implement split() in a sensible way.

My current workaround is to use unsafe and create an aliasing &mut reference, knowing it's a lie and gets used as a shared reference in _priv. And a mutex is still required to protect internal Tls state. So it's undefined behavior, but hopefully in a way that won't meltdown. It's so gross though - a lot more gross than having those _priv methods be exported and unsafe. Can't we just do that?

**Comment by Darksonn** [comment]
You can do this safely by combining `poll_read_ready` and `try_read`. When it comes to `TlsStream`, the situation is different because reading from it may result in writes being emitted due to how the tls protocol works, unless I misunderstood something.

**Comment by eloff** [comment]
> You can do this safely by combining `poll_read_ready` and `try_read`.

The poll_*_ready and try_* methods seem to be exactly what I need. Thanks!

> When it comes to `TlsStream`, the situation is different because reading from it may result in writes being emitted due to how the tls protocol works, unless I misunderstood something.

You're correct, I did call this out, but my post was very verbose so it's understandable if you missed it.

I think those methods work, I'm going to close this issue. Hopefully the word soup I posted gets indexed by Google and helps the next poor sap like me who spends hours trying to figure this out.
