### ISSUE TITLE
Consider removing `Core::id`.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#39]
I'm not sure exactly why it was added in the first place. Specifically, I know it was added to provide some token to use as a map key, but I don't recall the exact scenario that required this to be in the library.

The implementation also doesn't handle `usize` wrapping, which is a very edge case, but it seems like it should be handled.

Basically, enough has changed w/ the usage patterns of how the reactor should be used that I would like to remove `Core::id` from the initial release and re-evaluate if it is needed.

**Comment by aturon** [comment]
Fine by me.

**Comment by alexcrichton** [comment]
This was originally added in https://github.com/tokio-rs/tokio-core/pull/149 to solve https://github.com/tokio-rs/tokio-core/issues/147 which was in turn targeted at https://github.com/alexcrichton/tokio-signal/pull/6 which removed the need for keeping the original event loop alive once you're creating signal handlers.

With no ability to spawn this doesn't really make any more sense as the whole point was to "spawn a thing per event loop" or "spawn one thing globally and only one". That being said I have no idea how this will actually get implemented for signal handling...

**Comment by carllerche** [comment]
I'm not sure what exactly requires one task per executor in order to handle signals (which is what it seems like it is trying to do).

My initial thought would be that logic that pushes signals to the associated streams would be handled the same way as timers.

**Comment by aturon** [comment]
In any case it seems prudent to start without it at first, and then revisit tokio-signal; it's easy to add back if needed.

**Comment by carllerche** [comment]
Fixed by #41
