### ISSUE TITLE
Add a `TaskSet`

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#3903]
This issue contains a proposal for a new `TaskSet` type that is able to store a collection of `JoinHandle` values. A sketch of the API can be found below:

```Rust
struct TaskSet<T> {
    ...
}

impl<T> TaskSet<T> {
    pub fn new() -> Self {
        Self::new_with(Handle::current())
    }

    pub fn new_with(handle: Handle) -> Self;

    pub fn spawn<F>(&mut self, task: F)
    where
        F: Future<Output = T>,
        F: Send + 'static,
        T: Send + 'static;

    pub fn len(&self) -> usize;

    /// Wait until one of the tasks finish, then return its return value.
    /// Returns `None` if the `TaskSet` is empty.
    pub fn next_finished(&mut self) -> Option<T>;

    pub fn poll_next_finished(&mut self, cx: &mut Context<'_>) -> Poll<Option<T>>;
}
```

Related: #2478

**Comment by carllerche** [comment]
Additionally, when a `TaskSet` is dropped, it should cancel all remaining spawned tasks.

**Comment by hawkw** [comment]
Couple thoughts:
 - it would be nice for `tokio-util` to provide a stream adapter for this, which we could do easily with the `poll_next_finished` method :+1: 
 - I notice that `next_finished` and `poll_next_finished` return `Option<T>`s, presumably ignoring any `JoinError`s. Most of the time, this is _probably_ sufficient and is definitely a more ergonomic interface than having to deal with fallibility...but I can also imagine not wanting to have the `TaskSet` swallow panics. Maybe there should be a separate `try_next_finished` or something that returns an `Option<Result<T, JoinError>>`, so we can propagate task panics?

Overall this would definitely be nice to have!

**Comment by carllerche** [comment]
Right, we probably should include the join error. good call.

**Comment by Darksonn** [comment]
Right, I forgot about the `JoinError`. And `tokio-stream` will definitely provide a `Stream` adapter in [`tokio_stream::wrappers`][1].

Another thought is to include a `FromIterator` impl you so you can `collect` in to the `TaskSet` type.

[1]: https://docs.rs/tokio-stream/0.1/tokio_stream/wrappers/index.html

**Comment by Darksonn** [comment]
Regarding methods that don't return a `Result<T, JoinError>`, we could have it resume the panic. However, do we even want to have any methods that do this?

**Comment by hawkw** [comment]
Currently, we never resume panics...but I think it might be reasonable to at least have one version of the API that does that?

**Comment by Matthias247** [comment]
So is this a clone of `FuturesUnordered`, or explicitly for `JoinHandle`s?

It seemes like something in between, because `spawn` sounds it would spawn a real independent task. Then this seems like a version of #1897 without any of the guarantees that tasks actually stop if you stop interacting with the `TaskSet`.

If this is just a `FuturesUnordered` clone, then it has stronger guarantees. People can store `JoinHandle`s manually in it, and might have some idea that those tasks might continue to run in the background. But then again people can directly use `FuturesUnordered` - I have yet to see an application which imports tokio and not `futures`.

**Comment by Darksonn** [comment]
The `spawn` method spawns a real task, yes. It can be thought of as a `FuturesUnordered` for `JoinHandle`s.

**Comment by Noah-Kennedy** [comment]
I'm actually most interested in the cancellation capability here. It's not uncommon in certain types of code to need to mass cancel a set of tasks under some sort of "scope", and this seems like an excellent solution to that problem.

**Comment by Noah-Kennedy** [comment]
I might release a prototype in a separate crate.

**Comment by Noah-Kennedy** [comment]
Opened a PR: https://github.com/tokio-rs/tokio/pull/4238

This _should_ be pretty close to something we can all agree on.

**Comment by Noah-Kennedy** [comment]
So, an issue with my approach is that there isn't a good way from tokio-util to do something like FuturesUnordered without re-implementing the internal data structure that FuturesUnordered is built around, unless you want `poll_next_finished` to be O(n), as the naive approach of using a vec requires you to scan through your list of tasks, polling as you go.

**Comment by Skepfyr** [comment]
Is you use this like https://docs.rs/async-task-group/latest/async_task_group/ will it "leak" memory? I am considering using this for something a lot like the example in those docs:
```rust
#[async_std::main]
async fn main() -> io::Result<()> {
    let listener = TcpListener::bind("127.0.0.1:8080").await?;
    println!("Listening on {}", listener.local_addr()?);

    let handle = async_task_group::group(|group| async move {
        let mut incoming = listener.incoming();
        while let Some(stream) = incoming.next().await {
            let stream = stream?;
            group.spawn(async move { process(stream).await });
        }
        Ok(group)
    });
    handle.await?;
    Ok(())
}
```
But I have a suspicion that `JoinSet` will use an ever increasing amount of memory unless I have something else polling it to remove completed tasks.
