### ISSUE TITLE
Add tokio::io::Gateway

### ISSUE THREAD

**Issue by Morgan-iv** [tokio-rs/tokio#3905]
**Is your feature request related to a problem? Please describe.**
I worked with `teloxide` crate recently, and used method `Bot::download_file` from there. It accepts object that implements `AsyncWrite` and writes downloaded file content to it. I don't want to save file into fs, so the only available option is to use `DuplexStream`. But I don't know file size before downloading, so, I cant create buffer with knowingly sufficient size. And even if I knew file size, there will be extra data copy from `DuplexStream` buf to my own buf through `AsyncRead`

I think it's quite common situation when you need to asyncly download file and then work with this file syncly. And I think that situation where download-like process takes place via fn from external crate that takes `AsyncWrite` object is less common, but still deserves attention.

So, I want to create a gateway-like `AsyncWrite` and `AsyncRead` object: it will accept write ops, and respond with `Poll::Pending` on all read ops. And only after `AsyncWrite::poll_shutdown` it will become available for read ops. More than that, with these restrictions, this object can easy be `Vec` (so, we don't need to restrict capacity before writing), and after write shutdown we can safely give access to this inner Vec as &[u8] or even &mut [u8] to use it in other sync functions instantly, without additional data copies

**Describe the solution you'd like**
I've created a simple impl for this idea [there](https://github.com/Morgan-iv/tokio-gateway). So, if this impl is good enough, pls give me some help on how to turn my repo into PR (Where I need to place the code? What tests I need to create and how to test async ops? Docs?)

**Describe alternatives you've considered**
We always can discard this change and use `DuplexStream`, if restricted capacity and unnecessary data copy isn't a problem in specific case

**Additional context**
None

**Comment by Darksonn** [comment]
Instead of it implementing both `AsyncWrite` and `AsyncRead`, it sounds like what you really need is something that only implements `AsyncWrite`, stores the contents internally in a `Vec<u8>`, and when closed sends the vector on e.g. an oneshot channel.

**Comment by Morgan-iv** [comment]
Semantics of `AsyncWrite` doesn't allow sending inner `Vec<u8>` on shutdown, so I've removed `AsyncRead` and added conversion to `Vec<u8>` with `From`

**Comment by Morgan-iv** [comment]
Hmm, I think that we can wrap `data` with `Option` and `take` it in `poll_shutdown`, then it with oneshot channel. Which is better to choose?

**Comment by Darksonn** [comment]
If you are in a situation where you can access the IO object and take it out from the object directly, that's better, but it would not really be possible in many situations, in which case you would need the channel.

**Comment by Morgan-iv** [comment]
Ok, I changed impl to channel-based, what do you think about it?

**Comment by Darksonn** [comment]
I'm closing this as it seems like you went for a different solution.
