### ISSUE TITLE
[1.8] Device or resource busy

### ISSUE THREAD

**Issue by frederikbosch** [tokio-rs/tokio#3932]
**Version**
Tokio 1.8 (features: full)

```
│   │   │   ├── tokio v1.8.0
│   │   │   │   └── tokio-macros v1.2.0 (proc-macro)
│   │   │   └── tokio-rustls v0.22.0
│   │   │       ├── tokio v1.8.0 (*)
│   │   ├── tokio-stream v0.1.6
│   │   │   └── tokio v1.8.0 (*)
└── tokio v1.8.0 (*
```

**Platform**
Docker (buster and alpine)

**Description**
```rs
let connection = sqlx::MySqlPool::connect(mysql_dsn.as_str()).await?;
```

This fails for very specific addresses, e.g. `mysql://test:test@mariadb.service.consul/db` but not `mysql://test:test@test.com/db`, and only in a containerized environment with the following message: `Error: Io(Os { code: 16, kind: Other, message: "Device or resource busy" })`. 

It *only* fails on tokio 1.8, not on tokio 1.7. This is the reason I report the error here, and not with `sqlx`. On my Ubuntu OS with `cargo run` I was not able to reproduce it. Since the errors are influenced by the domain name, I guess it has something to do with resolving the host names in a Docker environment.

I also tried to compose a minimal case for you to reproduce, this failed. The minimal application did not render the error, but instead came with the expected error (`Error: Io(Custom { kind: Other, error: "failed to lookup address information: Name or service not known" })`). If there is anything I can do to help, I will gladly do so. And while I am here: thanks for the amazing work in the last years, working with Rust + Tokio has been absolutely incredible.

**Comment by Darksonn** [comment]
I don't really see anything on [the changelog][1] that could affect this. Perhaps those very specific addresses use a `UnixStream` and somehow running afoul with #3898? 

[1]: https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md

**Comment by frederikbosch** [comment]
@Darksonn Thanks for your reply. I solved it, no problems with Tokio. The error is confusing and I have no idea where it comes from, but it was a problem of my own.
