### ISSUE TITLE
Allow `LengthDelimitedCodec` to support signed integers.

### ISSUE THREAD

**Issue by 0x1991babe** [tokio-rs/tokio#3940]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a codec for the [Kafka wire protocol](https://kafka.apache.org/protocol.html#protocol_common), which represents frame sized in a signed integer, likely due to Java's lack of unsigned. Currently, `LengthDelimitedCodec` only supports unsigned integers.

**Describe the solution you'd like**
Allow a builder option that supports signed integers.

**Describe alternatives you've considered**
Realistically, sizes for messages fit within the intersection of `i32` and `u32`, however, this assumes a cooperating client. A malicious client sending negative length integers could cause unpredictable and potentially unsafe behavior in a codec that only reads unsigned ints. Additionally, there may be other protocols written in Java where the extra bit of information (i.e. `i8` vs `u8`) is much more significant.

**Comment by Darksonn** [comment]
You can accomplish the same functionality by setting `max_frame_len` to the largest value representable by a signed integer of the desired size.

**Comment by 0x1991babe** [comment]
Ooh, of course, that's a great workaround for the safety factor. Although still leaves an awkward API. For example, Kafka allows dynamically configuring a max message size, and it would be nice to use the codec's max size setting as additional validation separate from what kind of int it's trying to read.

**Comment by Darksonn** [comment]
I'm closing this because I don't think there's much reason to have this feature.
