### ISSUE TITLE
Blocking on Futures in testing

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/tokio#3949]
In the context of testing I want to drop a database I've used for testing. For simplicity and cleanup on errors I want to do this in the `Drop` impl of my connection pool (wrapper type). However running the drop query involves an async call, which I need to wait on in the sync `Drop::drop` call.

To achieve this I've tried two solutions:
* Spawning a `Future` that runs in the background. This doesn't work as the runtime (possibly due to Actix's use of it) doesn't wait for the spawned `Future` and it never completes (the test returns before the `Future` is complete).
* Tried to use [`tokio_test::block_on`](https://docs.rs/tokio-test/0.4.2/tokio_test/fn.block_on.html). This starts a new runtime which is rather unwanted overhead in the first place, but also seems to panic/abort.

For testing purposes only I would like to block on a `Future`/async function inside this `Drop` impl. Can `tokio_test::block_on` be modified such that is can hook into the current runtime and run it until the future is complete? Starting one if it's not in an async context already.

**Comment by Darksonn** [comment]
If you put the `block_on` inside an `tokio::task::block_in_place`, then it should work (provided the runtime is not a `current_thread` runtime).
```Rust
block_in_place(|| {
    Handle::current().block_on(...)
});
```

**Comment by Thomasdezeeuw** [comment]
> If you put the `block_on` inside an `tokio::task::block_in_place`, then it should work (provided the runtime is not a `current_thread` runtime).

I'm afraid [`actix_rt::test`](https://docs.rs/actix-rt/2.2.0/actix_rt/attr.test.html) uses a `current_thread` runtime: https://github.com/actix/actix-net/blob/a3c9ebc7fa4f05e855f47d183fa667db86d2c91e/actix-rt/src/runtime.rs#L15-L20.

**Comment by Darksonn** [comment]
Another thing that would "work" is to do this:
```Rust
let handle = Handle::current();
std::thread::spawn(move || {
    handle.block_on(...);
}).join().unwrap();
```
Of course, this would really terrible if done in a real application, but it would be ok if it's just the shutdown part of a test. A scoped crossbeam thread could be used for non-static stuff.

**Comment by Thomasdezeeuw** [comment]
@Darksonn I'm afraid that version never returns. Might be related to how Actix uses the runtime.

**Comment by Darksonn** [comment]
Ah, right, the IO driver is prevent from executing by the `join()` call. Even if you made a new runtime, it probably wouldn't work as exisiting IO resources use the driver they were created in, not the one they're currently in.

**Comment by Darksonn** [comment]
Closing this as it isn't really something we can fix.
