### ISSUE TITLE
Provide a backpressure mechanism, to tell applications how loaded this Runtime is

### ISSUE THREAD

**Issue by farnz** [tokio-rs/tokio#3975]
I'm integrating a Tokio application with a pre-existing C++ framework that uses load information to tell an upstream load balancer to not send further requests to this instance of the application - the idea is that if we have 10 instances behind the load balancer, it can take you out of rotation temporarily while you catch up.

In the C++ async executor from the Folly library (used by C++ applications in this framework), there is a "low priority" queue for new work items, and we can use the time an item spends in this queue as a proxy for async load. Workers in the Folly model only pull items from this queue when they would otherwise park the thread.

I could implement the Folly mechanism for Tokio - this would give us a `VecDeque` (acting as a FIFO) of spawned tasks that are waiting for a worker to run them. In both schedulers, we would take the first task from this FIFO and start running it *if* we would otherwise park the worker thread waiting for a notification. Naming TBD - something like `spawn_wait` to add a task to this queue, and `wait_queue_length`/`wait_queue_delay` to get its length.

That FIFO can then expose its length and the time the oldest task has been in the FIFO to the application, which can feed this information back in a useful form to allow the load balancer to stop sending work to the application instance that's most overloaded.

Any other mechanism that allows us to detect that the runtime has no free CPU cycles to work on a new work item would also resolve this issue - the FIFO is just the mechanism that I think I can implement easily.

**Comment by Darksonn** [comment]
One implementation that comes to mind is to give the builder an option to run a closure whenever a thread is about to park. Then that closure could call `tokio::spawn` to spawn a new task, preventing it from parking.

**Comment by farnz** [comment]
> One implementation that comes to mind is to give the builder an option to run a closure whenever a thread is about to park. Then that closure could call `tokio::spawn` to spawn a new task, preventing it from parking.

It would not be hard to add an `on_thread_park` to `runtime::Builder`, allowing a worker thread to run arbitrary code just before parking. I can do that if there's agreement it's an interesting thing to see.

**Comment by farnz** [comment]
And it occurs to me that a pairing with an `on_thread_unpark` that lets you know when a worker thread stops being idle would then have other uses in (e.g.) tracing.

**Comment by hawkw** [comment]
> One implementation that comes to mind is to give the builder an option to run a closure whenever a thread is about to park. Then that closure could call `tokio::spawn` to spawn a new task, preventing it from parking.

This is probably a good idea in general --- it could also be used for [QSBR](https://preshing.com/20160726/using-quiescent-states-to-reclaim-memory/) and similar techniques where performance is improved by only doing bookkeeping work when not busy doing more important things.

**Comment by glebpom** [comment]
This can also be useful to implement the cached version of SystemTime to reduce the number of syscalls when precise time is not required

**Comment by sfackler** [comment]
Time lookups go through the VDSO on linux and don't involve a system call.

**Comment by glebpom** [comment]
Hm, I see about 0.6% of time spent in `__clock_gettime` for hyper benchmarks in flamegraphs

**Comment by glebpom** [comment]
It seems like it's described here: https://berthub.eu/articles/posts/on-linux-vdso-and-clockgettime/
