### ISSUE TITLE
Implement Extend and FromIterator for StreamMap

### ISSUE THREAD

**Issue by allsey87** [tokio-rs/tokio#3982]
**Is your feature request related to a problem? Please describe.**
I would like to `collect` or `try_collect` into a `StreamMap`, however, these methods are only available if `StreamMap` implements `Extend`.

**Describe the solution you'd like**
Implement the `Extend` trait for `StreamMap`.

**Describe alternatives you've considered**
One could temporarily collect into a `Vec<(Key, Stream)>` and then loop over it calling insert on the `StreamMap`.

**Additional context**
None for the moment.

**Comment by Darksonn** [comment]
Collecting requires `FromIterator` rather than `Extend`.

**Comment by allsey87** [comment]
Indeed, `FromIterator` is required for `collect`. `Extend` is only necessary when working with `try_collect` from futures_util's `TryStreamExt`.

**Comment by bootrecords** [comment]
`Extend` usage with another instance of `StreamMap` (which is something I'd like to be able to do) would also require implementation of `IntoIterator`, if I see that correctly.
