### ISSUE TITLE
Add as_raw_handle for process::Child

### ISSUE THREAD

**Issue by passcod** [tokio-rs/tokio#3987]
**Is your feature request related to a problem? Please describe.**

Background: I'm trying to refactor watchexec (and thus `cargo watch`) as async.
On the way there, I need to get process groups working over Tokio's process::Command on both Unix (via `setsid`) and Windows (via `JobObject`). I've got the Unix part sorted, but on Windows I can't get access to the `RawHandle` via Tokio's implementation. I need that to create a JobObject and [assign the child process](https://docs.microsoft.com/en-us/windows/win32/api/jobapi2/nf-jobapi2-assignprocesstojobobject) to it.

**Describe the solution you'd like**
Implement `AsRawHandle` on `process::Child`.

**Describe alternatives you've considered**
Well, I could re-implement all of async process management for windows just for that, but I'd rather not.

**Comment by ipetkov** [comment]
We do export [Child::id](https://docs.rs/tokio/1.9.0/tokio/process/struct.Child.html#method.id) which is supposed to return the OS identifier back, but I can't tell at a glance whether that returns the actual process handle on Windows.

I'm not opposed to adding `AsRawHandle` on `process::Child`, but we may need to be careful with how we implement the API so that we cannot return a handle back if the process has been reaped...

**Comment by passcod** [comment]
It doesn't. On windows it returns the result of `GetProcessId(handle)`; there's no way to go the other way (pid to handle).

**Comment by passcod** [comment]
The Windows API is also a lot better than unix in this regard, as handles aren't recycled like PIDs are, so there's not the same risk as obtaining a different process after reaping:

> The handles are valid until closed, even after the process or thread they represent has been terminated.

([source](https://docs.microsoft.com/en-us/windows/win32/procthread/process-handles-and-identifiers))

---

However it occurs to me there *is* a way to get a handle from a pid, `OpenProcess`; I'll check if that provides the access I want.

**Comment by passcod** [comment]
> I'll check if that provides the access I want.

It doesn't: I can call it to get a handle, but the permission set I require isn't available, so I get denied. So the only way for me is to get the process handle from the creator/tokio.

**Comment by ipetkov** [comment]
Thanks for the context @passcod, makes sense to me.

Are you interested in opening a PR with the change? Feel free to tag/ping me for review if you do!
Otherwise I'll try to get to it this week
