### ISSUE TITLE
ThreadPool vs TokioPool

### ISSUE THREAD

**Issue by adam0z** [tokio-rs/tokio#399]
Hello,
Where could I find more info how the `tokio-threadpool` library works?
I would like to get to know the difference between a [Connicpu/tokio-pool](https://github.com/Connicpu/tokio-pool) library which runs multiple threads with a separate `Core` and provides `Remote`s to spawn as you can see in the simple code:
 https://github.com/Connicpu/tokio-pool/blob/master/src/lib.rs#L81

How could I set the number of threads in your library?

**Comment by carllerche** [comment]
Sorry, I don't know anything about the crate you are referencing.

The `tokio-threadpool` crate provides a way to set the number of threads.
