### ISSUE TITLE
More Example how to write concurrent code.

### ISSUE THREAD

**Issue by VJ-OK** [tokio-rs/tokio#4]
i am loving rust and tokio and futures and stuff.

i am just so much confused right now because code examples given are too intelligent for beginner to understand, can you guys please wrote some beginner level example how concurrency works with tokio and if possible step by step stuff. i know its lot to do but this is rust's turning point may be, and i think it should be better. thank you.

**Comment by alexcrichton** [comment]
Thanks for the report! This should be done now at https://tokio.rs

**Comment by brandonros** [comment]
It seems most (if not all) of the examples/documentation on the website are about the flow of incoming connections to a server. What about a client wanting to make 64 concurrent requests?

**Comment by kpp** [comment]
You should create a client with 1 connection, the result of processing should be a `Future`. Then you do other 63 connections with the same logic and you call `join`/`select`/`join_all` on them.

**Comment by kpp** [comment]
https://github.com/tokio-rs/tokio/blob/master/examples/connect.rs

**Comment by brandonros** [comment]
@kpp I was thinking more along the lines of using Tokio's executor to spawn tasks that return Futures. Like, using https://github.com/hyperium/hyper to concurrently and asynchronously do 64 requests at a time

**Comment by kpp** [comment]
Actually I am not familiar with `hyper`. But the logic is the same: you should create a client, which result of communication will be `Future`, then you call this `create_client` 64 times and `join_all` them together to get the result `Future` which you should run. Due to the properties of `Future` it will run `"concurrently"`

**Comment by brandonros** [comment]
@kpp 

```
fn main() {
  for i in 1..64 {
    let https = HttpsConnector::new(4).unwrap();

    let client = hyper::Client::builder()
    .keep_alive(true)
    .build::<_, hyper::Body>(https);

    let url = r#"http://127.0.0.1:10000/select"#.to_string();
    let request_body = r#"{"query":"SELECT ACCOUNT_ID FROM ACCOUNT"}"#.to_string();

    let fut = fetch_json(&client, url, request_body)
    .map(|response_body| {
      println!("body: {:#?}", response_body.as_array().unwrap().len());
    })
    .map_err(|e| {
      match e {
        FetchError::Http(e) => eprintln!("http error: {}", e),
        FetchError::Json(e) => eprintln!("json parsing error: {}", e)
      }
    });

    tokio::spawn(fut);
  }
}
```
Something like this? I am hazy on when to call tokio::run versus tokio::spawn... it seems that with the code sample pasted above, a runtime is never initialized?

**Comment by kpp** [comment]
> it seems that with the code sample pasted above, a runtime is never initialized?

It does not. You should put `tokio::run` right after the loop to start the `Future`s

**Comment by kpp** [comment]
and `for i in 1..64` will give you `[1, 64)` or `[1, 63]` values, 63 in total

**Comment by brandonros** [comment]
Does `tokio::run` block? What if I want to spawn more futures into the runtime later?

**Comment by kpp** [comment]
Yes it blocks. Yes you can spawn more futures while it is running. See https://docs.rs/tokio/0.1.7/tokio/runtime/fn.run.html

**Comment by brandonros** [comment]
I'm still confused. I understand spawning the futures into the runtime/executor. I just don't get what I am supposed to pass to `tokio::run()`? You said I'm supposed to pass a client, but I in theory should have 64 clients?

**Comment by kpp** [comment]
You may either create a big future with `join_all` or spawn 64 clients and call `tokio::run()` with a future (depends on).

**Comment by tobz** [comment]
`tokio::run` starts the (multi-threaded) runtime, spawns the future you give it, and waits until the runtime is idle.

You could do something along the lines of `tokio::run(futures::lazy(|| { ... }))` where the inside of the `lazy` future is the code you pasted above: creating each client, and calling `tokio::spawn` to spawn it into the runtime.

You can't call `tokio::spawn` unless the call is within an executing task in the runtime, so this `tokio::run(futures::lazy(|| { ... })` approach gives you a clean way to get into the runtime.

You _can_ spawn a runtime and avoid blocking the current thread waiting on it, but this is kind of depend on your design so I'm not going to post an example of it here.

It might be easier to join us over in the Gitter channel -- gitter.im/tokio-rs/tokio -- which is a little more collaborative!
