### ISSUE TITLE
[tokio-util] Build FramedRead and FramedWrite using buffers in FramedParts

### ISSUE THREAD

**Issue by chipsenkbeil** [tokio-rs/tokio#4000]
I've got an instance of `Framed<TcpStream, Codec>` that I want to split into `FramedRead<tcp::OwnedReadHalf, Codec>` and `FramedWrite<tcp::OwnedWriteHalf, Codec>`.

While I can get the codec and stream split into halves to feed into `FramedRead::new(...)` and `FramedWrite::new(...)`, I don't see any way to re-assign the existing read and write buffers that are exposed in `FramedParts<TcpStream, Codec>`, which means that I potentially drop partial frames for both reading and writing.

`Framed::into_parts()` provides me with the data I need to feed into the individual halves, but I can't figure out how to re-add the buffers.

Is there a practice for how to do this? Anything I missed?

**Comment by Darksonn** [comment]
After creating the `FramedRead` and `FramedWrite`, you can insert the buffers via `read_buffer_mut` and `write_buffer_mut`.

**Comment by chipsenkbeil** [comment]
Ah, I somehow missed the mut variants of those methods. Thanks!
