### ISSUE TITLE
Deadlock when dropping the runtime

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#401]
Reported by @jonhoo 

Trace: https://gist.github.com/jonhoo/d898ca9e93fe851271a5aeaa31d4a7d2

**Comment by jonhoo** [comment]
Can be reproduced by running `cargo test -- --test-threads=1` on https://github.com/mit-pdos/distributary/commit/2ed4b1c3cf629a7e74b80f6a977f2c8464965168. It's a pretty elaborate system though, so hard to minimize. Different tests hang each time, and usually not if run in isolation, which suggests this is a fairly rare occurrence.
