### ISSUE TITLE
`impl Iterator for tokio::sync::mpsc::Receiver`

### ISSUE THREAD

**Issue by ShadowJonathan** [tokio-rs/tokio#4014]
#### Is your feature request related to a problem? Please describe.
`Receiver` implements a blocking recv function, but it doesn't implement `Iterator`

To coerce `Receiver` into an `Iterator`, I have to do
```rs
std::iter::from_fn(move || r.blocking_recv())
```

...which is a bit boilerplate-y.

### Describe the solution you'd like
Implement `Iterator` for `Receiver`, and maybe `UnboundedReceiver` too.

#### Additional context
Due to circumstances, we must coerce the channel into an iterator to return, and above was the best solution, but what could be better is that we can just return `r` on the `impl Iterator` signature.

**Comment by Darksonn** [comment]
We are not going to implement `Iterator` for `Receiver` because it makes it too easy to accidentally perform a blocking operation in asynchronous code.

**Comment by ShadowJonathan** [comment]
Maybe implement IntoIter for it, then? Or have an explicit wrapper done with `into()` somewhere, which'd make this easier.

**Comment by Darksonn** [comment]
I do not want to implement `IntoIterator` either. This snippet should not compile:
```
use tokio::sync::mpsc;

async fn foo(recv: mpsc::Receiver<String>) {
    for msg in recv {
        println!("{}", msg);
    }
}
```
In principle something like `into_blocking_iter()` could be ok, but given how short `std::iter::from_fn(move || r.blocking_recv())` is, it's not clear that its worth it.

**Comment by davidpdrsn** [comment]
I agree with @Darksonn and implementing `IntoIterator` isn't better for the same reason.

Personally I don't think `std::iter::from_fn(move || r.blocking_recv())` so too bad. If nothing else its pretty explicit.

**Comment by ShadowJonathan** [comment]
I think it's a bit of an antipattern, and an explicit conversion from the type itself would be appreciated.

**Comment by Darksonn** [comment]
The ergonomics of the asynchronous channel are generally optimized for use in async code.

**Comment by ShadowJonathan** [comment]
Hmmm, understood. I'll close this issue then.
