### ISSUE TITLE
[tokio-stream] Implement From<Receiver> for ReceiverStream (and maybe others)

### ISSUE THREAD

**Issue by ShadowJonathan** [tokio-rs/tokio#4015]
Reading [this doc page](https://docs.rs/tokio-stream/0.1.7/tokio_stream/wrappers/struct.ReceiverStream.html), it occurred to me that this needs to be constructed explicitly, wouldn't it be possible to make easier by implementing a `From<Receiver>` trait?

This probably also counts for other `tokio_stream::wrappers::*` structs, if they haven't already gotten these impls.

**Comment by Darksonn** [comment]
I am fine with adding such `From` impls.
