### ISSUE TITLE
worker_threads doesn't seem appropriate.

### ISSUE THREAD

**Issue by silence-coding** [tokio-rs/tokio#4029]
I implemented a web with tokio and hyper.
tokio 1.9.0
hyper 0.14

I expected to use 4 CPUs to work, so I use`.worker_threads(4)`,  but only two CPUs were used, and the rest were low.
Is the thread specified by worker_threads assigned two to signal and time? I can't find the information right now.

```
let common = Builder::new_multi_thread()
        .thread_name("worker")
        .enable_all()
        .worker_threads(4)
        .build()?;
```

**Comment by Darksonn** [comment]
This should spawn four worker threads, however some of them would be idle if you don't spawn enough work on them.

Signal, time or IO do not take up any threads.

**Comment by silence-coding** [comment]
@Darksonn 
I tested the pressure using wrk, and the overall pressure was sufficient. In version 0.2 of Tokio, set core_threads to 4, which can reach 4 CPUs.
Keeping the wrk pressure the same, I found that when worker_threads is set to 6, I could run to 4 CPUs, and when worker_threads is set to 8, I could run to 6 CPUs, which gives me the impression that 2 threads are dedicated to other purposes.

**Comment by Darksonn** [comment]
Go ahead and post the program you used to test this.

**Comment by silence-coding** [comment]
I've just written a demo that contains only tokio and hyper for testing, and I haven't found the problem I mentioned above. The problem may be caused by  our project code. I will further check the problem. Thank you very much for your reply
@Darksonn

**Comment by silence-coding** [comment]
Our formal project code is similar to this architecture, where multiple runtimes are deployed for isolation. But this simplified version doesn't have the problem I said.


```
use std::time::Duration;
use tokio::time::sleep;

fn main() {
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .thread_name("worker")
        .enable_all()
        .worker_threads(2)
        .build()
        .unwrap();
    let http = tokio::runtime::Builder::new_multi_thread()
        .thread_name("http")
        .enable_all()
        .worker_threads(4)
        .build()
        .unwrap();
    runtime.spawn(async move {
        http.spawn(do_something_loop());
        http.spawn(do_something_loop());
        http.spawn(start());
        std::mem::forget(http);
    });
    runtime.block_on(async move {
        sleep(Duration::from_secs(100)).await;
    })
}

async fn do_something_loop() {
    loop {
        sleep(Duration::from_secs(1)).await;
    }
}

async fn start() {
    use hyper::service::{make_service_fn, service_fn};
    use hyper::{Body, Error, Response};
    let make_svc = make_service_fn(|_| async {
        Ok::<_, Error>(service_fn(|_req| async {
            // business code
            Ok::<_, Error>(Response::new(Body::from("Hello World")))
        }))
    });
    let addr = "127.0.0.1:8080".parse().unwrap();
    let _ = hyper::Server::bind(&addr).serve(make_svc).await;
}

```

**Comment by Darksonn** [comment]
One possible cause is if you are [blocking the thread](https://ryhl.io/blog/async-what-is-blocking/) in some of your tasks.

**Comment by silence-coding** [comment]
@Darksonn Thank you very much for your answer, and I'm skeptical about that, but there's no good way to identify what's blocking the thread. Do you have any good suggestions? Identifying blocking logic in asynchronous code is a painful point.

**Comment by Darksonn** [comment]
Such tasks should be listed if you use [tokio-console](https://github.com/tokio-rs/console).

**Comment by silence-coding** [comment]
@Darksonn Thank you
