### ISSUE TITLE
Add an Either type for Listeners

### ISSUE THREAD

**Issue by qrnch-jan** [tokio-rs/tokio#4048]
**Is your feature request related to a problem? Please describe.**
I want to be able to (easily) listen on either a UnixListener or TcpListener in the same function.  Or, more precisely, I would like the freedom to nest other types as well, just as can be done with `tokio-util`'s `Either`.

On the client side we have a function which parses the socket address string and detects if it's a local domain socket or not, and paired with a custom connection function we can easily allow the user to control whether to use local domain sockets or TCP simply by altering a configuration string.  We want to be provide the same simplicity on the server end for the binding/listening.

**Describe the solution you'd like**
It would be nice to have an `EitherListener` (or equivalent) which works exactly like `tokio-utik`'s `Either`, except that it works on the server end (i.e. `.bind()` and `.accept()`).

**Describe alternatives you've considered**
We have a hardwired solution, but the nice thing about Either is that it generic and supports nested types.

**Comment by Darksonn** [comment]
Adding this to `tokio-util` is fine with me.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
@Darksonn  When you have time, could you help describe what you think the right API looks like?

**Comment by Hodkinson** [comment]
Hi @hi-rustin how's it going with this one? I could have a look at it this week if you like.

**Comment by Darksonn** [comment]
Please note that this PR was recently posted: #4385

**Comment by Darksonn** [comment]
Fixed in #4385.
