### ISSUE TITLE
tokio::process::Command may not pass on stdin/out/err

### ISSUE THREAD

**Issue by mcr** [tokio-rs/tokio#4053]
**Version**
│   │   └── tokio v1.7.1
│   │       └── tokio-macros v1.2.0 (proc-macro)
│   ├── tokio v1.7.1 (*)
│   └── tokio-util v0.6.7
│       └── tokio v1.7.1 (*)
│   └── tokio v1.7.1 (*)
├── tokio v1.7.1 (*)
├── tokio-serde v0.8.0
└── tokio-util v0.6.7 (*)
└── tokio-test v0.4.2
    ├── tokio v1.7.1 (*)
    └── tokio-stream v0.1.6
        └── tokio v1.7.1 (*)

**Platform**
obiwan-[pandora/connect/connect](2.6.6) mcr 10106 %uname -a
Linux obiwan 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux

**Description**

I have redirected stdout and stderr to a file using Gag::Redirect, which calls FileDescriptor to do the work.
After some investigation, it was obvious that the new FD was marked CLOEXEC.   I dispute whether FileDescriptor should do that when redirecting stdin/out/err.

tokio::process::Command, even when explicitly told to .stderr(Stdio::inherit()) does not inherit because of CLOEXEC.

I expected to see this happen: [explanation]

I expected to see my subprocess' stderr in the file.

Instead, this happened: [explanation]

I see nothing output, and investigating my subprocess with lsof, reveals that fd 2 is not open.

I think that the principal of least surprise should be that subprocesses inherit stdio, and that CLOEXEC should be unset on fds 0/1/2 after the fork.    Perhaps only if  .stderr(Stdio::inherit())) is explicitely called, but I think that also violates surprise.

**Comment by mcr** [comment]
https://github.com/wez/wezterm/pull/1066

**Comment by Darksonn** [comment]
@ipetkov Thoughts?

**Comment by Darksonn** [comment]
Closing as this appears to be an issue in the standard library, or in an external crate.
