### ISSUE TITLE
Broadcast channel get nothing if send more messages than capacity.

### ISSUE THREAD

**Issue by BratSinot** [tokio-rs/tokio#4057]
**Version**
```
└── tokio v1.10.0
    └── tokio-macros v1.3.0 (proc-macro)
```

**Platform**
Fedora 34

**Description**
Broadcast channel get nothing if send more messages than capacity.
```rust
#[tokio::main]
async fn main() {
    let (tx, mut rx) = tokio::sync::broadcast::channel(4);

    tokio::task::spawn({
        let mut rx = tx.subscribe();
        async move {
            while let Ok(msg) = rx.recv().await {
                println!("0: {}", msg);
            }
        }
    });

    tokio::task::spawn(async move {
        while let Ok(msg) = rx.recv().await {
            println!("1: {}", msg);
        }
    });

    for i in 0..8 {
        tx.send(format!("QWE{}", i)).unwrap();
    }

    tokio::time::sleep(tokio::time::Duration::from_millis(3000)).await;
}
```

From docs, I expected that first message will lose or something, but output is just empty.

**Comment by Darksonn** [comment]
Don't use a `while let Ok` loop. You are ignoring the [`Lagged`][1] errors.

[1]: https://docs.rs/tokio/1/tokio/sync/broadcast/error/enum.RecvError.html#variant.Lagged

**Comment by BratSinot** [comment]
> Don't use a `while let Ok` loop. You are ignoring the [`Lagged`](https://docs.rs/tokio/1/tokio/sync/broadcast/error/enum.RecvError.html#variant.Lagged) errors.

Thanks for answer!
And no way to get such error at `send`?

**Comment by Darksonn** [comment]
If you want that, you probably shouldn't be using Tokio's broadcast channel.

**Comment by BratSinot** [comment]
> If you want that, you probably shouldn't be using Tokio's broadcast channel.

Yeah, probably. I just didn't figure out yet any good way to implement `single-producer multi-consumer`.

**Comment by Darksonn** [comment]
You could try the [`async-broadcast`][1] channel.

[1]: https://docs.rs/async-broadcast/

**Comment by BratSinot** [comment]
> You could try the [`async-broadcast`](https://docs.rs/async-broadcast/) channel.

I totally forgot about this lib! Thanks a lot!

**Comment by BratSinot** [comment]
> You could try the [`async-broadcast`](https://docs.rs/async-broadcast/) channel.

`async-broadcast` is using `std::sync::Mutex` and I get problem with global locks =(
