### ISSUE TITLE
Multithreaded runtime block_on executed on the main thread

### ISSUE THREAD

**Issue by glebpom** [tokio-rs/tokio#4064]
**Version**
1.10.0

**Platform**
Darwin MacBook-Pro-2.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Description**
executing `block_on` on the multithreaded Runtime leads to the execution of the code on the `main` thread, instead of the worker. If running another code through `tokio::spawn`, it gets to the right worker. At least, I would expect to utilize only the provided number of threads (defined through `worker_threads` builder method), but may get an additional one (main thread). 

I tried this code:

```
pub fn main() {
    let rt = Builder::new_multi_thread()
        .worker_threads(1)
        .enable_all()
        .build()
        .unwrap();
    rt.block_on(async move {
        println!("thread is {:?}", std::thread::current());
        tokio::spawn(async move {
            println!("spawn thread is {:?}", std::thread::current());
        });
    })
}
```

I expected to see that only one worker thread is used

Instead, I see that two threads are involved: tokio-runtime-worker and main.

**Comment by Darksonn** [comment]
This is the expected behavior.
