### ISSUE TITLE
tokio-util: Add compat with `AsyncSeek`

### ISSUE THREAD

**Issue by jorgecarleitao** [tokio-rs/tokio#4068]
**Is your feature request related to a problem? Please describe.**
Currently the compat module does not offer support for `AsyncSeek`.

**Describe the solution you'd like**

Something like this should compile:

```rust
use tokio_util::compat::*;

async fn read<R: futures::AsyncRead + futures::AsyncSeek + Send + std::marker::Unpin>(&mut R) {todo!()};

#[tokio::main]
fn main() {
    let mut reader = tokio::fs::File::open("some_path").await.unwrap().compat();
    read(&mut reader).await;
};
```

**Comment by Darksonn** [comment]
I would definitely accept a PR that implements this, and it should be rather easy to do.
