### ISSUE TITLE
Select macro incorrectly binds expression result as shared reference

### ISSUE THREAD

**Issue by tobz** [tokio-rs/tokio#4076]
**Version**
`tokio 1.10.1`

**Description**
When using `select!` and taking advantage of the built-in pattern matching i.e. `Some(foo) = fut_here()`, the macro incorrectly binds the result as a shared reference, which turns into confusing errors like this:

```|
192 | /         select! {
193 | |             // TODO: why the hell is this coming out as &S3Request?!?!
194 | |             Some(mut req) = rx.recv() => {
    | |                  -------
    | |                  |
    | |                  data moved here
    | |                  move occurs because `req` has type `S3Request`, which does not implement the `Copy` trait
195 | |                 let seqno = seq_head;
...   |
236 | |             else => break
237 | |         }
    | |_________^
```

The full code can be seen [here](https://gist.github.com/tobz/196c9b6cc3264f0b81a6d16319503121), but `rx` is `Receiver<S3Request>`, so clearly the returned value is/should be owned.  @Darksonn pointed out that the code in the macro responsible for this issue is [here](https://github.com/tokio-rs/tokio/blob/08ed41f339e345286f26bdbc6c67bf9f2975ed07/tokio/src/macros/select.rs#L518-L528).

Note to whoever is interested in fixing it: @Darksonn also pointed out that changing from `match &out {` to `match &mut out {` would likely be a suitable fix.

**Comment by blasrodri** [comment]
This update
```diff
diff --git a/tokio/src/macros/select.rs b/tokio/src/macros/select.rs
index a90ee9eb..88c26adb 100644
--- a/tokio/src/macros/select.rs
+++ b/tokio/src/macros/select.rs
@@ -502,7 +502,7 @@ macro_rules! select {
                                 let mut fut = unsafe { Pin::new_unchecked(fut) };
 
                                 // Try polling it
-                                let out = match fut.poll(cx) {
+                                let mut out = match fut.poll(cx) {
                                     Ready(out) => out,
                                     Pending => {
                                         // Track that at least one future is
@@ -519,8 +519,8 @@ macro_rules! select {
                                 // the specified pattern.
                                 #[allow(unused_variables)]
                                 #[allow(unused_mut)]
-                                match &out {
-                                    $bind => {}
+                                match &mut out {
+                                    $bind => {},
                                     _ => continue,
                                 }
 
```
allows me to do the following:

```rust
    Some(ref mut req) = rx.recv() => {...}
```

However, I still cannot get the following pattern:

```rust
    Some(mut req) = rx.recv() => {...}
```

**Comment by Darksonn** [comment]
Try using the `matches!` macro instead.

**Comment by blasrodri** [comment]
> Try using the `matches!` macro instead.

Do you mean
```rust
if !matches!(&mut out, $bind) {continue}
```
same result

**Comment by Darksonn** [comment]
Hmm, yeah I tried a few things. It doesn't seem like we can get it to work. We probably have to change the macro to not require this check in the first place.

**Comment by blasrodri** [comment]
> Hmm, yeah I tried a few things. It doesn't seem like we can get it to work. We probably have to change the macro to not require this check in the first place.

Any suggestions? I tried playing around and couldn't find an easy way.

**Comment by Darksonn** [comment]
I don't think there's an easy way.
