### ISSUE TITLE
watch::error::SendError<T> has no way of obtaining contained data

### ISSUE THREAD

**Issue by surban** [tokio-rs/tokio#4096]
**Is your feature request related to a problem? Please describe.**
` tokio::sync::mpsc::error::SendError<T> ` allows obtaining the contained value because the inner field is marked public. However `tokio::sync::watch::error::SendError<T>` has its inner field marked private for no apparent reason.

**Describe the solution you'd like**
Mark inner field public.

**Comment by Darksonn** [comment]
Ah yeah, that appears to be an oversight.

**Comment by surban** [comment]
Thanks!
