### ISSUE TITLE
Add readable/writeable/ready methods to read/write half

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#4098]
It would make sense for the various socket type read/write halves have the readable/writeable/ready methods, as well as the `try_*` methods.

**Comment by Noah-Kennedy** [comment]
I think I'll give this one a go.

**Comment by Noah-Kennedy** [comment]
On this note, I think `peer_addr` is also a potentially useful function to have here.

**Comment by Noah-Kennedy** [comment]
I've got a PR up now to address this.
