### ISSUE TITLE
`tokio::spawn_named`

### ISSUE THREAD

**Issue by Milo123459** [tokio-rs/tokio#4100]
**Is your feature request related to a problem? Please describe.**
For the console
**Describe the solution you'd like**
A new function, `tokio::spawn_named` that takes an extra parameter for the name of the task
**Describe alternatives you've considered**
Writing my own function
**Additional context**
Happy to implement this

**Comment by seanmonstar** [comment]
My hunch is that we'd just stick with following the same pattern as in `std::thread`, by just having a builder that you can add a name to. There isn't a separate `std::thread::spawn_named`, for instance.

**Comment by Milo123459** [comment]
> My hunch is that we'd just stick with following the same pattern as in `std::thread`, by just having a builder that you can add a name to. There isn't a separate `std::thread::spawn_named`, for instance.

Ah alright.
