### ISSUE TITLE
Can't spawn task from dylib when using multi-thread scheduler

### ISSUE THREAD

**Issue by nicolaferraro** [tokio-rs/tokio#4102]
**Version**

```
└── tokio v1.11.0
    └── tokio-macros v1.3.0 (proc-macro)
└── tokio v1.11.0 (*)
```

**Platform**

`Linux localhost.localdomain 5.13.4-100.fc33.x86_64 #1 SMP Tue Jul 20 22:25:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

I'm creating an application that loads external plugins as `dylibs` and both the host and the lib use tokio to spawn tasks.
Since my goal is to create multiple plugins, I'd like them to share the same tokio Runtime.
The reactor is thus created by tokio::main and an `Handle` is passed to the plugin lib when loading it.

Everything seems to work as expected as long as a single-threaded scheduler is used (e.g. in tests, but also with `(flavor = "current_thread")` on the main).
Instead, the process hangs when using the multi-threaded scheduler. It seems that calls to `handle.spawn` are doing nothing when the call starts from the plugin.

I've created a reproducer here: https://github.com/nicolaferraro/libloading-rs/tree/ba38ab5d7bf6c60ac0295406403a3700dc292e6f

When using a single-threaded reactor the output of the program is:

```
1. Spawn on current runtime from main lib
2. Enter say_hello, let's spawn a new task on the handle from the dylib...
3. Print something (will never happen)!
4. Return value
5. End of main
```

Which is what I expect in general. Point `3` is printed inside a `handle.spawn` call from the plugin lib.

When using the multi-threaded reactor, the output is:

```
1. Spawn on current runtime from main lib
2. Enter say_hello, let's spawn a new task on the handle from the dylib...

```

Then the process hangs.

Is it possible to share the reactor and make it work also in multi-threaded mode?

**Comment by Darksonn** [comment]
This is probably impossible. Rust may not give Tokio's types the same layout in the main application and in the dylib. They may also use different memory allocators. I'm surprised it actually works for the current_thread runtime.

Generally, I would not expect anything but ordinary C FFI interfaces to work here, and I would follow the usual recommendations about always freeing memory in the piece that allocated it and putting `#[repr(C)]` on anything that needs to work across the boundary.

**Comment by nicolaferraro** [comment]
> This is probably impossible. Rust may not give Tokio's types the same layout in the main application and in the dylib. They may also use different memory allocators. I'm surprised it actually works for the current_thread runtime.
> 
> Generally, I would not expect anything but ordinary C FFI interfaces to work here, and I would follow the usual recommendations about always freeing memory in the piece that allocated it and putting `#[repr(C)]` on anything that needs to work across the boundary.

I see your concerns. But shouldn't the Rust ABI be ok if using the same compiler for both the main program and the libs?

The only reason why I'd like to split the app is that only a few plugins need to be loaded per process for the use cases I have in mind, so using a single compiler is an option.

**Comment by Darksonn** [comment]
It sounds sketchy to me, but I don't know.

**Comment by Darksonn** [comment]
Closing as won't fix
