### ISSUE TITLE
Lock `tokio::sync::Mutex`from synchronous code

### ISSUE THREAD

**Issue by dpc** [tokio-rs/tokio#4109]
**Is your feature request related to a problem? Please describe.**
I need to use async `Mutex` (because I need to lock between async yield points), but at the same time I need to share (and lock) it from some synchronous code.

**Describe the solution you'd like**
`lock_blocking` method on `Mutex` (and corresponding on `RwLock`) that allow locking the mutex from synchronous code.

**Describe alternatives you've considered**
Maybe there's a library that can do it already? I'm having trouble finding it though.

**Comment by Darksonn** [comment]
You can do this by calling `futures::executor::block_on(mutex.lock())`, though it could still make sense to add this. We have something similar for the mpsc channel.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
@dpc Can we close this issue now?

**Comment by Darksonn** [comment]
Oh, I didn't notice that the PR didn't include a [keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to auto-close it.

**Comment by leonardder** [comment]
Note that in the initial comment of this issue, equivalent synchronous methods were requested for RwLock. This wasn't covered by #4130
