### ISSUE TITLE
Only 128 oneshots are resolved in one `poll`

### ISSUE THREAD

**Issue by Sushisource** [tokio-rs/tokio#4111]
**Version**
1.11.0

**Platform**
Linux 5.13.13

**Description**
I'm implementing an API that lets users write potentially very long running code in a natural way using futures. More on the original code at the bottom.

Sometimes I create many `oneshot` channels that represent the results of external tasks that may or may not be fulfilled. Sometimes, the user's code using the API might create many "commands" which result in these channels being created, and immediately thereafter (in the same `poll` call which drives the user's code) my code will resolve those commands by `send`ing down the channels. As it stands, it's quite difficult to create these futures as already-resolved (though, I may have to do that if what I'm describing is not a bug / won't change).

The "bug" (which is maybe more like a not-explicitly-documented limitation) is that I have found that tokio seems to make only 128 of these channels `Ready` per `poll` call. I'd love to know more about if this is the intended behavior, and if so, what some better approaches might be.

I tried this code:

```rust
#[cfg(test)]
mod tests {
    use std::future::Future;
    use std::pin::Pin;
    use std::task::{Context, Poll};
    use futures::future::{BoxFuture, FutureExt};
    use tokio::sync::oneshot;

    struct MyFut {
        inner: BoxFuture<'static, ()>,
        oneshots: Vec<oneshot::Receiver<()>>
    }

    impl Future for MyFut {
        type Output = ();

        fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
            let r = self.inner.poll_unpin(cx);
            dbg!(self.oneshots.len());
            let mut ready_ct = 0;
            let mut pending_ct = 0;
            for os in self.oneshots.iter_mut() {
                match os.poll_unpin(cx) {
                    Poll::Ready(_) => ready_ct += 1,
                    Poll::Pending => pending_ct += 1,
                };
            }
            dbg!(ready_ct);
            dbg!(pending_ct);
            dbg!(r)
        }
    }

    #[tokio::test]
    async fn oneshot_sends_issue() {
        let mut send_chans = vec![];
        let mut recv_chans = vec![];
        for _ in 0..1000 {
            let (tx, rx) = oneshot::channel();
            send_chans.push(tx);
            recv_chans.push(rx);
        }

        let inner_fut = async {
            for sender in send_chans {
                sender.send(()).unwrap();
            }
        };

        let mf = MyFut {
            inner: inner_fut.boxed(),
            oneshots: recv_chans
        };
        mf.await;

    }
}
```

I expected to see this happen: 
```
[src/main.rs:23] self.oneshots.len() = 1000
[src/main.rs:32] ready_ct = 1000
[src/main.rs:33] pending_ct = 0
[src/main.rs:34] r = Ready(
    (),
)
```
Instead, this happened:
```
[src/main.rs:23] self.oneshots.len() = 1000
[src/main.rs:32] ready_ct = 128
[src/main.rs:33] pending_ct = 872
[src/main.rs:34] r = Ready(
    (),
)
```

For the curious, this is a dramatically simplified version of the code here: https://github.com/temporalio/sdk-core/blob/master/src/prototype_rust_sdk/workflow_future.rs#L228

**Comment by Sushisource** [comment]
Just by searching for `128` it looks like this is probably why: https://github.com/tokio-rs/tokio/blob/b42f21ec3e212ace25331d0c13889a45769e6006/tokio/src/coop.rs#L55

It would be lovely if this was a bit more explicit in the documentation, and possibly configurable. Any pointers about a better approach here are very welcome. Thank you!

**Comment by Darksonn** [comment]
This is intended behavior and how the coop system works. You can opt-out using [`tokio::task::unconstrained`][1].

[1]: https://docs.rs/tokio/1/tokio/task/fn.unconstrained.html

**Comment by Sushisource** [comment]
@Darksonn Awesome, I had figured that out a bit later and was going to post it back here but you beat me to it. Thanks for the info!

Closing this since I can't think of any obvious docs improvements that would've helped me. I just happened to miss the relevant spot, this issue existing might help people who went down a similar path I did.
