### ISSUE TITLE
TcpListener stops listening on Windows, but the same code works fine on Linux

### ISSUE THREAD

**Issue by sylverdrag** [tokio-rs/tokio#4124]
**Version**
tokio v 1.11.0

**Platform**
Windows 10 64 bit
**Description**

I am following along a tutorial to create a simple chat server. The step I am on creates a basic echo server:

```
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt}, 
    net::TcpListener,
};

#[tokio::main]
async fn main() {
    let listener = TcpListener::bind("localhost:8080").await.unwrap();

    let (mut socket, _addr) = listener.accept().await.unwrap();
    let mut buffer = [0u8; 1024];
    let bytes_read = socket.read(&mut buffer).await.unwrap();
    socket.write_all(&buffer[..bytes_read]).await.unwrap();
}

```
The server was supposed to accept the connection, wait for an input, and write back the same input. I send the input from telnet:
telnet localhost 8080

The server connects (at least, no error message) and the terminal is cleared for input. If I type anything, the server shuts down and displays "Connection to host is lost"

After trying several versions of tokio, I tried the same code from a Linux VM (copy paste), and it worked exactly as expected, so there is more likely an issue with Windows support.

**Comment by Darksonn** [comment]
I don't think this is a bug in Tokio, rather it's a difference in when your telnet client sends the characters being typed. I.e. does telnet wait for you to press enter before sending, or does it send on every character press? The difference is important because `TcpStream::read` returns as soon as at least one byte of data becomes available, so if telnet sends data on the first keypress, then that's when the `read` call returns.

Consider changing it to read until a newline is received. You can do that like this:
```Rust
use tokio::{
    io::{AsyncBufReadExt, AsyncWriteExt, BufReader},
    net::TcpListener,
};

#[tokio::main]
async fn main() {
    let listener = TcpListener::bind("localhost:8080").await.unwrap();

    let (socket, _addr) = listener.accept().await.unwrap();
    let mut socket = BufReader::new(socket);
    let mut buffer = String::new();
    socket.read_line(&mut buffer).await.unwrap();
    socket.write_all(buffer.as_bytes()).await.unwrap();
}
```

**Comment by sylverdrag** [comment]
Thanks. Seems like this was the issue. 

Now, the terminal waits for "enter", does not display what I type as I type it (the terminal is just a black screen). Then when I press enter it displays:

```
This is a test

Connection to host lost.
PS F:\rust\test\chatsrvr>
```
("This is a test" is the test string typed.) 

The server is working properly (I used println! to see that it is receiving the string), but I am puzzled by the absence of info displayed: On Linux, I get:

```
sylver@sylver-UbuntuVB:~/dev/rust/chat_server$ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Hello
Hello
Connection closed by foreign host.

```

On Windows, I only get the last two lines. 

Is there any way to make telnet behave the same way on Windows as it does on Linux?

**Comment by Darksonn** [comment]
I would probably try not closing the connection immediately? E.g. maybe you could add this at the end:
```Rust
tokio::time::sleep(tokio::time::Duration::from_secs(5)).await;
```
Furthermore, you might want to experiment with closing your `TcpStream` only in the write direction by calling [`shutdown`][1], then waiting for the telnet client to close it in the other direction by reading until you get a read of length zero. This is how a graceful shutdown of a TCP connection is done.

[1]: https://docs.rs/tokio/1/tokio/io/trait.AsyncWriteExt.html#method.shutdown

**Comment by sylverdrag** [comment]
Thanks for the tip. I think this issue can be closed since it's more a telnet issue than a Tokio issue.
