### ISSUE TITLE
Please update the documentation for try_join!

### ISSUE THREAD

**Issue by rwthompsonii** [tokio-rs/tokio#4127]
**Is your feature request related to a problem? Please describe.**
The docs tell you to spawn for parallelism but then don't tell you that you'll have to flatten the result for it to actually have the early return behavior you're using try_join *for*.     Please update the docs with an example very similar to: 

```
This is because, the return type of something you spawn is wrapped in Result<T, JoinError> in case the task panics or is aborted. To fix this, define a helper:
async fn flatten<T>(handle: JoinHandle<Result<T, SomeError>>) -> Result<T, SomeError> {
    match handle.await {
        Ok(Ok(result)) => Ok(result),
        Ok(Err(err)) => Err(err),
        Err(err) => Err(err.into()),
    }
}
You can now use try_join!.
match tokio::try_join!(flatten(renderer), flatten(listener)) {
    Ok(val) => {
        println!("success: {:?}", val);
        Ok(())
    }
    Err(val) => {
        println!("failure: {:?}", val);
        Err(val.into())
    }
}
Regarding tokio::select!, you should not include the call to .await in the selection. The macro automatically awaits them.
```

source: https://users.rust-lang.org/t/how-to-run-fallible-async-functions-in-parallel-returning-on-the-first-error/57303
**Describe the solution you'd like**
Please update the docs making it more clear how to do parallelism *and* early return on failure with try_join! macro.
**Describe alternatives you've considered**
None.
**Additional context**
It would be helpful to have this as it's a very common use case for this macro.

**Comment by hi-rustin** [comment]
I am working on this.
