### ISSUE TITLE
Updating to Mio v0.8

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/tokio#4135]
For Mio v0.8 I plan on removing the `TcpSocket` type. Followed (closely, hopefully) by a v1.

`TcpSocket` functionality has grown beyond what Mio should support as it's by no means limited to provided non-blocking I/O anymore. The [socket2](https://docs.rs/socket2) crate provides all functionality and will be my recommended replacement, but I'm biased as I maintain both crate. However @carllerche already indicated he wanted to keep the dependencies low, so adding socket isn't a solution. So, I'm opening issue to discuss to upgrade to Mio v0.8 with `TcpSocket`.

P.S. I don't there will be any other breaking changes to Mio v0.8.

/cc @carllerche

**Comment by Noah-Kennedy** [comment]
Would v0.8 add support for `UdpSocket::peer_addr`?

**Comment by Thomasdezeeuw** [comment]
> Would v0.8 add support for `UdpSocket::peer_addr`?

Yes, I think v0.7 couldn't because it was only added 1.40 which was too new at the time.
