### ISSUE TITLE
new "task_local_set" test suite failures with tokio 1.12.0

### ISSUE THREAD

**Issue by decathorpe** [tokio-rs/tokio#4138]
**Version**

tokio 1.12.0

**Platform**

x86_64-unknown-linux-gnu / Fedora Workstation 35 x86_64

**Description**

We're running tokio's test suite when building our distribution packages for the tokio crate, to make sure (to some degree) that tokio is working correctly on all our architectures (since it's used by quite a lot of projects). With the recent 1.12.0 release, two tests started failing when running the equivalent of `cargo test --release --all-features`:

```
     Running `/builddir/build/BUILD/tokio-1.12.0/target/release/deps/task_local_set-21920c572ff636f1`
running 19 tests
(...)
test localset_implicit_current_thread ... FAILED
test localset_implicit_multi_thread ... FAILED
(...)
failures:
---- localset_implicit_current_thread stdout ----
thread 'localset_implicit_current_thread' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /builddir/build/BUILD/tokio-1.12.0/src/task/local.rs:305:18
---- localset_implicit_multi_thread stdout ----
thread 'localset_implicit_multi_thread' panicked at '`spawn_local` called from outside of a `task::LocalSet`', /builddir/build/BUILD/tokio-1.12.0/src/task/local.rs:305:18
failures:
    localset_implicit_current_thread
    localset_implicit_multi_thread
test result: FAILED. 17 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
     Running `/builddir/build/BUILD/tokio-1.12.0/target/release/deps/tcp_accept-d07dd9a63b28e3ee`
```

It looks like there has actually been a PR that added these two tests shortly before the 1.12.0 release:
https://github.com/tokio-rs/tokio/pull/4027
So, since I assume that this PR didn't just add two broken tests, something else is going wrong?

**Comment by Darksonn** [comment]
This particular test requires a currently unreleased change in `tokio-macros`.

**Comment by decathorpe** [comment]
Thanks, that explains it. Then I'll just skip those two tests for now.

**Comment by Darksonn** [comment]
I'll try to make a release tomorrow or in two days.
