### ISSUE TITLE
Revisit docsrs settings now that cfg implies doc(cfg)

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#4163]
**Description**
A recent change to rustdoc makes `#[cfg]` now imply `#[doc(cfg)]`.  That's handy for most crates, but makes Tokio's various `cfg` macros now partially redundant and somewhat confusing.  In the best case, Tokio may be able to simply delete all of the docsrs stuff.
https://github.com/rust-lang/rust/pull/89596

**Comment by Darksonn** [comment]
I worry if this will make some things documented incorrectly. For example, we might have a `#[cfg(not(loom))]` on something, or maybe we use cfgs to choose between two implementations depending on a feature flag. E.g. the `#[tokio::main]` macro that is visible in the documentation has an `#[cfg(feature = "rt-multi-thread")]` even though it exists without that feature flag.

**Comment by hawkw** [comment]
> I worry if this will make some things documented incorrectly. For example, we might have a `#[cfg(not(loom))]` on something, or maybe we use cfgs to choose between two implementations depending on a feature flag. E.g. the `#[tokio::main]` macro that is visible in the documentation has an `#[cfg(feature = "rt-multi-thread")]` even though it exists without that feature flag.

According to the linked PR, we can use `#![doc(cfg_hide(loom))]` to disable generating docs for the loom cfg, at least. I'm not sure how this will behave for definitions where two separate versions of that definition are enabled/disabled based on the cfg attribute, though...

**Comment by hawkw** [comment]
> Does the change in rustdoc break anything for us, or just allow us to potentially simplify things?

It shouldn't *break builds*, but it may result in incorrect docs in some places, I think? Per @Darksonn's comment, there are some places where we use `#[doc(cfg(...))]` attributes for APIs that require a cfg but are not actually compiled out based on that cfg.
