### ISSUE TITLE
Provide access to reactor handle from current_thread::Runtime

### ISSUE THREAD

**Issue by saarw** [tokio-rs/tokio#417]
Hyper's HttpConnector requires a tokio_reactor::Handle, but current_thread::Runtime only provides access to its own handle struct. There's also no constructor for a current_thread::Runtime or its builder that lets one pass in the reactor so one can get the handle before creating the runtime.

**Comment by carllerche** [comment]
You can always call `Handle::default()`.

If this works, maybe submit a doc PR to hyper that adds a note explaining that `default` can be used.

**Comment by seanmonstar** [comment]
Hm? It's not required, the default will be used. There is just an alternative constructor if you wish to make it register with a specific reactor.

**Comment by saarw** [comment]
I want to use the specific reactor created in the current_thread::Runtime builder. It seems that Handle::default uses the reactor set in a thread local that is only populated when executing a task inside a reactor (when with_default is invoked), but I'm creating the hyper HttpConnector outside of any reactor tasks so I would not expect the thread local to be populated with the Runtime's reactor.

Will the current_thread::Runtime's reactor still somehow become the default reactor and prevent new reactors from being created for the HttpConnector if I leave the handle argument empty or use Handle::default? (I haven't been able to follow how the default reactor connects to the created runtime in the source)

**Comment by carllerche** [comment]
@saarw in theory, it should still work because `HttpConnector` only passes that handle -> `TcpStream` and that fn only uses the handle once it is spawned onto a task.

In short, calling `Handle::default()` while **off** task should work fine.

**Comment by saarw** [comment]
Ok, thanks! It seems to work, was just worried that the hyper task would be running in some other lazily-started reactor as I'd like to keep everything in one thread.
