### ISSUE TITLE
`handle` parameter for Connection in tokio-postgres

### ISSUE THREAD

**Issue by adam0z** [tokio-rs/tokio#418]
I would like to start using `tokio-postgres` with `tokio-threadpool` crate.

I need to pass a tokio_core::reactor::Handle to connect method:
https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/lib.rs#L299

In tokio-postgres examples they get a handle from:
```
let mut core = Core::new().unwrap();
let handle = core.handle();
```
How can I access a handle (I guess to a thread event loop) inside a Future passed to [spawn function](https://docs.rs/tokio-threadpool/0.1.4/tokio_threadpool/struct.ThreadPool.html#method.spawn)?

Should I do it as I wrote above?

**Comment by carllerche** [comment]
Unfortunately, it looks like tokio-postgres still depends on `tokio-core`, which has been deprecated. Since `tokio_core::reactor::Handle` is not `Send`, it cannot be used with the thread pool. 

This is the issue tracking the upgrade: https://github.com/sfackler/rust-postgres/issues/334
