### ISSUE TITLE
Questions on `blocking` strategy and behavior

### ISSUE THREAD

**Issue by dekellum** [tokio-rs/tokio#419]
The -threadpool and -fs code is pretty readable but I'm unclear on a few details and beyond the code, I want to understand more of the the feature's intentions and direction.   If I can get answers to the following questions, I will also attempt to contribute this back as documentation for #339.

There is a `max_blocking` setting on the threadpool, which currently defaults to 100 threads.  **Q1**: Is the primary intention here to protect against unbounded thread creation in some problem scenarios?  If blocking was used solely for file-system I/O, I suspect this seemingly high default, if used to capacity, would likely result in sub-optimal performance. 

A `Worker` thread transitions to the `is_blocking` state on entering a `blocking` closure.  Currently there is no transition back to the non-blocking state where a `Worker` could again take the event loop (stated better as: drive the Reactor?). Worker::transition_from_blocking currently just has:
``` rust
    // TODO: Attempt to take ownership of the worker again`
```
**Q2**: This couldn't just simply be changed to the following?
``` rust
    self.is_blocking.set(false);
```
I assume not, but why is that?

**Q3**: These blocking workers, or any workers with no work are put to sleep and will eventually be shutdown?

**Q4**: A sleeping blocking worker can be given additional work when another `blocking` closure is run, so _every_ `blocking` call does not have the cost of OS new thread creation, correct? Some blocking calls will have this cost, though, correct?

The `tokio_threadpool::blocking` method returns `Poll` which may return `NotReady` if the max_blocking limit has been reached.  In tokio::fs, for example for the `tokio_fs::File` wrapper, methods that return an io::Result, for example in the impl of `Read` and `Write`, will convert this to `io::ErrorKind::WouldBlock` (for example from the tokio_fs::would_block helper).   This probably deserves some documentation at least, as I suspect that most initial users of `tokio_fs::File` would simply treat `WouldBlock` like any other I/O error and they will only see that at high load, with max_blocking exceeded, in benchmarks or worst case, production. **Q5**:  Or am I missing something here?

To *do this right* in user code: Checking for `WouldBlock`, backing up the current state and constructing a new future awaiting availability of a blocking thread to run the blocking operation, seems pretty complex. 

In a fully asynchronous server, all blocking work should originate from events in the `Reactor`. An easier model for avoiding unbounded blocking thread growth might be to just go ahead an execute the blocking operation on the reactor thread, if and only if `max_blocking` is exceeded, and perhaps with a log warning.  Then `blocking`, or a new variant like `blocking_anyway` would never need to return `NotReady` and instead of `Poll` could just return the closures `T` return. Since the current `blocking` method takes an `FnOnce` its ackward but not impossible to do this already in user code. **Q6**:  Is this alternative strategy reasonable? Would you consider a PR for a `blocking_anyway` method (or alt suggestion on naming)?

If this was in place, I would probably configure `max_blocking` lower, or the default could be lower as well, say CPUs * C where C was 2 or 3?

You mention a possible fallback strategy for tokio-fs in the context of the current thread runtime in this 
[comment](https://github.com/tokio-rs/tokio/issues/386#issuecomment-395487336) on #386. If the above is acceptable, **Q7**: would this also be a reasonable fallback strategy for this case; e.g. when on the current thread runtime, `blocking` operations still block the current (reactor) thread, since its the only thread available?

**Comment by carllerche** [comment]
Re: Q1

> Is the primary intention here to protect against unbounded thread creation

Yes

> If blocking was used solely for file-system I/O

It is for any blocking task (mutex, file, etc...)

> I suspect this seemingly high default, if used to capacity, would likely result in sub-optimal performance.

Possibly, not a ton of thought was put into that default value.

Re: Q2:

> This couldn't just simply be changed to the following?
>
> ```rust
>  self.is_blocking.set(false);
> ```

It's a bit more complicated. When a worker switches to blocking, it hands off its work queue (well, really its `worker::Entry` reference) to a backup thread. This hand off will take some amount of time as the thread either has to wake up or a new thread is spawned.

If the blocking section is short (for example, a file read when all the data is cached), then it is possible for the blocking call to finish before the `worker::Entry` hand off is complete. The thread needs to claim back the `worker::Entry`, preventing the other thread that is receiving the hand off to actually take ownership of it.

It gets more complicated in that there are more complicated races where thread A hands off the `worker::Entry` to thread B, but thread B is stalled. Thread A claims the `worker::Entry` back, enters a second `blocking section, and hands its `worker::Entry` to thread C. Then thread B wakes up and wins the race for the `worker::Entry` before thread C can...

All of this can be dealt with and I don't think the end code would be *that* complex, but it is more involved than setting `self.is_blocking`.

Re: Q3:

> These blocking workers, or any workers with no work are put to sleep and will eventually be shutdown?

The backup threads should terminate eventually, but currently will not (#427 - I haven't gotten to this yet). "Worker" threads will terminate when idle (if configured to do so).

Re: Q4:

> A sleeping blocking worker can be given additional work when another blocking closure is run, so every blocking call does not have the cost of OS new thread creation, correct? Some blocking calls will have this cost, though, correct?

Correct. Once a thread is spawned and has completed its work, it goes to sleep (using a condvar) until there is more work. The pool attempts to avoid spawning new threads if possible.

Re: `Read`, `Write,` and `io::ErrorKind::WouldBlock`

When using `tokio_fs::File`, users should avoid using the `std::io::Read` and `std::io::Write` traits. Instead, they should use `poll_read` and `poll_write` on `AsyncRead` and `AsyncWrite`.

It is unfortunate that `AsyncRead: std::io::Read`. This was done a while ago and was a mistake. Fixing this will require a breaking change though.

Re: Q6

If I understood the strategy, it would require *sometimes* blocking the reactor thread. If so, it makes me pretty uncomfortable to offer an API that can ever block the reactor thread when used in-appropriately.

I also am not sure that I understand the advantage of doing so vs. the current strategy. The current strategy makes a `tokio::fs::File` act the same way as `tokio::net::TcpStream`.

Perhaps you can try to explain a bit more your aversion to `tokio::fs::File::poll_read()` returning `NotReady` when `max_blocking` is reached.

Re: comment on #386.

The strategy I had in mind was to have a thread pool that was off to the side to power tokio-fs. This strategy would require significantly more thread coordination as well as some extra data copying, but it would allow tokio-fs to work in all contexts.

If you are interested in attempting this, I can try to write up my thoughts in more detail.

**Comment by dekellum** [comment]
Thanks very much for the detailed response. Your answers prompt me to further question my use case and explore other possible alternatives.  My initial use case of `blocking` is to handle writing chunks of large HTTP bodies to temporary files, which thus far I've done inside a `Stream::fold` closure.  What was encouraging about the `blocking` feature was the prospect of better async. behavior/performance without needing to radically change this portion of the application.  But without radical change the best it appears I can do, is either to treat exhausting the backup threads as a write error, which isn't really acceptable, or block the worker thread as a last resort.

[Here](https://github.com/dekellum/body-image/blob/d2ad8435afd7ce4f4f7c337f6943c4e6fa5efbfc/src/client.rs#L358) is my current implementation of the latter approach.

I'm going to next attempt the more radical change of re-implementing as a custom future with states for awaiting a blocking thread and proceeding with the writes, while consuming from the body stream.  I'm not entirely certain that this is possible. I will be going deeper into futures than I've previously gone.

**Comment by carllerche** [comment]
👍 

I'm going to close the issue. If you have further questions, feel free to post.

**Comment by dekellum** [comment]
FYI, I ended up implementing an [AsyncBodySink](https://github.com/dekellum/body-image/compare/tokio-reform...tokio-nonblocking-sink#diff-31bbf71c54bca98a0ae3d40a327af940R348), impl `futures::Sink`, to make my application fully compliant when `blocking` returns `Async::NotReady` (backup/max_blocking threads limit reached). It wasn't too bad, "once you know how to do it", either in complexity or code volume. 

Testing isn't complete. I don't yet have a good benchmark to see the presumed benefits of this fully asynchronous approach, and for comparing pool_size vs max_blocking settings.  I suspect that there might be some performance benefit, vs. RAM utilization, to buffering blocking writes (beyond the typical 8K HTTP Chunk) which this Sink could be extended to do.

In any case, beyond learning some more of *futures*, I think I now understand enough about `blocking` to attempt #339.   Thanks again!
