### ISSUE TITLE
Poll op error

### ISSUE THREAD

**Issue by Milo123459** [tokio-rs/tokio#4206]
**Version**
List the versions of all `tokio` crates you are using. The easiest way to get
this information is using `cargo tree` subcommand:

```rs
????????? console-subscriber v0.1.0 (https://github.com/tokio-rs/console?branch=main#31704326)
???   ????????? console-api v0.1.0 (https://github.com/tokio-rs/console?branch=main#31704326)
???   ???   ???   ???   ????????? tokio v1.13.0
???   ???   ???   ???   ???   ????????? tokio-macros v1.5.1 (proc-macro)
???   ???   ???   ???   ????????? tokio-util v0.6.9
???   ???   ???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ???   ????????? tokio-io-timeout v1.1.1
???   ???   ???   ???       ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio-stream v0.1.8
???   ???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio-util v0.6.9 (*)
???   ???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ???   ????????? tokio-stream v0.1.8 (*)
???   ???   ???   ???   ????????? tokio-util v0.6.9 (*)
???   ????????? tokio v1.13.0 (*)
???   ????????? tokio-stream v0.1.8 (*)
???   ???   ????????? tokio v1.13.0 (*)
???   ???   ????????? tokio-rustls v0.22.0
???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio-rustls v0.22.0 (*)
???   ???   ????????? tokio v1.13.0 (*)
???   ???   ????????? tokio-rustls v0.22.0 (*)
???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio v1.13.0 (*)
???   ???   ???   ????????? tokio-rustls v0.22.0 (*)
???   ???   ????????? tokio-stream v0.1.8 (*)
????????? tokio v1.13.0 (*)
```

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

Windows 64-bit

**Description**
Enter your issue details here.
One way to structure the description:

[short summary of the bug]

I tried this code: N/A (Can't find out where it is coming from)

[code sample that causes the bug]

I expected to see this happen: Shouldn't log an error

Instead, this happened: Logs this error: https://sourceb.in/wwCmo0qpY7

**Comment by Milo123459** [comment]
Error only happens when I update with cargo update, this is what is updating.
```
    Updating tokio v1.12.0 -> v1.13.0
    Updating tokio-macros v1.5.0 -> v1.5.1
    Updating tokio-stream v0.1.7 -> v0.1.8
    Updating tokio-util v0.6.8 -> v0.6.9
```

**Comment by Darksonn** [comment]
cc @hawkw @zaharidichev

**Comment by zaharidichev** [comment]
@Milo123459 Will me looking at that tomorrow. Do you have any code sample that reproduces the issue as this will make things much easier?

**Comment by Milo123459** [comment]
> @Milo123459 Will me looking at that tomorrow. Do you have any code sample that reproduces the issue as this will make things much easier?

Not really. I just know that it appears in the new version of tokio (v1.13.0) and comes from the sleep.rs file.

**Comment by Darksonn** [comment]
In the discord, the lines `src/time/driver/sleep.rs:368` and `src/time/driver/sleep.rs:379` were cited as the source of the prints.

**Comment by hawkw** [comment]
I think this should maybe be an issue on the `tokio/console` repo rather than on Tokio itself. I believe that warning is printed from code in the `console-subscriber` crate, rather than from Tokio.

**Comment by hawkw** [comment]
> In the discord, the lines `src/time/driver/sleep.rs:368` and `src/time/driver/sleep.rs:379` were cited as the source of the prints.

This is where the `poll_op` event was produced, it's not _actually_ where the message is printed --- the message is printed from within `console-subscriber`, but it includes the debug output for the `tracing` event, which has those lines as part of its metadata.

**Comment by Milo123459** [comment]
So this is a problem with console-subscriber

**Comment by hawkw** [comment]
> So this is a problem with console-subscriber

not *necessarily*, but those warnings are printed by `console-subscriber`. specifically, what it's saying is that the events emitted by `tokio::time` are not in the form that `console-subscriber` expects them to be in. i can't easily say whether this is an issue in `console-subscriber`, an issue with the actual events emitted by tokio, or both.

**Comment by hawkw** [comment]
it would be helpful to have a minimal working reproduction of code that generates these warnings.

**Comment by Milo123459** [comment]
> it would be helpful to have a minimal working reproduction of code that generates these warnings.

I'm not entirely sure whats causing it, so that's the problem.

**Comment by hawkw** [comment]
is the code that generates the warning open source?

**Comment by Milo123459** [comment]
Sadly no.

**Comment by hawkw** [comment]
Okay, in that case, we can't really investigate this issue without some kind of reproduction. You'll need to try and isolate the code from the closed-source project that generates the warning and put together a shareable reproduction.

**Comment by hawkw** [comment]
I did notice that the `tokio-console` example app only uses `time::sleep` (and not `time::interval`). I modified the example to use `interval`, just in case that the issue was triggered specifically by the use of that API...but I still can't reproduce the warning.

**Comment by Milo123459** [comment]
I could possibly invite you to the repo?

**Comment by Darksonn** [comment]
@Milo123459 It would be very helpful if you were able to create a minimal, reproducible example containing the issue.

**Comment by Milo123459** [comment]
Shall try

**Comment by Milo123459** [comment]
I have created one!

`src/main.rs`
```rs
#[tokio::main]
async fn main() {
    console_subscriber::init();
    tokio::time::sleep(tokio::time::Duration::from_secs(4)).await;
}
```
`Cargo.toml`
```toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.13.0", features = ["rt-multi-thread"] }
console-subscriber = { git = "https://github.com/tokio-rs/console", branch = "main" }
```
`.cargo/Config`
```toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```

**Comment by zaharidichev** [comment]
will take a look very shortly

**Comment by Milo123459** [comment]
Are there any hacky workarounds for this yet, or just any updates?

**Comment by zaharidichev** [comment]
Yes, the issue has been identified. Basically, the problem is that these tasks have been spawned before the console subscriber has been initialized. Will submit a fix in a day or two. The problem is that there is not an elegant fist apart from ignoring the error and dropping these events without printing annoying messages

**Comment by zaharidichev** [comment]
@Milo123459 What you can do as a workaround is: 

```
#[tokio::main]
async fn main() {
    tokio::spawn(async move {
          console_subscriber::init();
          tokio::time::sleep(tokio::time::Duration::from_secs(4)).await; 
    })
}
```

**Comment by Darksonn** [comment]
@zaharidichev Is there anything we should do about this in Tokio itself?

**Comment by hawkw** [comment]
Yeah, the issue here is just that the `#[tokio::main]` task is created _before_ the console was set up, so it doesn't know about that task, and any timers (etc) awaited directly in `main` (rather than in a task spawned by `main`) don't appear to be within a task from the console's perspective. tokio-rs/console#186 fixes this upstream by making the console not care. :)
