### ISSUE TITLE
Notify: basic example intermittently fails

### ISSUE THREAD

**Issue by davidcopp** [tokio-rs/tokio#4210]
When running the given [Notify - basic example](https://docs.rs/tokio/1.13.0/tokio/sync/struct.Notify.html#examples) (tokio 1.13.0 on MacOs 11.6), the correct output is

```
sending notification
received notification
```

but more often I get only

```
sending notification
```

Joining the spawned task fixes the problem:
```
    let join = tokio::spawn(async move {
        notify2.notified().await;
        println!("received notification");
    });

    println!("sending notification");
    notify.notify_one();
    println!("joining spawned task");
    join.await.expect("spawn failed");
    println!("spawned task completed");
```

Could be a  doc or a real bug, not sure.

**Comment by Darksonn** [comment]
Thanks for reporting. This is a problem in the documentation - the spawned task is killed when main returns, so it may never get to run.
