### ISSUE TITLE
tokio runtime could not be created

### ISSUE THREAD

**Issue by Algorab** [tokio-rs/tokio#4220]
I have a project where I use arm actix(tokio) musl mimalloc. When I run it on the raspberry I can see a error message in the title with running under valgrind.
I am not sure what cause the real problem.
A [arm-musl-mimalloc-actix repo ](https://github.com/Algorab/arm-musl-mimalloc-actix) is available for reproduce the error and
everything is explained in more detail.

I start rust programming a view month ago, so my experience isn't very deep. Hope somebody can help me or point me to the right direction.

**Comment by sfackler** [comment]
The error message from valgrind says you should report the bug to them.

**Comment by Algorab** [comment]
It is also crashing when I don't use valgrind, see the core dump. So valgrind isn't the real cause.

**Comment by Algorab** [comment]
@taiki-e I tried this flag. This produces a dynamic linked library with this flag, for some reason I want a static one. The raspberry pi 4 can also run in 64bit mode as aarch64. I compiled my program for this target and run the raspberry pi in 64bit and the start behaviour was the same. So I think 32bit cause not the problem.

@Darksonn I create a new [repo](https://github.com/Algorab/arm-musl-mimalloc-tokio) which hopefully met what you wrote. And did also some tests, the results you can find in the Readme.

**Comment by Darksonn** [comment]
Since it fails only with `mimalloc`, it sounds like there is some operation that the runtime needs that is not supported when using `mimalloc`.

**Comment by Algorab** [comment]
@taiki-e You are right,  rust-musl-cross uses the latest version of 
musl-cross-make which is version 0.9.9.  musl-cross-make 0.9.9 has the latest version of musl 1.1.24. I build a local image with musl 1.2.2 and run the tests on the raspberry. No crashes anymore. 

@Darksonn @taiki-e  Thanks for helping / pointing me to the right direction.
