### ISSUE TITLE
Still clippy warning after `macros: fix wrong error messages #4067`

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [tokio-rs/tokio#4245]
**Version**
1.13.0

**Platform**
* Rust Playground
* `Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description**
In https://github.com/tokio-rs/tokio/pull/4067, there was a discussion about a falsely Clippy warning `clippy::semicolon_if_nothing_returned` in tokio's main and test.
Most problems were solved in #4176.
However, I encountered some leftovers that still pose the same problem.

I could reproduce it in Rust Playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=39638811ab983f5bea782a42d5d184b9

```Rust
#![warn(clippy::semicolon_if_nothing_returned)]

use tokio; // 1.13.0

async fn foo() -> &'static str {
    "foo"
}

#[tokio::main]
async fn main() {
    let _foo = foo().await;
}
```

The output of Clippy is 

>  Checking playground v0.0.1 (/playground)
> warning: this import is redundant
>  --> src/main.rs:3:1
>   |
> 3 | use tokio; // 1.13.0
>   | ^^^^^^^^^^ help: remove it entirely
>   |
>   = note: `#[warn(clippy::single_component_path_imports)]` on by default
>   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
> 
> warning: consider adding a `;` to the last statement for consistent formatting
>   --> src/main.rs:11:5
>    |
> 11 |     let _foo = foo().await;
>    |     ^^^^^^^^^^^^^^^^^^^^^^^ help: add a `;` here: `let _foo = foo().await;;`
>    |
> note: the lint level is defined here
>   --> src/main.rs:1:9
>    |
> 1  | #![warn(clippy::semicolon_if_nothing_returned)]
>    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#semicolon_if_nothing_returned
> 
> warning: `playground` (bin "playground") generated 2 warnings
>     Finished dev [unoptimized + debuginfo] target(s) in 2.09s

My current state of investigation is, that this problem arises when `….async;` is the last command in the function that is rewritten by tokio's main or test.

An expansion brings the following output:
```Rust
#![feature(prelude_import)]
#![warn(clippy::semicolon_if_nothing_returned)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
use tokio;
async fn foo() -> &'static str {
    "foo"
}
fn main() {
    let body = async {
        let _foo = foo().await;
    };
    #[allow(clippy::expect_used)]
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("Failed building the Runtime")
        .block_on(body)
}
```

So, the semicolon is missing here. But if `….async;` isn't the last expression, then there is a `;`.

**Comment by taiki-e** [comment]
we need to handle syn::stmt::local the same as non-`return` syn::stmt::semi.

https://github.com/tokio-rs/tokio/blob/b1afd95994be0d46ea70ba784439a684a787f50e/tokio-macros/src/entry.rs#L341-L342
