### ISSUE TITLE
No 1.14 release on GitHub?

### ISSUE THREAD

**Issue by davepacheco** [tokio-rs/tokio#4266]
It looks like 1.14 was released to crates.io last week but there's no corresponding GitHub release with change notes and no tag for it.  Is that intended?

**Comment by Darksonn** [comment]
This has been fixed.

**Comment by davepacheco** [comment]
Thanks!  The change notes are really helpful for us.

**Comment by Darksonn** [comment]
The changelog can also be found here: https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md
