### ISSUE TITLE
Missing Command::get_{args,envs}

### ISSUE THREAD

**Issue by alecmocatta** [tokio-rs/tokio#4285]
Tokio's `std::process::Command` wrapper, `tokio::process::Command`, is missing [`Command::get_args`](https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.get_args) and [`Command::get_envs`](https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.get_envs).

Can be worked around in my case, but would be great to have parity here. Bumped into this porting some code to `tokio`.

**Comment by ipetkov** [comment]
Thanks for the report! I'll try to take a look at this when I'm back from vacation next week. 

If anyone wants take a shot at implementing it, feel free to ping me on the PR!

**Comment by Yogaflre** [comment]
https://github.com/rust-lang/rust/issues/44434

**Comment by Yogaflre** [comment]
It looks like it's unstable yet.
https://github.com/rust-lang/rust/issues/44434

**Comment by ipetkov** [comment]
Unfortunately, [our MSRV policy](https://github.com/tokio-rs/tokio/blob/master/CONTRIBUTING.md#mininum-supported-rust-version-msrv) requires that we support compilers from at least 6 months back, meaning we won't be able to rely on these methods from the stdlib for 6 months... :(

I've opened #4295 to add a `cmd.as_std()` method which will allow the caller to access the underlying `std::process::Command`, and therefore the new methods (if their stdlib version is new enough)

**Comment by ipetkov** [comment]
@alecmocatta #4295 has landed in 1.15.0 so I'm going to resolve this for now. Feel free to reopen if you have other issues or questions!
