### ISSUE TITLE
Problem with nested `tokio::task::spawn` and `now_or_never`

### ISSUE THREAD

**Issue by Gabriel4256** [tokio-rs/tokio#4288]
**Version**
└── tokio v1.14.0
    └── tokio-macros v1.6.0 (proc-macro)
├── futures v0.3.18

**Platform**
Linux 5.15.0-051500-generic x86_64 GNU/Linux

**Description**
What I want to do is like the following:
1. There is multiple executors that are run in parallel.
2. Each executor execute fixed number of `small_job` set without waiting and periodically check whether all executed small jobs are finished. 
  2-1. If so,execute next set of `small_job`s
  2-2. Otherwise, get over to next check

For this, I implemented each small job and executor as async function, and used nested `tokio::task::spawn` and `now_or_never` to check the   progress of each small job.

And following is a minimal reproduction for the problem: 
```rust
#[tokio::main]
async fn main() {
    let result = tokio::task::spawn(async move {
        
        let mut join_handle = tokio::task::spawn(
            async move { small_job().await }
        );

        loop {
            let status = (&mut join_handle).now_or_never();
    
            if let Some(_) = status {
                println!("completed");
                break;
            } else {
                println!("on progress");
            }
        }
    });
    let _ = result.await;
}

async fn small_job() {
    tokio::time::sleep(Duration::from_secs(1)).await;
}
```

I expected to program finishes with "completed" as a last print. 
Instead, it never ends with printing "on progress" endlessly, which means `now_or_never` always returns `None`. Is there anything wrong with the code above?

Please let me know if I am missing something. Thanks in advance.

**Comment by Darksonn** [comment]
Your loop has no `.await`, so it is [blocking the thread][1].

[1]: https://ryhl.io/blog/async-what-is-blocking/

**Comment by Gabriel4256** [comment]
I read the post you shared and solved the issue. Thank you!
