### ISSUE TITLE
Current thread runtime doesn't exit when main task completes when using yield

### ISSUE THREAD

**Issue by austenadler** [tokio-rs/tokio#4290]
As discussed at reinvent with @carllerche. Issue is within `fact_yielding` below. Tokio should cancel when another path is `select!`ed, but it doesn't likely because it is stuck in the tight loop here: https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/basic_scheduler.rs#L245. Also, MAX_TASKS_PER_TICK=61 is eerily close to 57 (in output below).

Code:
```
// Computes factorial of n, printing progress along the way.
async fn fact_stiff(n: u32) -> f64 {
    let mut i = 0_u32;
    let mut accum = 1_f64;
    loop {
        println!("i: {I} fact_{N}({I}): {A}", N = n, I = i, A = accum);
        if i == n {
            break;
        }
        i += 1;
        accum += i as f64;
    }
    accum
}
// Computes factorial of n, printing progress along the way.
async fn fact_yielding(n: u32) -> f64 {
    let mut i = 0_u32;
    let mut accum = 1_f64;
    loop {
        println!("i: {I} fact_{N}({I}): {A}", N = n, I = i, A = accum);
        if i == n {
            break;
        }
        // println!("About to yield");

        // Gets to iteration 57
        tokio::task::yield_now().await;
        // Gets to iteration
        // tokio::time::sleep(std::time::Duration::from_millis(10)).await;

        i += 1;
        accum += i as f64;
    }
    accum
}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tokio::spawn(async {
        let answer = tokio::select! {
            fact_5 = tokio::task::spawn(fact_stiff(50)) => fact_5,
            fact_10 = tokio::task::spawn(fact_yielding(100)) => fact_10,
        };
        println!("answer: {:?}", answer);
    })
    .await?;
    println!("done");
    Ok(())
}
```

Output:
```
i: 0 fact_50(0): 1
i: 1 fact_50(1): 2
i: 2 fact_50(2): 4
...
i: 49 fact_50(49): 1226
i: 50 fact_50(50): 1276
i: 0 fact_100(0): 1
answer: Ok(1276.0)
i: 1 fact_100(1): 2
i: 2 fact_100(2): 4
i: 3 fact_100(3): 7
...
i: 56 fact_100(56): 1597
i: 57 fact_100(57): 1654
done
```

Expected output:
Tokio should stop polling fact_100 after Ok(1276.0).

**Comment by carllerche** [comment]
I debugged this some and it seems like the scheduler is stuck checking the queue for max ticks so doesn’t see that the runtime should shut down.

**Comment by Darksonn** [comment]
I do not think that the behavior is incorrect, actually. We don't guarantee anything about when we poll which tasks, so if we want to poll a bunch of other tasks before we poll main again, then that is allowed under our guarantees. The runtime shuts down when it's supposed to, i.e. immediately when `main` returns.

The tasks in the `select!` are not cancelled because dropping the `JoinHandle` doesn't cancel the task.

**Comment by austenadler** [comment]
It could definitely not be a bug; I'm not too familiar with the guarantees of the library, but if "runtime shutdown *immediately* when main returns" is a promise, isn't this being broken? The task is being polled 57 times after (the async) main returns here because the poller doesn't know the runtime needs to be shut down.

**Comment by Darksonn** [comment]
It really should shut down properly once main returns, even if you remove the `tokio::spawn` wrapping.

**Comment by oldgalileo** [comment]
Has there been any movement or is there any way to resolve this? I'm seeing issues with `tokio::main` continuing on.

**Comment by Darksonn** [comment]
I don't think the behavior described here is wrong. The runtime shuts down immediately when `main` returns - its just that `main` didn't return when the author of the PR expected it to.
