### ISSUE TITLE
impl SpawnExt for tokio's runtime

### ISSUE THREAD

**Issue by realcr** [tokio-rs/tokio#4297]
**Is your feature request related to a problem? Please describe.**

Whenever I write a large project, I like to be able to write the core logic separately, and finally plug in a a runtime on the main file.
The main reasons are:
- Being able to test easily, without having to depend on any specific runtime.
- Being able to swap runtimes without having to change lots of code.

This is easy to do with futures-rs, having the `SpawnExt` trait. The `SpawnExt` trait has a `spawn()` method that is independent of the implementation. Having a trait that represents a runtime, or even an object that I can use to spawn tasks, allows me to write code that describes async semantics without any dependency on implementation details. This is generally something I can not do when using tokio.

I realize that usually futures-rs executors and tokio runtimes are not intechangeable (which is a real shame itself), but I would still like to enjoy the benefits of having tokio-free codebase, at least on the core parts of my codebase.

**Describe the solution you'd like**

In an ideal world, all async libraries are going to have a single trait that represents the basics of what we want a runtime or an executor to do, something like SpawnExt. Being more realistic, it would have been nice if tokio's runtime could implement `SpawnExt`. 

**Describe alternatives you've considered**
Whenever I use tokio I usually have to rely on third party tools like `https://github.com/smol-rs/async-compat` to "disinfect" my codebase from tokio specific code.

Finally, thank you for your work on tokio!

**Comment by MikailBag** [comment]
It seems that a basic integration is pretty straightforward: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c63e153f8a0eae7af6f84e7a7f76fb73

**Comment by Darksonn** [comment]
Tokio does not depend on the futures crate, and we aren't going to add any non-1.x crates to the public API of Tokio.

**Comment by realcr** [comment]
@MikailBag This is a really neat workaround that I am definitely going to use. Thanks!

> Tokio does not depend on the futures crate, and we aren't going to add any non-1.x crates to the public API of Tokio.

I can understand this reasoning. Maybe such a trait should be somewhere in `core::future::*`? But then of course it should be a well thought trait. Maybe this is a future consideration, when things become more stable in the async ecosystem.

**Comment by Darksonn** [comment]
If such a trait gets added to the standard library, we would implement it once our minimum-supported-rust-version is recent enough to allow us to.

I'll close this issue for now.

**Comment by Sytten** [comment]
I feel this could be added to a tokio-compact library as one was created in the past for tokio 0.2 and futures 0.1.
