### ISSUE TITLE
 i migrate from Erlang to Rust, But why community recommending single-thread instead of multithread 

### ISSUE THREAD

**Issue by Rustixir** [tokio-rs/tokio#4311]
Hi everyone.
I migrated from Erlang to Rust.
But when I learned **Tokio** and then **Tonic**

Every time I ask the forum why my code is not fast
They said use this:
```
#[tokio::main(flavor = "current_thread")]
```

Where is the problem in Tokio multithreading ?
Which does not exist in Erlang or Akka or even Golang

**because im working on distributed database and need multi threading**

**Comment by Darksonn** [comment]
This is being discussed at https://users.rust-lang.org/t/my-benchmark-done-elixir-is-faster-than-rust-tokio-how-do-i-improve-rust-code/68577/7

**Comment by Rustixir** [comment]
yes, really thank you from that,  

but this about why multithreading not great here ??!

I used erlang for backend of project, 
25 Core 50 Ram

and there was linear relative 
increase performance with increase cpu
until 60 core
