### ISSUE TITLE
Create a tokio::process::Child in a new process group

### ISSUE THREAD

**Issue by kpcyrd** [tokio-rs/tokio#4312]
**Is your feature request related to a problem? Please describe.**

I want to create a child process and later be able to kill this child with all of it's sub- and sub-sub- children on unix-style operating systems.

**Describe the solution you'd like**

Something along the lines of:

`.set_process_group(0)`

**Describe alternatives you've considered**

I'm currently using this code to implement it:

```rust
    unsafe {
        cmd.pre_exec(|| {
            // create a new process group
            let pid = nix::unistd::getpid();
            if let Err(err) = nix::unistd::setpgid(pid, Pid::from_raw(0)) {
                warn!("Failed to create new process group: {:#?}", err);
            }
            Ok(())
        });
    }
```

`setpgid` needs to be called before `exec` is called after `fork`.

**Additional context**

https://www.gnu.org/software/libc/manual/html_node/Process-Group-Functions.html

**Comment by Darksonn** [comment]
Thoughts @ipetkov ?

**Comment by ipetkov** [comment]
Unfortunately, I think this is the only way to accomplish this. We pretty much wrap the stdlib types, and there aren't any OS extensions that I could find which do the `setpgid` calls for us

**Comment by kpcyrd** [comment]
Would it help if I propose this extension in the stdlib?

**Comment by ipetkov** [comment]
It's worth a shot! We don't *need* to wait on the stdlib to potentially add such a wrapper, but having the feature parity would be nice

**Comment by danyspin97** [comment]
The stdlib has [`process_group`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.process_group) in `std::os::unix::process::CommandExt` but it's unstable for now.

**Comment by ipetkov** [comment]
Looks like `process_group` [was stabilized](https://github.com/rust-lang/rust/pull/99088) and will land on 1.64

**Comment by ipetkov** [comment]
I think next steps for this are:

- [ ] wait for 1.64 to be released
- [ ] add a `process_group` API behind a `tokio_unstable` flag
- [ ] stabilize the API once our MSRV policy allows for requiring a compiler that is >= 1.64
