### ISSUE TITLE
Add `blocking_recv` method to `oneshot::Receiver`

### ISSUE THREAD

**Issue by gretchenfrage** [tokio-rs/tokio#4319]
**Is your feature request related to a problem? Please describe.**

I would like to be able to send a value into a oneshot, and receive it either in an async context or a blocking context, to create an API which supports in both blocking and async contexts.

**Describe the solution you'd like**

`mpsc::Receiver` and `mpsc::UnboundedReceiver` have `blocking_recv` methods. It would be nice to see an equivalent `blocking_recv` method added to `oneshot::Receiver`.

**Describe alternatives you've considered**

It would be interesting to instead simply expose the `crate::future::block_on` mechanism by which the existing `blocking_recv` methods are implemented, and have a concept of "this async function doesn't aaactually rely on tokio and thus can be used in a non-async context in a blocking way with that wrapper."

**Additional context**

It's for the [`winit-main`](https://gitlab.com/gretchenfrage/winit-main) crate if you're curious.

**Comment by Darksonn** [comment]
I'm fine with adding this, though note that `futures::executor::block_on` is a solution that works today.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by besok** [comment]
Apparently the issue should be closed

**Comment by Darksonn** [comment]
Thanks.
