### ISSUE TITLE
Unbounded MPSC does not free large amounts of memory that were created during back-pressure

### ISSUE THREAD

**Issue by semirix** [tokio-rs/tokio#4321]
**Version**
1.14

**Platform**
`Linux pop-os 5.13.0-7620-generic #20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC  x86_64 GNU/Linux`

**Description**
I have a process with a persistent MPSC channel and when it has encountered back-pressure, the memory consumption of the app goes up (expected). What happens though, is that once the back-pressure is gone, it does not deallocate the blocks that got allocated during the back-pressure window, resulting in continued very high memory usage.

I made this minimum example to demonstrate. This ran on a Ryzen 4800U with 16GB of RAM.

```rust
#[tokio::main]
async fn main() {
    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<[u8; 4096]>();
    let mut counter = 0;

    tokio::spawn(async move {
        for _ in 0..100000 {
            if let Err(error) = tx.send([0; 4096]) {
                println!("{}", error);
            }
        }

        loop {}
    });

    while let Some(_) = rx.recv().await {
        counter += 1;
        println!("{} of 100000", counter);
    }
}
```

It got to about 200-300MB of RAM usage and it never came down. It varies in amount but usually it's around that mark. I was wondering if it's possible for something kind of like `Vec<T>`'s `shrink_to_fit` to be added to the unbounded channel? In my code, there is always at least 1 sender passing in data, but generally there are periods where that data is quite small and sparse.

**Comment by Darksonn** [comment]
I applied the following change to Tokio:
```diff
diff --git a/tokio/src/sync/mpsc/list.rs b/tokio/src/sync/mpsc/list.rs
index e4eeb4541..ed97f8942 100644
--- a/tokio/src/sync/mpsc/list.rs
+++ b/tokio/src/sync/mpsc/list.rs
@@ -353,10 +353,15 @@ impl<T> Rx<T> {
             self.head = NonNull::dangling();
         }
 
+        let mut counter = 0;
+
         while let Some(block) = cur {
             cur = block.as_ref().load_next(Relaxed);
             drop(Box::from_raw(block.as_ptr()));
+            counter += 1;
         }
+
+        println!("{}", counter);
     }
 }
```
Then I ran the following test:
```Rust
#[tokio::main]
async fn main() {
    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<[u8; 4096]>();
    let mut counter = 0;

    tokio::spawn(async move {
        for _ in 0..100000 {
            if let Err(error) = tx.send([0; 4096]) {
                println!("{}", error);
            }
        }
    });

    while let Some(_) = rx.recv().await {
        counter += 1;
        println!("{} of 100000", counter);
    }
}
```
When it exited, it reported that the channel had 5 blocks left when the channel was dropped. That means that the total number of slots that the channel had allocated memory for is 32*5 = 160 messages.

I encourage you to try out jemalloc with a configuration that aggressively releases memory back to the OS like [this one](https://github.com/tokio-rs/tokio/issues/2479#issuecomment-623157381) and see what happens.

**Comment by semirix** [comment]
Just for my own benefit, why would using jemalloc change the behaviour? Isn't the block code responsible for when/how blocks get dropped? If the minimum example still has blocks left and that's observable, why would those blocks use more/less memory under a different allocator?

**Comment by sfackler** [comment]
Memory allocators do not immediately return all freed memory to the operating system.

**Comment by semirix** [comment]
> Memory allocators do not immediately return all freed memory to the operating system.

@sfackler If those blocks are still in use by the MPSC channel and haven't been dropped, shouldn't it be impossible for it to be deallocated? I thought the issue here is that the blocks aren't being dropped and thus aren't being deallocated by the system. It's possible I'm not understanding this fully.

**Comment by Tarang** [comment]
I don't know if gemalloc is a good way to fix this. Is there a way to drop anything at the end? It seems very counterintuitive and against purpose of using rust if there is no way to control it.

**Comment by Darksonn** [comment]
> If those blocks are still in use by the MPSC channel and haven't been dropped, shouldn't it be impossible for it to be deallocated?

Yes, if they really are in use by the MPSC channel, then using jemalloc wont make a difference. The reason I mention jemalloc is that according to the test I did, the MPSC channel is _not_ holding on to most of the blocks anymore, and they have already been deallocated.

**Comment by Darksonn** [comment]
Alternatively you might find this more convincing:
```Rust
use std::sync::atomic::{AtomicUsize, Ordering};
use std::alloc::{GlobalAlloc, System, Layout};
use std::time::Duration;

struct AllocCounter {
    count: AtomicUsize,
}

unsafe impl GlobalAlloc for AllocCounter {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        self.count.fetch_add(layout.size(), Ordering::Relaxed);
        System.alloc(layout)
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        self.count.fetch_sub(layout.size(), Ordering::Relaxed);
        System.dealloc(ptr, layout)
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        self.count.fetch_add(layout.size(), Ordering::Relaxed);
        System.alloc_zeroed(layout)
    }
}

#[global_allocator]
static A: AllocCounter = AllocCounter {
    count: AtomicUsize::new(0),
};

#[tokio::main]
async fn main() {
    std::thread::spawn(|| {
        loop {
            std::thread::sleep(Duration::from_secs(1));
            println!("Current memory: {}", A.count.load(Ordering::Relaxed));
        }
    });

    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<[u8; 4096]>();
    let mut counter = 0;

    tokio::spawn(async move {
        for _ in 0..100000 {
            if let Err(error) = tx.send([0; 4096]) {
                println!("{}", error);
            }
        }

        loop {}
    });

    while let Some(_) = rx.recv().await {
        counter += 1;
        println!("{} of 100000", counter);
    }
}
```
For me, this claims that the memory usage is 580 kB once the loop completes, far less than the 200 MB you were talking about.

**Comment by semirix** [comment]
Things keep getting weirder.

![image](https://user-images.githubusercontent.com/7454145/147040141-b6db0c1e-9131-4ba1-96a3-f0f39891d70a.png)

The system monitor is reporting something different than the allocator. I'm not really sure what to make of this. I left it running for a few minutes and I saw no change in the system monitor.

**Comment by Darksonn** [comment]
It's not particularly surprising to me. Every time someone has reported a potential memory leak to Tokio that they found by looking at their system monitor (as opposed to e.g. valgrind), it was not actually a memory leak. Every single time it has been because the memory allocator was not releasing the deallocated memory back to the OS so it could reuse it for future allocations, speeding up those future allocations.
