### ISSUE TITLE
Misleading documentation for Builder::max_frame_length. 

### ISSUE THREAD

**Issue by dvdsk** [tokio-rs/tokio#4340]
**Version**
`tokio-util current master (78e0f0b42a4f7a50f3986f576703e5a3cb473b79)`

**Platform**
```Linux ubuntu 5.11.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Nov 19 07:45:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux```

**Description**
The documentation of [max_frame_length](https://docs.rs/tokio-util/0.6.9/tokio_util/codec/length_delimited/struct.Builder.html#method.max_frame_length) has a misleading example. 

In the example it states the default value for frame length 8MB, this is correct (see: [source](https://github.com/tokio-rs/tokio/blob/78e0f0b42a4f7a50f3986f576703e5a3cb473b79/tokio-util/src/codec/length_delimited.rs#L655)). Then the example sets the value to 1024*8. Since `max_frame_length` is just a setter [source](https://github.com/tokio-rs/tokio/blob/78e0f0b42a4f7a50f3986f576703e5a3cb473b79/tokio-util/src/codec/length_delimited.rs#L775) the frame length is now 8KB. 

I inferred from this that the frame length is set in KB. I would suggest adjusting the example to set a value of 8 * 1024 * 1024 and mentioning it is the size in bytes.

I would be happy to pull request such a change, let me know.

**Comment by Darksonn** [comment]
You are welcome to submit such a PR.
