### ISSUE TITLE
Tests in `time_throttle.rs` and `stream_timeout.rs` are disabled

### ISSUE THREAD

**Issue by vlad20012** [tokio-rs/tokio#4341]
It looks like the tests in [`tokio-stream/tests/stream_timeout.rs`](https://github.com/tokio-rs/tokio/blob/78e0f0b42a4f7a50f3986f576703e5a3cb473b79/tokio-stream/tests/stream_timeout.rs) and [`tokio-stream/tests/time_throttle.rs`](https://github.com/tokio-rs/tokio/blob/78e0f0b42a4f7a50f3986f576703e5a3cb473b79/tokio-stream/tests/time_throttle.rs) files are always cfg-disabled because there is a `#![cfg(feature = "full")]` attribute in each file, but the crate `tokio-stream` [does not have](https://github.com/tokio-rs/tokio/blob/78e0f0b42a4f7a50f3986f576703e5a3cb473b79/tokio-stream/Cargo.toml#L19) a feature called `full`.

**Comment by Grubba27** [comment]
Hello there,  this is a good first issue ? seems like i only have to change 

```rust
#![cfg(feature = "full")]
```

for:
```rust
#![cfg(feature = "time")]
```

 right ? if there is something beside this ?

**Comment by Darksonn** [comment]
Yeah, that seems like it would fix it.

**Comment by Grubba27** [comment]
In stream_timeout if i use time or default it gives me errors on tests
other options are ok?:
```rust
net = ["tokio/net"]
io-util = ["tokio/io-util"]
fs = ["tokio/fs"]
sync = ["tokio/sync", "tokio-util"]
signal = ["tokio/signal"]
```

**Comment by Darksonn** [comment]
Pick a feature or combination of features that works. You can list several features like this:
```Rust
#![cfg(all(feature = "time", feature = "sync", feature = "io-util"))]
```

**Comment by Grubba27** [comment]
With multiple features all tests in local ran smoothly, adjusting PR and linking here

**Comment by Grubba27** [comment]
Thx btw, did not knew that could be done, multiple features at once in this manner

**Comment by Grubba27** [comment]
PR is in this [link](https://github.com/tokio-rs/tokio/pull/4441/files)
