### ISSUE TITLE
tokio-util: adapter that creates connected AsyncWrite (for input) and Stream (for output)

### ISSUE THREAD

**Issue by itamarst** [tokio-rs/tokio#4345]
**Is your feature request related to a problem? Please describe.**

I want to stream from S3 to the response in an Actix Web handler.

* The S3 client takes `AsyncWrite` as input: https://docs.rs/rust-s3/latest/s3/bucket/struct.Bucket.html#method.get_object_stream
* Actix Web wants a `Stream` to be passed to the response: https://docs.rs/actix-web/4.0.0-beta.15/actix_web/struct.HttpResponseBuilder.html#method.streaming

So I need an object that takes data via `AsyncWrite` and has a `Stream` as output.

Other people seem to have this requirement: https://users.rust-lang.org/t/asyncwrite-input-to-stream-output/59367

**Describe the solution you'd like**

```rust
let asyncwriter, stream = tokio_util::io::asyncwrite_to_stream();
```

And then writes to the one get output from the other; presumably there is some sort of  buffer in between (a channel?) to provide backpressure.

**Describe alternatives you've considered**

Right now I'm buffering to temporary file on disk. Next will investigate writing my own.

**Additional context**

Here's my code, approximately, with temporary file:

```rust
use actix_web::data;
use tempfile::tempfile;

#[get("/downloads/{download_key}")]
async fn download(
    download_key: web::Path<DownloadKey>,
    config: web::Data<Configuration>,
) -> Result<impl Responder, ApiError> {
    // Download to a temporary file:
    let mut async_file = tokio::fs::File::from_std(tempfile()?);
    let code = config
        .storage_bucket
        .get_object_stream(format!("/{}", download_key), &mut async_file)
        .await
        .map_err(|e| {
            error!(error = %e);
            ApiError::S3
        })?;
    if code == 404 {
        return Err(ApiError::NotFound);
    }
    async_file.flush().await?;
    async_file.seek(SeekFrom::Start(0)).await?;
    Ok(HttpResponse::Ok().streaming(tokio_util::io::ReaderStream::new(async_file)))
}
```

**Comment by Darksonn** [comment]
You can get this by combining a [`tokio::io::duplex`][1] with [`tokio_util::io::ReaderStream`][2].

[1]: https://docs.rs/tokio/latest/tokio/io/fn.duplex.html
[2]: https://docs.rs/tokio-util/latest/tokio_util/io/struct.ReaderStream.html

**Comment by itamarst** [comment]
Ah hah! Here's the code using that suggestion:

```rust
let (mut asyncwriter, asyncreader) = tokio::io::duplex(256 * 1024);
let streamreader = tokio_util::io::ReaderStream::new(asyncreader);
```

**Comment by itamarst** [comment]
Perhaps this is more of a documentation issue? As a beginner I could not have figured that out on my own; I know enough of this sort of thing to know what the shape should be, but not where to look.

**Comment by Darksonn** [comment]
I don't disagree, but where should we put this? One of the main challenges with stuff like this is putting it somewhere people will find it when they need it.

I already updated my response in the thread you linked.

**Comment by itamarst** [comment]
In the four-quadrants model of documentation (https://documentation.divio.com/) this would be a how-to, I think. "How to connect  AsyncRead/AsyncWrite/Sink/Stream" and then show all the combinatorical variants. So probably under https://tokio.rs/tokio/topics? As a companion to the sync topic. And maybe another on bridging `Read` and `Write`.

I also had to do "here's the `Stream` from Actix, turn it into a `AsyncRead`" for the upload side, and that was slightly tricky since I had to adapt error types from `PayloadError` to `std::io::Error`; eventually I figured out `Stream` has `map`:

```rust
async fn upload_report(
    payload: web::Payload,
    config: web::Data<Configuration>,
) -> Result<web::Json<DownloadKey>, ApiError> {
    let mut payload_asyncread =
        StreamReader::new(payload.map(|i| {
            i.map_err(|_| std::io::Error::new(std::io::ErrorKind::Other, "payload error"))
        }));
    // ...
    config
        .storage_bucket
        .put_object_stream(&mut payload_asyncread, format!("/{}", download_key))
        .await
        .map_err(|e| {
            error!(error = %e);
            ApiError::S3
        })?;
    info!(download_key = %download_key);

    Ok(web::Json(download_key))
}
```

**Comment by Darksonn** [comment]
Yeah, I suppose it makes sense if you combine all the conversions into a single post. I'll put it on my endless list of topics articles I should write.

**Comment by itamarst** [comment]
Thank you!
