### ISSUE TITLE
`pin-project-lite` pinned to a yanked version

### ISSUE THREAD

**Issue by ReagentX** [tokio-rs/tokio#4350]
The `pin-project-lite` dependency is pinned to a version that has been yanked:

- https://github.com/tokio-rs/tokio/blob/4b6bb1d9a790b0b81e56d4d852944a2a08b1f70d/tokio-util/Cargo.toml#L46
- https://lib.rs/crates/pin-project-lite/versions

This leads to the following warning when depending on Tokio:

```
warning: package `pin-project-lite v0.2.0` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
```

**Comment by sfackler** [comment]
`"0.2.0"` does not pin to that exact version - it supports any `0.2.x` version.

**Comment by ReagentX** [comment]
Is the warning `cargo` emits safe to ignore, then?

**Comment by sfackler** [comment]
Run `cargo update`.
