### ISSUE TITLE
`cargo doc` breaks for 2018-06-18 nightly

### ISSUE THREAD

**Issue by ErichDonGubler** [tokio-rs/tokio#437]
The crux of the issue seems to be `lib.rs:9`, where `[notified]` doesn't actually refer to anything in source. 

I've included a sample invocation below, but if you need any further information please let me know! Builds for [`uploads-im-client-rs`](https://github.com/erichdongubler/uploads-im-client-rs) are [breaking because I decided to include a `cargo doc --verbose` command](https://travis-ci.org/ErichDonGubler/uploads-im-client-rs/jobs/394331899). I would love to keep my CI more rigorous, but I can't with this issue!

<details>
<summary>Log output</summary>

```
~/…/tokio/tokio-executor master$ cargo +nightly-2018-06-18 doc
 Documenting futures v0.1.21
    Checking futures v0.1.21
warning: `[Debug]` cannot be resolved, ignoring it...
   |
   = note: #[warn(intra_doc_link_resolution_failure)] on by default
   = note: the link appears in this line:

            themselves through the [`Display`] and [`Debug`] traits, and may provide
                                                    ^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

 Documenting tokio-executor v0.1.2 (file:///C:/Users/egubler/workspace/personal/bug-reports/tokio/tokio-executor)
error: `[notified]` cannot be resolved, ignoring it...
 --> tokio-executor\src\lib.rs:9:27
  |
9 | //! whenever the task is [notified]. Notification happens when the internal
  |                           ^^^^^^^^ cannot be resolved, ignoring
  |
note: lint level defined here
 --> tokio-executor\src\lib.rs:33:54
  |
33| #![deny(missing_docs, missing_debug_implementations, warnings)]
  |                                                      ^^^^^^^^
  = note: #[deny(intra_doc_link_resolution_failure)] implied by #[deny(warnings)]
  = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: Could not document `tokio-executor`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name tokio_executor tokio-executor\src\lib.rs -o C:\Users\egubler\workspace\personal\bug-reports\tokio\target\doc -L dependency=C:\Users\egubler\workspace\personal\bug-reports\tokio\target\debug\deps --extern futures=C:\Users\egubler\workspace\personal\bug-reports\tokio\target\debug\deps\libfutures-2ecc8546a5859d7a.rmeta` (exit code: 101)
```
</details>

**Comment by carllerche** [comment]
My understanding is that `cargo doc` on nightly is under a lot of flux / bugs.

That said, there probably are also issues w/ the docs. I will happily accept PRs to fix broken links.

**Comment by kpp** [comment]
Depends on https://github.com/rust-lang-nursery/net2-rs/issues/76

cc @alexcrichton

**Comment by kpp** [comment]
Depends on https://github.com/crossbeam-rs/crossbeam-utils/pull/21

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/pull/450

**Comment by kpp** [comment]
Depends on https://github.com/carllerche/bytes/pull/218

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/pull/458

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/pull/471

**Comment by kpp** [comment]
Depends on https://github.com/rust-lang-nursery/rand/issues/582

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/issues/437

**Comment by ErichDonGubler** [comment]
Uh...isn't that last comment a circular dependency?

**Comment by kpp** [comment]
Oops. fixed

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/issues/556

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/issues/557

**Comment by kpp** [comment]
Depends on https://github.com/tokio-rs/tokio/pull/792
