### ISSUE TITLE
Add method to allow mutate task local `tokio::task::LocalKey`

### ISSUE THREAD

**Issue by unrealhoang** [tokio-rs/tokio#4375]
**Is your feature request related to a problem? Please describe.**
I want to use task local as a byte buffer to do serialization and compression, this requires the content of task local to be mutable.

**Describe the solution you'd like**
`LocalKey` should have method `with_mut` and `try_with_mut` that allow the inner value to be mutable. 
```
    pub fn try_with_mut<F, R>(&'static self, f: F) -> Result<R, AccessError>
    where
        F: FnOnce(&mut T) -> R,
    {
        self.inner.with(|v| {
            if let Some(val) = v.borrow_mut().as_ref() {
                Ok(f(val))
            } else {
                Err(AccessError { _private: () })
            }
        })
    }
```

**Describe alternatives you've considered**
To use inner `RefCell` to allow for interior mutability.

**Comment by Darksonn** [comment]
Unfortunately this is not possible because a mutable reference has to be unique, but you could call the `with_mut` method inside itself to get two mutable references. The intention is that you use a `Cell` or `RefCell` to do this.
