### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by Antiarchitect** [tokio-rs/tokio#4399]
**Version**

```
cargo tree | grep tokio
│   │   └── tokio v1.15.0
│   │       └── tokio-macros v1.7.0 (proc-macro)
│   │   └── tokio v1.15.0 (*)
├── tokio v1.15.0 (*)
├── tokio-retry v0.3.0
│   └── tokio v1.15.0 (*)
├── tokio-util v0.6.9
│   └── tokio v1.15.0 (*)
```

**Platform**

```
Linux warmachine 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**
Frankly, I don't actually know if this is related to tokio, I'm building MQTT <--> AMQP proxy based on `lapin` and `ntex-mqtt` crated which both use `tokio` as the runtime. I will do further investigation, but it seems the app leaks memory a bit (noticed in the first 30 minutes. I Will do longer tests afterward). Here is a Heaptrack screenshot that shows the place that bothers me. The amount of memory leaked here is rather the same I see in `ps RSS` diff:
https://i.imgur.com/LsuixZr.png

Any help or advice would be very appreciated!

**Comment by Darksonn** [comment]
There's not much I can say based on what you have posted here.

**Comment by Antiarchitect** [comment]
@Darksonn Is there any additional info I can provide?

**Comment by Darksonn** [comment]
Well, for example, if you can figure out which allocation is the culprit, that would be one way.

Another thing that's helpful is a graph with memory usage over time for a long duration of time.

**Comment by Antiarchitect** [comment]
The whole graph (with app start and terminate):
https://i.imgur.com/x37UqIj.png
Rising to plateau:
https://i.imgur.com/VLMArqp.png
And rising leakage: https://i.imgur.com/VLMArqp.png
plateau: (seems clear) https://i.imgur.com/nTRI0zh.png

Seems like the situation is normal. It stabilizes after a few minutes, do not why heaptrack count this as leakage

**Comment by Antiarchitect** [comment]
@Darksonn I will close the issue. If you can tell this is a real problem - please reopen. Long-running testing shows that these 1-5 MB are consumed only in first several minutes of app works
