### ISSUE TITLE
No spawn method is compatible with all executors

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#440]
By my count, there are 6 different ways to start an Executor, and give global functions to spawn a Future into the current Executor (not including functions that need a Handle or some other explicit reference to the Executor).  However, not all of the spawning methods work with all of the Executors, and the documentation doesn't make it clear which are compatible.  So I tested all 30 combinations, and found that no single Executor is compatible with all spawning functions, and no single spawning function is compatible with all Executors.  You can see the executive summary at https://docs.google.com/spreadsheets/d/1yszSLpbO8bicBCZOq9FGnPOnceOOTcIXt2XReqhU-pw/edit?usp=sharing .  My conclusions are:
* The `tokio_current_thread` crate has no compatibility with either the `tokio` or `tokio_executor` crates.  Don't mix and match them.
* `tokio::runtime::current_thread::Runtime::block_on` works with all spawners except the one in `tokio_current_thread`.
* Even ignoring the `tokio_current_thread` crate, there is no single spawner that works with all other Executors.  This is a big problem for middleware crates that want to spawn tasks, but don't control their own Runtimes.

Open problems are:
* What should a middleware crate do if it needs to spawn a Future, but doesn't know how its Runtime was created?
* The documentation needs some clarification.

**Comment by carllerche** [comment]
I agree that the documentation could use clarification.

The idea is roughly that individual executor crates (`tokio_current_thread`, `tokio_threadpool`) do not impose defaults as they are building blocks.

The runtime in `tokio` is the glue layer that brings all the components together.

From a library, if you want to spawn, you should not reference an executor crate. Instead:

a) Be generic over an executor and require the user to provide one
b) Default to using `DefaultExecutor` from tokio-executor.

Alternatively, you *could* just hardcode `DefaultExecutor::spawn(..)`.

Application devs should just use one of the runtimes that are preconfigured and shouldn't worry about the individual executor crates either.

Does that clarify things at all? The reality is that all of these patterns are still being discovered.

**Comment by asomers** [comment]
Yes, that helps.  `DefaultExecutor::spawn` is the best choice.  However, it doesn't work with `tokio::executor::current_thread::block_on_all`.  So are you saying that library and application developers need to agree that:
1) Library developers can assume that there will be a Runtime, so they can spawn stuff with `DefaultExecutor::Spawn`, and
2) Application developers will create some kind of `Runtime`, and not rely on the bare executors?

**Comment by carllerche** [comment]
Right... so `tokio::executor::current_thread` is deprecated (not pushed yet), but mostly because it was moved to another crate.

If you use the `current_thread` executor yourself, you are responsible for configuring where `DefaultExecutor::spawn` goes.

And yes, you are correct w/ your two points.

**Comment by asomers** [comment]
> If you use the current_thread executor yourself, you are responsible for configuring where DefaultExecutor::spawn goes.

And that would be done by `tokio_executor::with_default`?

**Comment by carllerche** [comment]
that is correct

**Comment by asomers** [comment]
Ok, that answers everything.

**Comment by carllerche** [comment]
How do you think the documentation should be updated?

**Comment by asomers** [comment]
Firstly, the proscription against applications using executors directly is already documented in the first paragraph of tokio-current-thread.  But I never read it because I started using tokio_core back before there was a Runtime.  However, I can't find the same warning anywhere in the API docs for tokio::executor.  The same warning should probably be repeated there.

The other problem is that tokio::executor::current_thread::spawn doesn't work with a multithreaded runtime, and its documentation isn't clear about that.  It says it will "always spawn on a CurrentThread executor" as if that were always possible.  It probably should say that it "requires that the default executor be a CurrentThread executor".  Even better would be to fix issue #446, but that would obviously take a lot more work.
