### ISSUE TITLE
It seems it is a bug in JoinHandle.abort()

### ISSUE THREAD

**Issue by uniconductive** [tokio-rs/tokio#4400]
**Version**
1.15

**Platform**
5.16.0-1-MANJARO x86_64 GNU/Linux 

**Description**
Unexpected results for JoinHandle.abort()

I tried this code:
```
#[tokio::main]
async fn main() {
    let h = tokio::spawn(async move {
        let hh = tokio::spawn(async move {
            for i in 1..=10 {
                tokio::time::sleep(std::time::Duration::from_secs(1)).await;
                println!("{}", i);
            }
            println!("loop finished");
        });
        hh.await;
    });
    println!("sleep(5)");
    tokio::time::sleep(std::time::Duration::from_secs(5)).await;
    println!("abort");
    h.abort();
    println!("abort done");
    println!("sleep(10)");
    tokio::time::sleep(std::time::Duration::from_secs(10)).await;
    println!("sleep(10) finished");
}
```

I expected to see this happen: 
output: 
> sleep(5)
> 1
> 2
> 3
> 4
> abort
> abort done
> sleep(10)
> sleep(10) finished

Instead, this happened: 
output: 
> sleep(5)
> 1
> 2
> 3
> 4
> abort
> abort done
> sleep(10)
> 5
> 6
> 7
> 8
> 9
> 10
> loop finished
> sleep(10) finished

**Comment by sfackler** [comment]
Aborting the `h` task doesn't abort the `hh` task.
