### ISSUE TITLE
BufReader.take(n).read_to_end(buf) reads nothing

### ISSUE THREAD

**Issue by hbprotoss** [tokio-rs/tokio#4402]
**Version**
List the versions of all `tokio` crates you are using. The easiest way to get
this information is using `cargo tree` subcommand:

└── tokio v1.15.0
    └── tokio-macros v1.7.0 (proc-macro)

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

macOS

**Description**
Enter your issue details here.
One way to structure the description:

I'm parsing redis protocol from TcpStream via BufReader, trying to read exact n bytes from underlying stream, but BufReader.take(n).read_to_end(but) reads nothing.

I tried this code:

```
pub async fn read_n(&mut self, n: u64, buf: &mut Vec<u8>) -> Result<usize, Error> {
        self.reader.get_mut().take(n).read_to_end(buf).await
    }
```

I expected to see this happen:

`buf` is filled with n bytes from stream

Instead, this happened: 

before and after the call, `buf` is still empty

**Comment by Darksonn** [comment]
What does the call return?

**Comment by hbprotoss** [comment]
> What does the call return?

returns 0

I've traced to `tokio-1.15.0/src/io/async_read.rs`:67

```
Pin::new(&mut **self).poll_read(cx, buf)
```

It seems the function `poll_read ` does not return, and jump to asm code

**Comment by Darksonn** [comment]
Sounds like your `self.reader` object has reached EOF then.

**Comment by hbprotoss** [comment]
I'm sure it has retained bytes.

client sent `*2\r\n$7\r\nCOMMAND\r\n`, the code before consumes `*2\r\n$7\r\n`

**Comment by hbprotoss** [comment]
How can I find call stack from underlying C++ perhaps?

**Comment by hbprotoss** [comment]
I replace the call to this `read_n` with `read_until`, reader reads the left `COMMAND\r\n` into buffer

**Comment by hbprotoss** [comment]
success:

```
let mut b = [0 as u8; 7];
self.reader.read_exact(&mut b).await?;
```

fail:

```
let mut b = [0 as u8; 7];
self.reader.get_mut().read_exact(&mut b).await?;
```

**Comment by Darksonn** [comment]
Oh, yeah, you definitely shouldn't be calling `get_mut` on the `BufReader`. Use a mutable reference to the `BufReader` instead.

**Comment by hbprotoss** [comment]
after modified to `(&mut self.reader).take(n).read_to_end(buf).await`, all works well

**Comment by hbprotoss** [comment]
btw, `get_mut` is too confusing

**Comment by Darksonn** [comment]
The documentation _does_ say this:

> It is inadvisable to directly read from the underlying reader.

I'm going to close this as there's no bug in Tokio here.
