### ISSUE TITLE
Why doesn't tokio::process::ChildStdin implements IntoRawFd

### ISSUE THREAD

**Issue by NobodyXu** [tokio-rs/tokio#4403]
Since `tokio::process::ChildStdin` already implements `AsRawFd`, it seems to be only natural  that it also implements `IntoRawFd` like `std::process::ChildStdin`.

What is the reason for it to not implement `IntoRawFd`?

**Comment by Darksonn** [comment]
Well, the conversion is fallible, which the trait doesn't support.

**Comment by NobodyXu** [comment]
Is it because the conversion into `RawFd` requires the `O_NONBLOCKING` flags to be removed?

**Comment by Darksonn** [comment]
Yes, but also because its registration with epoll needs to be removed.

**Comment by NobodyXu** [comment]
OK, I got it.

Is it possible to have some alternative API that can return the fd along with its ownership?

I personally is OK with the fd being `O_NONBLOCKING`.

**Comment by Darksonn** [comment]
Sure, we could have an `into_std` function.

**Comment by NobodyXu** [comment]
> Sure, we could have an `into_std` function.

I don’t think we can support “into_std” since “ChildStdin” doesn’t support FromRawFd.

**Comment by Darksonn** [comment]
Ok, I guess that's why we don't have it already. I'm sure we could find some other alternative.

**Comment by NobodyXu** [comment]
Maybe something like `fn to_owned_fd(self) -> Result<io_lifetimes::OwnedFd, io::Error>` where [`io_lifetimes::OwnedFd`](https://docs.rs/io-lifetimes/0.4.4/io_lifetimes/struct.OwnedFd.html) is implementation of the unstable `std::os::unix::io::OwnedFd`?

**Comment by Darksonn** [comment]
We would probably use the same return type as the `IntoRawFd` trait. We are not going to add a dependency on `io_lifetimes` for this, nor are we going to define a similar type in Tokio just for the stdio types.

**Comment by NobodyXu** [comment]
I agree that introduce a new dependency is too much and using “RawFd” is fair enough.

I think having a new unix-only trait for this is the way to go, since “ChildStdin”, “ChildStdout” and “ChildStderr” will all have this method implemented.
