### ISSUE TITLE
Ability to know the used capacity of a broadcast channel

### ISSUE THREAD

**Issue by alex88** [tokio-rs/tokio#4405]
It would be nice, on the receiver side, to be able to see the used capacity of the bounded channel, to make different decisions in the case the receiver is struggling to keep up with the production (skipping, grouping some values etc).

**Comment by Darksonn** [comment]
When people talk about "the bounded channel", they generally refer to `tokio::sync::mpsc::bounded`, but in #4404 you asked about the broadcast channel. Which is it?

And if you mean the broadcast channel, then it is not necessarily obvious what it should return. Different receivers may be different amounts of items behind.

**Comment by alex88** [comment]
Sorry I'm referring about the broadcast bounded channel, in that case I would imagine each receiver would see its own queue, because like you said, it would be different for each receiver. I imagine it's also more relevant to the receiver to know how much it's behind to know what to do.

**Comment by Darksonn** [comment]
So you are asking for a method on the receiver, and not the sender? I suppose that could make sense.

**Comment by alex88** [comment]
Yeah sorry I did mention the receiver but it wasn't clear, I'll add to the initial comment.
