### ISSUE TITLE
Mark tokio futures as UnwindSafe

### ISSUE THREAD

**Issue by Masoman3** [tokio-rs/tokio#4414]
**Version**
tokio = 1.15.0
tokio-macros = 1.7.0
tokio-util = 1.15.0

**Platform**
Linux  5.3.18-59.37-default 1 SMP  x86_64 GNU/Linux

**Description**

Some tokio futures are not marked as unwind safe, making catching panics unwieldy and uncertain. [I spoke with Alice ](https://users.rust-lang.org/t/tokio-catch-unwind/70585) who suggested I make a bug report about this.

I tried this code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=77e8b4432bd28f50080cbae9eb26b8ae

And the compiler reports that various futures produced (particularly by the tokio::fs module) are not UnwindSafe.

**Comment by Hodkinson** [comment]
I can take a look at this

**Comment by Masoman3** [comment]
Yep! Thanks everyone!
