### ISSUE TITLE
tokio 1.16.1 doesn't compile for arm32

### ISSUE THREAD

**Issue by asonix** [tokio-rs/tokio#4452]
**Description**
On armv7-unknown-linux-musleabihf, tokio uses it's own AtomicU64 type based on a Mutex. however, there's no `fetch_add` method on this type, so this line in the runtime metrics does not compile: https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/metrics/scheduler.rs#L25

**Comment by Darksonn** [comment]
Thanks.
