### ISSUE TITLE
Feature request: Executor::spawn_local

### ISSUE THREAD

**Issue by asomers** [tokio-rs/tokio#446]
Some applications want to use a thread pool-based Runtime, but still must occasionally spawn non-`Send` Futures.  Currently it's not possible to do that.  Such an application would have no choice but to use the `tokio::runtime::current_thread::Runtime` Runtime and `tokio::executor::current_thread::spawn`.  It would be great if every Executor had a `spawn_local` method that could spawn non-`Send` Futures, which would be bound to the current Reactor.  Applications include:
* Reactor-local data structures could use `Rc` and `RefCell`, which are faster than `Arc` and `RwLock`
* Seastar-style applications that carefully segregate data between Reactors, to minimize cache conflicts
* RCU

**Comment by carllerche** [comment]
I'm actually thinking of adding a `TypedExecutor` trait, which would roughly be the same as [this](https://docs.rs/futures/0.1.18/futures/future/trait.Executor.html).

This trait would allow more advanced executor constraints.

**Comment by asomers** [comment]
I'm a little unclear about your proposal.  Are you suggesting that some Runtime implementations (or Handles, or whatever) would implemented `TypedExecutor`, which has a non-`Send` `execute` method?  That sounds like it would work.  What does the "Typed" in `TypedExecutor` refer to?

**Comment by carllerche** [comment]
The trait would be:

```rust
pub trait TypedExecutor<F: Future<Item = (), Error = ()>> {
    fn execute(&self, future: F) -> Result<(), SpawnError>;

   fn status(&self) -> Result<(), SpawnError>;
}
```

The concurrent runtime would have a blanket impl:

```
impl<T: Future<Item = (), Error = ()> + Send> TypedExecutor<T> for Runtime { ... }
```

The `current_thread` runtime would have:


```
impl<T: Future<Item = (), Error = ()>> TypedExecutor<T> for Runtime { ... }
```

Then, your code would be generic over the executor:

```rust
fn my_fn<E: TypedExecutor<MyTask>>(executor: E) { }
```

**Comment by carllerche** [comment]
I'm going to close this in favor of #625 and try to redirect the discussion towards a solution. If you feel that this is incorrect, let me open and I will reopen this one.
