### ISSUE TITLE
Is WaitForCancellationFuture cancel safe?

### ISSUE THREAD

**Issue by NobodyXu** [tokio-rs/tokio#4464]
There is no documentation on whether [`WaitForCancellationFuture`] is cancel safe and reading the implementation of `Future` for it seems like that it is cancel safe.

[`WaitForCancellationFuture`]: https://docs.rs/tokio-util/0.6.9/tokio_util/sync/struct.WaitForCancellationFuture.html#

**Comment by Darksonn** [comment]
Yes, it's cancel safe.

**Comment by NobodyXu** [comment]
Thanks for the swift reply!
