### ISSUE TITLE
Documentation of tokio-codec has parameters vice-versa

### ISSUE THREAD

**Issue by mkpankov** [tokio-rs/tokio#447]
Documentation at https://docs.rs/tokio-codec/0.1.0/tokio_codec/struct.Framed.html#method.new says `AsyncRead + AsyncWrite` is first, and `codec` is second. However, when I tried it, it only works this way:

```rust
let framed = tokio_codec::Decoder::framed(tokio_codec::BytesCodec::new(), serial_port);
```

How come? I thought it would be impossible for autogenerated docs to mismatch the actual signature.

**Comment by kpp** [comment]
Well, that is because you mixed up docs for `Framed::new` and tried to use [Decoder::framed](https://docs.rs/tokio-codec/0.1.0/tokio_codec/trait.Decoder.html#method.framed) instead.

**Comment by mkpankov** [comment]
All work and no play make @mkpankov a dull boy.

Thanks.
