### ISSUE TITLE
comment correction about JOIN_WAKER

### ISSUE THREAD

**Issue by hidva** [tokio-rs/tokio#4506]
https://github.com/tokio-rs/tokio/blob/8758965206d3c23c07ded0518d6c7398043ef227/tokio/src/runtime/task/mod.rs#L76

I think this should be modified as follows:

>  If JOIN_WAKER and COMPLETE are both one, then the thread that set COMPLETE to one has *shared* access to the join handle waker.

Because `Harness::complete()` and `can_read_output()` may be called concurrently, this means that `trailer().wake_join()` and `trailer.will_wake(waker)` may be called concurrently, which is why we use `waker.wake_by_ref()` instead of `waker.wake()` in `Trailer::wake_join()`.

**Comment by Darksonn** [comment]
This was fixed in #5217.
