### ISSUE TITLE
io: Refactor out usage of `Weak` in the io handle

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#4509]
Remove the use of `Weak` in the I/O Driver handle similar to how the timer does it. This will allow the `IoHandle` to store `Arc<Inner>` rather than require `Weak::upgrade` to access the inner timer.

The reason for `Weak` was to avoid cycles caused by wakers stored in the driver pointing to the runtime which points back to the driver. The cycle can be broken by making sure nobody can register a new io resources on (shutdown?) and by emptying the driver.

**Comment by hidva** [comment]
Hi, everyone, I have communicated with Lucio and I will try to solve this problem this week.
