### ISSUE TITLE
try_io() of UDPSocket doesn't work on Windows

### ISSUE THREAD

**Issue by masa-koz** [tokio-rs/tokio#4510]
**Version**
└── tokio v1.17.0
    └── tokio-macros v1.7.0 (proc-macro)

**Platform**
Windows 10 64bit

**Description**
I'm trying to use try_io() of UDPSocket for using WSARecvMsg() with tokio. But the following code doesn't work properly on Windows.
On Linux, it works as expected.

I tried this code:

```rust
use std::time::Duration;

#[cfg(target_family = "unix")]
use std::os::unix::io::AsRawFd;
#[cfg(target_family = "windows")]
use std::os::windows::prelude::AsRawSocket;

#[tokio::main]
async fn main() {
    let task_recv = tokio::spawn(async move {
        let udp = tokio::net::UdpSocket::bind("127.0.0.1:3456").await.unwrap();
        let mut buffer = vec![0; 1500];

        loop {
            let _ = udp.readable().await;
            let res = udp.try_io(tokio::io::Interest::READABLE, || {
                let res = unsafe {
                    #[cfg(target_family = "unix")]
                    let sock = udp.as_raw_fd();
                    #[cfg(target_family = "unix")]
                    let buf = buffer.as_mut_ptr() as *mut libc::c_void;
                    #[cfg(target_family = "unix")]
                    let buf_len = buffer.len();
                    
                    #[cfg(target_family = "windows")]
                    let sock =  udp.as_raw_socket() as usize;
                    #[cfg(target_family = "windows")]
                    let buf = buffer.as_mut_ptr() as *mut i8;
                    #[cfg(target_family = "windows")]
                    let buf_len = buffer.len() as i32;
        

                    libc::recvfrom(
                        sock,
                        buf,
                        buf_len,
                        0,
                        std::ptr::null_mut(),
                        std::ptr::null_mut()
                    )
                };
                if res < 0 {
                    Err(std::io::Error::last_os_error())
                } else {
                    Ok(res as usize)
                }
            });
            println!("res: {:?}", res);
        }
    });
    let task_send = tokio::spawn(async move {
        let udp = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
        loop {
            udp.send_to(&[0; 10], "127.0.0.1:3456")
                .await
                .expect("couldn't send data");
            tokio::time::sleep(Duration::from_secs(1)).await;
        }
    });

    let _ = tokio::join!(task_recv, task_send);
}
````

I expected to see this happen: 
```
res: Ok(10)
res: Err(Kind(WouldBlock))
res: Ok(10)
res: Err(Kind(WouldBlock))
res: Ok(10)
res: Err(Kind(WouldBlock))
res: Ok(10)
res: Err(Kind(WouldBlock))
^C⏎
```

Instead, this happened:
```
res: Ok(10)
res: Err(Kind(WouldBlock))
error: process didn't exit successfully: `target\debug\check-try_io.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```
It seems that readable() never returns even though many udp packets should arrive.

**Comment by Noah-Kennedy** [comment]
@masa-koz did this previously work on 1.16.1?

**Comment by masa-koz** [comment]
@Noah-Kennedy I've just tried this on 1.16.1, but it does'n work, too.
On Linux (5.10.60.1-microsoft-standard-WSL2) both versions work.

**Comment by masa-koz** [comment]
I find that I should call libc::recvfrom() in do_io() on Windows. Now, I'm suggesting to add do_io() in mio::net::UDPSocket.

https://github.com/tokio-rs/mio/issues/1550

**Comment by Noah-Kennedy** [comment]
@masa-koz so that fixed your issue?

**Comment by masa-koz** [comment]
@Noah-Kennedy Yes. my test code works expectedly after I change try_io as below.

    pub fn try_io<R>(
        &self,
        interest: Interest,
        f: impl FnOnce() -> io::Result<R>,
    ) -> io::Result<R> {
        self.io.registration().try_io(interest, || self.io.do_io(f))
    }

**Comment by Noah-Kennedy** [comment]
@masa-koz can we close this again or is there something here that you think is actionable in tokio?

**Comment by masa-koz** [comment]
I don't mind closing this now. If there's any progress in mio, I would like to reopen this.

**Comment by masa-koz** [comment]
Since mio 0.8.1, there are try_io methods on TCPStream, UDPSocket, UnixStream, and UnixDatagram. So, try_io methods on tokio should call these methods internally, I think. If acceptable, I will create PR.

https://github.com/masa-koz/tokio/commit/1ed65a6af84dbf3d35c86967767ab8b76a252116

**Comment by Darksonn** [comment]
Yes, please open a PR for that.
