### ISSUE TITLE
LocalPool runtime should allow configuration with io-uring

### ISSUE THREAD

**Issue by jkelleyrtp** [tokio-rs/tokio#4546]
**Is your feature request related to a problem? Please describe.**

The new local-pool is a very welcome addition! 

However, the runtime is configured to use the single-threaded runtime exclusively.

It would be very useful to allow this runtime to be io-uring compatible - especially since TCP/UDP support just landed in io-uring.

https://docs.rs/tokio-util/latest/src/tokio_util/task/spawn_pinned.rs.html#244-247

I don't know exactly how this would be enabled, but maybe an optional method with a runtime builder argument? Or a feature flag?

**Comment by Darksonn** [comment]
It would certainly have to involve some sort of feature flag. The main issue is that tokio-uring is likely to have more frequent breaking changes than tokio-util, but we can't upgrade the version that tokio-util uses without a breaking change.

**Comment by Noah-Kennedy** [comment]
I would agree with @Darksonn here. `tokio-uring` is quite new and is not unlikely to see breaking changes to its API as it grows.
