### ISSUE TITLE
StreamReader.into_inner should return its held chunk

### ISSUE THREAD

**Issue by jgraettinger** [tokio-rs/tokio#4552]
**Is your feature request related to a problem? Please describe.**

We have a proxying use case where we want to AysncRead some stuff from a StreamReader, and then unwrap the StreamReader to forward along the underlying Stream<Byte>. This is _almost_ easy to do, as StreamReader helpfully provides an [into_inner](https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/io/stream_reader.rs#L118-L123) that returns the underlying stream.

But there's a catch. The StreamReader also has an inner `chunk` of received but unread Bytes, and `into_inner` drops this chunk. To correctly forward the stream remainder, one needs to chain this chunk (as a stream) as a prefix followed by the inner stream.
It doesn't seem like the current API offers a way to do this.

**Describe the solution you'd like**
I _think_ the right course of action is to have `into_inner` return a held `chunk`, if any, along with the inner stream.
Likely I'm missing something, as I was surprised it wasn't the current behavior already.

**Describe alternatives you've considered**
Any other API which exposes the buffered chunk would be sufficient. I'm not seeing a current way to get at it though.

**Additional context**
If the proposed solution is appropriate, I'm happy to work up a PR.
Unsure if there are API stability guarantees which would require that it be a separate method.

**Comment by Darksonn** [comment]
I'm ok with adding a method that exposes the buffer in some way.
