### ISSUE TITLE
add Condvar

### ISSUE THREAD

**Issue by zhuxiujia** [tokio-rs/tokio#4557]
Condvar .wait()  must be   for example:
```
Condvar.wait().await()
```
Does Condvar currently using ``` std::sync::Condvar``` will be  blocking tokio threads?
maybe tokio should add an Condvar ?

**Comment by Darksonn** [comment]
You cannot use `std::sync::Condvar` inside Tokio. Unfortunately, condvars are tricky to implement properly in async. I'm going to close this as a duplicate of #3892.
