### ISSUE TITLE
ToSocketAddrs cannot convert to tokio::net::unix::SocketAddr

### ISSUE THREAD

**Issue by huguesBouvier** [tokio-rs/tokio#4561]
Issue with Tokio 1.17

I am trying to create an object to mock a call from UDS: 
pub struct UdsConnectInfo {
    pub peer_addr: Option<Arc<tokio::net::unix::SocketAddr>>,
    pub peer_cred: Option<tokio::net::unix::UCred>,
}

But I am having issues when trying to create "tokio::net::unix::SocketAddr"
I tried "127.0.0.1:443".to_socker_addr().unwrap() but it works only for std.

I tried to be a bit more creative and did:
![image](https://user-images.githubusercontent.com/33438817/157786220-da45cbcc-d9c7-4793-87a5-51a1ee79bec8.png)
But the object I am getting is std! Even if the listener of tokio type.

I am getting crazy trying to mock that UDS call. Is there a way to get a SocketAddr object? 
Then looking at the trait https://docs.rs/tokio/0.2.4/tokio/net/trait.ToSocketAddrs.html
I tried:
![image](https://user-images.githubusercontent.com/33438817/157787124-ea368d15-8505-4820-87b4-6c61051d1b62.png)
But it is still not letting me convert.
![image](https://user-images.githubusercontent.com/33438817/157787375-97a2caf7-2364-46c9-80b3-6e94673752e1.png)

Lastly I tried the full manual option:
![image](https://user-images.githubusercontent.com/33438817/157788494-711c8b63-8aae-4005-9bde-c0b04859631a.png)

**Comment by Noah-Kennedy** [comment]
You mentioned you are trying to use unix domain sockets. The "address" used by those is a file path, not an IP & port tuple. UDS has nothing to do with `ToSocketAddrs` or `std::net::SocketAddr`.

`tokio::net::unix::SocketAddr` is completely different from `std::net::SocketAddr`; one is a wrapper around a path and one is an IP & port tuple.
