### ISSUE TITLE
Convert TcpListenerStream to TcpStream

### ISSUE THREAD

**Issue by Ilqjx** [tokio-rs/tokio#4573]
Hi. How to realize the mutual conversion between `tokio_stream::wrappers::TcpListenerStream` and `tokio::net::TcpStream`?

**Comment by Darksonn** [comment]
A `TcpListenerStream` is convertible to an `TcpListener` with the `into_inner` method. You cannot convert it into a `TcpStream` because that's a completely different thing. That said, the `next` method on a `TcpListenerStream` will return a `TcpStream` when someone connects.

**Comment by Ilqjx** [comment]
Ok. Thanks for your reply.
