### ISSUE TITLE
Expose the length_field_len field in LengthDelimitedCodec

### ISSUE THREAD

**Issue by ljedrz** [tokio-rs/tokio#4574]
I'd like to be able to obtain the value of `length_field_len` from the `LengthDelimitedCodec` (once it's been built) in order to correctly register the number of bytes read from the network. I'm using a `FramedRead<OwnedReadHalf, LengthDelimitedCodec>` and calling `next()` on it, but I'm unable to obtain the actual length of the received bytes, only the length of the payload.

I'd like the `length_field_len` field to be accessible like [max_frame_length](https://docs.rs/tokio-util/latest/tokio_util/codec/length_delimited/struct.LengthDelimitedCodec.html#method.max_frame_length). Alternatively, something like `num_skipped` would work as well.

I know that `num_skip(0)` could be used to preserve the header, but I would prefer not to have to process it again just to know how many bytes had to be skipped.

**Comment by ljedrz** [comment]
In the meantime I was able to implement a workaround using a wrapper `Decoder` that counts all the bytes read by the inner codec in tandem with `Framed::map_decoder`.

**Comment by Darksonn** [comment]
If we added something like this, then we should probably add getters for all of the fields. However, it seems a bit overkill to me.
