### ISSUE TITLE
tokio-stream: Expose Timeout

### ISSUE THREAD

**Issue by madadam** [tokio-rs/tokio#4599]
I noticed the `Timeout` struct which is returned from `StreamExt::timeout` is not public. In my use case I want to create a struct which contains this `Timeout` as one of its fields but this is currently impossible.  Is there a reason this type is not exposed? If not, then I'd be happy to contribute a PR exposing it.

**Comment by Darksonn** [comment]
Probably not. There's probably already an issue about this.

**Comment by madadam** [comment]
> There's probably already an issue about this

I didn't find one, but maybe I wasn't looking hard enough. Anyway, here is the PR: https://github.com/tokio-rs/tokio/pull/4601.
