### ISSUE TITLE
Add try_read_buf to net::windows::named_pipe::NamedPipeClient

### ISSUE THREAD

**Issue by cptpiepmatz** [tokio-rs/tokio#4602]
**Is your feature request related to a problem? Please describe.**
The [`net::TcpStream`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html) does have a [`try_read_buf`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.try_read_buf) method that takes a [`bytes::buf::BufMut`](https://docs.rs/bytes/1.1.0/bytes/buf/trait.BufMut.html) to read data in.
The [`net::windows::named_pipe::NamedPipeClient`](https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.NamedPipeClient.html) is missing such method.

**Describe the solution you'd like**
A `try_read_buf` method with the same signature as the `TcpStream`.

**Describe alternatives you've considered**
Alternatively the [`read_buf`](https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html#method.read_buf) from the [`io::AsyncReadExt`](https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html) trait may be used, that one is async, while `try_read_buf` usually isn't.

**Additional context**
@Darksonn [asked me to submit this issue.](https://discord.com/channels/500028886025895936/500336333500448798/961341729888415857)

**Comment by Darksonn** [comment]
Adding this method should be relatively easy. It should be identical to the one on `TcpStream`.

**Comment by acalhoon** [comment]
I'm not a contributor yet but am willing to look into this

**Comment by Darksonn** [comment]
@acalhoon Go ahead and submit a PR!
