### ISSUE TITLE
bottleneck when spawning a task and immediately awaiting its result

### ISSUE THREAD

**Issue by jhgg** [tokio-rs/tokio#4606]
**Version**

```
└── tokio v1.17.0
    └── tokio-macros v1.7.0 (proc-macro)
```

**Platform**
```
Linux jake-dev-vm 5.4.0-1054-gke #57-Ubuntu SMP Fri Oct 1 03:16:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**
The following code is unable to fully saturate system resources. On a 60 core VM (for my tests, I am using a GCP [c2-standard-60](https://cloud.google.com/compute/docs/compute-optimized-machines#c2_machine_types) instance), the following program does not fully utilize system resources:

```rust
#[tokio::main]
async fn main() {
    let mut jh = vec![];
    for _ in 0..60 {
        jh.push(tokio::task::spawn(async move {
            loop {
                tokio::task::spawn(async move {}).await.ok();
            }
        }))
    }

    for x in jh {
        x.await.ok();
    }
}
```

When running this program, we can see that tokio is indeed using 60 worker threads, however each thread is only using ~12% CPU. See this screenshot of htop:

![image](https://user-images.githubusercontent.com/5489149/162355832-091d4d5e-c905-425d-939c-2c2a333a6b2b.png)

You can modify this code to make it not infinitely loop to get a rough idea of performance. Having the inner loop run 100,000 times takes roughly:

```
❯ time cargo run --release
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rust-playground`
cargo run --release  60.42s user 90.18s system 709% cpu 21.227 total
```

However, if I manually spawn a runtime per core, then the system resources are able to be fully utilized:

```rust
fn main() {
    let mut jh = vec![];
    for _ in 0..60 {
        jh.push(std::thread::spawn(|| {
            let rt = tokio::runtime::Builder::new_current_thread()
                .build()
                .unwrap();

            rt.block_on(async move {
                loop {
                    tokio::task::spawn(async move {}).await.ok();
                }
            })
        }));
    }

    for x in jh {
        x.join().unwrap();
    }
}
```

for comparison: 

![image](https://user-images.githubusercontent.com/5489149/162354824-d2d4c008-945f-42a8-99bc-c4cec23ba57a.png)

And when timing this code (the inner loop doing iterations 1,000,000 (so 10x more work per loop compared to the example above) takes:

```
❯ time cargo run --release
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rust-playground`
cargo run --release  19.96s user 0.05s system 3428% cpu 0.583 total
```

For the first example, the program actually appears to execute *faster* when the system is under more load as well... for example, if I spawn 60 threads that do `loop { spin_loop(); }` then the time the program completes in is... 

```
time cargo run --release
   Compiling rust-playground v0.1.0 (/home/discord/code/rust-playground)
    Finished release [optimized] target(s) in 0.87s
     Running `target/release/rust-playground`
cargo run --release  671.53s user 2.70s system 5198% cpu 12.969 total
```

Much less time being spent in system as well, and much less time overall. Lots more time spent in user though of course, because we're busy looping... 

---

### An additional observation:

When I reduce this to a single task doing the await loop, then it is much faster, but *only* when I run the code inside of a `spawn`

For example:

```rust
#[tokio::main]
async fn main() {
    for _ in 0..100000 {
        tokio::task::spawn(async move {}).await.ok();
    }
}
```

This takes:

```
❯ time cargo run --release
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rust-playground`
cargo run --release  0.96s user 2.13s system 173% cpu 1.780 total
```

But, when I do:

```rust
#[tokio::main]
async fn main() {
    tokio::task::spawn(async move {
        // NOTE: I added 2 0's to the end, so 100x more work being done:
        for _ in 0..10000000 {
            tokio::task::spawn(async move {}).await.ok();
        }
    })
    .await
    .ok();
}

```

This takes:

```
❯ time cargo run --release
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/rust-playground`
cargo run --release  2.93s user 0.38s system 119% cpu 2.770 total
```

**Comment by Darksonn** [comment]
This is probably because the tasks doing the spawning aren't able to get distributed evenly across the threads. My guess is that the threads with the spawning tasks keep overflowing tasks into the global queue, which the other threads check before trying to work steal, so they don't actually work steal the tasks doing the spawning.

As for the additional observation, that is known. The main thread isn't a worker thread but a `block_on` call, so any tasks you spawn there always have to get transferred to another thread before it can run, which is more expensive than just running them on the same thread as the spawner.

**Comment by Noah-Kennedy** [comment]
This is interesting, but when is this actually an issue? If we can make this faster that's great, but I have trouble imagining any real world situations where this is actually a bottleneck.

**Comment by jhgg** [comment]
> This is interesting, but when is this actually an issue? If we can make this faster that's great, but I have trouble imagining any real world situations where this is actually a bottleneck.

We hit this unexpected issue during development. It was not this exact code that caused it, this is just a minimization.

**Comment by Darksonn** [comment]
I'm going to close this issue. We will continue to make performance improvements to Tokio, but we probably wont make changes that focus on this particular example.
