### ISSUE TITLE
Add `UdpSocket::peer_addr()`

### ISSUE THREAD

**Issue by teenjuna** [tokio-rs/tokio#4609]
**Is your feature request related to a problem? Please describe.**

`UdpSocket` from `std` has this method, but the `UdpSocket` from the `tokio` does not.

**Describe alternatives you've considered**

One can carry `UdpSocket` with the `IpAddr` used for connection to the peer, but it's not convenient.

**Comment by PoorlyDefinedBehaviour** [comment]
I'll take this one :smile:
