### ISSUE TITLE
No way to create UnixListener without a filesystem path in tokio_uds

### ISSUE THREAD

**Issue by LegNeato** [tokio-rs/tokio#461]
All the `UnixListener` examples in `tokio_uds` use a filesystem tmp path. There doesn't appear to be a way to go from a `UnixStream` created with `UnixStream::pair()` (which doesn't use a path and only has a `RawFd`) to a `UnixListener`.  Thus, there is no way to get a `futures::Stream` from a `UnixStream` created with `UnixStream::Pair()`.

**Comment by LegNeato** [comment]
Apologies for the noise, I see it implements `FromRawFd` which will work.

**Comment by carllerche** [comment]
Should `UnixStream::pair()` be added to Tokio?

**Comment by LegNeato** [comment]
@carllerche It already exists in `tokio_uds`: https://docs.rs/tokio-uds/0.2.0/tokio_uds/struct.UnixStream.html#method.pair. The issue is it was unclear to go from a `UnixStream` created with `pair` to a `UnixListener`.  It turns out with some convolutions you can:

```rust
use std::os::unix::io::{FromRawFd, AsRawFd};
use std::os::unix::net;
use tokio_core::reactor::Core;
use tokio_uds;
use futures::Stream;

let core = Core::new()?;
let (receiver, sender) = tokio_uds::UnixStream::pair()?;
let listener = net::UnixListener::from_raw_fd(receiver.as_raw_fd());
let listener = tokio_uds::UnixListener::from_std(listener, &core.handle().new_tokio_handle().clone())?;
```

**Comment by carllerche** [comment]
Is that a common thing to do?
