### ISSUE TITLE
Notify loses notifications

### ISSUE THREAD

**Issue by jakajancar** [tokio-rs/tokio#4618]
**Version**
1.13.0

**Platform**
Darwin Jakas-MacBook-Pro-2.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

**Description**
Notify loses notifications if `Notified` is dropped.

```
use tokio::sync::Notify;

let notify = Notify::new();

// First listener polls once
let notified1 = notify.notified();
pin!(notified1);
assert!(poll_immediate(&mut notified1).await.is_none()); // no work yet

// Notification sent
notify.notify_one();

// First listener dropped, notification lost.
drop(notified1);

// Second listener
notify.notified().await; // stuck forever!
```

**Comment by Noah-Kennedy** [comment]
I'm really not sure if this is the intended behavior or not.

**Comment by jakajancar** [comment]
The same problem exists with Semaphore.

  - Many clients (e.g. via HTTP) waiting (`.notified()` or `.acquire()`) for a shared resource.
  - A resource becomes available and `.notify_one()` or `.add_permits(1)` is called.
  - However the client cancels (e.g. disconnects) before being awakened.
  - No other client ever gets notified / awakened.

Maybe I'm solving this in a wrong way...

**Comment by Darksonn** [comment]
This is certainly not supposed to happen, but I am quite puzzled because we have a test for this:

https://github.com/tokio-rs/tokio/blob/221bb94b9c78f137cb0675f62b6d2e26cdf8d987/tokio/tests/sync_notify.rs#L87-L105

Can you post a complete example including all imports and your `Cargo.toml`, or a link to a runnable playground?

**Comment by taiki-e** [comment]
> // First listener dropped, notification lost.
> drop(notified1);

Note that `notified1` is a pinned reference. Dropping a reference guarantees that the reference lives up to this point, but does not guarantee that the referenced value will be dropped here.

**Comment by jakajancar** [comment]
You are correct, changing `pin!` to `Box::pin` and ensuring the first `Notified` is dropped, makes the second one complete.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1417b22a0d7b0500f31af01d8bc28834)
