### ISSUE TITLE
Document how `tokio::sync::broadcast::channel(0)` behaves

### ISSUE THREAD

**Issue by TheButlah** [tokio-rs/tokio#4621]
I'm not sure how `broadcast::channel(0)` would work, and if I should set my capacity to 0 or 1 if I only intend on ever sending 1 message. If the capacity is 0, does that mean the sending thread blocks until all receiving threads have received, like `crossbeam_channel`? https://docs.rs/crossbeam-channel/latest/crossbeam_channel/struct.Sender.html#method.send

**Comment by Darksonn** [comment]
The function will panic if you specify a capacity of zero.

Feel free to submit a PR that adds that to the documentation.
