### ISSUE TITLE
Switch back to std::sync::Mutex?

### ISSUE THREAD

**Issue by SUPERCILEX** [tokio-rs/tokio#4623]
https://github.com/rust-lang/rust/pull/95035

std is using futex now and seems to beat parking lot in most cases. Are there contention benchmarks that could validate this for tokio?

**Comment by hawkw** [comment]
Tokio's use of `parking_lot` is an off-by-default optional dependency, so Tokio actually uses `std::sync::Mutex` by default, unless the `parking_lot` feature flag is enabled.

However, I agree that it would be interesting to measure performance with `std`'s new mutex implementation; we might stop recommending the use of `parking_lot` if performance is consistently better with `std` now...

**Comment by SUPERCILEX** [comment]
Oops, I thought parking_lot was the default. Either way, if std faster I think parking_lot should just be removed entirely.

**Comment by Darksonn** [comment]
The parking_lot mutex has a `const` new method. We use that in some places, e.g. [here][1].

[1]: https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html#method.const_new

**Comment by SUPERCILEX** [comment]
Dang, though that stuff should be able to be deprecated as std is moving towards removing the allocation that prevents things from being const: https://github.com/rust-lang/rust/issues/93740

**Comment by hawkw** [comment]
> Oops, I thought parking_lot was the default. Either way, if std faster I think parking_lot should just be removed entirely.

Removing the feature flag is a breaking change. It _could_ be made into a no-op, where enabling it doesn't actually *do* anything and Tokio unconditionally would use the `std`mutex, but this seems...questionable.

**Comment by SUPERCILEX** [comment]
How does deprecation work? Would the idea be to say the flag is deprecated (AFAIK there's no way to mark a flag as deprecated) and then remove it in a major release?

I think it's perfectly reasonable to make it a noop (I would even argue removal is fine without a major release) because parking_lot is specifically documented as an "internal feature." Unless there's a policy about internal features I'm missing?

**Comment by jdahlstrom** [comment]
Futexes are a Linux-only thing, remember.

**Comment by hawkw** [comment]
> How does deprecation work? Would the idea be to say the flag is deprecated (AFAIK there's no way to mark a flag as deprecated) and then remove it in a major release?

There isn't any way to mark a feature flag itself as deprecated, but it could be made to emit a deprecation warning by enabling code that emits a deprecation warning. An otherwise unused type can be added and marked as deprecated to emit a deprecation warning when the feature is enabled.

Alternatively, a build script could check if the "deprecated" feature is enabled, and emit a warning using `println!("cargo:warning=...);"`.

Both of these solutions are kind of hacky though.

**Comment by Noah-Kennedy** [comment]
Personally I see no reason to get rid of this feature.

**Comment by hawkw** [comment]
Yeah, IMO, the only compelling reason to remove the feature is to actually get rid of the need to test another feature combination, which we can't do without a breaking change anyway, so it's not going to happen any time soon. Users can always just choose not to enable `parking_lot`...which is what they get by default anyway.

**Comment by memoryruins** [comment]
> The parking_lot mutex has a `const` new method. We use that in some places, e.g. [here](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html#method.const_new).

https://github.com/rust-lang/rust/pull/97791 should make std's `{Mutex, Condvar, RwLock}::new()` const in `rustc 1.63.0`.

**Comment by Darksonn** [comment]
That's nice to know. Increasing our MSRV to 1.63.0 isn't going to happen anytime soon, but it probably will eventually.

**Comment by Noah-Kennedy** [comment]
So for now that would be a breaking change due to const and MSRV. Once that change happens, I'd still say its a breaking change.

**Comment by nashley** [comment]
>Increasing our MSRV to 1.63.0 isn't going to happen anytime soon, but it probably will eventually.

Once this happens, can `tokio`'s `Mutex::new()` become `const` as well, or are there other reasons that preclude it from becoming `const`?

**Comment by hawkw** [comment]
> > Increasing our MSRV to 1.63.0 isn't going to happen anytime soon, but it probably will eventually.
> 
> Once this happens, can `tokio`'s `Mutex::new()` become `const` as well, or are there other reasons that preclude it from becoming `const`?

`Mutex::new` could certainly become `const fn` once `std::sync::Mutex::new` is a `const fn` on Tokio's MSRV &mdash; note that when `parking_lot` is enabled, there's currently a separate [`const_new` constructor](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#method.const_new). Once Tokio's MSRV is Rust 1.63.0 or newer, we could probably deprecate that in favor of making `Mutex::new` just be a `const fn`.

**Comment by NobodyXu** [comment]
> > > Increasing our MSRV to 1.63.0 isn't going to happen anytime soon, but it probably will eventually.
> > 
> > 
> > Once this happens, can `tokio`'s `Mutex::new()` become `const` as well, or are there other reasons that preclude it from becoming `const`?
> 
> `Mutex::new` could certainly become `const fn` once `std::sync::Mutex::new` is a `const fn` on Tokio's MSRV — note that when `parking_lot` is enabled, there's currently a separate [`const_new` constructor](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#method.const_new). Once Tokio's MSRV is Rust 1.63.0 or newer, we could probably deprecate that in favor of making `Mutex::new` just be a `const fn`.

Unfortunately they can't since with `cfg(all(tokio_unstable, feature = "tracing"))` `Mutex::new` will log using `tracing::trace!` and it also constructs a span using `tracing::trace_span!`.
