### ISSUE TITLE
Documentation example out of date 

### ISSUE THREAD

**Issue by Fiono11** [tokio-rs/tokio#4628]
**Version**
tokio-timer-0.2.13

**Description**

The example usage of `DelayQueue` to manage cache entries appears to be out of date (https://docs.rs/tokio-timer/latest/tokio_timer/struct.DelayQueue.html)

**Comment by Darksonn** [comment]
In what way?

**Comment by Fiono11** [comment]
The `futures` crate api has changed.

**Comment by Darksonn** [comment]
Oh, you are looking at the outdated `tokio-timer` crate. The up-to-date `DelayQueue` is found in the `tokio-util` crate.
