### ISSUE TITLE
broadcast receivers :Only some will be received

### ISSUE THREAD

**Issue by rockit-ba** [tokio-rs/tokio#4647]
**Version**
 tokio v1.17.0

**Platform**
Apple M1
**Description**
There are multiple receivers, but after the broadcast sends the message, only the nearest two receivers will receive the message. I don't know where the code is written . In the vicinity of  `broad_receiver.recv()` .

```rust
 pub async fn start(&mut self) -> Result<()> {
        let listener = TcpListener::bind(self.addr.as_str()).await?;
        info!("Connor Server_Bootstrap Startup");
        let mut listener_stream = TcpListenerStream::new(listener);

        let (broad_tx, _) = broadcast::channel::<InboundHandleBroadcastEvent>(1024*1024);
        while let Some(socket) = listener_stream.try_next().await? {

            let peer_addr = socket.peer_addr().unwrap().to_string();
            info!("connection come in：{}", &peer_addr);
            let (m_sender, mut s_receiver) = mpsc::channel::<InboundHandleSingleEvent>(1);
            let arc_map = self.servers.clone();
            // channel
            let (mut writer, mut reader) =
                Framed::new(socket, LengthDelimitedCodec::new()).split();
            // response client spawn
            let mut broad_receiver = broad_tx.subscribe();
            info!("count {}",broad_tx.receiver_count());
            let response_handle = tokio::spawn(async move {
                loop {
                    if let Some(data) = s_receiver.recv().await{
                        println!("{:?}",data);
                        outbound_handle(data,&mut writer).await;
                    }

                    if let Ok(data) = broad_receiver.recv().await {
                        println!("{:?}",data);
                        outbound_broad_handle(data,&mut writer).await;
                    }
                }
            });

            let broad_sender = broad_tx.clone();
            tokio::spawn(async move {
                let m_sender = m_sender;
                while let Ok(Some(req)) = reader.try_next().await {
                    let string = String::from_utf8((&req).to_vec())
                        .unwrap_or_else(|_| panic!("{}", Byte2JsonErr));
                    info!("Inbound data：{}", string);

                    if let Ok(rpc_kind) = RpcKind::from_str(&string[0..1]) {
                        let json = &string[1..];
                        inbound_handle(rpc_kind, json, &broad_sender, &m_sender,arc_map.clone()).await;
                    }
                }

                warn!("Reader Close\n");
                response_handle.abort();
                warn!("Writer Close\n");
            });
        }
        Ok(())
    }
```

**Comment by Darksonn** [comment]
I haven't studied your code in detail, but it looks like you are ignoring the [`Lagged`](https://docs.rs/tokio/latest/tokio/sync/broadcast/error/enum.RecvError.html#variant.Lagged) error, which happens when messages are lost due because the capacaity was exceeded.

**Comment by rockit-ba** [comment]
> Lagged

When I processed the error, it actually reported no errors。In fact, it can't exceed capacity, I set the capacity to 1024 by 1024, and my code uses very little capacity

<img width="698" alt="image" src="https://user-images.githubusercontent.com/53960157/166164472-7bbb70e0-cd84-4290-b3e7-a5a32a7aa3b1.png">

**Comment by Darksonn** [comment]
The broadcast channel has received quite extensive use. I strongly doubt you have found a bug—you are probably misunderstanding something about how your code works.

If you still think this is a bug, please create a minimal reproducible example with the problem.

**Comment by rockit-ba** [comment]
> The broadcast channel has received quite extensive use. I strongly doubt you have found a bug—you are probably misunderstanding something about how your code works.
> 
> If you still think this is a bug, please create a minimal reproducible example with the problem.

I think I found the problem. Thank you.
