### ISSUE TITLE
tokio-fs: 0.1.2 release

### ISSUE THREAD

**Issue by lnicola** [tokio-rs/tokio#467]
- [ ] decide if #454 and #450 should go in
- [ ] update version and `html_root_url` (#469)
- [x] check changelog

**Comment by dekellum** [comment]
Sorry @lnicola if my PR's are slowing your release down. I've been trying my best to get these merged! Any guidance on getting these merged would be greatly appreciated!

**Comment by lnicola** [comment]
Considering #469, I don't think they are. I don't have commit rights here either :smile:.

As guidance, pinging carllerche on Gitter seemed to work, but I figured he's busy with other stuff.

**Comment by carllerche** [comment]
Thanks 👍 

tokio-fs 0.1.2 is out.
