### ISSUE TITLE
Feature request: a way to stop yielding in nested `select!`

### ISSUE THREAD

**Issue by Banyc** [tokio-rs/tokio#4673]
### Discussed in https://github.com/tokio-rs/tokio/discussions/4672

<div type='discussions-op-text'>

<sup>Originally posted by **Banyc** May 10, 2022</sup>
I want to encapsulate the inner `select!` as a single entry point so that the outer `select!` don't need to explicitly handle every arm in the inner `select!`. However, if the body of an arm in the inner `select!` happens to `await`, the `await` will yield and let other `select!` arms interrupt the body. Worse still, the lines after the `await` won't be called at all.

```rust
use std::time::Duration;

use tokio::{select, time};

#[tokio::main]
async fn main() {
    println!("Hello, world!");

    run().await;
}

async fn run() {
    let mut interval_3s = time::interval(Duration::from_secs(3));
    let mut interval_sleep = time::interval(Duration::from_secs(7));
    let mut s = S::new();

    loop {
        select! {
            _ = s.another_select() => {
                println!("run: another_select");  // never called
            }
            _ = interval_3s.tick() => {
                println!("run: interval_3s");
            }
            _ = interval_sleep.tick() => {
                println!("run: interval_sleep");
                // during this time, no other arms interrupt which is ideal
                time::sleep(Duration::from_secs(5)).await;
                println!("run: interval_sleep + 5s");
            }
        }
    }
}

struct S {
    interval_5s: time::Interval,
}

impl S {
    fn new() -> Self {
        S {
            interval_5s: time::interval(Duration::from_secs(5)),
        }
    }

    async fn another_select(&mut self) {
        select! {
            _ = self.interval_5s.tick() => {
                println!("another_select: tick");
                // during this time, it is expected not being interrupted by other arms of in the outer `select!`
                time::sleep(Duration::from_secs(5)).await;
                println!("another_select: tick + 5s");  // never called
            }
        }
    }
}

```

I don't want any code (`interval_3s.tick()` in this case) in the same `tokio::spawn`/task to preempt my encapsulated code (`s` in this case).

A raw workaround is to break the encapsulation and merge the `another_select` to the `select!` under `run`. But what if I have private members being used in `another_select`? Should they also be exposed and made public?
</div>

**Comment by Darksonn** [comment]
I'm going to close this. A solution was found in the discussion thread, and adding a special branch type for this is probably not desirable or even possible.
