### ISSUE TITLE
Cancel safety of `tokio::task::JoinHandle` is not documented

### ISSUE THREAD

**Issue by tbu-** [tokio-rs/tokio#4679]
Neither in the documentation of [`JoinHandle`](https://docs.rs/tokio/1.18.2/tokio/task/struct.JoinHandle.html) nor in the "Cancellation safety" of the [`select!`](https://docs.rs/tokio/1.18.2/tokio/macro.select.html#cancellation-safety) macro.

**Comment by Darksonn** [comment]
Well, cancelling something is done by dropping it, so once you've "cancelled" the `JoinHandle`, you don't have it anymore. It should say what happens when you drop it. On the other hand, if you use a mutable reference to the join handle in the select, then it isn't actually being cancelled at all.

**Comment by tbu-** [comment]
Can you explain why it is not planned? The [documentation of `select!`](https://docs.rs/tokio/1.20.1/tokio/macro.select.html#cancellation-safety) tells me that I need to be careful about using it with futures, that I need to determine whether they're cancellation safe. It lists a few futures, but `JoinHandle` isn't one of them. How should I, as a user, determine whether it (or a mutable reference to it) is cancellation safe?

**Comment by Darksonn** [comment]
Cancellation safety does not apply to `JoinHandle` at all because if you cancel it, the `JoinHandle` is lost and you cannot use it again. Anyway, I suppose it would be good to explain the situation in the docs regardless, so I have reopened the issue.

**Comment by tbu-** [comment]
Thanks!
