### ISSUE TITLE
Improve the documentation for #[tokio::test]

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#4720]
The `#[tokio::test]` macro currently has much less detail in its documentation than `#[tokio::main]`. The macro should also explain that each test gets a separate current-thread runtime.

**Comment by Pyrromanis** [comment]
I can give it a go

**Comment by Darksonn** [comment]
You should just make the change in our `tokio-macros/src/lib.rs` file. The change will be visible on `docs.rs/tokio` next time we make a release of Tokio.
