### ISSUE TITLE
spawn_local not working as intended nor deterministically

### ISSUE THREAD

**Issue by kkaatii** [tokio-rs/tokio#4734]
**Version**
1.18.2

**Platform**
WSL2, also repeatable on Rust Playground

**Description**
I'm trying to use single-threaded runtime in a multi-thread environment where there is a master thread and one or more worker threads. The master thread sends work requests and shutdown signals to the worker threads using unbounded tokio channels.

Each worker thread keeps an event loop. Upon receiving a work request, the worker thread spawns locally a new task and runs some work on that task. Upon receiving a shutdown signal, the worker simply breaks the event loop and enters a second loop to wait for all the spawned tasks the finish (also coordinated via unbounded channels).

I tried this code:

[Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=0e92c8f5f348a1f4bbcd7f291cea9525)

I expected to see this printed out:

```
Request received!
Falling asleep...
Cmd received!
Waken up
All tasks finished!
```

Instead, depending how much time the spawned task slept (see the line marked with "THIS ONE"), the mock task may finish multiple times or does not finish at all.
```
Request received!
Falling asleep...
Cmd received!
```

EDIT: Made a mistake polling the streams before. But still couldn't get it right after fixing that part unless I shorten the sleep period on the spawned task.

**Comment by Darksonn** [comment]
There's no guarantee that the `req_tx` message is received before the `cmd_tx` message.

**Comment by kkaatii** [comment]
But during times when it is received, you will still not see the correct results. For example, running this code without changing anything I may see this result
```
Request received!
Request received!
Cmd received!
Falling asleep...
Falling asleep...
Waken up
Waken up
All tasks finished!
```
Which is still strange--the master thread sent out 1 request but why 2 were received?

**Comment by Darksonn** [comment]
When you drop the sender and have received all sent messages, the receive calls will immediately return None every time you call it.

**Comment by kkaatii** [comment]
Yes you are right. Realized that I made a stupid mistake. 
Tried to fix the code in the original post but it still wouldn't work...

**Comment by Darksonn** [comment]
The `tokio::select!` macro has a pattern feature that you should be using rather than putting a check inside the branch.

**Comment by kkaatii** [comment]
Thanks for your patience (much appreciated!) and the suggestion. Modified the [code](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=4bd30d38469cdff540dab86378a54f62) as well but the issue still persists.

In this case and in my real-world application, the spawned task seems to never get polled again after the `Some(cmd)` branch breaks out the `select!` loop.

**Comment by Darksonn** [comment]
My guess is that your `finish_rx.next()` call returns `None` every time, turning the loop into a busy loop that never yields. This prevents the spawned task from running.

**Comment by kkaatii** [comment]
But actually when the spawned tasks owns a `finish_tx` and that `finish_tx` has not sent out a message, shouldn't the `finish_rx` poll to `Poll::Pending` since the other end of the stream is not closed?

Nevertheless, I tried modifying the [code](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=9af32a5cf6ce573e39babe3c1a5714f3) again using a `tokio::sync::mpsc` channel similar to what is demonstrated on the [official website](https://tokio.rs/tokio/topics/shutdown) under "Waiting for things to finish shutting down" but still couldn't get it to work. I'm literally pulling my hair now.

**Comment by kkaatii** [comment]
Well never mind. Seems like the playground just kills a long-running thread with a time out. So there must be some other issue with my real application.
