### ISSUE TITLE
task: add LocalSet::enter to enable calling `task::spawn_local` from outside of an async context

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#4736]
**Is your feature request related to a problem? Please describe.**

The `task::spawn_local` function is not async, which means it could be called from outside of an async context. However, this method also requires that it is called from within a "local" context. This local context is setup using `LocalSet::run_until`. However, *that* method is async.

All this to say, there is no *non-async* way to enter a local context.

**Describe the solution you'd like**

Add a `LocalSet::enter() -> EnterGuard` method that enables entering the local context without requiring async. Other types that setup contexts also include such a method. E.g.: https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.enter

**Comment by ritikBhandari** [comment]
Hi,
I'd like to work on this issue if available.

**Comment by Darksonn** [comment]
Sure, go ahead and submit a PR. You can ask on our discord server in `#tokio-dev` if you have any questions.

**Comment by gftea** [comment]
@Darksonn @carllerche , first try, please have a review

**Comment by Darksonn** [comment]
@gftea You will need to file a pull request containing your change.

**Comment by gftea** [comment]
@carllerche @Darksonn ,this can be closed because the PR is merged

**Comment by Tahinli** [comment]
Can this feature solve this kind of problem for me ?

I have to run a function in a nonblocking way that takes non send value.
```rust
tokio::spawn(async {
   if let Ok(non_send_value) = function_a().await {
      function_that_takes_non_send_value_and_takes_a_lot_of_time_to_finish(non_send_value)
   }
   
   printf("This print should not wait upper function");
})
```
