### ISSUE TITLE
tcpsockets can get stuck in CLOSE-WAIT 

### ISSUE THREAD

**Issue by aep** [tokio-rs/tokio#474]
A Stream which in its poll calls poll on Framed<TcpStream> does not unpark if the socket is closed by the remote. The socket instead gets stuck in CLOSE-WAIT forever.

this is the only output i get from tokio on log:
```
TRACE 2018-07-11T11:24:14Z: tokio_reactor: event Readable | Writable | Hup Token(4194305)
TRACE 2018-07-11T11:24:14Z: tokio_threadpool::notifier: Notifier::notify; id=0x7f277aa461d0
DEBUG 2018-07-11T11:24:14Z: tokio_reactor: loop process - 1 events, 0.000s
```

is it possible to register a specific future to be unparked when its inner socket gets closed?

the link "found online at tokio.rs" in https://docs.rs/tokio/0.1.7/tokio/prelude/trait.Future.html  is by the way a 404

**Comment by carllerche** [comment]
Did you get a `NotReady` trying to get the close event?

**Comment by carllerche** [comment]
In general, if you try reading from a socket, get NotReady, and the socket closes, that will trigger a notification.

**Comment by aep** [comment]
no NotReady either, just no unpark. It's not stuck anywhere either, all threads are in epoll (or the worker barrier).
This is very hard to reproduce unfortunately and the info I have so far inst particularity useful. Maybe there's more info somewhere on the internals that could help me find a direction?

**Comment by carllerche** [comment]
The log entries show that the task is being notified. If the task never gets called, it could be a bug, but I cannot say more without a repro to look at.

**Comment by aep** [comment]
is there any way to debug which futures are on a task?

**Comment by aep** [comment]
i can't reproduce this outside of my messy code. giving up.
