### ISSUE TITLE
Single-threaded runtime does not wait for spawned futures

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio#476]
if I spawn on the `Handle` to a remote `current_thread::Runtime`, then resolve the future that the `current_thread::Runtime` is blocking on, then call `current_thread::Runtime::run`, `run` returns without necessarily polling the spawned future..

Example code ([on playground](https://play.rust-lang.org/?gist=9a7ab5b2a1ed78de9ed21c6a71178ca1&version=nightly&mode=debug&edition=2015)):

```rust
let (trigger, exit) = futures::sync::oneshot::channel();
let (handle_tx, handle_rx) = ::std::sync::mpsc::channel();
let jh = ::std::thread::spawn(move || {
    let mut rt = tokio::runtime::current_thread::Runtime::new().unwrap();
    handle_tx.send(rt.handle()).unwrap();

    // don't exit until we are told to
    rt.block_on(exit.map_err(|_| ())).unwrap();
    // NOTE: if we instead just spawn the future, all is well :/
    //rt.spawn(exit.map_err(|_| ()));

    // run until all spawned futures (incl. the "exit" signal future)
    // have completed.
    rt.run().unwrap();
});

let (tx, rx) = futures::sync::oneshot::channel();

let handle = handle_rx.recv().unwrap();
handle
    .spawn(futures::future::lazy(move || {
        tx.send(()).unwrap();
        Ok(())
    }))
    .unwrap();

// signal runtime thread to exit
trigger.send(()).unwrap();

// wait for runtime thread to exit
jh.join().unwrap();

// this uwnrap fails; it gets Canceled, which suggests that the
// spawned future is dropped before it is executed.
assert_eq!(rx.wait().unwrap(), ());
```

**Comment by carllerche** [comment]
Submitting futures from other threads goes over a channel. The runtime shuts down if there are zero active futures (in the channel do not count right now). This is the [fn](https://github.com/tokio-rs/tokio/blob/master/tokio-current-thread/src/lib.rs#L222) that does the check.

To fix this, `num_futures` would need to be switched to an `AtomicUsize` and would have to both track the number of futures currently in the executor **and** in the channel. It would also have to have a magic value indicating that the runtime is shutdown. This would allow `run` to exit while ensuring that `Handle` never accepts a task that doesn't ever get run.
