### ISSUE TITLE
Expose the max channel buffer capacity

### ISSUE THREAD

**Issue by Sunt-ing** [tokio-rs/tokio#4792]
**Describe the solution you'd like**
Provide a way to expose the given capacity of the channel buffers. i.e.
```rust
impl Sender<T>{
[...]
  pub fn max_buffer_len(&self)->usize{
   self.[inner-semaphore].permits()
  }
}
```

**Describe alternatives you've considered**
Currently have to pass a `tx` clone along with the allocated buffer size as a parameter.

Thanks!

**Comment by Darksonn** [comment]
Does this not already exist? [`mpsc::Sender::capacity`][1]

[1]: https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Sender.html#method.capacity

**Comment by Sunt-ing** [comment]
This is the current available_permits. I need the max capacity. Example:
```rust
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    let (tx, mut rx) = mpsc::channel(100);

    tokio::spawn(async move {
        for i in 0..10 {
            tx.send(i).await.unwrap();
            assert_eq!(tx.max_capacity(), 100);
            // assert_eq!(tx.capacity(), 100);
        }
    });
}
```

**Comment by Darksonn** [comment]
I don't mind adding this function. If you want to submit a PR, then go ahead.
