### ISSUE TITLE
process: Windows tests failing on 1.62

### ISSUE THREAD

**Issue by Noah-Kennedy** [tokio-rs/tokio#4801]
With the new version of rust having landed, windows tests are failing. Specifically, it seems that the `pipe_from_one_command_to_another` test is failing.

I'm currently investigating what exactly is prompting this to fail on windows. Once the root cause is identified, we can figure out how to proceed from there. It may be an std issue or it may be on us.

CI build failure: https://github.com/tokio-rs/tokio/runs/7155496538?check_suite_focus=true#step:8:228

**Comment by pie-flavor** [comment]
https://github.com/rust-lang/rust/pull/95469

**Comment by Noah-Kennedy** [comment]
Thanks!

**Comment by ChrisDenton** [comment]
Hi, the linked PR fixed a soundness issue reported by Microsoft in https://github.com/rust-lang/rust/issues/81357

The short version is that passing async file handles through stdio is unsound. They must be synchronous. The "fix" was to abort the process when stdio reads or writes do not complete synchronously.

This did however have the effect of breaking code. Including within the stdlib itself. A rather inelegant "pipe relay" (https://github.com/rust-lang/rust/pull/95841) had to be added to turn async pipes synchronous.

Iirc in tokio's case it's mio giving out async pipe handles, which will cause problems when passed to stdin or stdout.

See also: https://github.com/tokio-rs/tokio/issues/4670 (aka my failed attempt to use more synchronous pipes in stdlib).

**Comment by Noah-Kennedy** [comment]
Thanks @ChrisDenton!

I actually read that, and just wrote a change that _should_ fix this failing test, however I now need to write up a bunch of documentation changes.

**Comment by Noah-Kennedy** [comment]
@ChrisDenton I don't see this in the rust release notes, did I miss something, or was it omitted?

**Comment by ChrisDenton** [comment]
Hm you're right. The pipe relay thing was added to the notes but the issue it was working around wasn't. That appears to have been an oversight. I'll see to fixing that.

**Comment by Noah-Kennedy** [comment]
Thanks!
