### ISSUE TITLE
Implement Clone for watch::Sender to make it multi-producer

### ISSUE THREAD

**Issue by madadam** [tokio-rs/tokio#4809]
Currently `watch` is single-producer but looking at the [source of `Sender`](https://github.com/tokio-rs/tokio/blob/master/tokio/src/sync/watch.rs#L86-L88), it seems it would be trivial to change it to multi-producer - just slap a `#[derive(Clone)]` on it. I think this would make it more useful as it would be possible to watch multiple sources. It's already possible to put the `Sender` into `Arc`, but it's inefficient because it's essentially an `Arc` in an `Arc`. 

Would the tokio maintainers be interested in a PR to add this?

**Comment by madadam** [comment]
Good point, I haven't considered it. Guess that makes it not quite as trivial as I though...

**Comment by madadam** [comment]
I think to properly implement this, we would have to track the number of senders instead of just a single bit indicating closed channel. Thus we won't be able to pack the information about whether the channel is closed into the same atomic as the version and we would need a separate atomic. That would make the state loading operation no longer atomic (because it would require two separate atomic `load`s). I'm not sure what implication that would have. I think it should be fine because the two values are independent, but I might be missing something.

**Comment by madadam** [comment]
But currently the flag indicating whether the channel is closed *is* packed together with the version. So I wonder whether that's just to save some space or whether there is a deeper reason.

**Comment by Darksonn** [comment]
Packing the closed flag together with the version is indeed done for space reasons.

**Comment by bouk** [comment]
I've started work on this feature here: https://github.com/tokio-rs/tokio/pull/5936

Comments welcome
