### ISSUE TITLE
tokio_codec: replacement for split() missing?

### ISSUE THREAD

**Issue by drahnr** [tokio-rs/tokio#481]
For some really interesting protocols it is nice to have the option to split the `Sink` from the `Stream` - but the `split()` (as presented fromerly by `tokio-io` ) method is gone. What's the best practice to achieve this with `tokio_codec`?

**Comment by carllerche** [comment]
I believe that you mean `split` defined on `Stream`? https://docs.rs/tokio/0.1.7/tokio/prelude/trait.Stream.html#method.split Is this

**Comment by drahnr** [comment]
You are right. I think this is mostly a result of my mental model still being stuck with the old ways of the `tokio_io` crate. Apologies for the noise.
