### ISSUE TITLE
Clippy lint firing with `tokio::task_local` macro

### ISSUE THREAD

**Issue by sbromling** [tokio-rs/tokio#4836]
**Version**
 1.20.0

**Platform**
 x86_64 GNU/Linux

**Description**
After adopting the latest tokio 1.20.0 release, and using the latest stable rust toolchain (1.62.0), clippy reports the  https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const lint against `tokio::task_local!` macro uses.

Seems like this is similar to https://github.com/rust-lang/rust-clippy/issues/8493, i.e. this may be a false positive.

**Comment by rukai** [comment]
This lint is still firing on the latest rust nightly so I raised on issue on the clippy repo https://github.com/rust-lang/rust-clippy/issues/9224
