### ISSUE TITLE
Timeout_at not working as expected when deadline already expired at call time

### ISSUE THREAD

**Issue by thepyper** [tokio-rs/tokio#4842]
On tokio versions:
│   │   │   └── tokio-macros v1.7.0 (proc-macro)
│   │   ├── tokio-util v0.7.2
├── tokio v1.18.2 (*)
├── tokio-rustls v0.23.4 (*)

on alpine linux (arm)

I have an issue with tokio::time::timeout_at() not working as I expected.
Maybe it's intended behaviour, but I give my experience:
I have a loop in a server, trying to read data from a client (tcp), and wanted to manage a timeout.
Roughly, my loop works like that:

let deadline = ... now + some seconds

loop {
  tokio::time::timeout_at(deadline, stream.read(...)).await.map(|_| Error::Timeout)?.map(|_| Error::Read)?;
  match {
     0 => { no new incoming data, sleep for 250 ms },
     i => { some new data, manage it and maybe break loop if enough data arrived }
  }
}

So what happened sometime is that some (bad?) client connected, and sent no data.
This way, match always fell into the 0 case;
This way, after some looping tokio::time::timeout_at(...) was called with a past deadline.. that is, Instant::now() > deadline.

My expectation would be that timeout_at would immediately return a Timeout error.
Instead, timeout_at just worked fine, and continued executing stream.read() call.
I don't know what could happen on a non-returning working call, maybe timeout_at would block?

So I solved by just checking if deadline was passed before calling timeout_at.
This is ok for me, but maybe that check should be integrated in timeout_at?

Thanks!

**Comment by Darksonn** [comment]
The `Timeout` future will always check if the future is ready before checking the timeout. In your case, the `read` call was immediately ready, so the timeout didn't trigger.
