### ISSUE TITLE
`tokio::time::sleep` inside `spawn_blocking+block_on` causes tokio-runtime-worker to panic

### ISSUE THREAD

**Issue by AlastairHolmes** [tokio-rs/tokio#4862]
**Version**
1.19.2

**Platform**
Darwin MacBook-Pro-50.localdomain 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Description**
tokio-runtime-worker panics when tokio::time::sleep is called inside spawn_blocking+block_on, if the runtime is dropped after the spawn_blocking call. Also the future doesn't continue to run after the sleep should complete.

I tried this code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4cde3bd308480d86babd8b6b5063469e

```rust
use core::time::Duration;
use tokio; // 1.19.2

#[tokio::main]
async fn main() {
    let handle = tokio::runtime::Handle::current();
    tokio::task::spawn_blocking(move || {
        handle.block_on(async {
            tokio::time::sleep(Duration::from_secs(1)).await;
            println!("HELLO WORLD");
        })
    });
}
```

I'd expect the "HELLO WORLD" to be printed after ~1 second, no panics to happen, and then the app to exit. I.e. The tokio-runtime should wait for the spawn-blocking task to end before shutting down, and the tokio sleep should work until the tokio-runtime has shutdown.

Instead, it prints this:

```
thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /playground/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/time/driver/entry.rs:551:13
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.rust-lang.org/?version=stable&mode=release&edition=2021#)
```

**Comment by Darksonn** [comment]
When you return from main, the program will start shutdown immediately. You should make sure that you wait for the task to finish.
```Rust
#[tokio::main]
async fn main() {
    let handle = tokio::runtime::Handle::current();
    let join_handle = tokio::task::spawn_blocking(move || {
        handle.block_on(async {
            tokio::time::sleep(Duration::from_secs(1)).await;
            println!("HELLO WORLD");
        })
    });
    
    join_handle.await.unwrap();
}
```

**Comment by AlastairHolmes** [comment]
> When you return from main, the program will start shutdown immediately. You should make sure that you wait for the task to finish.
> 
> ```rust
> #[tokio::main]
> async fn main() {
>     let handle = tokio::runtime::Handle::current();
>     let join_handle = tokio::task::spawn_blocking(move || {
>         handle.block_on(async {
>             tokio::time::sleep(Duration::from_secs(1)).await;
>             println!("HELLO WORLD");
>         })
>     });
>     
>     join_handle.await.unwrap();
> }
> ```

The docs say: "Closures spawned using spawn_blocking cannot be cancelled. When you shut down the executor, it will wait indefinitely for all blocking operations to finish. You can use [shutdown_timeout](https://docs.rs/tokio/0.2.22/tokio/runtime/struct.Runtime.html#method.shutdown_timeout) to stop waiting for them after a certain timeout. Be aware that this will still not cancel the tasks — they are simply allowed to keep running after the method returns."

https://docs.rs/tokio/0.2.22/tokio/task/fn.spawn_blocking.html

**Comment by Darksonn** [comment]
Perhaps the documentation could be improved, but the behavior today is as intended. The shutdown process has started, so the IO and timer drivers are no longer available.

**Comment by AlastairHolmes** [comment]
@Darksonn 

The behaviour you described doesn't happen in this case below. In this example the executor does wait for the blocking task:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c9973131e2c9077a6c1d95bc86e52841

```
use core::time::Duration;
use tokio; // 1.19.2

#[tokio::main]
async fn foo() {
    let handle = tokio::runtime::Handle::current();
    tokio::task::spawn_blocking(move || {
        handle.block_on(async {
            std::thread::sleep(Duration::from_secs(5));
            println!("HELLO WORLD");
        })
    });
}

fn main() {
    foo();
    println!("HELLO WORLD 2");
}
```

It prints:

```
HELLO WORLD
HELLO WORLD 2
```

Suggesting foo doesn't exit until after the spawn_blocking has finished.

**Comment by Darksonn** [comment]
The shutdown process starts immediately when you return. The shutdown just takes five seconds to complete in this example.

**Comment by AlastairHolmes** [comment]
Ok, I understand now, thank you. I'd be interested in why tokio is designed like that? Because I think it would be much more helpful if IO and Timing did not stop working when shutdown begins.

**Comment by Darksonn** [comment]
Well, it's possible that we could change it, but it would make the shutdown process a lot more complicated.
