### ISSUE TITLE
Mutex::try_lock blocks in single-threaded runtime

### ISSUE THREAD

**Issue by jgerrish** [tokio-rs/tokio#4868]
**Version**
├── tokio v1.20.1
│   └── tokio-macros v1.8.0 (proc-macro)
└── tokio-util v0.7.3
    └── tokio v1.20.1 (*)

**Platform**
Linux ? 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
I'm attempting to use the Tokio Mutex::try_lock in a single-threaded application.  It appears to block instead of yielding immediately.

I tried this code:

    pub async fn start(&mut self) -> Result<bool, Error> {
        let running_result = self.running.try_lock();

        let mut running = match running_result {
            Ok(r) => r,
            Err(_e) => {
                error!("Already started the clock");
                return Err(Error::new(ErrorKind::ClockAlreadyRunning));
            }
        };
        ....
    } 

A full working example is here:
https://github.com/jgerrish/async-soft-clock

I expected to see this happen:
I expected it to immediately return, or at least at the next yield point.

Instead, this happened:
The second task that calls start() blocks until the first task finishes.

It may be a misunderstanding of Tokio or asynchronous on my part.  If that's the case, I'm sorry.

Thank you for your help.

**Comment by Darksonn** [comment]
Looking at the implementation of `Mutex::try_lock`, that should be impossible - especially in a single-threaded setting. I'm guessing that the thing blocking the thread is something else.

Can you reduce the example further? The example you posted is really large. Ideally a minimum example would fit in a single short file.

**Comment by jgerrish** [comment]
An update, I've created a simplified version, but wasn't able to reproduce the behavior. I'll see if I can reproduce it with another example.  If not, I'll assume I mistook something I was doing wrong in my code for a Tokio bug.

Ok, to help with tracking, here's a link to a single-file example that fails to reproduce, using the following dependencies:

lazy_static = { version = "1.4" }
tokio = { version = "1.20", features = ["time", "rt", "macros", "io-std"] }
tokio-util = { version = "0.7" }

https://gist.github.com/jgerrish/4ea86aa5e642b226d40b09f177603015

**Comment by jgerrish** [comment]
Further testing with a multithreaded runtime couldn't reproduce.

Feel free to close the issue.

Thank you for your time.
