### ISSUE TITLE
Multiple `tokio::io::copy` streaming to and from `tokio::process::Command`'s child stdin/stdout appears to hang

### ISSUE THREAD

**Issue by opsound** [tokio-rs/tokio#4884]
**Version**
tokio_process_bug v0.1.0 (/Users/amastro/tokio_process_bug)
└── tokio v1.20.1
    └── tokio-macros v1.8.0 (proc-macro)

**Platform**
Darwin amastro-mbp 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

**Description**
I am attempting to use tokio to stream an input file to stdin of a subprocess, and at the same time stream its stdout to a different output file. I was able to achieve equivalent functionality using `std::process::Command` and multiple `std::thread`s which each run a `std::io::copy`. I am unsure if I am holding tokio+async wrong, or if this is a bug.

I tried this code:

```rust
#[tokio::main]
async fn main() {
    let args: Vec<_> = std::env::args().collect();
    let cmd = &args[1];
    let in_path = &args[2];
    let out_path = &args[3];
    println!("{} {} {}", cmd, in_path, out_path);

    let mut in_file = tokio::fs::File::open(in_path).await.unwrap();
    let mut out_file = tokio::fs::File::create(out_path).await.unwrap();
    let mut child = tokio::process::Command::new(cmd)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .unwrap();

    let mut stdin = child.stdin.take().unwrap();
    let mut stdout = child.stdout.take().unwrap();
    let mut stderr = child.stderr.take().unwrap();
    let mut stderr_buf = Vec::new();

    let (status, ..) = tokio::join!(
        child.wait(),
        tokio::io::copy(&mut in_file, &mut stdin),
        tokio::io::copy(&mut stdout, &mut out_file),
        tokio::io::copy(&mut stderr, &mut stderr_buf),
    );

    println!("finished: {:?}", status);
}
```

I expected to see this happen:
The input file to get piped to `cat` which pipes into the output file 
I expected similar functionality to 
```
cat < ./infile > ./outfile
```

Instead, this happened: 
```
amastro@amastro-mbp tokio_process_bug % echo hello world > infile
amastro@amastro-mbp tokio_process_bug % cargo run -- cat ./infile ./outfile
cat ./infile ./outfile 
# program hangs -- "finished" never printed
```
No progress is made past the `join!`

**Comment by opsound** [comment]
I figured it out. I needed to drop `stdin` after the copy. In my version with `std`, I was spawning a closure which moved `stdin` into it. `stdin` got dropped at the end of the closure's scope. Here, `stdin` is still in scope, so it's keeping the child alive. 

Here is working code

```
#[tokio::main]
async fn main() {
    let args: Vec<_> = std::env::args().collect();
    let cmd = &args[1];
    let in_path = &args[2];
    let out_path = &args[3];
    println!("{} {} {}", cmd, in_path, out_path);

    let mut in_file = tokio::fs::File::open(in_path).await.unwrap();
    let mut out_file = tokio::fs::File::create(out_path).await.unwrap();
    let mut child = tokio::process::Command::new(cmd)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .unwrap();

    let mut stdin = child.stdin.take().unwrap();
    let mut stdout = child.stdout.take().unwrap();
    let mut stderr = child.stderr.take().unwrap();
    let mut stderr_buf = Vec::new();

    let (status, ..) = tokio::join!(
        child.wait(),
        async move {
            let _ = tokio::io::copy(&mut in_file, &mut stdin).await;
            drop(stdin);
        },
        tokio::io::copy(&mut stdout, &mut out_file),
        tokio::io::copy(&mut stderr, &mut stderr_buf),
    );

    println!("finished: {:?}", status);
}
```

**Comment by Darksonn** [comment]
You should probably flush your two output files at the end.

**Comment by opsound** [comment]
> 

> You should probably flush your two output files at the end.

Makes sense. Thank you. I hadn't been thinking about flush. Neither `File`'s `Drop`, nor the OS `man 2 close` fd close implicitly flushes file output.

**Comment by opsound** [comment]
> You should probably flush your two output files at the end.

Makes sense. Thank you. I hadn't been thinking about flush. Neither `File`'s `Drop`, nor the OS `man 2 close` fd close implicitly flushes file output.

**Comment by Darksonn** [comment]
The `std::fs::File` doesn't need flushing. It only makes a difference for the Tokio file.
