### ISSUE TITLE
New point release with `wasm32-wasi` Cargo fixes

### ISSUE THREAD

**Issue by rjzak** [tokio-rs/tokio#4892]
**Is your feature request related to a problem? Please describe.**
The current version of Tokio on Crates.io allows for `socket2` to be compiled when compiling for `wasm32-wasi`, which always fails.

**Describe the solution you'd like**
A point release, `1.20.2`, since the bug was fixed after the latest release in commit https://github.com/tokio-rs/tokio/commit/b2ada60e701d5c9e6644cf8fc42a100774f8e23f

**Describe alternatives you've considered**
I'm working on `wasm32-wasi` support in downstream projects, and either they have to use old versions, or have to pull from Github directly.

**Comment by Darksonn** [comment]
Support for WASI has not been released yet at all. It will be available in the `1.21.0` release. If you want to use it before that release, then you will need to use the version of Tokio on github. You can do that with the following annotation in your `Cargo.toml`:
```toml
[patch.crates-io]
tokio = { git = 'https://github.com/tokio-rs/tokio.git' }
```

**Comment by npmccallum** [comment]
@Darksonn When can we expect `1.21.0`?

**Comment by Darksonn** [comment]
We don't have a fixed release schedule, but it's probably time for a release soon. I'll need to think about whether there are any things in the wasm support that I want to fix before the release.

**Comment by Noah-Kennedy** [comment]
@Darksonn we were going to stabilize JoinSet as well IIRC. Should I get a PR up to do this?
