### ISSUE TITLE
Unexpected `sleep()` behavior if time is paused

### ISSUE THREAD

**Issue by loyd** [tokio-rs/tokio#4899]
**Version**
1.19.2

**Description**
I don't understand why the following test fails:
```rust
    time::pause();
    let origin = time::Instant::now();
    time::sleep(time::Duration::from_secs(1)).await;
    assert_eq!(origin.elapsed(), time::Duration::from_secs(1));
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=423458cd4c9dc9f4278cd2a113944314

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1.001s`,
 right: `1s`', src/main.rs:8:5
```

Is it expected behavior? I know about 1ms precision, but why is it important here?

With such a constant bias it's harder to write long tests.

**Comment by Darksonn** [comment]
What you are seeing here is due to the amount of time between the test starting and the `time::pause()` method being called. To avoid it, you can do the following:
```Rust
use tokio::time;

#[tokio::main(flavor = "current_thread", start_paused = true)]
async fn main() {
    let origin = time::Instant::now();
    time::sleep(time::Duration::from_secs(1)).await;
    assert_eq!(origin.elapsed(), time::Duration::from_secs(1));
}
```
