### ISSUE TITLE
Flaky test `immediate_exit_on_error` should be fixed

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#4900]
The `immediate_exit_on_error` test in `tests/io_copy_bidirectional.rs` sometimes gets stuck and continues running forever. This should be fixed.

**Comment by podusowski** [comment]
I might be making some bad assumptions here, but this is how I understand what's going on here.

When timer in `block_write` is short enough, it might preempt the `write` call (which might be waiting for epoll or something). This causes a -> b path to have not enough data and `copy_bidirectional` finishes before b is dropped.

Normally my system backpressures writes after ~5M of data. When this test hangs I'm seeing `block_write` returning as little as 700k.

So in general the solution would be to extend the duration in `block_write` or somehow rewriting the whole logic, but nothing comes to my mind right now.
