### ISSUE TITLE
RunError is not a proper Error

### ISSUE THREAD

**Issue by vorner** [tokio-rs/tokio#491]
When working with [`current_thread::Runtime::run`](https://docs.rs/tokio/0.1.7/tokio/runtime/current_thread/struct.Runtime.html#method.run), I've noticed the returned `RunError` does not implement `Error` (so it is uncomfortable to handle as an error). It also doesn't seem to have any documentation (it is not a link), no idea why, so it is not clear under which circumstances it can happen.

**Comment by kpp** [comment]
@vorner would you please provide a MRE to test against?

**Comment by vorner** [comment]
I'll probably provide even the PR later this weekend, but here goes the MRE (if MRE is Minimum Reproducer or something like that).

```rust
extern crate failure;
extern crate tokio;

use failure::Error;
use tokio::prelude::future;
use tokio::runtime::current_thread::Runtime;

fn main() -> Result<(), Error> {
    let mut runtime = Runtime::new()?;
    // Well, this one would actually spawn some things…
    runtime.block_on(future::ok::<_, Error>(()))?;
    // This should wait for the rest of the spawned things… but it doesn't work, because RunError
    // doesn't implement the Error trait
    runtime.run()?;
    Ok(())
}
```

I went this way in actual real code, because `current_thread::run` doesn't allow the initialization future to error out and abort on startup.

Both `tokio` and `failure` are on their newest versions.

**Comment by carllerche** [comment]
The PR has been merged 👍 Thanks again.
