### ISSUE TITLE
Convenience and flexibility to switch between different execution contexts

### ISSUE THREAD

**Issue by npuichigo** [tokio-rs/tokio#4912]
As far as I know, tokio configures the default runtime to be a global execution context, like `current_thread` or `multi_thread`. But in some cases, multiple contexts are needed to match the actual needs. 

For example, someone may would like to spawn async jobs on some `gpu_context` while doing other works on `thread_context`.

In current [C++ executor design](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html), regardless of global context, user can easily schedule tasks on their own and may specify the completion context.
```c++
execution::scheduler auto cpu_sched = new_thread_scheduler{};
execution::scheduler auto gpu_sched = cuda::scheduler();

execution::sender auto snd0 = execution::schedule(cpu_sched);
execution::scheduler auto completion_sch0 =
  execution::get_completion_scheduler<execution::set_value_t>(snd0);
// completion_sch0 is equivalent to cpu_sched

execution::sender auto snd1 = execution::then(snd0, []{
    std::cout << "I am running on cpu_sched!\n";
});
execution::scheduler auto completion_sch1 =
  execution::get_completion_scheduler<execution::set_value_t>(snd1);
// completion_sch1 is equivalent to cpu_sched

execution::sender auto snd2 = execution::transfer(snd1, gpu_sched);
execution::sender auto snd3 = execution::then(snd2, []{
    std::cout << "I am running on gpu_sched!\n";
});
execution::scheduler auto completion_sch3 =
  execution::get_completion_scheduler<execution::set_value_t>(snd3);
// completion_sch3 is equivalent to gpu_sched
```

Since I'm new to tokio, I would like to ask if it's already available. Or do you have any future plan on improve the flexibility on context switching?

**Comment by Darksonn** [comment]
The `tokio::runtime::Handle` type allows for context-switching.

**Comment by npuichigo** [comment]
Thanks. So it seems that I need to create a new runtime and use handle to spawn new tasks.

**Comment by Darksonn** [comment]
If you want to have more than one runtime, then you need to spawn another runtime, yes.
