### ISSUE TITLE
tokio::io::copy_with_timeout

### ISSUE THREAD

**Issue by agrover** [tokio-rs/tokio#4919]
**Is your feature request related to a problem? Please describe.**
Wrapping the future from `copy` with a `timeout` will time out even if there's still copy activity ongoing. Instead, I'd like a timeout that pops when progress on the future stops -- i.e. there is either no more data to read for some amount of time, or cannot write for some amount of time. This doesn't seem possible to me (love to be shown otherwise) currently.

**Comment by sfackler** [comment]
You can wrap your readers and writers in https://docs.rs/tokio-io-timeout/latest/tokio_io_timeout/

**Comment by agrover** [comment]
Thanks! Ok, closing this.
