### ISSUE TITLE
Add a way to shutdown SyncIoBridge

### ISSUE THREAD

**Issue by KB5201314** [tokio-rs/tokio#4932]
**Is your feature request related to a problem? Please describe.**
`SyncIoBridge`(https://github.com/tokio-rs/tokio/pull/4146) does not provide a way to call the `shutdown()` function of its internal `tokio::io::AsyncWrite` instance. 

**Describe the solution you'd like**
Add a `shutdown()` function to `SyncIoBridge`, which invoke the shutdown() function of `src` field

**Describe alternatives you've considered**
n/a

**Additional context**
Take `tokio::io::DuplexStream` as en example. Its `shutdown()` can be used to close the writer of stream, but in the following example, I have no way to shutdown:
```rust
let (s1, _s2) = tokio::io::duplex(1024);
let (rh, wh) = tokio::io::split(s1);
tokio::task::spawn_blocking(move || {
    let mut wh = SyncIoBridge::new(wh);
    // wh.write_all() ...
    // Now I need to shutdown the write half
    wh.shutdown(); // I need this function
});
```

**Comment by KB5201314** [comment]
@Darksonn What do you think about the proposal to add `SyncIoBridge::shutdown()`? If appropriate, I can create a PR for this.

**Comment by Darksonn** [comment]
Adding a method for this sounds good to me.
