### ISSUE TITLE
StreamReader should have example that converts the error type

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#4954]
When using `StreamReader` together with reqwest, one will run into the issue that `reqwest::Error` isn't convertible to `std::io::Error`. We should include an example of how to make this conversion.

I imagine that the example will have a function like this:
```Rust
fn reqwest_to_io_error(err: reqwest::Error) -> std::io::Error {
    todo!()
}
```

**Comment by randomicon00** [comment]
Hello @Darksonn,
I would like to make my first contribution to the tokio project. 
How should the correspondance between the two errors be?

For instance, should we convert the `reqwest` `Kind::Status(StatusCode::NOT_FOUND)` into `std::io::Error`  `ErrorKind::NotFound` ?

**Comment by Darksonn** [comment]
Honestly, you can just put a call to `todo!()` and let the user of the example fill it in. This would also let the example apply more directly to any error type and not just reqwest.

**Comment by alexrudy** [comment]
@randomicon00 I just made my first contribution to Tokio against this issue (since I ran into it yesterday) and didn't refresh the issue to see that you wanted to work on it!

I'm sorry! Maybe you have a better approach for the example anyhow, I'm not attached to what I wrote up.

**Comment by randomicon00** [comment]
@alexrudy No problem, really :)

**Comment by Darksonn** [comment]
Thank you both for taking the time to work on this. I've looked over both examples and picked the one I prefer.
