### ISSUE TITLE
tokio::run never ends

### ISSUE THREAD

**Issue by Leonqn** [tokio-rs/tokio#496]
Program listed below will never finish. 
"Fut done" will be printed, but "program done" not. 
```
extern crate tokio; // 0.1.7
extern crate hyper; // 0.12.5

fn main() {
    use hyper::Client;
    use tokio::prelude::{Future, Stream};

    let client = Client::new();
    let fut = client
        .get("http://example.com".parse().unwrap())
        .and_then(|x| x.into_body().concat2())
        .map_err(|_| println!("Got error"))
        .map(|_| println!("Fut done"));
    tokio::run(fut);

    println!("Program done")
}
```
Although if you inline variable ```client``` or remove ```.and_then(|x| x.into_body().concat2())```, program will finish correctly
Is this ok?

**Comment by kpp** [comment]
> Is this ok?

No. It is fixed on `master` branch but I am not sure when. You may bisect on your own if you want.

**Comment by jsgf** [comment]
@kpp Do you have a reference to what the issue was? Was it a tokio, futures or hyper bug?

**Comment by kpp** [comment]
IDK, I ran your code on master branch and it worked fine. Use git bisect to find the issue

**Comment by jsgf** [comment]
OK, I'd put that as "it worked for me" rather than "it was fixed".

**Comment by kpp** [comment]
You may try on your own by specifying `master` branch for tokio in Cargo.toml.
Did it work for you too?

**Comment by Leonqn** [comment]
It works for me on master tokio branch.

**Comment by carllerche** [comment]
I'm not entirely sure what changed to makee this work on master, but seems good?

**Comment by Leonqn** [comment]
Yes

**Comment by drager** [comment]
I tried the code @Leonqn on master with rustc 1.27.2 (58cc626de 2018-07-18) and I get: 
`Error { kind: Execute, cause: None }`.

**Comment by Leonqn** [comment]
I also tried one more time on master. And for me it do not hangs, but returns an error ``failed to spawn task``

**Comment by seanmonstar** [comment]
If on tokio master the code pasted above is causing a spawn error, sounds like a bug in tokio. The code shouldn't cause any errors, but it *should* hang (yes, it's unfortunate, but that's what should be happening).

**Comment by carllerche** [comment]
Thanks all.

I ran the code provided against both 0.1.8 and master and am seeing the expected behavior.

I will close this issue. If there is still an error returned, please open a new issue with code to reproduce.
