### ISSUE TITLE
Tokio LocalSet can no longer be stored in thread_local

### ISSUE THREAD

**Issue by futursolo** [tokio-rs/tokio#4973]
**Version**

`tokio 1.21.0`

**Platform**

- `aarch64-unknown-linux-gnu`
- `x86_64-unknown-linux-gnu`

**Description**

The following [code](https://github.com/futursolo/local-set-test) runs fine with `1.20.1` but panics in `1.21.0`.

I tried this code:

```rust
use std::thread;

use tokio::runtime::Handle;
use tokio::sync::oneshot;
use tokio::task::LocalSet;

thread_local! {
    static LOCAL_SET: LocalSet = LocalSet::new();
}

#[tokio::main]
async fn main() {
    // holds runtime thread until end of main fn.
    let (_tx, rx) = oneshot::channel::<()>();
    let handle = Handle::current();

    thread::spawn(move || {
        LOCAL_SET.with(|local_set| {
            handle.block_on(local_set.run_until(async move {
                let _ = rx.await;
            }))
        });
    });
}
```

I expected to see this happen:

The code should run as normal.

Instead, this happened: 

```
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 3450452000
Aborted
```

**Comment by Noah-Kennedy** [comment]
Thanks for reporting this!

I have a few ideas as to what did this. I'm going to go and run a bisect.

**Comment by Darksonn** [comment]
This is probably caused by #4765, but I don't really understand how this was not already an issue. Perhaps that PR somehow changes the order in which the thread-locals are destroyed?

Anyway, I've opened a PR that should fix this.
