### ISSUE TITLE
Calling fill_buf on a BufReader<OwnedReadHalf> does not always bring fresh data when it should

### ISSUE THREAD

**Issue by Nic0w** [tokio-rs/tokio#4974]
**Version**
tokio v1.20.1

**Platform**
Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
Hi everyone,

I'm currently writing code for a custom network protocol that work with "sentences" consisting of multiples "words".
Sentences do not have a header with a finite size so the only way to know when the sentence ends is when you have read the word meaning "end". 
I took inspiration from the mini-redis example where a Frame is read asynchronously with a trial-and-error pattern : if there is not enough bytes in the buffer for a whole Frame, try to read more bytes, then try again, ...
Link to the function I took inspiration from: https://github.com/tokio-rs/mini-redis/blob/tutorial/src/connection.rs#L59

I ended up with the following code :
```rust
async fn try_read_sentence(reader: &mut BufReader<OwnedReadHalf>) -> Result<Vec<String>, Error> {
    println!("try_read_sentence");
    loop {
        let mut cursor = Cursor::new(reader.buffer());

        if let Ok(sentence) = read_sentence(&mut cursor) {
            let res = sentence.iter().map(|t| t.to_string()).collect();

            let consumed = cursor.position() as usize;

            reader.consume(consumed);

            return Ok(res);
        }

        //tokio::time::sleep(time::Duration::from_millis(10)).await;
        let new_bytes = reader.fill_buf().await?;

        if new_bytes.is_empty() {
            panic!("EOF");
        }
    }
}
```
The problem I initially witnessed is that maybe 1~2 time out of 5, the function "hangs". 
I tried to debug the problem with lots of `println!` to show buffer lengths and contents at each iteration (not shown here).

What happens is that sometimes, the function `read_sentence` ends up missing data to decode the whole sentence. Debugging the buffer's contents, I can see that remains a fixed amount of bytes, and that it is indeed not enough to parse a new sentence.

Firing up Wireshark to try and debug the issue at the network level, what happens is that I get sent approximately 7400 bytes in patterns of : ~2900 + ~4400 + ~200 bytes then ~200 bytes. Sometimes it's ~2600 + ~2600 + ~2200 bytes. 

Wireshark always show all the data getting to me, but when comparing the buffer returned by `fill_buf`, the problem becomes obvious:
it is stuck on the previous-to-last (or one before when data is split in 3 packets) packet's content, seemingly not wanting to read the last packet worth of data.

What could cause such an issue ?

**Comment by Nic0w** [comment]
More debugging with `strace` :

- Wireshark: shows reception of 7596 bytes in 3 packets of 2962 + 2962 + 1672 bytes.
- strace output shows 

```
[pid 521563] recvfrom(9, 0x7f7760000c20, 8192, 0, NULL, NULL) = -1 EAGAIN 
[pid 521563] epoll_wait(3, [{EPOLLIN|EPOLLOUT, {u32=1, u64=1}}], 1024, -1) = 1
[pid 521563] recvfrom(9, "..."..., 8192, 0, NULL, NULL) = 5792
/* parts of sentence gets processed, but not enough */

[pid 521563] epoll_wait(3, [{EPOLLIN|EPOLLOUT, {u32=1, u64=1}}, {EPOLLIN, {u32=2147483648, u64=2147483648}}], 1024, 11) = 2
[pid 521563] epoll_wait(3, [], 1024, 11) = 0
[pid 521563] write(4, "\1\0\0\0\0\0\0\0", 8) = 8
/* looping to infinity */
```
So 5792 bytes are read, which is exactly the 2 first packets I see in Wireshark; fill_buff is called but no new recvfrom is made...

When everything works as expected, strace output is like:
Receiving 3 packets (2962 + 4410 + 224 bytes )
```
[pid 526041] recvfrom(9, 0x7f90b4000c20, 8192, 0, NULL, NULL) = -1 EAGAIN (Ressource temporairement non disponible)
[pid 526041] epoll_wait(3, [{EPOLLIN|EPOLLOUT, {u32=1, u64=1}}], 1024, -1) = 1
[pid 526041] recvfrom(9, "..."..., 8192, 0, NULL, NULL) = 7398

/* sentence gets fully processed */
```

**Comment by Darksonn** [comment]
The `fill_buf` method does not read additional data if the buffer is non-empty.

**Comment by Nic0w** [comment]
Hmmm ... Reading the doc again, it now seem pretty obvious, indeed; as that's what's written :/

However I feel like the mini-redis example is misleading. It does say : 
```
    // ... Tokio's `BufReader`
    // currently requires you to empty its buffer before you can ask it to
    // retrieve more data from the underlying stream, so we have to manually
    // implement buffering. This should be fixed in Tokio v0.3.
```
But apparently it is still needed to empty the buffer. Or is there any feature/usage pattern that I missed ?

I must admit I am now at a loss at what to do with BufReader to achieve what I intended to do.

**Comment by Darksonn** [comment]
Ah, the part about it being fixed in v0.3 didn't happen. You can't use BufReader to implement the same kind of reading as what mini-redis does. If you're looking for a tool that can help you do this beyond just implementing it manually like mini-redis does, then that would be `tokio_util::codec`.

**Comment by Darksonn** [comment]
Actually where do you see that comment? I went to go update it, but I can't find it anywhere.

**Comment by Nic0w** [comment]
I will take a look at `tokio_util::codec`, thanks :) For now I rewrote my code using `try_read_buf` directly on the `OwnedReadHalf`, along with a BytesMut. Looks like it works as expected !

As for the comment I was quoting, it's there : 
https://github.com/tokio-rs/mini-redis/blob/tutorial/src/connection.rs#L27

I guess this can be closed now :)

**Comment by Darksonn** [comment]
Oh, so its on a different branch. I see.

**Comment by Nic0w** [comment]
Yes, apparently the Tokio website has links pointing to that branch. Here, for example: https://tokio.rs/tokio/tutorial/framing
