### ISSUE TITLE
Tokio 1.21 breaks semver on task::Builder::spawn

### ISSUE THREAD

**Issue by njaard** [tokio-rs/tokio#4982]
**Version**
1.21.0

**Platform**
Linux

**Description**

Version 1.21 of tokio has fn [spawn](https://docs.rs/tokio/latest/tokio/task/struct.Builder.html#method.spawn)<Fut>(self, future: Fut) -> [**Result**](https://doc.rust-lang.org/nightly/std/io/error/type.Result.html)\<JoinHandle\>

But tokio 1.20 has fn [spawn](https://docs.rs/tokio/1.20.1/tokio/task/struct.Builder.html#method.spawn)<Fut>(self, future: Fut) -> JoinHandle

This change in API breaks semver by having this function return a `Result` where before it returned the JoinHandle directly.

**Comment by sfackler** [comment]
`task::Builder` is explicitly part of the unstable API: 

![Screen Shot 2022-09-06 at 11 43 53 AM](https://user-images.githubusercontent.com/1455697/188678596-d7dd26af-7635-48fc-b271-ce6247f84a40.png)

**Comment by njaard** [comment]
Well, ok, nevermind :)
