### ISSUE TITLE
Second call of UdpSocket::send seems to fail even after calling UdpSocket::connect

### ISSUE THREAD

**Issue by Andful** [tokio-rs/tokio#4996]
**Version**
tokio 1.21.0

**Platform**
Linux \<redacted\> 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description**
After calling `UdpSocket::connect`, the first call to `UdpSocket::send` works, but the second call to `UdpSocket::send` fails.

Here is some code that fails.
```rust
use tokio::net::UdpSocket;

#[tokio::main]
async fn main() {
    let socket =  UdpSocket::bind(("0.0.0.0", 12345)).await.unwrap();
    socket.connect(("127.0.0.1", 1122)).await.unwrap();
    socket.send(b"test 123").await.unwrap();
    socket.send(b"test 123").await.unwrap();
}
```
and a rust playground link to the same code.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b522081daa9f88ba0bfb22080fd3d87e.

The code should work, and it should not matter if any program is listening to the specific port.

**Comment by Noah-Kennedy** [comment]
This is actually how UDP is supposed to work. Because nothing is listening on that port, an ICMP Unreachable packet is sent as a response to the initial datagram, causing the second attempted send to fail with "connection refused". This logic is in the kernel, not in tokio, which is why std::net::UdpSocket has the same behavior.

**Comment by hydra** [comment]
thanks for posting this question and the response, I bumped into this today too, it was entirely non-obvious from the UdpSocket documentation and really weird unexpected behavior.  On Windows this doesn't happen, so when I tried my Tokio UDP code on Linux it failed in really weird ways...

**Comment by Darksonn** [comment]
In general, you should never expect that a successfully sent UDP packet was received. UDP packets may be lost, duplicated, or reordered on the way to the recipient.

You may even encounter a situation where it fails on, say, the fifth packet. This can happen if the first three were lost and never made it to the recipient, and the fourth made the recipient reply with ICMP unreachable. Or even if they're not lost, you may have sent the first four packets quickly enough that the reply to the first one arrived after the fourth packet.

**Comment by hydra** [comment]
@Darksonn yes indeed, however 'connection refused' on the second message seemed somewhat odd, given that UDP is lossy to begin with.

In the code I was using, which worked on Windows and some other variants of Linux here, there was a check for errors which was closing the connection when an error occured.  The connection was closed when the second message was sent.  It was not clear why the first send succeeded and the second one failed.  Before I found this thread I didn't even know it was the second one that failed, and had already written some unit tests to make sure I could send and received, which passed, leading on a wild goose chase of digging around for hours trying to find out why I would get a connection refused on a **_UDP_** connection, when I already knew a) it works sometimes, b) there was nothing listening yet.

My solution was to specifically check for `ConnectionRefused` and ignore it, which is well, 'odd' for a **_CONNECTIONLESS_** protocol, and an ENTIRELY unexpected thing to have to implement.

**Comment by Darksonn** [comment]
What would you like us to do? This is simply how the OS works. Tokio just forwards errors from the OS.

**Comment by hydra** [comment]
> What would you like us to do? This is simply how the OS works. Tokio just forwards errors from the OS.

@Darksonn Perhaps improve API documentation for `send` a little, mentioning that later calls can fail even if the first one succeeds, this should help prevent developers running into this issue.
