### ISSUE TITLE
Compilation failure regression on x86_64-fortanix-unknown-sgx target

### ISSUE THREAD

**Issue by kostko** [tokio-rs/tokio#4999]
With tokio 1.20.1 it was possible to build for the `x86_64-fortanix-unknown-sgx` target when not using the `net` feature since the `socket2` dependency was optional and only enabled when `net` was enabled. With `tokio 1.21.0` compilation now fails due to `socket2` being required and built with the `all` feature flag which is not supported on the `x86_64-fortanix-unknown-sgx` target.

Could `socket2` be removed as a dependency on `x86_64-fortanix-unknown-sgx` similar to how it is now on `wasm*` targets or if there is another course of action that would be more suitable to ensure compilation on `x86_64-fortanix-unknown-sgx`?

**Comment by carllerche** [comment]
Is there a way to add a cross-compilation check for this platform in CI? @kostko is that something you could submit a PR for?

**Comment by kostko** [comment]
Sure, just opened #5001.

**Comment by kostko** [comment]
And thanks for the quick reply and fix!
