### ISSUE TITLE
length_delimited refactoring

### ISSUE THREAD

**Issue by kpp** [tokio-rs/tokio#500]
There is some work to be done to make the code for tokio_io::length_delimited a little bit cleaner. We need to get rid of custom Framed* types in favour of tokio_codec::Framed* types, rename length_delimited::Decoder -> Codec. Also the logic of length_delimited::Framed needs to be moved into Codec.

TODO list:

- [x] implement Codec (https://github.com/tokio-rs/tokio/pull/575)
- [x] remove Framed* (https://github.com/tokio-rs/tokio/pull/575)
- [x] move to tokio_utils (https://github.com/tokio-rs/tokio/pull/568)
- [x] mark old length_delimited as depricated (https://github.com/tokio-rs/tokio/pull/568)
- [x] tests for https://github.com/tokio-rs/tokio/issues/497 (https://github.com/tokio-rs/tokio/pull/576)
- [x] fix https://github.com/tokio-rs/tokio/issues/497 (https://github.com/tokio-rs/tokio/pull/576)

**Comment by carllerche** [comment]
I would move length_delimited into tokio_utils.

**Comment by kpp** [comment]
Good job Eliza!

**Comment by hawkw** [comment]
My pleasure!
