### ISSUE TITLE
performance degradation becuase of wrong `thread::yield_now()` in park.rs

### ISSUE THREAD

**Issue by zhzhsx** [tokio-rs/tokio#5010]
**Version**
tokio 1.12.0 to latest version

**Platform**
tested on x86_64 (Icelake server)

**Description**
Following line is `loom::thread::yield_now()` according to the import statement. It was (in version 1.11.0), and is better to be `std::thread::yield_now()`.

https://github.com/tokio-rs/tokio/blob/56ffea09e5ab682e49eab0374da651f277e72566/tokio/src/runtime/scheduler/multi_thread/park.rs#L124

https://github.com/tokio-rs/tokio/blob/56ffea09e5ab682e49eab0374da651f277e72566/tokio/src/runtime/scheduler/multi_thread/park.rs#L7

The change was introduced by commit f1b89675eb621edc23a9aa31d625270307fb6ce9 .

In a simple benchmark of simple http server based on hyper.rs in my enviroment, the QPS is 315198.85 in case of `std::thread`, and the QPS is 252620.14 in case of `loom::thread`, making a considerable difference.

The code of http server is from https://github.com/rousan/rust-web-frameworks-benchmark/tree/master/hyper , with hyper & tokio updated to latest version.
Wrk is used in benchmark, with flags: `wrk -t4 -c100 -d20s http://127.0.0.1:8082`

wrk output in case of `std::thread::yield_now`:
```
Running 20s test @ http://127.0.0.1:8082
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   301.72us  203.16us   9.03ms   85.39%
    Req/Sec    79.50k     5.85k  217.27k    93.13%
  6335559 requests in 20.10s, 531.70MB read
Requests/sec: 315198.85
Transfer/sec:     26.45MB
```
wrk output in case of `loom::thread::yield_now()`:
```
Running 20s test @ http://127.0.0.1:8082
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   401.15us  313.66us  20.96ms   88.53%
    Req/Sec    63.49k     2.98k   72.37k    69.12%
  5054358 requests in 20.01s, 424.18MB read
Requests/sec: 252620.14
Transfer/sec:     21.20MB
```

**Comment by asonix** [comment]
interestingly, it seems tokio's `yield_now` is actually `spin_loop` hint: https://github.com/tokio-rs/tokio/blob/ac1ae2cfbcc1811d34b2c7da2bf7a80005d94729/tokio/src/loom/std/mod.rs#L100

**Comment by Noah-Kennedy** [comment]
First off, this isn't a terribly meaningful benchmark. Localhost networking is, for various reasons, not usable for benchmarking because it hits very different kernel paths and has a very different core set of assumptions about what performs "well" than normal networking over a LAN or the public internet does. Serving minuscule responses with no underlying business logic also doesn't help much.

That said, I'm not quite sure why this is causing a regression here. For what we are doing with our parking, a spin loop is probably going to be better on a lot of systems as this is being used for CAS operations primarily. Could you provide me with more details, such as the number of cores in use here for tokio?

**Comment by zhzhsx** [comment]
Thank you for the ideas. I run the benchmark again in slightly different setup. The QPS difference between two cases is very small and seems trivial now, although QPS in case of `std::thread::yield_now` is always slighty higher in multiple runs of benchmark. 

Details of benchmark:
Environment:
* two virtual machines of instance type `ecs.g7.xlarge` on aliyun, each with 4core 16GiB, http server on one machine and wrk on the other
* CPU Model Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
* bandwith between two instances: 10Gbps
* os: linux with kernel 5.10 (custom distribution based on centos 8)
* tokio use all 4 cores by default

output in case of `std::thread::yield_now()`:
```
wrk -t4 -c100 -d20s http://172.16.0.191:8082
Running 20s test @ http://172.16.0.191:8082
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   206.87us   56.98us   3.76ms   79.87%
    Req/Sec   117.59k     5.99k  199.42k    80.17%
  9383944 requests in 20.10s, 787.53MB read
Requests/sec: 466877.22
Transfer/sec:     39.18MB
```
output in case of `loom::thread::yield_now()`(`std::hint::spin_loop(); `):
```
Running 20s test @ http://172.16.0.191:8082
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   208.57us   60.73us   5.06ms   81.42%
    Req/Sec   116.78k     6.08k  226.98k    79.40%
  9305689 requests in 20.10s, 780.96MB read
Requests/sec: 462979.92
Transfer/sec:     38.85MB
```

**Comment by Noah-Kennedy** [comment]
Thanks @zhzhsx!

I'm gonna dig into this a little later tomorrow.

**Comment by Noah-Kennedy** [comment]
My guess here is that in the original benchmark, `wrk` was contending with tokio for CPU time, which would explain why the spin loop caused a regression, as we were no longer nicely yielding back to the kernel (note that this should probably be irrelevant in real-world use cases generally).

As far as the second benchmark is concerned, those results are so far within margin of error that they are effectively identical.
