### ISSUE TITLE
tokio-stream chunks_timeout only works in a tokio runtime context

### ISSUE THREAD

**Issue by makroiss** [tokio-rs/tokio#5031]
**Version**
tokio-stream 0.1.10

**Description**

`ChunkTimeout::new` calls `tokio::time::sleep` ([see code](https://github.com/tokio-rs/tokio/blob/master/tokio-stream/src/stream_ext/chunks_timeout.rs#L30)) which can only be called in a tokio runtime context. This is undesirable as constructing the stream is often done outside a runtime. It should be possible to change `deadline` to `Option` and initialize it with `None` instead. The call to `sleep` is only used to generate a default value, but the actual deadline is not used in `poll`, instead it is overwritten ([see code](https://github.com/tokio-rs/tokio/blob/master/tokio-stream/src/stream_ext/chunks_timeout.rs#L48)).  

I tried this code:

```
use std::time::Duration;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tokio_stream::StreamExt;

fn main() {
  let (sender, receiver) = mpsc::channel(8);
  let receiver = ReceiverStream::new(receiver).chunks_timeout(4, Duration::from_millis(10));
  drop(sender);
  drop(receiver);
}
```

I expected to see this happen:

Run without crashing.

Instead, this happened:

```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', third_party/rust/tokio/v1/src/runtime/context.rs:54:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: tokio::runtime::context::time_handle
   6: tokio::time::driver::sleep::sleep
   7: tokio_stream::stream_ext::StreamExt::chunks_timeout
```

**Comment by Darksonn** [comment]
Ah, yes, it would be nice to fix that.
