### ISSUE TITLE
Question about error starting nested runtime

### ISSUE THREAD

**Issue by GOVYANSONG** [tokio-rs/tokio#5035]
I have read about this particular error in other blog posts. But still I want to share my use case for some brain storming. Assume following code snippet:

#[tokio::main]
async fn main()
{
   eprintln!("hello world");
   async-fn.await?; // <----this line of interest
}

i tried to wrap the async.fn.await in follow code and got reported error:
      tokio::runtime::Handle::currenthandle().block_on(async { async-fn.await?; })

is there a way in tokio to propagate the surrounding context/runtime in a way that the above scenario is possible?

**Comment by GOVYANSONG** [comment]
i switched to async_std::task::block_on instead for my purpose:

async_std::task::block_on(async {
            eprintln!("blocking");
            handle.close();
            signals_task.await.unwrap();
        });

**Comment by Noah-Kennedy** [comment]
Why are you using block_on if you are already in a runtime context?

**Comment by GOVYANSONG** [comment]
I would like to use a golang style defer macro to wrap certain logic that can be run once exits surrounding closure e.g. a block, a function etc. the logic for the defer only allows FnOnce which only has sync fn signature. rust compiler complained about await not within async. to work around this, i needed to inject a blocking.

**Comment by Noah-Kennedy** [comment]
Ah, so like scopeguard, but in this case with async code. This isn't a problem which has any good solutions right now. There is discussion right now around eventually getting an `AsyncDrop` trait to allow for async drop implementations, but I am doubtful that this will ever be implemented.

I can't think of a non-terrible way to do this. Spawning an inner runtime to do the blocking (in the case of tokio you'd need to spawn a temp thread for the "inner" runtime) technically works, but is going to be pretty expensive for what you are doing and also has the issue that you are going to be blocking a worker the entire time that you spawn the inner runtime and run the destructor, which, in the case of async code, could be a while. I could potentially see this causing a lot of valid-looking user code to deadlock if that code assumed that other tasks on the runtime were progressing normally, as a `current_thread` runtime would never progress any tasks while the inner runtime was operating.

**Comment by Darksonn** [comment]
Having a runtime inside of a runtime _requires_ use of `block_in_place`. Otherwise you are very likely to deadlock. This will also let you use Tokio as the inner runtime.

**Comment by GOVYANSONG** [comment]
thanks everyone for the insightful information. Indeed the combination of block_in_place and nested block_on provide a more robust solution.

**Comment by Noah-Kennedy** [comment]
`block_in_place` is the best solution if you are only running in `multi_thread`. Supporting `current_thread` is the challenge.
