### ISSUE TITLE
tokio::run is not reentrant

### ISSUE THREAD

**Issue by aep** [tokio-rs/tokio#504]
calling tokio::run from within tokio::run will lead to all other futures starving.

for the sake of saving someone else the headache finding the nested run, 
should run panic instead?

at the very least have a warn!("calling tokio::run from inside tokio::run is probably not what you want")

also it would be really nice if we could simulate a specific amount of worker threads in testing before discovering that stuff in production. maybe with an env variable?

**Comment by carllerche** [comment]
Nice find. The intent was that it should panic. The fact that it does not is an error.

**Comment by hawkw** [comment]
@carllerche 

Adding
```rust
tokio_executor::enter().expect("nested tokio::run");
```
or similar to the top of `tokio::run` seems sufficient to make nested calls to `tokio::run` panic, and doesn't break any of the other tests. Is there any reason this wouldn't be an appropriate solution?

**Comment by carllerche** [comment]
It would work for this case...

I kind of want to add `Enter::block_on` as a function and avoid `Future::wait` entirely. If we are going to update `run`, maybe we should just do that?

Up to you.

**Comment by hawkw** [comment]
> I kind of want to add `Enter::block_on` as a function and avoid `Future::wait` entirely. If we are going to update run, maybe we should just do that?

That definitely seems less like "spooky action at a distance" to me. 👍 

There are several other calls to `wait` in similar functions that I think should perhaps be replaced with `enter().block_on(...)` as well.
