### ISSUE TITLE
`broadcast::Receiver` skips some messages when the original receiver isn't used

### ISSUE THREAD

**Issue by AbsohAbsoh** [tokio-rs/tokio#5083]
It seems that when the original receiver created by `broadcast::channel(n);` isn't used (expected dropped) some messages are not picked up by cloned versions of the receiver. 

It is difficult to provide a minimally working example as my use-case was fairly complex, but essentially:
1. Spawn a broadcast channel. 
2. Pass the (clonable) sender to multiple tasks. Those tasks call `.subscribe().recv()` to listen.
3. Send events to the broadcasters. From location A the events were sent, but from location B the events were not sent. Both locations occur on the same sender instance, but one was more deeply nested than the other. 

I'm not entirely sure if this my misuse of the broadcaster or a bug, but all I changed was consuming the original receiver (rather than letting it drop out of function scope) and it started receiving the missing events.

**Comment by Darksonn** [comment]
Receivers don't receive messages from before they were created. Other than that, are you properly checking for lagged errors?

**Comment by AbsohAbsoh** [comment]
In my case the cloned receivers were guaranteed to spawn before any messages were sent. The receivers were not receiving any message, error or otherwise, and the sender was returning `Ok(1)` though I'm not sure if that is relevant.

**Comment by Darksonn** [comment]
My guess is that it's probably some sort of misuse, but if you can create a minimal reproducible example with the issue, I would be able to consider it further.
