### ISSUE TITLE
Support blocking_xx_timeout style function for bounded channel

### ISSUE THREAD

**Issue by chenyuanrun** [tokio-rs/tokio#5084]
**Is your feature request related to a problem? Please describe.**
I need to send message from a sync runtime to tokio runtime, and don't want to block forever for sending this message while the channel is full. (And I don't want to use unbounded channel and handle capacity myself by the way.)

**Describe the solution you'd like**
Support those function for mpsc bounded channel:
- blocking_send_timeout
- blocking_reserve_timeout
- blocking_recv_timeout

**Describe alternatives you've considered**
Any notification mechanism from tokio runtime to my sync runtime while the channel is not full.

**Additional context**
No.

**Comment by Darksonn** [comment]
You can do this by storing a `tokio::runtime::Handle` and calling `handle.block_on(tokio::time::timeout(chan.recv(), duration))`

**Comment by chenyuanrun** [comment]
> You can do this by storing a `tokio::runtime::Handle` and calling `handle.block_on(tokio::time::timeout(chan.recv(), duration))`

That would add a HUGE overhead which is not possible for me. I would like not to spawn tasks and allocate additional memory just for sending/recving a single message.

**Comment by Darksonn** [comment]
The code I posted does not spawn tasks, nor does it allocate memory.

**Comment by chenyuanrun** [comment]
> The code I posted does not spawn tasks, nor does it allocate memory.

Thanks! I will do what you suggested for the moment, and I am still looking forward to have this feature in tokio in the future........

**Comment by agourlay** [comment]
Thank you for the work-around!

I just wanted to add a clarification as the `timeout` fails if you do not run within a async. block.

```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
```

Here is the full snipped when you just have the runtime handle to work with.

```rust
// sync. environment
let received = handle.block_on(async {
  tokio::time::timeout(timeout, chan.recv()).await
});
```
