### ISSUE TITLE
Some small problems of `Wheel` implementation

### ISSUE THREAD

**Issue by cjwcommuny** [tokio-rs/tokio#5085]
1. The comment of `runtime::time::wheel::Wheel` needs update. Currently it states:

> The structure is generic over `T: Stack`

but `Wheel` actually doesn't have any generic type parameters.

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L12-L24

---

2. There is some code duplication between `tokio::runtime::time::wheel::Wheel` and `tokio_util::time::wheel::Wheel<T>`, which needs cleanup.

e.g.

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio-util/src/time/wheel/mod.rs#L24-L39

and 

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L24-L42

---

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L193-L201

and 

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio-util/src/time/wheel/mod.rs#L176-L184

---

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L212-L225

and

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio-util/src/time/wheel/mod.rs#L189-L202

---

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L266-L277

and

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio-util/src/time/wheel/mod.rs#L230-L241

---

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio/src/runtime/time/wheel/mod.rs#L308-L359

and 

https://github.com/tokio-rs/tokio/blob/992a16812258bae5192a997484ada046a88a6425/tokio-util/src/time/wheel/mod.rs#L264-L315

**Comment by cjwcommuny** [comment]
Possible solution: move the timer wheel implementation to a independent crate

**Comment by Darksonn** [comment]
Well, maybe.
