### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by MathieuDutSik** [tokio-rs/tokio#5110]
The pages [RwLockWriteGuard](https://docs.rs/tokio/0.2.22/tokio/sync/struct.RwLockWriteGuard.html)
and [RwLockReadGuard](https://docs.rs/tokio/0.2.22/tokio/sync/struct.RwLockReadGuard.html) list the traits **Access** and **DynAccess**. However, those traits do not appear to exist and anyway there is no implementation for them in the source code of tokio.

**Comment by Darksonn** [comment]
That seems like some sort of bug in rustdoc. However, considering that the linked docs are so old, and that the newest docs do not list those traits, this has probably already been fixed a long time ago.

**Comment by MathieuDutSik** [comment]
Yes, I had not realized that google in its first choice was pointing to this very old version. Feels like a bug at google actually.
