### ISSUE TITLE
Ability to change backpressure boundary in `Framed`

### ISSUE THREAD

**Issue by crusader-mike** [tokio-rs/tokio#5123]
**Is your feature request related to a problem? Please describe.**
I am using `Framed<TcpStream, ...>` and would like to be able to change backpressure boundary (which is currently hardcoded to 8kb). See [this line](https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/codec/framed_impl.rs#L28).

Two questions on related subject:
- is there any point adding buffering between `Framed` and `TcpStream` (e.g. `Framed<BufStream<TcpStream>>`)? (I suspect no, since `Framed` has it's own r/w buffers that can be made to reserve desired space)
- is there any downside in increasing `Framed` read buffer capacity? default value of 8kb looks pretty small nowadays and leads to too many syscalls (per MB transferred)

**Describe the solution you'd like**
A simple `Framed::set_backpressure_boundary()` function will do...

**Describe alternatives you've considered**
The only alternative I see is to copy `Framed` source code to my project.

**Comment by Darksonn** [comment]
Adding an option to change this seems reasonable. I don't see any reason to combine with a `BufReader`.

**Comment by crusader-mike** [comment]
@Darksonn Any idea when this feature will be added? I kind of need it in my project right now... :-)

**Comment by Darksonn** [comment]
If you submit a PR, then we can have it added quite quickly.

**Comment by crusader-mike** [comment]
@Darksonn Done. See #5124

**Comment by crusader-mike** [comment]
@Darksonn Any idea when next `tokio-utils` release (hopefully with this change) is going to happen?

**Comment by Darksonn** [comment]
It happens whenever I get around to making the release. I've wanted to make one soon.
