### ISSUE TITLE
Error on making client sync call with hyper

### ISSUE THREAD

**Issue by madmaxio** [tokio-rs/tokio#514]
I'm trying to block client call with block_on_all and get data back, without runtime. Client panics with error, please check this repo https://github.com/madmaxio/hyper-cases - start the server, after start the client.

> panicked at 'called Result::unwrap() on an Err value: Error { kind: Execute, cause: None }', libcore\result.rs:945:5

https://github.com/hyperium/hyper/issues/1615

**Comment by tobz** [comment]
Per @seanmonstar on the linked hyper issue:

> I tried out your code, and true enough, using current_thread::block_on_all(fut) does not work. It seems that contrary to what the tokio docs say, calling tokio::spawn from inside appears to be failing.

Sounds like a bug with spawning inside of `current_thread`.

/cc @carllerche

**Comment by seanmonstar** [comment]
It's not an issue with the `current_thread` *Runtime*, as I've successfully used that with no problem. It might be that reaching into `tokio::executor::current_thread` is different that `tokio::runtime::current_thread`, but I don't know all the details.

**Comment by tobz** [comment]
Yeah, fair enough.  Just trying to whittle down the scope of the problem here for prioritization. 👍

**Comment by carllerche** [comment]
Yes, `tokio::executor::current_thread` should not be used by the end application. It is *just* the raw task executor and is used as a building block for `tokio::runtime::current_thread`. The `tokio::executor::current_thread` module will be deprecated & hidden from docs soon.

**Comment by madmaxio** [comment]
So this one should be used https://tokio-rs.github.io/tokio/tokio/runtime/struct.Runtime.html#method.block_on_all ?
