### ISSUE TITLE
Export metrics about the blocking thread pool

### ISSUE THREAD

**Issue by duarten** [tokio-rs/tokio#5156]
**Is your feature request related to a problem? Please describe.**

I'd like to have insight into how many threads are currently created in the blocking thread pool and what the main queue length is.

**Describe the solution you'd like**

These metrics coul be exported as tokio-metrics or there could be some API to fetch their values.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Darksonn** [comment]
This sounds reasonable.
