### ISSUE TITLE
UdpSocket missing poll_read, poll_write methods.

### ISSUE THREAD

**Issue by canndrew** [tokio-rs/tokio#516]
I'm trying to port a library from `tokio-core` to the newer `tokio`. I've noticed that these methods are now gone. Is there a reason for this? They were kinda useful to me.

**Comment by tobz** [comment]
It looks like these have been replaced by [poll_recv](https://docs.rs/tokio/0.1.7/tokio/net/struct.UdpSocket.html#method.poll_recv) and [poll_send](https://docs.rs/tokio/0.1.7/tokio/net/struct.UdpSocket.html#method.poll_send).

**Comment by carllerche** [comment]
For TcpStream, those were renamed [`poll_read_ready`](https://docs.rs/tokio/0.1.7/tokio/net/struct.TcpStream.html#method.poll_read_ready). This was done, in part, due to the naming confusion.

It would be fine to bring them back on `UdpSocket` using the same name as `TcpStream`.

**Comment by tobz** [comment]
Is it accurate to say that, for `TcpStream`, `poll_ready_ready` + `read` is functionally equivalent to `poll_read`/`read_buf`? Just trying to grasp what it would mean to provide equivalency.

For example, if `poll_read` in `UdpSocket` is equivalent to `poll_read` in `TcpStream`, then wouldn't having the ability to _only_ poll in `UdpSocket` invite having a matching `read` or `write`?

**Comment by canndrew** [comment]
I've made a PR for this here: https://github.com/tokio-rs/tokio/pull/522

Bikeshed: should the new methods maybe be called `poll_recv_ready` and `poll_send_ready` instead?

**Comment by tobz** [comment]
I think `recv`/`send` make sense over `read`/`write`, yeah.

**Comment by carllerche** [comment]
As a counter point, `poll_read_ready` and `poll_write_ready` directly correlate w/ Mio terminology around read ready / write ready.
