### ISSUE TITLE
Port to `windows-sys`

### ISSUE THREAD

**Issue by kennykerr** [tokio-rs/tokio#5201]
I noticed that all of the `tokio` dependencies have already made the switch to `windows-sys`, so I thought I'd take a stab at porting `tokio` itself just to confirm that there aren't any gaps. 

https://github.com/kennykerr/tokio/pull/1/files

All tests pass as far as I can tell. There are some doc dependencies on `winapi` which I'm not too sure about, otherwise I'd submit a PR. Anyway, just thought I'd point you to my port in case someone wants to pursue it further.

**Comment by Darksonn** [comment]
Considering that all of our dependencies have switched, I think it is reasonable that we switch too.

**Comment by davidbarsky** [comment]
Speaking not as a reviewer, but instead a consumer of Tokio, `windows-sys` is moving to rust's not-yet-stabilized `raw-dylib`. This is particularly impactful for my employer, as vendoring `windows-sys` requires stripping out all the `#[link]` arguments for complicated, Buck-related reasons. Would it be possible to have a feature hidden behind `tokio_unstable` that breaks MSRV to use a version of `windows-sys` that uses `raw-dylib`?

(I'm genuinely unsure whether `rustflags` can influence dependency resolution, and if it can, whether it is a good idea from a maintenance perspective.)

**Comment by kennykerr** [comment]
`raw-dylib` support is modeled after `tokio_unstable` and is offered via the `windows_raw_dylib` flag. 

https://github.com/microsoft/windows-rs/pull/2164

**Comment by davidbarsky** [comment]
I didn't realize that you were the one responsible for that change! Thanks so much for doing that. `raw_dylib` support in `windows-sys` is going to make vendoring `windows-sys` a lot a _lot_ easier.

**Comment by Darksonn** [comment]
> Would it be possible to have a feature hidden behind tokio_unstable that breaks MSRV to use a version of windows-sys that uses raw-dylib?

If windows-sys plans to unconditionally use features that require a very recent MSRV, then that's something we should be very aware of when deciding whether we should use it. But it sounds like this is not the case?

**Comment by kennykerr** [comment]
Right, this will continue to be an opt-in for `windows-sys` via the `windows_raw_dylib` flag for the foreseeable future to avoid requiring a major MSRV bump.

**Comment by kennykerr** [comment]
I went ahead and ported the examples and docs as well. Here's a PR: #5204 

Feel free to close if you would prefer to manage the port yourself. 😊
