### ISSUE TITLE
`TcpStream::try_io` does not handle multiple interests

### ISSUE THREAD

**Issue by satakuma** [tokio-rs/tokio#5214]
**Version**
tokio v1.22.0

**Platform**
Linux 6.0.8-arch1-1

**Description**

I noticed that `TcpStream` and other types from `tokio::net` with a `try_io` method do not work properly with multiple interests.
Consider the following code:

```rust
use std::error::Error;
use tokio::io::{AsyncWriteExt, Interest};
use tokio::net::{TcpListener, TcpStream};

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let listener = TcpListener::bind("127.0.0.1:8080").await?;

    tokio::spawn(async move {
        let mut stream = TcpStream::connect("127.0.0.1:8080").await?;
        stream.write_all(b"some data from the client").await
    });

    let (stream, _) = listener.accept().await?;
    loop {
        let ev = stream
            .ready(Interest::READABLE | Interest::WRITABLE)
            .await?;
        assert!(ev.is_readable() || ev.is_writable());

        let r = stream.try_io(Interest::READABLE | Interest::WRITABLE, || {
            println!("brrr performing io manually");
            Ok(())
        });
        if r.is_ok() {
            break;
        }
    }

    Ok(())
}
```

I expected this code to eventually call my closure and exit. Instead, this program runs forever.
If I replace `Interest::READABLE | Interest::WRITABLE` with `Interest::READABLE` the code works as expected.

[`try_io` docs](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.try_io) do not warn about this behavior. If this is intended, I would expect an appropriate mention in the documentation.

I noticed this issue while trying to fix #5098. In my opinion, both issues are related to the `tokio::io::Interest` → `tokio::io::Ready` conversion. If this behavior is indeed unintended, I can submit a PR fixing both issues.

**Comment by satakuma** [comment]
I am not aware of such operation. Probably every use of `try_io` with multiple interests should be refactored to sequentially call `try_io` with a single interest. Nevertheless, based on the documentation, which clearly states that the closure will be called *if and only if* the socket is ready, I find this behavior unexpected.

`try_io` documentation also says that the closure should return `WouldBlock` if the socket was not ready. Considering this, I come to a conclusion, that accepting multiple interests will add unnecessary ambiguity what it means for a socket to be “ready” in terms of multiple interests. If being ready means satisfying at least one interest, it might be confusing how readiness state should be cleared if the closure returns `WouldBlock`.

I think it would be best if the docs stated that using `try_io` with multiple interests will never call the closure, or at least that the behavior is undefined.

**Comment by Darksonn** [comment]
I would be happy to see a PR that updates the documentation on this topic.

> Probably every use of `try_io` with multiple interests should be refactored to sequentially call `try_io` with a single interest.

The `try_io` method shouldn't attempt to make more than a single IO operation on the socket, so it seems to me that such a use of `try_io` not only _could_ be refactored, but _should_ be refactored for it to be correct.
