### ISSUE TITLE
perf - io::Handle::is_shutdown acquires a global lock on every IO op

### ISSUE THREAD

**Issue by arielb1** [tokio-rs/tokio#5227]
**Version**

Tokio 1.21.2

**Platform**

Tested on Linux on AWS c7g (ARM)

**Description**

The function io::Handle::is_shutdown read-acquires a global lock every time it is called

https://github.com/tokio-rs/tokio/blob/fc9518b62714daac9a38b46c698b94ac5d5b1ca2/tokio/src/runtime/io/mod.rs#L44-57

https://github.com/tokio-rs/tokio/blob/fc9518b62714daac9a38b46c698b94ac5d5b1ca2/tokio/src/runtime/io/mod.rs#L285-L287

That function is called from `poll_ready`, which runs on every IO operation

https://github.com/tokio-rs/tokio/blob/a051ed726f3b99b077e8c9ef8ef1df2ab2943213/tokio/src/runtime/io/registration.rs#L142-L157

In my application's profiles, this results in a few % of CPU usage being lost in cache-line ping pong (2% with 3 cores, more with more).

**Comment by Darksonn** [comment]
We can make this an atomic to make it cheaper to read.

**Comment by carllerche** [comment]
We could also get rid of that check entirely if we add a "shutdown" bit to I/O readiness. In that case, when the I/O driver shuts down, it would wake every outstanding I/O resource w/ "shutdown" readiness.

**Comment by Darksonn** [comment]
Also, I think that the timer driver has a similar issue.

**Comment by hawkw** [comment]
Storing a bit in the readiness field seems significantly nicer, as we wouldn't have to add an entire additional `AtomicBool`...
