### ISSUE TITLE
Add clippy let_underscore_future for JoinHandle

### ISSUE THREAD

**Issue by Stargateur** [tokio-rs/tokio#5234]
A full description of the problem is available on https://github.com/rust-lang/rust-clippy/issues/9932.

A solution was proposed by https://github.com/rust-lang/rust-clippy/issues/9932#issuecomment-1326697596.

> Maybe the answer would be to annotate JoinHandle itself with `#[allow(clippy::let_underscore_future)]`?

**Describe alternatives you've considered**
Fix the problem in clippy.

**Additional context**
The new lint of clippy is useful but hurt very rare case where a future doesn't need to be polled. I think the real problem lie in the exception of spawned task. Maybe there is other future in tokio that doesn't need to be polled and should also have `#[allow(clippy::let_underscore_future)]`

**Comment by taiki-e** [comment]
> > Maybe the answer would be to annotate JoinHandle itself with `#[allow(clippy::let_underscore_future)]`?

Um, would this suppress the clippy warning to downstream? If true, that seems to be the undocumented (and probably [untested](https://github.com/rust-lang/rust-clippy/pull/9760/files)) configuration of this lint.
https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_future

**Comment by taiki-e** [comment]
As mentioned in https://github.com/rust-lang/rust-clippy/issues/9932#issuecomment-1327990360, the proposed way does not seem to work in practice.

There is no way to address this on our end, so I will close this for now.

**Comment by Stargateur** [comment]
my bad I didn't check
