### ISSUE TITLE
Many allocations contradicting the zero-cost claim

### ISSUE THREAD

**Issue by FooBarWidget** [tokio-rs/tokio#527]
I'm investigating the performance characteristics of Hyper, and thus also Tokio (which Hyper depends on). I've found that every HTTP request results in many malloc() calls, a significant portion of which come from tokio-executor.

After some digging, it seems Tokio uses Box, Rc and Arc in various places, more than I would expect. Some of it is even enforced by the interface, for example:

~~~rust
pub trait Executor {
   fn spawn(&mut self, future: Box<Future<Item = (), Error = ()> + Send>)
            -> Result<(), SpawnError>;
~~~

I'm not that familiar with Tokio yet, but such widespread calls to malloc() seems to go against Tokio's claim to provide zero-cost abstractions.

Can you shed some light on this situation? Are there any plans to reduce the amount of allocations and to improve performance?

**Comment by carllerche** [comment]
"Zero cost abstraction" does not mean that the code has no cost. It means that the _abstraction_ imposes no additional cost over writing the equivalent functionality by hand.

The fundamental abstraction in Tokio is the asynchronous model and how it is managed (via futures). These futures, as an abstraction, do not impose any additional cost over writing the state machines by hand.

You can also implement future executors that do not require allocation. However, it would implement [this](https://docs.rs/futures/0.1.23/futures/future/trait.Executor.html) trait. I have been meaning to move that trait into `tokio-executor` under the name `TypedExecutor` but have not.

Tokio, also, offers additional conveniences. These conveniences are optional and are not part of the fundamental abstraction. `tokio::spawn` is one of those conveniences.

Tokio itself does not currently provide a typed runtime (to avoid runtime allocations in the executor) as nobody has asked for it yet or reached a point where the allocations in the executor were the bottleneck, but the abstraction does not prohibit this and we could talk about adding such a runtime.

**Comment by seanmonstar** [comment]
It's also worth noting that hyper performs at the top of the TechEmpower benchmarks, and these allocations aren't causing a problem.
