### ISSUE TITLE
Will Tokio Support Priority Scheduling in the Future?

### ISSUE THREAD

**Issue by silence-coding** [tokio-rs/tokio#5277]
Will Tokio Support Priority Scheduling in the Future?

**Comment by Noah-Kennedy** [comment]
I think priority scheduling would be very useful to have. It might be tricky to figure out though in the context of something like work-stealing.

**Comment by silence-coding** [comment]
> I think priority scheduling would be very useful to have. It might be tricky to figure out though in the context of something like work-stealing.

In simple implementation, would it be feasible to simply assign more ticks to high-priority tasks?

**Comment by Darksonn** [comment]
Unfortunately, it's not so simple to actually implement.

**Comment by Noah-Kennedy** [comment]
Yes, but it certainly can be done. If someone were to propose a good system for _opting into_ this, I'd be quite interested.

**Comment by silence-coding** [comment]
Unfortunately, I don't know the logic of this, and I hope I'll have time to read it carefully later. This should be a nice feature for tokio.

**Comment by barafael** [comment]
Can this be closed?
