### ISSUE TITLE
`tokio::sync::Mutex` appears to be acquired multiple times without being released

### ISSUE THREAD

**Issue by bk2204** [tokio-rs/tokio#5285]
**Version**

```
% cargo tree | grep tokio
└── tokio v1.23.0
    └── tokio-macros v1.8.2 (proc-macro)
```

**Platform**
`Linux tapette 6.0.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.6-2 (2022-11-01) x86_64 GNU/Linux`

Debian amd64/sid (unstable)

However, the behaviour is also seen (and seen more rapidly) on FreeBSD 13.  I've tested using Vagrant's `generic/freebsd13` box.

**Description**
It appears that in some cases, a Mutex can be acquired multiple times without having been released.  When running the server in one tmux pane as `rm -fr /tmp/socket && target/release/lock-test server` and the client in another as `target/release/lock-test client`, the server sometimes prints an output like this:

```
about to acquire lock
lock acquired
about to acquire lock
lock acquired
```
without printing any intervening message about dropping the lock.

This leads me to believe that the lock has been acquired multiple times without being dropped, which is not what I expected.  Note that when this happens, both the client and the server will panic: the client because the server hung up, and the server because one caller to `read` has read data that was intended to be read by another caller in order.

Note that compiling with `--release` is helpful to get the best performance.  On Linux, it appears to crash after a few seconds at most.  It appears to take substantially fewer iterations on FreeBSD.

It's completely possible that I'm just holding this wrong somehow, in which case I would be very grateful to know how I should make multiple read calls on the same `OwnedReadHalf` without anyone else reading at the same time.  If so, I apologize for the noise.  It seems extremely unlikely to me that Tokio would be broken in this way, but I can't think of any other possibility here from the output.

I tried this code:

```
use std::sync::Arc;
use std::time::Duration;
use tokio::select;
use tokio::sync::Mutex;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::unix::{OwnedReadHalf, OwnedWriteHalf};

struct Message {
    // The size is the length of the data plus the length of the id and next fields.  That is,
    // data.len() + 8.
    size: u32,
    id: u32,
    next: u32,
    data: Vec<u8>,
}

struct Server {
    inp: Arc<Mutex<OwnedReadHalf>>,
    out: Arc<Mutex<OwnedWriteHalf>>,
}

impl Server {
    async fn run(&self) {
        loop {
            let mut counter = 0;
            let mut timer = tokio::time::interval(Duration::from_millis(10));
            select! {
                _ = timer.tick() => {
                    counter += 1;
                    if (counter % 100) == 0 {
                        eprintln!("tick");
                    }
                }
                msg = self.read() => {
                    let out = self.out.clone();
                    tokio::spawn(async move {
                        Self::write(out, msg).await;
                    });
                }
            }
        }
    }

    async fn write(out: Arc<Mutex<OwnedWriteHalf>>, msg: Message) {
        let mut g = out.lock().await;
        g.write_all(&8u32.to_le_bytes()).await.unwrap();
        g.write_all(&msg.id.to_le_bytes()).await.unwrap();
        g.write_all(&0u32.to_le_bytes()).await.unwrap();
    }

    async fn read(&self) -> Message {
        eprintln!("about to acquire lock");
        let mut g = self.inp.lock().await;
        eprintln!("lock acquired");
        let mut buf = vec![0; 12];
        g.read_exact(&mut buf).await.unwrap();
        let size = u32::from_le_bytes(buf[0..4].try_into().unwrap());
        let id = u32::from_le_bytes(buf[4..8].try_into().unwrap());
        let next = u32::from_le_bytes(buf[8..12].try_into().unwrap());
        if size < 4 || size > 0x00ffffff {
            panic!("invalid data: {:08x}", size);
        }
        buf.resize((size - 8) as usize, 0);
        g.read_exact(&mut buf).await.unwrap();
        eprintln!("about to drop lock");
        std::mem::drop(g);
        eprintln!("lock dropped");
        Message {
            size,
            id,
            next,
            data: buf,
        }
    }
}

#[tokio::main]
async fn server() {
    // This is insecure and should only be run on a trusted system.
    let listener = tokio::net::UnixListener::bind("/tmp/socket").unwrap();
    loop {
        if let Ok((stream, _addr)) = listener.accept().await {
            let (rd, wr) = stream.into_split();
            let serv = Server{ inp: Arc::new(Mutex::new(rd)), out: Arc::new(Mutex::new(wr)) };
            serv.run().await;
        }
    }
}

#[tokio::main]
async fn client() {
    // This, too, is insecure and should only be run on a trusted system.
    let sock = tokio::net::UnixStream::connect("/tmp/socket").await.unwrap();
    let (rd, wr) = sock.into_split();
    let client = Client{};
    client.run(rd, wr).await;
}

struct Client {
}

impl Client {
    async fn run(&self, inp: OwnedReadHalf, out: OwnedWriteHalf) {
        tokio::spawn(async move {
            let mut inp = inp;
            loop {
                let mut buf = [0u8; 12];
                inp.read_exact(&mut buf).await.unwrap();
            }
        });
        let mut val = false;
        let mut id = 0u32;
        let mut out = out;
        loop {
            let buf = if val {
                vec![0xffu8; 16384]
            } else {
                vec![]
            };
            let size: u32 = buf.len() as u32 + 8;
            out.write_all(&size.to_le_bytes()).await.unwrap();
            out.write_all(&id.to_le_bytes()).await.unwrap();
            out.write_all(&1234u32.to_le_bytes()).await.unwrap();
            val = !val;
            id += 1;
            out.write_all(&buf).await.unwrap();
        }
    }
}

fn main() {
    let arg = std::env::args().nth(1).unwrap();
    if arg == "client" {
        client();
    } else {
        server();
    }
}
```

I apologize for the length of the code, but this mimics a different tool that I have and mimicking it as much as possible allowed me to write a better testcase.

I expected to see this happen:

Blocks of messages from the server like this:

```
about to acquire lock
lock acquired
about to drop lock
lock dropped
```

And no panic.  That would indicate that the operations while `g` is held are excluded from happening more than once concurrently, which is what I expected.

Instead, this happened:

A message is printed twice in a row that the lock is acquired without any intervening message that the lock has been dropped.

I take it to mean that the operations under the lock within `read` are happening concurrently, which is unexpected.

To explain the code more succinctly, the packets sent contain a size field of the following two u32s and the additional data.  The size field must be less than 2^24.  The client alternates between sending no additional data and 16384 bytes of 0xff.  When the code panics, the extra data, 0xffffffff, is read out of order as the size field, which is not allowed.

As an additional note, I first saw this on FreeBSD (and my CI indicates that it may also frequently happen on macOS, although since the symptom in my code is a hang, it's hard to be certain).  From my testing with other code, it appears that this more quickly happens on FreeBSD because FreeBSD will read in blocks of 8192 bytes.  Thus, the first 12 bytes are read, and then a read of 8180 (the rest of the 8192-byte block).  Then, the read of the next 8192-byte block blocks and Tokio switches to another task, one of which happens to pick up another `self.read` call.

**Comment by Darksonn** [comment]
The problem is your `select!`, which cancels the `read` call when a timer triggers. Cancelling a future makes it stop running at the current await, running the destructors of local variables at that point. If you use a wrapper like this that prints in the destructor, then you should see the prints about it getting dropped:
```Rust
use tokio::sync::MutexGuard;

pub struct PrintGuard<'a, T> {
    guard: MutexGuard<'a, T>,
}

impl<'a, T> PrintGuard<'a, T> {
    pub fn new(guard: MutexGuard<'a, T>) -> Self {
        println!("new guard");
        Self { guard }
    }
}

impl<'a, T> Drop for PrintGuard<'a, T> {
    fn drop(&mut self) {
        println!("drop guard");
    }
}

impl<'a, T> std::ops::Deref for PrintGuard<'a, T> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.guard
    }
}
impl<'a, T> std::ops::DerefMut for PrintGuard<'a, T> {
    fn deref_mut(&mut self) -> &mut T {
        &mut self.guard
    }
}
```
More generally, the issue is that your `read` call is not cancellation safe. See the documentation for `tokio::select!` for more info on that.
