### ISSUE TITLE
panic: assertion failed: self.ref_count() > 0

### ISSUE THREAD

**Issue by Noah-Kennedy** [tokio-rs/tokio#5295]
**Version**
Tokio 1.21.2

**Platform**
Linux (kernel 5.15)

**Description**
I am seeing panics here: https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/task/state.rs#L226

I'm not sure what the sequence of events could be which may lead to this. I've only seen this occur a couple of times, so it seems to be pretty rare (lots of instances of this service are running).

I might be able to spend some time looking at this later if need be.

Updates:
- This seems to have happened during a shutdown when the tx half of a mpsc was dropped and wake_rx got called

**Comment by Darksonn** [comment]
Closing as stale. Similar to #6422.
