### ISSUE TITLE
Possible bug in tokio::process::Command

### ISSUE THREAD

**Issue by I60R** [tokio-rs/tokio#5304]
**Version**

tokio = { version = "1.23.0", features = ["full"] }

**Platform**
Linux 160R 5.19.17-2-MANJARO 

**Description**

From documentation of `tokio::process::Command::wait`:

> The stdin handle to the child process, if any, will be closed
> before waiting. This helps avoid deadlock: it ensures that the
> child does not block waiting for input from the parent, while
> the parent waits for the child to exit.

> If the caller wishes to explicitly control when the child's stdin
> handle is closed, they may `.take()` it before calling `.wait()`:

>```rust
> use tokio::io::AsyncWriteExt;
> use tokio::process::Command;
> use std::process::Stdio;
>
> #[tokio::main]
> async fn main() {
>    let mut child = Command::new("cat")
>        .stdin(Stdio::piped())
>        .spawn()
>        .unwrap();
>
>    let mut stdin = child.stdin.take().unwrap();
>    tokio::spawn(async move {
>        // do something with stdin here...
>        stdin.write_all(b"hello world\n").await.unwrap();
>
>        // then drop when finished
>        drop(stdin);
>    });
>
>    // wait for the process to complete
>    let _ = child.wait().await;
>}
>```

But there seems to be something wrong.

I tried this code:

```rust
#[tokio::main]
async fn main() {
    let mut p = tokio::process::Command::new("cat")
        .stdin(std::fs::OpenOptions::new()
            .read(true)
            .open("/dev/tty")
            .expect("cannot open tty")
        )
        .spawn()
        .expect("cannot spawn");

    p.stdin
        .take()
        .expect("cannot get stdin");
}
```

I expected it to execute without panics.

Instead, it panicked with `cannot get stdin` message.

Is it okay for `p.stdin` to be `None` in this case?

**Comment by I60R** [comment]
Okay, `std::process::Command` has exactly the same behavior

**Comment by Darksonn** [comment]
The `stdin` field is only set if stdin is a pipe.
