### ISSUE TITLE
await is panicking acros dlopen boundaries

### ISSUE THREAD

**Issue by tzachshabtay** [tokio-rs/tokio#5311]
**Version**
tokio v1.15.0

**Platform**
Darwin ip-192-168-1-152.ec2.internal 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin

**Description**

I'm writing a web server with a plugin system. I use `dlopen` to load the plugins which implement an async trait. However awaiting in the loaded plugin panics with `there is no reactor running, must be called from the context of a Tokio 1.x runtime`.

I read [this discussion](https://github.com/tokio-rs/tokio/discussions/5299) and I understand this is because Tokio is using TLS (thread local storage) to store the runtime but TLS doesn't work between dlopen boundaries. I also read somewhere that `async-std` doesn't have this issue because they're using a global static.

I'm really hoping Tokio could use a similar solution (or any other solution that will make this use-case work).

Thanks.

**Comment by taiki-e** [comment]
Closing per https://github.com/tokio-rs/tokio/issues/4835#issuecomment-1210670792

Note also that most rust libraries (including tokio and async-std) make no guarantees about the layout of the internal types, so what you think is currently working may in fact only be working by accident. (It depends on how you're using it, though.)
