### ISSUE TITLE
No way to extract an owned `RawFd` from `ChildStdout`

### ISSUE THREAD

**Issue by satakuma** [tokio-rs/tokio#5333]
**Is your feature request related to a problem? Please describe.**
I am trying to implement support for named Unix pipes (#5318) and I am considering adding conversion from types in `tokio::process` which hold a file descriptor to a pipe end. However, I've noticed that currently there is no way to turn `ChildStdout`, `ChildStderr` and `ChildStdin` types into an owned `RawFd`, even though they implement `AsRawFd`.

In this particular case, I can probably hack my way through internally to get the fd, but I think it would be useful to expose such conversion to the public API.

**Describe the solution you'd like**
Add a new method to the `ChildStdout`, analogous to the [from_std](https://docs.rs/tokio/1.23.0/tokio/process/struct.ChildStdout.html#method.from_std) method:
```rust
fn into_std(self) -> Result<std::process::ChildStdout>
```
which would perform conversion from an asynchronous `ChildStdout` to a synchronous one, which in turn implements `IntoRawFd`. Also add similar methods to `ChildStderr` and `ChildStdin` types.

**Describe alternatives you've considered**
Implement `IntoRawFd` to those types directly, but from what I can see tokio does not implement this trait for most types in favor of `into_std`-like methods.

**Comment by Darksonn** [comment]
Generally, the reason that we don't implement `IntoRawFd` is that the operation is fallible. I wouldn't mind adding an `into_fd` method that returns a result.

I would have to think about it when it comes to an `into_std` method. I recall there being some reason for not having that method, but I don't remember what it is.

**Comment by ipetkov** [comment]
@Darksonn pretty much the fallible unwrap IIRC

**Comment by satakuma** [comment]
The `into_std` method was mentioned in #4403, which I failed to notice while opening this issue.
`ChildStd{in,err,out}` are lacking `FromRawFd` impls, so it is impossible to create them from tokio types. New IO safety traits for them also haven't landed yet, see rust-lang/rust#98704.

As I said, I can live without this conversion for now, but the topic of `into_std` methods may appear again once it becomes possible to create std types from raw file descriptors. Feel free to close this issue.
