### ISSUE TITLE
Tokio runtime hangs indefinitely when blocking task is running 

### ISSUE THREAD

**Issue by DASPRiD** [tokio-rs/tokio#5338]
**Version**
Tokio 1.23.0

**Platform**
Linux dasprid-desktop 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

**Description**
When spawning a blocking task and the main function finishes, the program will not terminate until the blocking task is finished. Here is a small reproduction case:

```rust
use std::{thread, time::Duration};

#[tokio::main]
async fn main() {
    tokio::task::spawn_blocking(|| {
        thread::sleep(Duration::from_secs(10));
    });
}
```

This issue was brought up originally in `tokio-graceful-shutdown` https://github.com/Finomnis/tokio-graceful-shutdown/issues/50.

The reproduction case above is of course an overly simplified version. Originally this issue was discovered through the async `lookup_host()` function provided by tokio. Basically the program was instructed to exit and all spawned task were closed, but because `lookup_host()` spawns blocking (and due to network issues was hanging until the 20 second timeout), the program did not exit until that timeout occurred.

The following two examples do exit immediately on the other hand:

```rust
use std::{thread, time::Duration};

fn main() {
    thread::spawn(|| {
        thread::sleep(Duration::from_secs(10));
    });
}
```

```rust
use std::time::Duration;

#[tokio::main]
async fn main() {
    tokio::spawn(async {
        tokio::time::sleep(Duration::from_secs(10)).await;
    });
}
```

Ideally the `#[tokio::main]` macro would have an option to call `Runtime::shutdown_background` on drop or something similar. Maybe @Finomnis can chime in here as well.

**Comment by Finomnis** [comment]
We talked about this issue on discord: https://discord.com/channels/500028886025895936/1059951448894492872
I don't expect discord to be a traceable resource, and I will open another issue here with the findings of our discussion, I just wanted to let you know.

**Comment by Finomnis** [comment]
I've open the following feature request: https://github.com/tokio-rs/tokio/issues/5340

**Comment by Darksonn** [comment]
Per discussion on discord, I'm closing this in favor of #5340.
