### ISSUE TITLE
Inadequately large `Timeout`'s size

### ISSUE THREAD

**Issue by loyd** [tokio-rs/tokio#5348]
**Version**
1.23.1

**Description**
I tried the following code:
```rust
async fn make_request() -> u32 { 42 }

async fn plain() -> u32 {
    make_request().await
}

async fn timeout() -> u32 {
    tokio::time::timeout(std::time::Duration::from_secs(1), make_request()).await.unwrap()
}

fn main() {
    println!("plain:   {}", std::mem::size_of_val(&plain()));   // => 2
    println!("timeout: {}", std::mem::size_of_val(&timeout())); // => 896
}
```

Debug and release builds print the same numbers.

It can affect performance even if `timeout()` is used rarely (e.g. conditionally). For instance, it degraded the performance (~18%) of my DB client until I boxed `Sleep`.

**Comment by w41ter** [comment]
The cache line alignment of `timeout` entry caused it.

**Comment by Darksonn** [comment]
I would be happy to remove the cache padding.
