### ISSUE TITLE
Exposing macro_rules `ready!` in `tokio` or `tokio-util`

### ISSUE THREAD

**Issue by NobodyXu** [tokio-rs/tokio#5363]
While [`std::task::ready!`](https://doc.rust-lang.org/std/task/macro.ready.html) is stablised, many crates cannot use it due to their MSRV.

Thus, I think it would be a good idea for `tokio` or `tokio-util` to expose its internal `ready!` macro_rules given that other crates such as `futures`/`futures-util` also expose `ready!`.

This issue is created based on the suggestion of @Noah-Kennedy from https://github.com/tokio-rs/tokio/pull/5362#discussion_r1063914021

**Comment by Noah-Kennedy** [comment]
Tokio has this already internal to the crate. We could just expose it there.

**Comment by Noah-Kennedy** [comment]
Another point that's worth asking about here is that with it being in rust, how many would benefit from it being in a crate like tokio which has a rolling MSRV?

**Comment by NobodyXu** [comment]
> Another point that's worth asking about here is that with it being in std, how many would benefit from it being in a crate like tokio which has a rolling MSRV?

I guess crates like
 - `hyper` which is going to reach v1.0 pretty soon
 - `h2`, `http-body`, `tower-service` which has already reached v1.0

might benefit as they usually also adopt a MSRV schema similar to tokio and they might also adopt a very conservative one?

P.S. I haven't checked actual MSRV of these crates, but I remember hyper having one.

**Comment by Noah-Kennedy** [comment]
@seanmonstar would this benefit hyper?

**Comment by seanmonstar** [comment]
The macro is super small, and hyper doesn't necessarily need to depend on Tokio, so I'd just keep one vendored in hyper most likely.

**Comment by Noah-Kennedy** [comment]
Yeah, I figured. It's a pretty small macro.

**Comment by Darksonn** [comment]
Maybe it would have made sense before it was added to std, but I don't think there's any reason in doing this now.
