### ISSUE TITLE
LengthDelimitedCodec to support custom length encoding

### ISSUE THREAD

**Issue by EliyahuSternDAI** [tokio-rs/tokio#5383]
**Problem description:**
I've started working on an implementation of ADB client/server with tokio.
ADB protocol defines client messages where [the content length is encoded in ASCII](https://cs.android.com/android/platform/superproject/+/master:packages/modules/adb/OVERVIEW.TXT;l=96).
For instance, a request to get the server version is decoded as the string "000Chost:version", where the 4 first bytes are a hex-ascii decoded length. 

**Suggested solutions:**
Either of the following:
- Introduce a customizable `LengthDecoder` trait that receives the `ByteMut` slice and returns a decoded length. Such decoder will have a builder setter, e.g., `set_length_decoder`, and the default implementation would depend on endieness for compatibility.
- Specifically support hex-ascii length via a builder setter `set_ascii_length`.

**Alternatives**
I can alternatively write my own codec, but I believe this may become useful for other cases as well.

**Comment by Darksonn** [comment]
My initial impression of this is that you should probably just make your own codec.

**Comment by EliyahuSternDAI** [comment]
Maybe I should ¯\_(ツ)_/¯

**Comment by maminrayej** [comment]
Closing as it is better to write a custom codec.
