### ISSUE TITLE
Add greybox fuzz testing using cargo-fuzz

### ISSUE THREAD

**Issue by silvergasp** [tokio-rs/tokio#5391]
**Is your feature request related to a problem? Please describe.**
Tokio currently uses [proptest-rs](https://github.com/proptest-rs/proptest) for some [basic fuzz tests](https://github.com/tokio-rs/tokio/search?l=Rust&q=proptest). However, proptest-rs doesn't support coverage-driven feedback and so it has limited performance when it comes to automatically finding new code-paths (and therefore bugs).

_Black box fuzzing (proptest-rs)_
This approach to fuzzing is considered to be [open-loop](https://en.wikipedia.org/wiki/Control_system#Open-loop_and_closed-loop_control) and **does not** use feedback to improve future results.
```mermaid
flowchart LR
    A[Random Input] --> B[Fuzz Harness]
    B --> A
```
With black-box fuzzing the probability of finding a bug does not change over time.

_Grey box fuzzing (cargo-fuzz/libfuzzer)_
This approach to fuzzing is considered to be [closed-loop](https://en.wikipedia.org/wiki/Control_system#Open-loop_and_closed-loop_control) and **does** use feedback to improve future results.
```mermaid
flowchart LR
    A[Random Input] --> B[Fuzz Harness]
    B --> C[Collect code coverage information]
    C -->  D[Mutate orgional input to maximize coverage] 
    D --> B
```

With greybox fuzzing the probability of finding a bug over time increases.

**Describe the solution you'd like**
- [x] Port existing proptest-rs test harnesses over to use `cargo-fuzz`. https://github.com/silvergasp/tokio/commit/0327538f8eca9702757460a7e12b0b000ff03281
- [x] Enabled continuous fuzz-testing using [oss-fuzz](https://github.com/google/oss-fuzz). OSS-fuzz is a free continuous fuzzing service that is offered to open-source projects. One advantage of this step is that fuzzing is run on a large cluster of servers at no cost. Additionally OSS-fuzz can be configured to use multiple fuzzing engines e.g. libfuzzer, honggfuzz, afl etc. https://github.com/google/oss-fuzz/pull/9480

**Describe alternatives you've considered**
- Keep the original proptest-rs fuzzing harnesses. This is simpler to maintain and doesn't require any changes to tokio.

**Additional context**
 - Examples of where [cargo-fuzz is used in tokio/prost](https://github.com/tokio-rs/prost/tree/master/fuzz)
 - [tokio/prost integration with oss-fuzz](https://github.com/google/oss-fuzz/tree/master/projects/prost)

**Comment by silvergasp** [comment]
To merge, the https://github.com/google/oss-fuzz/pull/9480 PR I'll need a tokio maintainer to review the PR and comment :)

**Comment by silvergasp** [comment]
Also, is security@tokio.rs associated with a google account? To get full access to the oss-fuzz dashboard I'll need to change this to an [email address associated with a google account](https://github.com/google/oss-fuzz/pull/9480/files#diff-a93c209643ca74af7928a3e766c5ab5906e126ed9a7354d48d1c8e5a7e1e27f9R3). You can read about why this is required [here](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication).

**Comment by Darksonn** [comment]
I don't think security@tokio.rs is associated with a Google account. For now, you can use aliceryhl@google.com instead.

**Comment by silvergasp** [comment]
> I don't think [security@tokio.rs](mailto:security@tokio.rs) is associated with a Google account. For now, you can use [aliceryhl@google.com](mailto:aliceryhl@google.com) instead.

Done https://github.com/google/oss-fuzz/pull/9480/files#diff-a93c209643ca74af7928a3e766c5ab5906e126ed9a7354d48d1c8e5a7e1e27f9R3

**Comment by Darksonn** [comment]
Is there anything else that needs to be done here?

**Comment by silvergasp** [comment]
> Is there anything else that needs to be done here?

Nope, this is done, so this issue can be closed. Although I'll likely be chipping away at adding more fuzz tests. As it currently stands, the [code-coverage is pretty low](https://storage.googleapis.com/oss-fuzz-coverage/tokio/reports/20230212/linux/src/tokio/report.html). I'll leave it up to you if you want to keep this issue open to track future fuzz test additions :)
