### ISSUE TITLE
one call tokio::sync::Notify::notify_waiters() can wake two sequential tokio::sync::Notify::notified().await

### ISSUE THREAD

**Issue by Leonqn** [tokio-rs/tokio#5396]
**Version**
1.24.1

**Platform**
Rust playground as well as local macos

**Description**
one call to tokio::sync::Notify::notify_waiters can wake up two(and more) sequential tokio::sync::Notify::notified().await

I tried this code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3a70cbf0ed38d88e0b47c41ba9925c94

I expected to see this happen: "twice notified" won't be printed

Instead, this happened: "twice notified" is printed

**Comment by satakuma** [comment]
It appears that there is a race here: https://github.com/tokio-rs/tokio/blob/c90757f07a1b15d7e26a710003d8e98a83db1ffc/tokio/src/sync/notify.rs#L522-L549

`notify_waiters` wakes futures in batches and releases the lock to avoid deadlocks, but while the lock is released, it is possible to insert new futures from another thread. These new futures will be then notified in one of the later batches. Looks like undesired behavior to me, I can try to fix it.

**Comment by Darksonn** [comment]
This has come up before, but for some reason we never ended up fixing it. We didn't have such a clear-cut reproduction of the race last time, so thank you for that.

**Comment by Darksonn** [comment]
Let's say we have two pending `notified()` futures `fut1` and `fut2` initially, and then we call `notify_waiters` in parallel with the following:

```
let res1 = fut1.poll();
let res2 = fut2.poll();
assert!(res1.is_pending() || res2.is_ready()); // if res1 is ready, then res2 must also be ready
```

Can the assert fail under this change?

**Comment by carllerche** [comment]
As a general rule, "false positive" wakeups are permitted. That said, we probably should clarify `Notify`'s guarantees in the docs.
