### ISSUE TITLE
API for number of active tokio tasks?

### ISSUE THREAD

**Issue by coder3101** [tokio-rs/tokio#5400]
**Is your feature request related to a problem? Please describe.**
I would like to get the count of active running tokio tasks. In python, I can use `len(asyncio.all_tasks())` which returns the unfinished tasks for the current running loop.

**Describe the solution you'd like**
A simple associated function such as `tokio::active_tasks()` which could return the number or as with `asyncio.all_tasks()` return a set of not yet finished Task objects run by the loop.

**Describe alternatives you've considered**
There are debugging tools such as [tokio-rs/console](https://github.com/tokio-rs/console) or tracing which helps achieve the same but they are mainly suited for debugging purpose. Is there a way to get those information in production?

**Additional context**
Originally asked as question on [stackoverflow](https://stackoverflow.com/questions/75248246/how-to-find-number-of-active-tokio-task)

**Comment by Darksonn** [comment]
Adding this to [`tokio::runtime::RuntimeMetrics`][1] sounds like a good idea.

[1]: https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html

**Comment by coder3101** [comment]
When and which version of tokio will include this newly added metric?

**Comment by Darksonn** [comment]
It will be available in 1.29, which will be released about one month from now.
