### ISSUE TITLE
Documentation of tokio::process::Command::arg is misleading

### ISSUE THREAD

**Issue by mTsBucy1** [tokio-rs/tokio#5406]
**Version**
Using tokio 1.24.2, rust 1.67

**Platform**
Windows 10, 64 bit

**Description**
The example of [`tokio::process::Command::arg`](https://docs.rs/tokio/1.24.2/tokio/process/struct.Command.html#method.arg) (and other methods of `Command`) suggests the following code:
```rust
use tokio::process::Command;

let command = Command::new("ls").arg("-l").arg("-a");
```
which naturally extends to
```rust
#[tokio::test]
async fn wontcompile() {
    use tokio::process::Command;

    let command = Command::new("ls").arg("-l").arg("-a");
    command.output();
}
```

This snippet won't compile, however, with the error:
```
error[E0716]: temporary value dropped while borrowed
  --> taumada-rusty-runner\src\lib.rs:80:19
   |
80 |     let command = Command::new("ls").arg("-l").arg("-a");
   |                   ^^^^^^^^^^^^^^^^^^                    - temporary value is freed at the end of this statement
   |                   |
   |                   creates a temporary value which is freed while still in use
81 |     command.output();
   |     ---------------- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
```

**Resolution**
I suggest to either, like [`std::process::Command::arg`](https://doc.rust-lang.org/1.67.0/std/process/struct.Command.html#method.arg), add a `.spawn().unwrap()`, or the remove the let binding named `command`.

**Comment by Darksonn** [comment]
You're right, this is misleading. It would be nice to improve the documentation here.
