### ISSUE TITLE
CancellationToken is no longer UnwindSafe in tokio-util 0.7.2

### ISSUE THREAD

**Issue by main--** [tokio-rs/tokio#5424]
It seems that the new implementation of `CancellationToken` from #4652 is no longer `UnwindSafe`. I assume this because I see on docs.rs that the type is still `UnwindSafe` in versions prior to 0.7.2.

This causes a breaking change in a minor release.

**Comment by Darksonn** [comment]
That's a mistake. It should implement `UnwindSafe` (and `RefUnwindSafe`).

**Comment by idevtier** [comment]
I'm interested in taking this on. I'll take a closer look at this tonight and write if I have any questions.
