### ISSUE TITLE
Adding checksum to length delimited codec

### ISSUE THREAD

**Issue by surban** [tokio-rs/tokio#5427]
**Is your feature request related to a problem? Please describe.**
A stream may be unreliable in the way that it corrupts bytes, etc.

**Describe the solution you'd like**
Adding a checksum to `LengthDelimitedCodec` that could be used to detect corruption and return an error in that case.

**Describe alternatives you've considered**
I could write another codec that just performs checksumming and chain it before `LengthDelimitedCodec`. However, I believe this would be inefficient as the data of each packet would be copied twice.

**Additional context**
I would be willing to contribute the implementation if there is interest. Otherwise I would copy `LengthDelimitedCodec` and extend it in an external crate.

**Comment by Darksonn** [comment]
I don't see much reason to keep adding more features to `LengthDelimitedCodec`. Every new feature to tokio-util must be maintained by Tokio maintainers going forward, and I would prefer that someone else maintains them elsewhere.

**Comment by surban** [comment]
Ok, I see.

Thank you :)
