### ISSUE TITLE
Possible deadlock when a waker is replaced

### ISSUE THREAD

**Issue by satakuma** [tokio-rs/tokio#5429]
**Version**
1.25.0

**Description**

There are some types in `tokio::sync` which keep a shared state behind a mutex and expose methods to modify it through a shared reference. For example: `Notify::notify_waiters(&self)`, `Semaphore::add_permits(&self, n: usize)`.
It is possible to trigger a deadlock with custom wakers backed by [`ArcWake`](https://docs.rs/futures/latest/futures/task/trait.ArcWake.html), which call those methods in their destructors. This can happen because tokio drops a waker while holding the lock to the shared state, and the waker tries to re-enter the lock in its Drop impl. Examples of wakers dropped with the lock held: [`Notify::notified`][notified], [`Semaphore::acquire`][semaphore].

To trigger a deadlock, you can poll a future twice with two different wakers. At the second poll, the old waker will be replaced and instantly dropped. Examples of deadlocking code:
<details>
<summary>Notify::notified</summary>

Adapted from [this test](https://github.com/tokio-rs/tokio/blob/80ec80165bfa41c197353983edcbeb64bd45a869/tokio/tests/sync_notify.rs#L107-L139)

```rs
fn notify_in_drop() {
    use futures::task::ArcWake;
    use std::future::Future;
    use std::sync::Arc;

    let notify = Arc::new(Notify::new());

    struct NotifyOnDrop(Arc<Notify>);

    impl ArcWake for NotifyOnDrop {
        fn wake_by_ref(_arc_self: &Arc<Self>) {}
    }

    impl Drop for NotifyOnDrop {
        fn drop(&mut self) {
            self.0.notify_waiters();
        }
    }

    let mut fut = Box::pin(async {
        notify.notified().await;
    });

    // Second iteration deadlocks.
    for _ in 0..2 {
        let waker = futures::task::waker(Arc::new(NotifyOnDrop(notify.clone())));
        let mut cx = std::task::Context::from_waker(&waker);
        assert!(fut.as_mut().poll(&mut cx).is_pending());
    }
}
```

</details>

<details>
<summary>Semaphore::acquire</summary>

```rs
fn release_permits_at_drop() {
    use futures::task::ArcWake;
    use std::future::Future;
    use std::sync::Arc;

    let sem = Arc::new(Semaphore::new(1));

    struct ReleaseOnDrop(Option<OwnedSemaphorePermit>);

    impl ArcWake for ReleaseOnDrop {
        fn wake_by_ref(_arc_self: &Arc<Self>) {}
    }

    let mut fut = Box::pin(async {
        let _permit = sem.acquire().await.unwrap();
    });

    // Second iteration deadlocks.
    for _ in 0..2 {
        let waker = futures::task::waker(Arc::new(ReleaseOnDrop(
            sem.clone().try_acquire_owned().ok(),
        )));
        let mut cx = std::task::Context::from_waker(&waker);
        assert!(fut.as_mut().poll(&mut cx).is_pending());
    }
}
```

</details>

This issue has been partially addressed in the past (#401, [PR discussion](https://github.com/tokio-rs/tokio/pull/3098#discussion_r520291825)), but only about calling `waker.wake()` while holding a lock, not dropping a waker in general.

**Simple solution**
When an old waker has to be replaced, it can be stored on the side and dropped outside the critical section.

[notified]: https://github.com/tokio-rs/tokio/blob/80ec80165bfa41c197353983edcbeb64bd45a869/tokio/src/sync/notify.rs#L874
[semaphore]: https://github.com/tokio-rs/tokio/blob/80ec80165bfa41c197353983edcbeb64bd45a869/tokio/src/sync/batch_semaphore.rs#L458

**Comment by amab8901** [comment]
I'll give it a try

**Comment by amab8901** [comment]
I'm thinking that a good solution might be the following:

Trigger:
Process P is holding a resource X and requesting another resource Y. 1 second after the request, it still doesn't have the requested resource Y.

Response:
Process A starts a timer and lets go of the held resource X. When the timer hits 5 seconds, it will request the resource X and resource Y and try to execute to completion. If it misses some needed resource and doesn't get it after 1 second, then it repeats the above process. 

What are your thoughts on it? Would this be a good approach?

**Comment by satakuma** [comment]
What you've proposed seems like a way to modify examples of deadlocking code from the issue description. These examples are only meant to demonstrate the problem which lies within Tokio's internal code. I would like to address this issue by changing the code in Tokio so that such deadlocks are *impossible* to trigger from a program using Tokio as a library.

To resolve this issue, I would suggest you the following approach:
1. Browse through Tokio's code, starting with the places I've linked in the description ([Notify](https://github.com/tokio-rs/tokio/blob/80ec80165bfa41c197353983edcbeb64bd45a869/tokio/src/sync/notify.rs#L874), [BatchSemaphore](https://github.com/tokio-rs/tokio/blob/80ec80165bfa41c197353983edcbeb64bd45a869/tokio/src/sync/batch_semaphore.rs#L458)), and look for statements which replace a waker while holding a lock.
2. Modify them so that the old waker is kept in a separate variable, which will go out of scope *after* the mutex is released.
3. Ensure that it is impossible to produce examples such as those from the description.

**Comment by amab8901** [comment]
do you mean "waker" or "waiter"? Because waiters are the ones that seem to be replaced in `Notify::notify_waiters()` and are also the ones that hold the MutexGuard

**Comment by amab8901** [comment]
Why are we asserting that the future has to be pending, in the Notify test?
```
assert!(fut.as_mut().poll(&mut cx).is_pending());
```

**Comment by satakuma** [comment]
That assert is quite arbitrary, I am uncertain whether it is correct if the code does not deadlock. Surely you can ignore the result from `poll` in the second iteration.

**Comment by Darksonn** [comment]
Closing a semaphore is another instance of this.

**Comment by amab8901** [comment]
Here is a list of all the places where this issue might occur
- [ ] mpsec
  - [ ] block.rs
  - [ ] bounded.rs
  - [ ] chan.rs
  - [ ] error.rs
  - [ ] list.rs
  - [ ] unbounded.rs
- [ ] rwlock
  - [ ] owned_read_guard.rs
  - [ ] owned_write_guard.rs
  - [ ] owned_write_guard_mapped.rs
  - [ ] read_guard.rs
  - [ ] write_guard.rs
  - [ ] write_guard_mapped.rs
- [ ] task
  - [ ] atomic_waker.rs
- [ ] barrier.rs
- [ ] batch_semaphore.rs
- [ ] broadcast.rs
- [ ] mutex.rs
- [ ] notify.rs
- [ ] once_cell.rs
- [ ] oneshot.rs
- [ ] rwlock.rs
- [ ] semaphore.rs
- [ ] watch.rs

**Comment by satakuma** [comment]
Reopening as it seems this issue was closed on accident (there is still the problem with closing a `BatchSemaphore`).

**Comment by amab8901** [comment]
> Reopening as it seems this issue got closed on accident (there is still the problem with closing a BatchSemaphore).

What do you mean with `BatchSemaphore`? I couldn't find any such struct in this project

**Comment by satakuma** [comment]
I mean the `Semaphore` type from [`src/sync/batch_semaphore.rs`](https://github.com/tokio-rs/tokio/blob/ee1c940709ad88f83daea29612a924524e37d173/tokio/src/sync/batch_semaphore.rs#L36). Sorry for the confusion.

**Comment by bbmena** [comment]
Is this issue still open? It looks like BatchSemaphore has been fixed as well.

**Comment by Darksonn** [comment]
Yes, thank you for pointing that out.
