### ISSUE TITLE
time: `Instant::now()` is slow when `test-util` is enabled

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#5431]
When the `test-util` feature flag is enabled, `Instant::now()` uses a mutex to support mocking time (`time::pause()`). This mutex adds significant overhead. This overhead is acceptable because mocking time is only to support writing tests. However, because Cargo feature flags work, it is easy to enable `test-util` in a release build accidentally. For example, if `Turmoil` is used for testing but is accidentally added as a dependency and not dev-dependency, the `test-util` feature flag is enabled in a release build.

I propose only enabling time mocking functionality when `test-util` **and** debug assertions are enabled. This reflects the original intent of time mocking and avoids adding any performance regressions with release builds. The `pause()` APIs will still be available with only `test-util` but will panic if called without debug assertions.

**Comment by sfackler** [comment]
Paused time can be useful outside of just running unit tests. For example, I use it to deterministically simulate the behavior of some complex client-side retry/fallback logic. I build those simulations in release mode since they're doing a bunch of work, so they'd be broken if paused time was conditioned on debug assertions.

**Comment by Darksonn** [comment]
I'm wondering whether its possible to dynamically "swap" the runtime when `pause` is first called so that performance is only hurt in runtimes where `pause` have been called. Since it only works in current-thread runtimes, it might be feasible to do that without any extra mutexes.

**Comment by carllerche** [comment]
Unfortunately, while pausing time is only possible with the `current-thread` runtime, it is possible to call `pause` and `advance` from other threads using a `runtime::Handle`.

**Comment by carllerche** [comment]
It would certainly be possible to speed up `Instant::now()` if `pause()` has never been called by using an atomic check before acquiring the lock.

**Comment by Darksonn** [comment]
Closed by #5513.
