### ISSUE TITLE
Format tokio::select! with rustfmt

### ISSUE THREAD

**Issue by dbrgn** [tokio-rs/tokio#5441]
**Is your feature request related to a problem? Please describe.**

The `tokio::select!` macro is something used quite often in real-world code. However, rustfmt cannot format code inside that call.

**Describe the solution you'd like**

Maybe it would be possible to adjust the macro so that the code can be formatted with rustfmt?

I found a project [here](https://github.com/jkelleyrtp/tokio-alt-select) which plays with alternative syntax to enable this. (Pinging @jkelleyrtp)

**Describe alternatives you've considered**

Alternatively, maybe rustfmt could be changed to support the current syntax? Not sure if that's possible, since macros can have quite diverse syntax.

Related issue: https://github.com/rust-lang/rustfmt/issues/8

**Comment by Darksonn** [comment]
Although this would be very nice, we cannot change the syntax used by the macro.

**Comment by Darksonn** [comment]
I'm going to close this. As it currently stands, this is not actionable for us. Feel free to reopen or open a new issue if a change in rustfmt makes this possible in the future.

**Comment by dbrgn** [comment]
The best workaround is probably to move the branch code into a standalone function, and call it from the macro. That way, the function can be formatted.

**Comment by Darksonn** [comment]
I'm not sure I understand your suggestion.

**Comment by dbrgn** [comment]
The problem is that in this example:

```rust
    tokio::select! {
        val = rx1 => {
            println!("rx1 completed first with {:?}", val);
            // do some other stuff with rx1
        }
        val = rx2 => {
            println!("rx2 completed first with {:?}", val);
            // do some other stuff with rx2
        }
    }
```

...the code in the branches is not formatted by rustfmt, because it is inside the `select!` macro.

By moving the code into separate functions outside the macro:

```rust
    tokio::select! {
        val = rx1 => {
            println!("rx1 completed first with {:?}", val);
            handle_rx1(val)
        }
        val = rx2 => {
            println!("rx2 completed first with {:?}", val);
            handle_rx2(val)
        }
    }

    fn handle_rx1(val: ...): void {
        // do some stuff with rx1
    }

    fn handle_rx2(val: ...): void {
        // do some stuff with rx2
    }
```

...the functions can be formatted correctly.

**Comment by lfpraca** [comment]
I found that a decent solution is to put `#[rustfmt::skip]` on top of the tokio::select! macro and format the code inside the macro using functionality from a code editor
