### ISSUE TITLE
`fs:read_dir` does not end for a network location

### ISSUE THREAD

**Issue by EFanZh** [tokio-rs/tokio#5473]
**Version**

v1.25.0

**Platform**

Windows 11

**Description**

The iterator generated from `fs::read_dir` does not seem to end for `\\live.sysinternals.com\tools`.

I tried this code:

```rust
use tokio::runtime::Builder;
use tokio::{fs, io};

const SOURCE: &str = r#"\\live.sysinternals.com\tools"#;

async fn main_async() -> io::Result<()> {
    let mut read_dir = fs::read_dir(SOURCE).await?;

    while let Some(item) = read_dir.next_entry().await? {
        println!("{}", item.path().display());
    }

    Ok(())
}

fn main() -> io::Result<()> {
    Builder::new_current_thread()
        .build()
        .unwrap()
        .block_on(main_async())
}
```

I expected to see this happen:

Program exits after printing a list of paths.

Instead, this happened:

Program loops endlessly.

For comparison, here is a synchronized version that works as expected:

```rust
use std::{fs, io};

const SOURCE: &str = r#"\\live.sysinternals.com\tools"#;

fn main() -> io::Result<()> {
    let read_dir = fs::read_dir(SOURCE)?;

    for item in read_dir {
        println!("{}", item?.path().display());
    }

    Ok(())
}
```

**Comment by Darksonn** [comment]
Considering that Tokio's `read_dir` is implemented in terms of `std::fs::read_dir`, that sounds pretty weird. Can you say more about the exact behavior? Did it print all of the files before hanging? Does it work for you on ordinary directories with the same number of files? Are you sure that you're running them in exactly the same way?

**Comment by EFanZh** [comment]
@Darksonn It does not hang, just prints the same list of entries over and over.

I added a counter to the code:

```rust
use tokio::runtime::Builder;
use tokio::{fs, io};

const SOURCE: &str = r#"\\live.sysinternals.com\tools"#;

async fn main_async() -> io::Result<()> {
    let mut read_dir = fs::read_dir(SOURCE).await?;
    let mut i = 0_usize;

    while let Some(item) = read_dir.next_entry().await? {
        println!("{} => {}", i, item.path().display());

        i += 1;
    }

    Ok(())
}

fn main() -> io::Result<()> {
    Builder::new_current_thread()
        .build()
        .unwrap()
        .block_on(main_async())
}
```

The counter goes up to 100000 and still does not stop.

The synchronous one stops after printing 176 entries.

```rust
use std::{fs, io};

const SOURCE: &str = r#"\\live.sysinternals.com\tools"#;

fn main() -> io::Result<()> {
    let read_dir = fs::read_dir(SOURCE)?;

    for (i, item) in read_dir.enumerate() {
        println!("{} => {}", i, item?.path().display());
    }

    Ok(())
}
```

**Comment by ChrisDenton** [comment]
Could it be the server itself having problems?

**Comment by Darksonn** [comment]
Interesting. It seems like our implementation assumes that `ReadDir` is fused. Perhaps the underlying implementation differs on what happens if you call `.next()` after getting a `None`.
