### ISSUE TITLE
Document the timing at which messages sent to a channel are Dropped

### ISSUE THREAD

**Issue by fulmicoton** [tokio-rs/tokio#5490]
When sending message to a mpsc channel, messages seem dropped when the `Receiver` is dropped.

This seems like the most natural behavior, but this is not "goes without saying" situation.
Some alternative library like flume for instance, require all Senders to also be dropped for messages to be dropped.

It would be nice, if this behavior is confirmed, to add that information in the documentation.

**Comment by hds** [comment]
@fulmicoton I've made some changes to the documentation in the attached PR. Do you think this would have been sufficient if you'd found it during your initial search?

**Comment by fulmicoton** [comment]
@hds yes thank you!
