### ISSUE TITLE
Do not timeout if inner future resolves immediatelly.

### ISSUE THREAD

**Issue by ZetaNumbers** [tokio-rs/tokio#5495]
**Is your feature request related to a problem? Please describe.**
I would like `timeout_at(at, mpsc.recv())` to resolve immediatelly and never timeout if inner future immediately returns `Ready` on `poll`.

**Describe the solution you'd like**
Current implementation does this already i belive, so i would like it to be documented and stabilized.

**Describe alternatives you've considered**
Currently i call `mpsc.try_recv()` and then use regular `recv` with timeout.

**Comment by Darksonn** [comment]
If this is already the current behavior, then there is no problem. Would you like to submit a documentation PR for this?
