### ISSUE TITLE
missing documentation for Windows-specific tokio::fs functions

### ISSUE THREAD

**Issue by brodybits** [tokio-rs/tokio#5499]
**Version**

`1.25.0`

**Platform**

Windows

**Description**

While working on PR #5493 I discovered that documentation for Windows-specific functions is missing. For example:

- `tokio::fs::OpenOptions` functions:
  - `custom_flags`: only Unix version documented here: https://docs.rs/tokio/1.25.0/tokio/fs/struct.OpenOptions.html#method.custom_flags
  - `access_mode`, `share_mode`, `attributes`, `security_qos_flags`
- top-level `tokio-fs` functions - https://docs.rs/tokio/1.25.0/tokio/fs/index.html#functions - has Unix `symlink` function but missing Windows-specific `symlink_dir` & `symlink_file` functions

I did find the Windows-specific functions documented for an earlier version of Tokio:

- https://docs.rs/tokio/1.7.0/i686-pc-windows-msvc/tokio/fs/struct.OpenOptions.html#method.access_mode etc.
- https://docs.rs/tokio/1.7.0/i686-pc-windows-msvc/tokio/fs/fn.symlink_dir.html
- https://docs.rs/tokio/1.7.0/i686-pc-windows-msvc/tokio/fs/fn.symlink_file.html

but when I tried the platform dropdown for Tokio 1.25.0 I did not see an option for Windows.

Please let me know if I am missing anything. I hope to investigate this further (someday). Thanks.

**Comment by Darksonn** [comment]
Thank you for reporting this. They need to be listed when viewing the default unix documentation like we do for named pipes. It would be great to get that fixed.
