### ISSUE TITLE
Segmentation fault when making an HTTPS connection ("tokio-runtime-w" received signal SIGSEGV)

### ISSUE THREAD

**Issue by bonigarcia** [tokio-rs/tokio#5532]
**Version**

The [Cargo.toml](https://github.com/SeleniumHQ/selenium/blob/trunk/rust/Cargo.toml) I used for building my binary includes _tokio_ as follows:

```
tokio = { version = "1.26.0", default-features = false, features = ["macros", "net", "rt-multi-thread"] }
```

**Platform**
```
Ubuntu 22.10 x86_64
```

**Description**

I am a Selenium committer and the developer of `selenium-manager`, a CLI tool developed in Rust belonging to the Selenium project. `selenium-manager` is currently used by many Selenium users nowadays, and recently, one of them has reported a [segmentation fault](https://github.com/SeleniumHQ/selenium/issues/11717) problem on Ubuntu x64.

Internally, `selenium-manager` uses _tokio_ to handle asynchronous requests and _reqwest_ to manage the HTTP connections, and it seems the problem happens when making an HTTPS connection (see [function](https://github.com/SeleniumHQ/selenium/blob/trunk/rust/src/downloads.rs#L73)).

As you can see in the [bug report in Selenium](https://github.com/SeleniumHQ/selenium/issues/11717), I asked the user to debug the problem with `gdb`. The complete output of that test is [here](https://gist.github.com/benhutton/0d0833f4a9e5436f3d42808500f99a42), and the backtrace starts from the following message:

```
Thread 18 "tokio-runtime-w" received signal SIGSEGV, Segmentation fault.
```

I looked for clues about this problem but still had no luck determining the cause of the issue. But it seems related to `tokio-runtime-w`. Do you have an idea about this problem? I really appreciate any help you can provide.

**Comment by Darksonn** [comment]
Well, `tokio-runtime-w` is just the name of a thread, so all this tells you is that the segfault happened in some code running on a thread owned by the Tokio runtime.

**Comment by bonigarcia** [comment]
Indeed, the error was not due to _tokio_. Instead, static linking using target `x86_64-unknown-linux-musl` fixed my issue. Sorry for the noise.
