### ISSUE TITLE
Weird behavior of tokio::task::spawn on Apple M1

### ISSUE THREAD

**Issue by ArturAralin** [tokio-rs/tokio#5544]
**Version**
tokio v1.26.0
tokio-macros v1.8.2 (proc-macro)

**Platform**
Darwin MacBook-Air-Artur.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64

**Description**
I have a sample code which should spawn feature and log "spawn" in stdout. Periodically no output to stdout. 

I tried this code:

```
#[tokio::main]
async fn main() {
    tokio::task::spawn(async move {
        println!("spawn");
    });
}
```

command `cargo run`

outputs
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/khand`
```

I expected to see this happen: every start of my program should output "spawn"

Instead, this happened: periodically "spawn" log.

I'd tried to run this code on replit and no problems here 
https://replit.com/@ArturAralin1/tokio-spawn

**Comment by sfackler** [comment]
Your program is not waiting for the spawned task to complete before exiting.

**Comment by Darksonn** [comment]
The program is immediately killed when you return from main. If this happens before the spawned task starts, then it doesn't have time to print before it gets killed.
