### ISSUE TITLE
Support for anonymous pipes

### ISSUE THREAD

**Issue by notpeelz** [tokio-rs/tokio#5547]
**Is your feature request related to a problem? Please describe.**
It's unclear how anonymous pipes should be used in Tokio. For my use case, I have a `RawFd` returned from a `pipe2()` syscall and I want to wrap it with the types in `tokio::net::unix::pipe`. At the moment, it seems like the only way to do this is to wrap it in a `File` first:
```rs
let file = unsafe { std::fs::File::from_raw_fd(fd) };
let sender = tokio::net::unix::pipe::Sender::from_file(file).unwrap();
```

**Describe the solution you'd like**
I'm not sure if wrapping it in a `File` is the "right" way to do this, but it should at least be documented.

**Comment by Darksonn** [comment]
We should definitely have a way to construct an anonymous pipe in the API.

**Comment by luben** [comment]
I found https://crates.io/crates/tokio-pipe works well for my use case. Having it in tokio would be better of course.
