### ISSUE TITLE
UdpSocket::bind("[::]:0") fails on Windows

### ISSUE THREAD

**Issue by RReverser** [tokio-rs/tokio#5562]
**Version**

1.26.0

**Platform**

Windows 10 64-bit Build 19045

**Description**

When trying to bind `tokio::net::UdpSocket` to `[::]:0`

```rust
tokio::net::UdpSocket::bind("[::]:0")
```

it fails with

> Error: The system detected an invalid pointer address in attempting to use a pointer argument in a call. (os error 10014)

I can't find any useful results about why this happens - they range from invalid params passed to underlying socket functions to not correctly zeroing out param structs to, in some scenarios, even filled disk on the user side or network config issues.

Same code works fine for me when used from within WSL. Also, using Rust standard library's `std::net::UdpSocket` with the same unspecified address works just fine - which makes me lean even more to this being an issue with Windows bindings used by `tokio::net::UdpSocket` rather than a problem with my machine.

Let me know if there is any more info I can provide.

**Comment by Darksonn** [comment]
@Thomasdezeeuw Any idea what this could be?

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw Any idea what this could be?

Not entirely sure, I don't see something obviously wrong in the code.

> it fails with
> 
> > Error: The system detected an invalid pointer address in attempting to use a pointer argument in a call. (os error 10014)

Could it be that we're passing an IPv4 (sized) address buffer, which should be an IPv6?

> ```rust
> tokio::net::UdpSocket::bind("[::]:0")
> ```

I don't have a Windows so I can't try to reproduce this.

Could someone see what the `ToSocketAddrs` implementation for `"[::]:0"` returns? I don't expect it to be an issue, but just to exclude.

After that try [`mio::net::UdpSocket::bind`](https://docs.rs/mio/latest/mio/net/struct.UdpSocket.html#method.bind) with the expect IPv6 address: `SocketAddr::new(IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1)), 0)`.

**Comment by RReverser** [comment]
Hm I'm a bit concerned because now that I tried all of the things above to debug in an isolated example, it works.

I don't think anything changed on my side, but if it's indeed related to structure sizes / some sort of memory issue, I suppose it could fail only sporadically.

**Comment by RReverser** [comment]
Sorry for wasting your time, it looks like due to async debugging shenanigans I arrived at completely wrong place where the error was coming from.

It happens when I use `send_to` on such socket to `Ipv4Addr::BROADCAST`, which is a whole separate issue - apparently on Windows it just requires the user to somehow opt-in into "any interface". Not sure if it's something tokio could automate, but either way, it's a whole separate feature issue not related to memory corruption or anything like that.
