### ISSUE TITLE
TcpStraem wirte_all() large size Vec, read() will block?

### ISSUE THREAD

**Issue by mengzhaofeng2016** [tokio-rs/tokio#5567]
**Version**
tokio = "1.26.0"

`cargo tree | grep tokio`

**Platform**
Ubuntu 2204

**Description**

let ret = reader.read(&mut *mbuf).await;  == this statement will blocked, when i call write_all() to send large size vec, such as 16MB,
howerer, i split the large vec to 8KB slice, and then send them in sequence,  reader become recover normal, could read success.

[short summary of the bug]

I tried this code:

[code sample that causes the bug]

I expected to see this happen: [explanation]

Instead, this happened: [explanation]

**Comment by Darksonn** [comment]
You need to provide more information. I have tagged this as "needs minimum complete verifiable example".
