### ISSUE TITLE
File::create() folloed by AsyncReadExt::read_u64() results in "Bad file descriptor"

### ISSUE THREAD

**Issue by xfbs** [tokio-rs/tokio#5568]
**Version**
```
tokio = { version = "1.26.0", features = ["rt", "macros", "fs", "io-util"] } 
```

**Platform**
```
Linux Titus 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

**Description**

I create a file using `File::create()`, and then I read from it using `AsyncReadExt::read_u64()`. Since the file is empty, I expect this to fail with an error indicating that the end of file has been reached. Instead, I get an error indicating that the file descriptor is bad. This is unexpected.

I tried this code:

```rust
use tokio::fs::File;
use tokio::io::AsyncReadExt;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let mut file = File::create("state.txt").await.unwrap();
    let current = file.read_u64().await.unwrap();
}
```

I expected to see this happen:

```
Error: End of file.
```

Instead, this happened:

```
Err value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
````

**Comment by sfackler** [comment]
`File::create` doesn't open the file with read permissions, only write. For whatever reason POSIX reports that as an EBADF.

**Comment by Darksonn** [comment]
The same happens with the std file. Tokio is implemented in terms of those, so if there's any problem, then it is in std.
```rs
use std::fs::File;
use std::io::Read;

fn main() {
    let mut file = File::create("state.txt").unwrap();
    let current = file.read(&mut [0]).unwrap();
}
```

**Comment by xfbs** [comment]
Hey, thanks for the quick response. You guys are totally right, it even mentions in the documentation that it opens in write-only mode. This error is probably somewhat unintuitive, but it does not look like this is Tokio's fault, so I'm closing this bug again.
