### ISSUE TITLE
android support?

### ISSUE THREAD

**Issue by KORuL** [tokio-rs/tokio#559]
I'm trying to use your library on android in another project. Tokio compiles under android, but then either
 "let listen = socket.incoming ()
            .map_err (| err | error! ("Error accepting socket: {:?}", err))
            .for_each (move | socket | {
                tokio :: spawn (hdb.clone (). handle_incoming (socket));
                Ok (())
            });

listen.join4 (connect, generate_txns_status, hdb_handler) .map (| (_, _, _, _) | ())
"
or

"tokio :: run (..)"

causes an error when using the compiled library on android
"A / libc: Fatal signal 6 (SIGABRT), code -6 in tid 32272 (Thread-1977)"

Do you plan to adapt the library to android?

**Comment by KORuL** [comment]
It may be my fault, this is the first time I've tried to assemble a library for rust to work on android. It falls on the next function and it is under android

"/// Binds to a host address and returns a future which starts the node.
    pub fn node (self, remotes: Option <HashSet <SocketAddr >>, reactor_remote: Option <()>)
            -> impl Future <Item = (), Error = ()> {
        let socket = TcpListener :: bind (& self.inner.addr) .unwrap ();
        println! ("Listening on: {}", self.inner.addr);

        let remotes = remotes.unwrap_or (HashSet :: new ());

        let hdb = self.clone ();
        let listen = socket.incoming ()
            .map_err (| err | error! ("Error accepting socket: {:?}", err))
            .for_each (move | socket | {
                tokio :: spawn (hdb.clone (). handle_incoming (socket));
                Ok (())
            });

        let hdb = self.clone ();
        let local_pk = hdb.inner.secret_key.public_key ();
        let connect = future :: lazy (move || {
            for & remote_addr in remotes.iter () {
                tokio :: spawn (hdb.clone (). connect_outgoing (remote_addr, local_pk, None, true));
            }
            Ok (())
        });

        let generate_txns_status = self.clone (). generate_txns_status ();

        let hdb_handler = self.handler ()
            .map_err (| err | error! ("Handler internal error: {:?}", err));

        listen.join4 (connect, generate_txns_status, hdb_handler) .map (| (_, _, _, _) | ())
    }

    /// Starts a node.
    pub fn run_node (self, remotes: Option <HashSet <SocketAddr >>) {
tokio :: run (self.node (remotes, None));
    } "

**Comment by kpp** [comment]
Wrap your code with ``` to highlight it.

**Comment by KORuL** [comment]
I created a test project on rust. This example works fine on Linux `./ runTestPy`, but on android causes a fall! This example is based on the example of tokio hello_world. Project -  [git repository](https://github.com/KORuL/tokio_android) .

Crash on android:

![image](https://user-images.githubusercontent.com/19871487/44549269-4224b600-a729-11e8-891b-9671c4b29429.png)


MainActivity android: 

```
import android.support.v7.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {

    lateinit var thread: Thread

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        thread = Thread {
            val b = helloworld()
        }
        thread.start()
    }


    private external fun helloworld(): Boolean

    companion object {

        init {
            System.loadLibrary("tokio_android")
        }

    }
}

**Comment by tobz** [comment]
@carllerche This one is a bit out of my wheelhouse.

I know Mio has Android support, but do you know if there's any other known issues with using Tokio on Android?  Of course, that one stack in the stacktrace between `hello_world` and the panic starting is empty. 😢

**Comment by KORuL** [comment]
I updated the example project [git repository](https://github.com/KORuL/tokio_android) in which the fall occurs! I added logcat and localized the error: the error occurs in the line `listener.unwrap ();`
@carllerche  if you use tokio on android please help me

**Comment by KORuL** [comment]
I found my mistake! The error was associated with permissions for android. Therefore, I could not bind. You can close Issue

**Comment by open-trade** [comment]
> I found my mistake! The error was associated with permissions for android. Therefore, I could not bind. You can close Issue

What permissions have you set to avoid crash? I have set below permissions, but still crash.
```
// crash here
 TcpStream::connect("127.0.0.1:34254").await.ok()
```


```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by open-trade** [comment]
> > I found my mistake! The error was associated with permissions for android. Therefore, I could not bind. You can close Issue
> 
> What permissions have you set to avoid crash? I have set below permissions, but still crash.
> 
> ```
> // crash here
>  TcpStream::connect("127.0.0.1:34254").await.ok()
> ```
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
> ```

forget about this, this crash on mio 0.6, it is fine on mio 0.7

**Comment by Phill030** [comment]
I'm currently trying Tokio using Flutter + Rust, what have you done to fix the issue?

**Comment by OverShifted** [comment]
@Phill030 They probably added the "INTERNET" premissiom to their Android app's manifest. You should also be able to set it for your Flutter app.

**Comment by Phill030** [comment]
wat

**Comment by Darksonn** [comment]
Just to clarify, Tokio does indeed support Android. This is documented in our [supported platforms](https://docs.rs/tokio/latest/tokio/index.html#supported-platforms) section.
