### ISSUE TITLE
optional tcp

### ISSUE THREAD

**Issue by aep** [tokio-rs/tokio#560]
can we make tokio-tcp an optional dependency?

**Comment by carllerche** [comment]
Relates to #354

**Comment by carllerche** [comment]
I'm open to the idea. We just need to come up with a good feature strategy.

**Comment by aep** [comment]
no longer relevant for me. should we close?

**Comment by carllerche** [comment]
FWIW it landed on master

**Comment by aep** [comment]
ah nice, so this is closed either way.
