### ISSUE TITLE
Ensure that fuzz tests compile in CI

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#5601]
We don't run fuzz tests in our CI because they're executed elsewhere, but we should still make sure that they compile. To close this, submit a PR that updates our CI configuration to ensure that fuzz tests compile. The CI configuration can be found in the `.github` directory.

There are a few warnings in the fuzz tests currently, those should be fixed too.

See #5392 for context.

**Comment by silvergasp** [comment]
There is a github action for oss fuzz that can make this pretty simple. https://google.github.io/oss-fuzz/getting-started/continuous-integration/

**Comment by hootio** [comment]
Submitted a PR for checking the `/tokio/` subdir.
Was going to include `/tokio-stream/` too but that had its own compilation warnings, which should be addressed in a separate PR.

**Comment by hootio** [comment]
Submitted #5675 to remove compilation warnings from `/tokio-stream/`. Next step is to add the compilation check step in CI and then this issue can be resolved.
