### ISSUE TITLE
Add an async `Stdout::lock`

### ISSUE THREAD

**Issue by hlbarber** [tokio-rs/tokio#5605]
**Is your feature request related to a problem? Please describe.**

[Stdout::lock](https://doc.rust-lang.org/std/io/struct.Stdout.html#method.lock) returns a [StdoutLock](https://doc.rust-lang.org/std/io/struct.StdoutLock.html), this allows exclusive access to the stdout writer.

There are use cases where atomic writes to `stdout` are required. As far as I can tell there's no way to ensure this occurs with `tokio::io::Stdout`. An `async fn lock` on `tokio::io::Stdout` would allow the user to take the lock, then write atomically to stdout without a chance of other writers interleaving data.

**Describe the solution you'd like**

Mirror the standard library with the exception that `lock` is async and the `StdoutLock` is `AsyncWrite`?

**Describe alternatives you've considered**

Just taking a lock on the `tokio` `Mutex` before calling `std::io::Stdout::lock`.

**Additional context**

This is probably not possible - but it'd be nice to know for sure.

**Comment by Darksonn** [comment]
The std stdout lock cannot be locked asynchronously. It would be possible to have a lock that only protects against interleaving by others who also use the Tokio stdout type, but it wouldn't block writers using `std::io::stdout`.

On the balance, considering that we already recommend not using the Tokio stdin/stdout types for interactive use-cases, I think it's fine not to support this use-case either.

Thank you for the suggestion.
