### ISSUE TITLE
tokio Interval not woken up after first tick on 1.27

### ISSUE THREAD

**Issue by mattsse** [tokio-rs/tokio#5627]
**Version**
List the versions of all `tokio` crates you are using. The easiest way to get
this information is using `cargo tree` subcommand:

tokio-interval v0.1.0
└── tokio v1.27.0
    └── tokio-macros v2.0.0 (proc-macro)

**Platform**
Darwin MacBook-Pro-5.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64

**Description**

A future that uses `Interval::poll_tick` is not polled again after the delay elapses.

I tried this code:

See repro: 

https://github.com/mattsse/tokio-interval-repro

I expected to see this happen:

on 1.26
tokio-interval v0.1.0
└── tokio v1.26.0
    └── tokio-macros v1.8.2 (proc-macro)

the future is polled after each interval 2s tick as expected:

```text
polled
polled
is ready, elapsed 1.340166ms
polled
is ready, elapsed 2.0023145s
polled
is ready, elapsed 2.002097s
polled
is ready, elapsed 1.999464791s
```

Instead, this happened:

on 1.27 after the first `tick` the future never gets polled again:

```text
time cargo r                                                                                          
polled
polled
is ready, elapsed 1.371666ms

cargo r  0.08s user 0.03s system 0% cpu 20.132 total
```

**Comment by Darksonn** [comment]
This is due to a bugfix in `Interval`, where it incorrectly sends too many wakeups.

The problem is that `poll_tick` only promises to emit a wakeup when it returns `Poll::Pending`. If it returned `Poll::Ready`, then it will not wake you up. You need to call `poll_tick` again.

**Comment by mattsse** [comment]
> If it returned Poll::Ready, then it will not wake you up.

got it, ty.

then this is now working as expected and this issue can be closed?

**Comment by Darksonn** [comment]
Yep.

**Comment by mattsse** [comment]
is the idiomatic way of doing this now

```rust
if interval.poll_tick(cx).is_ready() {
    let _ = interval.poll_tick(cx);
}
```

?

**Comment by Darksonn** [comment]
You shouldn't ignore the return value. Usually, poll methods are implemented with a loop like this:
```rs
fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
    let mut this = self.project();
    loop {
        match this.interval.as_mut().poll_tick(cx) {
            Poll::Ready(()) => {
                println!("is ready, elapsed {:?}", this.now.elapsed());
                *this.now = Instant::now();
            },
            Poll::Pending => return Poll::Pending,
        }
    }
}
```
