### ISSUE TITLE
`tokio::net::TcpStream` does not implement `std::io::BufRead`

### ISSUE THREAD

**Issue by rushmorem** [tokio-rs/tokio#564]
This makes it impossible to use with `tokio::io::read_until`.

**Comment by tobz** [comment]
You can see here in the chat-combinators example how it's intended to be used: https://github.com/tokio-rs/tokio/blob/f1cb12e14fb047f3f86c852c253962c60ce471e8/examples/chat-combinator.rs#L83

A [`BufReader`](https://doc.rust-lang.org/nightly/std/io/struct.BufReader.html) wraps the TCP stream (or, specifically, in the case of the example, the read half of the TCP stream) and provides the buffering required.

Buffering is an orthogonal concern to `tokio`/`mio`, and can be provided by external types.
