### ISSUE TITLE
LinesCodec returns incomplete frames on EOF

### ISSUE THREAD

**Issue by wolthom** [tokio-rs/tokio#5646]
**Version**
Crates:
```
tokio = v1.27.0
tokio-stream = v0.1.12
tokio-util = v0.7.7
```

**Platform**
Ubuntu 20.04 / x86_64

**Description**
I'm using `tokio-util` with the `codec` feature flag to make use of the `Decoder` functionality.
Specifically, I'm reading data from a `TcpStream` in a newline separated framing via `Framed<TcpStream, LinesCodec>`.
When the client side unexpectedly closes with an incomplete frame (i.e. without the newline), calling `next()` on the stream will return the remaining data without any indication of the missing newline. 

Is there any way to actually identify this case without trying to read / write from the underlying socket and receiving `Ok(0)` which indicates a closed socket?

This should reproduce the issue:
`Cargo.toml`
```toml
[dependencies]
futures-util = "0.3.28"
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["codec"] }
```

```rust
use std::net::SocketAddr;

use futures_util::StreamExt;
use tokio::io::AsyncWriteExt;
use tokio::net::{TcpListener, TcpStream};
use tokio_util::codec::{Framed, LinesCodec};

const SERVER_ADDR: &str = "127.0.0.1:8888";

#[tokio::main]
async fn main() {
    let server = tokio::spawn(start_server());
    tokio::spawn(start_client());
    server.await.unwrap();
}

async fn start_client() {
    let addr: SocketAddr = SERVER_ADDR.parse().unwrap();
    let mut con = TcpStream::connect(addr).await.unwrap();
    con.write_all("First part\n Second Part \n Third part".as_bytes())
        .await
        .unwrap();
}

async fn start_server() {
    let addr: SocketAddr = SERVER_ADDR.parse().unwrap();
    let server = TcpListener::bind(&addr).await.unwrap();

    loop {
        let (con, _addr) = server.accept().await.unwrap();
        tokio::spawn(handle_con(con));
    }
}

async fn handle_con(con: TcpStream) {
    let mut r = Framed::new(con, LinesCodec::new());
    while let Some(msg) = r.next().await {
        match msg {
            Ok(msg) => {
                println!("received message: {msg}");
            }
            Err(e) => {
                println!("unexpected error occured: {}", e.to_string());
            }
        }
    }
}

```

**Comment by Darksonn** [comment]
This is expected behavior. All read line-by-line APIs in Rust that I am aware of will accept it if the last frame is missing a newline at the end.

If you want something else, then write your own codec.

**Comment by wolthom** [comment]
@Darksonn Oh, I was not aware of this being the expected behavior. Then this issue can be closed.

My apologies for the erroneous bug report and thank you for your time!
