### ISSUE TITLE
Consider reexporting `bytes`-dependencies required for implementing util's traits

### ISSUE THREAD

**Issue by pflakus** [tokio-rs/tokio#5719]
When I implement the `Encoder` or `Decoder` trait in my projects, I'm always required to add `bytes` as another dependency. Otherwise the compiler isn't able to resolve `BytesMut`.

I'd wish to be able to have `BytesMut` be available to import as `tokio_util::codec::BytesMut`, since that is where I'm importing the traits from.

So far I have just added bytes as another dependency and imported `bytes::BytesMut` instead.
This works well enough, but doesn't feel like it should be the intended way of going about things.

**Comment by Darksonn** [comment]
Seems reasonable enough to me.
