### ISSUE TITLE
Add `TaskLocalFuture::into_value`

### ISSUE THREAD

**Issue by TennyZhuang** [tokio-rs/tokio#5743]
**Is your feature request related to a problem? Please describe.**

Sometimes we want to use `LocalKey` with `Stream`, and it's impossible to yield from an async closure. A workaround is wrap inside the stream iteration:

```rust

tokio::task_local! {
    static TASK_LOCAL_ALLOCATED_BYTES: AtomicUsize;
}

let allocated_bytes = AtomicUsize::new(0);
while let Some(message) =
        TASK_LOCAL_ALLOCATED_BYTES.scope(allocated_bytes, input.try_next()).await?
    {
        yield message;
    }
```

However, the `scope` will take the ownership of the slot value, and compile failed.

**Describe the solution you'd like**

I hope we can add a method to return the ownership of slot value instead of always dropping it, so that we can:

```rust
    let mut allocated_bytes = Some(AtomicUsize::new(0));

    loop {
        let f = TASK_LOCAL_ALLOCATED_BYTES.scope(allocated_bytes.take().unwrap(), input.try_next());

        let message = (&mut f).await?;
        if let Some(message) = message {
            yield message;
            allocated_bytes = Some(f.into_value());
        }
    }
```

**Describe alternatives you've considered**

Directly support Stream, such as `LocalKey::scope_stream`.

**Additional context**

**Comment by Darksonn** [comment]
This seems reasonable to me.

**Comment by Darksonn** [comment]
As pointed out in https://github.com/tokio-rs/tokio/pull/5758#discussion_r1215517904, this method would not be callable once the future has been pinned. A `take_value` method might be a better idea?
