### ISSUE TITLE
Can we add `shutdown()` to `JoinHandle`?

### ISSUE THREAD

**Issue by ileixe** [tokio-rs/tokio#5750]
**Is your feature request related to a problem? Please describe.**

In this code below, I'd like to drop future and cleanup entirely as future has internal resource which is a singleton . (let's say dev file which is only available exclusively)
 
```rust
let a = future.await;
drop(a)
let b = future.await; // Here occurs error as first future not yet dropped 
```

Current situation `a` is not dropped until future is polled so I'd like to ask scheduler to drop immediately the future. 

I tried

```rust
let a = future.await;
a.abort()
drop(a)
let b = future.await; // Still not work
```

but it did not work as `abort()` in `JoinHandle` is just to set cancellation flag not drop the future right away.

So, I'm suggesting to add `shutdown()` instead to drop the future in place like below.

```rust
let a = future.await;
a.shutdown() // New API
drop(a) 
let b = future.await; // Now it works
```

**Describe the solution you'd like**
Add shutdown in JoinHandle

```
diff --git a/tokio/src/runtime/task/join.rs b/tokio/src/runtime/task/join.rs
index a04ec956..ee7abfa7 100644
--- a/tokio/src/runtime/task/join.rs
+++ b/tokio/src/runtime/task/join.rs
@@ -203,6 +203,12 @@ impl<T> JoinHandle<T> {
         }
     }

+    pub fn shutdown(&self) {
+        if let Some(raw) = self.raw {
+            raw.shutdown();
+        }
+    }
+
     /// Checks if the task associated with this `JoinHandle` has finished.
     ///
     /// Please note that this method can return `false` even if [`abort`] has been
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ileixe** [comment]
Hm.. is there any workaround which does not use .await? Actually our usage is to call the abort() in Drop() (so no async calling is available)

**Comment by Darksonn** [comment]
It's not possible via the `JoinHandle` api, but you can store the shared resource in another location where you have access to destroy it synchronously. For example, you could store it in an `Arc<Mutex<Option<Resource>>>` and do `arc.lock() = None` to drop it.

**Comment by ileixe** [comment]
That makes sense. I put myself in the wrong place while simple solution is there. Thanks for the advice.
