### ISSUE TITLE
Adjust Core::transition_from_parked behavior after introducing disable_lifo_slot feature

### ISSUE THREAD

**Issue by hidva** [tokio-rs/tokio#5751]
### Discussed in https://github.com/tokio-rs/tokio/discussions/5749

<div type='discussions-op-text'>

<sup>Originally posted by **hidva** June  1, 2023</sup>
After introducing the `disable_lifo_slot` feature in Tokio, I think that the behavior of `Core::transition_from_parked` also needs to be adjusted. For example, when `core.run_queue.is_stealable()` is true, park should also be terminated. Additionally, to avoid task contention, `Context::park_timeout` should only wake up others when `core.run_queue.len() >= 2`.

Please let me know your thoughts on this proposed adjustment.

Best regards,
盏一</div>

**Comment by hidva** [comment]
If necessary, I would be happy to propose a corresponding PR

**Comment by carllerche** [comment]
It looks like you are correct. A PR would be nice. Could you include a test maybe? It *should* be possible to simulate the case.
