### ISSUE TITLE
Make `JoinSet::poll_join_next` a public API

### ISSUE THREAD

**Issue by bartlomieju** [tokio-rs/tokio#5769]
**Is your feature request related to a problem? Please describe.**
We're migrating `deno_core` to use `JoinSet` instead of `FuturesUnordered` based on suggestions from @Darksonn. `deno_core` has a main `poll_event_loop` function that responsible for polling all spawned tasks. With `FuturesUnordered` polling them was as simple as:
```rust
while let Poll::Ready(...) = state.pending_ops.poll_next_unpin(cx) {
  ...
}
```
however with `JoinSet` more ceremony (and pinning) is required:
```rust
loop {
  let item = {
    let next = std::pin::pin!(context_state.pending_ops.join_next());
    let Poll::Ready(Some(item)) = next.poll(cx) else {
      break;
    };
    item
  };
  ...
}
```

**Describe the solution you'd like**
Make `JoinSet::poll_join_next` API public, which would change the example above to:
```rust
while Poll::Ready(Some(item)) = context_state.pending_ops.poll_join_next(cx) {
  ...
};
```

**Describe alternatives you've considered**
Keep current API as is without changes.

**Comment by Darksonn** [comment]
There's already a PR for this:  #5721.

**Comment by bartlomieju** [comment]
Thanks, I'm gonna close the issue then.
