### ISSUE TITLE
Unify UnixDatagram and UdpSocket

### ISSUE THREAD

**Issue by luben** [tokio-rs/tokio#577]
I think we should unify handling of both IP/Unix datagram interfaces the same way as the TcpSocket and UnixStream are unified through AsyncRead/AsyncWrite traits. May be call the new traits AsyncRecv/AsyncSend.

Do you think it's feasable or do you see any blockers?

**Comment by carllerche** [comment]
Do you have use cases in mind? Is it possible to just shim over the differences? Since you need to pass a SocketAddr, wouldn't the caller still need to be aware of the difference between IP & Unix?

**Comment by luben** [comment]
Yes, the constructor can't be abstracted but this is also the case with TcpStream/UnixStream. My use case is to be able to share the datagram processing pipeline - currently I have some functionality (e.g. create a stream of Bytes, one Bytes value per datagram) that I have to duplicate because the there is no common trait. It should be possible to abstract the difference using macros but I have not tried.

**Comment by luben** [comment]
In my project I have done a trivial implementation of AsyncSend/AsyncRecv that delegate to poll_send/poll_recv from UDP/UDS crates. I am not sure it's worth having it in Tokio, so I am closing it.
