### ISSUE TITLE
Ability to run one event loop per worker thread

### ISSUE THREAD

**Issue by trungda** [tokio-rs/tokio#5771]
**Is your feature request related to a problem? Please describe.**
Hi,

Thanks a lot for the great work. We've been using tokio and the related ecosystem for a few years and are very happy. Our workload is actually not suitable for the default work-stealing scheduler (we are basically a proxy that gets a request and route it very quickly), the load is uniform. After exhaustive benchmarking, we concluded that the single event loop for the whole runtime is the bottleneck. We would be more beneficial with a runtime that has one event loop per CPU core in the multi-threaded runtime. 

I am just curious if it's possible technically and is there anything in the roadmap that would consider this architecture. 
I am aware of a workaround is that we could have multiple single-threaded runtimes in the same app. That has much better performance compared to the default multi-threaded runtime for our workload but there are certain overheads with that approach (tho negligible). 

**Describe the solution you'd like**
A knob to turn on single event loop per core in the multi-threaded runtime.

**Describe alternatives you've considered**
Multiple single-threaded runtime. 

**Additional context**

**Comment by Darksonn** [comment]
The standard way of doing this is to spawn several current-thread runtimes.

**Comment by trungda** [comment]
Thanks @Darksonn. For my education, what's the difference between using a multi-thread runtime with number of worker = 1 v.s, current-thread runtime. If I understand correctly, in the former case, there are still two threads (the main thread and the worker thread, and there are some overhead here since tasks might be passed around between the two) whilst the latter set up, everything runs in one thread so there is no need to implement multi-threaded synchronization (e.g., `Arc`, `Mutex`, `RWLock`), we can just use single-threaded primitives (e.g., `Cell`, `RefCell`, `Rc`). Am I correct?

**Comment by Darksonn** [comment]
The multi-thread runtime will spawn its own thread, whereas the current-thread runtime will run on the thread you call `block_on` from.

**Comment by trungda** [comment]
Thank you for the explanation!
