### ISSUE TITLE
tokio::time::sleep in tokio::select! wrong behaviour

### ISSUE THREAD

**Issue by getong** [tokio-rs/tokio#5780]
I use rustc 1.72.0-nightly (b2b34bd83 2023-06-06), tokio 1.28.2

the code:
```
use std::sync::Arc;
use tokio::time::{sleep, Duration};
use tokio::sync::Mutex;

#[tokio::main]
async fn main() {
   select_arc_example().await;
}


async fn select_arc_example() {
    let value = Arc::new(Mutex::new(0));
    loop {
        tokio::select! {
            _ = async {
                // Branch 1
                {
                    let mut temp_value = value.lock().await;
                    *temp_value += 1;
                    println!("Branch 1: {}", *temp_value);
                }
                sleep(Duration::from_secs(1)).await;
            } => {
                println!("branch 1");
                let temp_value = value.lock().await;
                println!("branch 1, temp_value: {}", *temp_value);
                if *temp_value >= 10 {
                    break
                }
            },
            _ = async {
                // Branch 2
                {
                    let mut temp_value = value.lock().await;
                    *temp_value += 2;
                    println!("Branch 2: {}", *temp_value);
                }
                sleep(Duration::from_secs(1)).await;
            } => {
                println!("branch 2");
                let temp_value = value.lock().await;
                println!("branch 2, temp_value: {}", *temp_value);
                if *temp_value >= 10 {
                    break
                }
            },
        }
    }
}
```
I make two branch, which break the loop statement when the value first greater than or equals 10.
But it does not work.
The output :
```
Branch 1: 1
Branch 2: 3
branch 1
branch 1, temp_value: 3
Branch 2: 5
Branch 1: 6
branch 2
branch 2, temp_value: 6
Branch 2: 8
Branch 1: 9
branch 2
branch 2, temp_value: 9
Branch 1: 10
Branch 2: 12
branch 1
branch 1, temp_value: 12
```
The code executes two more times, but as expected, it should stop when the branch 1 at 10 value.
By deleting the `sleep(Duration::from_secs(1)).await;`, the code works.

I make a playground link , 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=511b21e80afe4ff3a2121b24ff76db71 
You can test it there.

**Comment by Darksonn** [comment]
I don't understand the problem. You don't check for the value being `>= 10` until one branch has fully completed.

**Comment by getong** [comment]
> I don't understand the problem. You don't check for the value being `>= 10` until one branch has fully completed.

I think I have check the value completely at one branch.
You can check the new code here.
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2389506ed15beaf064d2463d91db00a1

I juse disable the `sleep` function.
And the output is ok.
```
Branch 1: 1
branch 1
branch 1, temp_value: 1
Branch 1: 2
branch 1
branch 1, temp_value: 2
Branch 2: 4
branch 2
branch 2, temp_value: 4
Branch 1: 5
branch 1
branch 1, temp_value: 5
Branch 1: 6
branch 1
branch 1, temp_value: 6
Branch 1: 7
branch 1
branch 1, temp_value: 7
Branch 2: 9
branch 2
branch 2, temp_value: 9
Branch 2: 11
branch 2
branch 2, temp_value: 11
```

**Comment by carllerche** [comment]
The blocks with the `sleep` calls are concurrent. That is why the number can go above 10.

**Comment by carllerche** [comment]
Feel free to open a [discussion](https://github.com/tokio-rs/tokio/discussions) if you have further questions about how `select` works.
