### ISSUE TITLE
Named future return type for `time::advance()` function

### ISSUE THREAD

**Issue by d-e-s-o** [tokio-rs/tokio#5819]
**Is your feature request related to a problem? Please describe.**
I'd like to name the Future that is returned by the [`time::advance`](https://docs.rs/tokio/latest/tokio/time/fn.advance.html) function. Currently this function returns an opaque future (it's just an `async` function) and that makes it impossible to name the future type when used in a trait method, for example. So in the end we need to resort to a heap allocated (`Box<dyn Future>`) future.

**Describe the solution you'd like**

Could we make
https://github.com/tokio-rs/tokio/blob/910a1e2fcf8ebafd41c2841144c3a1037af7dc40/tokio/src/task/yield_now.rs#L39-L64

`yield_now` return the `YieldNow` future type (named; as part of its signature) and then expose that from `advance` (perhaps wrapping it in a distinct type) here:

https://github.com/tokio-rs/tokio/blob/910a1e2fcf8ebafd41c2841144c3a1037af7dc40/tokio/src/time/clock.rs#L198-L209

?

Any other ideas are welcome as well.

**Comment by Darksonn** [comment]
For some special methods, I'm okay with adding named future types, but I'm not convinced that this one qualifies. We're not going to do it for all async methods.

I would recommend that you use boxing for now, or wait for `impl Trait` in associated types to be implemented.
