### ISSUE TITLE
Fix documentation link to codec module/crate

### ISSUE THREAD

**Issue by marcospb19** [tokio-rs/tokio#5825]
I wanted to use the counterpart `tokio_util::io::SinkWriter` but there's none, instead the docs point to `"codec"` but the link is broken.

Codec link can be found here:

https://docs.rs/tokio-util/latest/tokio_util/io/struct.SinkWriter.html

Or here:

https://github.com/tokio-rs/tokio/blob/910a1e2fcf8ebafd41c2841144c3a1037af7dc40/tokio-util/src/io/sink_writer.rs#L26-L27

---

I believe the link could point to [`tokio_codec::BytesCodec`](https://docs.rs/tokio-codec/latest/tokio_codec/struct.BytesCodec.html) instead, but I'm not sure.

**Comment by Darksonn** [comment]
To fix this, replace `tokio_util` with `crate` in the link.
