### ISSUE TITLE
sometime  steal_work  may be miss tasks;

### ISSUE THREAD

**Issue by sxstd001** [tokio-rs/tokio#5841]
why not copy golang steal strategy.   tokio steal logic not serious;

**Comment by Noah-Kennedy** [comment]
@sxstd001 what's your issue with our steal strategy?

**Comment by Darksonn** [comment]
Tokio's implementation _does_ copy golang in many ways.

Closing due to lack of information.

**Comment by sxstd001** [comment]
Translation: I've been reading and analyzing for three days, and I realized I was wrong because I didn't consider Park's logic. I thought it was the same as "go", but in reality, Tokio's scheduling logic is better.
