### ISSUE TITLE
failed to lookup address information: Name or service not known

### ISSUE THREAD

**Issue by NOBLES5E** [tokio-rs/tokio#5851]
### Bug Description

I'm experiencing an intermittent error when trying to resolve domain names using `tokio::net::lookup_host` in parallel tasks. The issue seems to be related to the parallel lookup of a domain name. The error received is `called Result::unwrap() on an Err value: Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })`. The error does not occur consistently, and some lookups are successful before the error is encountered. This issue does not appear when using IP addresses instead of domain names.

Running `lookup_host` without spawning tasks in a while loop always succeeded.

### Minimal Reproduction

Here's a minimal example to reproduce the bug:

```rust
use tokio::net::lookup_host;
use std::time::Duration;

#[tokio::main]
async fn main() {
    let domain = "db.service.consul:443";
    for i in 1..100 {
        let domain = domain.to_string();
        tokio::task::spawn(async move {
            let _addresses = lookup_host(&domain).await.unwrap();
            eprintln!("{}", i);
        });
    }
    let _addresses = lookup_host(&domain).await.unwrap();
    eprintln!("{}", 100);
    tokio::time::sleep(Duration::from_secs(60)).await;
}
```

In this script, I expected each iteration to successfully resolve the domain and print out its corresponding number. However, at some point during the process, a panic occurs due to a failed address lookup.

### Info

* Tokio version: 1.29.1
* Operating system: Linux
* `rustc --version`: rustc 1.70.0 (90c541806 2023-05-31)

I'd like to kindly request further investigation into this matter. I suspect there may be a bug in how Tokio handles DNS lookups in parallel tasks.

**Comment by NOBLES5E** [comment]
Only happening on consul addresses, seems to be a consul related issue. Closing for now.

**Comment by Darksonn** [comment]
Tokio just uses the std implementation of DNS lookups.
