### ISSUE TITLE
`Child.kill` return `Ok` but the process is not killed

### ISSUE THREAD

**Issue by duskmoon314** [tokio-rs/tokio#5857]
**Version**

```
└── tokio v1.29.1
    └── tokio-macros v2.1.0 (proc-macro)
```

**Platform**

`Linux <machine name> 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

I want to exec a process and kill it once timeout. But my code exits and leaves the process running.

I tried this code:

```rust
// stress is an example, cmd can be another binary in my case
let mut cmd = tokio::process::Command::new("stress")
    .args(["-c", "1"])
    .spawn()?;

let sleep = tokio::time::sleep(tokio::time::Duration::from_secs(10));
tokio::pin!(sleep);

let _ = tokio::select! {
    _ = &mut sleep => {
        println!("Sleep done");
        let res = cmd.kill().await;
        println!("Kill result: {:?}", res);
    }
    res = cmd.wait() => {
        println!("Child exited: {:?}", res);
		// Do something with the result
    }
};
```

I expected to see this happen: cmd is killed and cannot see it in `htop`

Instead, this happened: 

The code exit successfully:
```shell
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/rust-test`
stress: info: [811294] dispatching hogs: 1 cpu, 0 io, 0 vm, 0 hdd
Sleep done
Kill result: Ok(())
```

But `stress` is still running:
```
❯ top | grep stress
 811295 star      20   0    3704    108      0 R 100.0   0.0   1:43.72 stress                                               
 811295 star      20   0    3704    108      0 R 100.0   0.0   1:46.74 stress                                               
 811295 star      20   0    3704    108      0 R 100.0   0.0   1:49.78 stress
...
```

I can kill it in htop with `SIGKILL`

---

A minimal code I can reproduce this (just include `fn main` and above)
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3cc453c3181d54cac4f8d3914ddf950f

Thr original code I find this issue (I'm trying to build a binary executor)
https://github.com/duskmoon314/rxec/blob/main/src/main.rs#L183-L223

**Comment by duskmoon314** [comment]
This might be a problem with `std` since I cannot successfully kill the child process using `std` either: https://stackoverflow.com/q/76663724/15766817

Haven't found out how to solve this. 😢

**Comment by ChrisDenton** [comment]
Is it possible that stress is itself spawning a new process? So the original process terminates but the new one carries on.

**Comment by duskmoon314** [comment]
> Is it possible that stress is itself spawning a new process? So the original process terminates, but the new one carries on.

I tested this with `stress -c 1 &` and `kill $!`. A process is running after `kill`. Thus, you are right. 👍 

I'm unsure why that process is not a child of the killed process. 😢

**Comment by duskmoon314** [comment]
It seems `stress` add the ability to listen parent's termination signal in the child process in `v1.0.6` [ref](https://github.com/resurrecting-open-source-projects/stress/pull/1). But I'm using `v1.0.5` provided by apt. I believe this is the reason why I cannot kill them.
