### ISSUE TITLE
Memory leak when futures are canceled

### ISSUE THREAD

**Issue by anatols** [tokio-rs/tokio#5861]
**Version**

`cargo tree | grep tokio`
```
└── tokio v1.29.1
    └── tokio-macros v2.1.0 (proc-macro)
```

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Linux _ 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**

Dear tokio contributors!

I believe I have found a memory leak in tokio that is caused by future cancellation in a task.

In short, waker object has a strong reference to the task, and the task has the size of the top level future plus some. Even if the future terminates (and is dropped), task memory will not be freed until any clone of the waker object is still alive.

On the one hand, this seems like a niche thing. On the other, for us the stars aligned in a way that one of our services started leaking 20GB a day. With no change to its code, just some change in API usage from the customers' side. Point is, it can be severe.

Longer story:

When using `tokio::select!`, it is possible to run two or more futures concurrently, and this way when one resolves, the other get canceled. There are other ways to reproduce the issue, but the one with select I think is the easiest.

When tokio executor polls tasks, it passes a waker to the top level future, which in turn passes it down the call chain. The leaf futures that do not resolve immediately are capturing this waker (a clone of) to later signal that the future can be polled again.

When select is used in the top level future of a task, and one of the branches captures the waker, and the top level future is canceled, the task memory is not freed until all waker clones are dropped. And I can imagine it can get stuck forever (e.g. awaiting on some data that never arrives).

I've taken a look through the tokio source code, and, although it's a bit overwhelming (and I might be totally wrong in my conclusions), I think the issue boils down to the fact that the task stores
the future in an enum here:

`tokio/tokio/src/runtime/task/core.rs`

```rust
/// Either the future or the output.
pub(super) enum Stage<T: Future> {
    Running(T),
    Finished(super::Result<T::Output>),
    Consumed,
}

```
This enum has the size of at least the size of the future. When the task terminates it flips the enum to the `Consumed` state, and further awakes are noops, but the size of the enum does not change obviously.

I believe this enum is in turn wrapped in a bunch of structures, with `RawTask` being the top. The `RawTask` implements a bespoke version of ref counting. I believe wakers hold a reference here, and thus prevent the `Stage` enum from being dropped.

I've put together a minimal example to reproduce the issue.

```toml
[dependencies]
memory-stats = "1.1.0"
tokio = { version = "1", features = ["full"] }
```

```rust
use std::{
    future::Future,
    mem,
    sync::{
        atomic::{AtomicUsize, Ordering},
        Mutex,
    },
    task::Waker,
};

static WAKERS: Mutex<Vec<Waker>> = Mutex::new(vec![]);
static TOTAL_BLOAT_CREATED: AtomicUsize = AtomicUsize::new(0);
static TOTAL_BLOAT_DROPPED: AtomicUsize = AtomicUsize::new(0);
const BLOAT_SIZE: usize = 2000;

#[tokio::main]
async fn main() {
    println!(
        "mem used {}M",
        memory_stats::memory_stats().unwrap().physical_mem / (1024 * 1024)
    );
    let mut total_size_of_tasks = 0;
    for _ in 0..100000 {
        
        let task = async {

            // A select on two futures, one that awaits something external, the other that awaits a
            // cancellation signal (for this example cancellation is immediate).
            tokio::select! {
                // 'biased' to avoid random selection. We need select to poll the bloated future at least
                // once.
                // In real life scenario the cancellation will not be immediate, so the bloated future
                // will have a chance to get polled even in a non-biased select.
                biased;

                _ = async {
                    // Artificially bloated future for demonstration. This one gets cancelled.
                    // In real life, the size of this future will come from its local variables, and is
                    // normally of kilobytes magnitude.
                    //
                    // Note that with debug assertions on, tokio::spawn will box the passed in future
                    // if it's larger than 2048 bytes, so it will leak much less (the size of Box instead
                    // of the size of the original future). Hence only 2000B of bloat here and the outer loop,
                    // to make it easier to reproduce/demonstrate.
                    //
                    // What's more important, is that in release mode (with debug assertions off)
                    // the futures will not be boxed, so there's no limit on the leaked size.
                    let _bloat = Bloat::new();
                    WakerCapture.await;
                } => (),

                _ = async {
                    // Do nothing, immediately exits the select.
                    // In real life scenario this would await some cancellation signal.
                } => ()
            }
        };
        assert!(mem::size_of_val(&task) >= BLOAT_SIZE);
        total_size_of_tasks += mem::size_of_val(&task);

        // spawn the task and immediately wait for its completion.
        tokio::spawn(task).await.unwrap();
    }

    // At this point we expect all the futures to be dropped
    assert_eq!(
        TOTAL_BLOAT_CREATED.load(Ordering::Relaxed),
        TOTAL_BLOAT_DROPPED.load(Ordering::Relaxed)
    );
    println!(
        "all tasks completed, total size of tasks {}M, total bloat: {}M",
        total_size_of_tasks / (1024 * 1024),
        TOTAL_BLOAT_CREATED.load(Ordering::Relaxed) / (1024 * 1024)
    );

    // Although the futures were dropped, the underlying memory is not freed, unless the wakers
    // are dropped too.
    println!(
        "mem used {}M",
        memory_stats::memory_stats().unwrap().physical_mem / (1024 * 1024)
    );

    {
        let mut wakers = WAKERS.lock().unwrap();
        println!("releasing {} wakers", wakers.len());
        wakers.clear();
        wakers.shrink_to_fit();
    }

    println!(
        "mem used {}M",
        memory_stats::memory_stats().unwrap().physical_mem / (1024 * 1024)
    );
}

struct WakerCapture;

impl Future for WakerCapture {
    type Output = ();

    fn poll(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        // Capture a clone of the waker in some "external" location, never actually wake.
        // (the static mutex is just for demonstration, can be anything else that holds on to the waker).
        WAKERS.lock().unwrap().push(cx.waker().clone());
        std::task::Poll::Pending
    }
}

struct Bloat([u8; BLOAT_SIZE]);

impl Bloat {
    fn new() -> Self {
        let bloat = Self([42; BLOAT_SIZE]);
        TOTAL_BLOAT_CREATED.fetch_add(mem::size_of_val(&bloat), Ordering::Relaxed);
        bloat
    }
}

impl Drop for Bloat {
    // Implementing drop also ensures the compiler won't throw it away as unused
    fn drop(&mut self) {
        TOTAL_BLOAT_DROPPED.fetch_add(mem::size_of_val(self), Ordering::Relaxed);
    }
}

```

The output on my machine:
```
mem used 3M
all tasks completed, total size of tasks 193M, total bloat: 190M
mem used 225M
releasing 100000 wakers
mem used 4M
```
Basically, it leaked ~220MB in around 5 seconds, and only gave it back when wakers were dropped.

In our live system we could mitigate the issue because we were in control of the code that retains the waker. However, I can imagine it would have been a problem if the awaited future came from some library. E.g. awaiting on some socket accept etc.

**Comment by Darksonn** [comment]
This is intentional. Ultimately, the waker has a pointer to something, and that pointer cannot become dangling while there are still wakers left. We could mitigate this by making a separate allocation for the wakers so that they keep less memory alive, but that makes the common case more expensive by performing multiple allocations per task.

Note that you can wrap futures being spawned in a box to reduce the size of the task allocation. This would have the same effect as splitting the allocation internally.

**Comment by anatols** [comment]
I get it that the waker has no way of knowing if the task is still alive. Normally in such case I'd expect a weak pointer with a separate allocation for the strong and weak ref counters. I would imagine the ref counters could be pooled, so no extra allocation per task would be necessary.

Wrapping futures in boxes would mean it's leaking in sizes of Box (so, a size of 1 pointer) instead of sizes of futures. It is a fair mitigation, but strictly speaking it's still leaking.

**Comment by Darksonn** [comment]
To be clear `std::rc::Weak` and `std::sync::Weak` do exactly the same as Tokio here. The actual value is dropped, but an allocation large enough for the entire value stays around.

**Comment by anatols** [comment]
Interesting, I did not realize std ones work like this. I was thinking more along the lines of how, for example, std::shared_ptr is implemented in C++, where it has the control block (ref counters) and the data separated.
Tasks (the data) are already allocated separately, and since tokio is in control it can have a pool of control blocks.

**Comment by Darksonn** [comment]
I understand the suggestion, but I don't think the extra complexity in the implementation is worth it.
