### ISSUE TITLE
await is intended to be a keyword

### ISSUE THREAD

**Issue by Nemo157** [tokio-rs/tokio#587]
The keywordification hasn’t happened yet, but it will not be possible to define an override of the `await!` macro once it has happened. I’m raising this now so alternative solutions for `tokio-async-await` can be considered before it is actually added to the 2018 keyword list.

**Comment by carllerche** [comment]
Thanks for the clarification. I am aware there has been talk about it, but I have not see any movement on that front. If it happens, it is no big deal, I can switch to any other word (`wait`, `get`, `block` ...).

That said, it seems that switching to a keyword is low value API wise and comes at a downside: preventing the ability to implement these compatibility layers.

@withoutboats thoughts?

**Comment by withoutboats** [comment]
Its unfortunate but the intended consequence. We plan to replace the macro with a proper keyword once we settle syntax debates, which would need to break this crate; our only opportunity to do that is the 2018 edition.

Its possible that we should not have `await!` at all, and instead the macro form is `wait!` (etc) everywhere, not just in this library.

**Comment by withoutboats** [comment]
I've wondered if there's a way we could uplift your macro's behavior into std without uplifting futures 0.1, but I don't know how.

**Comment by withoutboats** [comment]
See rust-lang/rust#53834, in which I propose a solution that will allow you to keep the `await!` name for your macro.

**Comment by carllerche** [comment]
Closing as there is no further action to take.
