### ISSUE TITLE
Add ability for `sync::watch::Receiver` to flag current item as unseen

### ISSUE THREAD

**Issue by allada** [tokio-rs/tokio#5871]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for a `sync::watch::Receiver` to be created and mark the current item as unseen without notifying all `Receiver`s.

**Describe the solution you'd like**
Add a function on `Receiver` that allows the next time the `Receiver` calls `.has_changed()` (or similar) it returns true.

**Describe alternatives you've considered**
Add similar function to `Sender::subscribe()` where newly created `Receiver` has a message pending and `Receiver::clone()`-like method that does the same thing.

**Use case**
* Client connects with some request.
* These requests can be multiplexed, so only 1 unique request is ever being processed, but clients all get notified of state changes (only most recent state matters).
* When first client connects they are notified of a change 100% of the time because `sync::watch::channel()` always creates a `Receiver` with a pending message.
* When a new client connects, we want to notify the client of the current state.

This is a very minor security concern for us because unless we hold a copy of the last seen data for every `Receiver` we are forced to re-send a bogus state change to every `Receiver`, which can then be used by the receiver client to get hints on when people are connecting and disconnecting (yes, this could be solved on a higher level, but requires a lot of needless work & memory).

**Comment by victor-timofei** [comment]
If no one is working on this I'd like to pick this up.

**Comment by Darksonn** [comment]
Go ahead.
