### ISSUE TITLE
`tokio::runtime::EnterGuard` is `!Send` from `v1.29.0`

### ISSUE THREAD

**Issue by rise0chen** [tokio-rs/tokio#5879]
**Version**
^1.29.0

**Description**
![image](https://github.com/tokio-rs/tokio/assets/12853908/75b968a2-4f31-4220-b02a-127793c3bd0e)

---

![image](https://github.com/tokio-rs/tokio/assets/12853908/62b6f382-81d2-44c3-8590-04a16a3b99e9)

**Comment by Darksonn** [comment]
Please see the changelog: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.29.0
