### ISSUE TITLE
#[tokio:test] causes weird intellisense on the last line of the test

### ISSUE THREAD

**Issue by escritorio-gustavo** [tokio-rs/tokio#5882]
**Version**
tokio v1.28.0
tokio-macros v2.1.0 (proc-macro)
tokio-util v0.7.8
tokio v1.28.0 (*)
tokio v1.28.0 (*)
tokio v1.28.0 (*)
tokio-native-tls v0.3.1
tokio v1.28.0 (*)
tokio v1.28.0 (*)
tokio-native-tls v0.3.1 (*)
tokio v1.28.0 (*)

**Platform**
Windows 11 64-bit Build: 22621.1992

**Description**
Enter your issue details here.
One way to structure the description:

When using the `#[tokio:test]` macro, the last line of the test function gets the syntax highliting of a function call, hovering over it indicates a call to `new_current_thread`. This occurs with macro calls (such as `assert!`), method calls on objects, and basically any identifier at the start of the last line (even if the identifier doesnt exist)

I tried this code:
```rust
mod test {
    #[tokio:test]
    async fn my_test() {
        assert!(true);
    }
}
```
I expected to see this happen:
`assert!` is highlighted as a macro call, hovering over it shows docs about the assert macro

Instead, this happened:
 `assert!` is highlighted as a function call:
![image](https://github.com/tokio-rs/tokio/assets/131818645/fa5a0e38-0ece-4cb4-8206-6fe5e7435655)

Hovering over it shows `new_current_thread` docs:
![image](https://github.com/tokio-rs/tokio/assets/131818645/cbc579cf-4886-4bbf-bffa-832adc714f3e)

This happens to any identifier even if it doesn't exist:
![image](https://github.com/tokio-rs/tokio/assets/131818645/901a75a2-068f-42e4-a726-b5852a4f1f63)

This does *not* happen to `let` bindings, literals or inside control flow blocks, such as `if` or `match`:
![image](https://github.com/tokio-rs/tokio/assets/131818645/16acdcba-4370-4e3d-b37b-a77844034213)
![image](https://github.com/tokio-rs/tokio/assets/131818645/30d9edb3-b8d2-4774-af4d-bbb139769768)

**Comment by taiki-e** [comment]
Is this the same issue as #5518 (except for macro is `#[tokio:test]` not `#[tokio:main]`)?

**Comment by escritorio-gustavo** [comment]
Yes, it does seem to be the same problem affecting `#[tokio:test]`

**Comment by Darksonn** [comment]
I'm going to close this as a duplicate.
