### ISSUE TITLE
Panic with misaligned pointer dereference: address must be a multiple of 0x80 on initialization.

### ISSUE THREAD

**Issue by chyyran** [tokio-rs/tokio#5883]
**Version**

* tokio 1.29.0
* tokio 1.29.1

**Platform**
`Linux ip-10-0-179-120 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` using `x86_64-unknown-linux-musl` toolchain.

**Description**
When initializing a `Runtime` using `Builder::new_multi_thread` within a `lazy_static` or `once_cell::Lazy`, panic with 

```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x80 but is 0x59a5a050820', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:240:32
```

Partial backtrace:
```
   7: tokio::runtime::task::core::Cell<T,S>::new
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:240:32
   8: tokio::runtime::task::raw::RawTask::new
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:164:33
   9: tokio::runtime::task::new_task
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:295:19
  10: tokio::runtime::task::unowned
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:319:38
  11: tokio::runtime::blocking::pool::Spawner::spawn_blocking_inner
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:384:30
  12: tokio::runtime::blocking::pool::Spawner::spawn_blocking
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:301:17
  13: tokio::runtime::handle::Handle::spawn_blocking
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/handle.rs:217:9
  14: tokio::runtime::blocking::pool::spawn_blocking
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:183:5
  15: tokio::runtime::scheduler::multi_thread::worker::Launch::launch
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:447:13
  16: tokio::runtime::builder::Builder::build_threaded_runtime
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/builder.rs:1213:13
  17: tokio::runtime::builder::Builder::build
             at usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/builder.rs:658:34
```

This issue does not occur in tokio 1.28

**Comment by carllerche** [comment]
cc @pnkfelix

**Comment by carllerche** [comment]
It looks like this is failing in `Box::new`. I suspect it is a bug with rustic, musl, or something else at that level. If we can figure out what the root of the bug is, we can look into work around until the bug is fixed.

**Comment by chyyran** [comment]
@Darksonn 
```
pub static TOKIO_RUNTIME: Lazy<RwLock<Runtime>> = Lazy::new(|| {
  let runtime = Builder::new_multi_thread()
    .enable_all()
    .build()
    .expect("Error creating tokio runtime");
  RwLock::new(Some(runtime))
});
```

**Comment by taiki-e** [comment]
Could you provide information about the build environment? Specifically, what versions of rustc and musl are used, which tool is used if cross-compilation, and whether dynamic or static linking is used.

The version of musl used to compile the standard library changed in rust 1.71, so I'm wondering if that may have caused the problem. [^1]

[^1]: The fact that I had encountered a case not long ago where musl version mismatches caused segfaults even on 64-bit architectures motivated me to [support](https://github.com/taiki-e/setup-cross-toolchain-action/commit/cc018525bd78a6827dc86a29e32dc245704b69ed#diff-f121df8f1f148ef72415f98dd27089a0e6cec3ec939840286358170e5e20c990R163-R168) musl in setup-cross-toolchain-action and to [move](https://github.com/taiki-e/cargo-llvm-cov/commit/13c3af77988ec254dbfcd1754823ad51ccd69f0f) from cross to setup-cross-toolchain-action. However, the architecture I actually encountered problems with was mips64, not x86_64.

**Comment by carllerche** [comment]
According to @chyyran in [Discord](https://discord.com/channels/500028886025895936/500336346770964480/1131310597108142170) this is due to an issue in mimalloc. Closing.
