### ISSUE TITLE
Internal runtime error, entered unreachable code

### ISSUE THREAD

**Issue by Gelbpunkt** [tokio-rs/tokio#5884]
**Version**

tokio v1.29.1

**Platform**

Host kernel:
`Linux ceres 6.5.0-0.rc1.20230716gt831fe284.216.vanilla.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul 16 06:46:34 UTC 2023 x86_64 GNU/Linux`

Environment:
Alpine Linux 3.17 container

**Description**

I'm trying to benchmark my websocket library and under certain load scenarios, tokio aborts with the following message:

```
thread 'main' panicked at 'internal error: entered unreachable code: unexpected stage', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:304:26
```

Steps to reproduce:

* Checkout <https://github.com/Gelbpunkt/tokio-websockets/commit/987699d37a1eeac8b3bb21cfa07540db4b25ad1d>
* To see the error message, comment out `panic_immediate_abort` in `.cargo/config.toml`
* The source code for the binary you're about to crash is in `examples/echo-server.rs` (both unconstrainted  and without will crash)
* Build the docker image (podman/docker should be interchangable): `podman build -t bench:latest -f benches/Dockerfile .`
* Run the specific one that fails by entering the following:
```bash
$ podman run \
    --rm \
    -it \
    --privileged \
    --ulimit=host \
    --ipc=host \
    --cgroups=disabled \
    --pids-limit -1 \
    --name bench \
    --security-opt label=disable \
    --userns=keep-id \
    -v $(pwd)/benches:/benches \
    bench:latest ash
~ $ /usr/bin/tokio-websockets
(nothing will show until it crashes)
```
In another shell, run:
```bash
$ podman exec -it bench ash
~ $ /usr/bin/load_test 10 0.0.0.0 3000 0 0 16384
ERROR: outstanding bytes negative
(server should have crashed now)
```

You can reach out to me on the tokio discord `@adrianyyy`

**Comment by Darksonn** [comment]
What happens if you run that on an earlier version of Tokio?

Also, do you have a reproduction that does not depend on docker ...?

**Comment by Gelbpunkt** [comment]
> Also, do you have a reproduction that does not depend on docker ...?

Yes, I can also reproduce it on my glibc host.

Steps:
* Checkout my repo at the commit I linked in the post
* Comment out `panic_immediate_abort` in `.cargo/config.toml` to see the panic
* Run `cargo run --release --example echo-server` and keep it running
* Build the load_test tool:
```sh
$ git clone git clone --recursive https://github.com/uNetworking/uWebSockets.git
$ cd uWebSockets
$ make -C benchmarks
$ benchmarks/load_test 10 0.0.0.0 3000 0 16384
(server will crash)
```

> What happens if you run that on an earlier version of Tokio?

`cargo minimal-versions run --release --example echo-server` using Tokio 1.6.1 also enter the same unreachable code.
