### ISSUE TITLE
Opt-in limiting the spawn_blocking when on a spawn_blocking task

### ISSUE THREAD

**Issue by koivunej** [tokio-rs/tokio#5889]
**Is your feature request related to a problem? Please describe.**

It is easy to create deadlocks when a `spawn_blocking` when the given FnOnce uses `Handle::block_on` if the called future for example uses `tokio::fs` and there can be multiple of these tasks running at the same time. They will eventually reach the number of allowed runtime threads.

**Describe the solution you'd like**

At minimum it would be great to *control* whether `spawn_blocking` can be used with a drop guard alike structure. Example:

```rust
use std::panic::{catch_unwind, AssertUnwindSafe, panic_any};

let handle = tokio::runtime::Handle::current();

// not allowed to call if not in spawn_blocking -- debatable.
//
// it might be there's a usecase where a particular runtime should not use
// `tokio::fs` but this is rather difficult route to disable it on all
// worker threads.
catch_unwind(AssertUnwindSafe(|| {
    denied = handle.disable_spawn_blocking();
    Unreachable
}).unwrap_err();

tokio::task::spawn_blocking(move || {
    // this would be thread local counter
    let denied = handle.disable_spawn_blocking();

    // now more spawn_blocking would panic
    catch_unwind(AssertUnwindSafe(|| {
        handle.block_on(async move {
            tokio::task::spawn_blocking(|| Unreachable)
        })
    })).unwrap_err();
    
    // it's a thread local counter not a boolean
    catch_unwind(AssertUnwindSafe(|| {
        let _multiple_times_is_fine = handle.disable_spawn_blocking();
    })).unwrap();
    
    drop(denied);
    
    // now it's allowed to spawn_blocking even from this context.
    let _no_panic = catch_unwind(std::panic::AssertUnwindSafe(|| {
        handle.block_on(async move {
            tokio::task::spawn_blocking(|| println!("now allowed"));
        })
    })).unwrap();

}).await.unwrap();

struct Unreachable;
```

Unsure if any other API way is possible while allowing *sometimes* `spawn_blocking` threads to `spawn_blocking` more since we cannot add parameters to spawn_blocking.

**Describe alternatives you've considered**

Wrapping all of tokio (because in some cases we use tokio::fs) but that is not ergonomic, it is error prone etc.

**Additional context**

I guess in general adding these kind of "blocks" might not be healthy for the crate API but giving the ability to express where `spawn_blocking` work is not expected to create more `spawn_blocking` work seems like an easy way to avoid deadlocks aside from careful code review.

**Comment by koivunej** [comment]
I've been thinking about the global allow/deny, even from async workers. Would it make sense for this to be opt-in at the `tokio::runtime::Builder` with options for enabling (default) or disabling spawn_blocking by default. Then it would require that you cannot just disable via a guard, but also enable? Starts to get quite complicated.

The simple thread-local approach should not interfere with what can happen as a result of `block_in_place` that a core moves to a spawn_blocking thread.

**Comment by Darksonn** [comment]
I see why this would be useful, but there's a tradeoff with the additional api surface and maintenance burden. Unfortunately, I don't think this feature wins that tradeoff, so I'm going to close this.
