### ISSUE TITLE
Using `stdin` prevents `tokio::run` from shutting down.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#589]
## Context

* `tokio::run` will only shutdown once all spawned tasks have completed. The idea is when shutdown is desired, the shutdown process is responsible for coordinating with running tasks to inform them to terminate.
* The `stdin` implementation in tokio-fs uses `tokio_threadpool::blocking` to allow the current task to perform a blocking operation. Trying to read on stdin will block indefinitely until input is received on `stdin`.

## Description

A problem arises when combining shutdown with reading from `stdin`. Because the stdin task is blocked in reading, it is unable to receive a shutdown signal to force the task to complete. This is because the task itself is blocked in the stdin read call.

## Solutions

The solution is not entirely clear. My guess is that we will need #588 first and then the current `tokio_threadpool::blocking` API will need to have additional documentation to indicate that it only supports *short* blocking tasks. Then `stdin` support could be updated to use the general purpose blocking strategy.

**Comment by canndrew** [comment]
Why are tokio's stdio types blocking? This was surprising to me and it took me a while to figure out why my program kept locking up. I eventually fixed my problems my implementing my own, non-blocking, stdin/stdout types, but it's weird that I had to do that :/

**Comment by carllerche** [comment]
The stdin / stdout types are global. If they are switched to non-blocking mode, then that impacts the entire process, not just Tokio. Other calls (like, to `println`) expect a blocking fd.

If you have fully control of the process, you can use your own stdin / stdout types that are non-blocking.

**Comment by canndrew** [comment]
That makes sense. Although I think a non-blocking stdio should be provided by tokio as well. In my case I do have full control of the process and I don't want to have to drop down to the level of `mio`, `unsafe` and syscalls just to read/write stdin/stdout.

Maybe it would be good to add `async_std{in,out}` types to `tokio::io` with a note in the documentation explaining why the sync types are usually more appropriate.

**Comment by carllerche** [comment]
I'm open to this.

How would you suggest switching `stdin` / `stdout` to non-blocking mode? It should be done once per process, ideally in the `main` function or some other "initialization" function.

**Comment by rotty** [comment]
Here is a [writeup](https://jdebp.eu/FGA/dont-set-shared-file-descriptors-to-non-blocking-mode.html) about the potential issues of setting stdin/stdout/stderr non-blocking (which @carllerche already [mentioned](https://github.com/tokio-rs/tokio/issues/589#issuecomment-425693195). At the end, the writeup links to an [article by DJB](https://cr.yp.to/unix/nonblock.html), who suggests a per-syscall nonblock flag. I'm not sure if any *NIX implements that solution.

**Comment by rotty** [comment]
Opening `/dev/stdin` (and friends) with `O_NONBLOCK` seems like a solution that avoids the pitfalls of setting FD 0/1/2 non-blocking.

**Comment by rotty** [comment]
Note that apparently, calling `open()` on `/dev/stdin` returning a file descriptor independent of the regular `STDIN_FILENO` (aka as FD 0) is not portable. It seems to work that way under Linux, but other Unix derivates seem to handle it like `dup(STDIN_FILENO)`, i.e. sharing the file handle state, including the `O_NONBLOCK` flag. 

I think the only portable (across Unix-likes, that is) way is to actually set `STDIN_FILENO` to be non-blocking, and require the invoking program to pass a newly-generated file descriptor (e.g. the reading end of a pipe) for FD 0, using `dup2()` after forking the child process. At that point, you might as well pass an arbitrary file descriptor number to the child via a command-line argument, and use that instead, avoiding potentially messing up libraries or other code used which expects `STDIN_FILENO` to be blocking.

**Comment by ramosbugs** [comment]
> Note that apparently, calling `open()` on `/dev/stdin` returning a file descriptor independent of the regular `STDIN_FILENO` (aka as FD 0) is not portable. It seems to work that way under Linux, but other Unix derivates seem to handle it like `dup(STDIN_FILENO)`, i.e. sharing the file handle state, including the `O_NONBLOCK` flag.

Thanks for adding these details! This issue has been affecting one of my projects as well, and this has been an interesting thread to monitor. Do you happen to have references to code and/or docs that point to the non-Linux behavior?

**Comment by parthsane** [comment]
@canndrew I need to implement my own non-blocking stdio too. 
Could you help me with that?

**Comment by totorigolo** [comment]
I don't know if that helps, but as a workaround for async stdin I'm just spawning a thread and using an async channel.

**Comment by canndrew** [comment]
@parthsane you could look here: https://github.com/canndrew/termcandy/blob/master/src/io/non_blocking.rs

**Comment by canndrew** [comment]
> How would you suggest switching stdin / stdout to non-blocking mode? It should be done once per process, ideally in the main function or some other "initialization" function.

Maybe it should be a feature flag. If the feature is enabled then `tokio::io::{stdin, stdout}` first set the file descriptor to non-blocking (if it hasn't already been done), but otherwise they spawn a background thread to do blocking reads/writes and return a handle for doing async reads/writes to an intermediate buffer.

That way an application can opt-in to unbuffered, true-async stdio, and all its library dependencies would inherit that behaviour, but otherwise you still get `Stdin`/`Stdout` types which behave async and which don't interfere with the rest of the process.

**Comment by carllerche** [comment]
This is fixed on master.

**Comment by Cldfire** [comment]
Does the closure of this issue mean that the warning added in #876 no longer applies and can be removed?
