### ISSUE TITLE
Unexpected Behavior of Notify::notify_waiters() in select! Block

### ISSUE THREAD

**Issue by vincent-herlemont** [tokio-rs/tokio#5896]
**Version**
The version of `tokio` I am using is 1.29.1.

**Platform**
The output of `uname -a` is: Linux Ubuntu 20.04.

**Description**
Unexpected behavior of `Notify::notify_waiters()` in a `select!` block.

I tried the following code:

```rust
#[test]
fn test() {
    let runtime = Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("failed to create runtime");

    let shutdown = Arc::new(Notify::new());
    let shutdown_for_notified = shutdown.clone();
    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel();

    runtime.spawn(async move {
        loop {
            tokio::time::sleep(Duration::from_millis(900)).await;
            select! {
                _ = shutdown_for_notified.notified() => {
                    println!("shutdown");
                    break;
                },
                rx = rx.recv() => {
                    println!("received message: {:?}", rx);
                },
            }
        }
    });

    let shutdown_handler = std::thread::spawn(move || {
        std::thread::sleep(Duration::from_secs(1));
        shutdown.notify_waiters();
        println!("notified shutdown");
        std::thread::sleep(Duration::from_secs(3));
    });

    for i in 0..100 {
        tx.send(i).expect("failed to send message");
    }

    shutdown_handler.join().unwrap();
}
```

The output of this code is:

```
received message: Some(0)
notified shutdown
received message: Some(1)
received message: Some(2)
received message: Some(3)
```

I expected to see the loop break immediately after `shutdown.notify_waiters()` is called, without processing any additional messages from the `rx` channel. This is because the `notify_waiters()` method should wake up all tasks waiting on the `Notify` instance, which in this case includes the task waiting inside the `select!` block.

However, what actually happened is that the `rx` channel continues to be consumed even after `shutdown.notify_waiters()` is called.

Interestingly, if I use `notify_one()` instead of `notify_waiters()`, the loop breaks as expected:

```
received message: Some(0)
notified shutdown
shutdown
```

**Comment by Darksonn** [comment]
If `notify_waiters` is called during the call to sleep, then you wont wake it up because the `notified` future is created *after* the call to `notify_waiters`.

It's different with `notify_one` due to the permit.

**Comment by vincent-herlemont** [comment]
@Darksonn ho I understand, thanks you. How I can deal with that properly?

**Comment by Darksonn** [comment]
What, exactly, is the thing you're trying to do?

**Comment by vincent-herlemont** [comment]
@Darksonn The context is an embedded ffi library that does not handle asynchronous calls. Consequently, I would need to send a signal to properly shut down all processes (using a combination of infinite `loop` and `select!`) that were created in the tokio runtime spawns.

**Comment by vincent-herlemont** [comment]
@Darksonn My bad, If I put the notifed just before, that would solve the issue necessarily...

```rust
...
            loop {
                let notified = shutdown_for_notified.notified();
                tokio::time::sleep(Duration::from_millis(900)).await;
                select! {
                    _ = notified => {
                        println!("shutdown");
                        break;
                    },
                    rx = rx.recv() => {
                        println!("received message: {:?}", rx);
                    },
                }
            }
```

**Comment by Darksonn** [comment]
How about using a `CancellationToken`?

**Comment by vincent-herlemont** [comment]
@Darksonn thanks for pointing out! It's exactly what I need.
