### ISSUE TITLE
Docs prose say Sleep doesn't implement Unpin, but sidebar does

### ISSUE THREAD

**Issue by jrose-signal** [tokio-rs/tokio#5901]
Since v1.1.0, Sleep has been documented as follows:

> This type does not implement the `Unpin` trait, which means that if you use it with [`select!`](https://docs.rs/tokio/1.1.0/tokio/macro.select.html) or by calling `poll`, you have to pin it first. If you use it with `.await`, this does not apply.

But the autogenerated sidebar says it does implement Unpin, since v1.0.1. I did find #3267 and #3278 and even https://github.com/tokio-rs/tokio/pull/3278#discussion_r544616612:

> We should have a test that asserts that `Sleep` is `!Unpin` (same for other types that contain pinned `Sleep`s).

~~And yet Sleep is Unpin.~~ I tested locally incorrectly and thought Sleep was *actually* Unpin, but it's just the autogenerated docs that are confusing.

**Comment by sfackler** [comment]
The definition of the impl comes from pin project, and is conditional:

```rust
impl<'__pin> Unpin for Sleep
where
    __Origin<'__pin>: Unpin,
```

**Comment by taiki-e** [comment]
This is a rustdoc bug: https://github.com/rust-lang/rust/issues/80481

We may want to mention in the documentation that rustdoc cannot display this correctly.

**Comment by Darksonn** [comment]
It's a bit annoying, but we could fix this by not using pin-project-lite for `Sleep`. Or maybe we could get a feature in pin-project-lite that supports this, where we can say "this type should never be `Unpin`" and have the macro output something that makes the docs say that its never `Unpin`?

**Comment by taiki-e** [comment]
I think it is ok to add pin-project's [!Unpin](https://docs.rs/pin-project/latest/pin_project/attr.pin_project.html#unpin) equivalent to pin-project-lite and hide the Unpin implementation from the document.

As I [said previously](https://github.com/tokio-rs/tokio/pull/3330#pullrequestreview-558439663), I do not favor making our code vulnerable to human error to avoid rustdoc issue.
