### ISSUE TITLE
Stabilise Command::raw_arg

### ISSUE THREAD

**Issue by passcod** [tokio-rs/tokio#5929]
[`raw_arg` in std](https://doc.rust-lang.org/stable/std/os/windows/process/trait.CommandExt.html#tymethod.raw_arg) is stable from Rust 1.62, and Tokio 1.30's MSRV is 1.63.

The note in Tokio's `raw_arg` (added in #5704) documentation says:

> Note: This is an unstable API but will be stabilised once tokio’s MSRV is sufficiently new.

I think that's the case now :)

**Comment by Darksonn** [comment]
I'm that case, a PR world be appreciated. Otherwise I can look at it later.
