### ISSUE TITLE
Thread-local storage Runtime with normal Runtime panics on drop

### ISSUE THREAD

**Issue by NPN** [tokio-rs/tokio#593]
## Version

`tokio v0.1.8`

## Platform

`Linux HOSTNAME 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux`

## Description

Apologies if I am missing some hidden caveat of `tokio`, `futures`, `thread_local!`, or any other code, but the following code causes a panic when I wouldn't expect it to:

```rust
use std::cell::RefCell;
use tokio::runtime::Runtime;

thread_local!(
    static R: RefCell<Option<Runtime>> = RefCell::new(None);
);

fn main() {
    R.with(|cell| {
        *cell.borrow_mut() = Some(Runtime::new().unwrap());
    });
    Runtime::new().unwrap();
}
```
The backtrace:
```
thread 'main' panicked at 'cannot access a TLS value during or after it is destroyed: AccessError', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:248
  11: futures::task_impl::std::ThreadNotify::with_current
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/std/mod.rs:506
  12: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/task_impl/std/mod.rs:240
  13: futures::future::Future::wait
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.23/src/future/mod.rs:299
  14: <tokio::runtime::Runtime as core::ops::drop::Drop>::drop
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.8/src/runtime/mod.rs:490
  15: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  16: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  17: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  18: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  19: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  20: std::thread::local::fast::destroy_value
             at /checkout/src/libstd/thread/local.rs:402
  21: __call_tls_dtors
  22: __run_exit_handlers
  23: exit
  24: __libc_start_main
  25: _start
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
From looking at the backtrace and source code, the code panicked because `wait_future` tried to notify the current thread, which involved trying to call `.with()` on a thread-local variable (`CURRENT_THREAD_NOTIFY`) whose destructor was running or had already been run.

That makes sense, but what does the second `Runtime` have to do with it? The code doesn't crash if a second `Runtime` isn't created and dropped, which shows that the thread-local `Runtime` can be cleaned up correctly, but isn't when another `Runtime` is involved. Furthermore, the code only crashes if the second `Runtime` is created after the thread-local `Runtime`.

I know that the panic can be avoided if the thread-local `Runtime` is explicitly shutdown. But, I'm wondering if there's a way to avoid that and safely drop the thread-local `Runtime` in this situation.

**Comment by carllerche** [comment]
Thanks for the report. I believe #628 fixes this problem. Would you be able to test?

**Comment by stjepang** [comment]
@carllerche I doubt it.

This particular stacktrace is reporting a panic in `ThreadNotify::with_current`, which attempts to access a different thread-local (in the `futures` crate):

```rust
thread_local! {
    static CURRENT_THREAD_NOTIFY: Arc<ThreadNotify> = Arc::new(ThreadNotify {
        state: AtomicUsize::new(IDLE),
        mutex: Mutex::new(()),
        condvar: Condvar::new(),
    });
}

impl ThreadNotify {
    fn with_current<F, R>(f: F) -> R
        where F: FnOnce(&Arc<ThreadNotify>) -> R,
    {
        CURRENT_THREAD_NOTIFY.with(|notify| f(notify))
    }

    // ...
}
```

Fixing this issue completely might be quite an effort.

**Comment by NPN** [comment]
Indeed, I'm still getting the panic.

**Comment by DoumanAsh** [comment]
TLS dtor order is out of control for user, I think it would be better to advise against putting it there plainly.
Instead user should manually clean TLS.

**Comment by carllerche** [comment]
I'm pretty sure the issue is [this](https://github.com/tokio-rs/tokio/blob/06c473e62842d257ed275497ce906710ea3f8e19/tokio-threadpool/src/thread_pool.rs#L186). Calling `wait` will access a thread-local.

**Comment by carllerche** [comment]
Looks like this is fixed. I submitted #2011 which adds the provided repro as a test.

**Comment by carllerche** [comment]
Well that is interesting, it seems that it only fails on linux and not OS X...
