### ISSUE TITLE
Tokio 1.25 MSRV breakage on Windows

### ISSUE THREAD

**Issue by TheBlueMatt** [tokio-rs/tokio#5934]
**Version**
tokio 1.25.1 building targeting windows

**Description**
`windows-targets 0.48.2` updated its edition key to 2021 in https://github.com/microsoft/windows-rs/pull/2568 which broke building tokio 1.25's MSRV.

**Comment by kennykerr** [comment]
Hmm didn't realize the edition was a breaking change. If so, I can yank 0.48.2 and publish 0.48.3 with 2018.

**Comment by Darksonn** [comment]
Thank you for reporting this.

Although we have removed dependencies that transitively broke our MSRV in the past, we aren't planning on doing so for the windows family of crates. This is consistent with our policy: 

> Note that although we try to avoid the situation where a dependency transitively increases the MSRV of Tokio, we do not guarantee that this does not happen. However, every minor release will have some set of versions of dependencies that works with the MSRV of that minor release.

The decision of whether we will remove a dependency or rely on this policy happens on a case by case basis.

**Comment by kennykerr** [comment]
By MSRV I mean the `rust-version`, which has never been set for the `windows-targets` crate.

**Comment by ChrisDenton** [comment]
Tbh, I'm confused why there would be an issue here. tokio 1.25.1 [depends on](https://crates.io/crates/tokio/1.25.1/dependencies) windows-sys 0.42 which does not [depend on](https://crates.io/crates/windows-sys/0.42.0/dependencies) windows-targets (it uses the older individual crates).

**Comment by riverar** [comment]
How are you using cargo with rustc 1.49? The cargo paired with that version doesn't understand the 2022 edition and will fail on generally all transitive dependencies. Is this some mixture of new/old tools? Or are you using some sort of hand crafted cargo.lock?
