### ISSUE TITLE
Fix tokio-test category slugs

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#5944]
When publishing tokio-test 0.4.3, I got this warning:
```
warning: the following are not valid category slugs and were ignored: testing. Please see https://crates.io/category_slugs for the list of all category slugs.
```
We should fix the warning.

**Comment by taiki-e** [comment]
"testing" is a sub-category of "development-tools", i.e., we should use "development-tools::testing".
https://crates.io/categories/development-tools::testing
