### ISSUE TITLE
Question about the `clear_readiness` method of `ScheduledIo`

### ISSUE THREAD

**Issue by rodman10** [tokio-rs/tokio#5945]
**Description**
Recently I was reading the source code of `tokio` for learning. I have noticed the implementation of `clear_readiness` method of `ScheduledIo` clears the `close` event through subtraction like [this](https://github.com/tokio-rs/tokio/blob/master/tokio/src/runtime/io/scheduled_io.rs#L391]). Whether it will go wrong when the `event` argument doesn't contain `close` event? Maybe we should clear the `close` event through bit operation to ensure only the corresponding bit will be changed? Thanks for reply!

**Comment by Darksonn** [comment]
The subtraction operator for the `Ready` type is defined with bit operations:

https://github.com/tokio-rs/tokio/blob/3b79be624d83d6763e23728a44c90963f0353f5c/tokio/src/io/ready.rs#L298-L305
