### ISSUE TITLE
runtime::tests::queue::stress1 unit test often not terminating or taking 50+ minutes

### ISSUE THREAD

**Issue by decathorpe** [tokio-rs/tokio#5955]
The `runtime::tests::queue::stress1` unit test is often hanging for extended amounts of time with tokio 1.32.0. I noticed this because we run the "full" tokio test suite for package builds in Fedora Linux (on all five architectures that we support, i.e. `{x86_64,i686,aarch64,powerpc64le,s390x}-unknown-linux-gnu`), and sometimes, our build tasks for tokio just don't seem to finish or progress at all for a long time, with the last log message being:

`test runtime::tests::queue::stress1 has been running for over 60 seconds`

For example, I ran a test build for tokio 1.32.0 today, and the build tasks for i686, aarch64, and s390x took ~10 minutes, and the tasks for x86_64 and powerpc64le took ~60 minutes.

I *think* this started happening around tokio v1.29 or v1.30, but I cannot pinpoint an exact starting point, since this does not occur reliably. However, it seems to me like this has been getting worse over time - with earlier releases of tokio (or rustc, I can't tell - we always use the latest rust "stable" release), this happened for <10% of test suite runs, now it seems to happen for roughly 40% of test suite runs.

It looks like the bad behaviour happens most often on `x86_64-unknown-linux-gnu`, but also happens - albeit less often - on other architectures mentioned above.

In case it makes a difference, we compile Rust code and run tests in `release` mode (and with `-Copt-level=3`, and `-Cdebuginfo=2`, and a few other flags that shouldn't make a difference). Our build hosts have pretty beefy hardware, and most build tasks should get 5+ CPU cores assigned to them.

**Comment by carllerche** [comment]
Any chance you could try bisecting to see if there is a commit that causes it?

**Comment by Darksonn** [comment]
It may be worth investigating whether it's happening in our CI too. If it's happening 40% of the time, then we shouldn't need to check that many runs.

**Comment by decathorpe** [comment]
Bisecting might be difficult since I never saw this happen on my local dev machine, only on our build servers ... but I can try. Test suite doesn't take *that* long locally, so I could try running it in a loop until one of the iterations suddenly takes much longer than the others. I will report back with my findings.

**Comment by decathorpe** [comment]
I tried reproducing the issue locally (both on "bare metal" and in a KVM-based VM), ran tests tens of thousands of times with the same flags that they are run with during our builds, but *never* hit the issue.

At this point I'm wondering whether this might just be an artefact of unusually high load on our build servers / VMs (and, potentially, overcommitted CPU resources). In the meantime, I set our builds to skip this test because of how unpredictable it makes the completion time.

I'm not sure how to proceed here ... but since I don't seem to have a way to reliably trigger the issue in an environment under my control, feel free to close this ticket if there's no time for / interest in investigating further.

**Comment by Darksonn** [comment]
Yeah, if there's no way for us to reproduce the issue, then I don't think there's much we are able to do right now.

Either way, thank you for reporting this.

**Comment by decathorpe** [comment]
Makes sense to me. Thank you for your time!

**Comment by decathorpe** [comment]
One thing that's relatively easy is resubmitting old build tasks. From what I can tell, tokio 1.28.2 is unaffected, but 1.29.1 immediately hit this issue. I don't have any old builds for versions between 1.28.2 and 1.29.1, so bisecting between these two will be a bit tedious, but I'll try.

**Comment by Darksonn** [comment]
Thank you. That's definitely an interesting finding. I'll reopen the isssue.

**Comment by Darksonn** [comment]
Perhaps asking the allocator for really large alignments is slow under some circumstances?

**Comment by Noah-Kennedy** [comment]
Profiling results would be interesting here for the before and after.

I should be able to get to this today.

**Comment by decathorpe** [comment]
Yeah, I'm trying to gather profiling data on various architectures for this. Should be able to post results later (I'm trying tokio v1.32.0 and will later run the same tests with v1.28.2).

**Comment by decathorpe** [comment]
I ran the equivalent of `cargo test --release runtime::tests::queue::stress1` for tokio v1.28.2 and tokio v1.32.0 with perf, and made flamegraphs with inferno, using these steps:

```bash
# build tokio + tests with --release
rm ./target/release/deps/tokio-*.d
perf record --call-graph dwarf ./target/release/deps/tokio-* runtime::tests::queue::stress1 &> /dev/null
perf script | inferno-collapse-perf > stacks.folded
cat stacks.folded | inferno-flamegraph > flamegraph.svg
```

The raw `perf.data` was huge (several gigabytes), so I couldn't gather these files from the build servers, but I have `stacks.folded` and `flamefraph.svg` for x86_64, aarch64, powerpc64le, and s390x and can provide the raw data, if it would be helpful (linked below).

But the flamegraphs with default settings already look very different between tokio v1.28 and more recent versions.

---

Here's the output for tokio v1.28.2 on x86_64-unknown-linux-gnu:

![flamegraph-tokio-1 28 2-x86_64](https://github.com/tokio-rs/tokio/assets/12836693/964cd3e2-fbb3-4f52-aa7c-70cc52cdf640)

And here's the output for tokio v1.32.0 on x86_64-unknown-linux-gnu:

![flamegraph-tokio-1 32 0-x86_64](https://github.com/tokio-rs/tokio/assets/12836693/1d350b68-9e2d-4ea7-b887-ab7acc19e5eb)

I uploaded all of the flamegraphs (they are interactive SVGs when opened in a web browser) and the raw `stacks.folded` data here: <https://decathorpe.fedorapeople.org/tokio-flamegraphs/>

---

The first one looks like a normal flamegraph, but the second one looks like almost all time is spent in `__posix_memalign` (confirming your suspicions that indeed requesting aligned memory might be expensive).

The flamegraphs for aarch64 and powerpc64le look almost identical to the ones for x86_64. The ones for s390x also show much more time spent in `__posix_memalign`, but it isn't as extreme as for the other three.

I couldn't produce the same data for i686 because we no longer build it for i686.

**Comment by Noah-Kennedy** [comment]
@decathorpe what version of glibc are you on? Is this 2.38?

If so, I think it might be https://sourceware.org/pipermail/libc-alpha/2023-August/150653.html

It would also seem that some folks don't like this means of getting cache-aligned data: https://sourceware.org/pipermail/libc-alpha/2023-August/150771.html.

**Comment by Noah-Kennedy** [comment]
We probably want to either revert that commit or handle aligned memory allocation ourselves (ugh).

**Comment by decathorpe** [comment]
Good catch - yes, this is with glibc 2.38. The issue described in the mailing list sounds very much like the one I encountered here (and also explains why I wasn't able to reproduce it locally, since my machine is on Fedora 38, which has glibc 2.37).

I can try reporting this against the Fedora glibc package - the maintainers are involved with glibc upstream (or *are* glibc upstream).

**Comment by Noah-Kennedy** [comment]
Thank you!

**Comment by Noah-Kennedy** [comment]
What I'm curious about now is how much this impacts real-world code.

**Comment by decathorpe** [comment]
> What I'm curious about now is how much this impacts real-world code.

I was wondering the same thing ... if this is caused by glibc, then the whole distribution is going to be affected by this change, i.e. any program that does `posix_memalign` a lot will suffer :(

---

for reference, here's the bug I filed against glibc: https://bugzilla.redhat.com/show_bug.cgi?id=2236255

**Comment by decathorpe** [comment]
Looks like the upstream glibc 2.38 release branch already has fixes for this issue, and the Fedora package was just updated to a snapshot that has these changes: <https://src.fedoraproject.org/rpms/glibc/c/620b1d37aebb16acd20693ac6cb93db0ee71018d?branch=f39>

I'll re-do the profiling tests to confirm whether this fixes the performance regression.

**Comment by Noah-Kennedy** [comment]
> We probably want to either revert that commit or handle aligned memory allocation ourselves (ugh).

Forget I said this, as it's being patched now.

**Comment by decathorpe** [comment]
I re-ran the same tests with profiling against glibc 2.38 + the fixes from the 2.38 release branch, and things are looking much better:

![flamegraph](https://github.com/tokio-rs/tokio/assets/12836693/8b2f2cca-8398-4002-ab85-ef4f135870cd)

This flamegraph with tokio 1.32.0 (with does memory alignment) now looks much closer to tokio < 1.29 (which doesn't). There's still some overhead from what I can see, but it's definitely a lot smaller than with "unpatched" glibc 2.38.

**Comment by decathorpe** [comment]
I haven't encountered this issue now for a few weeks, so from my point of view, I'd say it's resolved. Not sure if you still want to make some changes on the tokio side - the memory alignment definitely has some overhead, but the stress test is also likely more strongly negatively affected than real-world code. Feel free to close this issue or move discussion about that into a new ticket.

**Comment by Darksonn** [comment]
For now, I think we will just close this. Thank you for making us aware of this issue.
