### ISSUE TITLE
Publish documentation off of main?

### ISSUE THREAD

**Issue by sunshowers** [tokio-rs/tokio#5959]
**Is your feature request related to a problem? Please describe.**

I'd love to be able to inspect and link to project documentation as off of main, not just the most recent release via docs.rs.

**Describe the solution you'd like**

A GitHub job that publishes documentation to GitHub Pages.

With nextest I publish documentation at e.g. https://nexte.st/rustdoc/nextest_runner, though it could also be published to github.io: https://camino-rs.github.io/camino/rustdoc/camino/

It's really easy to set up the job. See e.g. https://github.com/camino-rs/camino/blob/main/.github/workflows/docs.yml.

**Describe alternatives you've considered**

Clone locally and build, though it's not as nice as just having them available online.

I'm happy to implement the repository part of this though it'll likely require some admin-driven setup (decisions about where to publish, access the GitHub Pages button in the repository settings, etc) so it might be easier for an admin to do it.

**Comment by taiki-e** [comment]
We had published such things in the past and repositories like bytes [still continue to do so](https://github.com/tokio-rs/bytes/blob/64c4fa286771ad9e522ffbefc576bcf7b76933d0/.github/workflows/ci.yml#L145). However, at least as for bytes, I don't think anyone is seeing that.

**Comment by Darksonn** [comment]
We did this previously, but it was challenging the docs.rs page in Google search.

What is the value you're hoping to get out of this?

**Comment by sunshowers** [comment]
Ah, I figured it would be a straight improvement. I've just generally found it helpful to be able to read the latest documentation and upcoming additions to APIs.

But the Google search result issue makes sense. A bit of a shame to be honest.
