### ISSUE TITLE
Priority-inverted `Semaphore`

### ISSUE THREAD

**Issue by tntokum** [tokio-rs/tokio#5990]
**Is your feature request related to a problem? Please describe.**
I have a scenario where I'd like to grant the most recent `acquire()` call the highest priority, therefore "preempting" the `acquire`s that have already been issued. This would turn the **fair queue** of `Semaphore` acquire requests into a **stack**.

**Describe the solution you'd like**
I would want another function implemented on `Semaphore`, something like `acquire_priority()`.
- From what I'm seeing, I'd have to modify the underlying `ll::Semaphore` `acquire()` method, which would then involve making a new `AcquirePriority` class that I can poll.
- This would allow both calls to `acquire()` and `acquire_priority()` on the same underlying `ll:Semaphore` object if desired.

Once we have two types of `Acquire`s, the `poll_acquire()` method implemented on `ll:Semaphore` could accept a `Priority` enum with `High` and `Fair` or `Low` variants.
- This would allow us to keep one unified `poll_acquire()`.
- The only difference would be that we'd pass a `High` variant in the `impl Future for AcquirePriority<'_>` and `Fair` or `Low` for the current method.

**Describe alternatives you've considered**
I've thought about writing my own crate for this, but `tokio` has a very nice semaphore system that I would probably just end up copying chunks out of. This way, more folks could at least take advantage of a greedy `Semaphore` if they need one. This functionality would also be impossible to write a trait for due to the private scope of `ll::Semaphore`.

**Additional context**
It's very possible to misuse the `acquire_priority()` function and end up starving your enqueued tasks, so it'd require much more care on the user end to ensure that when `acquire_priority()` is called, the remaining tasks are okay with being starved. It just happens to be the nature of **my** problem that newer tasks should be prioritized without care for the older ones.

**Comment by tntokum** [comment]
Also, I'm willing to write the code for this! I'm mainly posting as a request for comments on design, as well as for visibility.

**Comment by Darksonn** [comment]
I'm not convinced that I want to add this. I want to avoid complicating our semaphore too much.

**Comment by tntokum** [comment]
Very understandable, the less complexity around sync prims the better after all. I wanted to ask in case anyone found this desirable, but if it's not, I'm completely cool with uprooting `Semaphore` into a local crate.

**Comment by Darksonn** [comment]
Yeah, I think it would be better if you copy the code into your own crate and implement it there.
