### ISSUE TITLE
Cannot build Example: serving database content using proto

### ISSUE THREAD

**Issue by Zteve** [tokio-rs/tokio#6]
The subject example will not build, no matter where I look for the crates.  The example doesn't say where to get the crates from (some are in crates.io and some are not), nor what versions the dependencies should have.

Example problems I have had:
```
error: no matching package named `tokio-minihttp` found (required by `loda`)
location searched: registry https://github.com/rust-lang/crates.io-index
```
and then I resolve this with `tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp" }`, and follow this by resolving `r2d2`, but fail with `r2d2-postgres`:
```
error: no matching package named `r2d2-postgres` found (required by `loda`)
location searched: registry https://github.com/rust-lang/crates.io-index
```

I find a specific github for this, but it doesn't seem to work:
```
error: no matching package named `r2d2-postgres` found (required by `loda`)
location searched: https://github.com/sfackler/r2d2-postgres
```

eventually, I gave up.

Please update the example so that it compiles, at least, and provide enough information to be able to reproduce it.

**Comment by alexcrichton** [comment]
Thanks for the report! Could you point me in the direction of the example you were looking at? I think it should be `r2d2_postgres` but it'd be good to update any documentation if necessary.

**Comment by Zteve** [comment]
Thanks Alex.  Here is the example: [serving database content using proto](https://tokio.rs/docs/getting-started/db/). I put `r2d2-postgres` in the `Cargo.toml` file, couldn't find it, so explicitly added the `git` linked to in the example doc; but it still didn't compile, with or without a version.

**Comment by alexcrichton** [comment]
@Zteve have you tried `r2d2_postgres` instead? (note the underscore instead of a dash)

**Comment by Zteve** [comment]
I think I did; but the doc doesn't tell me what to write in the Cargo file, so I'm floundering.  The `-` mustn't appear in the `*.rs` file, so I use `_` there; and the `-` is in the name of the git repo, so I use `-` in the `Cargo.toml` file.  What should I write in each place?  If  you read the example link, it gives a complete source code at the foot of the page; but no hint as to the dependencies section in the `Cargo.toml` file.  I could have got these wrong, but all plausible guesses worked out wrong for me at some stage.

**Comment by alexcrichton** [comment]
Yeah that's definitely true! Could you open an issue over at https://github.com/tokio-rs/website about including `Cargo.toml` snippets as well?

**Comment by Zteve** [comment]
Will do.
