### ISSUE TITLE
Tokio 1.29 uses glibc 2.29 symbol when compiled with glibc 2.31

### ISSUE THREAD

**Issue by LukasKalbertodt** [tokio-rs/tokio#6003]
**Version**
Everything works with 1.28.2 and the problem occurs with 1.29.1.

**Platform**
Compiled on Ubuntu 20.04.6:

```
$ uname -a
Linux hostname 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

Executed on CentOS Stream 8:

```
$ uname -a
Linux hostname 4.18.0-490.el8.x86_64 #1 SMP Thu May 4 10:26:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ ldd --version
ldd (GNU libc) 2.28
```

**Description**
When updating from Tokio 1.28 to 1.29, somehow the GLIBC requirement of the executable is increased. Or something like that. Take this minimal example:

```rust
#[tokio::main]
async fn main() {}
```

```toml
tokio = { version = "=1.28", features = ["rt-multi-thread", "macros"] }
```

When I compile that on the Ubuntu mentioned above, transfer it to the CentOS mentioned above, and try to execute -> everything works. But if I change `"=1.28"` to `"=1.29"`, executing it fails with:

```
$ ./broken
./broken: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./broken)
```

Everything is done with Rust 1.72.

`ldd` output doesn't seem helpful:

```
$ ldd broken
./broken: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./broken)
	linux-vdso.so.1 (0x00007ffcc15d3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f50992a1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5099081000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5098cff000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5098afb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f5098736000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f50994b9000)
$ ldd works
	linux-vdso.so.1 (0x00007ffced1e2000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f63a7f6f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f63a7d4f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f63a79cd000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f63a77c9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f63a7404000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f63a8187000)
```

While Tokio bumped its minimal `libc` version between 1.28 and 1.29, I don't think that's the problem, as both `broken` and `works` were built with `libc 0.2.147` (from `Cargo.lock`).

Let me know if I can provide you with more information! I'm not an expert in this, so I'm not sure what information would be useful to debug this.

**Comment by Darksonn** [comment]
What versions of rustc are you using?

**Comment by LukasKalbertodt** [comment]
```
$ cargo --version
cargo 1.72.0 (103a7ff2e 2023-08-15)
$ rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)
```

**Comment by taiki-e** [comment]
Well, in general, there is no guarantee that the binary compiled with the new glibc will work with the old glibc.

**Comment by LukasKalbertodt** [comment]
Yeah, I assumed so. I thought you might want to know about this anyway. It is probably something that at least some production users are interested in.

Any luck in finding out what Tokio change caused this?

**Comment by Darksonn** [comment]
I don't think we intentionally increased the glibc requirement. I don't know what caused the problem. Could I get you to bisect it to find the commit?

**Comment by taiki-e** [comment]
> It is probably something that at least some production users are interested in.

I hope that few users compile and use binaries for production environments in a way that is not guaranteed to work by the platform.

In any case, code compiled with glibc version that is the same or smaller than the environment it is run in should not be affected.

> Any luck in finding out what Tokio change caused this?

There have been so many changes that it is hard to tell which ones cause the problem just by looking at a few.

https://github.com/tokio-rs/tokio/compare/tokio-1.28.2...tokio-1.29.1

**Comment by taiki-e** [comment]
I can compile a repro that uses tokio 1.29 with glibc 2.17 and run it with glibc 2.17 without problems, so it is not that the glibc requirements for tokio itself have been raised.

**Comment by taiki-e** [comment]
Closing -- This is an issue on the user side that depends on the accidental availability of code compiled using glibc, which is incompatible with the environment in which the binaries are run, to work. AFAIK, neither the platform nor the compiler provides any guarantee that such usage will work.
