### ISSUE TITLE
Add Peekable trait for socket

### ISSUE THREAD

**Issue by cathaysia** [tokio-rs/tokio#6006]
I want to be able to select all socket types using generics, currently using:

```rust
    pub async fn read_traffic<T>(sck: &mut T) -> anyhow::Result<Self>
    where
        T: tokio::io::AsyncWriteExt + std::marker::Unpin + tokio::io::AsyncReadExt,
    {
}
```

However, this approach renders the peek method unavailable. Is it possible to add peekable trait to all sockets?

**Comment by cathaysia** [comment]
The root cause of this problem is that I'm trying to deserialize data from a stream, I have to read a byte from the stream to know the type of the next packet, but this packet is also part of the deserialization of the data.

I thought about it carefully, and the fundamental reason during the deserialization process is that I hope to be able to adapt to multiple transmission protocols, but currently only tcpstream in tokio requires the peek method (because udp has obvious boundaries). This part of the adaptation work should be done by myself instead of putting the work in tokio.

So I will close this question and thank you very much for your answer.

**Comment by cathaysia** [comment]
Also, thank you very much for your suggestions. I have not developed a lot of software using tokio tcpstream. Your suggestions are of great help to me.

**Comment by Darksonn** [comment]
I see. You probably want one of these:

 * [`tokio_util::codec`](https://docs.rs/tokio-util/latest/tokio_util/codec/index.html)
 * [Framing | Tokio tutorial](https://tokio.rs/tokio/tutorial/framing)

**Comment by cathaysia** [comment]
Thanks. That's what I want 😊
