### ISSUE TITLE
Is the scheduling scheme of CONCURRENTCPP better? No global-queue and steal-task, only balance work to idles;

### ISSUE THREAD

**Issue by sxstd001** [tokio-rs/tokio#6012]
Is the scheduling scheme of Concurrencpp better?

https://github.com/David-Haim/concurrencpp

A thread-worker has a pub_queue  and a private_queue.  if private_queue is empty ,  swap pub_queue.
Every loop, check exists idle-workers ,  if exists, balance tasks(in private_queue) to idle-worker's pub_queue.  

I thinks it's easy and performance. 

please share your opinions.

**Comment by wathenjiang** [comment]
I don't know much about concurrencpp, but Tokio does have a work-stealing schedulers.

**Comment by wathenjiang** [comment]
As you described, the starving problems would be very serious in some cases.

**Comment by wathenjiang** [comment]
Suppose current worker thread have a task A that would take 1s to complete, and there is an idle worker thread. Until the task A completes, the idle worker thread's pub_queue will not be put any tasks in by current worker thread.

**Comment by sxstd001** [comment]
> Suppose current worker thread have a task A that would take 1s to complete, and there is an idle worker thread. Until the task A completes, the idle worker thread's pub_queue will not be put any tasks in by current worker thread.

**you are right.**
