### ISSUE TITLE
Broadcast channel capacity is not well-documented

### ISSUE THREAD

**Issue by mdacach** [tokio-rs/tokio#6015]
**Description**
`tokio::sync::broadcast` documentation states that [the `capacity` parameter is an upper bound on the number of values the channel may retain at any given time](https://docs.rs/tokio/latest/tokio/sync/broadcast/index.html#lagging).
But when creating the channel, this `capacity` is actually [rounded up to the nearest power of two](https://github.com/tokio-rs/tokio/blob/d247e7f5df4bd861287467ecc5f827538bee4d63/tokio/src/sync/broadcast.rs#L507) - thus the constraint that [`capacity <= usize::MAX / 2`](https://docs.rs/tokio/latest/tokio/sync/broadcast/fn.channel.html#panics) on `channel()`

**Solution**
I guess we want to either
1. commit to rounding up to the next power of two and update the docs to state that, or
2. have the docs clarify that the actual channel capacity is >= than `capacity`, (but then the constraint of `capacity <= usize::MAX / 2` is not clear)

For context, I came across this messing around with the example code:
![image](https://github.com/tokio-rs/tokio/assets/43617028/19ef0ff4-2d44-4f1d-a9e3-2381871e1359)
![image](https://github.com/tokio-rs/tokio/assets/43617028/9e5118f5-8555-44de-9426-31c3205994fc)

**Comment by mdacach** [comment]
Follow-up question: why round up the capacity at all?

**Comment by hawkw** [comment]
I think it would be preferable to change the docs to state that the channel's capacity will be _at least_ `capacity`, rather than publicly committing to power of two capacities. The bitmask is an internal implementation detail, and if it's possible to document the behavior clearly in a way that does not commit to maintaining that internal implementation detail forever, that's probably better.

**Comment by hawkw** [comment]
For comparison, the [documentation for `Vec::with_capacity`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.with_capacity), which also rounds to the next power of two, states:
> The vector will be able to hold at least `capacity` elements without reallocating. This method is allowed to allocate for more elements than `capacity`. If `capacity` is 0, the vector will not allocate.
>
> ...
> 
> If it is important to know the exact allocated capacity of a Vec, always use the [`capacity`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.capacity) method after construction.

The broadcast channel docs could probably use similar language.
