### ISSUE TITLE
Time::Interval shifting trend of tick period when MissedTickBehavior set as Delay

### ISSUE THREAD

**Issue by NWPoul** [tokio-rs/tokio#6029]
**Version**
1.32.0

**Platform**
64-bit Windows,
Web based playground https://play.rust-lang.org/

**Description**
When set MissedTickBehavior of tokio::time::interval as Delay
the period of tick is have trend to noticeable (100th of ms for each 100 sec) shifting away
while if MissedTickBehavior set to Skip or Burst the deviation of period is drifting around several ms without trending  

I tried this code:

```rs
use tokio::time::{interval, Duration, Instant, MissedTickBehavior};

#[tokio::main]
async fn main() {
    let delay = Duration::from_millis(100);
    let mut interval = interval(delay);
    interval.set_missed_tick_behavior(MissedTickBehavior::Delay);
    
    let start_time = Instant::now();
    let mut tick:u32   = 0;
    
    loop {
        interval.tick().await;

        let elapsed   = start_time.elapsed();
        let estimated = delay * tick.into();
        let deviation = elapsed.as_millis() as isize - estimated.as_millis() as isize;
        println!(
            "elapsed: {:?} estm: {:?} dev_ms: {:?}",
             elapsed,
             estimated,
             i32::try_from(deviation).unwrap()
        );
        tick += 1;
    }
}
```

**Comment by Darksonn** [comment]
Well, if a tick is missed, then you told it to delay itself. Ticks are considered missed if they are 5 ms late.

**Comment by NWPoul** [comment]
Oh...
but what is considered as "late"? I am fairly new in rust so pardon me if I take it stupidly wrong😇
in above code:
after each **interval.tick().await;** invocation tokio::interval waits the established delay (with some tolerance) and proceeded the rest code of the loop
if it's takes longer that the delay +5 ms (before thr next invoketion of **interval.tick().await;** ) it considered as "late"
but delay set as 100ms and I tried it as 1000ms also with the same result - very unlikely that loop code take more than 105 or even 1005 ms

**Comment by Darksonn** [comment]
If you remove the call to `set_missed_tick_behavior`, you will find that it sometimes takes more than 5ms. This is probably due to other things happening on the machine making the sleep take longer than necessary.

I'm going to close this as it is behaving as expected.
