### ISSUE TITLE
Task dumps can deadlock.

### ISSUE THREAD

**Issue by jswrenn** [tokio-rs/tokio#6035]
Requesting a task dump can deadlock. When a task dump is requested, `OwnedTasks` is locked and iterated over, which each task being polled.

Tasks are polled in 'tracing mode', causing most tokio leaf futures to produce `Poll::Pending`, even if they are otherwise ready. However, if a non-tokio or non-instrumented leaf future is used and completes during tracing, the system will deadlock: completed futures are removed from `OwnedTasks` and doing so requires locking `OwnedTasks` (which can't happen, because it's already locked for tracing).

**Comment by Darksonn** [comment]
Yeah, we definitely shouldn't hold the lock while polling stuff. Making a vector of tasks seems like a better solution.
