### ISSUE TITLE
Add Future::timeout() method

### ISSUE THREAD

**Issue by petrzjunior** [tokio-rs/tokio#6047]
**Is your feature request related to a problem? Please describe.**
Currently, the code to timeout a Future is
```rust
let _ = timeout(Duration::from_secs(3), listener.accept())
    .await
    .expect("timeout")
    .expect("accept failed");
```
I propose it should be possible to write
```rust
let _ = listener.accept()
    .timeout(Duration::from_secs(3))
    .await
    .expect("timeout")
    .expect("accept failed");
```
This results in cleaner code following the fluent style of writing.

**Describe the solution you'd like**
I propose adding a `Future` extension method
```rust
fn timeout(self, timeout: Duration) -> Timeout<Self>
```

**Describe alternatives you've considered**
The current method `timeout(Duration, Future)` works, but is less readable.

**Additional context**
The proposed method used to be in Tokio in the past:
https://github.com/tokio-rs/tokio/blob/27e5b41067d01c0c9fac230c5addb58034201a63/tokio/src/future.rs#L61-L66

It got removed in #1774 refactoring.

Similar method is implemented in [async_std](https://docs.rs/async-std/1.12.0/async_std/prelude/trait.FutureExt.html#method.timeout) since 2019 https://github.com/async-rs/async-std/pull/600.

**Comment by Darksonn** [comment]
We don't currently have any extension traits for futures in Tokio, and I'm somewhat reluctant to add one.

**Comment by chris-leach** [comment]
@Darksonn can you expand on your reluctance at all? I agree that the postfix interface is more ergonomic, especially when there are several chained method calls before the `await`, as opposed to after:

```rust
timeout(
    Duration::from_secs(1),
    RequestBuilder::new(/*...*/)
        .prepare(/*...*/)
        .check(/*...*/)
        .build(/*...*/)
        .send(/*...*/),
)
    .await
    .wrap_err(/* ... */)?;
```

vs

```rust
RequestBuilder::new(/*...*/)
    .prepare(/*...*/)
    .check(/*...*/)
    .build(/*...*/)
    .send(/*...*/)
    .timeout(Duration::from_secs(1))
    .await
    .wrap_err(/* ... */)?;
```

**Comment by YuanYuYuan** [comment]
Also curious about why `FutureExt` was removed from `tokio` .

**Comment by Darksonn** [comment]
We removed `FutureExt` because we wanted to move away from combinators such as `map` and so on. Async/await syntax has made those mostly obsolete. If we are to add this, I'd prefer to add it to tokio-util.

**Comment by evanrittenhouse** [comment]
Feel free to assign this to me, I'll add it to tokio-util
