### ISSUE TITLE
CI `tests-pass` is likely not working as it should

### ISSUE THREAD

**Issue by WaffleLapkin** [tokio-rs/tokio#6048]
This repository has a CI job that requires all required jobs via `needs`:

https://github.com/tokio-rs/tokio/blob/eaba9712e8a4b35a1a2cdeb3b27845d6239c12ea/.github/workflows/ci.yml#L38-L39

I'm not sure how exactly does tokio manage CI, but if `tests-pass` is required via branch protection, it likely doesn't work as expected. This is because when a job in `needs` fails, github skips the `tests-pass` job and then considers skipped being the same as successful.

Refs:
- https://github.com/orgs/community/discussions/26733#discussioncomment-3253155
- https://github.com/re-actors/alls-green

I just saw this issue in practice in my repo, where I partially copied the setup from tokio, so decided to let you know, in case that's also an issue for you. (for me it was especially surprising cause I use merge queue and got an "invisible" conflict that should have been prevented by it... oh well...)

**Comment by Darksonn** [comment]
Yeah, this is rather annoying. We had to modify our CI setup to make every individual check mandatory instead of using the `tests-pass` step.

**Comment by WaffleLapkin** [comment]
The discussion linked above suggests a way to fix the problem in the job itself (by basically making sure it always runs and failing it by hand when a required check has not succeeded)

**Comment by WaffleLapkin** [comment]
I'm going to close this, since this is a known issue that is worked around already.
