### ISSUE TITLE
tower::Service and async/await

### ISSUE THREAD

**Issue by withoutboats** [tokio-rs/tokio#607]
I just wanted to write up some thoughts on tower::Service and async methods

Here is the summary:

1. It is **not** the case that `fn call` could ever become `async fn call`, because lifetime capture is not how `async fn` works.
2. However (and relatedly), `fn call` is right in the sweet spot where we could move on making `-> impl Future` work for it *soon*, allowing you to use an `async` block inside of it.

The rest of this issue documents all of these issues in detail.

## `fn call` and async fn lifetimes

An `async fn` captures all lifetimes in its inputs in the future it returns - this is the result of the fact that the entire function body is captured in the future it returns. That is, `async fn call` would have to capture the lifetime of `&mut self`, having a signature more like this:

```rust
pub trait Service {
    type Request;
    type Response;
    type Error;
    type Future<'a>: Future<Output = Result<Self::Response, Self::Error>> + 'a;
    fn call<'a>(&'a mut self, req: Self::Request) -> Self::Future<'a>;
}
```

An astute observer will notice that this requires `type Future<'a>`: that is a *generic associated type*, which you may be aware is a feature that does not work today but that we are working on changing the compiler to make it work. This is the big blocker for allowing async methods today.

What this means is that the service trait will never have an `async fn call` in it. What you will be able to do someday, hopefully, is use an `async` block *inside* call, to construct the future it returns.

## async blocks and associated types

There's a big problem with using async blocks in Service, though: an async block evaluates to a unique anonymous type, just like a closure would. This means you cannot write what the associated type `Self::Future` is, e.g.:

```rust
impl Service for Something {
    type Future = ???; // impossible to name
    fn call(&self, req: Self::Request) -> Self::Future {
        async { ... }
    }
}
```

There are two solutions to this problem:

1. `impl Trait` - remove the Future associated type, and change call to return `-> impl Future`
2. "existential types" - we are working on a feature which would allow you to name anonymous types.

Neither of these are enabled today, because we don't allow `impl Future` in trait methods. *However*, for the same reason that call cannot be an `async fn`, there is no technical blocker on allowing it in this case: we could allow `impl Trait` in traits when they are analogous to normal associated types, as long as they wouldn't be generic associated types (basically: no generic parameters on the method and no `+ 'a` in the return type).

## Conclusion

The final thrust of all this is that right now we could implement a very conservative, very minimal version of impl Trait in traits, and it would happen to support changing `Service` to look like this:

```rust
pub trait Service<Request> {
    type Response;
    type Error;
    fn poll_ready(&mut self) -> Poll<(), Self::Error>;
    fn call(&mut self, req: Request) -> impl Future<Item = Self::Response, Error = Self::Error>;

    fn ready(self) -> Ready<Self>
    where
        Self: Sized,
    { ... }
}
```

This would allow users to implement call with a `Futures03Compat(async { })` expression, using async/await syntax, or else with combinators (which also usually involves anonymous closure types).

The question for y'all then, would you be interested in experimenting with this (probably just on git master, not released to crates.io)? I know Buoyant is using tower a lot internally, it would be great to get more experience from y'all using async/await syntax. If you are, we could possibly prioritize getting a conservative impl trait in traits enabled.

**Comment by withoutboats** [comment]
Oh crap, I meant to open this in the tower repo. Oops, sorry!

**Comment by carllerche** [comment]
No worries, are you going to open a new one in the tower repo?

**Comment by cramertj** [comment]
> "existential types" - we are working on a feature which would allow you to name anonymous types.

FWIW this is usable now on nightly, though the syntax and some of the inference details are still subject to change.

**Comment by withoutboats** [comment]
tower-rs/tower#103
