### ISSUE TITLE
Can I assume the ```decode``` will be called once for each received dgram in UdpFramed?

### ISSUE THREAD

**Issue by astrojhgu** [tokio-rs/tokio#610]
For my application, one udp datagram forms one data frame.

So can I assume the function ```decode``` will be called as soon as one datagram is received? or the parameter of ```decode``` is simply the raw data of ONE (not two, not half) udp datagram?

In this case I will not need to validate the completeness of dataframe accepted by ```decode```.

Thanks

**Comment by In-line** [comment]
You can't receive half of UDP datagram, because well.. It is datagram, not stream.
https://serverfault.com/questions/534063/can-tcp-and-udp-packets-be-split-into-pieces

Tokio uses internally `recv_from`, from which you only can receive 1 datagram, not two or more. https://github.com/tokio-rs/tokio/blob/82c5baa09bbcf1a4e2bb813552c72c69deb970d3/tokio-uds/src/datagram.rs#L104

**Comment by In-line** [comment]
There are some caveats while working with `UDPFramed`, so I recommend you to read this issue https://github.com/tokio-rs/tokio/issues/173

**Comment by astrojhgu** [comment]
Sorry for not expressing my question clearly. My concern is that can I assume each time the function ```decode``` is called by UdpFramed, there will be one and only complete datagram in its parameter (suppose each time it is called, I always take the content of the parameter)?

Or in other words, will UdpFramed guarantee to call the function ```decode``` each time one datagram arrives and fill the whole content of the arriving datagram into the parameter of ```decode```?

**Comment by tobz** [comment]
`Framed` works at a higher level than UDP datagrams, or TCP packets.  So, there's two parts here:

- your UDP datagrams
- your framing codec

As @In-line mentioned with that StackOverflow link, when it comes to UDP, your application either "gets" the datagram or it doesn't.  From that perspective, your application should be getting notified when it has a new datagram available.

From the `Framed` perspective, it depends on what your codec does.  If you used the `BytesCodec`, you should expect a call to `decode`, when a full UDP datagram is available, to simply return the buffer containing the datagram to you.

Of course, calling `decode` will not block, so if you have no UDP datagram available on your socket, the call will not return anything, and your application will be notified when the socket gets more data, so it can try and decode a message again.

**Comment by astrojhgu** [comment]
In my condition I'm using UdpFramed to receive some kind of messages. Each piece of message is exactly one UDP datagram.

So can I safely ignore the possibility that sometimes, when ```decode``` is called the data in the buffer is not exactly ONE single complete UDP datagram (given that each time ```decode``` is called, I will strictly ```take``` ALL the data in the buffer and leave an empty one)?

**Comment by tobz** [comment]
I think an example will explain better:

- server calls `decode`, no data available, -> `None`
- client sends four UDP datagrams to server
- server calls `decode`, data available, -> `Some(msg)`
- server calls `decode`, data available, -> `Some(msg)`
- server calls `decode`, data available, -> `Some(msg)`
- server calls `decode`, data available, -> `Some(msg)`
- server calls `decode`, no data available, -> `None`

**Comment by astrojhgu** [comment]
Thanks, this example answers my question.

**Comment by tobz** [comment]
👍 

Going back to your very original question, and with all the discussion: you should be able to use `UdpFramed` + `BytesCodec`.

Are you OK if I close this issue?

**Comment by astrojhgu** [comment]
Yes, my problem has been solved. It's OK to close this issue.
Thank you again.

**Comment by tobz** [comment]
Great!

Thanks for using Tokio. 👍
