### ISSUE TITLE
tokio-util@0.7.9 depends on outdated hashbrown

### ISSUE THREAD

**Issue by dignifiedquire** [tokio-rs/tokio#6101]
`tokio-util@0.7.9` depends currently on an outdated version of `hashbrown@0.12`, which in turn depends on `ahash@0.7.6` which is yanked: https://github.com/tokio-rs/tokio/blob/master/tokio-util/Cargo.toml#L48

**Comment by Darksonn** [comment]
I'm happy to upgrade to hashbrown v0.14, but it doesn't seem like we force you to use a yanked version of ahash. Hashbrown v0.12.x is compatible with ahash 0.7.7, which is not yanked. Remember that cargo dependencies are caret-dependencies, and do not specify an exact version.

**Comment by dignifiedquire** [comment]
Thanks, `0.7.7` was not yet released when I filed this issue, so it makes it much less urgent. 
I'll make a PR updating hashbrown in any case though.

**Comment by dignifiedquire** [comment]
Opened https://github.com/tokio-rs/tokio/pull/6102
