### ISSUE TITLE
Verify that all tests pass with panic=abort

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6109]
We should make sure that the test suite passes with panic=abort. Tests that need unwinding can be gated with `#[cfg(panic = "unwind")]`.

To close this issue, add a new CI step that runs the test suite with panic=abort.

**Comment by satakuma** [comment]
To check which tests need to be gated, you can use the following command:
```sh
RUSTFLAGS="-C panic=abort -Zpanic-abort-tests" cargo +nightly test --all-features --no-fail-fast
```

For me, this command outputs the following list of failing tests in the main `tokio` crate:
```
runtime::tests::task_combinations::test_combinations
sync::tests::atomic_waker::atomic_waker_panic_safe
async_fd_new_panic_caller
async_fd_with_interest_panic_caller
test_panics_do_not_propagate_when_dropping_join_handle
tcp_listener_from_std_panic_caller
tcp_stream_from_std_panic_caller
issue_2174
interleave_then_enter
builder_max_blocking_threads_panic_caller
builder_worker_threads_panic_caller
signal_panic_caller
broadcast_channel_panic_caller
mpsc_bounded_channel_panic_caller
panicking_blocking_task_wakes_paused_runtime
block_in_place_panic_caller
local_key_get_panic_caller
interval_at_panic_caller
interval_panic_caller
pause_time_in_spawn_threads
```

In `tokio-util` it outputs the following:
```
delay_queue_insert_at_panic_caller
delay_queue_insert_panic_caller
callback_panic_does_not_kill_worker
task_panic_propagates
remove_after_compact
remove_after_compact_poll
```

In `tokio-stream` only the following test fails: `stream_chunks_timeout_panic_caller`.

**Comment by sunheyi6** [comment]
@Darksonn It seems you should close this issue

**Comment by satakuma** [comment]
I don't think this issue should be closed. We still have to:
1. Gate all panicking tests in `tokio-util` and `tokio-stream`.
2. Add a step to the CI which will automatically verify that all tests are covered.
