### ISSUE TITLE
Implement AsyncRead for &Take<File>

### ISSUE THREAD

**Issue by alucryd** [tokio-rs/tokio#6123]
**Is your feature request related to a problem? Please describe.**

I have a workflow where I need to split a big file into multiple smaller files with variable sizes. I would like to open the big file only once, and sequentially feed multiple `Take`s to `io::copy` (and later `io::copy_buf` to use the most optimal buffer size). However the borrowed `Take` does not implement `AsyncRead`.

**Describe the solution you'd like**
It would be nice to be able to take the same file multiple times.

```
let mut bin_paths: Vec<PathBuf> = Vec::new();
    let bin_file = open_file(&bin_path).await?; // this returns an instance of fs::File

    for (bin_name, size) in bin_names_sizes {
        let split_bin_path = directory.as_ref().join(bin_name);
        let mut split_bin_file = create_file(progress_bar, &split_bin_path, quiet).await?; // this returns another instance of fs::File

        let mut handle = &bin_file.take(*size); // take moves bin_file so we need to borrow

        io::copy(&mut handle, &mut split_bin_file)
            .await
            .expect("Failed to copy data"); // currently not possible

        bin_paths.push(split_bin_path);
    }
```

**Describe alternatives you've considered**
The only alternative seems to open the file multiple times and seek + take on each instance.

**Additional context**
I'm coming from async_std where this exact workflow was working fine, but since the library is more or less unmaintained I'm trying to switch over to tokio.

**Comment by satakuma** [comment]
In your case, it is possible to sequentially create multiple `Take`s if you create them like this:
```rs
let mut handle = (&mut bin_file).take(*size);
```

**Comment by alucryd** [comment]
Ah! Thank you so much, that does the trick indeed! I guess this can be closed then :)

**Comment by sunheyi6** [comment]
@alucryd 
If you think this problem has been solved, you can close this issue.
