### ISSUE TITLE
`BufReader` `split` does not return empty segments if they were last before EOF

### ISSUE THREAD

**Issue by AaronKutch** [tokio-rs/tokio#6124]
as of tokio 1.33.0,
```rust
use tokio::io::{AsyncBufReadExt, BufReader, AsyncWriteExt};


#[tokio::main]
async fn main() {

    dbg!("hello\nworld".split('\n').collect::<Vec<&str>>());
    let (mut client, server) = tokio::io::duplex(64);
    client.write_all(b"hello\nworld").await.unwrap();
    drop(client);
    let mut buf = BufReader::new(server).split(b'\n');
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());

    dbg!("case 1");

    // add on a trailing newline, the string split returns an extra empty string, but
    // the BufReader does not
    dbg!("hello\nworld\n".split('\n').collect::<Vec<&str>>());
    let (mut client, server) = tokio::io::duplex(64);
    client.write_all(b"hello\nworld\n").await.unwrap();
    drop(client);
    let mut buf = BufReader::new(server).split(b'\n');
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());

    dbg!("case 2");

    // despite it being able to return empty strings
    let (mut client, server) = tokio::io::duplex(64);
    client.write_all(b"\n\nw").await.unwrap();
    drop(client);
    let mut buf = BufReader::new(server).split(b'\n');
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());
    dbg!(buf.next_segment().await.unwrap());

}
```
This causes a lot of problems for my usecase, it would be great if this could be fixed soon.

**Comment by carllerche** [comment]
Tokio aims to copy the semantics of `std::io::BufReader`. Could you see what std does? If it has the same behavior, I would open an issue with them and see what they say.

**Comment by AaronKutch** [comment]
seems that unfortunately it is the case https://github.com/rust-lang/rust/issues/109907

**Comment by AaronKutch** [comment]
Is there any relatively simple workaround for this in the meantime? It looks like I would have to delve into wakers and all that.

**Comment by AaronKutch** [comment]
I found a workaround involving using the tokio::time::timeout function on a read in a loop

**Comment by Darksonn** [comment]
You could use [`chain`](https://docs.rs/tokio/latest/tokio/io/trait.AsyncReadExt.html#method.chain) to add an extra newline at the end of the byte stream. I think this has the effect you want in all cases.

Note that I also think that the current behavior is the correct one. If you create a `.txt` file in pretty much any editor and don't add an extra empty line at the end, then the file will still end with a newline character. So the behavior of `BufReader` is consistent with that.

**Comment by AaronKutch** [comment]
> If you create a .txt file in pretty much any editor and don't add an extra empty line at the end, then the file will still end with a newline character.

This issue is about information being lost through the stream _removing_ segments when there should be (you can't distinguish between case 0 and 1). Text editors have no say on what an more information rigorous and well defined structure like a stream should do.

**Comment by Darksonn** [comment]
I do agree that there is a reasonable case to be made for the behavior your want, but changing it has too many downsides:

 * If we change it, we would no longer match the standard library.
 * If we change it, we may break existing programs using Tokio.
 * The current behavior is correct for some use-cases: Specifically, it is correct for the use-case of reading text files.

Although I agree that losing information is a downside of the current implementation, I think that the benefits do not outweigh the costs. Because of that, we will not make this change. If the standard library decides to make the change, then we can reconsider.

Regardless, thank you for taking the time to file an issue. I was not aware of this behavior, and it's important to verify whether we have the correct behavior in edge cases.

**Comment by AaronKutch** [comment]
in a zulip thread it looks like it is possible to fix but only by adding new method https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/broken.20and.20un-fixable.20parts.20of.20Rust , if someone has the motivation and time to do it.
