### ISSUE TITLE
Implement FromIter for JoinSet

### ISSUE THREAD

**Issue by jkelleyrtp** [tokio-rs/tokio#6132]
I'd like to implement FromIter for JoinSet so I can transform a vec of API endpoints into reqwest calls. The traditional JavaScript would look like something like:
```
Promise.all(urls.map((url) => fetch_url(url))
```

FuturesUnordered has this trait implemented and is quite useful.

Is there a reason why I could not add the trait impl to JoinSet?

**Comment by Darksonn** [comment]
Hmm. I've seen people misuse the `impl FromIter on FuturesUnordered` several times by just using it as a `Vec`. But maybe it's okay since we don't have `IntoIterator` for `JoinSet` ...
