### ISSUE TITLE
Inconsistencies between channel stream types in tokio_streams

### ISSUE THREAD

**Issue by TylerBloom** [tokio-rs/tokio#6137]
**Is your feature request related to a problem? Please describe.**
There are certain methods and traits implemented for the MPSC receiver streams in `tokio_streams` that are not implemented for the other channel-based stream types. Namely, the `BroadcastStream` does not implement `AsRef` and `AsMut` nor does it have an `into_inner` method, but the MPSC streams do.

My primary use case is that I would like to call the receiver's `resubscribe` and `try_recv` methods.

**Describe the solution you'd like**
I would like to see similar capabilities between all channel-based stream types or at least the broadcast channel stream.

**Describe alternatives you've considered**
I currently have implemented a stream wrapper. This works, but ideally, I would use an official version as the project I'm working on already uses the MPSC streams as well.

**Comment by Darksonn** [comment]
Due to differences in how they are implemented, this might not be possible.

**Comment by TylerBloom** [comment]
Ya, looking into the implementation, I see that the broadcast wrapper uses a `ReusableBoxFuture` internally. Do you know the reason for this? Is it because the broadcast receiver does not directly implement a `poll_recv` method? Perhaps my approach is a bit naive, but in my implementation, I poll the future created by the broadcast receiver's `recv` method. Using pin projection, this is roughly my version:
```rust
#[pin_project]
struct BroadcastStream<M>(#[pin] broadcast::Receiver<M>);

impl<M: Clone> Stream for BroadcastStream<M> {
    type Item = M;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        pin!(self.project().0.recv()).poll(cx).map(Result::ok)
    }
}
```

**Comment by Darksonn** [comment]
The broadcast receiver stores important state in the `recv` future itself, so that future must be kept around from call to call. That is why we use a boxed future.

Your implementation is incorrect because it destroys the `recv` future. This will cause missed wakeups.

**Comment by TylerBloom** [comment]
Hmm, I see. An alternative workaround could be to keep a spare copy of the receiver either in each stream or shared via an `Arc` (both have downsides, though). Would it be possible to implement a `poll_recv` method on the broadcast receiver to avoid such workarounds?

**Comment by Darksonn** [comment]
Yes, those alternatives you mentioned are the main alternatives.

Changing the receiver to allow this would introduce allocations for every time you clone the receiver, which we would not like to do.

**Comment by TylerBloom** [comment]
I see. Thank you for your help. It sounds like what this would require is not aligned well with the current design of the broadcast channels, so I will close this issue.
