### ISSUE TITLE
Use `signalfd` on Linux for `tokio::signal`

### ISSUE THREAD

**Issue by NobodyXu** [tokio-rs/tokio#6140]
**Is your feature request related to a problem? Please describe.**

`tokio::signal` uses `signal-hook-registry` for catching signal on unix currently.

On Linux, there's a more efficient syscall called [`signalfd`](https://man7.org/linux/man-pages/man2/signalfd.2.html) available in Linux `2.6.27`.

It creates a fd for the signal specified (and can change the signal mask dynamically), the fd can then be `epoll`ed and `read` `signalfd_siginfo` from it.

**Describe the solution you'd like**

Add a `signalfd` implementation for Linux, fallback to `signal-hook-registry` if it's not available.

**Describe alternatives you've considered**

**Additional context**

**Comment by Darksonn** [comment]
Thoughts @ipetkov ?

**Comment by ipetkov** [comment]
I don't have any experience with `signalfd` and I don't have any reservations about someone adding such an implementation, so long as we can gracefully fall back to the signal based one if it isn't available

**Comment by notgull** [comment]
We tried this in `async-signal`. It turns out that [`signalfd`'s semantics](https://github.com/smol-rs/async-signal/pull/20) work very differently from just raw signal handlers. So it might not be the best idea to migrate over to them.

In addition, I doubt that the efficiency gains would be very noticeable, since signals are a cold operation anyways.

**Comment by NobodyXu** [comment]
@notgull Is it because `signalfd` could lose miss some `SIGCHLD` signal?
IIRC signal are general lossy even if you use traditional `sigaction`.

> In addition, I doubt that the efficiency gains would be very noticeable, since signals are a cold operation anyways.

Well it will certainly be beneficial for waiting on children, although #6141 provides a much better solution for waiting on children.

**Comment by NobodyXu** [comment]
And it has a severe problem when using `epoll` with `fork` (I considered it as a bug):

> epoll(7) semantics
>        If a process adds (via [epoll_ctl(2)](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html)) a signalfd file descriptor
>        to an [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html) instance, then [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html) returns events only
>        for signals sent to that process.  In particular, if the process
>        then uses [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html) to create a child process, then the child will
>        be able to [read(2)](https://man7.org/linux/man-pages/man2/read.2.html) signals that are sent to it using the signalfd
>        file descriptor, but [epoll_wait(2)](https://man7.org/linux/man-pages/man2/epoll_wait.2.html) will not indicate that the
>        signalfd file descriptor is ready.  In this scenario, a possible
>        workaround is that after the [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html), the child process can close
>        the signalfd file descriptor that it inherited from the parent
>        process and then create another signalfd file descriptor and add
>        it to the epoll instance.  Alternatively, the parent and the
>        child could delay creating their (separate) signalfd file
>        descriptors and adding them to the epoll instance until after the
>        call to [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html).

**Comment by NobodyXu** [comment]
In that case it indeed doesn't make sense to use it.
