### ISSUE TITLE
`tokio::time::sleep(...)` hangs indefinitely in tests after task is spawned

### ISSUE THREAD

**Issue by a-0-dev** [tokio-rs/tokio#6142]
**Version**
1.32.0

**Platform**
`Linux hostname 6.5.10-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov  2 19:59:55 UTC 2023 x86_64 GNU/Linux`

**Description**
`tokio::time::sleep(...)` seems to not work as expected in a `#[tokio::test]` if a task was spawned before. The following minimal example illustrates the issue:
```rust
#[tokio::test]
pub async fn test() {
    println!("First output");
    tokio::spawn(async move {
        loop {}
    });
    println!("Second output");
    tokio::time::sleep(Duration::from_millis(1000)).await;
    println!("Third output");
}
```

I would expect the third output to be printed about 1 second after the second output, however it is never printed. If I am not mistaken, the "main" thread (the `test()` function's) should not be impaired by whatever demanding tasks are computed in `tokio::spawn(...)`ed threads.

**Comment by Darksonn** [comment]
Tests use the current-thread runtime, so spawned tasks also happens on the "main" thread.

**Comment by a-0-dev** [comment]
Found it myself, you can configure the runtime to use `multi_thread` by setting
```
#[tokio::test(flavor = "multi_thread")]
```
above the test function.

Thanks @Darksonn for your quick support!
