### ISSUE TITLE
Async/Await interface for UDP

### ISSUE THREAD

**Issue by pusateri** [tokio-rs/tokio#616]
## Version

```
├── tokio v0.1.8                                                                
│   ├── tokio-codec v0.1.0
│   │   └── tokio-io v0.1.8
│   ├── tokio-current-thread v0.1.1
│   │   └── tokio-executor v0.1.4
│   ├── tokio-executor v0.1.4 (*)
│   ├── tokio-fs v0.1.3
│   │   ├── tokio-io v0.1.8 (*)
│   │   └── tokio-threadpool v0.1.6
│   │       └── tokio-executor v0.1.4 (*)
│   │   └── tokio-io v0.1.8 (*)
│   ├── tokio-io v0.1.8 (*)
│   ├── tokio-reactor v0.1.5
│   │   ├── tokio-executor v0.1.4 (*)
│   │   └── tokio-io v0.1.8 (*)
│   ├── tokio-tcp v0.1.1
│   │   ├── tokio-io v0.1.8 (*)
│   │   └── tokio-reactor v0.1.5 (*)
│   ├── tokio-threadpool v0.1.6 (*)
│   ├── tokio-timer v0.2.6
│   │   └── tokio-executor v0.1.4 (*)
│   ├── tokio-udp v0.1.2
│   │   ├── tokio-codec v0.1.0 (*)
│   │   ├── tokio-io v0.1.8 (*)
│   │   └── tokio-reactor v0.1.5 (*)
│   └── tokio-uds v0.2.1
│       ├── tokio-io v0.1.8 (*)
│       └── tokio-reactor v0.1.5 (*)
├── tokio-core v0.1.17
│   ├── tokio v0.1.8 (*)
│   ├── tokio-executor v0.1.4 (*)
│   ├── tokio-io v0.1.8 (*)
│   ├── tokio-reactor v0.1.5 (*)
│   └── tokio-timer v0.2.6 (*)
└── tokio-io v0.1.8 (*)
```

## Platform

Darwin xxxxxxx 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

## Description

I have code to join a UDP socket to a multicast group here:

[socket2 multicast join code](https://gist.github.com/pusateri/df98511b88e9000f388d344a1f3db9e7)

I want to take the received UDP multicast packets and iterate over them using the new async/await pattern that is now available for TCP with .incoming but this isn't available for UDP.

**Comment by tobz** [comment]
Right, `TcpListener` is the only thing that implements `incoming()` for waiting on new connections.

There's no equivalent for UDP given that it's connectionless.

If you're simply looking for a stream interface to the packets themselves coming in over the UDP socket, you could look at `tokio::net::UdpFramed`. Framing is a high-level approach to extracting fully-formed messages from raw data over asynchronous TCP/UDP sockets.

**Comment by carllerche** [comment]
UDP should have `_async` fns added via an extension trait. This would let you do:

```rust
let packet = await!(udp.recv_async());
```

The strategy is to implement futures for all `poll_*` functions that borrow self, similar to how it is done for AsyncRead / AsyncWrite.

It should be relatively straightforward to implement in the `tokio-async-await` crate. I would be happy to take a PR.

**Comment by pusateri** [comment]
Yes, I am looking for a futures stream of UDP packets received on the multicast group. I can look at Framing. I mostly want to create a chain and perform filtering and translation on the packets.

**Comment by starsheriff** [comment]
Hei @carllerche, I'm interested in working on that issue. It looks to me that it might be something suited as a first PR since the Tcp implementation serves as a reference. What do you think?

**Comment by pusateri** [comment]
Yes. I would use it for DNS queries and responses if it were available.

**Comment by carllerche** [comment]
@starsheriff sorry for the delay. I'd love to get a PR. Always feel free to ask questions in http://gitter.im/tokio-rs/dev/ if you need pointers to get started on the PR.

Cheers.

**Comment by starsheriff** [comment]
I'm currently working on something else. If I am done with it I'll take a look.

**Comment by Firstyear** [comment]
There is some interest from users of the Actix project for Udp to be Async so that UdpFramed can be used with AsyncWrite and AsyncRead.

**Comment by bryandmc** [comment]
Is this PR gonna be merged? Are you guys `'await'ing` (pun intended) the resolution of the new `.await` syntax? Just wanna get an idea where tokio is heading on this..
