### ISSUE TITLE
Split tokio_threadpool::blocking into separate roles

### ISSUE THREAD

**Issue by jsgf** [tokio-rs/tokio#617]
`tokio::blocking` is currently documented as:
> The blocking function annotates a section of code that performs a blocking operation, either by issuing a blocking syscall or by performing a long running CPU-bound computation.

The two cases - "CPU bound" and "blocking syscall" are similar from the perspective of async code, in that they both mean "this thread is going to be out of commission for running `poll`".

But the other effect is to move this thread into a separate distinct pool. The size of that pool matters for the point of view of the work being performed. If the work is CPU-bound, then having more threads than (approx) number of cores is just going to cause lots of context switching but no throughput improvement. On the other hand, you might also want multiple priorities of worker threads so that long-running background work doesn't starve shorter, more important work out of threads.

For the "blocking in syscall" case, you want as many threads as you are willing to spend resources on (mostly memory for stacks, I suspect).

So this suggests that we'd like, at the very least, `blocking_cpu` and `blocking_io` to broadly categorize the cases. One could consider a more general `blocking_with_pool` and a more general concept of arbitrary subpools, but that's getting more complex.

**Comment by carllerche** [comment]
IMO, any additional coordination to handle limits can probably be handled by an additional layer of abstraction on top of the single call instead of adding more logic to the threadpool. What do you think?

**Comment by jsgf** [comment]
I think a lot of this comes from my confusion over whether `blocking` is an operation on a specific future, or if its an operation on a whole task. I'd assumed the former, but as https://github.com/tokio-rs/tokio/issues/618 discusses, its actually an operation on the whole task.

This makes it a lot less useful than I'd first thought, since it doesn't allow a task to make progress if there is one future in `blocking` but others which are not blocked and could make progress if they had a thread to run on.

**Comment by carllerche** [comment]
Is this issue still needed with #618? What are the action items to close this?

**Comment by jsgf** [comment]
I think #629 addresses this.
