### ISSUE TITLE
Add Sink trait impl to Either

### ISSUE THREAD

**Issue by mattsse** [tokio-rs/tokio#6181]
**Is your feature request related to a problem? Please describe.**

The docs of `tokio_util::either::Either` state

> Combines two different futures, streams, or sinks having the same associated types into a single type.

Though Either does not implement Sink

**Describe the solution you'd like**
Implement Sink for Either if Error types and message type match, similar to Stream

https://docs.rs/tokio-util/0.7.10/tokio_util/either/enum.Either.html#impl-Stream-for-Either%3CL,+R%3E

**Comment by mobley-trent** [comment]
Hello @mattsse I'd like to work on this

**Comment by Darksonn** [comment]
@mobley-trent Go ahead and submit a PR. You can ask in `#tokio-dev` on our discord if you run into trouble.
