### ISSUE TITLE
Allow Semaphore to reserve available permits.

### ISSUE THREAD

**Issue by leptonyu** [tokio-rs/tokio#6191]
**Is your feature request related to a problem? Please describe.**
I want to hold requester to get permit from semaphore, the easiest way is requesting all remaining permits. Current API need loop to request all available permits. 

**Describe the solution you'd like**

Add two new APIs:

- pub async fn acquire_all_owned(
    self: Arc<Self>
) -> Result<OwnedSemaphorePermit,AcquireError>
- pub async fn acquire_all(
    self: &Self
) -> Result<SemaphorePermit<'_>, TryAcquireError>

**Comment by leptonyu** [comment]
As I mentioned above, we need to use `loop` to retry these two operations to get all remaining permits. Low level code could do better.

@Totodore

**Comment by Darksonn** [comment]
You can implement this yourself:
```rs
use tokio::sync::{Semaphore, SemaphorePermit, TryAcquireError};

fn acquire_all(sem: &Semaphore) -> Option<SemaphorePermit<'_>> {
    loop {
        match sem.try_acquire_many(sem.available_permits() as u32) {
            Ok(permits) => return Some(permits),
            Err(TryAcquireError::Closed) => return None,
            Err(TryAcquireError::NoPermits) => {},
        }
    }
}
```
I don't think we will add a dedicated method for this.
