### ISSUE TITLE
Implement Listener for Either

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6201]
The tokio-util crate has a type called [`Either`][2] for handling the case where you have one of two possible types. It implements various IO traits, but currently not the [`Listener`][1] trait.

To close this issue, add an implementation of the `Listener` trait for `Either`.

[1]: https://docs.rs/tokio-util/latest/tokio_util/net/trait.Listener.html
[2]: https://docs.rs/tokio-util/latest/tokio_util/either/enum.Either.html

**Comment by saiintbrisson** [comment]
Having `Either<L, R>` implement `Listener` means the trait's `Io` and `Addr` asoc types must also be `Either<L::{Io,Addr}, R::{Io,Addr}>`, right? Or are you thinking of another way of defining this impl?

**Comment by Darksonn** [comment]
Yeah, that sounds correct to me.

**Comment by Darksonn** [comment]
As discussed in #6206, we already have methods on `Either` for this, so this is not needed. Unfortunately, I did not notice that when opening this issue.
