### ISSUE TITLE
Implement AsyncWrite for io::Empty

### ISSUE THREAD

**Issue by mcastorina** [tokio-rs/tokio#6233]
**Is your feature request related to a problem? Please describe.**

I'm trying to create a no-op stream, but cannot find any utilities that implement both `AsyncRead` and `AsyncWrite` in a single object.

**Describe the solution you'd like**

Implement `AsyncWrite` trait for the type returned by `tokio::io::empty()`.

**Describe alternatives you've considered**

I've looked for a way of combining two separate `AsyncRead` and `AsyncWrite` objects into one, but couldn't find how to do that.

**Additional context**

[std::io::empty()](https://doc.rust-lang.org/std/io/fn.empty.html) implements both `Read` and `Write`, so I think it makes sense for tokio to parallel that behavior.

**Comment by Darksonn** [comment]
This seems like a reasonable addition.

See also the recently merged #6220.
