### ISSUE TITLE
tokio-async-await tests don't compile

### ISSUE THREAD

**Issue by liranringel** [tokio-rs/tokio#624]
## Version
tokio-async-await 0.1.2

## Description

I run `cargo test` in the `tokio-async-await` directory.
The code in the master fails to compile:
```rust
error: unused attribute
  --> src\lib.rs:79:1
   |
79 | #[macro_export]
   | ^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src\lib.rs:5:24
   |
5  | #![cfg_attr(test, deny(warnings))]
   |                        ^^^^^^^^
   = note: #[deny(unused_attributes)] implied by #[deny(warnings)]
```

**Comment by carllerche** [comment]
Any chance to get a PR? 😄

**Comment by liranringel** [comment]
No problem.
There is 1 more issue. Since #585 `tokio` is not referred as `tokio_main` so I also get that error:
`error[E0465]: multiple rlib candidates for tokio found`.
It happens because of the way cargo/rustc looks for the dependencies, and it has 2 rlib files with the same `libtokio` prefix.
Just making sure, is there a reason not to rename it back (to `tokio_main`)?

**Comment by carllerche** [comment]
Ah yes, there is a bug in Cargo with regards to renaming dependencies. Try creating a new crate that depends on tokio-async-await as tokio and it doesn't work :(
