### ISSUE TITLE
Non Send futures discussion

### ISSUE THREAD

**Issue by dev-ardi** [tokio-rs/tokio#6241]
@matklad 's [blog post ](https://matklad.github.io/2023/12/10/nsfw.html#Non-Send-Futures-When)criticises work stealing runtimes and the trait bounds it forces the users to use.

I haven't seen any discussion here so I'm opening this issue so that this can be easily discussed somewhere public.

**Comment by matklad** [comment]
To clarify, this is strictly a language issue, not a library issue. There’s nothing tokio as a library can realistically do here. 

The most relevant discussion happens in wg-async Zulip stream: https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async/topic/Non-.60Sync.60.20borrow.20across.20.60.2Eawait.60.3F

**Comment by carllerche** [comment]
Thanks, this is not a Tokio issue. Any discussion should happen external to the Tokio tracker.
