### ISSUE TITLE
`tokio::io::copy` should yield if it copies too many times

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6250]
If `tokio::io::{copy,copy_bidirectional}` are given streams that don't interact with coop and have a lot of data available, then they should yield after copying data some number of times.

One way to do this is to have `copy` consume a coop budget each time it copies a chunk of data.

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by hi-rustin** [comment]
@Darksonn Is there any existing code example I can follow? I am not sure what is the right way to do it.

**Comment by Darksonn** [comment]
You can look for previous similar PRs. For example  #6254. Also check out [this search query](https://github.com/tokio-rs/tokio/pulls?q=label%3AM-coop+).
