### ISSUE TITLE
AsyncWrite impl for File uses seek, while there exists writable files that are not seekable

### ISSUE THREAD

**Issue by ii41** [tokio-rs/tokio#6258]
**Version**
tokio v1.35.1

**Platform**
Linux 6.5.7.arch1-1

**Description**
`tokio::fs::File`'s `tokio::io::AsyncWrite` implementation calls `seek` on the file: https://github.com/tokio-rs/tokio/blob/02b779e315c5c5f0dbbc8b56fc711cc8e665ee1e/tokio/src/fs/file.rs#L676

However, on unix systems, a writable file can be non-seekable. For instance, `/dev/tty` which is the file representing the terminal device connected to the process is not seekable. As a result, a user can get a "Illegal seek" OS error even if they only write to and never seek a file.

The code below triggers the problem. I'm not sure about the reason why `seek` is used here or in what exact situation it is called, so I couldn't find a simpler example.

```rust
use tokio::fs::OpenOptions;
use tokio::io::{AsyncReadExt, AsyncWriteExt};

async fn read_tty(tty: &mut tokio::fs::File) -> (u8, usize) {
    let mut buf = [0; 1];
    let count = tty.read(&mut buf).await.unwrap();
    (buf[0], count)
}

async fn read_stdin(stdin: &mut tokio::io::Stdin) -> (u8, usize) {
    let mut buf = [0; 1];
    let count = stdin.read(&mut buf).await.unwrap();
    (buf[0], count)
}

#[tokio::main]
async fn main() {
    let mut tty = OpenOptions::new()
        .read(true)
        .write(true)
        .open("/dev/tty")
        .await
        .unwrap();
    let mut stdin = tokio::io::stdin();
    loop {
        let (byte, count) = tokio::select! {
            ret = read_tty(&mut tty) => ret,
            ret = read_stdin(&mut stdin) => ret,
        };
        println!("{:?}", byte);
        if count == 0 {
            tty.write(b"stdin is closed\n").await.unwrap();
        }
    }
}
```

To see this problem, firstly, create a fifo:

```sh
mkfifo fifo
```

Then, build and run this program with the fifo piped in:

```sh
cat fifo | cargo run
```

In another terminal, write into the fifo:

```
cat > fifo
```

You can send input to either the terminal where the program itself is run or the terminal where `cat > fifo` is used. You can see that the bytes sent get printed out as expected. Then, you can close the pipe by pressing `Ctrl-C` on the `cat > fifo` terminal.

I expected to see this happen: the program keeps printing "stdin is closed".

Instead, this happened: the program crashes with `NotSeekable` error.

**Comment by Darksonn** [comment]
This cannot be fixed without significantly hurting the performance of `tokio::fs::File` on real files. To read data from a pipe, please use [`tokio::net::unix::pipe`](https://docs.rs/tokio/latest/tokio/net/unix/pipe/index.html) (or [`AsyncFd`](https://docs.rs/tokio/latest/tokio/io/unix/struct.AsyncFd.html)) instead. 

If you need to support any kind of file, then please use `std::fs::File` from within `spawn_blocking` or `std::thread::spawn` instead.

**Comment by ii41** [comment]
All right. `AsyncFd` is useful for my use case it seems. Thanks for the pointer.
