### ISSUE TITLE
Documentation of tokio::sync::Mutex needs to be clearer about the FIFO behavior

### ISSUE THREAD

**Issue by hlavaatch** [tokio-rs/tokio#6278]
FIFO behavior of the `tokio::sync::Mutex` needs to be documented more clearly, it is only mentioned in the discussion of the example that is easy to miss and does not look official enough to be relied on

**Comment by Darksonn** [comment]
Thank you. Yes, we guarantee that the mutex gives out guards in FIFO order, and we will not change it in the future. This should be clear from the documentation.

**Comment by azuredream** [comment]
Hi @Darksonn, I've opened a PR according to your discussions.
I'm newcomer to this repo, your guidance and insights would be greatly appreciated.
Thanks!
