### ISSUE TITLE
Add Memory Mapped Files for Windows IPC

### ISSUE THREAD

**Issue by RivenSkaye** [tokio-rs/tokio#6286]
**Is your feature request related to a problem? Please describe.**
Tokio (and the underlying Mio) support several IPC mechanisms, including sockets and pipes and they make it rather easy to leverage Linux's POSIX extension for named pipes to get IPC to multiple clients sorted. Currently, however, the only supported mechanism for this on Windows is the slow Named Pipe implementation offered there. I'm currently in a position where I need to make a single USB camera feed accessible to several reading applications at the same time. This results in a problem due to either the latency of Named Pipes and multithreading if a task spends too much time and the next frame has not yet been read, or when only providing frames on request and having to wait for the next frame to come in. All in all, it's just inefficient and error-prone or slow.

**Describe the solution you'd like**
Through mapping a specific use of the invalid file handle enum, it's possible to create shared memory on Windows as well, using the [Memory Mapped Files](https://learn.microsoft.com/en-us/dotnet/standard/io/memory-mapped-files) mechanism; this is a lot faster and instead only requires you know a couple things about the shared state for different applications:
1. The upper bound of the size of the data you're sharing (in my case, I know how big every frame is)
2. The name of the MMF to create (this allows developers to open the same MMF in multiple applications)
3. the scope (same session, global) controlled through [flags and permissions described here](https://learn.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory), which allows for leveraging system services to provide accessibility to non-elevated readers.

For local-only IPC on Windows, this is by far the fastest way to do it, with no risk of breakage or errors if other processes don't need to ready every byte shared or if multiple processes need to access the same data. There also isn't an upper bound on the amount of allowed readers other than whatever cap exists for file handles, which means not having to track existing states and open handles. It also allows for easily scaling up the amount of accessing instances, as this doesn't need to be provided during pipe initialization.

**Describe alternatives you've considered**
I've considered Named Pipes, but these don't allow for the speed and flexibility required. I've also considered an on-disk file, but this would create _a lot_ of unnecessary writes to the disk for no good reason. I've also considered alternative IPC mechanisms leveraging a net listener, but this comes with latency again. Finally I've attempted to work with pipes to only write a frame to disk if a request was sent from the client, but this also hits speed problems. Leveraging on-disk files for this also creates additional cleanup mess.

**Additional context**
Memory Mapped Files are backed by the pagefile alone, which means writes only ever happen if the memory needs to be reclaimed. This means that during high activity (say, writing to it at set intervals from a constantly active process) it shouldn't cause pagefaults. And if it does, it's in a core system component that _should_ minimize the time it takes to acquire the resource anyway.
I'm currently busy using the `windows` crate in conjunction with `nokhwa` to set this up. Once I have a working implementation, I'll make something more generalized as a public example for how this could be implemented.

If the feature proposal is accepted, I think Tokio is the most suitable crate because of the `fs` and `io` modules present here being relevant. The relevance for `fs` is mainly for system bindings to handle file-like objects and handles (relevant to `fs` internals only), so I'd propose `io` as the module for this considering the boundary lies at reading from and writing to memory, after which it's up to the OS to decide where to leave it.

**Comment by Darksonn** [comment]
This doesn't sound like it would have any async logic at all.

How do you wait for a message to be sent when using memory mapped files?

**Comment by RivenSkaye** [comment]
MMFs are entirely treated entirely as files from code once opened, with the same problems and pitfalls as normal file I/O, which I presume would make the same logic apply as for other file operations (with the exception of writing to disk). This would also mean that reading and writing (albeit faster) still comes with the same constraints and Tokio's usual async file functions would work for actual use. I'd use the existing APIs for it, but the problem there is that there's no way to send the `windows::Win32::Foundation::INVALID_HANDLE_VALUE` when creating `Global\my_mmf_name`.
Besides that, MMFs are accessed through views, of which more than one can be opened. This means basic locking/waiting primitives could be implemented as well. The simplest example would be storing read and write locks in the first few bytes to prevent different users of the memory area from writing at the same time, or reading while a write is in progress.

If I'm wrong and I can manually spawn the file through the `windows`(`-sys`?) bindings and then treat it as a file within the context of Tokio, I'm all ears for how that'd work though.

**Comment by Darksonn** [comment]
The `tokio::fs` module doesn't really do true async IO. It just runs the equivalent `std::fs` operation in the background on the `spawn_blocking` thread-pool.

Right now, what you've described does not sound like it belongs in Tokio. If the memory mapped files ultimately just boil down to using blocking operations inside `spawn_blocking`, then we won't add an API for that in Tokio. However, you would be able to implement it in an external crate by calling Tokio's `spawn_blocking` method to off-load blocking operations.

**Comment by RivenSkaye** [comment]
In that case, I'm sorry for wasting time. I'll see if there's a way to safely (or at least soundly) coerce the `windows` `HANDLE` into a Rust `fd` and roll my own then, thanks!

**Comment by Darksonn** [comment]
You can convert an `std::fs::File` into a `tokio::fs::File`.

**Comment by RivenSkaye** [comment]
Yeah the challenge there isn't about `std::fs::File`, it's about a file handle from `windows::Win32::System::Memory::CreateFileMapping*` which returns a `windows::Win32::Foundation::HANDLE` (which is a pointer pretending to be an `isize`
