### ISSUE TITLE
Add New Attribute Macro for making function run in background when called.

### ISSUE THREAD

**Issue by alelopezperez** [tokio-rs/tokio#6295]
**Is your feature request related to a problem? Please describe.**
It gets quite repetitive to add `tokio::spawn(async{ ... })` when trying to make a fn run as a task run on the background.
Imagine when receiving a webhook and you need to respond with a 200 to the external service to notify a receipt  successful
```
fn process_payload(payload:Json<Value>){
    `tokio::spawn( async { 
        ...Process Value... 
     })
}
async fn webhookservice(payload: web::Json<serde_json::Value>){
    process_payload(payload);
}
``` 

**Describe the solution you'd like**
I propose this attibute tag for async `fn`
```
#[background_task]
async fn process_payload(payload:Json<Value>){
    insert_to_db(payload).await;
}
async fn webhookservice(payload: web::Json<serde_json::Value>){
    process_payload(payload);
}
```
The Macro Changes the fn to
```
fn process_payload(payload:Json<Value>){
    tokio::spawn( async { 
        insert_to_db(payload).await;
     });
}
```

**Describe alternatives you've considered**
Just Keep using the old syntax.

**Additional context**
This Macro will also handle when fn return values.
`async fn()->i32 will return tokio::JoinHandle<i32> `

I already have a working demo.

**Comment by Darksonn** [comment]
I don't really want to add any more macros, especially for something that could easily be implemented outside of Tokio.

**Comment by alelopezperez** [comment]
@Darksonn  I see your point, I did create a crate just for that `tokio-extra-macros`.
Do I wait for an automatic closing of the issue to see if more interactions come by?, or should i close it myself now?
