### ISSUE TITLE
Support an API to extract backtrace information from taskdump

### ISSUE THREAD

**Issue by mox692** [tokio-rs/tokio#6309]
**Is your feature request related to a problem? Please describe.**
Currently, the only supported output for taskdump is logging, as shown in the examples [here](https://github.com/tokio-rs/tokio/blob/4846959e8a534cf2aff63f8613e5f69a7d2ce5f8/examples/dump.rs#L50-L54). However, I would like to add a public API that can extract this backtrace information. By adding such an API, it will become possible to handle taskdump data programmatically, making it useful for various purposes.

**Describe the solution you'd like**
I would like to add a public API something like this:

```rust
struct Symbol {
  // one call stack info
}

pub struct TraceTree {
  symbol: Symbol,
  children: Vec<TraceTree>
}

impl Task {
  pub fn trace_tree(&self) -> TraceTree { ... }
}

async fn run {
  let handle = tokio::runtime::Handle::current();
  let dump = handle.dump().await;
  for task in dump.tasks().iter() {
    // get a trace tree per one tokio task.
    let root: TraceTree = task.trace_tree();
		
    // some traverse operations...
  }
}
```

We already have an internal struct named [Tree](https://github.com/tokio-rs/tokio/blob/4846959e8a534cf2aff63f8613e5f69a7d2ce5f8/tokio/src/runtime/task/trace/tree.rs#L11), so I believe it's not too hard to provide such an API.

**Additional context**
related issue: https://github.com/tokio-rs/tokio/issues/5638

**Comment by Darksonn** [comment]
cc @jswrenn

**Comment by mox692** [comment]
Thanks for clarifying the context!
Yeah, deciding on the right api seems difficult, but I believe we should eventually reach.

**Comment by arielb1** [comment]
Is there a strong reason we don't just export an API that is of the form:
```rust
#[derive(Serialize, ...)]
struct TokioBacktraceFrame {
    name: Option<Vec<u8>>,
    name_demangled: Option<String>,
    addr: Option<*mut c_void>,
    filename: Option<PathBuf>,
    lineno: Option<u32>,
    colno: Option<u32>,
}

impl Trace {
    pub fn as_json_api(&self) -> Vec<Vec<TokioBacktraceFrame>>;
}
```

I believe that this will work with every form of taking backtraces (especially given that all fields are options)

**Comment by Darksonn** [comment]
Tokio does not and will not depend on serde.

**Comment by arielb1** [comment]
K, so without the derive(Serialize) but with exposing accessors

**Comment by Darksonn** [comment]
We can probably expose some accessors.

**Comment by arielb1** [comment]
So are you positive for a function returning a `Vec<Vec<TokioBacktraceFrame>>`?

**Comment by Darksonn** [comment]
Yes, we can add it.
