### ISSUE TITLE
Automatically choose bind address in UDPSocket::connect

### ISSUE THREAD

**Issue by vehlwn** [tokio-rs/tokio#6342]
It would be convenient if `UDPSocket::connect` method automatically choose local address like TCPStream when creating client UDP sockets. For now (tokio 1.36.0) it imitates std::net API which also lacks this feature and requires bind() call with manual IP address. For example, [Go](https://pkg.go.dev/net#DialUDP) and [Boost.Asio](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/basic_datagram_socket/connect/overload1.html) does have this feature.

```go
package main

import (
    "net"
    "fmt"
    "os"
)

func main() {
    sockAddr, err := net.ResolveUDPAddr("udp", "9.9.9.9:5050")
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
    sock, err := net.DialUDP("udp", nil, sockAddr)
    if err != nil {
        fmt.Println("Can't connect to remote:", err)
        os.Exit(1)
    }
    fmt.Println("Local addr:", sock.LocalAddr())
}
```

```c++
#include <iostream>

#include <boost/asio/io_context.hpp>
#include <boost/asio/ip/udp.hpp>

int main() {
  using namespace boost::asio;
  auto ioc = io_context();
  auto sock = ip::udp::socket(ioc);
  sock.connect(ip::udp::endpoint(ip::make_address("9.9.9.9"), 6666));
  std::clog << "Local addr: " << sock.local_endpoint() << std::endl;
}
```

**Comment by vehlwn** [comment]
Std and tokio sockets require bind() call to construct them. Go and asio doesn't. They automatically choose bind address from routing table.

**Comment by vehlwn** [comment]
I think the issue can be closed. I realized it's a standard Linux feature where wildcard IP addresses have special meaning.

```python
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.bind(("0.0.0.0",0))
>>> s.getsockname()
('0.0.0.0', 35168)
>>> s.connect(("9.9.9.9",5645))
>>> s.getsockname()
('192.168.0.2', 35168)

```

Rust sockets have the same behavior:

```rust
async fn test_local_addr(local: &str, remote: &str) {
    let sock = tokio::net::UdpSocket::bind(local).await.unwrap();
    println!("tokio local before connect = {}", sock.local_addr().unwrap());
    sock.connect(remote).await.unwrap();
    println!("tokio local after = {}", sock.local_addr().unwrap());
}

fn test_local_addr_std(local: &str, remote: &str) {
    let sock = std::net::UdpSocket::bind(local).unwrap();
    println!("std local before connect = {}", sock.local_addr().unwrap());
    sock.connect(remote).unwrap();
    println!("std local after = {}", sock.local_addr().unwrap());
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    test_local_addr("0.0.0.0:0", "9.9.9.9:5555").await;
    test_local_addr("[::]:0", "[2620:fe::fe]:5555").await;
    test_local_addr_std("0.0.0.0:0", "9.9.9.9:5555");
    test_local_addr_std("[::]:0", "[2620:fe::fe]:5555");
    return Ok(());
}
```

tokio local before connect = 0.0.0.0:39058
tokio local after = 192.168.0.2:39058
tokio local before connect = [::]:35067
tokio local after = [fd::...2]:35067
std local before connect = 0.0.0.0:56088
std local after = 192.168.0.2:56088
std local before connect = [::]:45617
std local after = [fd::...2]:45617

PS: In Linux UDP sockets can be used even without bind() call. See `man 7 udp` (https://man7.org/linux/man-pages/man7/udp.7.html). In tokio and std::net it's impossible to use UDP sockets without bind().

**Comment by maminrayej** [comment]
There is an open [issue](https://github.com/rust-lang/rust/issues/96127) for this in std. Since we'd like to follow std, we're going to await their decision in order to move forward with this issue.

**Comment by vehlwn** [comment]
Ok, thanks. I continue using bind() then.
