### ISSUE TITLE
Cross-compiled builds often fail panic_in_block_on

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6361]
I often see the panic_in_block_on test fail on cross-compiled builds. Here's an example failure:
```
     SIGSEGV [   2.671s] tokio::rt_common alt_threaded_scheduler_4_threads::panic_in_block_on

--- STDOUT:              tokio::rt_common alt_threaded_scheduler_4_threads::panic_in_block_on ---

running 1 test
test alt_threaded_scheduler_4_threads::panic_in_block_on - should panic ... 
--- STDERR:              tokio::rt_common alt_threaded_scheduler_4_threads::panic_in_block_on ---
thread 'alt_threaded_scheduler_4_threads::panic_in_block_on' panicked at tokio/tests/rt_common.rs:880:29:
explicit panic
stack backtrace:
qemu-aarch64: QEMU internal SIGSEGV {code=MAPERR, addr=0x20}
```
I've never seen it fail on a build that isn't cross-compiled.

To me, the failure looks like a double-panic.

**Comment by pmcgleenon** [comment]
I suspect this might be related to the QEMU version used in the ubuntu-latest runner for the cross-compiled tests.   I've tried QEMU version 7.2 and it seemed to help.

**Comment by Darksonn** [comment]
Thanks! I will close this for now and reopen if I see it again.

**Comment by pmcgleenon** [comment]
Sounds good!
