### ISSUE TITLE
Windows Named pipes invalid memory access

### ISSUE THREAD

**Issue by radekvit** [tokio-rs/tokio#6369]
**Version**
tokio v1.36.0

**Platform**
Windows 10 Enterprise 64-bit
version 10.0.19045

**Description**
When running a simple named pipes `tokio` program with Application Verifier with `heap` turned on, invalid memory access is detected in `ScheduledIo::set_readiness`.

Reproduction code:

Cargo.toml:
```toml
[package]
name = "tokio-heaptest"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["net", "macros", "rt", "rt-multi-thread", "time"] }
```

main.rs:
```rust
use std::time::Duration;

use tokio::net::windows::named_pipe::{ClientOptions, ServerOptions};

const PIPE_NAME: &str = r"\\.\pipe\tokio-heap-issue";

#[tokio::main]
async fn main() {
    let connect_client = tokio::spawn(connect_client());
    tokio::spawn(client_fn());

    let connected = tokio::time::timeout(Duration::from_millis(1000), connect_client)
        .await
        .unwrap_or(Ok(Ok(false)))
        .unwrap_or(Ok(false))
        .unwrap_or(false);
    assert!(connected);
}

async fn connect_client() -> std::io::Result<bool> {
    let server = ServerOptions::new()
        .first_pipe_instance(true)
        .create(PIPE_NAME)?;

    server.connect().await?;

    Ok(true)
}

async fn client_fn() {
    // five tries to connect
    for _ in 0..5 {
        tokio::time::sleep(Duration::from_millis(20)).await;
        match ClientOptions::new().read(true).write(true).open(PIPE_NAME) {
            // Return after we've connected
            Ok(_) => return,
            Err(_) => {
                // pipe not created yet or busy, sleep and wait
                continue;
            }
        };
    }
}
```

With the following settings in [Application Verifier](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier)
![image](https://github.com/tokio-rs/tokio/assets/25612317/8fb400ce-c979-4c37-a958-5c2802abc5e1)

You can produce crash dumps by adding the following settings in the registry (see [this article](https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)):
In `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`:
- string `DumpFolder`: `C:\path\to\dump\folder`
- DWORD `DumpCount`: The number of dumps to keep
- DWORD `DumpType`: 2 for a full dump

I expected to see this happen: The program would run without accessing invalid memory. This happens in both debug and release builds.

Instead, this happened: The application crashes with `STATUS_ACCESS_VIOLATION`. The dump shows that the program is trying to access invalid memory in `ScheduledIo::set_readiness` when trying to load an atomic variable, which should mean that `ScheduledIo` itself has likely been freed. We observed this access violation in our larger application **when a named pipe client disconnects**.

**Comment by radekvit** [comment]
I also tried older versions of `tokio` and found out that this worked fine with up to `1.29.1` and broke in `1.30`.

**Comment by daira** [comment]
https://github.com/tokio-rs/mio/pull/1760 is marked as fixing this bug, but note that tokio's (optional) dependency on mio is still at 0.8.9 which was vulnerable:

https://github.com/tokio-rs/tokio/blob/f6d061919f7a56eebf78edb1d1d379fadad33b6a/tokio/Cargo.toml#L98

I believe this shouldn't be considered fixed in tokio until all tokio crates only depend on a non-vulnerable version of mio (or otherwise mitigate the vulnerability).

**Comment by Thomasdezeeuw** [comment]
@daira you can run `cargo update -p mio` and you're good.

**Comment by daira** [comment]
I'm aware of that; see the last paragraph of my comment.
