### ISSUE TITLE
`tokio_stream::wrappers::WatchStream` should take `AsRef<Receiver<T>>`

### ISSUE THREAD

**Issue by allada** [tokio-rs/tokio#6385]
**Is your feature request related to a problem? Please describe.**
It would be useful if `tokio_stream::wrappers::WatchStream` could take something that be referenced as a `Receiver<T>`. This would be a nice way to give code the ability to have custom destructors that need to be notified if a client is no longer listening without doing it by polling on the sender side.

**Describe the solution you'd like**
`pub fn new(rx: Receiver<T>) -> Self` should be:
`pub fn new(rx: impl AsRef<Receiver<T>>) -> Self`

This would also allow us to pass in things like `Arc<Receiver<T>>` or any other wrappers.

**Comment by Darksonn** [comment]
It needs mutable access to the receiver, so `AsRef<Receiver<T>>` is not enough.

We could support `AsMut<Receiver<T>>`, but this wouldn't solve your problem. I also don't think it's that useful, and people could implement it themselves if they really need it. I'd rather keep it as-is.
