### ISSUE TITLE
Awaiting Read and Write Half concurrently causes spin lock.

### ISSUE THREAD

**Issue by Frostie314159** [tokio-rs/tokio#6396]
**Version**
```
│       └── tokio-io v0.1.13
│   └── tokio v1.36.0
│       └── tokio-macros v2.2.0 (proc-macro)
│   └── tokio v1.36.0 (*)
└── tokio v1.36.0 (*)
└── tokio v1.36.0 (*)
```

**Platform**
`Linux simon-framework 6.1.80-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:09:53 UTC 2024 x86_64 GNU/Linux
`

**Description**
When using the `split` function and awaiting both the read and write half concurrently, a spin lock is triggered, which causes cpu usage to skyrocket. This is actually noted in the code at `tokio/io/split.rs`.

**Comment by Darksonn** [comment]
Thank you for the issue. We should probably fix the spinlock, I agree.
