### ISSUE TITLE
Semaphore example on sending http requests

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6412]
The [`Semaphore`](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html) currently has a lot of great examples, but it is missing one about sending many http requests in parallel.

To close this issue, submit a PR with an example that sends many http requests in parallel, with some limit on how many requests will be sent at the time. The example does not need to use reqwest or similar directly - you can call some made-up function that actually performs the http request. The important part of the example is the limit on how many requests can happen at the same time.

Here's how I think it would differ from existing examples:
* It differs from the file and test examples in that the `Semaphore` is in an `Arc`, rather than in a global variable.
* It differs from the incoming requests example in that we call `acquire` _inside_ the call to `tokio::spawn`, rather than doing so before spawning. Also, we don't need `acquire_owned`.

I would put the example after the file example.

This is a good first issue intended for new contributors. For mentoring, ask here or in our Discord.

**Comment by czzrr** [comment]
Hi! I would like to take a look at this.
