### ISSUE TITLE
JoinHandle should implement Clone, to support arbitrary dependency DAGs

### ISSUE THREAD

**Issue by Pr0methean** [tokio-rs/tokio#6415]
**Is your feature request related to a problem? Please describe.**
For https://github.com/Pr0methean/OcHd-RustBuild, I have a graph of tasks in which several tasks may need to block waiting for the same subtask's result. Often this result is a `Pixmap` or `Mask` and is large enough that it should be shared through an `Arc<_>`.

**Describe the solution you'd like**
I'd like a `spawn` method that returns a type that either is, or can be converted to, a `JoinHandle`, but also implements `Clone` when the task's output types implement `Send`, so that I can pass it as a subtask to several different consumers. The outputs should generally be assumed to be too big to clone and wrapped in an `Arc<_>`, but if this can somehow be avoided for small types that implement `Copy` then I'd prefer that. The dependency graph is an arbitrary DAG.

Even better would be, for tasks with a common type, a scope that could detect duplicates and return cloned futures rather than spawning redundant ones. To avoid memory leaks, I'd need to close it for new tasks while waiting for the existing ones to finish.

**Describe alternatives you've considered**
I've so far had to roll my own. I'm using Rayon rather than Tokio because the tasks are CPU-intensive and my `CloneableLazyTask` struct probably wouldn't benefit from extending `JoinHandle`. However, Tokio could eliminate the need to roll my own solution more easily than Rayon, since Rayon doesn't have a `JoinHandle` equivalent at all.

The implementation of the cloneable tasks is here: https://github.com/Pr0methean/OcHd-RustBuild/blob/main/main/src/image_tasks/cloneable.rs.

The subtask-reusing dispatch is defined in the various `add_to` methods here: https://github.com/Pr0methean/OcHd-RustBuild/blob/main/main/src/image_tasks/task_spec.rs. Using it with derived `Eq`, as I'm doing, requires all instances of the `TaskSpec` types to have already been converted to a canonical form.

The `TaskSpec` instances are created using functions in task_spec.rs (which do the canonicalization) and macros in https://github.com/Pr0methean/OcHd-RustBuild/blob/main/main/src/texture_base/material.rs.

It also occurs to me that something similar may be possible using a separate `Arc<JoinSet<_>>` instance for each task, each containing only that task.

**Comment by Darksonn** [comment]
We will not make this change. It's too complicated to implement, and the use-case is rare. You can achieve the same thing yourself by wrapping the `JoinHandle` in `futures_util::future::Shared` or similar.

**Comment by Pr0methean** [comment]
Thanks; I've switched to using `futures_util::future::Shared<BoxFuture<'_, _>>` with the Tokio multithread executor, and so far the speed and accuracy are about the same as what I was getting with the Rayon executor after specifically adapting to the latter.
