### ISSUE TITLE
Panic within multi-threaded scheduler

### ISSUE THREAD

**Issue by hallmaxw** [tokio-rs/tokio#6416]
**Version**
tokio v1.32.1

**Platform**
5.10.209-198.858.amzn2.x86_64

**Description**
My application is a web service that spawns thousands of tokio tasks. In prod, we recently saw a panic caused by this line of code within the multi-threaded scheduler https://github.com/tokio-rs/tokio/blob/tokio-1.32.x/tokio/src/runtime/scheduler/multi_thread/park.rs#L144. Unfortunately, I don't have a full backtrace or example code to cause the panic.

**Comment by hallmaxw** [comment]
Here's the panic message:

>inconsistent park state; actual = 0

**Comment by Noah-Kennedy** [comment]
What rust version was this on?

**Comment by Darksonn** [comment]
Please move discussion to #6424.

**Comment by Noah-Kennedy** [comment]
@hallmaxw please hop over to the new issue if you can, we are looking for more information from folks to try and narrow down what it might be.
