### ISSUE TITLE
Runtime builder should not accept a tokio-threadpool builder.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#642]
Currently, the concurrent Runtime is configured by passing in a threadpool builder. This is problematic for two reasons:

1) It exposes `tokio-threadpool` as part of the `tokio` public API, preventing `tokio` from transparently bumping the version used internally.
2) All the options on the threadpool builder cannot be maintained. There are some that the Runtime must set, overwriting previously set values.

`Runtime` should provide its own builder settings and hide the threadpool builder type from the public API.

The steps forward are to update `runtime::Builder` to:

1) Hide and deprecate `threadpool_builder`.
2) Add `core_threads` representing `pool_size` on the threadpool builder.
3) Add `blocking_threads` representing `max_blocking` on the threadpool builder.
4) Add `name_prefix`, mirroring the same fn on the threadpool builder.
5) Add `stack_size`, mirroring the same fn on the threadpool builder.

No other configuration settings should be exposed right now.

**Comment by kpp** [comment]
Fixes https://github.com/tox-rs/tox-node/issues/25
