### ISSUE TITLE
tokio_util::io::poll_read_buf does not work with ?Sized type.

### ISSUE THREAD

**Issue by fakeshadow** [tokio-rs/tokio#6429]
**Is your feature request related to a problem? Please describe.**
For given case said api does not work.
```rust
fn poll_read(
    io: &mut (dyn tokio::io::AsyncRead + Unpin),
    cx: &mut std::task::Context<'_>,
    buf: &mut impl bytes::BufMut,
) {
    tokio_util::io::poll_read_buf(std::pin::Pin::new(io), cx, buf);
}
```

**Describe the solution you'd like**
add `?Sized` bound.

**Additional context**
I recall at some point the function has `?Sized` bound but have no idea when or why it's removed.

**Comment by Darksonn** [comment]
Thanks, adding `?Sized` sounds like a good idea.

> I recall at some point the function has `?Sized` bound but have no idea when or why it's removed.

I'm pretty sure it has always been the way it is now.
