### ISSUE TITLE
Document cancelation safety `AsyncBufReadExt::fill_buf`

### ISSUE THREAD

**Issue by jkalez** [tokio-rs/tokio#6430]
**Version**
1.36

**Platform**
All

**Description**
Documentation does not comment on the cancellation safety of [`AsyncBufReadExt::fill_buf`](https://docs.rs/tokio/latest/tokio/io/trait.AsyncBufReadExt.html#method.fill_buf). In my experimentation and in reading the source, I have not been able to determine the cancellation safety of `fill_buf`. Hopefully developers more familiar with the code can provide this information.

**Comment by Darksonn** [comment]
Thanks. That should definitely be fixed. The method is cancellation safe.
