### ISSUE TITLE
Semaphore deadlock

### ISSUE THREAD

**Issue by scw00** [tokio-rs/tokio#6450]
**Version**
`tokio v1.36.0`

**Platform**
Linux/Macos

**Description**
Semaphore might get deadlock when using `tokio::select` which is impact Rwlock, Mutex(maybe, haven't tested).

Semaphore::release will assign the returned permit to the waiters, if existed, by order. But user can create
several waiters for one semaphore on same task . So the order of the task waking is undefined , and the previous assignment of permits might lead to deadlock.

```
#[tokio::main]
async fn main() {
    use tokio::sync::RwLock;

    static LOCK: RwLock<()> = RwLock::const_new(());

    let locked = LOCK.try_write().expect("first lock always success");

    // Create a new Semaphore's waiter for this task.
    let future1 = Box::pin(LOCK.write());
    tokio::pin!(future1);

    tokio::select! {
        _ = &mut future1 => unreachable!("never enter, because we hold the locked. it regist a waiter in the waiters' list"),
        _ = std::future::ready(()) => {}
    }

    println!("create another waiter");

    // Create a new Semaphore's waiter for same task.
    let future2 = Box::pin(LOCK.write());
    tokio::pin!(future2);
    tokio::select! {
        _ = &mut future2 => unreachable!("never enter, because we hold the locked. it regist another waiter in the waiters' list"),
        _ = std::future::ready(()) => {}
    }

    // the future1 will be waken up along with the the WriteGuard dropped.
    std::mem::drop(locked);

    // the future1 is expected to be immedately waken up. but it is not,
    // because the future2's waiter shadow the future1's waiter.

    // Skip the future1 Although it is awake.
    // future1.await;

    // Now, we poll the future2. However we have returned the all the permits from the LockGuard.
    // The future2 is pending forever unless future1 resolved. Because the returned permit is asigned
    // to the future1.
    let _ = future2.await;
}

```

**Comment by Darksonn** [comment]
This is working as intended. See the documentation for `RwLock`:

> The priority policy of Tokio's read-write lock is _fair_ (or [_write-preferring_]), in order to ensure that readers cannot starve writers. Fairness is ensured using a first-in, first-out queue for the tasks awaiting the lock; if a task that wishes to acquire the write lock is at the head of the queue, read locks will not be given out until the write lock has been released. This is in contrast to the Rust standard library's `std::sync::RwLock`, where the priority policy is dependent on the operating system's implementation.

[_write-preferring_]: https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock#Priority_policies
