### ISSUE TITLE
Slowdown when using deeply nested vector

### ISSUE THREAD

**Issue by arnabanimesh** [tokio-rs/tokio#6458]
**Version**

tokio v1.37.0
    tokio-macros v2.2.0 (proc-macro)

**Platform**

Windows 11 23H2 22631.3296 (64 bit)

**Description**

Running slow

[short summary of the bug]

I tried this code:
```rust
use tokio;

#[allow(dead_code)]
#[derive(Clone)]
struct DummyStruct {
    x: i32,
}

fn f() -> Vec<DummyStruct> {
    vec![]
}

fn parentf() -> Vec<DummyStruct> {
    // Works properly on a simple vector
    // let _: Vec<Vec<Vec<Vec<Vec<DummyStruct>>>>> = Vec::new();
    // Slows down considerably on a level 4 nested vec with a struct
    let _: Vec<Vec<Vec<Vec<Vec<DummyStruct>>>>> =
        vec![vec![vec![vec![Vec::new(); 1000]; 1000]; 2]; 2];
    f()
}

async fn solve(idx: usize) {
    parentf();
    // To check where it is slowing down
    println!("{}",idx);
}

async fn solve_async_handler(idx_list: Vec<usize>) {
    idx_list.into_iter().for_each(|idx| {tokio::spawn(solve(idx));});
}

#[tokio::main]
async fn main() {
    solve_async_handler((0..800).collect::<Vec<usize>>()).await;
}
```

I expected to see this happen:

Uncomment the first dummyvec and comment out the 2nd one to see the expected outcome

Instead, this happened:

Run the sample code and check the slow performance

**Comment by Darksonn** [comment]
Why is this a Tokio bug? The `Vec` type is not part of Tokio.

**Comment by arnabanimesh** [comment]
It runs fine when run on a single thread on Windows and on multiple threads on Ubuntu 22.04 WSL2. But when running it on multiple threads on Windows then the problem arises.

Since the problem only appears when running on multiple threads I posted here. I will post it in rust lang repo as well.

**Comment by Darksonn** [comment]
Closing as not a Tokio bug. This is just how threading works.

**Comment by arnabanimesh** [comment]
Posted the issue in rust repo: https://github.com/rust-lang/rust/issues/123447
