### ISSUE TITLE
TcpListener::bind faild on windows server 2008 64-bit (Windows)

### ISSUE THREAD

**Issue by zhuxiujia** [tokio-rs/tokio#6461]
**Version**
last

**how to build**
use crate `https://github.com/felixmaker/thunk` and `https://github.com/Chuyu-Team/YY-Thunks`

command:
`thunk --os xp --arch x86 -- --release`

**Platform**
`cargo 1.77.1`
windows server 2008 64-bit (Windows)
rust stable 

**Description**
`TcpListener::bind().await ` faild
on `mio` crates the func `SetFileCompletionNotificationModes` return `Os { code:5,kind:PermissionDenied,message:"permission denied"}`

[short summary of the bug]

I tried this code:
```toml
[dependencies]
tokio = { version = "1", features = ["full"] }
```

```rust
use tokio::net::TcpListener;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let listener = TcpListener::bind("0.0.0.0:9000").await?;// here PermissionDined

    println!("done");

    // loop {
    //     let (mut socket, _) = listener.accept().await?;
    //     tokio::spawn(async move {
    //         let mut buf = [0; 1024];
    //         loop {
    //             let n = match socket.read(&mut buf).await {
    //                 // socket closed
    //                 Ok(n) if n == 0 => return,
    //                 Ok(n) => n,
    //                 Err(e) => {
    //                     eprintln!("failed to read from socket; err = {:?}", e);
    //                     return;
    //                 }
    //             };
    //             if let Err(e) = socket.write_all(&buf[0..n]).await {
    //                 eprintln!("failed to write to socket; err = {:?}", e);
    //                 return;
    //             }
    //         }
    //     });
    // }

    return Ok(());
}
```

[code sample that causes the bug]

the `cmd` is also Execute with administrator privileges
```log
C:\Users\Administrator\Desktop\w>w.exe
start
bind_addr 0.0.0.0:9000
call bind 0.0.0.0:9000
call listen
call listen done
bind 0.0.0.0:9000 success
register
interests_to_afd_flags
interests_to_afd_flags done
afd_group.acquire
Afd::new
NtCreateFile
RtlNtStatusToDosError
add_handle
SetFileCompletionNotificationModes
register fail=拒绝访问。 (os error 5)
last_err
Error: Os { code: 5, kind: PermissionDenied, message: "拒绝访问。" }
```

**Comment by zhuxiujia** [comment]
also you can see this [issues](https://github.com/Chuyu-Team/YY-Thunks/issues/70)

**Comment by Thomasdezeeuw** [comment]
I don't think rust support Windows Server 2008 any more, see https://github.com/rust-lang/compiler-team/issues/651.

**Comment by zhuxiujia** [comment]
> I don't think rust support Windows Server 2008 any more, see [rust-lang/compiler-team#651](https://github.com/rust-lang/compiler-team/issues/651).

I know, but support for lower versions of operating systems can be achieved by adjusting the link lib

**Comment by Thomasdezeeuw** [comment]
@zhuxiujia apparently not as in practice it doesn't work.

If you have a patch that would solve this we could consider it. But since neither Rust nor Microsoft supports a version that, I don't think the Tokio project should either.

**Comment by zhuxiujia** [comment]
> @zhuxiujia apparently not as in practice it doesn't work.
> 
> If you have a patch that would solve this we could consider it. But since neither Rust nor Microsoft supports a version that old, I don't think the Tokio project should either.

Asynchronous operation cancellation mechanism
In most asynchronous I/O libraries, the cancellation of operations is usually handled through the design logic of the library itself, rather than relying on the API of the underlying operating system. For example, SMOL may track the completion and cancellation of asynchronous tasks at a higher level through state management, rather than canceling operations through kernel level I/O. Libraries typically provide their own task cancellation logic, without relying on specific system calls to cancel underlying I/O operations .
What about you think this?

**Comment by Thomasdezeeuw** [comment]
@zhuxiujia I'm sorry, but Mio is not going to support Windows XP.
