### ISSUE TITLE
feature request - provide a Receive trait for the recv() method for all the different channel receivers.

### ISSUE THREAD

**Issue by xushichangdesmond** [tokio-rs/tokio#6476]
As titled;
I am hoping for this so that my library API can use ```Box<dyn Receive>``` as an incoming method parameter type.

**Comment by Darksonn** [comment]
There is the `Stream` trait? All of our receivers provide a `Stream` wrapper via the `tokio-stream` crate:

https://docs.rs/tokio-stream/latest/tokio_stream/wrappers/index.html

We will not provide a new trait for this.
