### ISSUE TITLE
Create a macro to support parameterized tests

### ISSUE THREAD

**Issue by lprekon** [tokio-rs/tokio#6483]
**Is your feature request related to a problem? Please describe.**
There is no easy way to create parameterized async tests, which test a chunk of async code with multiple input values, considering each set of input as a separate test case 

**Describe the solution you'd like**
A macro that looks something like `#[tokio::param_test(arg1, arg2,...)]` that can be applied to a test function multiple times, and will create a test case that passes the supplied arguments to the function. Applying the macro multiple times would create multiple test cases, and the test case names would be derived from the function name and the arguments supplied. All together, it might look something like this:
```
#[tokio::param_test(1, 2)]
#[tokio::param_test(2, 3)]
async fn test_not_equal(first: i32, second: i32){
    assert_ne!(first, second);
}
```

when looking at test output, one would see something like
```
test test_not_equal__1_2__... ok
test test_not_equal__2_3__... ok
```

**Describe alternatives you've considered**

1. A user could manually create a different test function for each set of inputs, factoring out shared code into a separate function. Drawbacks:
   - more boilerplate code for multiple functions
   - less readable, as test logic and test cases are spread across more lines
   - changes to test function signatures (e.g. changing number or type of arguments) has to be repeated across multiple functions
2. A user could create parameterized synchronous tests using a separate library, and manually setup and execute the tokio runtime within the test to execute async code. Drawbacks
   - Lose all convenience of a default runtime provided by the `#[tokio::test]` macro
3. A user could create a single async test function using the `[tokio::test]` macro and, within the function, iterate over different input values, testing each. Drawbacks:
   - Only see a single pass/fail in the test output, rather than a pass/fail result for each different input

**Additional context**
None

**Comment by Darksonn** [comment]
Thank you for the suggestion. This is a reasonable idea. However, specialized testing utilities are out of scope for the main Tokio crate. I recommend that you publish this as your own crate on crates.io instead.
