### ISSUE TITLE
Use `wasm32-wasip1` target

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6484]
Tokio currently only supports preview 1 of wasi (see #6323 on preview 2 support), and Rust [is renaming the wasi target to `wasm32-wasip1`](https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html) in the 1.78 release of Rust. 

Once Rust releases 1.78 in May 2024, we should update our wasi support to use the new target name. This fix does not need to be backported to LTS releases, since wasi support is an unstable feature.

Tokio's wasi support is unstable, so it does not need to respect Tokio's msrv. This means that it is okay that this change breaks unstable wasi support on older rustc versions. However, ordinary wasm is stable, so that should not break on older Rust versions. Please see [our documentation](https://docs.rs/tokio/latest/tokio/#wasm-support) for details on wasm support in Tokio.

**Comment by brooksmtownsend** [comment]
Does the completion of https://github.com/tokio-rs/tokio/pull/6528 solve this?

**Comment by mox692** [comment]
If I understand correctly, the old target name was actually only used in ci, so there was no change to the source code.

The change to ci was applied in the above pr, so I think this can be closed.
