### ISSUE TITLE
On docs.rs, ‘time::pause’ and ‘time::resume’ no longer state requirement on feature test-util

### ISSUE THREAD

**Issue by glts** [tokio-rs/tokio#6495]
**Version**
tokio 1.37.0

**Description**
Please compare docs.rs documentation for `tokio::time::pause`.

In Tokio 1.35.0 [it says](https://docs.rs/tokio/1.35.0/tokio/time/fn.pause.html):

> Available on crate features `time` and `test-util` only.

In Tokio 1.35.1 and following [it says](https://docs.rs/tokio/1.35.1/tokio/time/fn.pause.html):

> Available on crate feature `time` only.

But feature `test-util` is still required for functions `pause` and `resume`. In other words, this seems to be a regression in documentation.

**Comment by Darksonn** [comment]
Thank you for reporting this. Something must have changed in how the compiler infers this information.
