### ISSUE TITLE
Unstable net feature not compiling for WASM

### ISSUE THREAD

**Issue by maxwellflitton** [tokio-rs/tokio#6524]
**Version**
```
└── tokio v1.37.0
    └── tokio-macros v2.2.0 (proc-macro)
```

**Platform**
Macbook M2

**Description**
In the following link in the docs:

https://docs.rs/tokio/latest/tokio/#unstable-wasm-support

it states that using the `tokio_unstable` flag enables the use of `tokio::net` on the `wasm32-wasi` target. I have the following dependencies:

```
[dependencies]
tokio = { version = "1.37.0", features = ["macros", "io-util", "rt", "time", "net"] }
```

And have the following code in my `config.toml` file:

```
[target.wasm32-wasi]
rustflags = ["--cfg", "tokio_unstable"]
```

However, when I run the following command:

```
cargo build --target wasm32-wasi --release
```

I get the following error:

```
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling wasi v0.11.0+wasi-snapshot-preview1
   Compiling bytes v1.6.0
   Compiling pin-project-lite v0.2.14
   Compiling mio v0.8.11
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling tokio-macros v2.2.0
   Compiling tokio v1.37.0
error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> /Users/maxwellflitton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/lib.rs:470:1
    |
470 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `tokio` (lib) due to 1 previous error
```
I then override the cargo to nightly and get the following error on compilation:

```
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling wasi v0.11.0+wasi-snapshot-preview1
   Compiling bytes v1.6.0
   Compiling pin-project-lite v0.2.14
   Compiling mio v0.8.11
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling tokio-macros v2.2.0
   Compiling tokio v1.37.0
error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> /Users/maxwellflitton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/lib.rs:470:1
    |
470 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `tokio` (lib) due to 1 previous error
```

I can't find any documentation or guides on how to use tokio unstable for TCP connections that wasmtime run. I am trying to get to the following command:

```
wasmtime run ./some_file.wasm -W tcp-listen=127.0.0.1:8080
```

**Comment by maxwellflitton** [comment]
updated my config.toml in my root which removed the warnings but still resulted in the same compilation outcome

**Comment by mox692** [comment]
Hmm, I was able to build on my local mac without any problems, following the steps you have described.

Looking at the code, it seems that the error is generated [here](https://github.com/tokio-rs/tokio/blob/d33fdd86a3de75500fe554d6547cf5ad43e006bf/tokio/src/lib.rs#L458-L470), so it's possible that one of these conditions may not be met in your workspace.

**Comment by Darksonn** [comment]
> I then override the cargo to nightly

Using nightly is the wrong way to use Tokio unstable features. Instead, you must pass the `--cfg tokio_unstable` flag using the instructions from [the documentation][1].

[1]: https://docs.rs/tokio/latest/tokio/#unstable-features

**Comment by maxwellflitton** [comment]
@mox692 thanks for the quick response. I think there is something going on with my `config` file. Thanks @Darksonn for the link to the docs because I have now just exported the env variable and it's now compiling.

I'm just going to try my luck here but I 100% understand that it's not a Tokio issue, just checking if you have the answer off the top of your head but again, don't expect any extra effort to find a solution as this is really for wasmtime. I get a bad file descriptor error with the following code:

```rust
#[tokio::main(flavor="current_thread")]
async fn main() {
    use std::os::wasi::io::FromRawFd;
    // StDTcpListener is std::net::TcpListener as StDTcpListener
    let std_listener = unsafe { StDTcpListener::from_raw_fd(3) };
    std_listener.set_nonblocking(true).unwrap();
    // TcpListener is Tokio TcpListener
    let listener = TcpListener::from_std(std_listener).unwrap();
    println!("Server listening on port 8080");
}
``` 
But when I run the following command:

```
sudo wasmtime run ./wasi-server.wasm -W tcp-listen=127.0.0.1:8080
```
It breaks at the `std_listener.set_nonblocking(true).unwrap()` line with bad file descriptor.

**Comment by Darksonn** [comment]
It sounds like 3 is the wrong number?

I'm going to close this issue. For further help, please open [a discussion](https://github.com/tokio-rs/tokio/discussions) instead.
