### ISSUE TITLE
Ability to split a JoinSet into spawn and join halves

### ISSUE THREAD

**Issue by slonkazoid** [tokio-rs/tokio#6547]
**Is your feature request related to a problem? Please describe.**

JoinSet requires a mutable reference to spawn or join tasks. This means you cannot have 2 concurrent tasks appending tasks and joining them.  
This may be required for example when you have to spawn multiple millions of tasks so you use a semaphore and acquire a ticket before you spawn a new task.

**Describe the solution you'd like**

A simple `fn split(self) -> (SpawnerHalf, JoinerHalf)` method like this:

```rs
let (mut spawner, mut joiner) = JoinSet::new().split();

let task_a = tokio::task::spawn(async move {
    spawner.spawn(async { 42i32 });
});

while let Some(joined) = joiner.join_next().await {
  println!("the meaning of life is: {}", joined.unwrap());
}

task_a.await.unwrap();
```

**Describe alternatives you've considered**
- Mutex. Deadlocks with no obvious way to fix it.
- Making a JoinSet equivalent that takes a &self so it can be put in an Arc and cloned around.
- Passing my own waker into `join_next()`.

**Comment by Darksonn** [comment]
This is not a use-case that `JoinSet` supports. Some alternatives:

1. If you don't need return values, then consider the [`TaskTracker`][1].
2. If you need return values, then consider sending them using a [mpsc channel][2].

[1]: https://docs.rs/tokio-util/latest/tokio_util/task/task_tracker/struct.TaskTracker.html
[2]: https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.Receiver.html
