### ISSUE TITLE
CI failure on windows

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6567]
Our windows builds that test all crates have started failing with the following error:
```
    Finished `test` profile [unoptimized + debuginfo] target(s) in 3m 14s
error: creating test list failed

Caused by:
  for `tokio-macros`, command `'D:\a\tokio\tokio\target\debug\deps\tokio_macros-2a8683d94d36d244.exe' --list --format terse` exited with code 0xc0000135: The specified module could not be found. (os error 126)
--- stdout:

--- stderr:

---
```
The error is happening consistently and will need to be fixed asap, as it is preventing us from merging PRs.

Any ideas?

**Comment by ChrisDenton** [comment]
This is just a drive-by comment but it looks like that error first occurred 2 days ago: https://github.com/tokio-rs/tokio/actions/runs/9100468527

"The specified module could not be found" usually means a DLL isn't found. If someone runs it locally then they may be able to get more information. Perhaps a directory isn't in PATH that should be?

**Comment by ChrisDenton** [comment]
Assuming it's not a tokio change that caused this then one thing that stands out is a recent rustup change: https://github.com/rust-lang/rustup/pull/3703. It used to add the bin directory to PATH but no longer does so.

Someone could try setting `RUSTUP_WINDOWS_PATH_ADD_BIN=1` in the environment to check.

**Comment by Darksonn** [comment]
Thanks @ChrisDenton !
