### ISSUE TITLE
Examples and doctests should handle errors properly (no panics)

### ISSUE THREAD

**Issue by liranringel** [tokio-rs/tokio#657]
Looking in the examples and even the doctests, errors are not handled properly (a lot of uses of `unwrap` and `panic`).
Tokio should follow the best practices because it's a core component of the Rust ecosystem. It may mislead newbies that copy-paste those examples.
Today we have the `?` operator and can return errors from main, so it's not harder to do so. It is also recommended by the api-guidelines: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark

**Comment by SanchayanMaity** [comment]
I would like to contribute to this. To clarify, would use of "?" be recommended or match arms are more preferable or it is better to select depending on the particular context?

**Comment by liranringel** [comment]
@SanchayanMaity
Usually "?".
I already changed most of the examples, I'll probably push it this weekend.
You do the doctests, ok?

**Comment by SanchayanMaity** [comment]
@liranringel Ok.

**Comment by carllerche** [comment]
I'm 👍 with this.

**Comment by liranringel** [comment]
This issue has been resolved :)
