### ISSUE TITLE
tinydb example refers to using a `RefCell` but doesn't

### ISSUE THREAD

**Issue by andrewtj** [tokio-rs/tokio#658]
A comment in [tinydb.rs](https://github.com/tokio-rs/tokio/blob/ffd73a64e7ec497622b7f939e38017afe7124dc4/examples/tinydb.rs#L58-L62) refers to using a `RefCell` for interior mutability but a `Mutex` is used instead.

**Comment by carllerche** [comment]
The example was switched from RefCell to Mutex when it was transitioned to `tokio::run` (multi threaded).

Would you mind submitting a PR to update the comment?
