### ISSUE TITLE
Helper struct/wrapper for a stream of named pipe connections

### ISSUE THREAD

**Issue by Tacklebox** [tokio-rs/tokio#6591]
**Is your feature request related to a problem? Please describe.**
Should you want to create a GRPC (or probably other tower based) server using tokio named pipes, you need to create a stream of connections to serve.

**Describe the solution you'd like**
A wrapper struct like the one for [Unix Domain Sockets](https://docs.rs/tokio-stream/latest/tokio_stream/wrappers/struct.UnixListenerStream.html)

**Describe alternatives you've considered**
Implement it in the binaries that depend on tokio instead of providing it upstream. This is just a convenience since it's likely something that most consumers of the crate could utilize. 

**Additional context**

**Comment by Tacklebox** [comment]
If this is something that you think should be in tokio or if you want to explore the idea, let me know and I will put up a PR.

**Comment by Darksonn** [comment]
Is this feature request for windows or unix named pipes? They are quite different.

**Comment by Tacklebox** [comment]
Sorry, I mean for windows named named pipes.

**Comment by Darksonn** [comment]
Utilities for that *may* be a fit for the tokio-util crate, depending on the details. Are you able to provide details on the API you want?

**Comment by Darksonn** [comment]
Frankly, the easiest way here is that you just use the async-stream crate to create the stream, rather than add something more complex to Tokio.

**Comment by Tacklebox** [comment]
Thanks for the tip. This ended up being quite easy with async-stream, so i'll close this as I don't think there's any way to make it significantly easier from within tokio.

**Comment by xavo95** [comment]
> Thanks for the tip. This ended up being quite easy with async-stream, so i'll close this as I don't think there's any way to make it significantly easier from within tokio.

do you mind sharing the working code that you have?
