### ISSUE TITLE
Every 32 messages `is_empty()` on `Receiver` and `UnboundedReceiver` returns `false` even though len == 0

### ISSUE THREAD

**Issue by sjoubert49** [tokio-rs/tokio#6602]
**Version**
tokio v1.37.0

**Platform**
Windows 10, 64 bits

**Description**

This issue was first mentionned in a [stackoverflow question](https://stackoverflow.com/questions/78552088/rust-tokiosyncmpscchannel-is-empty-returning-false-when-len-returns-0)
Every 32 messages, after reading all messages from the `Receiver`, the call to `receiver.is_empty()` returns false, even though the reported `len` is 0.

The issue can easily be reproduced with 
```rust
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    let (sender, mut receiver) = mpsc::channel(33);

    for value in 1..257 {
        sender.send(value).await.unwrap();
        receiver.recv().await.unwrap();
        if !receiver.is_empty() {
            // This should not be called
            println!("{value}. len: {}", receiver.len());
        }
    }
}
```

There are some lines printed, even though `is_empty()` should always be true after receiving the last value.
```
32. len: 0
64. len: 0
96. len: 0
128. len: 0
160. len: 0
192. len: 0
224. len: 0
256. len: 0
```

NB: 32 is `BLOCK_CAP` so I'm guessing the issue is removing a value from the last slot in a `Block`, but I don't understand the code well enough so far to reach a better conclusion.

**Also tested**

The same issue is seen when:
- using an `unbounded_channel` instead of an `channel`
- with a capacity of 1
- sending a non zero-sized value (`value` from the loop)
- in a single thread synchronous code with the `blocking` versions of the calls to send and recv

**Comment by Darksonn** [comment]
Thank you for reporting this issue. I have file #6603 to fix this.
