### ISSUE TITLE
`arcmutex!` convenience macro

### ISSUE THREAD

**Issue by amab8901** [tokio-rs/tokio#6617]
**Is your feature request related to a problem? Please describe.**
Frustration lies in the verbosity (and hard-to-readness) of having to write:
``` rust
let state_of_devices = Arc::new(Mutex::new(STATE_OF_DEVICES.clone()));
``` 

**Describe the solution you'd like**
Convenience macro:
``` rust
let state_of_devices = arcmutex!(STATE_OF_DEVICES.clone());
``` 

**Describe alternatives you've considered**
* The verbose approach
* creating my own crate just for this feature

**Additional context**
I think it would make sense to use a convenience macro for `Arc<Mutex<T>>` because it's a common pattern.

**Comment by Darksonn** [comment]
You can define it yourself. It will not be added to Tokio.
