### ISSUE TITLE
Please `impl Default for watch::Sender<T> where T: Default`

### ISSUE THREAD

**Issue by joshtriplett** [tokio-rs/tokio#6623]
For types like `watch::Sender<Option<...>>`, it'd be convenient if `Sender` implemented `Default` if its contents did:

```rust
impl<T: Default> Default for Sender<T> {
    fn default() -> Self {
        Self::new(T::default())
    }
}
```

This would allow, for instance, using `.or_default()` in the `HashMap`/`DashMap` `Entry` API, rather than `.or_insert_with(|| watch::Sender::new(None))`.

**Comment by Darksonn** [comment]
That sounds like a good idea.
