### ISSUE TITLE
tokio build broken for aarch64-apple-visionos

### ISSUE THREAD

**Issue by coolbluewater** [tokio-rs/tokio#6628]
https://github.com/tokio-rs/tokio/issues/6627 was closed because of changes needed in mio.
Those changes have been [merged](https://github.com/tokio-rs/mio/pull/1795), so reopening.

See https://github.com/tokio-rs/tokio/issues/6627 for details.

**Comment by Darksonn** [comment]
Closing as duplicate of #6627.
