### ISSUE TITLE
Interval panics with Duration::MAX

### ISSUE THREAD

**Issue by nazar-pc** [tokio-rs/tokio#6634]
**Version**
1.37.0

**Platform**
Ubuntu x86-64 with 6.9.4 kernel

**Description**
Tokio timers do not handle overflow gracefully, I hit this multiple times already so decided to finally report it upstream.

I tried this code:

```rust
#[tokio::main]
async fn main() {
    tokio::time::interval(std::time::Duration::MAX).tick().await;
}
```

I expected to see this happen: effectively timer is idle indefinitely.

Instead, this happened:
```
thread 'main' panicked at library/std/src/time.rs:417:33:
overflow when adding duration to instant
```

`Instant + Duration` should be saturating to prevent this issue.

**Comment by wathenjiang** [comment]
Hi. I believe it has be fixed in `1.38.0`. Please see https://github.com/tokio-rs/tokio/releases/tag/tokio-1.38.0 and https://github.com/tokio-rs/tokio/pull/6487.

**Comment by nazar-pc** [comment]
Indeed, what a coincidence, thanks!

**Comment by wathenjiang** [comment]
But there is still a possibility that 1.38.0 may panic, it eventually fixed in https://github.com/tokio-rs/tokio/pull/6612.
