### ISSUE TITLE
Improvement for `#[tokio::main]`

### ISSUE THREAD

**Issue by Jedsek** [tokio-rs/tokio#6639]
`Importing main from other modules or crates.` has been stabilized in [rust 1.79](https://releases.rs/docs/1.79.0/).

Maybe we could improve it a little for `#[tokio::main]`?

This code was not allowed before:

```rust
#[tokio::main]
async fn hello_world() {
    println!("Hello, world!");
}
```

**note:**
This is `backwards compatible` because the previous code not allowed.

**how to solved:**
We could add prefix before any function and then `use prefix_{name} as main;`.

**Comment by taiki-e** [comment]
> This code was not allowed before:

No, arbitrary function names are supported.

**Comment by Jedsek** [comment]
> No, arbitrary function names are supported.

Um...really?

**Comment by Jedsek** [comment]
Close it because It deviates from the semantics I thought.
