### ISSUE TITLE
Failed to bind TCP port on Windows xp/windows server2003 system

### ISSUE THREAD

**Issue by zhuxiujia** [tokio-rs/tokio#6684]
Failed to bind TCP port on `Windows xp/windows server2003` system

Compile environment：
https://github.com/Chuyu-Team/YY-Thunks

Directly running the tokio compiled exe and calling the bound HTTP port will prompt 'called' Result:: unwrap() 'on an Err value: Os {code: 10022, kind: Invalid In'
t. Message: "An invalid parameter was provided. The reason is that the `mio` `WSAIontl` operation called by mio only supports Vista and above.
How to solve:
After forcibly modifying the source code of mio and commenting out all WSAIotl calls, it ran normally on the Windows Server 2003 system (which should be in the same kernel as XP).

side effect:
The first few requests were fine and responded normally, but after a period of time, an error message appeared
```log
unexpected error when polling the I/O driver: Os { code: 995, kind: TimedOut,
ssage: "I/O operation has been abandoned due to thread exit or application request." }
```
How can I modify it to support XP system?

**Comment by Darksonn** [comment]
This version of windows is not supported.

See also previous issue  #6461.

**Comment by zhuxiujia** [comment]
> This version of windows is not supported.
> 
> See also previous issue #6461.

Asynchronous operation cancellation mechanism
In most asynchronous I/O libraries, the cancellation of operations is usually handled through the design logic of the library itself, rather than relying on the API of the underlying operating system. For example, SMOL may track the completion and cancellation of asynchronous tasks at a higher level through state management, rather than canceling operations through kernel level I/O. Libraries typically provide their own task cancellation logic, without relying on specific system calls to cancel underlying I/O operations ？？？
﻿
If it you can tell me how to modified `mio`, I believe it will be easier to port to the old system

**Comment by Darksonn** [comment]
I cannot help you with supporting old systems.
