### ISSUE TITLE
How to set tower middleware dynamically

### ISSUE THREAD

**Issue by tgy3300** [tokio-rs/tokio#6687]
tower middleware injection, the following is normal
 ```
 use tower_http::trace::TraceLayer;
 
 let layer = tower::ServiceBuilder::new()
        .layer(TraceLayer::new_for_grpc())
        .into_inner();
```

In practice, however, my layer is set dynamically, so changing it to this will result in an error
    ```
    use tower_http::trace::TraceLayer;
    
    let mut layers = Vec::new();
    layers.push(TraceLayer::new_for_grpc());

    let mut layer = tower::ServiceBuilder::new();
    for item_layer in layers {
        layer = layer.layer(item_layer);
    }
    layer = layer.into_inner();
```

Error reported as follows：
expected struct `ServiceBuilder<Identity>`
found struct `ServiceBuilder<Stack<TraceLayer<SharedClassifier<GrpcErrorsAsFailures>>, Identity>>`

**Comment by tobz** [comment]
This issue should be opened on https://github.com/tower-rs/tower.
