### ISSUE TITLE
Add DatagramFile and StreamFile traits

### ISSUE THREAD

**Issue by Yanpas** [tokio-rs/tokio#67]
Currently there is no common denominator for UnixStream (tokio-uds) and TcpStream sockets e.g., I have to use macros to reduce code duplication

**Comment by carllerche** [comment]
This probably can be provided by some other crate initially and have the utility vetted that way.

**Comment by alexcrichton** [comment]
@Yanpas if you're looking to abstraction of TCP/Unix sockets, does `AsyncRead + AsyncWrite` work for you?

Or at you specifically looking for a trait for datagram sockets instead?

**Comment by Yanpas** [comment]
Sorry, I've mixed up things a little bit (forgot that listening socket is different entity in rust unlike in C). I was meaning TcpListener and UnixListener. I'm implementing syslog-like service which is designed to support both unix and tcp and missing the most important **incoming** method trait.

Anyway trait for StreamSockets is still needed because of incoming prototype:
`fn incoming(self) -> IoStream<(UnixStream, SocketAddr)>`

**Comment by carllerche** [comment]
Can you use the Stream trait to abstract the inbound connections?

**Comment by Yanpas** [comment]
You mean futures::Stream? Even with Stream+Sink trait it is not flexible enough. Here is the piece of code which implements connection logic:
```
macro_rules! handle_conn {
  ($listener:expr, $handle:expr) => {
    let handle2 = $handle.clone();
    let listen_stream = $listener.incoming().for_each(move |(cli, addr)|{
      debug!("Connection from {:?}", addr);
      let handle3 = handle2.clone();
      handle2.spawn_fn(move || {
        let requests = cli.framed(syslog::Syslog::new());
        handle3.spawn(requests.into_future()
          .map(move |(maybemsg, _framed)|{
            handle_new_message(...);
            ()
          })
          .map_err(|(e, _framed)| {
            info!("Failed to parse msg: {}", e);
            ()
        }));
        Ok(())
      });
      Ok(())
    }).map_err(|_|());
    $handle.spawn(listen_stream);
  };
}
```
I call this macro on TcpListener and UnixListener. I think tokio should allow to implement this as generic function.

**Comment by carllerche** [comment]
Can you sketch the trait that you’d like to add?

**Comment by Yanpas** [comment]
I see it like this
```
/*
I don't know how to describe it yet, but there a lot of stream like
objects both in windows and unix (pipes, files, fifos etc.). Windows have cool
asynchronous API (Overlapping IO) which allows asynchronous IO for both files
and sockets.
*/
trait StreamFile; 

trait StreamSocket : StreamFile {
  pub fn connect<E>(endpoint: E, handle: &Handle) -> Result<StreamSocket>;
  pub fn poll_read(&self) -> Async<()>;
  pub fn poll_write(&self) -> Async<()>;
  pub fn local_addr(&self) -> Result<ToSocketAddr>;
  pub fn shutdown(&self, how: Shutdown) -> Result<()>;
}

trait StreamListener {
  pub fn bind<E>(endpoint: E, handle: &Handle) -> Result<StreamListener>;
  pub fn local_addr(&self) -> Result<ToSocketAddr>;
  pub fn poll_read(&self) -> Async<()>;
  pub fn accept(&mut self) -> Result<(StreamSocket, ToSocketAddr)>;
  pub fn incoming(self) -> IoStream<(StreamSocket, ToSocketAddr)>;
}

trait DatagramSocket {
  pub fn bind<E>(endpoint: E, handle: &Handle) -> Result<StreamListener>;
  pub fn poll_read(&self) -> Async<()>;
  pub fn poll_write(&self) -> Async<()>;
  pub fn local_addr(&self) -> Result<ToSocketAddr>;
  pub fn recv(&self, buf: &mut [u8]) -> Result<(usize, ToSocketAddr)>;
  pub fn send<E>(&self, buf: &[u8], endpoint: E) -> Result<usize>;
  pub fn shutdown(&self, how: Shutdown) -> Result<()>;
  pub fn framed<C>(self, codec: C) -> DatagramFramed<C>;
}
```

Anyway it would be nice to see how it's done in Java and .NET e.g.

**Comment by carllerche** [comment]
Could you clarify the goal here. My assumption was that this was to abstract over unix domain sockets and TCP sockets. If so, how would the unix domain socket implement `local_addr`?

**Comment by carllerche** [comment]
Also, what are poll_read and poll_write here for? I don't think those two fns are needed when operating with `T: AsyncRead + AsyncWrite`.

**Comment by Yanpas** [comment]
> what are poll_read and poll_write here for

agree, they are extra

> this was to abstract over unix domain sockets and TCP sockets

yes, that's the point of this issue.

> how would the unix domain socket implement local_addr

We may return "unefined udress" or something, that's how it works now if for_each method.

**Comment by carllerche** [comment]
This seems like a pretty opinionated trait / impl. I personally would not expect a `local_addr` fn on a trait that abstracts over unix domain sockets and TCP.

In your original snippet, you showed a macro. Why don't you use traits yourself instead of the macro?

**Comment by Yanpas** [comment]
I do not insist on any concrete overall design, it's all up to tokio devs.

> Why don't you use traits yourself instead of the macro
I don't know, I don't like writing boilerplate code :smiley:

**Comment by carllerche** [comment]
While I can understand that you would sometime want to abstract over incoming TCP vs. Unix streams, I'm not sure if such a trait should live in tokio proper. I would recommend starting out with having it in a dedicated crate and exploring the API there. Once it stabilizes and is proven useful, we can revisit merging it in.

**Comment by carllerche** [comment]
I think that part of my hesitation is that `std` doesn't have an equivalent synchronous trait. If it did, then the argument or tokio to include one would be much stronger.

**Comment by alexcrichton** [comment]
Ok thanks for the clarifications @Yanpas! I agree though in that I don't think there's a great consensus as to what these traits and/or abstractions would look like, and that `std` is a good precedent to follow in this regard. Perhaps eventually when `std` picks up abstractions we can pull them into Tokio proper itself, but for now I think we'll stick to a more lean interface in Tokio without these traits. Experiementing with various options in ecosystems is of course always an option! (as mentioned here)

In the meantime though I'm going to close this.
