### ISSUE TITLE
1.39.0 breaks quinn: linked_list.rs panic

### ISSUE THREAD

**Issue by alexheretic** [tokio-rs/tokio#6714]
**Version** 1.39.0

**Platform**
`Linux alex-XPS-15-9520 6.5.0-44-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Description**
tokio 1.39.0 causes quinn to panic. Repro running quinn tests. See https://github.com/quinn-rs/quinn/issues/1936

```
thread 'tests::stream_id_flow_control' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.0/src/util/linked_list.rs:123:9:
assertion `left != right` failed
  left: Some(0x7405e001cca8)
 right: Some(0x7405e001cca8)
```

As suggested by @Darksonn reverting https://github.com/tokio-rs/tokio/pull/6584 fixes the issue.

**Comment by Darksonn** [comment]
Thank you. We will be reverting this change for 1.39.1.

Afterwards, we can try to determine what the bug is and re-land the change for 1.40.0.

**Comment by fasterthanlime** [comment]
Amazingly, I have spent days debugging this, believing that my [terrible, no-good shared object hacks](https://crates.io/crates/rubicon) were causing memory corruption.

...but I was running a patched tokio, forked from well after https://github.com/tokio-rs/tokio/pull/6584 was merged.

So chances are, I've been chasing a ghost all this time.

Ah well, at least there's [pretty colors](https://github.com/bearcove/rubicon/pull/10#issuecomment-2245948076) now.
