### ISSUE TITLE
Compile Time Check for Channel Size

### ISSUE THREAD

**Issue by Tahinli** [tokio-rs/tokio#6723]
**Is your feature request related to a problem? Please describe.**
While creating broadcast channel if size is 0 or over usize::max/2, it will panic.  Mpsc channel also panics if size is equal to 0. In this situations developer might forget to read document about when it panics or basically, forget to handle it.

**Describe the solution you'd like**
Compile time checking for at least statically defined 0 size for mpsc, 0 size or over usize::max/2  for broadcast channel. It maybe hard to check variables in compile time that's why I'm asking about statically typed ones.

**Additional context**
As we all know Rust has verbose error handling and compile time checking. Since tokio is really important for Rust; if we're able to check this situations in compile time, it will help developers. 

Also code won't panic until it reaches the channel creation. This has a potential to make software unreliable. You know every situation couldn't be tested.

I would like to share code that does this but I don't have that kind of knowledge about compiling.

Thanks.

**Comment by Darksonn** [comment]
Unfortunately, I don't think this is possible.

**Comment by sfackler** [comment]
I think it'd need to be done as a new lint in Clippy. There is some precedent for lints for third party types (regex has some maybe?), but I don't know if this would qualify for one.

**Comment by Darksonn** [comment]
That could be an option. But I will close this, as it is not actionable for Tokio.
