### ISSUE TITLE
Is there a reason the tokio-async-await dependency is "target.'cfg(unix)'"?

### ISSUE THREAD

**Issue by EyeOfPython** [tokio-rs/tokio#673]
I tried to compile the tokio-async-await examples under Windows 64-bit, which resulted in "can't find crate for `tokio_async_await`". When moving the `tokio-async-await` dependency in tokio's Cargo.toml to the `[dependencies]` section, it compiles fine and the examples seem to work fine.

Can we enable tokio-async-await for non-cfg(unix) platforms?

I'm running tokio-0.1.10, latest commit is 1e45237a28aad44ab7fc18726ba969ba5277be85 "Bump tokio-uds to v0.2.2"

**Comment by carllerche** [comment]
Thanks for the report. I pushed out a (hopefully) fix to crates.io.
