### ISSUE TITLE
join_set There is a bug that was not found in 1.39.1, only discovered in 1.39.2

### ISSUE THREAD

**Issue by DemoTest6** [tokio-rs/tokio#6734]
`    while let Some(res) = actor_join.join_next().await {
        if let Ok(Ok(package)) = res {
            render.extend(package.0);
        }
    }`
    
   actor_join.join_next().await , It's an empty function inside, but the time returned by await ranges from a few milliseconds to several hundred milliseconds after a period of time. I think there was an unknown error in it

**Comment by Darksonn** [comment]
The difference between 1.39.1 and 1.39.2 is very small and definitely does not touch `join_next`.

**Comment by Darksonn** [comment]
Closing due to lack of information.
