### ISSUE TITLE
proposal: tokio_fs::file::File allowing access to the underlying std::fs::File

### ISSUE THREAD

**Issue by kinnison** [tokio-rs/tokio#674]
## Version

This is specifically related to tokio-fs for which I'm using `0.1.3` currently.

## Platform

`Linux equanimity 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`

## Description

I am writing some code using the `tokio_fs::file::File` abstraction to allow for asynchronous file IO.  Unfortunately at times I need access to the underlying `std::fs::File` so that I can perform some fairly platform-specific operations on the underlying file descriptor.  From the outside, it doesn't seem that I can get access to the underlying file descriptor without using the `.poll_try_clone()` to get a new `tokio_fs::file::File` which I then have to `.into_std()` to destructure, so I can then use `AsRawFD` to get hold of the FD, do my work, and then I end up dropping and thus closing the `std::fs::File`.  Since this isn't done repeatedly on any given file handle, there's no gain to be had in caching a cloned handle just for this.

It'd be super if, instead, I could either borrow the File out from underneath, or else re-wrap the result of `.into_std()` after I'm done with it.

I was imagining something along the lines of (entirely untested):

```rust
    pub fn poll_with_std<F, T>(&mut self, f: F) -> Poll<T, io::Error> 
        where F: FnOnce(&mut std::fs::File) -> io::Result<T>,
    {
        ::blocking_io(|| f(self.std()))
    }
```

Which would give me most of the flexibility I need.

Alternatively I guess making `tokio_fs::file::File::std()` public would also do the trick, though that might be less in the futuresy style, I'm not sure.

I hope this is of interest to you all.  Thank you all so much for tokio so far.

D.

**Comment by carllerche** [comment]
Well, `tokio_fs::file::File` should implement `AsRawFD`... would that solve your issue?

I would like to expose a more generalized blocking API (related: #629).

**Comment by carllerche** [comment]
I'm not against exposing the inner `std::File`, but I would like to hold off until after #386. Resolving that issue may end up being incompatible with exposing the `std::File`.

**Comment by carllerche** [comment]
Ref: #1045

**Comment by carllerche** [comment]
Should be handled w/ #674.
