### ISSUE TITLE
!Send Future fails Miri check

### ISSUE THREAD

**Issue by coder137** [tokio-rs/tokio#6750]
**Version**
1.38.1 and 1.39.2

**Platform**
Ubuntu, Windows and Mac
https://github.com/coder137/ticked-async-executor/actions/runs/10259175195

**Description**
Creating `TickedAsyncExecutor` to advance local async tasks only when the executor is ticked.
Repo reference: https://github.com/coder137/ticked-async-executor

The tokio test(s) fail only when future provided is !Send and `join!` macro is used.

**Replication**

Passing test when Send future is used: 

Branch: https://github.com/coder137/ticked-async-executor/tree/tokio_test
Test: https://github.com/coder137/ticked-async-executor/blob/tokio_test/tests/tokio_tests.rs
CI: https://github.com/coder137/ticked-async-executor/actions/runs/10259106870

Failing test when !Send future is used:

Branch: https://github.com/coder137/ticked-async-executor/blob/tokio_test_spawn_local
Test: https://github.com/coder137/ticked-async-executor/blob/tokio_test_spawn_local/tests/tokio_tests.rs
CI: https://github.com/coder137/ticked-async-executor/actions/runs/10259175195

Failing info/logs
```
= help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```
[0_build (ubuntu-latest).txt](https://github.com/user-attachments/files/16504510/0_build.ubuntu-latest.txt)

**Comment by Darksonn** [comment]
Is this solved by #6744?

**Comment by coder137** [comment]
Upgrades the tokio rev tag to use #6744

Test Patch: https://github.com/coder137/ticked-async-executor/pull/8/commits/6cc5e9da6c6898b59b1f5dd89723077763e78349#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542
CI/CD: https://github.com/coder137/ticked-async-executor/actions/runs/10274884563

**Comment by Darksonn** [comment]
Like what #6744 did, I recommend filing an issue with miri.
