### ISSUE TITLE
Please eliminating the allocations introduced by v1.38.1

### ISSUE THREAD

**Issue by viciousstar** [tokio-rs/tokio#6757]
**Is your feature request related to a problem? Please describe.**
Tokio version 1.38.1 introducing excessive [memory allocations ](https://github.com/tokio-rs/tokio/pull/6683#discussion_r1677175494). 
In version 1.38, our memory allocation QPS was at 1k/s, but after upgrading to 1.38.1, it became 3k/s. Currently, we are not sure if this has any impact on the overall performance of our application. our application is a proxy of redis, the complexity of memory allocation QPS may increase to `n` from 1.

**Describe the solution you'd like**
eliminating the allocations introduced from v1.38.1

**Describe alternatives you've considered**
No

**Additional context**

**Comment by Darksonn** [comment]
One option could be to wrap the wheels in an `RwLock`. That way, we can lock the write lock and access the mutex contents with `Mutex::get_mut`. All other accesses could use a read lock to avoid blocking each other.

**Comment by viciousstar** [comment]
If I do not want to use v1.38.1, which version should we use? v1.37?

**Comment by Darksonn** [comment]
You can use 1.37.0.

**Comment by viciousstar** [comment]
In the scenario of a total request of 30,000 requests per second, the number of memory allocations per second has risen from 6k to 18k.

**Comment by tglane** [comment]
I'd like to work on this. Will open a PR soon.

**Comment by hawkw** [comment]
The approach described by @Darksonn in https://github.com/tokio-rs/tokio/issues/6757#issuecomment-2273057393 seems like the right solution to me, at least for now.
