### ISSUE TITLE
Render more comprehensible documentation for join/try_join macros

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tokio#6775]
This issue is to make the same change as #6468 to the `join!` and `try_join!` macros.

**Comment by Rustin170506** [comment]
I will try to improve it.

**Comment by Darksonn** [comment]
This was fixed for the `join!` macro, but still needs to be changed for `try_join!`.

**Comment by Rustin170506** [comment]
Yes. I will send another PR for it.
