### ISSUE TITLE
`time::advance` does nothing when entered into a new runtime.

### ISSUE THREAD

**Issue by drwhut** [tokio-rs/tokio#6794]
**Version**
```
├── tokio v1.36.0
│   └── tokio-macros v2.2.0 (proc-macro)
├── tokio-native-tls v0.3.1
│   └── tokio v1.36.0 (*)
├── tokio-tungstenite v0.21.0
│   ├── tokio v1.36.0 (*)
│   ├── tokio-native-tls v0.3.1 (*)
├── tokio-util v0.7.10
│   └── tokio v1.36.0 (*)
```

**Platform**
Linux 6.8.0-40-generic 40-Ubuntu x86_64 GNU/Linux

**Description**
I'm trying to write a test for one of the modules in my program. It tests a task which checks for changes to a given file every 30 seconds, and makes sure that it updates a `sync::watch` channel if the file was changed.

This is the general layout of the code for the task which is being tested:
```rust
    let mut interval = interval(CONFIG_UPDATE_INTERVAL);

    loop {
        tokio::select! {
            _ = interval.tick() => {
                // -- file checking, watch update happens here. --
            },
            _ = shutdown_signal.recv() => {
                break;
            }
        }
    }
```

And this is what I have so far for the test:
```rust
    #[tokio::test(start_paused = false)]
    async fn update_task_default_file() {
        // -- test setup: creating channels, etc. --

        let runtime = tokio::runtime::Builder::new_current_thread()
                .enable_time()
                .start_paused(true)
                .build()
                .unwrap();
        
        let handle = runtime.spawn(update_config_task("__default__.toml", watch_send, shutdown_receive));
        
        {
            let _guard = runtime.enter();
            tokio::time::advance(CONFIG_UPDATE_INTERVAL * 2).await;
        }
        assert_eq!(*watch_receive.borrow(), VariableConfig::default());
        assert!(!watch_receive.has_changed().unwrap());

        // -- changing the file here. --

        // Now the config file has updated, the task's next pass should detect
        // the change and send an update to the watch channel.
        {
            let _guard = runtime.enter();
            tokio::time::advance(CONFIG_UPDATE_INTERVAL * 2).await;
        }
        assert_eq!(*watch_receive.borrow(), test_config); // <- point at which test fails!!
        assert!(watch_receive.has_changed().unwrap());
        watch_receive.mark_changed();

        shutdown_send.send(()).expect("failed to send shutdown signal");
        handle.await.expect("task was aborted");

        // -- cleanup --
    }
```

Based on my understanding of the documentation, the `tokio::time::advance` calls should advance the internal timer of `runtime`. Without using `runtime.enter()` beforehand, the test panics saying that the time has not been paused (which I've explicitly set in the `tokio::test` line), so I think `advance` is being called in the runtime.

However, my test fails as the updated value does not come through the watch channel, which leads me to believe that the task is not running, or that the timer is not being advanced.

Without using the separate runtime, the test randomly failed and succeeded. With the new runtime, the test always fails. One thing I did notice is that if I send the shutdown signal to the task early, then the test always succeeds, however I would like to avoid this workaround as I would only be able to test one change to the file.

Is this a bug with `time::advance`, or is this the intended behaviour when using it on a separate runtime? If it is advancing the time of the runtime, but the runtime is not being scheduled to run, is there a way to make it run when the time is advanced?

Thank you in advance!

**Comment by Darksonn** [comment]
It looks like you are simultaneously using `#[tokio::test]` and manually creating a new runtime. The `#[tokio::test]` macro already creates a runtime for you, so you probably ended up with two runtimes and confused them with each other.

Also, it's often easier to use `tokio::time::sleep` instead of `advance`. The runtime will auto-advance to the next pending timer if the runtime would otherwise be idle.

**Comment by drwhut** [comment]
If I replace `advance` with `sleep` in the test, now the test hangs indefinitely... I'm guessing that's because while I'm sending the shutdown signal, the task isn't running somehow, and so it never gets to react to the signal?

I did manage to get a working version of the test, although with a couple of caveats, by forcing the task to run using the `watch::Receiver::changed()` function:

```rust
#[tokio::test(start_paused = true)]
    async fn update_task_default_file() {
        // -- setup --
        let handle = tokio::spawn(update_config_task("__default__.toml",
                watch_send, shutdown_receive));

        assert_eq!(*watch_receive.borrow(), VariableConfig::default());
        assert!(!watch_receive.has_changed().unwrap());

        // -- changing the file --
        tokio::time::advance(CONFIG_UPDATE_INTERVAL).await;

        watch_receive.changed().await.unwrap(); // <-- forces task to run! \o/
        assert_eq!(*watch_receive.borrow(), test_config);

        shutdown_send.send(()).expect("failed to send shutdown signal");
        handle.await.expect("task was aborted");

        // -- cleanup --
    }
```

Although, this only works when I expect the watch channel to have a value in - if I wanted to test that the watch channel *doesn't* have a changed value for 100% certain, then I would need to do the same thing, but with timeouts I think? I'm not sure how clean that would be.

So I've managed to find a solution for my use case, however my original issue still stands, in that `time::advance` does nothing when entered into another runtime. This very well could be the intended behaviour, and that I'm misunderstanding something fundamental about the runtimes and how they work, but I wanted to make sure.

**Comment by drwhut** [comment]
I can confirm that the task was indeed not running - in fact, once I forced it to run using `block_on`, I started getting a panic saying that you cannot make a runtime within another runtime.

So I decided to make a small test example, as shown:
```rust
    async fn some_task(before: tokio::time::Instant) {
        println!("{:?}", tokio::time::Instant::now() - before);
    }

    #[test]
    fn advance_test() {
        let runtime = tokio::runtime::Builder::new_current_thread()
                .enable_time()
                .start_paused(true)
                .build()
                .unwrap();
        
        let _guard = runtime.enter();
        runtime.block_on(async {
            let before = tokio::time::Instant::now();
            tokio::time::advance(Duration::from_secs(5)).await;
            some_task(before).await;
        });
    }
```

Without the `advance` line, it prints `0ns`, but with it it prints `5s`, so it does indeed work - although, I could not use `advance` outside of the `async` block, since it is an `async` function. But the function does work as intended when using it on a custom runtime, so I'm happy to close the issue. Turns out I still need to wrap my head around asynchronous runtimes a bit more :stuck_out_tongue:
