### ISSUE TITLE
Future returned to Handle.spawn()/.execute() is never run

### ISSUE THREAD

**Issue by mqudsi** [tokio-rs/tokio#68]
I'm experimenting with remote reactors and task spawning, but I'm having trouble with a particular scenario where the `Future` passed to `.spawn()`/`.execute()` is not resolved.

This is the self-contained example: https://git.neosmart.net/mqudsi/futuretest/src/execute-no-future-unwrap/src/main.rs

I create a reactor and then call a function that queues a task with the event pump:

```rust
    let f = future::result::<(), ()>(Ok(())).map(|_| {
        println!("Starting first worker");
        match RUNNER.lock() {
            Ok(guard) => {
                match *guard {
                    Some(ref x) => {
                        println!("Starting runner");
                        x.run()
                    }
                    None => eprintln!("RUNNER not initialized!"),
                }
            }
            Err(_) => eprintln!("Could not lock mutex!"),
        }
    });
```

and the code that does the queuing:

```rust
impl TaskRunner {
    pub fn run(&self) {
        self.remote_handle
            .spawn({
                println!("Running!");
                future::ok(())
                .map(|()| println!("Running followup!"))
            })
            .unwrap()
    }
}
```

The closure passed to `.spawn()` is evaluated ("Running!" is printed) but the future returned to `.spawn()` from the closure is never executed ("Running followup!" does not appear).

Am I missing something? `.spawn()` and `.execute()` take a future but return void, so whose job is it to run the future if not theirs?

**Comment by alexcrichton** [comment]
Thanks for the report! Right now a reactor only executes code if `core.run` is called on a thread. Is there a thread that's turning th ereactor?

**Comment by mqudsi** [comment]
Yup, right here: https://git.neosmart.net/mqudsi/futuretest/src/execute-no-future-unwrap/src/main.rs#L41

I was presuming that without `core.run()` none of the code would be executed (neither "Running!" nor "Running followup!" printed).

**Comment by alexcrichton** [comment]
The problem is you're passing in a future that's immediately finished, so it has no reason to wait on and execute the spawned future.

**Comment by mqudsi** [comment]
After reading through the source, I have a better understanding of the underlying architecture and get the issue now. Thank you.

**Comment by snawaz** [comment]
> The closure passed to .spawn() is evaluated ("Running!" is printed) but the future returned to .spawn() from the closure is never executed ("Running followup!" does not appear).

Well, the part which prints `"Running"` isn't part of the closure. Actually, there is no *closure* at all. 

This code:

     self.remote_handle
            .spawn({
                println!("Running!");
                future::ok(())
                .map(|()| println!("Running followup!"))
            })
            .unwrap()

is equivalent to this:

    println!("Running!");
    self.remote_handle
            .spawn(
                 future::ok(())
                .map(|()| println!("Running followup!"))
             )
            .unwrap() 

So you see, there is no closure, and the part `println!("Running!");` is just a part of the block starting with `{` in your code. This block produces the *future* which is being passed to `.spawn()`. Please let me know if my understanding isn't correct. :-)

**Comment by snawaz** [comment]
> The problem is you're passing in a future that's immediately finished, so it has no reason to wait on and execute the spawned future.

@alexcrichton.. can you please elaborate on that? Why would it not execute the spawned future which is just a part of the plan and is created from within the `map()` on the initial future (the completed one)? The spawned future is still submitted to the Runtime through the handle, right? and if so, then it should be executed as well?
