### ISSUE TITLE
Get length of channel on mpsc::Sender

### ISSUE THREAD

**Issue by barafael** [tokio-rs/tokio#6817]
Since a while, it is already possible to get the number of elements in a channel on an mpsc::Receiver. For statistics and metrics, it can be useful to get that number, but usually, only an mpsc::Sender is available there. total_capacity - number_of_free_slots works, but only for bounded channels.

**Comment by Darksonn** [comment]
I agree that this would be nice, but it may be difficult with the current implementation. Right now, only the receiver has access to information about which messages have already been received.
