### ISSUE TITLE
AsyncFd didn't close file descriptor on Drop

### ISSUE THREAD

**Issue by oing9179** [tokio-rs/tokio#6820]
## Environment

**Tokio version**: `1.40.0`
**Platform**: `Linux (host name) 6.10.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000 x86_64 GNU/Linux`

## Description

`AsyncFd` didn't close the fd on drop but the [documentation](https://docs.rs/tokio/1.40.0/tokio/io/unix/struct.AsyncFd.html) clearly says:

> ... this object will handle closing the file descriptor when it is dropped, ...

Here's the code to replicate the bug:

```rust
#[tokio::main]
async fn main() -> () {
    test_async_fd().await;
}

async fn test_async_fd() -> () {
    use libc::{socket, AF_INET6, IPPROTO_ICMPV6, SOCK_NONBLOCK, SOCK_RAW};
    use std::time::Duration;
    use tokio::{io::unix::AsyncFd, time::sleep};

    let sock_fd = unsafe { socket(AF_INET6, SOCK_RAW | SOCK_NONBLOCK, IPPROTO_ICMPV6) };
    if sock_fd == -1 { return; }
    let async_fd = AsyncFd::new(sock_fd).unwrap();
    drop(async_fd);
    sleep(Duration::from_secs(60)).await;
}
```

Compile the code then run it with `sudo` then run the command `sudo ss -nwp` before the `sleep()` elapsed, a file descriptor should be listed in the output.

**Comment by Darksonn** [comment]
The sentence in question says:

> The `AsyncFd` takes ownership of an arbitrary object to represent the IO object. It is intended that this object will handle closing the file descriptor when it is dropped

You are creating an `AsyncFd<RawFd>`, so in this case "this object" refers to `RawFd`. Since the `RawFd` type has no destructor, the file descriptors is not closed.

**Comment by oing9179** [comment]
So I have to:

```rust
pub struct MyFd(i32);
impl AsRawFd for MyFd { ... }
impl Drop for MyFd {
    fn drop(&mut self) {
        unsafe { libc::close(self.0) };
    }
}
```

That's kind of lame.

**Comment by Darksonn** [comment]
You can use [`OwnedFd`](https://doc.rust-lang.org/stable/std/os/fd/struct.OwnedFd.html) from the standard library.
