### ISSUE TITLE
tokio::sync::Notify is ready all the time without calling notify_once

### ISSUE THREAD

**Issue by xoac** [tokio-rs/tokio#6827]
**Version**
```
[package]
name = "notified-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "=1.40.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
```

**Platform**
> Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1715181801~22.04~aba43ee SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux

**Rust version tested:** 
> rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**Description**

In code there is comment line that you can change to see 2 different behaviors. For me sounds like a bug if this is intended behavior this should be explained in documentation.   

<details>
<summary>I tried this code (spoiler):</summary>

```rs
use std::sync::Arc;

use tokio::sync::{futures::Notified, Notify};

pub struct NotifyWrapper {
    pub notify: Notify,
}

impl NotifyWrapper {
    pub async fn notified(&self) -> Notified<'_> {
        self.notify.notified()
    }
}

#[tokio::main]
async fn main() {
    let v = Arc::new(NotifyWrapper {
        notify: Notify::new(),
    });

    let n = v.clone();

    tokio::spawn(async move {
        for i in 0..10 {
            // Try line below to make it working as expected
            // let _notified = n.notify.notified().await;
            let _notified = n.notified().await;
            println!("notification = {:01}", i + 1);
        }
    });

    tokio::time::sleep(tokio::time::Duration::from_secs(3)).await;
    println!("before notify_one");
    v.notify.notify_one();
    println!("after notify_one");
    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
}
```
</details>

Same code in playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bf7270fd8d1e84100d93ebe9230ba055

**I expected to see this happen:**

(to see 3 lines order can be different)
```
before notify_one
after notify_one
notification = 1
```

**Instead, this happened:**

```
notification = 1
notification = 2
notification = 3
notification = 4
notification = 5
notification = 6
notification = 7
notification = 8
notification = 9
notification = 10
before notify_one
after notify_one
```

**Comment by Darksonn** [comment]
I tried running your example, and got this:
```
before notify_one
after notify_one
notification = 1
```
Are you sure you shared the right example?

**Comment by xoac** [comment]
@Darksonn Thanks. I have update code and the link. I mixed "expected" with unexpected behavior. 

The diff between expected and unexpected is:
```rs
            let _notified = n.notify.notified().await;
```
and
```rs
            let _notified = n.notified().await;
```
