### ISSUE TITLE
AsyncRead/AsyncWrite for connected UdpSockets

### ISSUE THREAD

**Issue by shahn** [tokio-rs/tokio#6829]
**Is your feature request related to a problem? Please describe.**
I've often wanted to use `AsyncRead`/`AsyncWrite` with a connected `UdpSocket`, due to the convenience of using these traits (for example, to interface with `tokio_test::io::Mock` or to re-use code written for Tcp Message parsing which uses these traits). 

**Describe the solution you'd like**
Unfortunately, providing the traits seems impossible in the general case of unconnected sockets and `recv_from`/`send_to` - but for the case of a connected socket, it seems like it should be possible.

**Additional context**
A trivial implementation like this seems to work for me, but I am not sure if it has problems that make it a bad idea:

```
struct ConnectedUdpAsyncBridge(UdpSocket);

impl AsyncWrite for ConnectedUdpAsyncBridge {
    fn poll_write(self: Pin<&mut Self>, cx: &mut Context<'_>, buf: &[u8]) -> Poll<Result<usize, Error>> {
        self.0.poll_send(cx, buf)
    }

    fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Result<(), Error>> {
        Ok(()).into()
    }

    fn poll_shutdown(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Result<(), Error>> {
        Ok(()).into()
    }
}

impl AsyncRead for ConnectedUdpAsyncBridge {
    fn poll_read(self: Pin<&mut Self>, cx: &mut Context<'_>, buf: &mut ReadBuf<'_>) -> Poll<std::io::Result<()>> {
        self.0.poll_recv(cx, buf)
    }
}
```

**Comment by Darksonn** [comment]
Datagrams cannot implement the IO traits. The `AsyncWrite` trait requires that `write([0,1])` is the same as `write([0]); write([1])`, but that is not the case with this implementation as it would change where the udp packet boundaries are.

**Comment by shahn** [comment]
Ah I see, that is indeed violated - thanks! I guess I could get closer to what I'd want with a `ConnectedUdpFramed` that would impl `Sink<I>` rather than `Sink<(I, SocketAddr)>`, because I could stick that into a `SinkWriter`. Does that make any sense?

**Comment by shahn** [comment]
I guess my question is, if I were to use something like SinkWriter<StreamReader<CopyToBytes<Udp>>>, would that work? I can get the types to sync up at least, but the behaviour might still not be correct

**Comment by Darksonn** [comment]
The `StreamReader` utility will happily split up a large message into several smaller ones, so it's probably not what you want.

**Comment by shahn** [comment]
Again, thanks a lot indeed. That is unfortunate, but I guess perhaps I could try improving `tokio_test::stream_mock` to be more in line with the `AsyncWrite` testing capabilities of `tokio_test::io::Mock`. And I guess having a ConnectedUdpFramed would make sense for my usecase independently of having the IO traits implemented.
