### ISSUE TITLE
tokio-timer::wheel::Wheel<T>::set_elapsed panics

### ISSUE THREAD

**Issue by Chris-Ricketts** [tokio-rs/tokio#684]
## Version

├── tokio-timer v0.2.7 (*)
│   │   ├── tokio v0.1.11 (*)
│   │       ├── tokio-executor v0.1.5 (*)
│   │       ├── tokio-io v0.1.9 (*)
│   │       ├── tokio-reactor v0.1.6 (*)
│   │       ├── tokio-tcp v0.1.2 (*)
│   │       ├── tokio-timer v0.2.7 (*)
│   │       ├── tokio-udp v0.1.2 (*)

## Platform

Linux NanoPi-NEO-Core 4.14.52 SMP Thu Jun 28 17:46:52 CST 2018 armv7l armv7l armv7l GNU/Linux

## Description

After running an [actix](https://github.com/actix/actix) based system on an 32bit ARM board (Allwinner H3) for several hours I get the following panic:
`thread 'main' panicked at 'elapsed=67137025; when=67137024', /rust/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/wheel/mod.rs:224:9`

[Heres the full backtrace](https://pastebin.com/raw/TsJ9HbDa)

This same issue was referenced in this PR https://github.com/tokio-rs/tokio/pull/515

**Comment by carllerche** [comment]
This makes me highly suspect that there is an issue with `Instant::now()` returning non monotonic values. Perhaps you could implement a little rust program that runs in a loop and does something like:

```rust
let mut prev = Instant::now();

loop {
    for _ in 0..10 {
        let curr = Instant::now();
        assert!(curr >= prev);
        prev = curr;
    }
    thread::sleep(Duration::from_millis(1));
}
```

In the mean time, I will try to take steps to avoid the panic.

**Comment by Chris-Ricketts** [comment]
I've left the rust program above running on the board. It usually takes quite a while for the panic to occur, so I'll come back and check it after the weekend.

**Comment by Chris-Ricketts** [comment]
@carllerche You were right - tit panicked. I suppose it could be a hardware fault - I'll try it on a different board.

**Comment by carllerche** [comment]
@Chris-Ricketts well... I would file the issue on the rust-lang repo. The fact that it panicked violates the `Instant::now()` guarantees.

**Comment by Chris-Ricketts** [comment]
@carllerche I'll file an issue on rust-lang this week and reference it here.

**Comment by carllerche** [comment]
Thanks. I’m going to close the issue but I would be open to working around it if necessary, so feel free to open it again if needed.

**Comment by vipeller** [comment]
@chris-ricketts  were you able to figure out what caused the timer "click backward" on your board? We face the similar problem, maybe your findings would be useful for us.
