### ISSUE TITLE
Can we convert unix::SocketAddr to/from std::os::unix::net::SocketAddr?

### ISSUE THREAD

**Issue by nmathewson** [tokio-rs/tokio#6864]
The [arti](https://arti.torproject.org) project, for various reasons, needs to convert between `tokio::unix::SocketAddr` and `std::os::unix::net::SocketAddr`.

The simplest approach here would be to implement `From<.>` and `Into<.>` on `tokio::unix::SocketAddr`.  We'd be happy to write a a patch to do that, but we're wondering if there is some reason not to do so?

As it stands, we've had to make [our own conversion function](https://gitlab.torproject.org/tpo/core/arti/-/merge_requests/2437/diffs?commit_id=ea3137ff54f9984314f2516fff2ba235517b82de#d56573f8f558e3d52583d5e44ba5836c1a6b1915_111_124) which is a bit ugly, and won't work in the future if Tokio adds support for "abstract" unix SocketAddrs.

Do you have any suggestions here?  As noted, we'd be happy to write a patch if there's some approach that would be acceptable on Tokio's end.

**Comment by Darksonn** [comment]
This is a historical deficiency due to mio also having a separate SocketAddr type too. However, mio v1 removed its SocketAddr type, so we don't really need to have our own type either. We probably can't get rid of our type, but adding conversions seems fine.
