### ISSUE TITLE
tokio::io::WriteHalf does not shutdown() the inner writer on drop()

### ISSUE THREAD

**Issue by varqox** [tokio-rs/tokio#6878]
**Version**
tokio v1.40.0

**Platform**
Linux arch 6.11.0-arch1-1 SMP PREEMPT_DYNAMIC Sun, 15 Sep 2024 18:38:36 +0000 x86_64 GNU/Linux

**Description**

tokio::io::WriteHalf does not shutdown() the inner writer on drop().

I tried this code:
```rs
use tokio::io::AsyncReadExt;

#[tokio::main]
async fn main() {
    let (mut reader, writer) = tokio::io::simplex(42);
    drop(writer);
    let mut buf = Vec::new();
    reader.read(&mut buf).await.unwrap(); // Hangs here indefinitely
    println!("{:?}", &buf);
}
```

I expected to see this happen: read() should return immediately reporting empty read.

Instead, this happened: Deadlock.

**Comment by Darksonn** [comment]
This is unfortunate, but there's nothing we can do to change it now. Both to avoid breaking existing users of `WriteHalf`, but also because the `AsyncWrite` trait doesn't provide a synchronous wait to close an IO resource - there is only an asynchronous poll method, which we can't use from drop.
