### ISSUE TITLE
tokio_io::read isn't re-exported in tokio::io

### ISSUE THREAD

**Issue by daboross** [tokio-rs/tokio#688]
## Version

Mostly looking at docs of `tokio` version 0.1.11.

## Platform

x86_64-unknown-linux-gnu

## Description

`tokio_io::read` is a useful utility function, kind of essential for some TCP server loops. It is not found in `tokio::io` though. Every other similar function is re-exported in `tokio::io`, but `read` isn't?

See here: https://github.com/tokio-rs/tokio/blob/1879bc49ce3126af4b561bfe535cbec9f7ae5b90/src/io.rs#L64-L83

**Comment by tobz** [comment]
Woops! :)

Would you be willing to submit a PR?

**Comment by daboross** [comment]
Sure.
