### ISSUE TITLE
Need better histogram granularity

### ISSUE THREAD

**Issue by rcoh** [tokio-rs/tokio#6896]
**Is your feature request related to a problem? Please describe.**
Currently, there are two histogram options: 
- Linear (uses way to much memory to have range + granularity)
- Log (impossible to obtain good granularity because each bucket is twice as big as the previous bucket)

**Describe the solution you'd like**
Add a new histogram type that uses a bounded-error histogram like [H2 Histogram](https://iop.systems/blog/h2-histogram/) for a reasonable accuracy-space tradeoff.

**Additional context**
Currently working on a pre-PR [implementation](https://github.com/rcoh/tokio/pull/3), opening this issue to discuss.

**Comment by Darksonn** [comment]
Are you able to clarify? Did you mean to link to something different?

**Comment by rcoh** [comment]
Yeah, sorry meant to link to my CR. Not sure what happened.

**Comment by Darksonn** [comment]
I updated your PR so that it will auto-close this issue when merged.
