### ISSUE TITLE
Graceful shutdown mechanism

### ISSUE THREAD

**Issue by mqudsi** [tokio-rs/tokio#69]
I don't think (and please correct me if I'm wrong) there's currently a general approach to "shutting down" a reactor where it will cease to accept new jobs but continue to execute until all spawned jobs have been executed, even if the first requirement is dropped (i.e. so long as futures remain spawned against the reactor, new jobs can still be added).

I also don't think there's a mechanism by means of which a thread can be notified that a future it spawned against a reactor will never be run (i.e. the reactor has been destroyed with spawned jobs enqueued), so such a feature would at least mitigate that concern.

Is the current architecture of a tokio core/reactor amenable to such a feature, and would you be open to considering this feature request?

**Comment by alexcrichton** [comment]
Thanks for the report! This is tracked at https://github.com/tokio-rs/tokio-core/issues/33 for the current iteration of the tokio-core but this will be a non-issue for the current repository as-is (somewhat still in progress to designed in tokio-rs/tokio-rfcs#3) so I'm going to close.
