### ISSUE TITLE
Naming is inconsistent when referring to the "global queue" and "injection queue"

### ISSUE THREAD

**Issue by rcoh** [tokio-rs/tokio#6915]
**Version**
Tokio 1.40

**Description**
The [docs](https://docs.rs/tokio/latest/tokio/runtime/index.html#multi-threaded-runtime-behavior-at-the-time-of-writing) refer to a "global queue" but the [metrics](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html#method.injection_queue_depth) refer to an "injection queue."

These are actually the same thing and both names should be consistent.

In my opinion, "global" is a somewhat clearer name in this case (at least, it is less jargony) but I don't have a strong preference.

**Comment by Darksonn** [comment]
The name global queue is already used in [`global_queue_interval`](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.global_queue_interval) which is stable, so that's probably the one that wins.

**Comment by rcoh** [comment]
Fixed by #6918
