### ISSUE TITLE
Typo in tokio-tls crate description

### ISSUE THREAD

**Issue by atouchet** [tokio-rs/tokio#6922]
**Description**
I noticed in the description of tokio-tls on crates.io (https://crates.io/crates/tokio-tls) that it directs users to use tokio-native-tls instead but unfortunately there's a typo in the crate name (`tokio-naitve-tls`). I was wondering if that could be fixed?

**Comment by Darksonn** [comment]
We don't have the repositories used to publish those old crates anymore. I don't want to spend the time on figuring out how to do that. The typo can stay.

Thank you for reporting this, though.
