### ISSUE TITLE
No way to get the sender's address from `codec::Decoder`

### ISSUE THREAD

**Issue by kurnevsky** [tokio-rs/tokio#693]
## Version

0.1.11

## Platform

Any

## Subcrates

tokio-codec, tokio-io

## Description

At the moment there is no way to get the sender's address from `codec::Decoder` besides always returning `Ok` and adding `Unknown` variant to your packets enum. It might be useful to add this address to errors/logs to see who sent invalid UDP packet.

**Comment by tobz** [comment]
For a little context here: for `UdpFramed`, `Item` is`(<C as Decoder>::Item, SocketAddr)` while `Error` is `<C as Decoder>::Error`, so you can't figure out the source client if you get an error.

**Comment by carllerche** [comment]
I think fixing this requires a breaking change. As such, I flagged this for 0.2.

**Comment by carllerche** [comment]
Is this still an issue?

**Comment by kurnevsky** [comment]
I believe yes: https://github.com/tokio-rs/tokio/blob/adc5186ebd1290c2f144e153a87e147d257f8b0f/tokio-util/src/udp/frame.rs#L42

**Comment by carllerche** [comment]
Codec code has been moved to tokio-util. Anyone who wishes to make the change can do so and we can release a breaking change.

However, as this is fairly low priority and has not gotten much recent activity, I'm going to close the issue. Anyone should feel free to open a PR.
