### ISSUE TITLE
The required feature flag of `UdpSocket` is not shown like the other net components.

### ISSUE THREAD

**Issue by YuanYuYuan** [tokio-rs/tokio#6935]
**Version**
tokio: 1.41.0

**Description**
`UdpSocket` needs the `net` feature to be enabled but the docs.rs doesn't show this.

- `UdpSocket`
![image](https://github.com/user-attachments/assets/e396e566-d549-43df-93a5-18928b0f4426)

- `TcpSocket`
![image](https://github.com/user-attachments/assets/706cea32-1937-465a-a06b-d34a07d26924)

**Comment by Darksonn** [comment]
Thanks for reporting this!
