### ISSUE TITLE
fs::File.read_to_string(...) appends newline character

### ISSUE THREAD

**Issue by MatthiasvB** [tokio-rs/tokio#6943]
**Version**
List the versions of all `tokio` crates you are using. The easiest way to get
this information is using `cargo tree` subcommand:

`cargo tree | grep tokio`
1.41.0

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Linux nixos 6.6.32 #1-NixOS SMP PREEMPT_DYNAMIC Sat May 25 14:22:56 UTC 2024 x86_64 GNU/Linux

**Description**
Enter your issue details here.
One way to structure the description:

[short summary of the bug]
I'm reading a file using
```rust
let master_key_file = env::var("MEILI_MASTER_KEY_FILE").expect("MEILI_MASTER_KEY_FILE must be set");
let mut master_key = String::new();
File::open(master_key_file).await.unwrap().read_to_string(&mut master_key).await.unwrap();
```

Now, `master_key` has an extra newline at the end, which breaks downstream code

I expected to see this happen: `master_key` should contain _exactly_ the contents of the file

Instead, this happened: it contains an extra newline at the end

**Comment by Darksonn** [comment]
I suspect your file probably contains an extra newline character :)

As an aside, [`tokio::fs::read`](https://docs.rs/tokio/latest/tokio/fs/fn.read.html) is better suited for your purposes.

**Comment by MatthiasvB** [comment]
I did check for that :). It does not

**Comment by mox692** [comment]
I couldn't see such a behavior in this program: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0e7fc9932d5c459ccc7d52a07bab198d

**Comment by Darksonn** [comment]
Have you tried with `std::fs`?

There really is nowhere for Tokio to insert a spurious newline character in the code you shared. I still think your file has a newline character, and that you're doing something wrong when checking it. I'm going to close this. If you want this issue reopened, I'm going to need really really compelling evidence that your file really does not have a newline character at the end.

Be aware that text editors usually don't show the last newline character as an additional empty line. Please see [this SO question](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

**Comment by MatthiasvB** [comment]
You were right, I'm sorry. It's just surprisingly hard to get this right.  I did not expect neovim to do nasty things like inserting invisible newlines (it only shows line numbers where content is, and there is _no_ line number on the line after my content, but sure enough, there's a newline character at the end of the first line).

It gets worse, as it's even harder to test if that newline is there.

```shell
echo "newlinetest" > testnewline;

echo "/$(cat testnewline)/"
# -> /newlinetest/
```

The newline _is_ there in the example above, but `cat` seems to omit it. Tokio, rightly so, does not.

Best way I found so far to _not_ have it there is

```shell
echo -n "whatever you want" > "wherever_you_want"
```

or perhaps even better

```shell
printf '%s' "whatever you want" > "wherever you want"
```

as taken from [here](https://stackoverflow.com/a/38021361/8447743)
