### ISSUE TITLE
idea: Newtype for clock::now() result

### ISSUE THREAD

**Issue by vorner** [tokio-rs/tokio#695]
It is not entirely clear that the whole tokio stuff runs around `clock::now()` instead of `Instant::now()`. People therefore are likely to use `Instant::now()` to construct the parameters of `Delay` and other things.

It would make sense to encode this information in the type system so people can't do that by accident. Like `clock::now() -> TokioInstant` (that would be explicitly convertible with normal `Instant` and could be added with `Duration`) and `Delay` also taking that one.

**Comment by carllerche** [comment]
Thanks for filing this. My gut is that this is a good change. It would be a breaking change, so I am adding this to 0.2.

**Comment by carllerche** [comment]
Done on master :+1:
