### ISSUE TITLE
Task counter for Runtime

### ISSUE THREAD

**Issue by ghost** [tokio-rs/tokio#697]
## Version

```shell
├── tokio v0.1.11                                                               
│   ├── tokio-codec v0.1.1
│   │   └── tokio-io v0.1.9
│   ├── tokio-current-thread v0.1.3
│   │   └── tokio-executor v0.1.5
│   ├── tokio-executor v0.1.5 (*)
│   ├── tokio-fs v0.1.3
│   │   ├── tokio-io v0.1.9 (*)
│   │   └── tokio-threadpool v0.1.7
│   │       └── tokio-executor v0.1.5 (*)
│   │   └── tokio-io v0.1.9 (*)
│   ├── tokio-io v0.1.9 (*)
│   ├── tokio-reactor v0.1.6
│   │   ├── tokio-executor v0.1.5 (*)
│   │   └── tokio-io v0.1.9 (*)
│   ├── tokio-tcp v0.1.2
│   │   ├── tokio-io v0.1.9 (*)
│   │   └── tokio-reactor v0.1.6 (*)
│   ├── tokio-threadpool v0.1.7 (*)
│   ├── tokio-timer v0.2.7
│   │   └── tokio-executor v0.1.5 (*)
│   ├── tokio-udp v0.1.2
│   │   ├── tokio-codec v0.1.1 (*)
│   │   ├── tokio-io v0.1.9 (*)
│   │   └── tokio-reactor v0.1.6 (*)
│   └── tokio-uds v0.2.2
│       ├── tokio-io v0.1.9 (*)
│       └── tokio-reactor v0.1.6 (*)
├── tokio-tls v0.2.0
│   └── tokio-io v0.1.9 (*)
```

## Platform

Windows 10 64-bit.

## Description

May I ask if you could add some kind of task counter to `Runtime`? Sometimes it helps in debugging.

Thank you,

**Comment by stjepang** [comment]
@carllerche I'm not completely sure, but here are some thoughts.

While Rayon doesn't expose a task counter, there's a way to access other similar information about the current state of the thread pool. For example, there's a method named [`current_thread_has_pending_tasks`](https://docs.rs/rayon-core/1.4.1/rayon_core/struct.ThreadPool.html#method.current_thread_has_pending_tasks) and it is exposed as `ThreadPool::current_thread_has_pending_tasks()` and also as `rayon_core::current_thread_has_pending_tasks()`.

I suggest we expose the task counter in Tokio either as `Runtime::pending_tasks()` or `Runtime::executor().pending_tasks()`. We should probably also add it as `ThreadPool::pending_tasks()`.

**Comment by carllerche** [comment]
Also, if the goal is to have additional debugging visibility, perhaps tokio-trace will be the way to expose this data.

**Comment by carllerche** [comment]
Tracked as part of #1186.
