### ISSUE TITLE
Tokio fs do not support Direct I/O

### ISSUE THREAD

**Issue by waruto210** [tokio-rs/tokio#6973]
**Version**
`v1.41.1`

**Platform**
`Linux VM-ubuntu 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Description**
I ran the following code and found that the assertion for tokio fs failed. After examining the tokio fs [source code](https://github.com/tokio-rs/tokio/blob/3b677d1fde79dce4b93f0518b4333d20db0212ac/tokio/src/fs/file.rs#L740), I discovered that Tokio `File` contains its own buffer, and this buffer is not aligned, which causes direct I/O failed.

 I'm curious whether this is a bug or if tokio fs is intentionally designed to not support direct I/O.

```rust
use std::io::Write;
use std::{alloc::Layout, fs::OpenOptions as StdOpts};
use tokio::{fs::OpenOptions as TkOpts, io::AsyncWriteExt};

#[inline(always)]
pub fn aligned_buffer<const ALIGN: usize>(size: usize) -> Vec<u8> {
    let layout = Layout::from_size_align(size, ALIGN).unwrap();
    let ptr = unsafe { std::alloc::alloc(layout) };
    unsafe { Vec::from_raw_parts(ptr, size, size) }
}

#[tokio::main]
async fn main() {
    let buf = vec![0u8; 4096];

    let mut opts = StdOpts::new();
    opts.create(true).write(true).truncate(true);

    let tk_opts = TkOpts::from(opts.clone());
    let mut f1 = tk_opts.open("./hello1.txt").await.unwrap();
    f1.write_all(&buf).await.unwrap();
    f1.sync_all().await.unwrap();
    println!("asssert tokio fs");
    assert_eq!(f1.metadata().await.unwrap().len(), 4096);

    #[cfg(target_os = "linux")]
    {
        use std::os::unix::fs::OpenOptionsExt;
        opts.custom_flags(libc::O_DIRECT);
    }

    let buf = aligned_buffer::<512>(4096);

    let mut f2 = opts.open("./hello2.txt").unwrap();
    tokio::task::spawn_blocking(move || {
        f2.write_all(&buf).unwrap();
        f2.sync_all().unwrap();
        println!("asssert std direct io + spawn blcoking");
        assert_eq!(f2.metadata().unwrap().len(), 4096);
    })
    .await
    .unwrap();

    let buf = aligned_buffer::<512>(4096);
    let direct_tk_opts = TkOpts::from(opts);
    let mut f3 = direct_tk_opts.open("./hello3.txt").await.unwrap();
    f3.write_all(&buf).await.unwrap();
    f3.sync_all().await.unwrap();
    println!("asssert tokio fs direct io");
    assert_eq!(f3.metadata().await.unwrap().len(), 4096);
}
```

**Comment by Darksonn** [comment]
This is intended behavior. The `tokio::fs` module only supports normal reading/writing to ordinary files.

**Comment by waruto210** [comment]
> This is intended behavior. The `tokio::fs` module only supports normal reading/writing to ordinary files.

The `write` syscall return `-EINVAL` due to buffer unaligned, but tokio fs hides that error, I believe Tokio fs should return the error to let users know about it.

**Comment by Darksonn** [comment]
We do want to avoid hiding the error.
