### ISSUE TITLE
The tokeio asynchronous function must be executed with 'await'

### ISSUE THREAD

**Issue by zhangxize** [tokio-rs/tokio#6990]
The tokeio asynchronous function must be executed with 'await'. If it is not executed without 'await', it will never be executed. If it must be executed with 'await', what is the difference between it and a synchronous function? As shown in the following code, the println of the body of the asynchronous function hello-world always fails to execute

async fn hello_world(){
// thread::sleep(time::Duration::from_secs(2));
println!("Hello,world66666");

}
#[tokio::main]
async fn main() {
let future=hello_world();
// tokio::join!(future);
// thread::sleep(time::Duration::from_secs(6));
for i in 1..10000
{
println!("Hello, world!");
}
let mut buf=String::new();
io::stdin().read_line(& mut buf);
}

**Comment by nurmohammed840** [comment]
This tracker is for bugs and feature requests.

For questions, Please ask in Decussation or join our Tokio [Discord](https://discord.com/channels/500028886025895936/500336333500448798) server.

**Comment by Noah-Kennedy** [comment]
Closing as this conversation should be had in #6989.
