### ISSUE TITLE
Update crates.io ownership

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#70]
Please add me as an owner of the tokio-core crate.

**Comment by carllerche** [comment]
Also, a release should be pushed out: https://github.com/tokio-rs/tokio-core/commit/c45bbaa04ee2a9524976374c204b9568f991dceb

**Comment by alexcrichton** [comment]
Oops added! (thought I did that already...)

**Comment by alexcrichton** [comment]
Also, published!
