### ISSUE TITLE
Refine panic propagation with `tokio::run` and spawning tasks

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#700]
Currently, `tokio::run` and `tokio::spawn` execute the provided task fully detached from the caller. This means that panics do not get propagated to the caller.

Initially, this was done to minimize overhead, but I am no longer sure that this is the correct default. Not propagating panics by *default* means that code can fail w/o the caller realizing it.

This should be refined for 0.2.

Refs: #640, 626

**Comment by stjepang** [comment]
There was a similar issue in Crossbeam:

```rust
crossbeam::scope(|scope| {
    scope.spawn(|| panic!());
    scope.spawn(|| panic!());
});
```

This code used to simply ignore both panics. Note that the end of the scope implicitly joins spawned threads, so what should we do with those `thread::Result<()>` coming from `.join()`?

We decided to return a `thread::Result<R>` from `scope()`. If all threads have finished successfully, we return an `Ok(_)`. If one or more threads panicked, we collect those panics into a `Vec`, box it, coerce it into `Box<Any + Send>`, and finally return as the `Err(_)` case.

I suggest we do something similar in Tokio. Maybe return a `thread::Result<()>` from `tokio::run()`?

**Comment by liranringel** [comment]
I imagine `spawn` looks like:
```rust
tokio::spawn<T>(future: T) -> SpawnHandle<Result<T::Item, T::Error>, Box<Any + Send + 'static>>
where T: Future: Send + 'static,
           T::Item: Send,
           T::Error: Send,
{ ... }
```
where `SpawnHandle` is a `Future`. `SpawnHandle` is like the async equivalent to `std::thread::JoinHandle`.
It's similar to what implemented in #638, but also let you know if a panic has occurred.

**Comment by carllerche** [comment]
The primary issue with returning a spawn handle by default is that, doing so, might require adding overhead. The question is:

* Can it be done without adding overhead.
* If it cannot, should there be an API that does not provide a handle?

**Comment by stjepang** [comment]
Something to think about: Rayon's thread pool allows specifying a panic handler.
https://docs.rs/rayon/1.0.2/rayon/struct.ThreadPoolBuilder.html#method.panic_handler

Tasks spawned by `rayon::join` and `Scope::spawn` have a parent and implicitly get joined. Panics in those child tasks get propagated ("re-thrown") into the parent task. This is reminiscent of our `spawn_handle`.

Tasks without a parent (e.g. spawned by `rayon::spawn`) are handled by the panic handler. This is like our `tokio::run` and `tokio::spawn`.

**Comment by ry** [comment]
For us having panic print to stderr and not die is incorrect. It means that our tests can, potentially, pass even if an `unimplemented!()` is hit.

It's understandable that HTTP servers would want to return 500 pages with stack traces. Either a panic handler (as linked to above) or a feature configuration that would avoid the current behavior would be very useful.

**Comment by carllerche** [comment]
@stjepang this would happen via the communication channels between tasks (mpsc, oneshot). If the send handles are dropped w/o pushing a value, the receive handles are canceled (notifying the tasks).

**Comment by carllerche** [comment]
I don't think this issue is relevant anymore:

- Runtimes will allow configuring how panics are handled (by default, they will swallow, which is OK because...)
- `spawn!` will return a handle annotated with `must_use`. panics are propagaged via this (#1180).
- `tokio::run` is removed in favor of an attribute macro.

If I am wrong, please let me know and I can updated the appropriate issue or reopen this one.

Also, dup of #495?
