### ISSUE TITLE
Potential thread leak in ``rt_common`` tests

### ISSUE THREAD

**Issue by tiif** [tokio-rs/tokio#7010]
**Version**
tokio master branch ``dcae2b9e``

**Description**
When running with ``cargo miri test --features full --test rt_common``, Miri reported ``error: the main thread terminated without waiting for all remaining threads`` on the ``rt_common`` tests below: 
```
tokio::rt_common current_thread_scheduler::shutdown_timeout_0
tokio::rt_common current_thread_scheduler::shutdown_timeout
tokio::rt_common threaded_scheduler_1_thread::shutdown_timeout
tokio::rt_common threaded_scheduler_1_thread::shutdown_timeout_0
tokio::rt_common threaded_scheduler_4_threads::shutdown_timeout_0
tokio::rt_common threaded_scheduler_4_threads::shutdown_timeout
```

To reproduce, ``#![cfg(not(miri))]`` needs to be removed. 

(I am not sure if this is an intended effect, but I will just file it under C-bug just in case this is something that should be fixed.)

**Comment by Darksonn** [comment]
Plausibly we could make the background threads exit more quickly, but it's not possible to actually join them. The `shutdown_timeout` API explicitly does not join the threads when the timeout hits, after all.

**Comment by tiif** [comment]
This probably falls under https://github.com/rust-lang/miri/issues/1371. Since it is working as expected, I will just close this issue, thanks for answering!
