### ISSUE TITLE
[tokio-stream] needs dev-dependency so tests can run

### ISSUE THREAD

**Issue by werdahias** [tokio-rs/tokio#7019]
**Version**
Latest (0.1.16)

When updating tokio-stream to 0.1.16 in Debian I discovered that apparently tokio-stream has a missing dev-dependency on tokio-test. 
E.g. `tests/stream_collect.rs` has `use tokio_test::{...` . However, the release on crates.io has no dependency on tokio-test, causing the tests to fai. Adding a patch for a -dev-dependency on tokio-test makes all tests pass.

**Comment by werdahias** [comment]
I see that it's present in git, so I assume something in the release process went wrong here.

**Comment by Darksonn** [comment]
It's because tokio-stream did not specify a version for the tokio-test dependency. This has already been fixed by #6931.
