### ISSUE TITLE
Awaiting LocalSet spawn_local never runs and stalls the runtime

### ISSUE THREAD

**Issue by RedKinda** [tokio-rs/tokio#7022]
**Version**
`tokio v1.42.0`

**Platform**
Linux archlinux 6.6.63-1-lts

**Description**
`localset.spawn_local(async move {})` never runs if created in the future that is passed into `runtime.block_on()`. If the resulting local JoinHandle is awaited program also stalls forever.

Repro code here https://gist.github.com/RedKinda/547c3e39ae275bd46bab534795e6a1d3

I expected to see this happen: 
Above code to print `inside root future` as well as `inside local async task` and then exit

Instead, this happened:
Only `inside root future` was printed and program never exits

**Comment by Darksonn** [comment]
Tasks in a `LocalSet` only execute if the `LocalSet` is being executed by awaiting the `LocalSet` or with `run_until`. Your code doesn't run the `LocalSet`, so the tasks do not execute.
