### ISSUE TITLE
`CancellationToken` should support GC its children

### ISSUE THREAD

**Issue by tabokie** [tokio-rs/tokio#7026]
**Is your feature request related to a problem? Please describe.**

One single `CancellationToken` might be used to control plenty of short-living tasks. ~But `CancellationToken::child_token` only populates the registry never shrinks it.~

**Describe the solution you'd like**

Provide a public method that collects the internal garbage based on `Arc` reference count.

**Describe alternatives you've considered**

None that I can think of.

**Additional context**

**Comment by Darksonn** [comment]
Can you provide more details on the case that isn't working? When I implemented it, I was pretty careful to always shrink the data structures when child nodes are dropped.

**Comment by tabokie** [comment]
Oh, sorry for the false claim.. I didn't read the code to understand it already has internal GC.

The problem we met was a long running server hosting multiple instances of task trees (controlled by one single token). One of them is malfunctioning and restarting a lot. According to jemalloc profile, the allocation of `CancellationToken::children` is causing a slow memory leak. I'll try to get a repro within tokio code later.

**Comment by tabokie** [comment]
Ach, rechecking the heap graph, the leak turns out to be in our code (that points to the same `Vec::grow` node). Sorry for the noise.
