### ISSUE TITLE
Pattern matching with `else` doesn't work as expected in `tokio::select!`

### ISSUE THREAD

**Issue by dlon** [tokio-rs/tokio#7030]
**Version**
```
tokio v1.42.0
tokio-macros v2.4.0 (proc-macro)
```

**Platform**
Mac M2, macOS 15.1

**Description**

`tokio::select! {}` doesn't take the `else` branch when pattern matching is used.

Forgive me if this is a misunderstanding on my part, but here is an example:

```rust
use std::time::Duration;
use tokio::io;

#[tokio::main]
async fn main() {
    let fut_a = async {
        Err::<(), _>(io::Error::other("fail"))
    };
    let fut_b = async {
        tokio::time::sleep(Duration::from_secs(100)).await;
    };
    
    tokio::select! {
        () = fut_b => {}
        Ok(()) = fut_a => {
            println!("fut_a resolved");
        }
        else => println!("else: Hello!"),
    }

}

```

I expect this to print `else: Hello!`, but instead it takes 100 seconds to resolve and then takes the first branch.

**Comment by Darksonn** [comment]
The else branch runs when *all* branches are deactivated. In your example, the `fut_b` branch is still active, so the else branch cannot run.
