### ISSUE TITLE
Make `tokio::test` attribute compatible with `sealed_test` attribute

### ISSUE THREAD

**Issue by fozzbuzz** [tokio-rs/tokio#7045]
**Is your feature request related to a problem? Please describe.**
I use `sealed_test` crate for marking tests with `sealed_test` attribute to isolate environments. This does not function when combined with `tokio::test` attribute, which is desired for tests that need an isolated environment plus tokio time manipulation.    
Looking at generated code for a test marked with both `tokio::test` and `sealed_test` , it appears that `tokio::test` adds the `#[::core::prelude::v1::test]` attribute while `sealed_test` adds the `#[test]` attribute; those two attributes combined make the test run twice, which fails since the environment is supposed to be isolated and this affects socket binds due to "Address in use" error.

**Describe the solution you'd like**
`tokio::test` attribute is able to be used in combination with `sealed_test` crate's attribute.

**Describe alternatives you've considered**
No real solution I can think of; to work around, I create a tokio runtime manually and spawn/block-on async code when using `sealed_test` .

**Additional context**
N/A

**Comment by Darksonn** [comment]
You can use `#[tokio::main]` instead of `#[tokio::test]`.

**Comment by Darksonn** [comment]
I'm pretty sure that `start_paused` also works with `#[tokio::main]` as long as the runtime flavor is `current_thread`.

**Comment by fozzbuzz** [comment]
You're right, attempting to use `start_paused` without specifying `flavor = "current_thread"` results in compilation error indicating your advice. `#[tokio::main(start_paused = true, flavor = "current_thread")]` works. Thank you for your swift advice!
