### ISSUE TITLE
impl From<net::TcpStream> for TcpStream

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tokio#707]
Whenever `TryFrom` stabilizes (rust-lang/rust#33417) we probably want to add a convenience method for turning a `std::net::TcpStream` into a `TcpStream` using the current reactor (i.e., `Handle::default()`). The impl would basically just be:

```rust
impl TryFrom<net::TcpStream> for TcpStream {
    type Error = io::Error;
    pub fn from(stream: net::TcpStream) -> io::Result<TcpStream>
    {
        TcpStream::from_std(stream, &Handle::default())
    }
}
```

**Comment by carllerche** [comment]
It is stable now.
