### ISSUE TITLE
Why are stdin actually blocks and how to make it truly non-blocking?

### ISSUE THREAD

**Issue by katyo** [tokio-rs/tokio#709]
## Version

termion-tokio v0.1.0
└── tokio v0.1.11
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.9
    ├── tokio-current-thread v0.1.3
    │   └── tokio-executor v0.1.5
    ├── tokio-executor v0.1.5 (*)
    ├── tokio-fs v0.1.3
    │   ├── tokio-io v0.1.9 (*)
    │   └── tokio-threadpool v0.1.7
    │       └── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.9 (*)
    ├── tokio-io v0.1.9 (*)
    ├── tokio-reactor v0.1.6
    │   ├── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.9 (*)
    ├── tokio-tcp v0.1.2
    │   ├── tokio-io v0.1.9 (*)
    │   └── tokio-reactor v0.1.6 (*)
    ├── tokio-threadpool v0.1.7 (*)
    ├── tokio-timer v0.2.7
    │   └── tokio-executor v0.1.5 (*)
    ├── tokio-udp v0.1.2
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.9 (*)
    │   └── tokio-reactor v0.1.6 (*)
    └── tokio-uds v0.2.2
        ├── tokio-io v0.1.9 (*)
        └── tokio-reactor v0.1.6 (*)

## Platform

Linux debi 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

## Description

When I tried to use tokio stdin (i.e. using `FramedRead` with self-written `Decoder`) it unexpectedly blocks process until any input happens.

I working with this repository: https://github.com/katyo/termion-tokio/
To reproduce you can run example: `cargo run --example input`.

**Expected behavior:** Periodical ticks happens independently from user input.
**Actual behavior:** No periodical ticks until any user input happens.

**Comment by carllerche** [comment]
Switching stdin / stdout to non-blocking is a process global operation and could have unintended impact on other code.

You can always switch the FD to non-blocking mode yourself, but that also means you cannot reliably use things like `println!` anymore.

**Comment by carllerche** [comment]
I'm going to close this issue as the documentation problem is tracked in the doc-push repo (https://github.com/tokio-rs/doc-push/issues/85).
