### ISSUE TITLE
0.1.10 I think just broke GRPC 0.4 ... Connection timeut on simple connect to server

### ISSUE THREAD

**Issue by przygienda** [tokio-rs/tokio#719]

**Comment by przygienda** [comment]
I try to wean packages out of 0.1.12 but between httpbis/grpc e'thing ends up picking up this publish that blew stuff up here ...

**Comment by carllerche** [comment]
Thanks for the report. I yanked 0.1.12 until we figure out the problem.

**Comment by carllerche** [comment]
Do you have a repro?
