### ISSUE TITLE
How to shutdown the global reactor

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#72]
Original comment: https://github.com/tokio-rs/tokio/pull/57#issuecomment-350849968

> How to shutdown the global reactor? The only (remaining) reason that I think it should be shutdown is to avoid FD leaks (the epoll FD never getting closed) which would be raised by linting tools and would be pretty annoying if there was no way to avoid. There doesn't need to be a way to restart it once it is shutdown and I think it would be pretty trivial to have a fn Reactor::shutdown_default_global or something that signals global::HelperThread to terminate and blocks until it does so.

**Comment by alexcrichton** [comment]
Overall I think most methods/APIs are at least ready for the global reactor to be shut down in the sense that there's proper channels for all errors to be communicated, so we should be set on that front!

I think one trick aspect of this API is we'll want a way to coordinate shutdown as well in terms of a program which wants to do this probably also wants some form of a synchronization point at which it's sure the global reactor is shut down. (as opposed to just a "please shut down at your convenience" API that is)

**Comment by carllerche** [comment]
@alexcrichton unless you think otherwise, I think it would be relatively safe to punt this past 0.1.

`reactor::shutdown_globa()` would even work I think as a hard shutdown that is performed before the process exits.

> we'll want a way to coordinate shutdown 

Do you mean beyond just an explicit shutdown fn?

**Comment by alexcrichton** [comment]
I'm fine punting this yeah, and for coordination I'm thinking that you've got two states: you've requested a shutdown and the shutdown has completed (aka the thread is joined and dead). We'll probably want a way to get notified of the latter I think, although that's all of course backwards compatible.

**Comment by carllerche** [comment]
Given the development of `Runtime`, I don't think this is much of an issue anymore.
