### ISSUE TITLE
how get IP ?

### ISSUE THREAD

**Issue by ami44** [tokio-rs/tokio#723]
it may be a stupid question but I can't figure out how to get the ip from http clients! 

Where can I find an example that would display "Your Ip" (like https://whatismyipaddress.com) 

that could be included in https://github.com/tokio-rs/tokio/blob/master/examples/tinyhttp.rs.

Thank you

ami44

**Comment by Patryk27** [comment]
After you get your hands on `TcpStream`, you can use its `peer_addr()` method:
```rust
println!("{:?}", stream.peer_addr());
```

**Comment by ami44** [comment]
Thank you
