### ISSUE TITLE
DTLS support

### ISSUE THREAD

**Issue by henriktorget** [tokio-rs/tokio#725]
Is there any plans on implementing DTLS support for tokio-rs? 
I am looking to make a client for IKEA's Tradfri Gateway and after an update this year you can only connect to it over COAP when using DTLS.

**Comment by marcelbuesing** [comment]
This might help: https://github.com/simmons/tokio-dtls-example

**Comment by carllerche** [comment]
I'm not familiar w/ DTLS, but the general strategy for expanding Tokio is to start in a third party crate to experiment, and once it has been proven out there and there is a reason to move it into Tokio vs. maintain it as a third party crate, then we can start that discussion.

If you want to take a stab at it and need some pointers, the [Gitter channel](http://gitter.im/tokio-rs/tokio) is probably the best place to go.
