### ISSUE TITLE
Provide async await block_on

### ISSUE THREAD

**Issue by PvdBerg1998** [tokio-rs/tokio#737]
To my knowledge, it is currently impossible to block on an async function. Please correct me if I'm wrong.
This functionality is required for unit testing.

My current workaround for anyone that has the same problem:

```rust
macro_rules! block_on_async {
    ($test:expr) => {{
        use tokio::runtime::current_thread::Runtime;
        use tokio_async_await::compat::backward;

        let future = backward::Compat::new(async {
            let _ = await!($test);
            let result: std::result::Result<(), ()> = Ok(());
            result
        });

        let mut rt = Runtime::new().expect("Unable to start async tester runtime");
        rt.block_on(future).unwrap();
    }};
}
```

**Comment by carllerche** [comment]
Good idea, I would take a PR that adds a `block_on_async` function.

The implementation would go in [this](https://github.com/tokio-rs/tokio/blob/master/src/async_await.rs) file.

**Comment by LucioFranco** [comment]
@xxks-kkk you can use the `futures` 0.3 `fut.unit_error().boxed().compat()` and pass that to a regular tokio runtime.

```rust
use tokio::runtime::Runtime;
use futures::future::{FutureExt, TryFutureExt};

async fn example() {...}

#[test]
fn example_test() {
	let rt = Runtime::new().unwrap();
	let fut = example().unit_error().boxed().compat();
	rt.block_on().unwrap();
}
```

With this method you can use any of the tokio runtimes, so you can just do `use tokio::runtime::current_thread::Runtime;` instead.

I find this works quite well for my testing needs, though this doesn't use any of the compat features within `tokio-async-await`.

@carllerche I don't know how useful this is but I've written a proc macro to allow easy testing of tokio based futures 0.3 projects https://github.com/LucioFranco/tokio-async-await-test. I am curious to hear what your thoughts are on about using the futures 0.3 compat over tokio's `await` macro?

I've had better luck using 0.3 compat and using more futures 0.3 components and just bringing in tokio futures and slapping a `.compat()` with them. This also allows one to use the futures aware mutexs to avoid the nasty issues of mixing `std::sync::Mutex` and `await!` generators. Don't know if that is the right way to move forward but it seems like a better story than using the tokio compat features.

**Comment by carllerche** [comment]
@LucioFranco I like the macro. It probably will have more value once async / await gets more common. We probably should have a tokio-test crate too...

**Comment by PvdBerg1998** [comment]
I agree with @LucioFranco . I recently reworked my code to use futures 0.3 and everything got better. IMO `tokio-async-await` and the macro's feel like a hack. At one point I had 4 macro's wrapping async blocks in async blocks ... I recommend everyone to use the futures 0.3 solution: `fut01.compat()` or `Compat::new(fut03)`.
