### ISSUE TITLE
[Question] Streaming with fs::File::open() ?

### ISSUE THREAD

**Issue by kolbma** [tokio-rs/tokio#738]
Hey,
I've some problem with getting the types right in my code... Should it work this way? Or how can I stream with your API? When will you provide some docs again? The link from the API returns a 403.

The Box should become a `Box<Stream<Item=(String, String), Error=xerror::Error> + Send>`.

My code looks like this...

```
    Box::new(
      stream::once(fs::File::open(self.path.clone()).wait())
        .map(move |file| {
          io::lines(BufReader::new(file))
            .filter(|line| {
              true
            }).filter_map(move |line| {
              Some((line.clone(), line.clone()))
            }).map(|tup| {
              trace!("{:?}", tup);
              tup
            })
        }).map_err(Error::from),
    )
```

The error:

```
   = note: expected type `tokio::prelude::stream::Map<tokio::prelude::stream::FilterMap<tokio::prelude::stream::Filter<tokio::io::Lines<std::io::BufReader<tokio::fs::File>>, [closure@src...]>, [closure@src...]>, [closure@src...]>`
              found type `(std::string::String, std::string::String)`
   = note: required for the cast to the object type `dyn tokio::prelude::Stream<Item=(std::string::String, std::string::String), Error=xerror::Error> + std::marker::Send`
```

**Comment by carllerche** [comment]
You should not use `wait()` in async code. That will block the thread, preventing other asynchronous code from executing.

Instead of using `map`, you probably want to use `and_then`, which is an async `map` (it will flatten the future).

Hope this helps.
