### ISSUE TITLE
Cancelable multi-thread future

### ISSUE THREAD

**Issue by rojhi96** [tokio-rs/tokio#739]
Hi,

After reading the futures source, I found that Future::select() and Future::join() will only run the two futures on one thread. Is there a way to combine two futures into one so that they are executed on different threads but still can be canceled by drop()? Same for Stream::for_each().

I know tokio::spawn() and the proposal of spawn_handle() can achieve this, but it would be great to return Futures cancelable by drop().

**Comment by carllerche** [comment]
Right now, you can use `futures::sync::oneshot::spawn` to do this. Once `spawn_handle` lands, it will be more ergonomic.

**Comment by carllerche** [comment]
I'm going to close this as the feature is tracked by #638.
