### ISSUE TITLE
Is that related to tokio?

### ISSUE THREAD

**Issue by goriunov** [tokio-rs/tokio#740]
## Version
Tokio: latest
Rust: 1.30 and 1.32

## Platform
Arch linux 64x 14.19

## Description
Please checkout vide from that [Reddit Post](https://www.reddit.com/r/rust/comments/9ulbj3/weird_rust_hyper_async_behaviour_why/)
I have put some comments explaining the situation also you can check repo with cleaner code in [here](https://github.com/goriunov/rust-test) 

Blocking db in `tokio_threadpool::blocking` executes much faster with println!() then without one in the block. (I actually tested and even if i put it just in future which holds blocking it acts the same)

**Comment by carllerche** [comment]
Thanks for the issue.

This does not seem Tokio related. If you can find a profile or repo that can demonstrate an issue with Tokio, I would be happy to look into this further.

Cheers
