### ISSUE TITLE
`current_thread::Handle::spawn()` requires future to be Send?

### ISSUE THREAD

**Issue by icefoxen** [tokio-rs/tokio#744]
## Version

`tokio` 0.1.11 (also appears to exist in 0.1.12)

## Subcrates

`tokio_current_thread` I think?

## Description

`tokio::runtime::current_thread::Handle` has a `spawn()` method that takes `F: Future<Item = (), Error = ()> + Send + 'static`.  Meanwhile, `current_thread::spawn()` takes `F: Future<Item = (), Error = ()> + 'static` -- no `Send` bound.  Since the whole point of `current_thread` is to run futures that don't implement `Send`, it seems odd that the `Runtime`'s `Handle` requires that they be `Send`.

Am I misunderstanding something?

**Comment by carllerche** [comment]
`Handle` is to send futures from other threads to the single-threaded runtime.

To spawn a `!Send` future, use the [free function](https://docs.rs/tokio/0.1.12/tokio/runtime/current_thread/fn.spawn.html).

Hope this helps.

Also, where in the docs do you think this should be explained to avoid the confusion?

**Comment by carllerche** [comment]
I'm going to close this issue, but if you have thoughts on how to improve the docs, please open a new issue on http://github.com/tokio-rs/doc-push.
