### ISSUE TITLE
Refine release process

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#765]
Tokio consists of a number of sub crates, each with their own dependencies. This can make releasing new versions of sub crates while maintaining correct minimal dependencies tricky.

I propose the following process:

* All `tokio-*` dependencies in `[dependencies]` sections depend on a version from crates.io.
* All `tokio-*` dependencies in `[dev-dependencies]` sections specify paths as dependencies.
* If a crate requires a new API that has not been released to crates.io yet, it updates its dependency to a path dependency.
* When releasing to crates.io, any path dependencies get converted back to version dependencies.

See change in #766

cc @tobz @jonhoo @seanmonstar @stjepang @ipetkov

**Comment by stjepang** [comment]
> This can make releasing new versions of sub crates while maintaining correct minimal dependencies tricky.

Just to make sure I understood: If crate A depends on crate B, and we bump the version of B, then we'd like to avoid having to bump the version of B in A's Cargo.toml, too? Is that what this is about?

**Comment by carllerche** [comment]
@stjepang yes, in part.

**Comment by LucioFranco** [comment]
@carllerche one of our members in the amethyst project has started work on a `cargo publish --all` kind of tool. It seems it takes the method of bumping a crate's version when a breaking change is introduced. The goal of the tool is then to allow CI to publish changes. This seems like it aligns with the same goals stated here.

https://gitlab.com/torkleyy/cargo-publish-all

This week I'll spend sometime trying it out with the `--dry-run` option.

**Comment by carllerche** [comment]
This was done i believe.
