### ISSUE TITLE
tokio-io, tokio-fs: No impl for Seek / No trait AsyncSeek

### ISSUE THREAD

**Issue by agrif** [tokio-rs/tokio#776]
The *tokio-fs* `File` struct implements both `Read` and `Write`, but not `Seek`, despite exposing seeking functionality.

Similarly, there is no trait in *tokio-io* that encapsulates an async-seekable thing in the same way that `AsyncRead` and `AsyncWrite` do for `Read` and `Write`.

I would be happy to take a stab at fixing this, but I was wondering if there was a reason why it hasn't been implemented yet. Also, if an `AsyncSeek` trait was added, should the seek methods on `File` be removed?

**Comment by tobz** [comment]
@agrif I think you contributing a PR would be great!

The answer to your first question is easy, though: the tokio-fs stuff was more of a small core concept -- bundled with the `blocking` stuff -- to start providing a footing for applications doing asynchronous file I/O.  It was missing things at release compared to where it is now.  A lot of the development of it is needs-based at this point.

As far as removing the seek methods on the current API: that would be backwards-incompatible so we wouldn't want to do that, no.  We could potentially deprecate them but we would have to remove them as a future release to provide a clean break.

**Comment by carllerche** [comment]
@agrif In what case do you need the `Seek` trait here? Would implementing the seek fns directly on `File` work for your case?

**Comment by agrif** [comment]
Ok, I will come up with a PR sometime this week.

@carllerche I'm writing code that needs to read and seek, and also needs to work on more than just `File`. For the async case I can write my own `AsyncSeek` and implement it as needed (though that should probably be part of *tokio-fs*) but for the synchronous case I'm out of luck, because orphan rules prevent me from implementing `Seek` on `File` directly. I could create a newtype, but again, that seems like something better solved by just implementing `Seek` in *tokio-fs*.

(Why does my code need to work on more than just `File`? Well, at least to start it'd be nice to be able to test by providing the code with something like `Cursor` that implements the traits I need, instead of having to test on actual files. Roughly, I need `AsyncSeek` for the same reasons I need `AsyncRead`.)

**Comment by agrif** [comment]
Alright, I have an implementation in #785. Just posting here real quick to ping any subscribers.
