### ISSUE TITLE
tokio-uds: unix:Datagram::poll_send returns Error(ErrorKind==Other(EAGAIN))

### ISSUE THREAD

**Issue by flxo** [tokio-rs/tokio#779]
## Version

```
└── tokio v0.1.11
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.10
    ├── tokio-current-thread v0.1.3
    │   └── tokio-executor v0.1.5
    ├── tokio-executor v0.1.5 (*)
    ├── tokio-fs v0.1.4
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-threadpool v0.1.8
    │       └── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-io v0.1.10 (*)
    ├── tokio-reactor v0.1.6
    │   ├── tokio-executor v0.1.5 (*)
    │   └── tokio-io v0.1.10 (*)
    ├── tokio-tcp v0.1.2
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.6 (*)
    ├── tokio-threadpool v0.1.8 (*)
    ├── tokio-timer v0.2.7
    │   └── tokio-executor v0.1.5 (*)
    ├── tokio-udp v0.1.2
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.10 (*)
    │   └── tokio-reactor v0.1.6 (*)
    └── tokio-uds v0.2.3
        ├── tokio-io v0.1.10 (*)
        └── tokio-reactor v0.1.6 (*)
```

## Platform

* Android 6.0.1
*  NDK r12b
* rustc 1.30.1 (1433507eb 2018-11-07) `arm-linux-androideabi`,  

## Subcrates

`tokio-uds`

## Description

The Android logging system opens a Unix socket (`/dev/socket/logdw`) where logs that shall be written to `logd`'s buffers are sent to. This is normally done via the native Android component `liblog`. For performance reasons I directly open the socket in order to stream log records into it. The protocol is pretty simple and not important here. The socket is kept in a struct that implements `Sink` and in `poll_complete` I'm flushing some `Bytes` into the socket. The code is basically the same as in `UnixDatagramFramed`.

With heavier load on the system, some calls to `UnixDatagram::poll_send` return the following error:

`Os { code: 11, kind: WouldBlock, message: "Try again" }`

which results in a termination of the stream forwarding.

I don't get the point why this error is returned here because for my understanding the `EAGAIN` (11) indicates `WouldBlock` and I would have expected to get a `Async::NotReady`. For getting things work I manually handle this case with a `NotReady`. I consider this as a workaround:

```rust
    fn poll_complete(&mut self) -> Poll<(), Error> {
       ...
        let n = match self.socket.poll_send(&self.wr) {
            Ok(Async::Ready(n)) => n,
            Ok(Async::NotReady) => return Ok(Async::NotReady),
            Err(e) => {
                if let Some(EAGAIN) = e.raw_os_error() {
                    return Ok(Async::NotReady);
                } else {
                    return Err(e);
                }
            }
        };
       ...
    }
```

I checked the error code in the platform which is declared in `libc::unix::notbsd::mod.rs` by 

```rust
pub const EAGAIN: ::c_int = 11;
...
pub const EWOULDBLOCK: ::c_int = EAGAIN;
```

Somewhere in tokio/mio the mapping for the `EAGAIN` to `WouldBlock` seems to be not correct. Correct me if I missed something.
I tried to track it down but got lost somewhere in mio. Feedback from the Rustfest Networking/Web workshop was also that this looks like a platform specific bug.

I'm eager to check/test suggestions or follow hints.
I have the full setup/hardware available and the behaviour is reproducible. (btw thanks for [cargo-edit-locally](https://github.com/alexcrichton/cargo-edit-locally)).

**Comment by tobz** [comment]
Yep, this looks like it's broken in Tokio!

    pub fn poll_send(&self, buf: &[u8]) -> Poll<usize, io::Error> {
        if self.io.poll_write_ready()?.is_not_ready() {
            return Ok(Async::NotReady);
        }
        let r = self.io.get_ref().send(buf);
        if is_wouldblock(&r) {
            self.io.clear_write_ready()?;
        }
        r.map(Async::Ready)
    }

Whenever we get a `WouldBlock`, we handle it in terms of fixing the underlying readiness of the mio I/O handle, but then `r.map(Async::Ready)` passes it right through as the original error.

Would you consider writing a PR to fix this? I can guide you and point out existing code that we would likely want to emulate.

**Comment by carllerche** [comment]
ideally we would have tests for this.... It is unfortunate that we don't

**Comment by flxo** [comment]
@tobz Thanks for taking a look at and the explanation!

So said a `return Ok(Async::NotReady);` is missing in the `is_wouldblock` if block in `UnixDatagram::poll_send` *and* `UnixDatagram::poll_send_to`? Same as it's probably correctly implemented in `UnixDatagram:: poll_recv(_from).

If you agree I'd test and create a PR tomorrow.

**Comment by tobz** [comment]
Yeah, functionally, that sounds correct.

If you're willing, we should make this match how `TcpStream` does it: https://github.com/tokio-rs/tokio/blob/master/tokio-tcp/src/stream.rs#L362

So, for example, we'd go from:

    pub fn poll_recv_from(&self, buf: &mut [u8]) -> Poll<(usize, SocketAddr), io::Error> {
        if self.io.poll_read_ready(Ready::readable())?.is_not_ready() {
            return Ok(Async::NotReady);
        }
        let r = self.io.get_ref().recv_from(buf);
        if is_wouldblock(&r) {
            self.io.clear_read_ready(Ready::readable())?;
            return Ok(Async::NotReady);
        }
        r.map(Async::Ready)
    }

to

    pub fn poll_recv_from(&self, buf: &mut [u8]) -> Poll<(usize, SocketAddr), io::Error> {
        try_ready!(self.io.poll_read_ready(Ready::readable()));

        match self.io.get_ref().recv_from(buf) {
            Ok(ret) => Ok(ret.into()),
            Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
                self.io.clear_read_ready(mio::Ready::readable())?;
                Ok(Async::NotReady)
            }
            Err(e) => Err(e),
        }
    }

It unifies the different network crates and produces code that's a little bit more idiomatic.

Either way,  your assessment is correct -- `poll_recv` has the correct structure -- and your outlined change would fix the problem.  We'll accept a PR for that approach or my approach.
