### ISSUE TITLE
Question / Suggestion + example idea

### ISSUE THREAD

**Issue by fawix** [tokio-rs/tokio#78]
Hi Folks, I have been poking around tokio (both the documentation and the repos here) trying to understand the new concepts; I think the documentation does a good job at explaining the basics of Futures, (I read it sequentially) Streams and Sink (although would be nice to see some medium complexity examples). 

In the docs I couldn't find any explanation how to chain several futures together. I have seen I can use `future_a.and_then(future_b);` but what if I have a bunch of futures and writing them by hand like that is not an option? (see what I mean below).

I came up with a simple example where this use-case shows;
the idea is to fetch the stop stores from HN. 

```rust
extern crate hyper;
extern crate hyper_tls;
extern crate futures;
extern crate tokio_core;
extern crate serde;
extern crate serde_json;

#[macro_use]
extern crate serde_derive;

use futures::{Future, Stream};
use hyper::{Client, Chunk};
use hyper_tls::HttpsConnector;
use tokio_core::reactor::Core;

use std::error::Error;
use std::io;
use std::fmt;

#[derive(Deserialize)]
struct Story {
    by: String,
    id: i32,
    score: i32,
    time: i32,
    title: String,
}

impl fmt::Display for Story {
    fn fmt (&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}, by {}", self.title, self.by)
    }
}

fn run () -> Result<(), Box<Error>> {

    let mut core = Core::new()?;

    let client = Client::configure()
                    .connector(HttpsConnector::new(8, &core.handle())?)
                    .build(&core.handle());

    let url = "https://hacker-news.firebaseio.com/v0/topstories.json".parse()?;
    let request = client.get(url).and_then(|response| {
        response.body().concat2().and_then(move |body: Chunk| {
            let v: Vec<i32> = serde_json::from_slice(&body).map_err(|e|{
                io::Error::new(io::ErrorKind::Other, e)
            })?;
            Ok(v)
        })
    });

    let ids: Vec<i32> = core.run(request)?;

    for id in ids {
        let url = format!("https://hacker-news.firebaseio.com/v0/item/{}.json", id).parse()?;
        let request = client.get(url).and_then(|response| {
            response.body().concat2().and_then(move |body: Chunk| {
                let v: Story = serde_json::from_slice(&body).map_err(|e|{
                    io::Error::new(io::ErrorKind::Other, e)
                })?;
                Ok(v)
            })
        });

        println!("{}", core.run(request)?);
    }


    Ok(())
}

fn main() {
    if let Err(e) = run () {
        eprintln!("Error: {}", e);
    }
}
```

At the moment this code is running extremely slow, I think I'm not handling futures properly.... or maybe because I'm calling core.run so many times; Thoughts?

PS: feel free to re-use the idea if you want to include something like that in the docs.

**Comment by alexcrichton** [comment]
@fawix I think you may want to use streams here perhaps? The original URL, `topstories.json`, I think could be viewed as returning a stream of `i32` values which you could then use stream combinators to chain on further compuation of fetching that particular item.

In particular I think if you did something like:

```rust
let stream_of_i32 = request.map(|v| stream::iter_ok(v)).flatten_stream();
let stories = stream_of_i32.map(|id| /* create `request` future */);
let stories = stories.buffered(10); // allow 10 HTTP fetches in parallel at most
let stories = core.run(stories.collect()); // collect a vector of stories
```

Would that work for you?

**Comment by fawix** [comment]
@alexcrichton thanks! Yes indeed it does make more sense! let me refactor it! 
Would you like to get the final version to include as an example to the docs maybe?

**Comment by alexcrichton** [comment]
Perhaps yeah, although we're currently in the middle of a rewrite of our documentation, so it may be best to wait to see how the dust settles before adding it. That being said I'm going to close this for now, but if it doesn't work please just let us know!
