### ISSUE TITLE
tokio::io::stdin() should return error on current_thread runtime

### ISSUE THREAD

**Issue by ufoscout** [tokio-rs/tokio#788]
## Version
```
$ cargo tree | grep tokio
│   ├── tokio v0.1.13
│   │   ├── tokio-codec v0.1.1
│   │   │   └── tokio-io v0.1.10
│   │   ├── tokio-current-thread v0.1.4
│   │   │   └── tokio-executor v0.1.5
│   │   ├── tokio-executor v0.1.5 (*)
│   │   ├── tokio-fs v0.1.4
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-threadpool v0.1.9
│   │   │       └── tokio-executor v0.1.5 (*)
│   │   │   └── tokio-io v0.1.10 (*)
│   │   ├── tokio-io v0.1.10 (*)
│   │   ├── tokio-reactor v0.1.7
│   │   │   ├── tokio-executor v0.1.5 (*)
│   │   │   └── tokio-io v0.1.10 (*)
│   │   ├── tokio-tcp v0.1.2
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-reactor v0.1.7 (*)
│   │   ├── tokio-threadpool v0.1.9 (*)
│   │   ├── tokio-timer v0.2.8
│   │   │   └── tokio-executor v0.1.5 (*)
│   │   ├── tokio-udp v0.1.3
│   │   │   ├── tokio-codec v0.1.1 (*)
│   │   │   ├── tokio-io v0.1.10 (*)
│   │   │   └── tokio-reactor v0.1.7 (*)
│   │   └── tokio-uds v0.2.4
│   │       ├── tokio-codec v0.1.1 (*)
│   │       ├── tokio-io v0.1.10 (*)
│   │       └── tokio-reactor v0.1.7 (*)
│   ├── tokio-codec v0.1.1 (*)
│   ├── tokio-executor v0.1.5 (*)
│   ├── tokio-io v0.1.10 (*)
│   ├── tokio-reactor v0.1.7 (*)
│   ├── tokio-signal v0.2.7
│   │   ├── tokio-executor v0.1.5 (*)
│   │   ├── tokio-io v0.1.10 (*)
│   │   └── tokio-reactor v0.1.7 (*)
│   ├── tokio-tcp v0.1.2 (*)
│   ├── tokio-timer v0.2.8 (*)
│   │   ├── tokio-executor v0.1.5 (*)
│   │   ├── tokio-io v0.1.10 (*)
│   │   ├── tokio-reactor v0.1.7 (*)
│   │   ├── tokio-tcp v0.1.2 (*)
│   │   ├── tokio-timer v0.2.8 (*)
│   │   ├── tokio-udp v0.1.3 (*)
│   │   ├── tokio v0.1.13 (*)
├── tokio v0.1.13 (*)
├── tokio-codec v0.1.1 (*)
└── tokio-io v0.1.10 (*)
```

## Platform
Linux ufo-laptop-1 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Description
Based on the documentation here provided:
https://github.com/tokio-rs/tokio/blob/f929576f0ea0debedd31cccd9b5a336ea1687568/tokio-fs/src/lib.rs#L10-L25

I expected that using `tokio::io::stdin()` in a not supported runtime would return a `std::io::ErrorKind::WouldBlock` error. Nevertheless, trying to read from tokio::io::Stdin from the `current_thread` runtime causes the thread and, in some cases, the entire application, to silently block.

This issue was found while developing an actix based application and [originally reported here](https://github.com/actix/actix/issues/181), in fact, actix uses the `current_thread` runtime by default and using the tokio::io::Stdin results in a completely blocked application.

Here a complete reproducer: https://github.com/ufoscout/actix_stdio

**Comment by DoumanAsh** [comment]
Just for reference, I did check and tokio does return error, so there is no issue per se

**Comment by tobz** [comment]
@DoumanAsh Where does Tokio throw an error for this situation?
