### ISSUE TITLE
Question: Is there a dependency between listener's socket stream and other tasks?

### ISSUE THREAD

**Issue by algermissen** [tokio-rs/tokio#8]
Hi,

in a minimal server (using hyper) I am seeing a behaviour that just cannot understand. It is likely that I am just missing a key point about Tokio internals, but I'd really like to understand the reason for what I am seeing.

The server uses a single thread, takes accepted connections from the incoming() stream and hands them to a hyper server for very simple processing (doing some string ops to simulate CPU work). Every connection's server is spawned on a new task by hyper.

The server can handle ~250 req/s (each request's work takes about 4ms, so that makes sense). I am load testing this with an external load generator and I am using a new connection for each request. I have metrics inside the service, and I can validate that the above indeed happens as described.

I also measure the number of connections taken from incoming() stream and I can see that ~250 connections/s are taken from the stream.

This completely goes against my expectations - I would have thought Tokio would just read from the stream as much as provided and I'd expect new connections to pile up, while waiting to be processed. Instead, they pile up before the incoming() stream - the are visible as not-served / long latency test requests outside my service.

When I reduce the work amount (eg from 5ms to 2ms duration), the server handles more requests according to this reduction - but it also shows more accepted connections. Again about the same rate as the req/s rate.

This relationship between the processing speed of incoming and the request/s rate confuses me completely - since they are on different tasks, what inside of Tokio makes them go a similar pace?

Can somebody help me figure out the reason for this behaviour?

The test server's incoming stream loop is here https://github.com/algermissen/web-rust/blob/708831056b92304426e00e3e2f529b16d229d2ea/src/bin/testserver.rs#L155

Jan

**Comment by alexcrichton** [comment]
Hm an interesting question! I don't believe there's any inherent backpressure here, it looks like in the server you constructed there's no limit on spawned tasks so the server should continue to accept connections as quickly as it can and spawn tasks for them.

Are you doing the CPU heavy work on the event loop? That may mean that on each turn of the event loop all outstanding connections are satisfied (basically blocking the event loop while they're working) which could explain this perhaps?

**Comment by algermissen** [comment]
I moved out the CPU bound work to another thread (using onshots) and indeed, this is significantly changing the overall behvior. The server can now do more then 4 times the requests per second and I also see the connections piling up, waiting to be processed at some point.

Thanks.
