### ISSUE TITLE
tokio-io: A way to reunite `ReadHalf` and `WriteHalf`?

### ISSUE THREAD

**Issue by twittner** [tokio-rs/tokio#803]
## Version

tokio-io 0.1.10

## Platform

Linux 4.19.9-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

## Description

`tokio_io::AsyncRead` allows to [split](https://docs.rs/tokio-io/0.1.10/tokio_io/trait.AsyncRead.html#method.split) itself into a `ReadHalf` and `WriteHalf` if `Self` also implements `tokio_io::AsyncWrite`. However I did not see a way to reunite the two halves back into the original type. The split functionality is implemented using `futures::sync::Bilock` which does provide a [reunite](https://docs.rs/futures/0.1.25/futures/sync/struct.BiLock.html#method.reunite) method. It would be nice if `tokio-io` would also allow getting back the original type, e.g. via a `reunite` function in `tokio-io/src/split.rs`

```rust
/// Reunite the two halves of a previously split resource.
pub fn reunite<T>(r: ReadHalf<T>, w: WriteHalf<T>) -> Result<T, (ReadHalf<T>, WriteHalf<T>)> {
    r.handle.reunite(w.handle).map_err(|err| {
        (ReadHalf { handle: err.0 }, WriteHalf { handle: err.1 })
    })
}
```

I would be happy to open a PR implementing this if there is a chance of getting this merged.

**Comment by arthurprs** [comment]
Maybe `unsplit`, for symmetry?
