### ISSUE TITLE
Call tokio based rust code from C++

### ISSUE THREAD

**Issue by VMatrix1900** [tokio-rs/tokio#811]
Hi, I wonder if it is possible to call a tokio based library(Such as a transport protocol developed using tokio) from C/C++? If so, how can I accomplish that?

**Comment by tobz** [comment]
Hi Vincent!

Rust supports compilation into a shared object/dynamic library, along with not mangling function names, for inclusion and calling from languages like C/C++: https://doc.rust-lang.org/1.2.0/book/rust-inside-other-languages.html

There shouldn't really be anything specific to Tokio when it comes to doing this. Best of luck! 👍
