### ISSUE TITLE
Question: Determining which worker ID that a task is running on

### ISSUE THREAD

**Issue by mmstick** [tokio-rs/tokio#815]
Is there a means to get the ID of a worker that is spawned on a `Runtime`?

```rust
oneshot::spawn_fn(
    || {
        eprintln!("processing on worker {}", ???);
        doing_thing()
    },
    &DefaultExecutor::current()
)
```

**Comment by stjepang** [comment]
This is not possible. Why do you need to get the ID of the worker? Is it just for debugging or do you have another use case in mind?

**Comment by carllerche** [comment]
I think the right way to provide this info for debugging will be via Tokio trace [here](https://github.com/tokio-rs/tokio/issues/561).

**Comment by carllerche** [comment]
Tracking this in #1186.
