### ISSUE TITLE
Error 111 when running the Hello World example

### ISSUE THREAD

**Issue by bertdemiranda** [tokio-rs/tokio#820]
This is a documentation issue: a flag `-p` is missing from the nc command.

Got error 111 when running the Hello World example with 
`$ nc -l 6142` for the receiving socket as described.

The output of the program:
`Running `target/debug/hello-world`
About to create the stream and write to it...
connection error = Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
Stream has been created and written to.
`

When using the command `$ nc -l -p 6142` for the receiving socket the program runs without errors.

**Comment by vokar97** [comment]
Fixed in tokio-rs/website#284.
