### ISSUE TITLE
Async / await needs a new release to work on latest nightly

### ISSUE THREAD

**Issue by qiimm** [tokio-rs/tokio#821]
The recent pin stabilization makes tokio-async-await 0.1.4 incompatible. It's fixed on master, but that requires a version bump to be effective.

This sentence in README.md is false:
> To use this crate, you need to start with a Rust 2018 edition crate, with rustc 1.33.0-nightly or later.

(rustc 1.33.0-nightly _or later_ doesn't work. You need rustc 1.33.0-nightly-2018-12-25 _or earlier_.)

------------

__EDIT__: As @LucioFranco pointed out, 1.33.0-nightly-2018-12-25 and earlier do work.

**Comment by LucioFranco** [comment]
Technically it is still correct you just need a `nightly` that is before `12-25-2018` as that was when the pin changes were introduced but yes there should be a new release.

**Comment by carllerche** [comment]
Fixed by #836
