### ISSUE TITLE
Create `tokio-test` for tokio testing utilities

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#841]
I would like to propose we add a `tokio-test` crate that will provide nice testing utilities out of the box. Current considerations to be included are:

- [ ] implement `tokio_test::block_on`
- [ ] include carllerche/mock-io@f3ddbf19207b4b91629a1e8a8122ca48828d1ffe
- [ ] include carllerche/fixture-io@3dc9148ae4319e34b499f89b08ed25c980f1401e
- [ ] include carllerche/tokio-mock-task@54b117f84d7c481e9edaccc45f740c9421a1fe90
- [ ] possibly include [carllerche/futures-test](https://github.com/carllerche/better-future/tree/master/futures-test)
- [ ] include tokio support utilities [here](https://github.com/tokio-rs/tokio/blob/d822b721b4c88a693dc04d281c02b61f857158d5/tokio-timer/tests/support/mod.rs) and throughout the rest of the code base
- [ ] https://github.com/tokio-rs/tokio/pull/1030#issuecomment-479593179

If anyone has anymore they would like to add please comment!

**Comment by carllerche** [comment]
tokio-test was included. I unfortunately created a dup of this issue. I will pull in ideas from here into #1175.

**Comment by carllerche** [comment]
tokio-test was included. I unfortunately created a dup of this issue. I will pull in ideas from here into #1175.
