### ISSUE TITLE
DelayQueue fails to yield long delays

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/tokio#853]
Stumbled into this trivial failing test in pursuit of a more complex bug. Failure seems to occur for items inserted at `epoch + ms(x)` for all x > 64.
```rust
#[test]
fn single_long_delay() {
    mocked(|timer, time| {
        let mut queue = DelayQueue::new();
        let mut task = MockTask::new();

        let epoch = time.now();

        let key = queue.insert_at("foo", epoch + ms(65));

        task.enter(|| {
            assert_not_ready!(queue);
        });

        turn(timer, ms(100));

        assert!(task.is_notified());

        assert_ready!(queue);
    })
}
```

**Comment by carllerche** [comment]
I think this is expected. `turn` only does one tick of the timer. The timer does not always advance to the next timeout. It has to do some bookkeeping every so often. Setting a timeout at 100 ms requires the timer to perform a bookkeeping step in 64ms.

There is an argument to implement an optimization where the timer tracks that there are no timeouts until 100ms and skips the bookkeeping at 64ms, but that is not implemented.

As such, I am going to close this.
