### ISSUE TITLE
Question: Inserting in DelayQueue at runtime

### ISSUE THREAD

**Issue by jean-airoldie** [tokio-rs/tokio#857]
Hi,
Is there a way to insert into a `DelayQueue` from a future yielded by the same `DelayQueue`?
I'm thinking of someting like this:
```rust
let interval =  Duration::from_secs(10);

let mut queue = DelayQueue::<()>::new();
queue.insert_at((), Instant::now());

// This takes ownership of the queue.
queue.for_each(move |_| {
  // Can't work because we use a value that has already been moved.
  queue.insert((), interval);
}
```
My specific use case is to combine a `Stream` that yields every 10min with another `Stream` via `Stream::select()` so that I can run a task at a fixed interval while simultaneously handling another steam. I tried using `Interval` but it blocks when polling.

**Comment by Ralith** [comment]
`Interval` should work fine for this; no idiomatic future/stream should block inside poll. `DelayQueue` is meant for more complex/low-level use cases where you're implementing poll yourself.

**Comment by jean-airoldie** [comment]
You are right. I wrote this minimal example and it does not block. Must be something wrong with my stream.
```rust
use tokio::prelude::{Async, Poll, Stream, Future, stream::poll_fn};
use tokio::timer::{Interval, Error};
use std::{time::{Instant, Duration}, thread};
use rand;

pub enum MergedItem<I1, I2> {
    First(I1),
    Second(I2),
}

fn main() {
    let stream = poll_fn(move || -> Poll<Option<()>, Error> {
        if rand::random::<bool>() {
            Ok(Async::NotReady)
        } else {
            Ok(Async::Ready(Some(())))
        }
    });

    let interval = Interval::new(Instant::now(), Duration::from_secs(5));

    let merged = interval
        .map(MergedItem::First)
        .select(stream.map(MergedItem::Second))
        .for_each(move |result| match result {
            MergedItem::First(_) => {
                println!("received interval notification!");
                Ok(())
            }
            MergedItem::Second(_) => {
                println!("received stream item!");
                Ok(())
            }
        }).map_err(|e| panic!(e));

    tokio::runtime::run(merged);
}
```
Thanks for the quick response!

**Comment by Ralith** [comment]
Unexpected hung futures and streams usually arise due to returning NotReady without arranging for the task to be notified/woken in the future. For example, in the code you posted above you're doing exactly that, although progress will still be made by coincidence as the `Select` future gets polled due to timer wakeups alone.

**Comment by jean-airoldie** [comment]
@Ralith Alright then that's exactly my problem. Do you suggest any specific documentation / code regarding implementing a `Stream`?

**Comment by Ralith** [comment]
The same rules apply as for implementing `Future`. https://tokio.rs/docs/going-deeper/futures/ may be of interest.
