### ISSUE TITLE
Interleaving CPU and IO work on the main reactor task

### ISSUE THREAD

**Issue by vitalyd** [tokio-rs/tokio#87]
I'm experimenting with porting a Java-based server (which I'll describe below) to Tokio + Rust, and having some difficulty in getting adequate performance from it; the reason for the performance gap, I suspect, is me misusing the reactor, or rather, not playing along nicely with it.  I wanted to confirm this, and see if there's a way to achieve what I'd like without introducing more threads into the mix.  So, without further ado, here's how the server works:

## Phase 1
1. Runs a `tokio_core::net::TcpListener` on a `Core` and waits for clients to connect.  The server knows a priori which clients to expect - a handshake is done upon accepting a connection, and this handshake identifies the client.
1. Once all expected clients are connected, the main future completes and the `TcpListener` is dropped (no need to keep the listener up since we do not expect more connections after this point).  This main future resolves to a `Vec` of structs representing a client, which is essentially a wrapper over the `tokio_core::net::TcpStream`.

This phase is pretty straighforward - no issues here.  I wanted to outline it anyway in case someone finds it of relevance.

## Phase 2
This is the phase that's slow.  It runs a simulation of sorts, modeling D days and each day having N iterations of clients taking turns interacting with the simulation state.  More details:
1. For each day, we run N iterations.  Each iteration consists of:
- a client is picked from the list of clients
- some simulation state is gathered for this client - this is purely in-memory calculations, and are very light on the CPU.
- the simulation state is sent to the client (over the TCP connection using textual json as the encoding).  **This part can happen in the background, technically speaking**
- similar simulation state is gathered for the other clients, and sent to them in the same manner.
- the server then needs to receive a request from the picked client from the first step, and update the simulation state based on the contents of that message.  **This part must complete before we move to the next iteration**.
- the next iteration is the same except a different client is picked.
1. The above proceeds for all D days, and then the simulation ends.

The way I have Phase 2 implemented (which I suspect is less than ideal) is via one large chain of futures, with the "root" future being `run()` on the `Core`.  For each client, however, I did `spawn` a future that handles its socket (and framed) rx/tx communication.  Each client has a `futures::unsync::mpsc::UnboundedSender` that the simulation task uses to send messages to it; this sender is wired up to the `FramedWrite` (on top of the socket) with a `send_all` combinator (i.e. the socket Sink is writing all messages received from the channel).  The rx portion of the tcp stream is given to the client directly, where the simulation treats it like a `Stream` when trying to read messages from it.   

The root simulation future is implemented as a couple of `LoopFn`s, one looping over the days and a nested one looping over the iterations.

The performance is pretty bad, and I suspect it's because I'm doing too much on the root task and not allowing enough concurrency (i.e. monopolizing the reactor thread, so to speak).  The actual non-IO work in the simulation is pretty cheap, as mentioned, so I was trying to see if I could interleave IO and execution on the same reactor thread without taking a performance hit.  However, I've thus far failed to do that :).

Am I just barking up the wrong tree here? I could try redesigning this with a dedicated thread for the reactor, a background thread for running the simulation, and communicating between the two via channels.  But I wanted to see if there was a way to keep it single-threaded and delicately interleave the IO and CPU work.

Any suggestions/thoughts/tips? Also happy to elaborate on the current design more, or anything else that's unclear.

**Comment by vitalyd** [comment]
Hey @alexcrichton,

Answering your questions first:
1. CPU usage is very low, which leads me to believe I’m stalling waiting on I/O.  Notably, a simulation tick cannot proceed to the next tick until the selected client responds to a message sent from the server.  The client only responds when it receives a message from the server.  So it’s possible that the event loop isn’t getting to service this I/O in a timely enough manner because I’m also running other code on the thread.
1. I’m using a single Core.  The Core is `run()` twice, once for Phase 1 and then for Phase 2.
1. There’s no other blocking calls on the reactor thread.  It’s literally IO to/from the clients and some CPU work mixed in. No other threads involved, no mutexes and so on.

I’ll also note that all clients are on the same machine so network latency/jitter is out of the equation.

I rewrote this thing to use a single reactor thread doing only IO and a background thread to run the simulation; they’re connected with channels.  The performance here is where it needs to be, so that’s good.

It’s possible that I configured the future chains incorrectly such that some can’t proceed until a child is resolved but I did put the client IO on separate tasks by spawning them via the Handle.  Still, I won’t rule out a misuse on my end.

Are there any examples of doing such CPU + IO interleaving on a single Core? Most examples I’ve seen are either heavily IO bound or use dedicated worker threads for offload.  I unfortunately can’t share the code but the closest analogy I can think of is a server playing chess against multiple clients, except the CPU work in my case is nowhere near the complexity of a (proper) chess engine.  But the protocol (ie taking turns with a client, multiplexing across clients) is similar.

**Comment by vitalyd** [comment]
Oh, the chess analogy is slightly off in that the server has global state that affects all clients - a given client’s action affects the overall simulation.  But the protocol is similar.

**Comment by alexcrichton** [comment]
Hm yeah it's definitely possible to do cpu/I/O work on one thread (or rather the thread calling `epoll` does *something* when it wakes up). It sounds like there's nothing awry here though, so unfortunately I'm not sure what's going on :(

If you're willing to share the code I can be sure to keep it to myself of course, but you may also want to try out tools like `perf trace` to see if there's any syscalls which are taking longer than expected (everything should be super fast except for `epoll` basically)

**Comment by vitalyd** [comment]
@alexcrichton, I’ll dig around some more.  Right now I’m going to proceed with the latest design using a background thread for running the simulation but will hopefully come back to trying running both on the reactor.

What would a high level sketch be of how you’d run a simulation on the reactor? Right now I have the client IO spawned as separate tasks and the core runs the main future representing the simulation.  As mentioned, iterating over days is modeled via a `loop_fn`; similarly, the N iterations per day are another `loop_fn`.  I tried modeling each iteration within a day as a custom struct implementing `Future`, and even tried sprinkling in some yields (ie notify the current task and return `Async::NotReady`) in hopes of letting any IO go through, but that didn’t help.  If you could give a high level outline of this that would be really helpful.  Keep in mind that each iteration of a day cannot proceed to the next iteration until the client responds to the server’s previous message to that client, which is also done on that iteration (but that message can go out async, no need to wait for its send completion).

Thanks!

**Comment by vitalyd** [comment]
Ok, thanks @alexcrichton.  I'll close this issue but will report back if I find anything of interest.  Thanks for your help and time!
