### ISSUE TITLE
Inner spawned futures dont get executed using tokio-core

### ISSUE THREAD

**Issue by snawaz** [tokio-rs/tokio#883]
## Problem

I've two functions `test1` and `test2`:

-  `test1` has used tools from `tokio_core` whereas `test2` has used `tokio`. 

My understanding of these libraries is that these two functions should behave in the same way &mdash; that is, they're semantically same. However, in the case of `test1` , the *spawned* future using the `handle` from inside `for_each` is not getting executed by Tokio, as it is getting executed in the case of `test2`. That is, `FOR EACH INSIDE` statement isn't getting printed in `test1` whereas it does in case of `test2`.

Is this a bug *in the tokio-core*? Or  is it designed differently than `tokio` and thus my assumption that these two functions are semantically same, is wrong? What do I have to change in `test1` so that the future passed to `.spawn()` gets executed as well?

```
fn test1() {
    use futures::{stream, Stream, Future};
    use tokio_core::{reactor::{Core, Handle}};
        
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let values = vec!["one", "two", "three"];

    let f = stream::iter_ok(values).for_each(move |value| {
                println!("{}", value);
                handle.spawn(futures::future::ok(959).map(move |x| { 
                    println!("FOR EACH INSIDE => {:?}", x); 
                }));
                let ret : Result<(), ()> = Ok(());
                ret 
        }); 
    core.run(f);
}

fn test2() {
    use futures::{stream, Stream, Future};
        
    let values = vec!["one", "two", "three"];
        
    let f = stream::iter_ok(values).for_each(|value| {
                println!("{}", value);
                tokio::spawn(futures::future::ok(959).map(move |x| { 
                    println!("FOR EACH INSIDE => {:?}", x); 
                }));
                let ret : Result<(), ()> = Ok(());
                ret 
        }); 

    tokio::run(f);
}

```
## Version

I'm using `cargo 1.31.0 (339d9f9c8 2018-11-16)`.  

Here is the output of `cargo tree | grep tokio`

```
│   ├── tokio-timer v0.2.9
│   │   └── tokio-executor v0.1.6
│   │   │   │   │   └── tokio-io v0.1.11
│   │   │   │   │   ├── tokio-connect v0.1.0 (/nix/store/v83b0fl8q620bvx8qzfz0a93fdv8l6bk-source)
│   │   │   │   │   │   └── tokio-io v0.1.11 (*)
│   │   │   │   │   ├── tokio-io v0.1.11 (*)
│   ├── tokio v0.1.15
│   │   ├── tokio-codec v0.1.1
│   │   │   └── tokio-io v0.1.11 (*)
│   │   ├── tokio-current-thread v0.1.4
│   │   │   └── tokio-executor v0.1.6 (*)
│   │   ├── tokio-executor v0.1.6 (*)
│   │   ├── tokio-fs v0.1.5
│   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   └── tokio-threadpool v0.1.11
│   │   │       └── tokio-executor v0.1.6 (*)
│   │   │   └── tokio-io v0.1.11 (*)
│   │   ├── tokio-io v0.1.11 (*)
│   │   ├── tokio-reactor v0.1.8
│   │   │   ├── tokio-executor v0.1.6 (*)
│   │   │   └── tokio-io v0.1.11 (*)
│   │   ├── tokio-sync v0.1.0
│   │   ├── tokio-tcp v0.1.3
│   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   └── tokio-reactor v0.1.8 (*)
│   │   ├── tokio-threadpool v0.1.11 (*)
│   │   ├── tokio-timer v0.2.9 (*)
│   │   ├── tokio-udp v0.1.3
│   │   │   ├── tokio-codec v0.1.1 (*)
│   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   └── tokio-reactor v0.1.8 (*)
│   │   └── tokio-uds v0.2.5
│   │       ├── tokio-codec v0.1.1 (*)
│   │       ├── tokio-io v0.1.11 (*)
│   │       └── tokio-reactor v0.1.8 (*)
│   ├── tokio-signal v0.2.7
│   │   ├── tokio-executor v0.1.6 (*)
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-reactor v0.1.8 (*)
│   └── tokio-threadpool v0.1.11 (*)
│   ├── tokio v0.1.15 (*)
│   ├── tokio-executor v0.1.6 (*)
│   ├── tokio-io v0.1.11 (*)
│   ├── tokio-reactor v0.1.8 (*)
│   ├── tokio-tcp v0.1.3 (*)
│   ├── tokio-threadpool v0.1.11 (*)
│   ├── tokio-timer v0.2.9 (*)
│   │   │   ├── tokio-core v0.1.17
│   │   │   │   ├── tokio v0.1.15 (*)
│   │   │   │   ├── tokio-executor v0.1.6 (*)
│   │   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   │   ├── tokio-reactor v0.1.8 (*)
│   │   │   │   └── tokio-timer v0.2.9 (*)
│   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   ├── tokio-service v0.1.0
│   │   │   ├── tokio-core v0.1.17 (*)
│   │   │   ├── tokio-io v0.1.11 (*)
│   │   │   ├── tokio-service v0.1.0 (*)
│   │   │   └── tokio-tls v0.1.4
│   │   │       ├── tokio-core v0.1.17 (*)
│   │   │       └── tokio-io v0.1.11 (*)
│   │   ├── tokio-core v0.1.17 (*)
│   │   ├── tokio-io v0.1.11 (*)
│   │   ├── tokio-tls v0.1.4 (*)
├── tokio v0.1.15 (*)
├── tokio-core v0.1.17 (*)
├── tokio-io v0.1.11 (*)
├── tokio-timer v0.2.9 (*)
```

## Platform

Output of `uname -a`:

```
Darwin Sarfarazs-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

**Comment by tobz** [comment]
Your `tokio-core` example only runs the outer future, and the `tokio` example runs all futures on the runtime until they complete.

Basically, `core.run` is finishing before the inner spawned future completes, and thus it stops turning the runtime, so it never actually gets a chance to complete.

**Comment by snawaz** [comment]
> Your `tokio-core` example only explicitly waits for the outer future, and the `tokio` example waits for all futures on the runtime until they complete.
> 
> Basically, `core.run` is finishing before the inner spawned future completes, and thus it stops turning the runtime, so it never actually gets a chance to complete.

The documentation isn't clear about this behaviour. Thanks for pointing out that (my colleague has said the same thing). Now the next question: is there any way to make `tokio-core` to wait for all the  spawned futures to completion?

**Comment by tobz** [comment]
`tokio-core` is deprecated and isn't being actively developed; users are encouraged to move to `tokio`.

 If you can't move, you could possibly utilize a `futures::sync::oneshot` channel as a synchronization point: hand the sender part to your inner future, and only send to it when your work is actually done, and then the future you run could be a joined future, both the receiver + your `f` future.

**Comment by snawaz** [comment]
As the issue has been explained, I'm closing it.
