### ISSUE TITLE
Question about shutting down a runtime.

### ISSUE THREAD

**Issue by alex-ozdemir** [tokio-rs/tokio#885]
## Version

tokio = "0.1.14"

## Platform

Linux, 64bit, GCC

## Description

First off, thanks for making such a useful and powerful library! I'm not sure whether this is the right place to ask questions, but I can't think of a better one, so here goes...

**Is it possible for a spawned task to shutdown the whole runtime?**

E.g. I'm writing an application where there are many tasks doing different kinds of I/O. Some of the tasks might receive input that should lead to the application shutting down -- specifically to all tasks being terminated, and then having some shutdown code run. Being able to do the following two things would let me accomplish this:
1. Block on a runtime shutting down.
2. From a task, shutdown the current runtime.

Below is an (incomplete) example program showing what I'd like to do.

```
extern crate tokio;

use tokio::prelude::*;

use std::time::Duration;
use std::time::Instant;

fn main() {
    let kill_future = tokio::timer::Delay::new(Instant::now() + Duration::from_secs(3));

    let time_print_future = tokio::timer::Interval::new_interval(Duration::from_secs(1)).map(|t| println!("{:?}", t));

    let mut runtime = tokio::runtime::Runtime::new().expect("failed to start new Runtime");
    runtime.spawn(time_print_future.fold((), |(),()| Ok(())).map_err(|_| ()));
    runtime.spawn(kill_future.map_err(|_| {
        eprintln!("Timer error");
    }).map(move |()| {
        // TODO
        unimplemented!("Shutdown the runtime!");
    }));
    // TODO
    unimplemented!("Block until the runtime is shutdown");
    println!("Done");
}
```

Thanks for any assistance that you can provide!

**Comment by carllerche** [comment]
The best strategy is to use a oneshot (or some other primitive) to use as the signal to shut the runtime down.

```rust
let (tx, rx) = oneshot::channel();

runtime.spawn(foo.and_then(move |_| tx.send(()).unwrap()));

runtime.block_on(rx);
```

Let me know if this doesnt' work for some reason. I'm going to close the issue, but I will watch for a reply.
