### ISSUE TITLE
Refine `Executor` trait

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#887]
Consider refining the `Executor` trait in order to support more use cases.

## Background

This proposed change is driven in large part by #626. Tokio will incrementally move to have `tokio::spawn` always return a handle to the task that allows retrieving the task result. This is similar to how `thread::spawn()` returns `ThreadHandle` which allows obtaining the value v

Currently, the `Executor` trait requires spawned tasks to be defined as `Box<Future<Item = (), Error = ()>>`. In order to implement `SpawnHandle`, the task itself would need to allocate again internally to communicate the value from the task to the spawner. This could be done with a `oneshot` channel. However, the oneshot channel would add an extra allocation for each spawned task even if the spawner does not care about the result of the task.

The goal is to avoid having to allocate the `oneshot` per spawned task.

## Proposal

The `Executor` trait is altered to spawn with a "raw" task: `*mut RawTask`. This can be represented with a `Box` or an `Arc`.

```rust
trait Executor {
    fn spawn_raw(&mut self, task: *mut RawTask);
}

trait RawTask {
    fn poll(&self) -> Poll<(), ()>;

    unsafe fn drop_raw(&self);
}
```

`Executor` implementations will call `poll` as they do now, but it will require an `unsafe { }` block. When the executor is done with the task, `drop_fn` must be called explicitly. At this point, the pointer can no longer be de referenced.

A utility can be provided that takes a `*mut RawTask` and handles the unsafe logic. Something like:

```rust
pub struct TaskObj {
    ptr: *mut RawTask,
}

impl TaskObj {
    pub fn new(ptr: *mut RawTask) -> TaskObj {
        TaskObj { ptr }
    }

    pub fn poll(&mut self) -> Poll<(), ()> {
        unsafe { (*self.ptr).poll() }
    }
}

impl Drop for TaskObj {
    fn drop(&mut self) {
        unsafe { (*self.ptr).drop_fn() }
    }
}
```

Using this API, `spawn_handle<F: Future>(f: F) -> SpawnHandle` may be implemented by wrapping the future in a "oneshot" that is inlined in the future:

```rust
struct InlinedOneshot<T> {
    state: AtomicUsize,
    val: UnsafeCell<Option<T>>,
}

struct InnerTask<T: Future> {
    task: UnsafeCell<T>,
    oneshot: InlinedOneshot<Result<T::Item, T::Error>>,
}

struct SpawnHandle<T: Future> {
   inner: Arc<InnerTask<T>>,
}

impl<T: Future> RawTask for InnerTask<T> {
    fn poll(&self) -> Poll<(), ()> {
        let res = unsafe { (*self.task.get()).poll() };

        match res {
            Ok(Async::Ready(v)) => {
                self.oneshot.send(Ok(v));
                Ok(Async::Ready(()))
            }
            Ok(Async::NotReady) => Ok(Async::NotReady),
            Err(e) => {
                self.oneshot.send(Err(e));
                Ok(Async::Ready(()))
            }
        }
    }

    unsafe fn drop_raw(&self) {
        let _ = Arc::from_raw(self as *const _);
    }
}

fn spawn_handle<T: Future>(f: F) -> SpawnHandle<F> {
    let handle = SpawnHandle {
        inner: Arc::new(InnerTask {
            task: f,
            oneshot: InlinedOneshot::new(),
        }),
    };

    let ptr = Arc::into_raw(handle.inner.clone()) as *mut RawTask;

    DefaultExecutor::current().spawn_raw(ptr);

    handle
}
```

## Alternative

Two alternatives are to do nothing and to change `Executor` to spawn an `Arc<Future<...>>`.

In the "do nothing" case, implementing `spawn_handle` would require an unconditional allocation for the oneshot.

In the case of changing `Executor` to spawn `Arc<Future<...>>` values, this would add required atomic operations for all executors / tasks. That said, the additional atomic ops required by `Arc` are minimal compared to the work executors already perform.

**Comment by carllerche** [comment]
cc @jonhoo @tobz @stjepang

**Comment by jonhoo** [comment]
A couple of things jump out at me:

 - Why is `drop_raw` unsafe? As far as I can tell, it's turning the `*mut RawTask` into `&RawTask` in order to _call_ `drop_raw` that's the unsafe part?
 - The nested `Arc` in the example seems unfortunate.
 - It seems like "something" must tie together `impl Future` and `RawTask::poll` — what is that something?
 - What exactly are the invariants the different parts here must enforce for the `unsafe` calls to be safe? Specifically, it looks a little worrying for `poll` to get `&mut self` while the `RawTask` is _also_ available immutably through other pointers (the `Arc<InnerTask>` in the example).
 - I think, for clarity, it'd be good to flesh out the `impl Future` blocks for both `InnerTask` and `SharedTask` to show exactly how they interact.

**Comment by carllerche** [comment]
>  * Why is `drop_raw` unsafe? As far as I can tell, it's turning the `*mut RawTask` into `&RawTask` in order to _call_ `drop_raw` that's the unsafe part?

`draw_raw` is marked unsafe to copy [UnsafeWake](https://doc.rust-lang.org/nightly/std/task/trait.UnsafeWake.html#tymethod.drop_raw). There is another unsafe step after converting `*mut RawTask` to `&RawTask` in that once `drop_raw` is called, the `&RawTask` must not be used again. Given this, I think `unsafe` makes sense.

>   * The nested `Arc` in the example seems unfortunate.

What nested `Arc`?

>  * It seems like "something" must tie together `impl Future` and `RawTask::poll` — what is that something?

Not following? `RawTask::poll` could call whatever internally, including the Future's poll fn.

>   * What exactly are the invariants the different parts here must enforce for the `unsafe` calls to be safe? Specifically, it looks a little worrying for `poll` to get `&mut self` while the `RawTask` is _also_ available immutably through other pointers (the `Arc<InnerTask>` in the example).

Yeah... I think that `RawTask::poll` might have to take `&self`.

I can try to write up a more full example.

**Comment by carllerche** [comment]
@jonhoo I updated the example and changed `RawTask::poll` to take `&self`.

**Comment by jonhoo** [comment]
> What nested `Arc`?

Ignore me -- misread the code.

> Yeah... I think that `RawTask::poll` might have to take `&self`.

Yeah, that makes more sense to me. And I guess in the updated example, the argument for why
```rust
unsafe { (*self.task.get()).poll() };
```
is safe is that nowhere else in the code is anyone accessing `self.task`?

Separately, I think I'd like to see `self.oneshot.send(Ok(v));` expanded to just to make the example maximally explicit about things like notifications.

**Comment by carllerche** [comment]
> that nowhere else in the code is anyone accessing `self.task`?

Correct/

> Separately, I think I'd like to see `self.oneshot.send(Ok(v));` expanded to just to make the example maximally explicit about things like notifications.

@jonhoo the impl should pretty much be similar to the version of `oneshot` in [tokio-sync](https://github.com/tokio-rs/tokio/blob/master/tokio-sync/src/oneshot.rs#L46-L59). The implementation could be optimized once we migrate to `std::futures` (`spawn_raw` would probably return a `Waker`, in which case `tx_task` can be removed.

**Comment by stjepang** [comment]
> In the "do nothing" case, implementing `spawn_handle` would require an unconditional allocation for the oneshot.

I'm in the "do nothing" camp. Fretting over a few additional atomic operations feels like an unwarranted concern to me. Perhaps we should write a simple prototype and measure what's the real overhead of spawn handles?

**Comment by carllerche** [comment]
@stjepang the “do nothing” approach implies using a oneshot for all spawned tasks. So, even if the spawner does not care about the result of the task, the oneshot needs to be allocated. 

Unconditional spawning an Arc<SomeTrait> would be the option to avoid the allocation but always have atomic ops.

**Comment by seanmonstar** [comment]
I'm also *currently* in the "do nothing" camp. It looks like a messier API, but without knowing that the extra oneshot is too expensive, it feels like premature optimization. If we could see that the extra oneshot *is* too expensive, then I'd pack up my tent and move over.

**Comment by carllerche** [comment]
Here are some quick results:

```
test existing ... bench:      15,590 ns/iter (+/- 494)
test inline   ... bench:      15,525 ns/iter (+/- 749)
test oneshot  ... bench:      24,782 ns/iter (+/- 821)
```

Bench here: https://gist.github.com/carllerche/fa0f22b9da2a1a7f1d6c1eb1018bc381#file-spawn-bench-rs

This is obviously a very "micro" use case, but the impact is measurable. The question is, what is the threshold for "realistic".

cc/ @seanmonstar @stjepang

**Comment by carllerche** [comment]
My reason for considering this isn't even so much the performance gain, but it is more about flexibility. The `Executor` trait is pretty fundamental, so it should ideally not change much. An 0.2 release is coming up soon, so it would be nice to bundle up any changes then. Using a `RawTask` strategy has the most flexibility moving forwards.

If the hesitation is adding `unsafe` to the public API, that can be mitigated by providing `struct TaskObj` and using that instead.

```rust
trait Executor {
    fn spawn_obj(&mut self, task: TaskObj);
}

trait RawTask {
    fn poll(&self) -> Poll<(), ()>;

    unsafe fn drop_raw(&self);
}

pub struct TaskObj {
    ptr: *mut RawTask,
}

impl TaskObj {
    pub fn new(task: Box<Future<Item = (), Error = ()>>) -> TaskObj { ... }

    pub fn from_ptr(ptr: *mut RawTask) -> TaskObj {
        TaskObj { ptr }
    }

    pub fn poll(&mut self) -> Poll<(), ()> {
        unsafe { (*self.ptr).poll() }
    }
}

impl Drop for TaskObj {
    fn drop(&mut self) {
        unsafe { (*self.ptr).drop_fn() }
    }
}
```

**Comment by seanmonstar** [comment]
I'm all for preparing APIs to allow for forwards-compatibility with new things.

The benches suggest a oneshot is always created, even just to throw away. If the goal is to in fact make `spawn` *always* have a channel, then I suppose the change is helpful. An alternative is to only make a channel if the user wants one...

**Comment by carllerche** [comment]
@seanmonstar the goal is #626. Initially, the oneshot will only be required for `tokio::spawn_handle`, but in 0.2, I would like to make  it the default: `tokio::spawn<F: ...>(future: F) -> SpawnHandle<...>`. So, the oneshot would be created for *all* calls to `tokio::spawn`. This is why I am examining performance.

There will always be a way to spawn **without** the oneshot by calling the executor directly. But, my guess is *most* usage will end up being with the oneshot.

**Comment by carllerche** [comment]
The intent is to mirror `thread::spawn` a bit more as well as remove the very annoying and confusing requirement of futures passed to `tokio::spawn` having to be of type `Result<(), ()>` (or just `()` in 0.3).

**Comment by stjepang** [comment]
To clarify, I'm a proponent of the idea that `spawn` should return something akin to `JoinHandle` (and that should be the default, agree on that) and feel that we can implement spawn handles with effectively negligible overhead.

What I felt unsure about were the alterations of the `Executor` trait - in particular, the signature of `spawn_raw`, as well as `RawTask` and `TaskObj`. I hoped we might be able to avoid them altogether but now I see we really need those. :) After some thinking, it makes a lot of sense now. I'd be happy with these refinements 👍
