### ISSUE TITLE
trace: ValueSets should indicate if they are complete

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#902]
## Subcrates

tokio-trace-core

## Description

Currently, the `field::ValueSet` type in `tokio_trace_core` exposes an `is_empty` method, which returns true if there are no field values contained in that `ValueSet`. However, there is currently no way for a subscriber to know whether a `ValueSet` contains values for _all_ the fields defined on that span.

### Solution
I originally proposed a `ValueSet::is_complete` method, which would return true if all the field values on the span are provided. However, it was [removed](https://github.com/tokio-rs/tokio/commit/7835bcbc3917afc684df7be7cfb4c6a16b1f4a9a#diff-67b64ce5b8dc4147ad948a3f0c87e504) based on feedback by @carllerche. I think a similar method should be reintroduced.

### Rationale

There is a convincing use case for providing such a method: if a subscriber wishes to cache formatted trace contexts, it needs to be able to determine if all of the fields on the spans in that contexts have already been recorded. Otherwise, a span may record additional fields and the cached context will become invalid. If a span was created with a complete `ValueSet`, its formatted fields may be cached safely. I've experimented with this kind of caching in a subscriber implementation and found that it can significantly improve subscriber performance.

### Alternatives
Subscribers _can_ determine span completeness themselves by recording `ValueSet`s with a `Record` implementation that tracks which fields have been recorded. However, this adds a lot of complexity to `Record` implementations. The `ValueSet` itself can determine whether or not it is complete much more easily.

**Comment by carllerche** [comment]
Could you clarify the rationale?

There is a separate, but related, question: Can the same field be recorded multiple times for a single span?

**Comment by hawkw** [comment]
@carllerche upon giving it some additional thought, I think it's probably inappropriate for `ValueSet` to have this method. The behaviour around recording the same field multiple times is up to the `Subscriber` implementation, so I think any notion of span "completeness" has different semantics depending on the subscriber.

Also, something like this is actually quite easy to implement on the subscriber-side, now that I've tried it.
