### ISSUE TITLE
trace: Allow Span IDs to be converted back to u64s

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#905]
## Subcrates

tokio-trace-core

## Description

Currently, the `tokio_trace_core::Span` type is constructed by a public `Span::from_u64` function. Subscribers are expected to provide `u64` span IDs to this constructor. However, once a `Span` has been constructed, the `u64` value can only be accessed from inside of `tokio_trace_core`, leaving subscribers no way to get the numeric value back _out_ of a `Span`. 

I propose adding a `Span::as_u64` method that returns the inner `u64` span ID.

### Rationale

The existence of the `Subscriber::clone_span` and `Subscriber::drop_span` functions imply that subscribers are permitted to store data of their choosing in span IDs (see also https://github.com/hawkw/tokio-trace-prototype/issues/80, where @carllerche suggests that they could be used to store pointers). For example, I've [implemented a subscriber that stores span data in a slab](https://github.com/tokio-rs/tokio-trace-nursery/blob/f30a14aee6c56df7a31767e5632b1d56f1f3bdb7/tokio-trace-fmt/src/span.rs#L182-L259), and [assigns span IDs based on indices into the slab](https://github.com/tokio-rs/tokio-trace-nursery/blob/f30a14aee6c56df7a31767e5632b1d56f1f3bdb7/tokio-trace-fmt/src/span.rs#L223-L225). This allows span data to be retrieved by indexing the slab with a `Span` ID.

Since there isn't currently a function to convert a `Span` back into a `u64`, this subscriber implementation is forced to [use `mem::transmute`](https://github.com/tokio-rs/tokio-trace-nursery/blob/f30a14aee6c56df7a31767e5632b1d56f1f3bdb7/tokio-trace-fmt/src/span.rs#L192-L195) to convert a `Span` into a `usize` that can be used to index the slab. While this _works_, it's quite unfortunate, as it relies on the layout of the `Span` type always being identical to a `u64`. 

My understanding is that the primary motivation for not providing a function to convert `Span`s into `u64`s is primarily for forward compatibility. However, a purely internal change could break the use of `mem::transmute`, if the layout of a `Span` changes in any way. Thus, this is even _less_ forward-compatible than an API which provides a `Span::to_u64` function...

**Comment by carllerche** [comment]
I think this is fine to do.
