### ISSUE TITLE
Can't install tokio async await ( LocalWaker )

### ISSUE THREAD

**Issue by victordetarragon** [tokio-rs/tokio#908]
## Version
Following this page and from a new cargo init : 
https://github.com/tokio-rs/tokio/tree/master/tokio-async-await

testing_tokio v0.1.0 (/root/testing_tokio)
└── tokio v0.1.15
    ├── tokio-async-await v0.1.5
    │   └── tokio-io v0.1.11
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.11 (*)
    ├── tokio-current-thread v0.1.4
    │   └── tokio-executor v0.1.6
    ├── tokio-executor v0.1.6 (*)
    ├── tokio-fs v0.1.5
    │   ├── tokio-io v0.1.11 (*)
    │   └── tokio-threadpool v0.1.11
    │       └── tokio-executor v0.1.6 (*)
    │   └── tokio-io v0.1.11 (*)
    ├── tokio-io v0.1.11 (*)
    ├── tokio-reactor v0.1.8
    │   ├── tokio-executor v0.1.6 (*)
    │   └── tokio-io v0.1.11 (*)
    ├── tokio-sync v0.1.1
    ├── tokio-tcp v0.1.3
    │   ├── tokio-io v0.1.11 (*)
    │   └── tokio-reactor v0.1.8 (*)
    ├── tokio-threadpool v0.1.11 (*)
    ├── tokio-timer v0.2.10
    │   └── tokio-executor v0.1.6 (*)
    ├── tokio-udp v0.1.3
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.11 (*)
    │   └── tokio-reactor v0.1.8 (*)
    └── tokio-uds v0.2.5
        ├── tokio-codec v0.1.1 (*)
        ├── tokio-io v0.1.11 (*)
        └── tokio-reactor v0.1.8 (*)

## Platform

Linux 4.13.0-kali1-amd64 #1 SMP Debian 4.13.10-1kali2 (2017-11-08) x86_64 GNU/Linux

## Description

I am simply following the exemple. Nothing more. And I have the following issue during the build : 

`   Compiling tokio-async-await v0.1.5
error[E0432]: unresolved import `std::task::LocalWaker`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-async-await-0.1.5/src/compat/forward.rs:7:17
  |
7 | use std::task::{LocalWaker, Poll as StdPoll};
  |                 ^^^^^^^^^^ no `LocalWaker` in `task`
`
Seems to be relate with Future issue about LocalWaker ...
Thank you.

**Comment by chocol4te** [comment]
`LocalWaker` was removed in PR https://github.com/rust-lang/rust/pull/57992, as discussed in https://github.com/rust-lang/rfcs/pull/2592.

**Comment by victordetarragon** [comment]
Exact so I presume Async Await is dead for the moment ? Do you have a work around ?

**Comment by chocol4te** [comment]
The workaround will be to use an older nightly. We'll need to discuss with `tokio-rs` members as to what to do.

**Comment by dvc94ch** [comment]
Using an older nightly breaks other crates. As a work around you can do this:
```rust
#![features(async_await, await_macro, futures_api)]
use futures::future::FutureObj;
use futures::prelude::*;

fn main() {
  tokio::run(FutureObj::new(Box::new(async move {
    println!("running");
    tokio::spawn(FutureObj::new(Box::new(async move {
       println!("spawned");
    })).compat());
  })).compat());
}
```

**Comment by victordetarragon** [comment]
Thank you David for the work around. The issue is I can't even build. Do you have a specific .toml according to it ?

@taiki-e  seems to be the Real MVP here. I hope your PR will be accepted !

Thanks everyone for your help in this issue.

**Comment by dvc94ch** [comment]
@victordetarragon `tokio-async-await` provides a `tokio::run_async` and `tokio::spawn_async` which take v3 Futures. By using the compat traits from `futures-preview` you can roll your own until it builds again. I updated the comment with a `Cargo.toml` and verified that the code example runs as is.

**Comment by carllerche** [comment]
Pushed out a release w/ the fix. Thanks @taiki-e
