### ISSUE TITLE
blocking + timeout = hang

### ISSUE THREAD

**Issue by quininer** [tokio-rs/tokio#931]
## Version

```
├── tokio v0.1.15
│   ├── tokio-codec v0.1.1
│   │   └── tokio-io v0.1.11
│   ├── tokio-current-thread v0.1.4
│   │   └── tokio-executor v0.1.6
│   ├── tokio-executor v0.1.6 (*)
│   ├── tokio-fs v0.1.5
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-threadpool v0.1.11
│   │       └── tokio-executor v0.1.6 (*)
│   │   └── tokio-io v0.1.11 (*)
│   ├── tokio-io v0.1.11 (*)
│   ├── tokio-reactor v0.1.8
│   │   ├── tokio-executor v0.1.6 (*)
│   │   └── tokio-io v0.1.11 (*)
│   ├── tokio-sync v0.1.2
│   ├── tokio-tcp v0.1.3
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-reactor v0.1.8 (*)
│   ├── tokio-threadpool v0.1.11 (*)
│   ├── tokio-timer v0.2.10
│   │   └── tokio-executor v0.1.6 (*)
│   ├── tokio-udp v0.1.3
│   │   ├── tokio-codec v0.1.1 (*)
│   │   ├── tokio-io v0.1.11 (*)
│   │   └── tokio-reactor v0.1.8 (*)
│   └── tokio-uds v0.2.5
│       ├── tokio-codec v0.1.1 (*)
│       ├── tokio-io v0.1.11 (*)
│       └── tokio-reactor v0.1.8 (*)
└── tokio-threadpool v0.1.11 (*)
```

## Platform

Linux btw 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64 GNU/Linux

## Subcrates

tokio-threadpool

## Description

Unable to release blocking thread when a timeout occurs.

https://gist.github.com/quininer/691caf86ec734dadc9d8590893825284

Note that this happens in hyper [TokioThreadpoolGaiResolver](https://github.com/hyperium/hyper/blob/master/src/client/connect/dns.rs#L331) @seanmonstar  , which causes dns response to never return.

**Comment by quininer** [comment]
Duplicate of #726 . :(

**Comment by carllerche** [comment]
This is kind of expected... a blocking call (right now at least) cannot be interrupted. You set the max number of blocking threads to 10, so you can get 10 concurrent sleeps. Could you clarify what you would expect would happen in this case?

**Comment by quininer** [comment]
You are right... I misunderstood what happened, the blocking behind was never executed because it was canceled by timeout and not because of `NoCapacity`.

I think I encountered the same problem with #726  on `tokio-threadpool 0.1.11`.
