### ISSUE TITLE
trace: Consider supporting 128-bit field values

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#932]
## Subcrates

tokio-trace-core

## Problem

In distributed tracing systems such as [OpenCensus] and [OpenTracing], trace IDs are specified as 128-byte integers. `tokio-trace`'s `Value` system currently [represents integer values as 64-bit]. This could make it difficult to implement subscribers that integrate with these distributed tracing systems if propagating these trace IDs as fields on `tokio-trace` spans is required.

Furthermore, it seems like a potential limitation if the value system is not capable of recording the largest integer primitive that Rust supports without truncating.

## Solution

I propose we add a `Record::record_u128` function to the `Record` trait, and an impl of `Value` for `u128`. Since the [`u128` primitive type] has been stable since Rust 1.26.0 (the minimum supported version), this should be fine. We may also want to add a `Record::record_i128` function at the same time.

It's probably a good idea to add this to `Record` prior to releasing `tokio-trace-core` 0.1. While this isn't a breaking change, minimizing version churn in `tokio-trace-core` is important as all libraries emitting trace data in a crate will need to be on the same version of `core`.

## Alternatives

There are a few other approaches that could be used to track 128-bit trace IDs from systems like OpenTracing:
+ **Make `Span` IDs 128 bits**: this is probably not the right choice. In my opinion, it is unlikely that `tokio-trace`'s span IDs will correspond directly to span IDs in a distributed tracing system --- the intention is that subscribers be free to store information internal to the implementation (such as slab indices or memory locations) in span IDs, and they may be reused within the context of the process. Furthermore, in both OpenCensus and OpenTracing, while _trace_ IDs (which identify an entire trace tree) are 128-bits _span_ IDs are 64-bits (as they are only guaranteed to be unique within the trace). So, if a subscriber _were_ to issue tokio-trace `Span` IDs based on span IDs in a distributed tracing system, it wouldn't use all 128 bits for span IDs, and would still need a way to annotate spans with 128-bit trace IDs.
+ **Store the trace ID as a string**: Users could simply format the 128-bit number as a string and store _that_ as a field, and the subscriber could parse the string when the numeric value is needed. The string allocation implied, as well as the overhead of formatting and parsing, seems unfortunate.
+ **Store the high-order and low-order halves of the trace ID as `u64`s** Users could do something like this:
   ```rust
    let lo = (trace_id & 0xFFFF_FFFF_FFFF_FFFF) as u64;
    let hi = (trace_id >> 64) as u64;
    span!("foo", trace_id_hi = hi, trace_id_lo= lo, ...)
   ```
   and the subscriber could reconstruct the ID from the two halves. This is kind of gross and requires an unfortunate amount of work at the callsite.
+ **Subscribers could provide an "out of band" method**: Subscribers integrating with distributed tracing systems could always provide an "out of band" method for associating IDs in the distributed tracing system with `tokio-trace` spans. For example,
   ```rust
    let span = span!("foo", ...);
    tokio_trace_opencensus::correlate_span_with_trace(span.id(), trace_id);
   ``` 
   This is less ugly at the callsite than the other approaches, but requires a lot of work on the part of the subscriber implementation.

In my opinion, these alternatives all add much more unnecessary complexity than adding a 128-bit value type.

[OpenCensus]: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Span.md#span-structure
[OpenTracing]: https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md#trace-context-http-headers
[represents integer values as 64-bit]: https://github.com/tokio-rs/tokio/blob/dbb04e310c061612a1bc585776c23400299e7ad0/tokio-trace/tokio-trace-core/src/field.rs#L180-L188
[`u128` primitive type]: https://doc.rust-lang.org/std/primitive.u128.html

**Comment by carllerche** [comment]
My initial gut is that, in this case, the trace ID should be stored as a string or tracked with an "out of band" method.

We may want to have conventional key names...

**Comment by hawkw** [comment]
@carllerche WRT an "out of band" API, I'm open to that being the right approach; my main concern is that it could require threading a handle to the subscriber through app code to the point where a span is correlated with a distributed tracing span; I'm not sure how bad this would be in practice.

**Comment by carllerche** [comment]
@hawkw Alternatively, there can be an API to get the current subscriber and you downcast. We should make sure that the API enables this.

**Comment by hawkw** [comment]
@carllerche 👍 that sounds like the right approach to me --- I've opened #950 to add downcasting support to `Dispatch`.
