### ISSUE TITLE
Edition error while trying to compile with async_await 

### ISSUE THREAD

**Issue by ayax79** [tokio-rs/tokio#936]
I am receiving an the following error edition while trying to compile with async_await even when edition is set to 2018:
```
error[E0670]: `async fn` is not permitted in the 2015 edition
 --> /Users/awri10/NikeDev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/src/async_await.rs:3:1
  |
3 | async fn map_ok<T: StdFuture>(future: T) -> Result<(), ()> {
  | ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0670`.
error: Could not compile `tokio`.

To learn more, run the command again with --verbose.
 awri10@AP6MJG5J85194C  ~/NikeDev/src/rust/async-await-test #  
```

I am compiling with the following:
```
cargo clean && cargo +nightly build
```

My Cargo.toml is as follows (to show that I do have the edition correctly set):
```
[package]
name = "async-await-test"
version = "0.1.0"
authors = ["Jack Wright <jack.wright@nike.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.1.15", features = ["async-await-preview"] }
tokio-process = "0.2.3"
```

The entire source can be viewed at: https://github.com/ayax79/async-await-test

```
rustc -Vv                                                                                                    ``
rustc 1.34.0-nightly (350674b71 2019-02-28)
binary: rustc
commit-hash: 350674b7180a41c8e508d93c6ab8e203b69d3df7
commit-date: 2019-02-28
host: x86_64-apple-darwin
release: 1.34.0-nightly
LLVM version: 8.0
```

Any help would be greatly appreciated.

**Comment by carllerche** [comment]
Thanks for the report. This is already tracked by #935

Until a fix is provided, I would recommend pinning the nightly you use. You can find a version that is known to work [here](https://github.com/tokio-rs/tokio/blob/master/azure-pipelines.yml#L75).

**Comment by ayax79** [comment]
Thanks for the info @carllerche! I'll give that a try.

**Comment by woody77** [comment]
For 1.1.16 to compile it needs to be pinned to nightly-2019-02-26:

```
$ rustc -Vv
rustc 1.34.0-nightly (00aae71f5 2019-02-25)
binary: rustc
commit-hash: 00aae71f503b1ab592f48de47dd30912f3858748
commit-date: 2019-02-25
host: x86_64-unknown-linux-gnu
release: 1.34.0-nightly
LLVM version: 8.0
```

**Comment by abelsromero** [comment]
I am experiencing the same error with the hello-world example using `1.42.0-nightly` with version "2.0.0" on MacOS.

**Comment by mhconradt** [comment]
I get this message with 1.42.0-nightly (689fca01c 2020-01-17).

**Comment by carllerche** [comment]
@abelsromero there is no "2.0" version. Do you mean 0.2? That should not be happening, we would need a repro.

**Comment by nanofaroque** [comment]
I am having the same issue: 
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-apple-darwin
release: 1.43.0
LLVM version: 9.0
```

Was there any solution?

**Comment by Darksonn** [comment]
@nanofaroque If you are getting errors about using the 2015 edition, you will have to change your project to the 2018 edition.
