### ISSUE TITLE
Could not compile `tokio 0.1.16`

### ISSUE THREAD

**Issue by nanpuyue** [tokio-rs/tokio#943]
## Version

tokio 0.1.16
tokio-fs 0.1.5
tokio-sync 0.1.2

## Description

`tokio 0.1.16` depends on `tokio-fs 0.1.6` & `tokio-sync 0.1.3`, but in the Cargo.toml their versions are `0.1.3` & `0.1.0` respectively.

So I may receive the following error:
![20190304122402](https://user-images.githubusercontent.com/1524609/53710482-6996d100-3e78-11e9-978d-0294ccc3edcb.png)

Then I know `cargo update` can fix it.

**Comment by carllerche** [comment]
Yeah, I assume `cargo update` fixed it?

**Comment by nanpuyue** [comment]
Yes. but this is still a problem.

**Comment by carllerche** [comment]
Are you able to submit a PR?

**Comment by nanpuyue** [comment]
Done.
But I'm not sure if there are other ependencies that need to be upgraded. It would be best if there was an automated detection mechanism.

**Comment by DoumanAsh** [comment]
I don't think it is feasible since there are potentially lots of version combinations.
The best would be if rust/cargo would have mechanism to mark public API with versions that could be tracked by itself or 3pp tools

**Comment by jonasbb** [comment]
I hit the same problem today. Cargo already provides an (unstable) way to detect those problems. You can use [`-Z minmal-versions`](https://doc.rust-lang.org/cargo/reference/unstable.html#minimal-versions) while generating the lock file. It might make sense to add this to the CI setup to detect at least some of the more common version incompatabilities.
