### ISSUE TITLE
trace: Runtime should automatically propagate subscriber context

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#947]
## Subcrates

`tokio`, `tokio-trace`

### Problem

One of the biggest pain points in the current `tokio-trace` API is that the subscriber context must be propagated manually. For example, if a user `tokio::spawn`s a future, the spawning thread's subscriber will not be propagated to the worker thread the spawned future actually executes on. 

Users can currently get around this one of two ways:
- Instrument the future with a span:
  ```rust
   use tokio_trace_futures::Instrument;

   let fut = do_stuff()
       .instrument(span!("do stuff"));
   tokio::spawn(Box::new(fut));
  ```
   Since entering a span sets the dispatcher to that span's dispatcher while inside the span, this will both propagate the dispatcher context and create a span for the future. However, if the span is disabled, then the dispatcher will not be set, which can lead to surprising and unexpected behavior.
- Explicitly attach a subscriber context to the future:
   ```rust
   use tokio_trace_futures::WithSubscriber;
   let dispatch = tokio_trace::dispatcher::with(|current| current.clone());

   let fut = do_stuff()
       .instrument(span!("do stuff")) // optionally
       .with_subscriber(dispatch);
   tokio::spawn(Box::new(fut));
   ```
   This will work regardless of whether or not the future is instrumented with a span, and regardless of whether or not any spans are enabled. However, it requires some extra noise and is perhaps non-obvious.

Additionally, the following issues apply to both of these approaches:
  - They both require the `tokio-trace-futures` crate, which is in the nursery and thus less stable than the core `tokio-trace` crates.
  - If library code also uses `tokio::spawn` or similar functions (a reasonably common pattern!) there is nothing that user code can do to ensure that futures spawned by libraries also propagate the subscriber context correctly.

### Solution

Other tokio crates use a similar pattern to `tokio-trace-core`'s `dispatcher::with_default`: `tokio-reactor` [has a `with_default`](https://docs.rs/tokio-reactor/0.1.9/tokio_reactor/fn.with_default.html), and `tokio-timer` [has](https://docs.rs/tokio-timer/0.2.10/tokio_timer/fn.with_default.html) [two](https://docs.rs/tokio-timer/0.2.10/tokio_timer/clock/fn.with_default.html). The threadpool `Runtime` currently uses the `tokio_threadpool::Builder::around_worker` function to ensure that the default reactor, timer, and clock contexts are all set for each worker thread:
https://github.com/tokio-rs/tokio/blob/e28856cffe00aa3f0c30292a91e36adab422668c/src/runtime/threadpool/builder.rs#L334-L344
We could add a similar call to `tokio_trace_core::dispatcher::with_default` here as well. 

A `subscriber` function could be added to the runtime builder to allow setting the default subscriber for the runtime, and `tokio::run` would probably set the current dispatcher. This would basically make everything just work out of the box.

The one major disadvantage to this approach is that it would require `tokio` to depend on `tokio-trace-core`. Since a crate published to crates.io may only depend on other published crates, this would require a crates.io release of `tokio-trace-core`. Thus, this is blocked on a stable `core` API.

### Alternatives

One potential alternative that _doesn't_ require an immediate release of `tokio-trace-core` is to add a function to the `runtime::Builder` API that allows additional functions to be added to the `around_worker` call. If it was possible to wrap functions called in `around_worker` with an additional closure, a third-party crate could provide an API that wraps a `runtime::Builder` and allows a `tokio_trace` subscriber to be added, without requiring `tokio` to depend on `tokio-trace`. 

However, this adds a new public API function to `runtime::Builder`, so it would require some thought to ensure it could be implemented in a way that would be stable and has little potential for misuse. It's possible that this functionality isn't something that should be exposed to users of the `Runtime` at all...

**Comment by carllerche** [comment]
All the tokio should depend on `tokio-trace-core`.

This should initially be done without a guarantee of backwards compatibility. Tokio should be able to update its dependency from `tokio-trace-core` 0.1 -> 0.2 without issuing a breaking release of the existing crates.

For this to work, no existing crate can include `tokio-trace-core` in its public API. Users should also explicitly opt-in to tokio-trace in an experimental capacity. The worst thing that should happen is any registered subscriber could stop receiving events.

**Comment by LucioFranco** [comment]
@hawkw thanks for writing this up! I think it makes more sense to wait for a stable core then add it as apart of the runtime builder. I personally can live without it for the moment, _I think none of my libraries use `tokio::spawn`_ so I should be safe. That said, the alternative solution might be a net positive for other use cases in which you would like to hook into the runtime, so maybe its worth investigating that?
