### ISSUE TITLE
trace-core: API stability/forward-compat pass

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#948]
Before doing an 0.1 release of `tokio-trace-core` on crates.io, we should give the API a thorough pass to find any remaining forwards-compatibility/stability hazards, and to ensure there are no additional API changes that we need to make before a release. This is a tracking issue for that work.

**Comment by hawkw** [comment]
Some things to address:
 - Consider make `Subscriber` API methods take an "arguments struct" to allow us to add more arguments without breaking method signatures (see also https://github.com/tokio-rs/tokio/issues/920#issuecomment-466512955)
- Consider requiring `Span`s to have `'static` metadata (removes the lifetime parameter on the `Span` type).
    * I've reconsidered my opinion on this since spans and events are now distinct (events must have generic lifetimes for their metadata for `log` compat reasons); in practice spans will always be `'static`.
- Should there be an API call to invalidate and rebuild the entire callsite registry?

**Comment by hawkw** [comment]
@carllerche since you asked about the point above that 
> events must have generic lifetimes for their metadata for `log` compat reasons); in practice spans will always be `'static`

The last time we discussed this was here: https://github.com/tokio-rs/tokio/pull/827#discussion_r247689183. This was when events and spans were backed by the same internal representation; in #880 they became wholly distinct. 

The reason that `Event` metadata has a generic lifetime is because I want it to be possible to construct an `Event` from a `log::Record`, which is generic over a lifetime for the target, module path, et cetera. However, there's no such restriction on `Span`s, which I expect to always be constructed from a `tokio-trace` `Callsite`. Since callsites have to be `'static` to be registered, I think it's reasonable to expect that span metadata be static as well. Given that, I've changed my mind about my earlier statement that a generic `Span` lifetime results in a more flexible API --- I think it just adds unnecessary complexity. 

Also, since spans interact with subscribers through span IDs rather than with the `Span` type, it's certainly still possible to build a completely alternative span representation which does have non-static metadata. And, since the `Span` type is in `tokio-trace` rather than `tokio-trace-core`, a breaking change in the future to add the generic lifetime parameter back would not be quite as painful as a change in `-core`.

**Comment by carllerche** [comment]
It looks like events have call sites, which mean that they have a static component and fields.

I'm wondering if events generated from `log::Record` should have static `Metadata`, but expose its data as field values, which don't have to be static.
