### ISSUE TITLE
tokio-fs: suggestion: could expose async wrappers for `Write` and `Read` types

### ISSUE THREAD

**Issue by dnaq** [tokio-rs/tokio#951]
## Version
└── tokio v0.1.16
    ├── tokio-codec v0.1.1
    │   └── tokio-io v0.1.12
    ├── tokio-current-thread v0.1.5
    │   └── tokio-executor v0.1.6
    ├── tokio-executor v0.1.6 (*)
    ├── tokio-fs v0.1.6
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-threadpool v0.1.12
    │       └── tokio-executor v0.1.6 (*)
    │   └── tokio-io v0.1.12 (*)
    ├── tokio-io v0.1.12 (*)
    ├── tokio-reactor v0.1.9
    │   ├── tokio-executor v0.1.6 (*)
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-sync v0.1.3
    ├── tokio-sync v0.1.3 (*)
    ├── tokio-tcp v0.1.3
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-reactor v0.1.9 (*)
    ├── tokio-threadpool v0.1.12 (*)
    ├── tokio-timer v0.2.10
    │   └── tokio-executor v0.1.6 (*)
    ├── tokio-udp v0.1.3
    │   ├── tokio-codec v0.1.1 (*)
    │   ├── tokio-io v0.1.12 (*)
    │   └── tokio-reactor v0.1.9 (*)
    └── tokio-uds v0.2.5
        ├── tokio-codec v0.1.1 (*)
        ├── tokio-io v0.1.12 (*)
        └── tokio-reactor v0.1.9 (*)
## Platform
Linux nixos 4.14.103 #1-NixOS SMP Sat Feb 23 08:06:44 UTC 2019 x86_64 GNU/Linux
## Subcrates
tokio-fs
## Description

The definition of `tokio::fs::File` is currently a wrapper for a `StdFile`. This wrapper can be generalized quite easily to implement `AsyncRead` for any type implementing `Read` and `AsyncWrite` for any type implementing `Write` without any code changes.

My suggestion is to expose some kind of `struct AsyncWrapper<T> { inner: Option<T> }` from tokio-fs and to have trait implementations such as:
```
impl<T> Read for AsyncWrapper<T> where T: Read {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        ::would_block(|| self.inner.read(buf))
    }
}

impl<T> AsyncRead for AsyncWrapper<T> where T: Read {
...
}
```
and correspondingly for `Write`. This allows a user to easily make any `Read` or `Write` type into one that can be used in asynchronous code.

The only thing missing would be helpers to actually create the actual `Read` or `Write` types, since the creation of those could also be blocking. For that reason it might be nice to expose the `would_block`, `blocking_io` and similar functions together with documentation on how to use them to create your own `OpenFuture`-like types.

**Comment by stjepang** [comment]
@carllerche Why do we implement `Read` and `Write` traits for `tokio_fs::File` anyway? Shouldn't we only implement `AsyncRead` and `AsyncWrite`?

**Comment by dnaq** [comment]
@stjepang Unfortunately the `AsyncRead` trait is defined as `pub trait AsyncRead: Read` in tokio, and the implementations in `tokio-fs` all defer to the methods from `read`. This has been fixed in `futures-0.3`, so it won't be an issue when tokio switches over to the new futures.

**Comment by Darksonn** [comment]
Is this still something we want?

**Comment by Darksonn** [comment]
Making the wrapper we already have for file system operations public would probably be a reasonable idea.

**Comment by jefftt** [comment]
hi, i'd like to give this a shot but am new to the project and not sure what exactly is needed to resolve this. is it just making the methods for the impl `AsyncWrite`,`AsyncRead`,`AsyncSeek` `for File` pub?

**Comment by Darksonn** [comment]
Hmm, I'm pretty sure that logic was previously in its own type — that's the wrapper I was talking about. Unfortunately it seems that this is not the case anymore, so it's probably not as easy a change as I predicted. 

It would involve making a public type with similar impls to what `File` has now, and making `File` just use that wrapper. 

If you are still interested in doing this, or perhaps one of our other issues, the Discord channel linked in our readme should be a good place to ask for help if you run into any issues.

**Comment by barafael** [comment]
can this be closed?
