### ISSUE TITLE
`addr` argument documention on `TcpListener::from_std`  is outdated

### ISSUE THREAD

**Issue by vandenoever** [tokio-rs/tokio#956]
## Version

tokio 0.1.16, tokio-tcp 0.1.3

## Platform

Linux

## Subcrates

tokio-tcp

## Description

The documentation of `TcpListener::from_std` explains the `addr` argument. There is no `addr` argument.

The function `TcpListener::from_listener` did have a `addr` argument. The function was renamed to `TcpListener::from_std` and later the `addr` argument was removed in 117dcba8cbff8fc5b688865360eb2c04277b09eb.

It is now unclear how to set the address when creating a `TcpListener` from a `net2::TcpListener` while retaining the socket address.
/

**Comment by tobz** [comment]
So, two separate things:

- Good catch on the documentation being misleading!
- Here's an example of using `net2::TcpBuilder` with tokio: https://github.com/nuclearfurnace/synchrotron/blob/master/src/listener.rs#L253

I'm not sure we really want to add any `net2`-specific stuff to the documentation, but we can definitely drop the bit about `addr` to remove confusion.

**Comment by vandenoever** [comment]
Sound good to me. I'm in the process of porting a hyper 0.11 project to 0.12 and switched it to using hyper::Server. No idea if this will work since porting is not finished yet. If required functionality from 0.11 got lost in 0.12, I'll open an issue for that separately.

**Comment by carllerche** [comment]
Fixed in 0.2.
