### ISSUE TITLE
trace: Static level filtering

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tokio#959]
## Subcrates

`tokio-trace`

## Description

`tokio-trace` should have static verbosity level filtering, [like the `log` crate](https://docs.rs/log/0.4.6/log/#compile-time-filters). The static max verbosity level should be controlled at compile time with a set of features. It should be possible to set a separate max level for release and debug mode builds. 

We can do this fairly similarly to how the `log` crate does it: `tokio-trace` should export [a constant whose value is set based on the static max level feature flags](https://github.com/rust-lang-nursery/log/blob/7d7daf6258fa33853e142d53892aff21ecdc0122/src/lib.rs#L1262-L1299). Then, we can add an `if` statement to the `span!` and `event!` macros, like 

```rust
macro_rules! event {
    (target: $target:expr, $lvl:expr, { $( $k:ident = $val:expr ),* $(,)*} )=> ({
        if $lvl <= $crate::STATIC_MAX_LEVEL {
            #[allow(unused_imports)]
            use $crate::{callsite, dispatcher, Event, field::{Value, ValueSet}};
            use $crate::callsite::Callsite;
            let callsite = callsite! {
                name: concat!("event ", file!(), ":", line!()),
                target: $target,
                level: $lvl,
                fields: $( $k ),*
            };
            if is_enabled!(callsite) {
                let meta = callsite.metadata();
                Event::observe(meta, &valueset!(meta.fields(), $( $k = $val),* ));
            }
        }
    });
    
    // ...
}
```

The `log` crate also [has some tests for this](https://github.com/rust-lang-nursery/log/tree/master/test_max_level_features), which would be nice to have as well.

Closes tokio-rs/tokio-trace-nursery#12.

**Comment by hawkw** [comment]
See also https://github.com/tokio-rs/tokio/issues/952#issuecomment-470311779.

**Comment by hawkw** [comment]
FWIW, if anyone wants to implement this, I'm happy to provide guidance/mentoring.

**Comment by phungleson** [comment]
@hawkw Hey mate I am keen to pick this up and started a PR here https://github.com/tokio-rs/tokio/pull/987

Let me know if it is ok, and how should I proceed further? Feedbacks are welcome, thanks!
