### ISSUE TITLE
trace-core: misc API thoughts

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#960]
`tokio_trace_core::dispatcher::{with, with_dispatch}` is confusing.

They are very similar names but do opposite things. Not saying `with_dispatch` is a great pattern, but it is what we do. I would recommend coming up with a completely different name for `with`.

`tokio_trace_core::event::Event::observe`: Maybe name this `dispatch`? It wasn't obvious what the fn was as I browsed the docs.

I think `tokio_trace_core::field::ValidLen` should be private (the trait itself should be a "pub trait in priv mod).

Do `tokio_trace_core::field::{debug, display}`  need to be in `tokio-trace-core` or can they be in `tokio-trace`?

**Comment by hawkw** [comment]
> `tokio_trace_core::dispatcher::{with, with_dispatch}` is confusing.
> 
> They are very similar names but do opposite things. Not saying `with_dispatch` is a great pattern, but it is what we do. I would recommend coming up with a completely different name for `with`.

Yeah, I don't care for the naming here at all. As we discussed offline, I think we ought to keep `with_default` (for consistency w/ the other crates) and rename `with` to `get_default` --- I don't really like `get_` for a function that takes a closure, but I really can't think of a better option.

> `tokio_trace_core::event::Event::observe`: Maybe name this `dispatch`? It wasn't obvious what the fn was as I browsed the docs.

I'm fine with `dispatch` but I personally find it _less_ clear. What about `record`? Admittedly we've overloaded `record` a lot.

> I think `tokio_trace_core::field::ValidLen` should be private (the trait itself should be a "pub trait in priv mod).

`ValidLen` is part of a public method's signature (`FieldSet::value_set`) so I thought it had to be public? The trait is sealed...

> Do `tokio_trace_core::field::{debug, display}` need to be in `tokio-trace-core` or can they be in `tokio-trace`?

They have to be in `tokio-trace-core`, as their entire purpose is to implement `Value`, and `Value` is currently sealed. If we unsealed `Value`, they could move to `tokio-trace` but IIRC the decision was that we shouldn't unseal `Value` until we've thought more about how to record composite types?
