### ISSUE TITLE
trace: Unable to import macros manually

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#968]
Currently, its not possible to import the `tokio-trace` macros like so:

```rust
use tokio_trace::{debug, info, span};
```

This is because it requires that `callsite` and `enabled` are imported as well. This is a pretty poor UX since as a user of `trace` they shouldn't have to know all the impl details for the macros.

**Comment by hawkw** [comment]
Thanks for pointing this out, that's definitely an issue. I believe this is what
```rust
#[macro_export(local_inner_macros)]
```
is intended for, but that feature doesn't seem to be very well documented. I'll look into seeing what I can do to resolve this.

**Comment by hawkw** [comment]
Ah, found it; it's documented [in the edition guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros). I'll go ahead and fix this!

**Comment by hawkw** [comment]
@LucioFranco I believe #969 should fix this --- mind confirming?
