### ISSUE TITLE
tokio-trace-core::span::Id should not accept zero values.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio#972]
This enables the non-zero layout optimization: https://doc.rust-lang.org/core/num/struct.NonZeroU64.html

**Comment by hawkw** [comment]
This does have the potential downside that schemes which use span `Id`s as indices into an array will have to special case index 0 (either by not using it or by subtracting 1 from all `Id`s before indexing with them). Not sure if this matters...

**Comment by hawkw** [comment]
@carllerche It seems like we can't do this while complying with `tokio`'s current minimum version --- `NonZeroU64` wasn't stabilized until Rust 1.28.0, and we're currently requiring a minimum version of 1.26.0.

**Comment by carllerche** [comment]
@hawkw we can at least assert for now and leave it as a TODO.

**Comment by hawkw** [comment]
@carllerche yup, already did:  #973

Should we leave this ticket open to track that, or should that PR close it?

**Comment by carllerche** [comment]
No, not super important. Either someone will notice it in profiles in the future or come across the TODO.
