### ISSUE TITLE
trace-core: Reintroduce callsite classification in Metadata

### ISSUE THREAD

**Issue by LucioFranco** [tokio-rs/tokio#986]
To ease the implementation of `Subscriber::register_callsite` a field should be added to `Metadata` to indicate if this callsite is an `event` or a `span`.

cc @hawkw

**Comment by hawkw** [comment]
Yeah, I think this is probably the right thing. A convention based on event naming (currently all the events generated by `tokio-trace` have names beginning with "event at ...") is also an option, but seems flakier than explicitly stating it in the metadata.

This will mean adding another parameter to the `metadata!` macros, and methods on `Metadata` that returns the value of the new field, as well.

**Comment by hawkw** [comment]
![PRs_welcome](https://user-images.githubusercontent.com/2796466/54454967-e8f98f80-4717-11e9-9372-1d8f79d6d144.jpg)
